### ISSUE TITLE
Elements of the graphic interface located on the very right side of the screen are not usable

### ISSUE THREAD

**Issue by NicolasBedon** [ubports/ubuntu-touch#1008]
### Illustrations

- Device: Nexus 4 (mako)
- Channel: rc6 stable
- Build: 20181126-12599 (UBports Image part)
OTA 6, Ubuntu 16.04 LTS -armhf

### Steps to reproduce
Many features on the very right side of the screen are not working properly.
A few examples: 
- I am unable to send a email via Dekko 2, since the 'send' button is located on the upper right corner of the screen.
- I am unable to register a new alarm in the clock application, since the '+' button is located on the upper right corner of the screen
- Many switches of the system configuration are difficult to use: I need to tap them quickly several times to turn them on/off
- I am unable to use the 'back' touch of the virtual keyboard on many applications (for example, the 'terminal' application

A few examples for easy reproduction:
- open the 'terminal' application, start to enter the password, and to correct it using the 'back' button of the virtual keyboard: the 'back' button has no effect
- open the 'clock' application, and try to add an alarm: the '+' button located on the upper right corner has no effect when clicking on it. 

### Expected behavior
Elements of the graphical interface of applications located on the right side should be usable.

### Actual behavior
Depending on the application, they are not usable at all, or very hard to use.

**Comment by aretzlaff** [comment]
I am unable to confirm this (Device: OnePlus Bacon; Channel: Development; Build: 2018-12-19).

**Comment by NicolasBedon** [comment]
Well, I can't even send an SMS, since the 'sent' key is on the right 
side of the screen.

I have noticed also that the only key that does not work on the virtual 
(french) keyboard is 'back'. The others on the very right side on the 
screen work fine.

**Comment by UniversalSuperBox** [comment]
It is possible for a section of a touch screen to fail, as you seem to be experiencing. Try downloading [Finger Painting](https://open-store.io/app/finger-painting.bhdouglass) from the openstore to make sure your entire screen is functional.

**Comment by NicolasBedon** [comment]
Thanks for the pointer. Painting with Finger Painting shows that the 
~1cm column at the very right of the screen seems to be insensitive. But 
this is not consistent with other tests. For example, I can use the 
system menu (the one which is scrolling for the top) normally: I can top 
of any of those buttons on the right side (eg cellular data, wifi, 
silent mode, battery settings, bluetooth activation, etc). So this does 
not seem to be a hardware problem to me.

**Comment by UniversalSuperBox** [comment]
Can you post a screenshot which shows the area which is insensitive? It's possible that the area overlaps the switches but there is still some area available where you can touch.

**Comment by UniversalSuperBox** [comment]
Also, are you able to use controls at the *bottom* of the screen if you turn it clockwise ninety degrees? Or at the top of the screen if you turn it counterclockwise ninety degrees?

**Comment by NicolasBedon** [comment]
Screenshot is in attachment.

As you can see, the column on the right is blank (with one small 
vertical line at the extreme right). What you can not see is that when I 
scroll down the system menu from the top, the blank area seems to match 
exactly the switches area of the system menu (that I can use !). It 
seems to me that I can use the switches of the system menu (black 
background) normally, but not on other menus (white background).

As you noticed, the switches area overlaps the "insensitive" area.

**Comment by NicolasBedon** [comment]
When the screen is rotated 90° clockwise:
- I am not able to use controls at the bottom of the screen
- top of the screen is OK
- launching terminal and using the virtual keyboard to enter a password, 
I am this time able to use the back key, but all the keys at the bottom 
are not working.

As a conclusion, it seems that the insensitive hardware area when the 
screen has normal orientation remains insensitive when the screen is 
rotated (exactly like it would be on an hardware malfunction).

**Comment by NicolasBedon** [comment]
OK, this is a confirmed hardware malfunction. Sorry guys for the bug 
report, and thanks for the help !
