### ISSUE TITLE
Ongoing call not shown

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#1019]
- Device: Nexus 5/hammerhead
- Channel: devel
- Build: 16.04, 2018-12-22/2

### Steps to reproduce
- Receive call while device is locked
- Turn up the volume (this is the only thing that happened differently this time)
- Tap the notification bubble to show the slider
- Answer the call by swiping on the notification bubble

### Expected behavior
Device shows the ongoing-call screen with call time and appropriate buttons.

### Actual behavior
The device remained locked and after unlocking, the phone app was at its normal screen with the keypad rather than showing information about the ongoing call. The result was that I couldn't hang up the call myself.

### Logfiles and additional information
Not the same as #195 as it's not about a button not responding to input.

I've only experienced this once despite having received multiple calls without experiencing this issue. As mentioned above, the only thing went differently compared to the other calls was that I turned up the volume and tapped the notification bubble to make the slider visible again (after changing the volume, the notification bubble collapsed, hiding the slider) before answering the call.

Upon trying to reproduce this using the steps above (I called myself using the same phone that called me the first time), the notification bubble did not collapse upon changing the volume and I didn't experience this same behavior. However, after hanging up the call from the calling phone, the device restarted (this is probably a completely separate issue, but I mention it for completeness).

On the second attempt at reproduction, the notification bubble *did* collapse but there was no ringing sound, despite the volume bar being mostly full. However, I again did not experience the issue of not having access to the ongoing-call screen. Additionally, the device didn't restart upon hanging up from the calling device.

**Comment by lduboeuf** [comment]
@Arc676  does it still occurs ?

**Comment by Arc676** [comment]
Unfortunately I don't currently have a SIM card for my Nexus 5, as I don't use it as my primary device, so I can't test this. Since no one else has reported similar behavior in over two years, I believe it would be appropriate to assume that the bug is either not reproducible or has already been fixed in some update between now and then. If I manage to reproduce this in the future, I'll ask to reopen the issue, but I'll close it for now since no one else seems to have experienced this problem.
