### ISSUE TITLE
No audio when connected to bluetooth car kit (Volvo My Car)

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#102]
Bacon on 15.04/devel r25

After some hassle, I finally managed to connect my OPO to my Volvo's bluetooth system. Problems in the connection process included that the phone said "Not discoverable" a number of times with bluetooth enabled. When "discoverable", Volvo My Car still could not discover the phone, so I had to go the other way having my OPO search for the Volvo kit. That worked, but pairing was really wonky. I discovered after a while that my Pebble watch bluetooth connection may have interfered with the process.

Finally, I managed to pair OPO to the car kit and I was able to initiate and terminate calls via the car kit. Initiating a call from the phone also showed fine in the car kit display. However, in both cases there was no audio routed through the car speakers. Switching to loudspeaker on the phone confirmed that the sound of the call was actually working, but switching back again audio was muted.

I only tried this with the voice message service, so I can't tell if the other end could hear me.

**Comment by tomoqv** [comment]
For info, call audio works when connected to a JBL Go external speaker.

**Comment by Flohack74** [comment]
Can you re-test now that I added some missing configs to the image?

**Comment by tomoqv** [comment]
@Flohack74 
I am back to my OPO now with the latest devel build. Connected it to the car kit in a brand new Skoda, but there was no sound at all through bluetooth.

**Comment by UniversalSuperBox** [comment]
The new "version" of the issue has been re-reported as #994.
