### ISSUE TITLE
SMS writing area above (hidden) OSK is not responding in many cases.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1023]
Description of the feature
SMS writing area, under the conversation, is sometimes not accesible. I feel it is after clicking on the notification selection.

- Device: Nexus 4
- Channel: stable OTA-6
- Build: 20181126

Steps to reproduce
When I receive a sms it appear into the notification panel.
By clicking on that shortcut, the sms conversation appear but the sms writing area is disabled.

Expected behavior
SMS writing area accesible whatever how I access to the sms conversation

Actual behavior
I have to go one step back by clicking on the arrow on the top-left corner, then open again the conversation.
Anyway, the notification icon is still green, like if it is still new. Doing that back and forth operation "solve" the problem.

**Comment by Thieb67k** [comment]
Still the same with mako and OTA-7.

**Comment by james-lyon** [comment]
I have the same issue with krillin and OTA-7 (also in previous releases).

My device is dual SIM, my workaround is to switch between SIMs and the text input area becomes accessible. 

I can't reliably reproduce the problem every time.

**Comment by lduboeuf** [comment]
@Thieb67k still having that issue ?

**Comment by Thieb67k** [comment]
No.
I feel it is time to do the Osterputz within the opened issues. :)

**Comment by lduboeuf** [comment]
:+1:
