### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by Gabriele69** [ubports/ubuntu-touch#1024]
### Description of the feature

upper bar And home circle, display wrong time
### Illustrations

see pictures

- Device: BQ 4.5
- Channel:RC
- Build: 2018-W01

### Steps to reproduce

Anything. Just turn on the phone

### Expected behavior

The top bar and circle should show the same time as the clock application (appropriate to the correct time zone)

### Actual behavior

The top bar and the circle show the UTC time, while the "clock" application is automatically corrected with the time zone

### Logfiles and additional information

I do not know the code, but I think the flaw is determined by the consideration or not of the time zone correction in the management of the clock and the indications of the upper bar. I am in Italy and - therefore - compared to UTC are at + 1 hour.
While the "clock" application takes into account the time zone correction, the top bar and the circle of the main screen, do not take into account indicating an hour less

**Comment by Gabriele69** [comment]
![screenshot20190110_072843120](https://user-images.githubusercontent.com/17642335/50951839-e1ff9800-14ae-11e9-86d8-8c7e58689aa0.png)
![screenshot20190110_072833150](https://user-images.githubusercontent.com/17642335/50951840-e2982e80-14ae-11e9-84df-2d6cb4c185eb.png)

**Comment by Gabriele69** [comment]
I specified that the "true" time was that shown by the "clock" application (7.28 am) and not the one shown by the circle and the upper bar (6.28 am).

**Comment by Gabriele69** [comment]
I restarted the phone and - now - it seems to work all regularly .... It is certainly a strange thing ...

**Comment by Flohack74** [comment]
When the time is off by so many years then maybe NTP sync will fail. Its too much difference for automatic correction maybe ;)

**Comment by Thieb67k** [comment]
@Flohack74 ,
How can I fix it? (If possible).
I can uptdate my last post by adding that happens with OTA-7,8 and 9.
I feel that the device turn off itself, then when I boot it --> 1 January 1970...

**Comment by dobey** [comment]
> @Flohack74 ,
> How can I fix it? (If possible).
> I can uptdate my last post by adding that happens with OTA-7,8 and 9.
> I feel that the device turn off itself, then when I boot it --> 1 January 1970...

Set the time to something close to the current time manually, and then switch back to automatic. If the device always keeps getting reset to 1970, then perhaps there is a hardware or similar issue

**Comment by dark-eye** [comment]
Anyone knows why this issue was closed?
