### ISSUE TITLE
Nexus 5 4g missing in UK network (o2)

### ISSUE THREAD

**Issue by prpldvl67** [ubports/ubuntu-touch#1025]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Can you confirm that you have an APN for `LTE` selected and its settings are correct? On my Nexus 5 I need to create three APNs -- one for LTE, one for Internet, and one for MMS.

**Comment by UniversalSuperBox** [comment]
Needed information was not provided
