### ISSUE TITLE
(Security) Feature Request: Ability to turn off sending SMS from notification while screen locked

### ISSUE THREAD

**Issue by ghost** [ubports/ubuntu-touch#1026]
### Description of the feature
The ability to turn off the functionality to send SMS from the notification while device is locked
AND 
the ability to turn off displaying the content of the body of an SMS message in the notification while device is locked

Consider the following: 
1) Someone has stolen your device and wallet
2) You have an SMS notification from "Wife" 
3) Thief sends one of the following messages to "Wife"
- What was the bank account password again?
- What was the ATM PIN again?
- What is the entry code to the house again?

Along a similar line, having the ability to turn off the preview of the body of an SMS (while keeping the sender info) in the notification, would stop certain types of attacks. Many services offer password reset links/codes and 2-factor authentication codes via SMS, which would be readily accessible to anyone holding your device.

Most users probably want to see the notifications, but it would be nice to be able to turn it off for the paranoid. I use a SIM PIN that I have to enter on startup, so a thief cannot take the SIM out and put it in another device to receive the 2FA codes or password reset links. You can't even launch the camera (which is decidedly not a security issue) while the device is locked, so it seems like a strange feature.

There is also the chance that this is already a feature and I just haven't found it yet!

**Comment by dobey** [comment]
You can disable access to the notifications menu and launcher while screen is locked, in system settings privacy panel. The pop-up notification will still appear with image/text, but you will not be able to reply directly from the notifications menu any longer while the screen is locked.

Also, if the launcher is _not_ disabled on lock screen, and Camera app is pinned to the launcher, you can launch the camera from the lock screen, but it will require you to unlock the screen before you can use the camera.

**Comment by hummlbach** [comment]
But notification settings for the messaging app as we have it for instant messaging apps, calendar etc is indeed missing for the messaging app...(?)

**Comment by dobey** [comment]
> But notification settings for the messaging app as we have it for instant messaging apps, calendar etc is indeed missing for the messaging app...(?) (in order to disable bubble notifications in his case)

But IIRC you cannot "quick reply" from the pop-up bubble, only the messaging menu.

**Comment by Flohack74** [comment]
I close this for now. Turning off access to the indicator menu should be enough for the moment. The OP has also left Github, so we cannot discuss this further with him. We could consider hiding details of messages in the bubble in this mode somehow. But I dont consider this a high priority.

**Comment by gzqx** [comment]
> But notification settings for the messaging app as we have it for instant messaging apps, calendar etc is indeed missing for the messaging app...(?) (in order to disable bubble notifications in his case)

I believe the setting for messaging app is still missing. Any plan for this at the moment?

**Comment by lduboeuf** [comment]
> > But notification settings for the messaging app as we have it for instant messaging apps, calendar etc is indeed missing for the messaging app...(?) (in order to disable bubble notifications in his case)
> 
> I believe the setting for messaging app is still missing. Any plan for this at the moment?

good point and i rhink this feature request is valid. Better recreate an issue
