### ISSUE TITLE
[xenial] Replace Oxide with another browser backend

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#103]
Since Oxide is no longer maintained by Canonical, it is necessary to replace it, possibly with [QtWebEngine](https://wiki.qt.io/QtWebEngine).

**Comment by altpapier** [comment]
will the new implementation allow greasemonkey style userscripts for a QML webview as described in http://daker.me/2014/05/how-to-use-oxide-in-your-ubuntu-qml-application.html
I found this quite useful

**Comment by altpapier** [comment]
Ok found the answer: https://doc-snapshots.qt.io/qt5-dev/qml-qtwebengine-webenginescript.html

**Comment by NeoTheThird** [comment]
Moved to https://github.com/ubports/unity8/issues/13
