### ISSUE TITLE
USB connection: phone get charge but phone not visible from the computer.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1032]
Description of the feature
Ubuntu touch phone is not recognized when connected to a windows computer (yet with Linux -Ubuntu- computer, that is fine).

- Device: LG Nexus 4 (mako)
- Channel: Stable, OTA-7
- Build: 20181231

Steps to reproduce
Connect the phone to Windows (7, 8.1) via USB

Expected behavior
to detect the phone and associated files/folders

Actual behavior
no detection. I have to use my ubuntu laptop (and only that one)

**Comment by dobey** [comment]
I think Windows 7 and 8.1 do not support MTP by default. You need to install MTP drivers in Windows to be able to use the same phone with Android via USB on Windows too.

**Comment by Flohack74** [comment]
Its not a problem for me. Windows 7 and up should have MTP by default. But I only have OPO, N5, FP2, E5, E4.5 and its working on all of them :)

**Comment by Thieb67k** [comment]
My laptop (Ubuntu as well) does not recognize my ubuntu touch mobile.
But that is fine with my desktop computer with Ubuntu....

**Comment by Wend1go** [comment]
Did you swipe-unlock the screen after connecting the phone to the pc?

**Comment by dobey** [comment]
Are you certain the USB cable supports data transfer, and isn't a charge-only cable. Does your phone show up in device manager at all?

**Comment by Flohack74** [comment]
E.g.:
![image](https://user-images.githubusercontent.com/16186470/53092564-606f4100-3515-11e9-9996-3446ad223d57.png)

**Comment by Flohack74** [comment]
Swipe-unlock is not necessary for the initial detection btw, only when you want to see the actual files. Otherwise an empty phone folder would be presented.

**Comment by Thieb67k** [comment]
Problem solved, my USB cable was bad. It was working but not for long time...
