### ISSUE TITLE
Inconsistency with version number reporting on phones

### ISSUE THREAD

**Issue by paul-hammant** [ubports/ubuntu-touch#1034]
On my Meizu Pro 5, it appears that I have installed `247` (as seen in "updates"). I'm not sure what that version maps to in terms of `OTA-n` numbering.  My about page, is similarly non informative:

![img_7435](https://user-images.githubusercontent.com/82182/51187921-ca704700-18d4-11e9-88f0-580560b9ba4f.png)

**Comment by UniversalSuperBox** [comment]
Hello Paul,

The version numbering found on the Updates screen corresponds to the build number of an image, which will go up by one every time there is any update.

The information you're looking for is listed next to "OS" in the About page, for you it is `Ubuntu 16.04 (2019-01-14). This is called the build tag, and its format is different for every channel:

* Daily `devel` builds receive a tag of the format `(YYYY-MM-DD)`
* Weekly `rc` builds receive a tag of the format `(2018-Wnn)`, where `nn` is the current ISO 8601 week number
* `stable` builds are tagged with their release number, such as `(OTA-7)`.

It appears that you are using Ubuntu Touch from the `devel` channel, which does not have the friendly release number tags like `OTA-7`. If you would like to switch to the `stable` channel, you can do so from "System Settings -> Updates -> Update settings -> Channels". Once you select a different channel, you should receive an update which will bring you to the newest release in that channel.

I'm not sure what it would take to display the build tags on the updates page, but I'll mark this as an Enhancement request and we'll see if someone comes through with an idea.

**Comment by paul-hammant** [comment]
Good too know, and thanks a bunch for the detailed reply instead of the insta-close :)

Maybe (2019-01-14) could be expanded to (2019-01-14; UbPorts 'devel' channel)? 

Maybe even a link to something back in GitHub-land. GH "Releases" would be the usual thing, but there's 0 here - https://github.com/ubports/ubuntu-touch/releases

**Comment by paul-hammant** [comment]
Updates says 353 now, and the About page is the same as snapped above, but with "2019-01-30" for the date.

**Comment by paul-hammant** [comment]
Still the same with the ambiguous '415' in the 'updates' page/tab/app.

**Comment by Flohack74** [comment]
Please do not consider the number alone as any identifier to a certain release. Its just a "counter" which pipeline build that was. And it can perfectly happen that due to some reasons we would retrigger the pipeline for all or just one device at certain times, and then this number will increase.

So rather reference to tis number, use only what Dalton explained above: On devel and RC channels this will not show an OTA number (as those releases are not the "real" OTA as for stable). Devel and RC are mainly for testing and early birds, so we do not need to make it more user-friendly, users of those channels know what they are looking at. The column for information is kinda narrow, and adding more stuff there makes it just tight and hard to comprehend IMHO.

**Comment by Flohack74** [comment]
And we are not using Github for releasing our stuff, so releases will always be empty. Sorry for that, but Github cannot build our complex setup. Maybe Gitlab could do it one day, who knows. Also there is not a single Release per se, but instead each device has its own release pipeline.

**Comment by paul-hammant** [comment]
I'm not talking about GitHub releases. I'm exclusively talking about Ubports' Ub-Touch as installed on my Meizu pro 5 and the version strings in use there.

**Comment by Flohack74** [comment]
I know what you are talking about. You mentioned 

> Maybe even a link to something back in GitHub-land. GH "Releases" would be the usual thing, but there's 0 here - https://github.com/ubports/ubuntu-touch/releases

So i wanted to clarify that there will always be 0 releases.

So we are not going to change the behaviour for this strings for the time being, as this is aligned with our CI infrastructure and makes sense with how we release images in the various channels.
