### ISSUE TITLE
FP2 Camera Flash

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#1047]
- Device: FP2
- Channel: RC
- Build: 2019-W07

### Steps to reproduce
Reloaded and tried again

### Expected behavior
Flash to work in low light

### Actual behavior
Flash does not work. 

### Logfiles and additional information
Flashlight doesn't work.
can't see anything related to camera in Logviewer

**Comment by UniversalSuperBox** [comment]
Hello @Dave1152000,

This issue has been reported as https://github.com/ubports/ubuntu-touch/issues/448, "Flashlight does not work". This is an issue affecting all Fairphone 2 devices with the 2nd generation camera module. I'll close this issue so it can be tracked in one place. :)
