### ISSUE TITLE
Feature Request: Full screen incoming call notification

### ISSUE THREAD

**Issue by liquidlemur** [ubports/ubuntu-touch#1048]
I would like to see a full screen notification of incoming calls, with the slider to answer or reject at the bottom of the screen. Additionally, the contact's / caller's picture (if available) should be displayed as well. Along with the number below their picture.

**Comment by cibersheep** [comment]
Thank you for the petition.
In our [design guidelines](https://gitlab.com/ubports/teams/ux-des/ubuntu-touch-human-interface-guidelines---hib/wikis/home) (still in progress) we discourage the app use of fullscreen (some exceptions are some games) and we want to prevent notifications to block the user work, at least in core apps.
Therefore, this petition goes out of the scope of the core app, but think that the UBports is not a product you consume, is a project you contribute to, meaning if you want to implement that feature you are more than welcome to do so.

**Comment by UniversalSuperBox** [comment]
I'll close this issue for now, if a solution can be provided that meets our design guidelines and is generally accepted by the community then we can reconsider.

**Comment by PhoenixLandPirate** [comment]
If this ever does get implemented, can we please consider having an option in the settings to switch between full screen and normal notifications for calls?

I can see why people like and see a big advantage in full screen phone calls, however, I find it much more peaceful, and have really enjoyed calls being the normal notification size.
