### ISSUE TITLE
Volume control has no effect on audio level during phone call

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#105]
Bacon 15.04/devel r27

The volume buttons or audio control in the indicator bar have no effect at all on the audio level during a phone call when a wired headset is connected. The volume indicator bar moves as expected, but the audio level stays the same.

It works playing a song from Cutespotify though.

**Comment by siucdude** [comment]
Same thing on Speakphone during a call..

**Comment by NeoTheThird** [comment]
Yep, i can confirm it.

**Comment by fabianHAW** [comment]
same here on ut 15.04 r3. any suggestions? just tried it with uVolMan, but there is no option to change it..

**Comment by Flohack74** [comment]
Hi Guys,
just wanted to update that there is finally a progress on this issue: We have a manual fix in place now, that´s being tested by me. The issues relates to adding and linking a few missing files to the device files build tree, and then compiling it into a new system image. So it´s nothing critical

As we are not planning to release an OTA for 15.04, this fix will be rolled out to a general public audience automatically only with upcoming 16.04 releases.

However, I will try to do my best to describe a hotfix in the forum´s support section, so that you can benefit from this also in 15.04

**Comment by Flohack74** [comment]
@rubencarneiro from daily use I can see that your fix improved the volume control a bit. But now the issue is that by changing the volume during call it also changes the volume of the loudspeaker, making my ringtone softer or louder all the time. Somehow this is coupled together...

**Comment by NeoTheThird** [comment]
@Flohack74 Do you think you'll get a chance to work on this? If not, i'd suggest to push it to the next milestone...

**Comment by Flohack74** [comment]
I am not sure, can take a look to determine how much work it is. Need to ping Ruben to see what he did in fact.

**Comment by tomoqv** [comment]
This appears to be a bug on Pro 5 with xenial as well.

**Comment by Flohack74** [comment]
I finally got an idea how to solve this. Lemme try to get it into a test image...

**Comment by Flohack74** [comment]
There is a potential fix in latest devel, can you test maybe :) - 1 or 2 of you?

**Comment by NeoTheThird** [comment]
Only tested on the FP2 and it doesn't work, do you want this issue to be tagged FP2 as well, or do you want a separate issue for that @Flohack74 ?

**Comment by NeoTheThird** [comment]
The Nexus 5 is probably also affected, since it has audioflingerglue as well, if someone could test that?

**Comment by UniversalSuperBox** [comment]
I connected a wireless headset to my Nexus 5 and answered a call. The volume control rocker changed the volume of the call for my side. Seems like this does not affect the Nexus 5.

I did the same with the FP2 as well. Volume control worked as expected there, but I did need to detach and reattach the headset before the output switched from the earpiece to the headset.

**Comment by Flohack74** [comment]
Please make a new issue about any other discoveries. We had this issue about the OPO missing acdbdata and mixer_paths.xml which has been resolved and which seems to have the intended resolution. While not perfect, the volume is now changeable (the change steps are to shallow atm IMHO). But its much better than before.

**Comment by WillemHexspoor** [comment]
Device: Nexus 4
image: 2018-W48
Volume slider during phone call with headset only works properly between roughly 60 and 100%. This means the volume changes according the position of the slider. Below around 60% the slider can be moved to zero but the volume does not decrease accordingly. Also at zero percent there is still sound audible from the other side although the headphone icon above the slider is striked through

**Comment by Flohack74** [comment]
Please: Make a new bug if a bug has been closed AND its not for your device...
