### ISSUE TITLE
it wont load 

### ISSUE THREAD

**Issue by Dragontis** [ubports/ubuntu-touch#1050]
### Illustrations

- Device:
- Channel:
- Build:

### Steps to reproduce

trying to install Ubuntu touch got stuck on waiting  for device to enter reovery mode; it was in recovery mode for hours

### Actual behavior

just froze there
### Logfiles and additional information

1.

**Comment by UniversalSuperBox** [comment]
Hello @Dragontis,

We handle support for installation of Ubuntu Touch in a few places:

* The Forum, https://forums.ubports.com, in the support section
* @WelcomePlus on Telegram
* #ubports:matrix.org on Matrix

Please come to one of these places and describe your problem, including the device you're trying to install on and the platform you're installing from. A volunteer should be able to help you install Ubuntu Touch.
