### ISSUE TITLE
Edge channel not bootable on Meizu MX4 arale

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#1052]
- Device: arale
- Channel: edge
- Build: 24+

### Steps to reproduce
Flash edge channel revision 24 or newer on Meizu MX4 arale. The device becomes not bootable, stuck on boot logo forever.

Proceed with any of the bellow commands to break your phone:
- `system-image-cli --switch ubports-touch/16.04/edge --progress dots`
- `ubuntu-device-flash --server=http://system-image.ubports.com touch --device=arale --channel=ubports-touch/16.04/edge`

While this still makes the phone bootable:
- `system-image-cli --switch ubports-touch/16.04/edge --progress dots -r 23`

### Expected behavior
Phone boots normally.

### Actual behavior
Phone is stuck on boot logo.

### Additional information
The new Mir stack seems not to work on MX4 and is crashing `Process 2794 terminated with signal 11`. The device is not bootable and is stuck on boot logo.

**Comment by zubozrout** [comment]
I can unfortunately still confirm the latest image (2019-03-12, r35) is broken and no miracle happened in the meantime. Sadly I have no idea what changed in between r22 and r23 and am not even sure how to investigate.

**Comment by zubozrout** [comment]
Well, apparently this is related to Mir after all since rev 23 is bootable (not sure why I was not able to boot it up before). The bellow logs indicate Mir is crashing on MX4.

[lightdm.log](https://github.com/ubports/ubuntu-touch/files/2999799/lightdm.log)
[unity-system-compositor.log](https://github.com/ubports/ubuntu-touch/files/2999800/unity-system-compositor.log)

**Comment by fredldotme** [comment]
With the hybris hack merged the only remaining issue is:
https://github.com/ubports/ubuntu-touch-session/issues/6

which can be fixed by reverting the offending change referenced in the linked GitHub issue.

**Comment by zubozrout** [comment]
@fredldotme Thank you very much. The edge now seems to work correctly on arale :).

Can we close this now?

**Comment by fredldotme** [comment]
@zubozrout I‘d say so. Thanks! :)

**Comment by NeoTheThird** [comment]
Good job!
