### ISSUE TITLE
[edge] Scrolling doesn't have any momentum

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#1054]
- Device: BQ E4.5 (krillin)
- Channel: edge
- Build: Ubuntu 16.04 (2019-02-23)

### Steps to reproduce
Scroll on any screen

### Expected behavior
Fluid scrolling movement

### Actual behavior
Scrolling doesn't have any momentum

### Additional information
There's a related old issue [0] that was closed by @mariogrip [1] with a provisional workaround [2].

[0] https://github.com/ubports/ubuntu-touch/issues/615
[1] https://github.com/ubports/ubuntu-touch/issues/615#issuecomment-406902155
[2] https://github.com/ubports/ubuntu-touch/issues/787

**Comment by mariogrip** [comment]
Should be fixed by https://github.com/ubports/qtmir/pull/20

**Comment by UniversalSuperBox** [comment]
Seems to be fixed in today's build of edge.

**Comment by advocatux** [comment]
@UniversalSuperBox not for me in krillin - 16.04 (2019-02-24), that's why I didn't close this issue, or do you mean that it's fixed in the build that's going to be published tomorrow?

**Comment by UniversalSuperBox** [comment]
I mean the one that's currently out. I definitely have momentum on the Fairphone 2, Oneplus One, and Nexus 7. Is there a certain app that's having trouble?

**Comment by advocatux** [comment]
Most of the apps that I've tried have this problem. See for example System Settings, OpenStore or Gallery.

I can't see anything relevant in `unity8.log`. Is there any other log of interest?
