### ISSUE TITLE
SIM card not detected after Libertine big bug.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1055]
After a Libertine's bug, SIM cards were not detected. 

- Device: Nexus 4 mako OTA-7
- Channel: Stable

### Steps to reproduce
My Libertine manager contained Firefox and Libreoffice. I was uninstalling Fifefox.
Everything disapear after a while.

### Actual behavior
I had to reinitiate the phone!

**Comment by UniversalSuperBox** [comment]
If you try to do the same steps again, does the same problem occur?

**Comment by Thieb67k** [comment]
Honestly, it is my main phone, hence I do not want to trigger a crash that needs a phone's reset.
I prefer to avoid the problem.
I never had that problem before and it occurred just after Libertine crash.
Now, after a reset, it is back to a normal operation.

**Comment by UniversalSuperBox** [comment]
I'm afraid we don't have enough information to fix this issue... If you ever run into it again, please feel free to leave a comment and we can reopen!
