### ISSUE TITLE
Drawer does not refresh apps

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1058]
In Unity8 on Edge, the app Drawer is used to launch apps rather than the App Scope. Currently, the Drawer does not refresh when an app is installed or removed and stays in an invalid state. There is also no UI interaction to refresh the Drawer (such as pulling down and releasing).

The Drawer should refresh automatically when apps are installed or removed.

**Comment by NeoTheThird** [comment]
So the issue here is that the drawer listens to the signals of the new ubuntu-app-launch, but we can't use that as-is, because it is closely integrated with systemd.
