### ISSUE TITLE
[Edge] - Mobile website

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1062]
- Device:N5
- Channel: Edge
### Actual behavior
Website are not automatically scaled to mobile view.

Not sure if related to #1057

**Comment by ernesst** [comment]
The issue doesn't seems to be resolved on 2019-03-07 (only the power button is fixed, as they have been merge together i'm guessing I got the fix for 1062 too on the phone.)

**Comment by UniversalSuperBox** [comment]
I believe that #1057 is indeed related to this, we lost the ability to do auto-scaling. Now websites are getting the message that you're a mobile user, but your scale is still too low.
