### ISSUE TITLE
Upgrading Bacon to OTA-8 - Network & Performance Issues

### ISSUE THREAD

**Issue by prazeworks** [ubports/ubuntu-touch#1066]
- Device: Bacon
- Channel: Stable
- Build: OTA-8

### What happened

Upgraded OnePlus One from OTA-7 to OTA-8 via adb shell `sudo system-image-cli -v -p 0 --progress dots`

### Expected behavior
Access web pages and web apps

### Actual behavior
Morph Browser displays "Error: net::ERR_NETWORK_CHANGED"
Device is now running hot
Overall system is now now quite "laggy"
Access to OpenStore is possible
Able to download new podcasts in Podbird

### Logfiles and additional information

[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2940586/UTlogcat.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2940584/UTdmesg.txt)

**Comment by UniversalSuperBox** [comment]
Reading your log:

```
[  221.556924] init: anbox-container main process (19083) terminated with status 1
[  221.556957] init: anbox-container main process ended, respawning
```

Anbox must be reinstalled or removed after an update to your device. The kernel you have installed does not support Anbox.
