### ISSUE TITLE
[FP2] Unity restarts when alarm is triggered, alarm can't be stopped

### ISSUE THREAD

**Issue by Wend1go** [ubports/ubuntu-touch#1072]
After installing the OTA, existing alarms just ring for a fraction of a second and than vanish.
There is no popup to silence the alarm but it looks like the alarm is still running in the background since the battery is drained at about 20%/h. If you restart the phone after the alarm started the battery drain goes back to normal but occures again the next time the alarm is triggered.
This happens since at least OTA 7.

Workaround:
A workaround was posted in the forum a while ago. If you delete the alarm after installing the OTA and recreate it again, it works as normal.
(This seams to not work for me anymore since OTA8, recrated the alarm two times and the issue still occures)

- Device: FP2
- Channel: RC
- Build: OTA8

### Steps to reproduce
1) Create an alarm
2) Install the OTA via update manager
3) Wait for the alarm to trigger

### Expected behavior
Alarm plays, a popup with a button to stop the alarm appears.

### Actual behavior
The alarm can be heared for an instance and goes silent while staying active in the background. There is no popup to stop it. The battery drains quickly even with WiFi turned off.

### Logfiles and additional information
If someone would be so kind to tell me where to look, I can add a log file.

**Comment by Wend1go** [comment]
Today I woke up before the alarm and wanted to use the phone to see what time it is. Upon touching the power button, Unity restarted (not the whole phone, just Unity) and at the time the alarm started it worked as expected (it rang and I could stop the alarm via the popup dialog).

I have a theory now what could be happening:
The alarm gets triggered and wakes the phone from deep sleep which for whatever reason causes Unity to restart. 
After the restart, the alarm clock process is still active but Unity doesn't know about it anymore since it restarted and the alarm process keeps running until I reboot the whole phone.

**Comment by Flaburgan** [comment]
I have an alarm set since OTA-8 on my FP2 and it never made Unity crash. It rings as expected, and can be stopped when ringing. So... cannot reproduce from my side.

**Comment by Wend1go** [comment]
Issue is still present in OTA10 (RC).

(All hope lies in the Unity8 Upgrade)

**Comment by Wend1go** [comment]
Looks like Ubuntu touch Version 64 fixed it, probably by removing the scopes.
Closing this now.
