### ISSUE TITLE
Battery warning keeps popping up despite charging

### ISSUE THREAD

**Issue by franktopel** [ubports/ubuntu-touch#1074]
Version: OnePlus bacon, 16.04 (2019-W11)

When the battery drops to 5% or lower, a "low battery" warning pops up. If you then attach the device to a charger, the warning keeps popping up while the device is charging.

Expected behaviour: While the device is charging, no battery warnings show up.

**Comment by BlueKenny** [comment]
Same problem on my OnePlus One

**Comment by UniversalSuperBox** [comment]
Hmm, looks like the battery in my device is bad and skips from 2% to 12% while charging... so I'm not able to reproduce this.

Does the accompanying sound also play? Does the problem occur when you hit 5% and then again when you hit 15%? Can you discern any pattern at all?

**Comment by Flohack74** [comment]
Sorry cannot confirm this on my daily...

**Comment by pixelr0** [comment]
i can confirm here! it drives me nuts. i can see and hear the warning. it also wakes the screen.
fairphone2 - edge channel

**Comment by entomologe** [comment]
I can confirm this on oneplus one, OTA-13. It wakes up the screen when suspended; when one is on the phone one has to push the notification away before continuing. Which further information is needed? 

Is there some recommendation on charging specs (Ampere/Volt)? Is there some relevant information regarding this below /sys/class/power_supply? Which logs should I see and paste to narrow it down (e.g. repowerd.log)?

**Comment by Flohack74** [comment]
Can it be that your charging cable is bad and it restarts charging every now and then? As I said, I have never experienced this on my OPO or any other UT device in more than 3 years.

**Comment by entomologe** [comment]
> Can it be that your charging cable is bad and it restarts charging every now and then? As I said, I have never experienced this on my OPO or any other UT device in more than 3 years.

You were right. I had some issue with my (extending) USB cable. The reason of misattribution was the lack in notifications on other devices running android. So, thanks for hinting me towards the actual cause. =)
