### ISSUE TITLE
Edge images are too large to install on the Oneplus One

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1078]
Currently, edge images are too large. The Oneplus One in particular runs out of space while trying to install it, then falls into recovery. We must find a way to decrease the image's size.

**Comment by aretzlaff** [comment]
I can confirm it. It took me some time to figure out what happened.

**Comment by ahmadalsaady** [comment]
Can I try the edge build now or the problem still persist?

**Comment by Aury88** [comment]
Is it possible to have an image without some core-apps that at the first start, (so after a fresh installation) installs the remaining core-apps?

**Comment by UniversalSuperBox** [comment]
You know, we've discussed that possibility before. Unfortunately, it would only save about 42MB of space at this time.

**Comment by UniversalSuperBox** [comment]
Applied the fix for https://github.com/ubports/ubuntu-touch/issues/1112 to xenial_-_edge, and...

![screenshot20190426_160103454](https://user-images.githubusercontent.com/21966173/56836497-0d7b7800-683d-11e9-8ba9-58ebba3f5621.png)

We're back.
