### ISSUE TITLE
Add option to hide/unhide OSK when external keyboard is connected

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1079]
### Description of the feature
An option to hide/unhide the OSK when external keyboard is connected to th device.
The default behavior is to hide the OSK.

### Illustrations
A toggle in the Language & Text page in the settings app will suffice which will only show when an external keyboard is connected similar to the item for external keyboard layouts.
A toggle can also be added in the keyboard indicator for fast enabling/disabling.

### Justification
Currently, OSK is always hidden when an external keyboard is connected however, there are still cases where you'd want to use the OSK. This could also fix issues with some BT mouse that has extra keys which causes UT to also hide the OSK.

**Comment by dobey** [comment]
Isn't there a toggle for this already in `indicator-session` (the gear indicator at far right of indicators)? Granted it's not the best place for it, but this feature is already "there."

**Comment by kugiigi** [comment]
I think there's only desktop mode toggle there unless I missed something in the new Unity 8?

**Comment by dobey** [comment]
Oh, sorry, no. It's in `system-settings` already under `Language & Text` options, when an external keyboard is present.

**Comment by kugiigi** [comment]
Oh okay, it's indeed already in edge channel. Cool!
So now, I guess this request will be just for the indicator for an easy toggle :)

**Comment by mateosalta** [comment]
also in gsettings i think: gsettings set com.canonical.Unity8 always-show-osk true

**Comment by mateosalta** [comment]
related: https://github.com/ubports/ubuntu-touch/issues/367

**Comment by kugiigi** [comment]
Why is this still open? 😄
There's already a toggle to still show the OSK even with a connected physical keyboard. Either via the keyboard button in the login field or the toggle in the `Language & Text` page. Let's just close this an log a separate feature request to add the toggle in the keyboard indicator.
