### ISSUE TITLE
Cannot scroll drawer immediately after opening 

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1080]
### Steps to Reproduce
1. Swipe from the left edge to show the drawer
2. Immediately swipe up to scroll the list of apps

### Expected Results 
The list of paps scroll up.

### Actual Results 
The list doesn't scroll and sometimes just accidentally open an appeared depending on where you lift your finger.

### Additional Input
It seems that the drawer doesn't get focus automatically so you have to tap on its  surface  first before you  can scroll.

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/unity8/pull/114

**Comment by UniversalSuperBox** [comment]
I had to revert that commit. Turns out that when you don't let a `clicked` event through, you tend to break things that depend on it... like launching apps.

**Comment by UniversalSuperBox** [comment]
Fixed by ubports/unity8#116
