### ISSUE TITLE
Ubuntu button on launcher not functioning

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#1085]
### Illustrations

- Device: hammerhead
- Channel: devel
- Build:2019-03-28

### Steps to reproduce

Swipe from left edge. press ubuntu button at the bottom of launcher

### Expected behavior

goes to app scope
### Actual behavior

nothing happens

**Comment by UniversalSuperBox** [comment]
I can't confirm this. Does anything appear in `.cache/upstart/unity8.log` when you tap the button?

**Comment by Arc676** [comment]
Can't reproduce on `devel` 2019-03-29 either. Also hammerhead.

**Comment by userj** [comment]
Seems fixed in 2019-03-29.
I wonder how I got to that point, but it was like that for the whole day. Sorry no logs for that... I will update if it happens again.
