### ISSUE TITLE
Apps steals focus once opened

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1088]
## Steps to reproduce
1. Open an pp via the launcher or drawer
2. Immediately switch to an already open app.

## Expected Results
The currently opened and focused app should retain on focus.

## Actual Results
The new app opened from the launcher/drawer steals the focus and becomes the foreground app once it completes its startup.

## Additional Input
I think this behavior is kind of counter-productive since it takes away some of the user's multitasking scenarios. I also hate this behavior on windows when I am typing something and an app suddenly gets foregrounded getting all what I typed...and sometimes that's my password :D

**Comment by jonnius** [comment]
I can confirm the behavior. You can even try various times to switch to another app while one app is loading and it will always switch back immediately.

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/unity8/pull/176 and https://github.com/ubports/qtmir/pull/27
