### ISSUE TITLE
Ubports Fails to install on Nexus 7 2013

### ISSUE THREAD

**Issue by AndrewSChapman** [ubports/ubuntu-touch#1089]
- Device: Nexus 7 2013 Flo

FASTBOOT MODE
Product Name -Flo
Variant - flo 32G
HW Version - rev_e
Bootloader Version - FLO-04.05
Carrier Info - None
Signing - Yes
Secure Boot - Yes
Lock State - Unlocked

Host OS: Windows 10

### Steps to reproduce
fastboot oem unlock
fastboot format cache
fastboot reboot-bootloader

fastboot flash recovery recovery.img

adb shell "mount -a" # You might see some errors from this command, that's ok.
adb shell "mkdir -p /cache/recovery"
adb push pool/ubports-b2daf85c2a255a0affc93d808e709697e472777de4bc189dd9128211db551469.tar.xz /cache/recovery/
adb push pool/ubports-b2daf85c2a255a0affc93d808e709697e472777de4bc189dd9128211db551469.tar.xz.asc /cache/recovery/
adb push pool/device-1481ee5bb7d4443bbc1506c297bc19aecc0520a305dca7a3ef800c57969ac9f4.tar.xz /cache/recovery/
adb push pool/device-1481ee5bb7d4443bbc1506c297bc19aecc0520a305dca7a3ef800c57969ac9f4.tar.xz.asc /cache/recovery/
adb push pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz /cache/recovery/
adb push pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc /cache/recovery/
adb push pool/version-6.tar.xz /cache/recovery/
adb push pool/version-6.tar.xz.asc /cache/recovery/
adb push gpg/image-signing.tar.xz /cache/recovery/
adb push gpg/image-signing.tar.xz.asc /cache/recovery/
adb push gpg/image-master.tar.xz /cache/recovery/
adb push gpg/image-master.tar.xz.asc /cache/recovery/
adb push commandfile /cache/recovery/ubuntu_command

adb reboot recovery

### Expected behavior
UBports installs successfully.

### Actual behavior
Hi guys, I'm trying to get UBports running on my Nexus 7 however it's not working.  Firstly I tried the GUI app, which failed to detect my device at any point.

I then tried the manual version using adb and fastboot process as described above, and got as far as Ubuntu actually installing.  However, it showed the progress bar at about 50%, did nothing more, then after about a minute it just reboots to the Google logo and does nothing, and reboots again in a loop.  

If  I go back into Ubuntu recovery and wipe cache, and factory reset, the installer runs again, however it gets stuck in exactly the same loop over again.

I downloaded the files today using the latest instructions.

**Comment by Flohack74** [comment]
Please try to use the latest installer, according to other users this is now fixed.

**Comment by UniversalSuperBox** [comment]
My previous information was incorrect, and I'm sorry it took this long to get it fixed.

We have now adjusted the installer so it downloads the new boot and recovery images compiled with the patch mentioned in this post. Previously these images were getting used in the final Ubuntu Touch install, but weren't used for the install process. Now this has been fixed.

You should be able to install on your newer Nexus 7 2013's with the UBports Installer.
