### ISSUE TITLE
Remove Dash Background option from Settings

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#1090]
Without dash, we don't need dash backgrounds. We need to revert the changes done for #104.

**Comment by nfsprodriver** [comment]
Progress here, please test:
https://github.com/ubports/unity8/pull/125
https://github.com/ubports/system-settings/pull/137

**Comment by nfsprodriver** [comment]
Oh sorry, PRs are into wrong branch yet...

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/system-settings/pull/138
