### ISSUE TITLE
Lock-PIN entry pad stretching

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubuntu-touch#1091]
### Description of the bug

- Device: arale (MX4)
- Channel: edge
- Build: 16.04 (2019-04-08)

### Steps to reproduce
1) Start a rotated application or game (like PathWind)
2) Lock the screen
3) Unlock the screen

### Expected behavior
Properly scaled PIN entry pad

### Actual behavior
PIN entry pad is stretched beyond it's destined height with miscalculated touch input in both x and y directions

### Logfiles and additional information

![screenshot20190407_114948330](https://user-images.githubusercontent.com/722660/55751395-d851e600-5a45-11e9-9b74-9bb9cfbb2250.png)

**Comment by NeoTheThird** [comment]
I see similar behavior after locking the device for the first time after boot on cooler. Maybe related to #1063?

**Comment by fredldotme** [comment]
With fixes for orientation support applied this bug can now be triggered more often.

**Comment by dupplak** [comment]
I have the same issue on FP2.

**Comment by ernesst** [comment]
Same on N5

**Comment by advocatux** [comment]
I can confirm this issue on BQ E4.5 (krillin) too but it happens on more screens than just the lock-pin one.

BTW the temporal workaround is to re-rotate the device once again before locking it.

**Comment by gerboland** [comment]
I can offer advice on what to look for. (I'm running off memory here, so please double-check my assertions)

- OSK is a maximised or fullscreen surface (depending on if panel visible) that is on top most other app & shell surfaces, with a large transparent and input pass-through-ing chunk so the app underneath is visible and can be interacted with.

- OSK shows & hides itself, based on if foreground app needs it.

- rotation is managed like this: on device rotation from portrait to landscape, shell causes OSK surface to be resized (swapping the width & height). This causes OSK to re-render at new dimensions. Shell does trickery to animate the transition.

I'd guess from the screenshot that the width/height resize goes wrong occasionally.

To investigate, I'd monitor the ubuntu-keyboard looking for
- is it getting the correct resize events? Use `QT_LOGGING_RULES=qt.qpa.mirclient.*=true" to see what (this)[https://github.com/ubports/qtubuntu/blob/master/src/ubuntumirclient/qmirclientwindow.cpp#L702] prints
- compare with what (this)[https://github.com/ubports/qtubuntu/blob/master/src/ubuntumirclient/qmirclientwindow.cpp#L799] prints (should be shortly after)
- use console.log() to print changes to width/height in https://github.com/ubports/keyboard-component/blob/xenial/qml/Keyboard.qml#L70 - compare the QML values with those from the QPA.


As a pertinent note: the code in QtUbuntu to deal with Surface resizing is something I'd suspect, as it is inelegant. Code-path starts here: 
https://github.com/ubports/qtubuntu/blob/master/src/ubuntumirclient/qmirclientwindow.cpp#L694
Mir's resize events don't correspond to it giving a resized buffer next - it could be 1 or 2 buffers later that is the updated size. Only way we could be sure is to fetch the next buffer and check its size, and if that's not what we wanted, try fetching another. 

So what we did on getting resize event is trigger a render, which then causes us to fetch a new buffer. We check its size, and if a new size, we fire all the Qt signals to say resize has happened.  i.e. https://github.com/ubports/qtubuntu/blob/master/src/ubuntumirclient/qmirclientwindow.cpp#L783

It's a bit janky, it could be the cause. But you can verify if this is a suspect by comparing the resize numbers using the steps I gave above.

**Comment by mariogrip** [comment]
@gerboland Thanks for you help :)
