### ISSUE TITLE
External display does not work initially

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1094]
- Device: Nexus 5
- Channel: Edge
- Build: 16.04 (2019-04-10/2)

### Steps to reproduce
1. Connect the device to an external display i.e. Nexus 5 via slimport adapter

### Expected behavior
The device screen should become a virtual touchpad + OSK
The external display should display the Unity 8 shell.

### Actual behavior
The device screen stays the same and shows the Unity 8 shell and does NOT react to any touch.
The external display is blank.

### Additional Information
Restarting Unity 8 will make the external display work.

**Comment by Amooti73** [comment]
Also with Nexus 5 having edge channel, except that the external display does work with a display/TV having HDMI input.  I have been using both mouse and keyboard on bluetooth because the nexus screen, although it changes as if to become a touch pad, is inactive. Up until now, I have been unable to get any display to work using VGA input although I have a working adapter for HDMI to VGA.

I just moved to Edge yesterday and, so still testing.

**Comment by luksus42** [comment]
Same behavior on FP2 with wireless display connection.
- device and display are connected
- device screen is "frozen"
- extermal display is blank (on demand it shows the transmitted resolution of 1280x720@25fps, so something seems to be transmitted)

**Comment by NeoTheThird** [comment]
Unity8 actually crashes and restarts on my M10 HD when i hook it up via micro-hdmi. Here's a log: https://paste.ubuntu.com/p/tMPDS8QddD/

Do you want to track that separately @mariogrip?

**Comment by kugiigi** [comment]
> Same behavior on FP2 with wireless display connection.
> 
> * device and display are connected
> * device screen is "frozen"
> * extermal display is blank (on demand it shows the transmitted resolution of 1280x720@25fps, so something seems to be transmitted)
> 
> > Additional Information
> > Restarting Unity 8 will make the external display work.
> 
> How to do this, when device is not responding? via SSH?

A really late and unnecessary reply but I feel like I want to 😁 

Yes, SSH is an option but I usually just connect a bluetooth mouse before connecting to a monitor and I can navigate fine using the mouse and restart Unity 8 via UTTT.

**Comment by luksus42** [comment]
ah, thanks.
Hopefully this is not longer needed, as Dalton set it to "in progress" for OTA-12 :-)

**Comment by luksus42** [comment]
On FP2 and LG PF1500 Largo:

- phone does not freeze anymore
- external display does connect, but stays black
- after Unity8 restart, external display works and phone works as mouse/keyboard
- some resolution issues appear

![IMG_9867](https://user-images.githubusercontent.com/6659488/73141824-a1a69400-4088-11ea-8aa2-5665502e0537.JPG)
![IMG_9868](https://user-images.githubusercontent.com/6659488/73141825-a1a69400-4088-11ea-9a96-401d993dd68e.JPG)

**Comment by luksus42** [comment]
@UniversalSuperBox please remove "edge" label, since it is in dev/rc.
The only thing whats currently missing to make it work, is a Lomiri restart.

**Comment by UniversalSuperBox** [comment]
The still-outstanding PRs for this follow:

https://github.com/ubports/qtmir/pull/37
https://github.com/ubports/mir-android-platform/pull/19

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/qtmir/pull/48

**Comment by abkro** [comment]
Checked this on an N5 running RC 2020 W-14. 
Connecting to external screen now works. Mousepad is still unresponsive.

**Comment by Bolly** [comment]
Checked this on an BQM10FHD running RC 2020 W-14.
The mouse works, right and left buttons.
The keyboard is not displayed.

**Comment by Bolly** [comment]
Checked this on an BQM10FHD running RC 2020 W-15.
The mouse works, right and left buttons.
The keyboard is not displayed.

**Comment by Flohack74** [comment]
I am not sure if touch pad functionality etc are part of this bug request. So @kugiigi what do you expect that must in order to close this issue?

**Comment by kugiigi** [comment]
This is only for the external display issue so it's fine to be closed. Other issues with the touchpad and OSK can have separate issues. Actually I believe they are known or previously closed issues.
