### ISSUE TITLE
OSK is displayed in the external display

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1096]
- Device: Nexus 5
- Channel: Edge
- Build: 16.04 (2019-04-10/2)

### Steps to reproduce
1. Connect the device to an external display i.e. Nexus 5 via slimport adapter

### Expected behavior
The OSK is displayed on the device screen when an input is needed i.e. lock screen

### Actual behavior
The OSK is displayed in the external display

**Comment by luksus42** [comment]
Can't really confirm for RC, but I did not encounter this bug on the on devel as I testet externl-display over aethercast on FP2, two weeks ago.

**Comment by luksus42** [comment]
Just tested again with FP2 on RC (aethercast) -> Fix confirmed.
