### ISSUE TITLE
Install on NEXUS-10 (Manta) ?

### ISSUE THREAD

**Issue by ShalomElkin** [ubports/ubuntu-touch#1097]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Hello @ShalomElkin,

Supported devices can be found at https://devices.ubuntu-touch.io. If you would like to learn more about porting Ubuntu Touch to a new device, please see https://docs.ubports.com/en/latest/porting/introduction.html
