### ISSUE TITLE
Window surfaces disappearing from Spread

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubuntu-touch#1103]
- Device: MX4 (arale)
- Channel: edge
- Build: 2019-04-18

### Steps to reproduce
Enter the spread
Kill the foreground application

### Expected behavior
Spread closes

### Actual behavior
The last window surface buffer of the application stays on the Stage,
but is not interactable with in the Spread.

### Logfiles and additional information

https://cloudhome.beidl.guru/index.php/s/SMiGFifwYa2XApG

**Comment by kugiigi** [comment]
This seems to happen only when the app is killed by the system due to running out of memory. The app becomes an invisible component in the spread and also shows in the launcher even thought it's not really running anymore. Switching to it kills it for good.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/qtmir/pull/26
