### ISSUE TITLE
Import/export contacts via .vcf file

### ISSUE THREAD

**Issue by michaelothing** [ubports/ubuntu-touch#1105]
with most people wanting to get away from Google, one of the most basic functionalities for contacts since the time of flip phones to smart phones is importing via .vcf file. Modern phones rarely give the option to save to sim, so unless you have a caldav account users of microg are out of luck. please implement this into the contacts app.
-------- FEATURE-REQUEST -------------------

**Comment by UniversalSuperBox** [comment]
It is already possible to do this. You can press and hold on contacts, then press Share. Select the file manager app and a folder in your home directory, then press "Select". `ubuntu_contacts.vcf` will be saved.

You can also import VCF files by sharing them to the Contacts app, such as by tapping them in the file manager, tapping "Open with another app," and selecting Contacts.

**Comment by Danfro** [comment]
But don't we really - for user convenience - want to have a "import from vcf" in contacts app? Then via content hub allow selecting a file with filemanager.

I vote to reopen this issue and mark it as enhancement.

**Comment by Flohack74** [comment]
I agree it could be both active and passive feature.

**Comment by UniversalSuperBox** [comment]
Sure -- could you refile it on https://github.com/ubports/address-book-app?
