### ISSUE TITLE
Openstore API change is not implemented in system-settings

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1108]
- Device: bacon
- Channel: devel
- Build: 

### Steps to reproduce
* Open System Settings
* Open Updates subsection

### Expected behavior
App updates are displayed and can be executed.

### Actual behavior
App updates are not shown anymore.

**Comment by mardy** [comment]
I see this is marked as "in progress", but no one is assigned to the issue; if there isn't someone yet, I volunteer to work on this :-)

**Comment by Flohack74** [comment]
Dalton volunteered, but he might be happy if you take it. For the time being, we decided to just add a text telling users that App updates are now in the Openstore App only. It seems that we wanted to remove this feature already for some time, but now we got surprised.
Theoretically other store apps could pop up, and we should separate this from the core system. But its a bit opinion-based, too.

**Comment by UniversalSuperBox** [comment]
My only plan was to remove the visible click stuff now, then add a new button that took you to the OpenStore to get your updates. @bhdouglass has started working on making the update experience in the open-store better. While I feel that this is a much better thread to follow, I won't say no to a contribution.

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/system-settings/pull/151

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Tested this just before switching to rc channel and updates were not shown.
Now updates are shown and can be executed.

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc (2019-W18)
Works as expected
