### ISSUE TITLE
Cannot install libertine container on m10fhd

### ISSUE THREAD

**Issue by SanderKSmit** [ubports/ubuntu-touch#111]
I use the same commands that worked on my m10 with Ubuntu version of touch and on my fp2. Installation crashes with an error on x11

**Comment by Flohack74** [comment]
Please fix the title or the message: Are you installing on M10FHD or on FP2?

**Comment by SanderKSmit** [comment]
maybe my description was a bit confusing.
On ubports m10 imstalling libertine contaimer does not work. I installed libertine containers previously  with success on the ubuntu version of my m10 and later on the fp2. 
on the ubport version i can't.

**Comment by Flohack74** [comment]
Got it. But be patient probably this will be on hold until we can switch to 16.04.

**Comment by WLBI** [comment]
@Flohack74 
Is there any forecast, until when it will be changed to 16.04?
Canonical announced that already since more than one year.
Before I tried staging 16.04 with Unity 8 on my M10 FHD and it was really cool...

**Comment by NeoTheThird** [comment]
@WLBI This is off-topic for this bug report, but you can track the progress for 16.04 here: https://github.com/ubports/ubports-touch/milestone/3
You can see some blockers we want to fix before landing a pre-alpha there. The staging channel only had very basic functionality and we will have to change and modify big parts of it.

**Comment by stefanomelchior** [comment]
@SanderKSmit @Flohack74 This Weekend I tested the following doc (https://wiki.ubports.com/wiki/Libertine%3A-install-and-manage-desktop-applications/37a2905) just after installing Desktop Apps Scope, which formerly hosted libreoffice and firefox in BQ's image, and it worked well.
Now I run again libreoffice, firefox and calibre (to read and edit ebooks)

**Comment by NeoTheThird** [comment]
Lost track of this one, yes, i can confirm that it works.
