### ISSUE TITLE
Restart does not work properly

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1111]
- Device: Bq E5, Nexus 5
- Channel: Edge
- Build: 2019-04-23

### Steps to reproduce
1. Hold the power button until the dialog appears.
2. Tap on the "Restart" button.

### Expected behavior
The device will reboot after tapping/clicking on the "Restart" button.

### Actual behavior
The device remains powered on but not interactive. Only the screen off and on functionality is working.

**Comment by fredldotme** [comment]
I can confirm this behavior on MX4/arale

**Comment by giiba** [comment]
My Nexus 5 reboots fine, I've been testing things and rebooting a lot the last couple of days. I'm using the rc 16.04 (2019-W17).

It does take 10-15 seconds before it happens, and the screen never powers down. But the 'Google' splash does appear and the phone does reboot. Takes a while.

I was going to make the suggestion for a shutdown splash screen to let users know that something is happening.

**Comment by jld3103** [comment]
Confirm on Nexus 5

**Comment by jld3103** [comment]
Also Power off doesn't work

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/qtmir/pull/26
