### ISSUE TITLE
MEIZU MX4 : GPS seems not working

### ISSUE THREAD

**Issue by zacardec** [ubports/ubuntu-touch#1114]
### Description of the feature
The location of my device seems not to work. I have tested on Unav, Google maps with Morphbrowser, and Sensorsstatus. Permissions have been given for each software.
This bug was also reported by another unav user here: https://bugs.launchpad.net/unav/+bug/1799307 .
The location is enabled, when searching the location icon changes state correctly but no results.

- Device:ARALE_MEIZU MX4
- Channel: STABLE
- Build: OTA-8

### Steps to reproduce
Make a localization request by an application or a web page

### Expected behavior
Be localized :)

### Actual behavior
Seems not to work;

### Logfiles and additional information
Thanks to tell me if you need logs and the way to find them.

**Comment by RubbelDeCatc** [comment]
Same problem here on Sony Xperia X

Hi everyone.

It seems that GPS isn't working on my device. And it never worked. The sensors Application tells me that GPS is supported and active.
**Source Staus** no error
**Last updated** empty

Here is the test_gps output
https://oc.dirk-hoeschen.de/index.php/s/WtZzxJ64Biecoyq

**My System**

* Sony Xperia X
* Ubuntu 16.04 (22.04.20)

**Comment by Flohack74** [comment]
Your device had contact with up to 26 satellites:
`num_svs:	26`
But you never got a lock. Did you start it under clear sky, no buildings blocking the sky view? Prevent screen suspension, and wait for at least 5 to 10 minutes. test_gps should then start reporting a longitude/latitude pair. What does @fredldotme know about it?

**Comment by cibersheep** [comment]
I have using GPS since I got my Arale. I checked these days just in case.
Indoors I seem not to get position locked but outside is ok.

So, just in case: If I'm not wrong, you need to have GPS and wifi network on

**Comment by Flohack74** [comment]
I close this since we basically it works, even when you need a lot of patience ;)
