### ISSUE TITLE
image-signing is expired

### ISSUE THREAD

**Issue by TheFox1312** [ubports/ubuntu-touch#1120]
- Device: mako
- Channel: all
- Build: latest

### Steps to reproduce
flash the latest image via ubports-installer for mako

### Expected behavior
Expected was the automatic install process on the phone

### Actual behavior
the installation process aborted and the phone booted into recovery

### Logfiles and additional information
ubports logs are OK
phone log shows: image-keyring.tar.xz expired

### how to fix
remove the expire date from the keyring.json in gpg/image-signing.tar.xz or renew it

**Comment by mariogrip** [comment]
Fixed now :)

**Comment by UniversalSuperBox** [comment]
There are still remaining issues with installing updates, this issue can remain open to track the problems.

To piggy-back off of this, I've filed https://github.com/ubports/build-scripts/pull/10 as a way to alert us when the time to regenerate these keys comes up... so this *never* happens again.

**Comment by UniversalSuperBox** [comment]
This issue has been completely resolved by re-signing all current candidate images and deltas with the new key. Installations and updates of Ubuntu Touch should now work properly.
