### ISSUE TITLE
Cannot search using words aside from the first one in the app drawer

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1122]
- Channel: Edge

### Steps to reproduce
1. Install an app from the store with more than 1 word. i.e. Activity Tracker
    Do not use any of the core apps because keywords are usually configured in them

2. Open the app drawer.
3. Search using a word aside from the first word from the title of the app installed in step 1.
    i.e. "Tracker".

### Expected behavior
Apps with "Tracker" in the title are included in the result.

### Actual behavior
Apps with "Tracker" in the title are NOT included in the result.

### Logfiles and additional information
I had a hard time coming up with the title to describe the issue and I'm still not satisfied with the one I came up 😆

**Comment by dobey** [comment]
Does searching for partial match of first word also fail? For example, searching for "vit" should also include "Activity Tracker" in results.

**Comment by kugiigi** [comment]
Yes, you can't search for wildcards (this seems a better word to describe? 😝)

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/unity8/pull/197
