### ISSUE TITLE
App drawer does not steal focus from the foreground app

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1123]
- Channel: Edge

### Steps to reproduce
1. Open an app.
2. Focus a text field to summon the OSK.
    If you have the game Falldown, play the game.
3, Open the drawer.

### Expected behavior
The app is suspended while the app drawer is open.
OSK opened from the app is closed.
Games such as Falldown will automatically pause (if supported).

### Actual behavior
App does not suspend. OSK opened frrom the app is still visible on top of the drawer.
Games such as Falldown continues to play and does not pause.

**Comment by kugiigi** [comment]
This actually seems to be the same issue as the lock screen although that might be a separate bug. Lock screen doesn't suspend the current app so OSK is still shown on the lock screen when a text field is focused in the app. This might also be the cause why location works even on locked screen.

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/unity8/pull/156
