### ISSUE TITLE
Minimize,Maximize, Window snapping are not working

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1124]
- Device: Nexus 5
- Channel: Edge

### Steps to reproduce
1. Switch to windowed/desktop mode preferably on an external display.
2. Click on the minimize and maximize button.
3. Drag any window to the edges to snap them.

### Expected behavior
Windows are minimized when minimize button is clicked.
Windows are maximzed when maximize button is clicked.
Windows snaps into edges when they are dragged there.

### Actual behavior
Windows stays visible or sometimes just go behind another app when minimize button is clicked.
Windows does nothing when maximize button is clicked.
Windows does nothing and the white rectangle just stays visible when they are dragged into edges.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/144
