### ISSUE TITLE
Ubuntu Touch dual boot installer doesn't work

### ISSUE THREAD

**Issue by addminztrator** [ubports/ubuntu-touch#1127]
So, I tried following along with the dual booting tutorial found [here](https://wiki.ubuntu.com/Touch/DualBootInstallation) but I can't get dual booting to work. The dual boot app just says "no available channels" and doesn't let me install. I even tried the process with several different [factory images](https://developers.google.com/android/images#occam) but the result was the same each time. 
Device: Nexus 4

**Comment by UniversalSuperBox** [comment]
Hello @addminztrator,

Those instructions are quite old and out of date, written before UBports was the maintainer of Ubuntu Touch. We do not support any dual-boot of Ubuntu Touch and Android together. There may be some community resources to help, but we currently don't have the resources to work on that kind of feature.

**Comment by addminztrator** [comment]
> Hello @addminztrator,
> 
> Those instructions are quite old and out of date, written before UBports was the maintainer of Ubuntu Touch. We do not support any dual-boot of Ubuntu Touch and Android together. There may be some community resources to help, but we currently don't have the resources to work on that kind of feature.

Okay, fair enough. Is the source code for those apps available somewhere though? I'd appreciate it if you could point me towards the repo so I could see if it is possible to get it to work.

**Comment by Flohack74** [comment]
Well the biggest issue is that Ubuntu Touch cannot use the same kernel as Android. So most of the multiboot solutions fail in terms of not being able to boot between 2 different kernels. You could flash the android kernel into boot partition and the UT e.g. into recovery, but then you loose the recovery functionality, and also system updates.

**Comment by UniversalSuperBox** [comment]
I think the most that's been done is taking the old MultiROM APK and replacing the URL of the old server with the new one... no patched source anywhere, just repacking the APK.

Hardcore hacking.

**Comment by addminztrator** [comment]
> I think the most that's been done is taking the old MultiROM APK and replacing the URL of the old server with the new one... no patched source anywhere, just repacking the APK.
> 
> Hardcore hacking.

Oh this is the answer I was looking for. Thanks!

**Comment by dobey** [comment]
FWIW, the above linked instructions were long outdated even when Canonical was still shipping Ubuntu for devices.

**Comment by addminztrator** [comment]
> FWIW, the above linked instructions were long outdated even when Canonical was still shipping Ubuntu for devices.

Yes I'm realizing that these instructions are basically irrelevant. Following [this](https://forum.xda-developers.com/google-nexus-5/orig-development/mod-multirom-v24-t2571011) has been more useful since I have a Nexus 5 too. The only problem I am having is finding the images of the Ubuntu Touch installer. I have no idea where to look for those but if I could find them, I'll probably be able to dual boot.

**Comment by addminztrator** [comment]
> I think the most that's been done is taking the old MultiROM APK and replacing the URL of the old server with the new one... no patched source anywhere, just repacking the APK.

Could you please share the URL of the new server? I have no idea how and where to find it!
