### ISSUE TITLE
Geotagging on camera app write the wrong location issue

### ISSUE THREAD

**Issue by sonigfr** [ubports/ubuntu-touch#1130]
Hi, I discovered a bug with the camera about the geotagging written on file when activate the location option on the app. The gps localization written in file is wrong with an about 100 kmiles distance difference.  

- Device: Oneplus one (Bacon)
- Software Version: Ubuntu 16.04 (OTA-8)
- Channel: Stable
- Build: 20190226-25779

### Steps to reproduce
Just flash the mobile, with wipe and fresh default 16.04 install from ubports install software. Activate location option on the camera app. Take a photo when the gps is activated (when location icon on the app become from red to white). Verify the photo taken from the mobile with any software (I use the map section from Darktable, or the map plugin of eog on linux...).  

### Expected behavior
The geolocalization is exact and show me the right place where the photo were taken  

### Actual behavior
The photo show a location miles away from my actual location. 

### Logfiles and additional information
image20190506_173941846.jpg is the original photo taken with the phone (containing written exif gps informations)
exiftool.txt is the exif photo gps and other informations reported by the exiftool command
My real location while shooting the photo was here : 
https://www.openstreetmap.org/#map=17/48.86187/2.35015
The location written on the file show here : 
https://www.openstreetmap.org/#map=14/49.71194/2.70024
Here a representation of the gap:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=48.862%2C2.350%3B49.710%2C2.687#map=6/49.859/3.142
UTlogcat.txt and UTdmesg.txt are /var/log/dmesg and /android/system/bin/logcat logs from adb commands and after manipulation from the phone as asked on the Bug reporting section of docs.ubports.com 

I tried from rc and devel channels, always tried to reboot and perform these steps again with same results. uNav, and other geolocalization apps on the phone show the right location. I take advantage of this post to say that gps is not as good as other phones. I never have signal when at home and outside, the synchronization take a while. If someone can see that on logs... I don't know where it comes from. 

[exiftool.txt](https://github.com/ubports/ubuntu-touch/files/3149245/exiftool.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/3149255/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/3149252/UTlogcat.txt)
If you think like me there is a characters issue with these logs (because phone or my linux set to French ?) here are two other versions that seems better, asked and uploaded directly from the phone terminal this time:
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/3149438/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/3149439/UTlogcat.txt)

![image20190506_173941846](https://user-images.githubusercontent.com/50325248/57244734-556a7e00-7039-11e9-8f84-831096d763ac.jpg)

**Comment by UniversalSuperBox** [comment]
This should be fixed, or at least made less annoying, with #282. Please see https://docs.ubports.com/en/latest/userguide/dailyuse/location.html for more information on making your location service more accurate.
