### ISSUE TITLE
Nexus 5 OpenStore and Update Bugs

### ISSUE THREAD

**Issue by deescover** [ubports/ubuntu-touch#1131]
- Device: Nexus 5
- Channel: All
- Build: All current builds (2019.05.08) including OTA-9

### Steps to reproduce
Installing a fresh copy of UT using the UBports Installer (0.2.2-beta) on a brand new Nexus 5 using any of the channels.

### Expected behavior
I expected the OpenStore to be populated and able to either browse through categories or use the text search feature. Also, if any apps need to be updated or uninstalled, I should be able to do so from the 'My Apps' tab.

For the updates, I am a brand new user, so I imagine that it would allow me to change which builds I am able to receive from updates, similar to when installing using the UBports Installer.

### Actual behavior
The OpenStore being completely empty in the first three tabs and the the 'My Apps' tab not allowing me to open any additional information regarding currently installed apps, even though it is populated.

Also, when I go to look at updates, it will check for updates fine, but when I try to change channels, there are no opens present.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/3159510/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/3159511/UTlogcat.txt)

**Comment by dobey** [comment]
This sounds very much like you are not connected to any data network (cellular or wifi). OpenStore does not behave well without network yet, unfortunately. See the following issues:

https://gitlab.com/theopenstore/openstore-meta/issues/149
https://gitlab.com/theopenstore/openstore-meta/issues/230

**Comment by Flohack74** [comment]
Also, please report this to the Openstore team in above´s Gitlab repo. We are not maintaining it in the UBports org.
