### ISSUE TITLE
High CPU usage from PulseAudio after playing audio

### ISSUE THREAD

**Issue by jfrederickson** [ubports/ubuntu-touch#1132]
- Device: OnePlus One
- Channel: RC
- Build: 16.04 (2019-W18)

(That said, I've also experienced this behavior on stable/OTA-8.)

### Steps to reproduce

I haven't been able to reliably reproduce this bug yet unfortunately. Some details about my use case though:

- I pretty regularly use a bluetooth headset to listen to podcasts during my commute
- My phone connects to wifi networks at home and at work

Normally I notice this issue at work, while the phone is connected to wifi and _not_ playing audio.

### Expected behavior

PulseAudio CPU usage is negligible while phone is idling

### Actual behavior

`top` (via adb) reports that pulseaudio is using ~15% CPU while phone is asleep. Typically when this happens there will be at least one app open in the background that was previously playing audio. Closing this app causes the CPU usage to drop. Most recently this was the "Ambient" app, but I've also experienced this behavior with Podbird.

### Logfiles and additional information

Grabbed dmesg and logcat logs; I also included the output of `strace` on the pulseaudio process in case something in there is helpful

https://gist.github.com/jfrederickson/163b3c55941ea2e0c0481733c2d62b67

**Comment by UniversalSuperBox** [comment]
That error `W/Looper  (    0): Poll failed with an unexpected error, errno=11` seems potentially interesting, however I don't think that's the entirety of logcat on the device. Maybe by running `sudo /system/bin/logcat` we'd be able to get a more complete picture of what's going on?

**Comment by UniversalSuperBox** [comment]
Since we haven't heard of another confirmation of this report, or received more information about it, I'll close it now. If the issue persists, let's open a new issue report with more complete logs.
