### ISSUE TITLE
dash missing dot bar [...] in landscape

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#1133]
fp2 edge
rotate the phone from portrait to landscape, the 3 dots bar is missing

**Comment by UniversalSuperBox** [comment]
This is by design. When the Drawer is wide enough, it is possible to tap outside the Drawer to close it... or at least that was the thought.

**Comment by dobey** [comment]
I would say even with the drawer not taking up the full width of the screen, we should still show the handle. I think it would also make sense to keep it, even after the relevant Qt issue is resolved, as it provides a visual hint. However, it might be appropriate to hide it if a touch gesture input device is not available (ie, on a PC with only keyboard/mouse), but that's probably much more difficult to resolve, and worth having a larger thought/discussion session on it.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/140
