### ISSUE TITLE
FP2 Edge: App drawer is not updated with new apps after installation

### ISSUE THREAD

**Issue by dupplak** [ubports/ubuntu-touch#1138]
- Device: FP2
- Channel: Edge
- Build: 16.04

### Steps to reproduce
Install any app from Openstore.

### Expected behavior
New app appears in app drawer.

### Actual behavior
New app won't be shown

**Comment by advocatux** [comment]
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1058

**Comment by UniversalSuperBox** [comment]
Duplicate of #1058
