### ISSUE TITLE
Update screen: inconsistency in date of last OS update

### ISSUE THREAD

**Issue by abkro** [ubports/ubuntu-touch#1139]
- Device: Nexus 5
- Channel: rc
- Build: 2019-W18

### Steps to reproduce
Open Settings - Updates. Check the date of the last OS update that was installed and compare to the date it was actually installed.

### Expected behavior
The date of the last update should be the date when this update was actually installed on the  device, and it should not change.

### Actual behavior
The date of the last OS update changes as time passes. This date is always incremented to today's date when you open this page, even though the update may have been installed many days earlier.

When the next OS update gets installed the date of the previous one stops changing.

**Comment by Fuseteam** [comment]
it's interesting to note the said date does not change on the about page

**Comment by Flohack74** [comment]
I found the bug and I will try to find a way to fix it. Basically the date is set after successful installation, which is easy for click apps. Now, a system update triggers a reboot, but then system settings cannot record that anymore. So its Datetime.Now() in the very moment when you open system update **again** - weird, but we might be able to fix it easily ;)

**Comment by PJK2011** [comment]
Correct install dates for previous updates still recorded on my Nexus 5 hammerhead on OTA-10 rc ver 54 image 2019-W32.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed. The date of last update is not today's date. It shows a date in the past, which corresponds to update date.
