### ISSUE TITLE
 Media player can't play .MP4 video files 

### ISSUE THREAD

**Issue by bugcrazy** [ubports/ubuntu-touch#1140]
### Illustrations

- Device: Turbo, Hammerhead
- Channel: Stable
- Build: 16.04 OTA-9

### Steps to reproduce

1. Open File manager and select a video with .MP4 format
2. Media player tries to open the file

### Expected behavior

Video should play.

### Actual behavior

File can't be played due an error (format not supported).

**Comment by Arc676** [comment]
Possible duplicate of #249 (MOV rather than MP4) and/or #1092 (RC rather than stable).

**Comment by UniversalSuperBox** [comment]
This is a duplicate of #1092. No video playback through the media player is possible on the Nexus 5 right now.
