### ISSUE TITLE
N5: microphone very poor in phonecalls

### ISSUE THREAD

**Issue by nomoreAndroid** [ubports/ubuntu-touch#1143]
### Illustrations

- Device: Nexus 5 (821)
- Channel: dev and stable
- Build: OTA 6 - 9

### Steps to reproduce

Speech in phonecalls gets ununderstandable if the phone is more than 10cm away from the face. Handsfree function does not work at all (not understandable noise).

### Expected behavior

The microphone works perfectly with any voice recorder over several meters. Record volume can be adjusted over audio settings.

### Actual behavior

Just in phonecalls the audio gets very fuzzy and bad if the sound source is more than 10cm away from the micro. 
Seems that just the phone-coreapp uses the microphone in a different way than other apps.

### Logfiles and additional information

This is the third (brand new) device with the same problem. Issue happened with this phone since the first minute (OTA 8+9), with prior phones also with earlier OTAs. Recordvolume of the micro can not be influenced with uVolMan.

**Comment by Flohack74** [comment]
Microphones are a very tricky thing on mobile phones. For example the OPO has 3 of them:
- Mic for calls when in normal call mode
- Ambient mic for the speakerphone
- Additional ambient mic (located on the back) to record ambient noise and calculate echo and noise countersignal
In Android all this is managed with a complex pathing of audio signals, most of which is influenced by the so called acdbdata records and mixerpaths.xml - Those things need to be checked if they are in place and used coirrectly in UT
If this does not help, we need to find if maybe LineageOS users had the same problem and some fixes were applied later. In general its a problem that can be solved but needs a lot of patience.

**Comment by talmai** [comment]
As of RC channel, build: 2020-W19, Image 20200507-19245, this was not reproducible. I suggest we close this issue.
