### ISSUE TITLE
Native device ports

### ISSUE THREAD

**Issue by ZeroPointEnergy** [ubports/ubuntu-touch#1145]
There are currently two new devices on the horizon (somewhere) like the Pinephone and the Librem5 that maybe could be classified as Linux native devices since they are not Android phones.

This means they will not be Halium ports so the question arises where this device ports will be tracked so we can see what the current issues are, what people are working on and what resources could be shared between this devices?

I currently have a librem5-devkit and in my rare free time I'm trying to get ubuntu-touch booting, but for now I'm stuck reading up on uboot and friends to understand how this all works and what is required. So no promises that anything will ever come out of this, but it would be great if we could share the insights and work we do on this devices in a central place and help each other out.

**Comment by Flohack74** [comment]
I think the best place would be to open a thread in the forum. @UniversalSuperBox and @mariogrip already have the PINE64 kit, they might be of help here. Note that UBports still does not have any Librem5 kit so we can´t just give you the precise steps.

**Comment by ZeroPointEnergy** [comment]
I think the technologies are pretty similar in that we can have a lot of synergy here. I already opened a forum thread about it. If that is the preferred place to discuss development I will keep all the progress and questions there.

**Comment by Flohack74** [comment]
There are also Telegram and IRC channels probably, @pinephone e.g.

**Comment by MenmuirMark** [comment]
My developer skills are limited but I'll happily test and report any progress on the Raspberry Pi if the Pinephone and Librem 5 progress gives me something to work on.

**Comment by Flohack74** [comment]
I close this question since there were no more responses.

**Comment by MenmuirMark** [comment]
Happy with that
Mark

On Wed, 13 Nov 2019 23:34:16 -0800, Florian Leeber wrote:
> I close this question since there were no more responses.
>

-- 
Sent using Dekko from my Ubuntu device
