### ISSUE TITLE
 Enhancement - Both screens active when external screen connected

### ISSUE THREAD

**Issue by absint0o** [ubports/ubuntu-touch#1147]
Feature description
It would be amazing if UT could have the ability to maintain the screen usability on the phone or tablet screen when it's on convergence mode with another screen connected. 
In any laptop when you connect a external screen via HDMI the laptop screen keeps being usable as another screen. This could be very useful on UT tablets as you can have some apps opened on the external screen and others on the equipment screen.  It would also be very useful on apps that can use both screens (like PowerPoint) 

Thank you very much. 
Regards.

**Comment by dobey** [comment]
This is roughly the same as https://github.com/ubports/unity8/issues/20

**Comment by dobey** [comment]
And definitely the same as https://github.com/ubports/unity8/issues/39

**Comment by absint0o** [comment]
Nice! Thank you for your help! Now there's two people requesting the feature! :)
