### ISSUE TITLE
Shorter battery life on OTA-1 , TURBO

### ISSUE THREAD

**Issue by Stefano0101** [ubports/ubuntu-touch#115]
Every since I switched to UBports I noticed there is shorter battery life on my Pro 5.
The issue was also reported back on Canonical image after OTA-13, which took an extra 15-20% of battery life, but nothing has been done. https://bugs.launchpad.net/canonical-devices-system-image/+bug/1630470

The IDLE battery life is very good on new UBports images, but immediately dropping when using browser, seems like it draining the most. Is there such a thing as CPU GOVERNOR on Ubuntu kernel, as on FLYME Is implemented very well and seems to do it's job. On Ubuntu is probably the CPU GOVERNOR stuck  in ON DEMAND or POWER USER mode as the system is faster, but it's draining battery life quite a lot.
Will there be in the future an option for the user to choose a governor, or maybe just implement an BATTERY SAVER mode??? I know we want a fast system, but as the battery life is also important as we do not want to charge every night or to carry a battery bank with us all the time.
Pro 5 has a huge battery and should last longer. Also for the future phones this might be a problem which need to be addressed as we want our phones to be on par or better then Android counterpart and maybe a new users will be attracted to a longer battery life on UBports??? :-)

If you need any logs, please let me know. (also how to get them, where to find them)
Thank you.

**Comment by mihaelmilea** [comment]
I have the same battery life on ubports as on canonical for my Pro 5.

**Comment by speedracer08861** [comment]
Battery life is shorter on ubports

**Comment by NeoTheThird** [comment]
Thanks for reporting everybody!

@Stefano0101 and @speedracer08861 How long does the battery last for you? How long did it last on the Canonical Image? How long does it last for you @mihaelmilea ?

Here's how to get [some logs](https://docs.ubports.com/en/latest/contribute/bugreporting.html#getting-logs) :)

**Comment by Stefano0101** [comment]
The battery life is around 1.5 day with average usage. Depends on data connection hopping from 4g to H to 3G to E as it eats a lot and sometimes the phones overheats while browsing internet. It's not happening all the time and places, but in areas with low signal or too far from mobile tower. This I believe is the main reason for shorter battery life.
On Canonical image it was similar right after OTA-13:
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1630470
Logs are there as well.

**Comment by mihaelmilea** [comment]
I charge my Pro 5 every night just to be sure but when I need it it can go for two days. I use mobile data on 2G only. I keep top running on the terminal all the time and when only a cpu core is used the battery consumption is very, very low. I make phone calls, I browse, I check emails, I take pictures. I don't play games.

**Comment by Stefano0101** [comment]
Some logs:
[“UTdmesg”.txt](https://github.com/ubports/ubports-touch/files/1256588/UTdmesg.txt)

**Comment by Stefano0101** [comment]
Updated Utlogcat.txt after phone overheats and signal dropping.
[Utlogcat.txt](https://github.com/ubports/ubports-touch/files/1256813/Utlogcat.txt)

**Comment by Stefano0101** [comment]
Close this one down. After a clean install, the battery life is as good as before.
