### ISSUE TITLE
Can I dualboot (preferably with LineageOS)? What is the current way of doing it?

### ISSUE THREAD

**Issue by adamryczkowski** [ubports/ubuntu-touch#1153]
- Device: LG Nexus 5

All the guides I found are outdated because they depend on ubuntu installer apk, that is broken (and difficult to obtain) at the moment due to missing software channels. Missing phablet-tools on bionic also does not help. Perhaps there is a way to fix that?

**Comment by Fuseteam** [comment]
dual boot is not officially supported at the mom

**Comment by adamryczkowski** [comment]
Thank you for comment. Do you know what is holding off that support? I understand, that the problem is more complicated than simply replacing hard-coded now-defunct software channel with a current one?

Are you aware of any unofficial way of doing it?

**Comment by Fuseteam** [comment]
as far as i understand it due to how ota updates work, there is an unsupported way in the ubports forum i believe

**Comment by cibersheep** [comment]
You might want to keep the conversation on the UBports forum:
https://forums.ubports.com/
