### ISSUE TITLE
Phone not detected installing Anbox

### ISSUE THREAD

**Issue by smurfgoddess** [ubports/ubuntu-touch#1158]
Bug Report

- Device: Nexus 5
- Channel: ?
- Build: 16.04

I just installed Ubuntu Touch and I would like some of my old apps. I am following the Docs to install AnBox on my Nexus 5. (https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html) I am running Ubuntu on my laptop, Satellite C55. The script says that adb and fastboot are installed.

I type in the Codename and the Partionname the way it reads and replace them as indicated in the chart. I then run the next lines of code but it always restarts my computer instead of my phone. The phone is in developer mode. A script never comes up indicating anything when it is connected to my computer and I don't know how to make it recognized. I ran the rest of the code but it didn't work, obviously.

I was following some other directions for something else and it did connect but I am not sure what I did.

Could someone coach me on how this works in Linux?

Thank you!

**Comment by UniversalSuperBox** [comment]
Hello @smurfgoddess,

It sounds like you are not getting a connection with `adb` to your device. Please try running `adb devices` on your PC to ensure it can detect your device. If not, try the following steps to resolve the problem:

1. Ensure that developer mode is enabled by following [Shell access via adb](https://docs.ubports.com/en/latest/userguide/advanceduse/adb.html)
1. Type `dmesg -w` in a terminal, then plug in your device. You should see something similar to `New EHCI/XHCI device detected` followed by information about your device (Saying it's an LGE Nexus 5)
1. If you do not see this information, try a different cable. Try multiple different cables. Some people go through 5 or 6 cables to find one that plays nice with adb. Try to run `adb devices` with the device on, plugged in, and unlocked.

If these steps do not help, please contact us via [our forum](https://forums.ubports.com/category/37/support) for better support.
