### ISSUE TITLE
Blank OSK on the lock screen

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#1159]
- Device: BQ E4.5 (krillin)
- Channel: edge
- Build: Ubuntu 16.04 (2019-06-11)

### Steps to reproduce
Boot the device, go to the lock screen

### Expected behavior
OSK shows and you can enter the PIN / Password to unlock the device

### Actual behavior
OSK is blank, so you can't type anything

### Logfiles and additional information
- maliit-server.log https://paste.ubuntu.com/p/zksFnHF34k/
- unity8.log https://paste.ubuntu.com/p/PhCbJJCFG4/
- syslog is full of this kind of messages https://paste.ubuntu.com/p/J5H2jbtngv/ (I don't know if that's relevant but just in case)
- I can unlock the screen plugging an external keyboard

**Comment by zubozrout** [comment]
I can confirm having the same issue with today's update on Meizu MX4 (arale).

**Comment by UniversalSuperBox** [comment]
I've updated the changelog of keyboard-component in `xenial_-_edge` and the images are rebuilding now. This should be fixed by upgrading after that is finished. https://ci.ubports.com/job/xenial-hybris-edge-rootfs-armhf/316/
