### ISSUE TITLE
System crashes from time to time right after I receive a Telegram message

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#1164]
- Device: Meizu MX4 (arale)
- Channel: any - this is a long standing issue, but this time it was observed on edge
- Build: 2019-06-21

### Steps to reproduce
Now this is quite hard. I have not been able to observe any regular patter for this. Sometimes when I am just using the phone and am receiving messages it can randomly crash, but more often it just happens when I leave the phone on my desk and have just received a message on Telegram (seeing the message on my laptop right at the time of the crash).

Please note this sluggish UI issue followed by a crash is a different one: https://github.com/ubports/ubuntu-touch/issues/29 so yes, both are happening to me, but they are different.

It is also important that sluggish UI mostly only leads to a Unity8 restart - which is usually enough for the system to recover. The issue I am reporting is a hard crash always going through the initial boot logo.

### Expected behavior
Well, ideally the system should not crash.

### Actual behavior
System crashes upon receiving a Telegram message. I would expect it would be network related but I don't recall seeing it with any other service.

### Logfiles and additional information

[unity8.log](https://github.com/ubports/ubuntu-touch/files/3316892/unity8.log)
[syslog.log](https://github.com/ubports/ubuntu-touch/files/3316893/syslog.log)

The crash happened right at "2019-06-22:15:21:21" and you can see some Telegram activity there in the unity8.log

In the syslog (named as syslog.log because of GitHub filename limitations) kernel seems unhappy at "Jun 22 15:21:22".

**Comment by UniversalSuperBox** [comment]
This is a very interesting problem. Reading your log file in more detail (relevant section [here](https://paste.ubuntu.com/p/q4ZJwJtCTd/)), it appears that this timeline happens:

* Screen is turned off at 15:21:19 via power key press
* System begins to attempt to enter a lower power state
* The [CMDQ](https://lwn.net/Articles/699452/) driver attempts to perform an action on the display (maybe) and fails, dumping a huge stack trace
* Unity8 stops and your session restarts (as noted by systemd starting again)
* The Nuntium service attempts to restart too many times and the device reboots safely (`session-watchdog: 'nuntium' (instance '') hit respawn limit - asking logind to reboot`)

Ultimately, it's unclear whether these events are related. The amount of information from these logs is huge, but at the same time not very useful. It's unclear why Unity8 stopped in the first place. The session failing to reload is an interesting side effect.

**Comment by zubozrout** [comment]
Thank you very much for looking at this. Well, I've just experienced another system crash and phone reboot but this time I received no Telegram message. Which is weird for me as so far I've only noticed such reboots immediately after I received Telegram message. But maybe it happens more often then I though without me even noticing it.

syslog(.log) again contains the same message you mentioned above:
```
Jul 12 18:01:13 ubuntu-phablet session-watchdog: 'nuntium' (instance '') hit respawn limit - asking logind to reboot
```
While unity8.log seems completely useless this time. I haven't been touching the phone a while.

[syslog.log](https://github.com/ubports/ubuntu-touch/files/3387202/syslog.log)
[unity8.log](https://github.com/ubports/ubuntu-touch/files/3387203/unity8.log)

**Comment by UniversalSuperBox** [comment]
Well, nuntium is a bridge for notifications. If something goes wrong in the notification system, I guess that'd be somewhere it could manifest. There should be a `nuntium.log` in `~/.cache/upstart/`, or a gzipped file from around one of the crashes. Maybe take a peek at those, see if they look interesting.

**Comment by zubozrout** [comment]
Not sure, but nothing I could see there: [nuntium.log](https://github.com/ubports/ubuntu-touch/files/3389063/nuntium.log)

**Comment by UniversalSuperBox** [comment]
@zubozrout, I'm not sure if that includes your phone number, but we should delete your message if it does.

The `org.ofono.Error.InProgress: Operation already in progress` seems interesting, I think it keeps restarting due to that. I'll have to see if I can talk to the Nuntium developers or get them to take a look at this thread. Maybe they can jog our memory.

**Comment by zubozrout** [comment]
@UniversalSuperBox Thank you for checking. Regarding the phone number it doesn't look like it but TBH I am not sure what the identity number is.

**Comment by Flohack74** [comment]
Is this still an issue? Note that most of those crashes are out-of-memory related, and happen randomly, you just attribute it to Telegram/TELEports as you use that quite often.

**Comment by zubozrout** [comment]
@Flohack74 Well, to be fair, it still happens from time to time but certainly not that often as back in summer when at certain point I had even several crashes like this during a day. Now these are pretty much rare.

As for my Telegram/Teleports attribution - it always happened when there was some incoming message. I doubt it has anything to do with the app itself - but I always suspected network related stuff or notifications (Dalton confirmed the later).

Anyway, if you feel this could be closed (and at the moment I have a feeling this faded away a bit so am all for it) then please do :).

Thank you

**Comment by Flohack74** [comment]
I would say so. I receive a lot of notifications per day, and it never happens in the way you described that unity crashes. Its mostly when I open an App or interact with a running one. Does this also happen with all Apps closed?

**Comment by zubozrout** [comment]
Well, for instance it never happened to me with Dekko (and I had these crashes even without Dekko installed), that is at least as far as I recall. In most cases system crashed when I was either using my phone directly and wanted to read the message or when I was reading in on my computer. Could have something to do with notifications removal on message read maybe :) - but again, doesn't seem to happen with Dekko, though that one is using its own approach. But it also crashed from time to time when I was not interacting with anything at all.

My habit was to keep Telegram/Teleports open on my device (while not having running anything else except for some rare cases) but with no way to go to "minimize" the last running app under latest Unity8 I am currently not leaving anything open anymore (maybe it is related, will try to keep it open for a while again) so these kind of issues should not be caused by any other app.

Anyway, please close this ticket and an case this reappears again I will open a new one - but hopefully this is not going to be the case :).

**Comment by Flohack74** [comment]
Fine ;)
