### ISSUE TITLE
Bootsplash exchange preparations break system-image-upgrader

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1167]
During trying to get the new bootsplash into bacon we somehow broke the automatic start of the upgrade after reboot into recovery. This accidentally slipped also into RC because no critical bug was created.

**Comment by UniversalSuperBox** [comment]
This issue has been fixed. Any affected users may download the next update through System Settings and tap "Reboot and Install" as normal. Once the UBports Recovery screen appears, tap "Android Actions" then "Apply Update". After this is finished, you will not need to repeat these steps.

Alternatively, users can run the UBports Installer to reinstall Ubuntu Touch. If the "Wipe" option is unchecked, user data will be kept intact.
