### ISSUE TITLE
Trust-Store prompts take a very long time to appear, freeze app

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1169]
- Device: All Qualcomm (it's all I have)
- Channel: edge
- Build: *

### Steps to reproduce

1. Open an app that has a trust prompt (such as [uNav](https://open-store.io/app/navigator.costales) or [SensorsStatus](https://open-store.io/app/sensorsstatus.chrisclime))
2. Take an action that opens the prompt (in uNav, tap the location detection button. In SensorsStatus, open the app)

### Expected behavior

The trust-store prompt opens almost instantly, allowing me to allow or deny access to sensitive data

### Actual behavior

The trust-store prompt takes several seconds to appear. During this time it appears that the app has frozen or crashed. In apps that open the prompt immediately on starting, the app will stay black until the prompt appears.

### Logfiles and additional information

I was unable to find any hints in the app's log or `ubuntu-location-service-trust-stored.log` so far.

**Comment by mardy** [comment]
Can you please verify if you meet the same behaviour when opening System Settings -> Accounts and create a new account?
(just to understand if this might be due to the trusted sessions implementation)

**Comment by UniversalSuperBox** [comment]
Looking in more detail, this appears to be a bug in sensorsstatus itself. Other apps can ask for location normally, and other trusted sessions seem to work fine. Sorry for the noise.
