### ISSUE TITLE
Multiple gmail notifications for the same mail

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#117]
Bacon, 15.04/devel r31

Quite frequently I am getting multiple notifications for the same e-mail in gmail. I have attached a screenshot where my indicator is showing 6 instances of the same notification.
![screenshot20170619_102453771](https://user-images.githubusercontent.com/13762919/27276058-2c496a8a-54da-11e7-93d1-87c32f260d01.png)

**Comment by NeoTheThird** [comment]
Did this start happening recently, or is it a longstanding bug? I'll put it on awaiting triage for now, since i'm not sure if we can fix it without replacing the canonical push notification server. @Flohack74 Do you know where gmail notifications are handled?

**Comment by tomoqv** [comment]
I would say that I first noticed this about a week ago. I can't recall this happening before that, and I have been on 15.04/devel for a few weeks now.

**Comment by NeoTheThird** [comment]
Then it's probably an issue with the push notification server...
We'll have to discuss what will happen with that soon. Also, with [Dekko](https://dekkoproject.org) coming back to Ubuntu Touch, we will probably not be needing Gmail anymore.

**Comment by tomoqv** [comment]
I would say that I first noticed this about a week ago. I can't recall this happening before that, and I have been on 15.04/devel for a few weeks now.

**Comment by Flohack74** [comment]
Its an issue with account-polld. Recently we updated to a new version which has the plugins as separate modules and not compiled in. Could be thats the reason. Can you check if you have a package installed named "account-polld-plugins-go" ? use apt-cache showpkg account-polld-plugins-go and tell me the output.

**Comment by tomoqv** [comment]
`phablet@ubuntu-phablet:~$ apt-cache showpkg account-polld-plugins-go
Package: account-polld-plugins-go
Versions: 
0.2-0ubuntu1 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 64be9a93f7b1cb14ce50467171062cca


Reverse Depends: 
  account-polld,account-polld-plugins-go
  ubuntu-touch,account-polld-plugins-go
Dependencies: 
0.2-0ubuntu1 - accountsservice (0 (null)) session-migration (0 (null)) libc6 (2 2.4) libqt5contacts5 (0 (null)) libqt5core5a (2 5.3.0) libstdc++6 (2 4.3.0) 
Provides: 
0.2-0ubuntu1 - 
Reverse Provides: 
`

**Comment by tomoqv** [comment]
`I have no idea why insert code doesn't work` ... now it did, though.

**Comment by Flohack74** [comment]
Thanks. Yes we will look into that. Basically @mardy needs to answer the question if this could happen after transition to the modules.

**Comment by Flohack74** [comment]
@tomoqv still an issue?

**Comment by tomoqv** [comment]
Oh, I am using Dekko2 now, and I am getting those notifications, but no Gmail notifications. I thought I had gmail notifications turned off, but it turns out that in the system settings for my google account, there are only 2 apps to enable; Contacts and Calendar. There is no gmail under "Notifications" in the system settings either.
16.04 RC channel, Pro 5.

**Comment by hummlbach** [comment]
So then, lets close this...
