### ISSUE TITLE
App splash screens are not shown when opening from the drawer

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1170]
- Device: Nexus 5, bq E5
- Channel: edge
- Build: 2019-06-30/2

### Steps to reproduce
1. Open an app.
2. Open another app from the app drawer.

### Expected behavior
The app's splash screen is shown until the app has actually loaded.

### Actual behavior
The current foreground app is shown and the newly opened app will only show moments before it actually loads. This might cause confusion to users because it seems like nothing happened after clicking the app from the drawer especially for those that opens a bit longer than usual.

### Logfiles and additional information
Possibly a regression of [unity8/#156](https://github.com/ubports/unity8/pull/156) since the imaginary (LOL) app that gets the focus might be the one hiding the currently opening app.

**Comment by dobey** [comment]
If this is happening, it's definitely a regression, as the "splash" screens are showing up on my Nexus 5, which has an older build of edge still.

**Comment by kugiigi** [comment]
Actually my words are a bit inaccurate 😅
The splash screen are still shown but it's just that the opening app does not get the focus until it actually opens.

**Comment by mariogrip** [comment]
Fixed with: https://github.com/ubports/unity8/pull/177
