### ISSUE TITLE
OTA9 blocks SIM

### ISSUE THREAD

**Issue by JassMan23** [ubports/ubuntu-touch#1172]
- Device: Hammerhead (Nexus 5)
- Channel: Stable
- Build: OTA9

### Steps to reproduce

Let the update do its thing

### Expected behavior

Carry on working as pre-upgrade. [solved with workaround - see below]

### Actual behavior

On rebooting, the "unlock sim" dialog pops up very briefly but Unity restarted 3 times. The status line now shows a sim next to Wifi. Dragging down shows "Flight mode", "cellular data" and a "sim locked" label with an "unlock SIM" button. The button is in-effective. You can see it knows it is being pressed but it doesn't bring up a dialog.
There is no corresponding button in System Settings.
Performing a "restart" prompts same behaviour - no way to unlock.

I eventually wondered if a full powerdown might have an effect. Yeah! Unity only restarted once and the "unlock sim" dialog remains in place long enough to type in the PIN. I have no way of knowing if it was the power down or simply performing 2 restarts before power down encouraged unity to perform single startup.

### Suggestion
If a new OTA is pushed to a device you should get some warning. eg. a download icon on the status bar - something like document-save.svg or an upside down other-actions.svg from the suru/actions/scalable. If a new icon is required I would suggest a device (smartphone) with an arrow going down into it.
Dragging down from status should show a warning that the OTA is about to happen, in progress or has finished awaiting a restart, and that the user should save any personal info if possible and that they should only restart or power down at a convenient time.
UTTweak should allow you to select whether  to always-accept or accept-on-prompt for OTAs.

**Comment by Flohack74** [comment]
@JassMan23 No OTA installation action is happening in the background. If you do not press on the install button, only download might happen automatically, depending on your settings.
Then, no changes have been done to the hardware part, nor to any core radio services etc - in your case for N5 - so it is very unlikely that the OTA really had any effect on the SIM unlocking. It is unfortunately the downside of UT, that sometimes things crash in the background or foreground, and you need a reboot which can fix things that can´be fixed otherwise. A good example is the hotspot function on some devices - after you turn it off, you will need a reboot to get a normal WiFi again.

**Comment by JassMan23** [comment]
Sorry but I never touched anything to install. A week ago I checked for updates but my phone said I was still on OTA6. Since then I have only ever checked for open-store updates. Yesterday, I forgot my phone in the car and the battery went flat overnight. Once recharged, I powered up and the first thing I noticed after the "Google" bootloader was the usual Unity dots taking slightly longer then the SIM unlock popping up and disappearing again. It then flashed up the "just woken up clock screen" but before the status circle could fully draw, unity started it dots again. Again, the "woken up" screen failed to fully draw the circle before unity did yet another restart. Once I got as far as logging in, I noticed I had no carrier strength but a pictogram of the sim. I went to system settings to see if I could unlock (but there was nothing to allow unlock). I then drew down the status screen and noticed the sim unlock button. Nothing I could do allowed an unlock. I then restarted twice more, both times, unity acted as before. Feeling rather frustrated, I powered down completely and amazingly it did a completely normal boot up. The sim unlock came up as usual, and once I had unlocked, I then checked system... About. It says I now have OTA9 surprisingly it says last updated 20/05/2019 which cannot be true because when I checked for new software just 1 week ago I was still on OTA6 and said it was up to date. At no point was I warned about new software being available or that it had downloaded anything and was waiting for me to hit an install button.   

Another thing to note is that the boot loader still says Google but my development phone (dev 1040 26-06-2019) updated the bootloader to "Nexus5", "powered by UBPorts" a couple of weeks ago on a daily update.

**Comment by nathangiovannini3** [comment]
Question the last time you checked for updates, did not give you the presence of OTA 8 or OTA 7 ?

**Comment by JassMan23** [comment]
I was expecting that as well but I figured that with OTA9 being on a phased roll-out that maybe they were somehow being withheld. Maybe some other setting has been slightly wrong ever since my initial install. This particular phone was originally running on vivid. I then changed to OTA4RC. I think it then changed itself to stable and I did manual updates as appropriate. It was running OTA6 for what seems like ages.   I completely missed the update to 7 in January then forgot about updates as I now have a second N5 which has always been on the dev channel and I upgrade usually each week to 10 days.

**Comment by JassMan23** [comment]
Perhaps we should just write this off as one of those strange quirks which sometimes take over the phone. I have just found the time to deliberately restart the phone and fail to enter the SIM PIN. The above mentioned unlock SIM button now works perfectly.   
Since it is working I have no way to know whether the repower had a different effect from restart, but it does seem as though something changed.   

My phone obviously had some kind of issue because  of the lack of OTA7 & 8 but a quick check of all my other apps shows improvements in some apps and no new bugs have become obvious (yet).

**Comment by JassMan23** [comment]
Seems I closed this too early.  Just received notification of 2 updates available (camera and openstore) but underneath it says Recent updates: **Ubuntu Touch version 7**, updated **5 July**. The trouble is that the update occurred on the **3rd**. Even allowing for Time offsets it shouldn't read 2 days different and although it says v7, when I look in System... About.. it says: Software Ubuntu 16.04 (**OTA9**) last updated **20/05/2019**  
What is going on?  
Is it possible that it really was on OTA7 even though I checked Sys.About when 9 was announced as coming soon and it definitely said I was on OTA6 (I didn't note the date) - again I never accepted any system updates since last year (or possibly January) but I have repowered so maybe an unannounced  7 update occurred and self installed during a re-power then reported itself as 6 in the about screen.   
The only system update I have EVER clicked on the INSTALL button was when I upgraded to OTA4RC

I have noticed on my dev phone that the date assigned to sys updates stays fixed if there was a new app update since it was installed but if a second sys upated occurs and there were no app updates, the previous sys update date changes to the current date. You then appear to have 2 sysupdates on he same day, if another app update then comes in.

**Comment by JassMan23** [comment]
Seems I closed this too early.  Just received notification of 2 updates available (camera and openstore) but underneath it says Recent updates: **Ubuntu Touch version 7**, updated **5 July**. The trouble is that the update occurred on the **3rd**. Even allowing for Time offsets it shouldn't read 2 days different and although it says v7, when I look in System... About.. it says: Software Ubuntu 16.04 (**OTA9**) last updated **20/05/2019**  
What is going on?  
Is it possible that it really was on OTA7 even though I checked Sys.About when 9 was announced as coming soon and it definitely said I was on OTA6 (I didn't note the date) - again I never accepted any system updates since last year (or possibly January) but I have repowered so maybe an unannounced  7 update occurred and self installed during a re-power then reported itself as 6 in the about screen.   
The only system update I have EVER clicked on the INSTALL button was when I upgraded to OTA4RC

I have noticed on my dev phone that the date assigned to sys updates stays fixed if there was a new app update since it was installed but if a second sys upated occurs and there were no app updates, the previous sys update date changes to the current date. You then appear to have 2 sysupdates on he same day, if another app update then comes in.

**Comment by UniversalSuperBox** [comment]
> Ubuntu Touch version 7, updated 5 July. The trouble is that the update occurred on the 3rd.

Please see the following issue for more information: https://github.com/ubports/ubuntu-touch/issues/1139

Updates will occur if the Recovery image is booted and there is an update waiting to be installed -- "Reboot and Install" only reboots the device to recovery for you.

The number that we alias an image to ("OTA-9") is separate from the build number of the image (7). The build number is shown on the updates page, the alias is shown in About. **Update 7 is not OTA-7**.

It is not possible for an update to occur without "About" showing the new update. The image name and number are written into the image, which is then signed with the system-image-server's GPG key and verified before installing.

It seems like all the issues discussed in this thread were either fixed or are reported elsewhere, so I'll close this thread now.

PS: nice cat.

![IMG_20180117_064739_750](https://user-images.githubusercontent.com/21966173/60984791-e4c63300-a301-11e9-9cd2-f648801ce354.jpg)
