### ISSUE TITLE
App icons visible behind scope header

### ISSUE THREAD

**Issue by Aurnytoraink** [ubports/ubuntu-touch#1175]
- Device: Nexus 7 (2013 Wifi)
- Channel: Development
- Build: 20190704-32398

### Steps to reproduce
I don't know. It's random

### Expected behavior
Just normally display the home screen

### Actual behavior
Well, sometimes home screen looks like this
![screenshot20190706_152953682](https://user-images.githubusercontent.com/28545669/60757275-c530c100-a008-11e9-950b-c5e515cfd1af.png)

### Logfiles and additional information
No

**Comment by UniversalSuperBox** [comment]
It's unclear whether this would be in the [unity8-dash QML](https://github.com/ubports/unity8/tree/xenial/qml/Dash) or [the app scope's C++](https://github.com/ubports/unity-scope-click). Either way, it wouldn't be very easy to allow the dash background to show through and keep the text visible. I'll leave these links here so anyone who would like to investigate can do so. However, note that all scopes (including the app scope) are being replaced with the Drawer in [the Mir and Unity8 upgrade](https://github.com/orgs/ubports/projects/10), so this issue might not get any attention.

**Comment by mateosalta** [comment]
Scopes are now gone, so I think we can close this bug.
