### ISSUE TITLE
Cannot close app after uninstalling it on edge

### ISSUE THREAD

**Issue by jld3103** [ubports/ubuntu-touch#1177]
- Device: Nexus 5
- Channel: edge
- Build: 2019-07-05

### Steps to reproduce

 - Install any app
- Open it
- Uninstall it
- Switch to app selection
-> App fades out and is not close able

### Expected behavior
App should be close able

### Actual behavior
App fades out and is not close able.
The app doesn't respond to user inputs anymore.

**Comment by prog66** [comment]
On hammerhead i can't uninstall app ...

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/qtmir/pull/26

@prog66, that is a separate issue. You can currently uninstall apps from the OpenStore.
