### ISSUE TITLE
[Release Candidate] SMS disappearing / not appearing in the apps

### ISSUE THREAD

**Issue by Flaburgan** [ubports/ubuntu-touch#1182]
- Device: Fairphone 2
- Channel: Candidate
- Build: 2019-W27/2

### Steps to reproduce
Receive a SMS and tap on the notification

### Expected behavior
The SMS app opens, the SMS is displayed

### Actual behavior
The SMS app doesn't open. When opening the SMS app, the received SMS isn't present.

I am not able to reproduce this morning but it happens twice to me yesterday evening. I'm not sure what I did exactly but I am sure a read SMS in the notification but am not able to find them in the app anymore.

**Comment by Flaburgan** [comment]
Btw I just switched from stable to RC yesterday and this never happened in stable.

**Comment by kugiigi** [comment]
I'm on stable on my MX4 and I think I'm also hitting this.
I had a notification which I cleared and when I opened the messaging app later on, that message wasn't there. I think I've had this same scenario at least twice.

The thing is I'm not exactly sure and my memory is a bit cloudy and I might be just dreaming 😅

**Comment by lduboeuf** [comment]
is this bug still happening ?

**Comment by Flaburgan** [comment]
I only encountered it twice and that was when I open the issue. No other occurence for months. If @kugiigi confirms, I'll close this.

**Comment by Flaburgan** [comment]
No news from @kugiigi and I never had it again, I'm closing this.
