### ISSUE TITLE
"No space left on device..." message in Camera app even with enough free space

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1185]
- Device: Meizu MX4
- Channel: Stable
- Build: OTA-9

### Steps to reproduce
1. Open the camera app.

### Expected behavior
The camera can shoot pictures and videos.

### Actual behavior
A message shows that there's no enough space and it's not possible to take pictures or videos.

### Logfiles and additional information
I still have 1.5GB of free space according to the system settings app. Deleting some photos from the camera app can sometimes remove the message. Clearing app data/cache/config doesn't help as well.

![screenshot20190802_152633814](https://user-images.githubusercontent.com/29456786/62355940-47c97500-b510-11e9-9e72-caa8342ff546.png)

[application-click-com.ubuntu.camera_camera_3.0.2.txt](https://github.com/ubports/ubuntu-touch/files/3460297/application-click-com.ubuntu.camera_camera_3.0.2.txt)

**Comment by UniversalSuperBox** [comment]
It's possible that there's space *somewhere*, but not in the data partition. Could we see the output of `df -h` on the device?

**Comment by kugiigi** [comment]
[space.txt](https://github.com/ubports/ubuntu-touch/files/3479656/space.txt)

Looks like you are right. It's weird that I get so many spaces left on other partitions but not on my userdata 😅

**Comment by UniversalSuperBox** [comment]
Well, you could file another bug since the space detection code is obviously faulty, but I believe this issue can be closed as invalid then.

**Comment by geeky-neo** [comment]
[NoSpaceLeftOnDevice.txt](https://github.com/ubports/ubuntu-touch/files/4572625/NoSpaceLeftOnDevice.txt)

Space is available in /userdata, still the camera app shows the same message.
Using ubports_GSI_installer_v5.zip
Device : Poco F1 Beryllium

@kugiigi @UniversalSuperBox , were you able to resolve this issue ?
