### ISSUE TITLE
no onscreen keyboard available

### ISSUE THREAD

**Issue by nic00o** [ubports/ubuntu-touch#1189]
### Illustrations

- Device:Fairphone2
- Channel:
- Build:

### Actual behavior

There is no onscreen keyboard available when starting the phone.

**Comment by UniversalSuperBox** [comment]
Hello @nic00o,

We'll need more information to help you solve this problem. Did you just install Ubuntu Touch? Which version are you running? Please see https://docs.ubports.com/en/latest/contribute/bugreporting.html for more information on finding the information we'll need to help.
