### ISSUE TITLE
Missing Sync Button Contacts App (Edge Channel)

### ISSUE THREAD

**Issue by lakotaubp** [ubports/ubuntu-touch#1190]
### Illustrations

- Device: OPO, Nexus 5
- Channel: Edge
- Build: 2019-08-09/2

### Steps to reproduce

Open Contacts App
### Expected behavior

Sync Button to be top right hand corner between settings and search

### Actual behavior

Button not there. Settings and search are.

**Comment by mariogrip** [comment]
Fixed by: https://github.com/ubports/buteo-syncfw/pull/1
