### ISSUE TITLE
Google account key change invalidates authentication, can't sign back in

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1191]
- Device: *
- Channel: rc, devel
- Build: 2019-W32 or newer

### Steps to reproduce

1. Sign in with your Google account on stable OTA-9
1. Sync calendars
1. Upgrade to rc or devel
1. Sync calendars

### Expected behavior

Calendars sync, or I receive a message asking to re-authenticate to Google account and can re-authenticate successfully

### Actual behavior

![I am asked to re-authenticate, but re-authentication fails](https://user-images.githubusercontent.com/21966173/62954420-f98c5f80-bdb4-11e9-8b6f-b07c01aa1c1e.png)

### Logfiles and additional information

[application-legacy-syncmonitorhelper-.log](https://paste.ubuntu.com/p/2X4rhCF2M3/)
[sync-monitor.log](https://paste.ubuntu.com/p/97G5X8YvJz/)
[signond debug log](https://paste.ubuntu.com/p/pqyp3Vphy9/)

It should be noted that the signond log happens entirely before syncmonitorhelper appears. There are no errors in either sync-monitor.log or signond's logs after syncmonitorhelper starts. `online-accounts-service`, when run for debug logging, is completely silent.

**Comment by mardy** [comment]
`online-accounts-service` cannot be completely silent: the error `"App 'com.ubuntu.calendar' cannot act as 'com.ubuntu.calendar'"` comes from there, and I know that it's quite verbose. It may be that there was already an instance of it running, so the one you started was left detached from D-Bus. I won't have my testing device with me for some days, so if you are able to reproduce it again, that would be helpful. :-)

**Comment by UniversalSuperBox** [comment]
This appears to be deeper. libaccounts-glib expects `~/.local/share/accounts/applications/com.ubuntu.calendar.application` to exist as an XML file. However, `~/.local/share/accounts/applications/com.ubuntu.calendar_calendar` exists instead.

**Comment by UniversalSuperBox** [comment]
This issue has been fixed and is shipping to the repository now. It will be included with tonight's devel and edge images. Installing these images should allow you to test the fix for this issue, if you were affected. We'll have that to test tomorrow, push it to RC later tomorrow evening (CDT), and continue testing for a stable release on (hopefully) Friday.

**Comment by giiba** [comment]
OPO 2019-W33

Tried today and it seems to work, I had to reauthenticate and it went smoothly.
