### ISSUE TITLE
Sound gauge inconsistent between setting menu and physical buttons.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1196]
### Description of the feature
I noticed that two sound-gauges co-exists. One accessible with the setting menu, the second with the physical buttons. The last one seems to be the "master".

- Device: Mako, LG Nexus 4
- Channel: Stable, OTA-9

### Steps to reproduce
-Go and increase sound volume with the setting menu.
-Quit the setting menu and mute sound with the physical button.
-Now, phone calls or notifications will be silent.
Yet, if you go back to the setting menu the sound gauge didn't change.

### Expected behavior
A consistent behaviour between gauge, accessible with menu and physical button

**Comment by wayneoutthere** [comment]
good day. 
First, I tried your steps above with my development channel and could not make the bug happen
Then I installed your stable channel (OTA-9)
Still I could not replicate.

Whether I use physical buttons or system setting sound buttons, they always match perfectly.
