### ISSUE TITLE
New Wallpapers / Wallpaper contest?

### ISSUE THREAD

**Issue by Scott-Marley** [ubports/ubuntu-touch#120]
Ubuntu Touch hasn't seen any new wallpapers in forever (or ever), so it'd be nice when the project hits a new milestone that these could be updated, perhaps via a community contest like desktop ubuntu does each release?

Also, an option to have these as a slideshow, or randomly chosen every time the phone wakes up from sleep mode would be nice too. 

![screenshot20170619_092954222](https://user-images.githubusercontent.com/29573528/27333680-0ce4bb1e-560a-11e7-97ce-61b2bf6baee6.png)

**Comment by tomoqv** [comment]
+1

**Comment by NeoTheThird** [comment]
Not a bad idea. I especially like the randomly-chosen-on-every-boot one. Let's put it on the list, shall we?

**Comment by Flohack74** [comment]
Maybe smth for the marketing team, to get a contest done?

**Comment by NeoTheThird** [comment]
@Flohack74 Yes, that'd be cool. But let's wait until 16.04 is really heating up.

**Comment by mymike00** [comment]
> I especially like the randomly-chosen-on-every-boot one.

maybe the choose randomly from only few wallpapers I selected before...

**Comment by ChloeWolfieGirl** [comment]
We'll have to do what canonical did with theres.

I beleive they did theres using flickr groups.
Something thats also good because we have a flickr uploader on the ubuntu phone.

It also has to be cc under a license so we can use there photos without getting a lawsuit.

**Comment by Flohack74** [comment]
BTW the contest is happening now: https://ubports.com/de_DE/blog/ubports-blog-1/post/16-04-ubuntu-touch-cultural-showcase-149 - shall we close this ticket ;)

**Comment by Flohack74** [comment]
Contest has been finished ;)
