### ISSUE TITLE
What happened to the indicator-datetime?

### ISSUE THREAD

**Issue by Daniel20000522** [ubports/ubuntu-touch#1200]
- Device: Nexus 5
- Channel: RC
- Build: 2019-W33/2

I would like to know why indicator-datetime translations are blocked.

### Steps to reproduce
See the Time and Date indicator

### Expected behavior
The words are translated

### Actual behavior
The words are not translated.

**Comment by Flohack74** [comment]
The translation file became corrupt but if I recreate it, we loose all translations for all languages. I dont want to do this but instead try to work with the guys from Weblate to find a way to save it.

**Comment by Daniel20000522** [comment]
May it succeed.
