### ISSUE TITLE
Google online account broken

### ISSUE THREAD

**Issue by dekkerj1** [ubports/ubuntu-touch#1202]
### Illustrations

Can't create google online account
- Device: BQ M10
- Channel: RC
- Build:2019-W33/2

### Steps to reproduce

After sign in with username / password I get the message "Sign in with Google temporarily disabled for this app. The app has not been verified yet by Google in order to use Google sign in."

### Expected behavior

Added google online account

### Actual behavior

Account is not available, Google Contacts won't sync and Google Calendar is not available.

**Comment by Flohack74** [comment]
Can you please re-test this with OTA-10 or even better, the now upcoming OTA-11?

**Comment by dekkerj1** [comment]
Hi, I'm on channel release candidate. Today I did a re-test with Ubuntu touch version 60, OS build number 2019-W41/2 (most recent update, installed today). Unfortunately the same error.

**Comment by dekkerj1** [comment]
Installed version 61 (release candidate) still the same error on BQ M10. No problem on OnePlus One.

**Comment by zubozrout** [comment]
Well, actually I can confirm it on devel 2019-11-07, device Meizu MX4 Arale. Maybe a reinstall eould fix that but my old Google account could be no longer used. I clicked on calendar sync and a message about me wanting to re-login popped up. And when I went throufh and logged in, it just said the app is not authorized. Same if I deleted the old account in the settings app and tried to re-login.

**Comment by zubozrout** [comment]
Ok, seems submitting the screenshot didn't work at all in Morph despite I selected it to be uploaded. So here it is - cropped a bit to not occupy half the page. There is an entire empty white screen bellow it with only a cancel button at the bottom of the screen. Unfortunately the message is in Czech, but is precisely the message this report has in its initial post ^.

![screenshot20191108_092849629](https://user-images.githubusercontent.com/3088349/68489500-82495900-0247-11ea-909f-b239fc603eb5.png)

**Comment by zubozrout** [comment]
Hm, and this seems to be what I got before I removed my at one point functional Google account sync from the device: [sync-monitor.log.txt](https://github.com/ubports/ubuntu-touch/files/3825309/sync-monitor.log.txt)

**Comment by zubozrout** [comment]
Hm, switching back to stable fixed this for me. So it is probably only broken on devel.

**Comment by zubozrout** [comment]
And switching back from stable to devel seems to keep this functional :).

**Comment by mardy** [comment]
The solution for this bug is to restore the patch that was reverted in https://github.com/ubports/account-plugins/pull/34
However, there's still the issue that automatic calendar sync does not notify the user when it fails (https://github.com/ubports/ubuntu-touch/issues/1195), and that's not trivial to fix.

**Comment by mariogrip** [comment]
humm, so now i get a new error? It says my *browser* is not secure?

**Comment by mariogrip** [comment]
moved it back to in progress at it does not work yet :)

**Comment by mardy** [comment]
For everyone still affected by this bug: please provide the logs for `online-accounts-service` as described here: https://docs.ubports.com/en/latest/systemdev/online-accounts.html#account-creation-issues

Also, someone in the [forums](https://forums.ubports.com/topic/3633/calendar-synchro-with-gmail/8) suggested that changing the device language to English would fix the issue; could someone else also try that, and see if that helps?

**Comment by UniversalSuperBox** [comment]
Oh boy, we're affected by this: https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/

**Comment by mardy** [comment]
> Oh boy, we're affected by this: https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/

I'm not sure. Some people (including myself) can create the account just fine, some others report that the error explicitly mentions that the app is not validated with Google. I actually suspect that for some reason the old key is still used in these devices.

So, please, if you are affected by this bug, post a screenshots and the logs from the online-accounts-service as explained in https://docs.ubports.com/en/latest/systemdev/online-accounts.html#account-creation-issues

**Comment by UniversalSuperBox** [comment]
It's interesting, I can also sign in normally on the OnePlus One, Nexus 7, and Xperia X. To sign in on the Xperia, I changed my language to German. Still no dice getting it to fail...

Someone who's out there with this error, please help!

**Comment by Flohack74** [comment]
I tried on my newly ported Samsung S3 Neo and immediately got this popup. I can try on a few other devices as well... maybe there is kinda cookie in place for people that have already signed in successfully before? Or its randomly seeded by Google around the world.

**Comment by giiba** [comment]
I am on the latest development release and I still get this error after each new update.

I click the notification to log in again, choose my account (there is only the one) and usually get a "failed to login" message, and try again a few times before it suddenly works. At least until the next update.

I am adding this comment because I also log into the same calendar with an install of Ubuntu 18.04 on my laptop and never experience a problem. I logged in once about a year ago and it still works flawlessly. Maybe the solution can be found in the account sync there?

**Comment by j2g2rp** [comment]
There were any changes on this?
I can't reproduce the problem on last RCs on N5 or M10FHD. Works fine for me on both devices.

**Comment by UniversalSuperBox** [comment]
It randomly works or does not work. It's different for every user. Maybe some "score" that Google uses to determine if logging in via the Morph WebView we use is safe for the user? It's hard to say.
