### ISSUE TITLE
launcher does not respond when launcher was disabled on other channel

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1203]
### Description of the feature
After moving from devel channel to edge, the launcher does not respond. It appears once, no actions are possible, and then disappear.

### Illustrations

- Device: N5
- Channel: edge
- Build: today

### Steps to reproduce

Disable the launcher (e.g with UT Tweak Tool) with your current image, then Install edge on the device: The launcher is not usable anymore.

### Expected behavior

Device is usable, i can use the launcher

### Actual behavior

launcher does not respond to touch events

### Logfiles and additional information
<!-- https://docs.ubports.com/en/latest/contribute/bugreporting.html#getting-logs --

**Comment by lduboeuf** [comment]
if the launcher is now on Unity8 the single entry point, maybe something need to be protected

**Comment by UniversalSuperBox** [comment]
This was added by https://github.com/ubports/unity8/commit/bb50476d40a7d64b0fe94e8e822466eddca44355, and the point it was added to UT Tweak Tool has been lost to history.

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/unity8/pull/179
