### ISSUE TITLE
GPS takes a long time to find location in OTA-10

### ISSUE THREAD

**Issue by ChristianPauly** [ubports/ubuntu-touch#1205]
- Device: Hammerhead
- Channel: Stable
- Build: OTA-10

I'm not 100% sure that this bug may only affect me or all hammerheads. But on Android on the same device it seems to work so this looks like a new bug to me...

### Steps to reproduce
Open uNav or Google apps and try to find your location.

### Expected behavior
Location is found in a couple of seconds. on Android with the same hardware this seems to work fine.

### Actual behavior
Location can't be found. Sometimes after waiting a very long time (around 10 minutes) it can be found and then work fine.

### Logfiles and additional information
![screenshot20190823_120154526](https://user-images.githubusercontent.com/24619905/63584750-e12ef880-c59d-11e9-9c2b-4896056e0272.png)

**Comment by ferrettim** [comment]
Not a bug this is working as intended:

"We have removed the "wolfpack" Wi-Fi based geolocation tool from this update. This module used the Geoclue service to gather approximate location data. That resulted in a very fast location lock in some cases, but a very inaccurate lock in others. Removing the module improves the reliability of the location service in almost all cases.

With this module removed, some users will experience a very long delay (20 minutes or more) in retrieving the first location fix on their device. This should only occur if the device is not connected to a mobile network and location services have not been used for a very long time. After this delay has passed, future attempts to retrieve a cold (first time each boot) location lock will take up to four minutes. To help users make the best use of Ubuntu Touch location services and to help avoid this problem, we have written a guide Using location services and have added it to our documentation pages."

**Comment by ChristianPauly** [comment]
I've tested on my device with full system wipe. No GPS connection after 20 minutes of waiting. This can't be intended. Maybe its just my device's GPS (very old Nexus 5) but anyway I'm sure that such a  delay would disappoint new users. :-( If someone finds a way how we could improve this, it would be very helpful.

**Comment by dobey** [comment]
> Location is found in a couple of seconds. on Android with the same hardware this seems to work fine.

On Android, with enhanced AGPS features (wifi/bt device scanning for location) disabled, and using only GPS and AGPS by cell tower positioning, how long does it take?

Does your device have reliable data connection with SIM installed when trying to get location? Are you only trying with sensors status app, or uNav or other apps?

**Comment by ChristianPauly** [comment]
> > Location is found in a couple of seconds. on Android with the same hardware this seems to work fine.
> 
> On Android, with enhanced AGPS features (wifi/bt device scanning for location) disabled, and using only GPS and AGPS by cell tower positioning, how long does it take?
> 
> Does your device have reliable data connection with SIM installed when trying to get location? Are you only trying with sensors status app, or uNav or other apps?

On the device I have tried with uNav, google maps webapp and sensor status app. I will check out about the android specific questions and post later

**Comment by dobey** [comment]
Oh, also are you trying to get GPS indoors, in the middle of a city, or in a clear open area? Line-of-sight is basically required for the sat signals, so fewer obstructions makes for much faster location fixing.

**Comment by ChristianPauly** [comment]
Ah okay, when I turn off enhanced AGPS then Android isn't finding my location too. So it looks like my Nexus 5 GPS is broken on hardware side... 😭

Thank you very much for the support and sorry for opening this issue. I will close it now.

**Comment by dobey** [comment]
> Ah okay, when I turn off enhanced AGPS then Android isn't finding my location too. So it looks like my Nexus 5 GPS is broken on hardware side... 

I don't think the hardware is broken. I think you're just hitting the "everything around me is an obstruction" issue, and it will take a long time. If you try in an open area with a good data connection, I think it will get a fix fairly quickly. But buildings, mountains, trees, etc… all interfere with satellite signals.

**Comment by Flohack74** [comment]
Rodney I still doubt that aGPS with cell towers work just so on UT. is there any evidence that it doesnt use an Android service to query rild and the network, and then inject this into location backends? because then it will always be GPS cold boot issue

**Comment by dobey** [comment]
> Rodney I still doubt that aGPS with cell towers work just so on UT. is there any evidence that it doesnt use an Android service to query rild and the network, and then inject this into location backends? because then it will always be GPS cold boot issue

It definitely works, because if I take the SIM out of my nexus 4 and leave it sit in the window to get a fix, it basically never happens. With a SIM in it, then it gets a fix, though it takes quite a long time sitting in the window sill. I haven't tried it outside in the clear, as it's not an activated SIM.
