### ISSUE TITLE
Open-session panel?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1207]
### Description of the feature
Hello,
Here I would like to report a strange, spontaneous and not reproducible issue*.
After waking-up the phone, an open-session panel (that I have never seen before) appeared for a very short time and disappeared. The screen shown a field "open session" in the middle of a white window. That was very furtive so I cannot provide with details. No app was opened.
Then the phone came back to a normal state without any action from me.

*It is not problematic at all and happened once. But it worth spreading the info I guess.

- Device: mako
- Channel: Stable, OTA-10

**Comment by UniversalSuperBox** [comment]
Hi @Thieb67k,

Has this ever occurred again?

**Comment by Thieb67k** [comment]
Hello,
No, that happened once.
If no one saw that, we can close the issue I guess.

**Comment by lduboeuf** [comment]
:+1:
