### ISSUE TITLE
SIM not detected on Nexus5

### ISSUE THREAD

**Issue by IanHasman** [ubports/ubuntu-touch#1213]
[not relevant]

**Comment by dobey** [comment]
> Should I go to my provider and see if they can correct the SIM?

What provider are you using? Is the SIM not detected by UT, or is it just that it fails to register to the network?

**Comment by lduboeuf** [comment]
any news IanHasman ?

**Comment by IanHasman** [comment]
Sorry, new to this and haven't got the hang of it yet. Please be tolerant.

I did reply to this issue by email.... but now I can't find it or I would post it here. The basic gist of the reply was that the problem was indeed caused by a VERY old SIM that had been cut down by 3 (my provider) to make it into a micro SIM. It would appear that it was too thick. The replacement SIM they sent was much thinner and works perfectly. My Nexus 5 is now working as expected. As far as I am concerned this problem can now be closed. Thank you for asking.

I'm looking forward to seeing how things evolve with ubports. I have to say that so far the experience has been good. More things work than don't work!
