### ISSUE TITLE
Can't set root password to sign in with su

### ISSUE THREAD

**Issue by tallero** [ubports/ubuntu-touch#1214]
- Device: Hammerhead
- Channel: stable
- Build: Ubuntu 16.04.6 LTS (GNU/Linux 3.4.0-cyanogenmod-g2669fa0 armv7l)

### Steps to reproduce

    # sudo su
    # passwd
    passwd: Authentication token manipulation error
    passwd: password unchanged

### Expected behavior
Root password should be set.

### Actual behavior
Changing password fails.

### Logfiles and additional information

I was trying to set a root password to set `zsh` as main shell (#1215) with `chsh`.

**Comment by dobey** [comment]
Ubuntu Touch is not a traditional linux distribution, and making changes to rootfs as such is not supported. So closing this.

**Comment by tallero** [comment]
> Ubuntu Touch is not a traditional linux distribution, and making changes to rootfs as such is not supported. So closing this.

The [developer user guide](http://docs.ubports.com/en/latest/systemdev/testing-locally.html#building-on-the-device-itself) mentions that it is possible to build and test on device, so someone can happen to make changes to rootfs.

I thought it could be interesting (for anyone with the will to do it) to know how it was made technically possible that one can `sudo` but can't `su` and/or change this behaviour.

**Comment by Flohack74** [comment]
Ubuntu always preferred sudo way, so on a normal desktop installation you also cannot use su. I think they wanted it just to be so.

**Comment by dobey** [comment]
> The [developer user guide](http://docs.ubports.com/en/latest/systemdev/testing-locally.html#building-on-the-device-itself) mentions that it is possible to build and test on device, so it can happen to make changes to rootfs.

This should be updated to direct people how to build something inside a libertine container then. The rootfs is not a sensible place to be doing that.

**Comment by tallero** [comment]
>Ubuntu always preferred sudo way, so on a normal desktop installation you also cannot use su. I think they wanted it just to be so.

I know it, just it has never been mandatory to do in a way or in the other. 

> > The [developer user guide](http://docs.ubports.com/en/latest/systemdev/testing-locally.html#building-on-the-device-itself) mentions that it is possible to build and test on device, so it can happen to make changes to rootfs.
> 
> This should be updated to direct people how to build something inside a libertine container then. The rootfs is not a sensible place to be doing that.

That developer guide is about building system software, not containerized user software in any case, so changes to rootfs still have to happen, otherwise how can you test them? Certainly it would be less feasible to generate a debug OTA every time.
In any case the software does not [build](https://github.com/ubports/keyboard-component/pull/89) (have to open another issue for that, I know).

**Comment by dobey** [comment]
> That developer guide is about building system software, not containerized user software in any case, so changes to rootfs still have to happen, otherwise how can you test them?

Well, you can build them in the container, which gives you plenty of room to install all the extra build dependencies, and then after building the debs you can simply use `dpkg -i` after making rootfs writable to install them there, for testing. This is much less problematic than using apt in rootfs.

**Comment by tallero** [comment]
>Well, you can build them in the container, which gives you plenty of room to install all the extra build dependencies, and then after building the debs you can simply use dpkg -i after making rootfs writable to install them there, for testing. This is much less problematic than using apt in rootfs.

I guess that is because container environment is xenial.

OT: Can one upgrade a xenial container to latest ubuntu release?

**Comment by dobey** [comment]
> OT: Can one upgrade a xenial container to latest ubuntu release?

It is theoretically possible, but not advisable due to ABI incompatibilities in newer releases versus 16.04, and the fact that the UT packages aren't necessarily available in other releases, as they were removed from Ubuntu after 17.04 release.
