### ISSUE TITLE
Can't set zsh as default shell

### ISSUE THREAD

**Issue by tallero** [ubports/ubuntu-touch#1215]
- Device: Hammerhead
- Channel: stable
- Build: Ubuntu 16.04.6 LTS (GNU/Linux 3.4.0-cyanogenmod-g2669fa0 armv7l)

### Steps to reproduce
Install zsh

    # mount -o remount,rw /
    # apt install zsh

Try to set it as default shell with

    $ chsh -s $(which zsh)
    $ sudo chsh -s $(which zsh)
    # chsh -s $(which zsh)
 
fails when entering the password, maybe because `chsh` calls `su` instead of `sudo`. So I tried to set a root password in #1214.

### Expected behavior
`zsh` should be set as default shell

### Actual behavior
The command fails with any password.

After trying various solution found on the internet involving `pam` I noticed `phablet` user was not anymore in `passwd` file (it was there, right?).

So I tried re-adding it but I set it up with a wrong UUID (I set 1000; I see from `stat /home/phablet` that `UUID` is `32011`) and now I am kicked out of the phone.

EDIT: I resetted the UUID in `/etc/passwd` mounting the `system.img` disk in recovery.

**Comment by Flohack74** [comment]
1. Any change you do to the system will be overwritten with the next OTA update, so in general we do not recommend to install any packages manually
2. Try sudo usermod -s /usr/bin/zsh $(whoami)

**Comment by dobey** [comment]
As installing packages with apt and making changes to rootfs as such is not supported, I'm closing this. If you really need to use zsh as a terminal, with plenty of other CLI tools, the supported way would be to do so in a libertine container. You can install zsh in there (but sudo won't work and installing it will break things, as libertine is an unprivileged container), and run `libertine-launch -i <container_id> zsh` to get a shell inside libertine with zsh once you've installed it.

**Comment by tallero** [comment]
>As installing packages with apt and making changes to rootfs as such is not supported, I'm closing this. If you really need to use zsh as a terminal, with plenty of other CLI tools, the supported way would be to do so in a libertine container. You can install zsh in there (but sudo won't work and installing it will break things, as libertine is an unprivileged container), and run libertine-launch -i <container_id> zsh to get a shell inside libertine with zsh once you've installed it.

So one should write a desktop file to directly open a terminal inside the container, with zsh preloaded, because what I wanted was a user terminal?.

I thought it since OTA were [snapshots](https://github.com/ubports/keyboard-component/pull/90#issuecomment-525839948) that was possible to keep the phone updated just `apt`ing

> Try sudo usermod -s /usr/bin/zsh $(whoami)

it worked after editing `/etc/passwd` such that

    phablet:x:<UUID>:<UUID>:phablet:/home/phablet:/usr/bin/zsh

**Comment by dobey** [comment]
> So one could write a desktop file to directly open a terminal inside the container, with zsh preloaded, because what I wanted was a user terminal.

As the native terminal app is a click package, and not a system service, this would perhaps be difficult to do, though it is theoretically possible.

> I thought it since OTA were [snapshots](https://github.com/ubports/keyboard-component/pull/90#issuecomment-525839948) that was possible to keep the phone updated just `apt`ing

That is partly why you can't update the phone using apt. The rootfs is a loopback image of a fixed size, and the partitioning scheme means some packages would fail to install properly, while the "disk" will fill up to 100% very quickly (typically just attempting to run `apt-get update` itself will do this).

You can of course do whatever you want to your own device, but you will have to keep the broken pieces, as these are not supported.

**Comment by tallero** [comment]
Yup, I see the application root is under

    /usr/share/click/preinstalled/com.ubuntu.terminal/

and its desktop file is not in `/usr/share/applications`.

**Comment by dobey** [comment]
> So, do you confirm that `apt upgrade` is equivalent to an OTA upgrade in terms of changes and apart from support?

No, because rootfs is only a part of the OTA. They are not the same at all.
