### ISSUE TITLE
Openstore does not show any applications

### ISSUE THREAD

**Issue by keitalbame** [ubports/ubuntu-touch#1216]
- Device: Nexus 7 LTE (flo)
- Build: 16.04 LTS armf 20190815

This device was installed using ubuntu touch appimage installer.
This issue keeps happening even after device full reset.

### Steps to reproduce
1. Open Openstore
2. Discover tab does not show any apps. Spinning icon is seen
3. Categories tab is empty
4. Search works but it is not possible to install any application
5. Unable to uninstall any app from My Apps tab.

### Expected behavior
1. Discover tab shows apps
2. Categories tab is populated
3. Search allows to install applications
4. Uninstall any application that is already installed

This issue seems similar to #572 and #725

**Comment by Flohack74** [comment]
Openstore has server issues, and its being worked on. If you feel you would need more infos in such a case, like an error message in the store app, please file a ticket on their GH project.

please note that Openstore is not run by UBports and we have no control over their infrastructure.
