### ISSUE TITLE
Ringtone rings from bluetooth earphones and not from device

### ISSUE THREAD

**Issue by Thanasis1101** [ubports/ubuntu-touch#1217]
- Device: Nexus 4
- Channel: Stable, OTA-10
- Build: 2019-08-15

### Steps to reproduce

1. Connect bleutooth earphones to device.
2. Make a call to this device from another device.

### Expected behavior

The ringtone rings from the device **and** from the bluetooth earphones.

### Actual behavior

The ringtone rings **only** from the bleutooth earphones.

### Logfiles and additional information

- This issue did not exist on version 15.04.
- I have tested it on all versions from OTA-4 to OTA-10 and the issue is always there.
- [UBports Forum discussion for this issue](https://forums.ubports.com/topic/2277/ringtone-rings-from-bluetooth-earphones-and-not-from-device)

**Comment by Flohack74** [comment]
Well that request is a bit of discussion and opinion. I am not sure if the device really should ring via its speaker, too, since the intended recipient, that is you wearing the headphones, can already here it from there. Do not pollute your environment with superflous ring tones ;)

**Comment by Thanasis1101** [comment]
@Flohack74 Nowadays every android and iphone smatphone, even basic cell phones behave in this manner (ring from both the earphones and the device).
Also, the receiver doesn't wear the headphones all the time, but wears them when he hears the incoming call.
So it's not an opinion, but a serius problem for every bluetooth earphones user.

**Comment by Flohack74** [comment]
Ok at least thats an argument (not wearing them)... :)

**Comment by toastedsocks** [comment]
I have a similar issue on OnePlus One, I always take calls with headphones plugged in (or a handset with an integrated mic and speaker). I'd like to be able to set the ringtone to sound through the external speaker of the phone, it's a feature request if anyone has an interest in addressing this issue, cheers.

**Comment by UniversalSuperBox** [comment]
Since there are multiple similar reports, I have opened https://github.com/ubports/ubuntu-touch/issues/1795 to replace them. Please continue further discussion there.
