### ISSUE TITLE
Scopes "My Video" and "Video" do not allow sorting videos by name

### ISSUE THREAD

**Issue by paulmueller** [ubports/ubuntu-touch#122]
Please allow sorting videos by name in the scopes. Currently, it seems like they are sorted according to 'date added to the phone'. This issue affects at least E4.5 and M10fhd.

**Comment by Flohack74** [comment]
Scopes will get a major overhaul, so at the moment we are not working on that. Sorry for the delay.

**Comment by lduboeuf** [comment]
as scopes gone now, that issue is not relevant anymore
