### ISSUE TITLE
Huge regression in release candidate: infinite loop in NetworkManager make the CPU 100% and kill the phone in minutes

### ISSUE THREAD

**Issue by Flaburgan** [ubports/ubuntu-touch#1222]
- Device: Fairphone 2
- Channel: Release candidate
- Build: This week release candidate build (2019-W36 20190903-6745). I was previously running the week 33 build, so just after the OTA-10 release, without any problem.

### Steps to reproduce
Simply boot the phone

### Expected behavior
The phone works normally

### Actual behavior
It looks like the problem is around the Wi-Fi connection. It is disabled, but the icon in the status bar constantly shows and hides (before, it was always shown even if not connected). The phone is heating a lot, is really slow (all the CPU is eaten) and the battery lost 20% in 10 minutes! The phone also is slow to boot, and even `adb shell` isn't responsive. 

### Logfiles and additional information
`.cache/upstart/unity8.log` is full of `[2019-09-05:11:54:18.009] "No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/ActiveConnection/X` where X increase, not sure if related.

Same goes for the network manager indicator logs, full of `Debug: Device Added: "/org/freedesktop/NetworkManager/Devices/X" ((null):0, (null))` where X also increases.

Here is a screenshot of top, with a scary load average:

![top](https://user-images.githubusercontent.com/930064/64338871-092d4b80-cfe3-11e9-86ec-3a8a04d173e3.jpg)

I tried to switch off and on Wi-Fi and even turn on flight mode without any success.

Btw before the upgrade I was running the anbox img.

**Comment by dobey** [comment]
> Btw before the upgrade I was running the anbox img.

Did you flash the anbox `boot.img` back after the upgrade? You must re-flash it after every update if you installed anbox.

**Comment by Flaburgan** [comment]
>Did you flash the anbox boot.img back after the upgrade? You must re-flash it after every update if you installed anbox.

To make anbox works, yes you need to. I didn't at the moment, so anbox probably is not working. But do you think it is what makes the NetworkManager going crazy? Because I didn't flash the anbox boot.img right after the upgrade last time and it didn't break the whole OS like that.

**Comment by dobey** [comment]
Yes, having anbox installed and not having the right kernel will cause weird issues like this. Flash the anbox boot and it will almost certainly go away.

**Comment by Flaburgan** [comment]
Okay, it looks like re-flashing the anbox boot.img solves it. I still consider that behaviour a big issue which should be fixed, anbox not working is fine, but knowing that the system allows such an infinite loop is worrying. And the anbox wiki page should warn about that, but I guess I can write message myself.

**Comment by NeoTheThird** [comment]
If you'd be willing to file a PR on github.com/ubports/docs.ubports.com for that note, that'd be great!

Sorry about the inconvenience. Keep in mind that anbox is still in development; when it'll be released properly, you won't have to jump through these hoops any more.

**Comment by dobey** [comment]
@Flaburgan It is not an infinite loop, not that there is any way to absolutely prevent any such events from occurring in a system. It is network-manager crashing and being restarted, over and over again, as a result of the system breaking due to the experimental feature of anbox which requires a different kernel.
