### ISSUE TITLE
OnePlus cannot run and constantly restart after install ubuntu touch,  it only can run after connect to computer by usb, i  not sure the problem was happed in hardware or software. Looking forward developer to replying.

### ISSUE THREAD

**Issue by huoxingwen** [ubports/ubuntu-touch#1224]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by lduboeuf** [comment]
Please rewrite this issue with a short title, use description for details

**Comment by lduboeuf** [comment]
close it for now, until more redeable format

**Comment by thebosbird** [comment]
Connect to an adapter to charge. Probebly the same llike connecting to the usb of your desktop. So I would say it is not the OS, but your battery. It is a known problem for the OPO with these signs. So change it for a new battery.
