### ISSUE TITLE
Countdown feature in clock app adds 1 day when start

### ISSUE THREAD

**Issue by xianrendou** [ubports/ubuntu-touch#1225]
- Device: LGE Nexus 5
- Channel: stable
- Build: OTA-10

### Steps to reproduce

1. Open clock app
2. Select countdown feature
3. Choose any time span through the dial
4. Tap "Start"

[Video](https://youtu.be/23-K-nvfAjI)

### Expected behavior

Countdown normally

### Actual behavior

After the first second of countdown, the remain time plus 1 day.

**Comment by thebosbird** [comment]
Not a probleem wit mij phone. But I kan reproduse tour problem. It is your timezone. 
My timezone is in Amsterdam. Then the timer works correct. After changing the timezone to New York I have your problem. The counter adds a day after the first second. 
When installing UT you need to set the timezone. Did you change it later again? Maybe that is the problem? If so, it is still a bug ;)

**Comment by giiba** [comment]
That explains the behaviour I have always seen:
If I set a timer less than 8hrs it adds one day after the first second ticks, if I add a timer for more than 8hrs the time remaining displays as expected untill 7:59:59 left when a day is added to the countdown.

I never change my timezone, which is GMT-8, so I expect if I set it to GMT-0 it would work fine...

**Comment by UniversalSuperBox** [comment]
Has this occurred for any of you recently? I am unable to reproduce a timer adding a day after passing the time prior to UTC that my current time zone is. Even after rebooting, the timer is still set for today.

**Comment by xianrendou** [comment]
I can now confirm this issue has been resolved in the timezone other than UTC. It seems recent update fixed this issue. Either setting countdown to more than 8 hours or less does not reproduce this problem again.
