### ISSUE TITLE
WebApp leaves location service switched on

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1226]
- Device: bacon
- Channel: edge
- Build: 2019-08-29

### Steps to reproduce

1. Install any webapp that can use location. In my case, its the local App "qando-ng" for public transport
2. Open the app, accept the location warning and wait a bit
3. Go to the app drawer, and start any new app and bring it to foreground

### Expected behavior
- After the new app has got focus, the location indicator gets inactive

### Actual behavior
- The location indicator stays actice

Note that this has sucked my battery nearly empty yesterday. Also fur uNav the behaviour is correct, so it must be smth with Webapps only.

**Comment by kugiigi** [comment]
In my experience, the issue seems to happen on initial location access prompt.
Location seems to hang and won't work correctly until reboot.
This is noticeable when for example installing PureMaps for the first time.

**Comment by balcy** [comment]
i can confirm this for krillin.
- only qando open (no other apps)
- location is active
- open terminal app
- location stays active
- switch to qando: location still active
- switch to terminal: location is inactive
- switch to qando: location is active
from there on switching between the apps works to switch the location active / inactive

When "qando" is open, and the lock-screen button is pressed twice, the location remains active, too.

I can see the problem with the "fahrplan" app (not a webapp), too.

**Comment by Flohack74** [comment]
I can confirm that its fixed on latest devel.

**Comment by jonnius** [comment]
Just tried to confirm, but failed, because both "Qando" as well as "Fahrplan" would freeze for approx. 20s when requesting location. Location indicator remains black (inactive). Should I open a new issue for this?

**Comment by cibersheep** [comment]
N5 RC, seams to work properly

**Comment by hendrikscheewel** [comment]
Nexus 4 in RC: Also seams to work.

**Comment by Flohack74** [comment]
There can be a problem with the trust prompts so that you cannot see the popup for the initial location request. @jonnius did you open those 2 apps for the first time on this installation?

**Comment by jonnius** [comment]
One day and at least one reboot later, it does work now. I confirm this issue is fixed, RC, FP2.

About the freezing issue: yes, both apps were started for the first time. In Fahrplan the location would not appear. In Qando, the Prompt appeared and the app froze during the fade-out animation of the prompt after answered.

**Comment by Bolly** [comment]
BQM10FHD in RC, test with Qando. Also seams to work.
