### ISSUE TITLE
Edge: unable to shutdown device

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1228]
### Illustrations

- Device: Hammerhead
- Channel: edge
- Build: last

### Steps to reproduce

Try to shutdown device either by hardware button or via the indicator menu, touch on "shutdown" button.

### Expected behavior

Device shut down

### Actual behavior

Device not responding

**Comment by mauricioduarte01** [comment]
i can confirm this behavior since a few days ago. This is the main reason why i switched back to devel

**Comment by lduboeuf** [comment]
> i can confirm this behavior since a few days ago. This is the main reason why i switched back to devel

There is workaround by booting into the bootloader( long press volume down + power )  and then choose "Power Off"

**Comment by UniversalSuperBox** [comment]
This appears to be a regression caused by https://github.com/ubports/unity8/pull/159
