### ISSUE TITLE
Downloading Ubuntu Touch Taking Way Too Long 

### ISSUE THREAD

**Issue by gab-albert** [ubports/ubuntu-touch#1230]
I'm trying too install Ubuntu Touch 
It's been 8 hours still downloading
Is there any other way? I tried to update now I'm without a phone.

### Illustrations

- Device:
- Channel:
- Build:

**Comment by parksjr** [comment]
I would post this up in the support forum here: https://forums.ubports.com/category/37/support. Before you do, fill your query with more details such as the details you left blank (device, channel, build, logfiles). also include what type of network you are on, network speed, wifi or not, what install method you uses, and anything else you can think of.
