### ISSUE TITLE
No WIFI networks found

### ISSUE THREAD

**Issue by anna-knez** [ubports/ubuntu-touch#1231]
- Device: OnePlus One 64GB A0001
- Channel: (don't know)
- Build: Bacon (16.04 Stable)

### Steps to reproduce
I just used UBPorts installer to do a new Bacon Ubuntu Touch installation on the device, 

### Expected behavior
Hoping to see wifi networks. 

I toggled the battery and the airplane mode, (without much luck), and then did a re-flash... Still nothing (no wifi networks) cellular data work fine.

### Actual behavior
After all that  there are still no wifi networks (old phone sees 20+ networks). 

Total newbie to Ubuntu touch here, so many thanks for your hard work, and apologies in advanced.

Thanks!

**Comment by Flohack74** [comment]
Certain Oneplus One models are not compatible with the way we try to configure the network. Please follow this thread after my post here: https://github.com/ubports/ubuntu-touch/issues/995#issuecomment-453663246 - basically you need to regenerate one config file, then it should be fine.

**Comment by anna-knez** [comment]
Hi Flohack74, thanks for the tip, will try it in a few hours and let you know!

**Comment by anna-knez** [comment]
That fixed it. Many thanks again!
