### ISSUE TITLE
Anbox BUG on Meizu Pro 5 16.04

### ISSUE THREAD

**Issue by Adam-W-1** [ubports/ubuntu-touch#1234]
### Illustrations

- Device: Meizu Pro 5
- Channel:help wanted
- Build:

### Expected behavior

Need instal anbox.

### Actual behavior

After flashing anbox-boot-turbo.img phone don't see sim card:
http://cdimage.ubports.com/anbox-images/anbox-boot-turbo.img
After flashing anbox-boot-turbo-test.img Wifi hotspot not work;
http://cdimage.ubports.com/anbox-images/anbox-boot-turbo-test.img

### Logfiles and additional information

Folowed instruction:
http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html
I have installed fastboot and adb drivers, system in phone is updated to 16.04.
Phone was bought with android, and was flashed to ubuntu touch 15.04 and updated to 16.04 using TWRP, after crash with sim and hotspot i had to flash agin 16.04.

**Comment by Adam-W-1** [comment]
Afer flashing http://cdimage.ubports.com/anbox-images/anbox-boot-turbo-test.img Wifi hotspod not work, anbox work fine. Unfortunately i had to restore backup because i need hotspot.

**Comment by Ingo-FP-Angel** [comment]
I get a "forbidden" message for https://www73.zippyshare.com/i/Ac0wnYsz/14426/ubuntu_touch_anbox_problem.png

**Comment by Flohack74** [comment]
I am closing this since Anbox is deprecated and will not longer receive any efforts. Please switch to Waydroid if you have an Android-9 device or higher. Lower versions we will not support unfortunately.
