### ISSUE TITLE
Keyboard is detached from app when opening app stack

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1236]
- Device: E5
- Channel: edge
- Build: 2019-09-25

### Steps to reproduce
- Open an app that uses keyboard (OSK) input i.e. Teleports or Terminal.
- Type some text to raise the keyboard.
- long swipe to open the app stack

### Expected behavior
The app(s) including the keyboard get stacked.

### Actual behavior
The app(s) get stacked, BUT the keyboard does stay in the foreground detached from the app.
Reproducible: always

### Logfiles and additional information
![screenshot20190925_201647608](https://user-images.githubusercontent.com/37637312/65634838-6e230280-dfdf-11e9-9c87-71ce688aef91.png)

**Comment by lduboeuf** [comment]
confirmed also on N5

**Comment by zubozrout** [comment]
I don't think this is a new issue. I've seen it on edge (arale) many times already. I don't recall when was it I've seen it first, but it was certainly a long time ago. This time however it is nicely reproducible.

**Comment by mauricioduarte01** [comment]
Confirmed! Maybe it was already there but I just was not paying attention to it.

**Comment by dark-eye** [comment]
shouldn't it will be better  to simply hide the keyboard? attaching the keyboard to the app sounds complicated and expensive

**Comment by Danfro** [comment]
Good point. Thinking about it, the OSK does likely not 'belong' to a certain app but only gets called.

But will closing the OSK have to be implemented within each app? Or is that something in the OSK? Or does this needs amending in unity8?

On Thu, 26 Sep 2019 00:54:44 -0700, Eran wrote:
> shouldn't it will be better  to simply hide the keyboard? 
> attaching the keyboard to the app sounds complicated and 
> expensive
>

--
