### ISSUE TITLE
can not install anbox ,"Anbox kernel is not installed!"

### ISSUE THREAD

**Issue by yuguangche** [ubports/ubuntu-touch#1237]
### Illustrations

- Device: meizu pro5  (turbo)
- Channel: 16.04 stable
- Build: 20190815

### Steps to reproduce

1

### Expected behavior

1.  install anbox follow 
http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html
2.  after flashed img file and rebooted,, I  exec bollow command:
adb shell
sudo mount -o rw,remount /
sudo apt update
sudo apt install anbox-ubuntu-touch
anbox-tool install
exit
everything looks well，unless a warring：No sandbox user '_apt' on the system, can not drop privileges, before exec anbox-tool install.
When I exec anbox-tool install. It retrens "Anbox kernel is not installed! Please flash this first!"

### Actual behavior

I should install anbox successfully

### Logfiles and additional information

1. for the warring I got，I executed sudo grep _apt /etc/passwd /etc/shadow
2. checked  ls -1 /dev/{ashmem,binder}, printed
/dev/ashmem
/dev/binder
3. manually copied anbox-boot-turbo.img to dev/block/platform/15570000.ufs/by-name/bootimg by execute dd if=/sdcard/anbox-boot-turbo.img of=dev/block/platform/15570000.ufs/by-name/bootimg WITH TWRP terminal
4.  why I do 3？ because I installed Ubuntu touch with ubporsts filed: UBports runs well, and my devics do not reboot in to system.And I try manually exec fastboot and adb command to install, fialed also. So I install Ubuntu touch follow this : https://blog.csdn.net/skykingf/article/details/52164955, succed but cant install anbox.
5.

**Comment by Adam-W-1** [comment]
After flashing SIM card is visible on your phone? On my Meizu pro 5 isn't and i had to restore recovery.

**Comment by yuguangche** [comment]
> After flashing SIM card is visible on your phone? On my Meizu pro 5 isn't and i had to restore recovery.

Yes, I have same problem. Anbox finally worked with test-boot.img，you provided on your issue。

**Comment by Adam-W-1** [comment]
I tested test-boot.img. This version have other bug; after flashing wirelles hotspot isn't visible to devices after enabling. I need hotspot and had to restore backup system.
