### ISSUE TITLE
Killed apps cannot be refocused or bring to the foreground

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1242]
- Device: Nexus 5
- Channel: Edge
- Build: 2019-10-03/3

### Steps to reproduce
1. Open lots of apps until an app gets killed. You can validate from the launcher if an unpinned app has no dots in both left and right side of the icon.
2. Tap on that app with no dots.

### Expected behavior
App gets focused and reopened.

### Actual behavior
Nothing happens and the app doesn't reopen.

**Comment by UniversalSuperBox** [comment]
It appears that the Launcher's app model does not know about the placeholders to be able to focus them. The placeholders still appear in the Spread and can be focused, relaunching the app. Still, this is not good for users with lower spec devices.

**Comment by cibersheep** [comment]
N5 RC, I manage to open 15 apps :)
Device is slow but works as expected

**Comment by luksus42** [comment]
E4.5 on RC:
Not sure how to test, but I opened 20 apps and everything seemed still to work. No app got killed.

- Installed Documentviewer and opened app-spread while installing -> ui froze for some seconds, but then everything was going on.
- Watched the launncher -> 7 apps got killed/closed (no dot next to the icon, but the icon was still there, even if it is not a pinned app)
- Watched the app-spread -> still all 20 apps were there.
- Selected a killed app in the spread -> app was relopened/reloaded.

Seems to work for me.

**Comment by peat-psuwit** [comment]
Note to QA: this bug is about selecting a killed app from the launcher panel, not from the spread. However, just to make sure everything works, try selecting one from both the launcher, the app drawer, and the spread.

**Comment by luksus42** [comment]
Updated my comment. Selecting from launcher panl does work too.

**Comment by Fuseteam** [comment]
Confirmed, refocussing works from spread, drawer and launcher
