### ISSUE TITLE
Sometimes unable to exit an app

### ISSUE THREAD

**Issue by hallyn** [ubports/ubuntu-touch#1246]
- Device: Nexus 4
- Channel: stable
- Build: 374

### Steps to reproduce

I haven't figured out yet what causes this.
### Expected behavior

At any time, I can swipe from right side to switch to previous application or show the list of cards, or swipe from the left side to open the dash.
### Actual behavior

Once in awhile, swiping from left or right edge does nothing.  Swiping from top still works so I can enter the system preferences app by picking one of options in the notification menu (like keyboard settings), and I can reboot, which "fixes" the issue.

### Logfiles and additional information

Next time it happens I will gather the unity8.log and unity8-dash.log

**Comment by Thieb67k** [comment]
Hello,
That is exactly what happens to me sometimes. That issue occurs during (or after) use of the dialer-app (from my side at least).
I noticed that in issues "/ubuntu-touch #1142 " and " /dialer-app#87".
Best

**Comment by hallyn** [comment]
I've only seen this on the dialer lately so maybe this more general issue should be closed.

**Comment by Flohack74** [comment]
Ok sure ;)

**Comment by hallyn** [comment]
Well, funny, it just happened to me today in the browser!
