### ISSUE TITLE
how do install samsung tab 3 lite

### ISSUE THREAD

**Issue by kpphyoe** [ubports/ubuntu-touch#1259]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by PhoenixLandPirate** [comment]
you can't

**Comment by UniversalSuperBox** [comment]
Hello @kpphyoe,

You can find the devices supported by Ubuntu Touch at https://devices.ubuntu-touch.io. Your device is not on this list, so the only option forward is to port Halium to the device and run Ubuntu Touch on top of that. This is not a simple process, but you can find instructions for doing so beginning at https://docs.ubports.com/en/latest/porting/introduction.html
