### ISSUE TITLE
Upgrade to latest QT LTS (QT 5.12)

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#1260]
Bug fixes, new features, and new apps, what's not to love, except that it'll probably be a lot of hard work migrating, and upgrading to get up to date.

**Comment by balcy** [comment]
https://github.com/orgs/ubports/projects/22

**Comment by mateosalta** [comment]
I think this is done right?

**Comment by lduboeuf** [comment]
true :)
