### ISSUE TITLE
Wifi not connectiong after reboot 

### ISSUE THREAD

**Issue by emailforfor** [ubports/ubuntu-touch#1262]
After months of searching, I finally found a solution for the problem - that even I understood.
With some commands in the terminal, the error can be corrected. Please refer to:
           https://forum.xda-developers.com/showthread.php?t=2730486
Thanks to Nilendu from India
--------
I testet this with BQ M10 HD. Should be o.k. for other phones / tablets also

**Comment by Flohack74** [comment]
@emailforfor can you please reformat your posting to use normal fonts? Thanks. And then, it would have been better to comment on the open issue for this, and not create a new one.

**Comment by ant0nwax** [comment]
I realized this happens on Note 4 Samsung Snapdragon and Exynos, too
the MAC address changes after each reboot and then somehow the password needs to be reentered, we also found a workaround for this, i will edit post later

**Comment by userj** [comment]
Wait, what's the solution? This is happening on Xperia XZ (Kagura). Thanks.

**Comment by mateosalta** [comment]
> Wait, what's the solution? This is happening on Xperia XZ (Kagura). Thanks.

Remove mac-address entry from /etc/NetworkManager/<your network> and run `sudo service network-manager restart`

will have to do this for each network as a workaround

**Comment by UniversalSuperBox** [comment]
Since this is not an issue but rather an offer of a solution, I think it can be closed.
