### ISSUE TITLE
WIFI Issue - 16.04(OTA-10), on Nexus-5

### ISSUE THREAD

**Issue by ravikv123** [ubports/ubuntu-touch#1266]
### Description of the feature
After Update 16.04(OTA-10), on Nexus-5, unable to connect to wifi.
No Existing wifi routers seen, unable to connect to new network,  no wifi switch to turn on/off

### Illustrations

- Device: Nexus 5
- Channel: 16.04/stable
- Build: 5.1.1 LMY48W 1024 test-keys

### Steps to reproduce

Auto updated via OTA and after reboot no wifi signal

### Actual behavior

No Wifi signal , no switch to toggle  and no avbl routers are shown

### Logfiles and additional information

--
Screnshots:

![IMG_20191023_235406](https://user-images.githubusercontent.com/43967054/67423787-855f0b00-f5f2-11e9-92ae-b0d149d9a71b.jpg)
![IMG_20191023_235411](https://user-images.githubusercontent.com/43967054/67423788-85f7a180-f5f2-11e9-8048-48e5cb6d852a.jpg)
![IMG_20191023_235356](https://user-images.githubusercontent.com/43967054/67423790-85f7a180-f5f2-11e9-98e8-7130dc5e1ecd.jpg)

**Comment by ravikv123** [comment]
Screenshots of the issue
![IMG_20191023_235406](https://user-images.githubusercontent.com/43967054/67422921-fb627280-f5f0-11e9-9b13-6c728c7ea45d.jpg)
![IMG_20191023_235411](https://user-images.githubusercontent.com/43967054/67422922-fb627280-f5f0-11e9-9822-04086d7f5ee1.jpg)
![IMG_20191023_235356](https://user-images.githubusercontent.com/43967054/67422923-fb627280-f5f0-11e9-8aba-9f63166077be.jpg)

**Comment by Flaburgan** [comment]
Did you installed Anbox, following [that page](https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html)? If yes then you need to reflash the bootloader each time you do an ubuntu upgrade. I'll edit the wiki page to mention that.

Also, you say OTA-10, but isn't it OTA-11? It is the one just released.

**Comment by Flaburgan** [comment]
I just saw this issue: https://github.com/ubports/ubuntu-touch/issues/1264 so if you installed Anbox that's probably the same.

**Comment by BadAngelZ** [comment]
ravikv123 says it runs the "stable" branch: I thought that anbox could only be installed on the devel branch ... but I may be mistaken ...
I own some other nexus 5 for "spare parts"... some of them do not have wifi because the chip has a known manufacturing issue (I don't know where I've read that)... Hope, for you, that's a software problem only !

**Comment by ravikv123** [comment]
@Flaburgan , I was running stable version and the update was OTA-10  on 10/23(screenshot attached).
 @BadAngelZ, the wifi stopped working aft the OTA Update.. :( till that time it was fine...
 any quick check;s that I can do? 
![IMG_20191024_161034](https://user-images.githubusercontent.com/43967054/67478112-0eb92080-f679-11e9-8c08-1a4e33dfbad1.jpg)

**Comment by BadAngelZ** [comment]
I am not an expert, but I would suggest to try to run 
`nmcli -p d`
and see if your wifi card is detected.

**Comment by ravikv123** [comment]
only 3 in the o/p (nmcli -p d)...  ril_0, sit0, lo.. no wlan :(

**Comment by lduboeuf** [comment]
still the same with OTA 11 ?

**Comment by Flaburgan** [comment]
@badangelz you can totally install Anbox on the stable branch. I'm doing it :)

Can you please try to install OTA-11 as that's now the last UT stable version?

**Comment by ravikv123** [comment]
how to update to OTA 11? Cant connect to WIFI... any other option other than flashing  using UBPorts?
Actually, Im using that as a full linux env.. :( have much data and scripts.. so dont want to flash OS...

**Comment by lduboeuf** [comment]
With the ubports installer

**Comment by ravikv123** [comment]
ok.. Installed using UBPorts with data wipe off... WIFI is back and have all the reqd data........
Closing the tkt..
thankyou all for the support....
