### ISSUE TITLE
FEATURE REQUEST: sent and received Teleports-Messages in the Lockscreen

### ISSUE THREAD

**Issue by bassemolufda** [ubports/ubuntu-touch#1269]
I wish a Feature to shown the send and received Messages in the Lockscreen, how Telegram.

**Comment by airmjr** [comment]
I miss it also! Great feature!

**Comment by airmjr** [comment]
I would also appreciate the possibility to access the music player from lockscreen, without unlocking the device. For example some small buttons on the bottom of the lockscreen..

**Comment by PhoenixLandPirate** [comment]
Duplication of #143

**Comment by dobey** [comment]
> Duplication of #143

No I don't think so. I think this is a request to have TELEports implement the infographics feature. Obviously messages you sent would not appear in notifications on your own device.

@bassemolufda Please open tickets for TELEports at https://gitlab.com/ubports/apps/teleports/issues instead. Thanks.
