### ISSUE TITLE
GPS not finding current location

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubuntu-touch#1272]
### System Info:
Device: Oneplus One (bacon)
OS: Ubuntu 16.04 (OTA 11)
Channel: Not sure how to get this information from the phone.

### Steps to reproduce
- Turn location detection on
- Let device use GPS to detect location (in Location settings).
- Try to use an app to find current location using GPS.

### Expected behavior
- Applications find current location in reasonable amount of time.

### Actual behavior
WITH CLOCK APP:
- Launch clock app
- Clock posts "Retrieving location" for very long time (+ 20min)

WITH UNAV:
- Launch uNav
- Click icon to find your position.
- Position not found after long time (~9hours)

In either test case, the current location is never found.

### Logfiles and additional information
- Not sure where to find these but am happy to post them if someone can point me to them.
- I have tried restarting the device a few times to see if that helps, but it doesn't seem to. 
- Also every attempt did not have the wifi turned on.

**Comment by dobey** [comment]
If you're indoors, GPS is unlikely to work well (or at all). You need clear line of site to satellites, a SIM card with some cell towers in range, and a good data connection, to get the quickest fix on location.

**Comment by aclifton314** [comment]
@dobey ah I see. I currently don't have a SIM card in. I'm just relying on wifi. Just to confirm, a SIM card is a must for GPS to work?

**Comment by Flohack74** [comment]
No, SIM card is not mandatory but can help in the process. With only GPS, you need to be outside a building, and you need patience. The GPS is not running in the background, so first invocation of GPS can take 5-10mins

**Comment by dobey** [comment]
Right. SIM isn't required, but it speeds up the process if it can relate cell towers. With satellite only, you need clear line of site to at least 3 satellites (more for higher accuracy).
