### ISSUE TITLE
Question: possible to set 24h time?

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubuntu-touch#1273]
### System Info:
Device: Oneplus One (bacon)
OS: Ubuntu 16.04 (OTA 11)
Channel: Not sure how to get this information from the phone.

I just wanted to know if it was possible to set the clock on my device to be in 24 hour format? I wasn't able to find a way to do this in the newest release.

**Comment by BlueKenny** [comment]
Hello, 
I think this is linked to your timezone  ?

**Comment by aclifton314** [comment]
Thanks for the response. 

If I got to System Settings -> Time and Date, I only see options to set the time zone, or to automatically/manually set the time and date. If I click Time Zone, I get taken to a page that allows me to set the time zone but I don't see any options for setting the time format.

**Comment by thebosbird** [comment]
It is your language. Go to settings, language/text. Here set your Display language: 
English US is in 12h notation
English UK is in 24h notation
After setting, reboot and you should be ok

Found the answer on the forum: https://forums.ubports.com/topic/374/bq-e4-5-just-flashed-time-format-24h

**Comment by aclifton314** [comment]
@thebosbird that's the trick! Thanks!
