### ISSUE TITLE
Possible background issue

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubuntu-touch#1274]
### System Info:
Device: Oneplus One (bacon)
OS: Ubuntu 16.04 (OTA 11)
Channel: Not sure how to get this information from the phone.

This is more of a question, as I am new to ubuntu touch. I notice that there are background options in the System Settings, but the "home screen" just shows a white background with the apps that are currently installed (first pic). I only see the background changes when I long swipe left and get the screen showing the apps that are currently open (second pic). I just wanted to know if this is expected/intended?
![20191026_100815](https://user-images.githubusercontent.com/53267795/67622638-535bcd80-f7d9-11e9-9aa8-501350fa5f0f.jpg)
![20191026_100825](https://user-images.githubusercontent.com/53267795/67622640-56ef5480-f7d9-11e9-83c6-39c122b63042.jpg)

**Comment by PhoenixLandPirate** [comment]
Its expected behavior, if you want to see your background in scopes, then you have to turn that on, and mess about with the transparency slider.

**Comment by aclifton314** [comment]
I guess it would help to scroll all the way down, hahaha! My bad everyone. Closing this now.
