### ISSUE TITLE
Random unity8 crash while booting

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1277]
- Device: turbo
- Channel: devel
- Build:

### Steps to reproduce
random

### Expected behavior
not rebooting

### Actual behavior
random reboots

**Comment by Danfro** [comment]
Are you referring to the fact that when rebooting, it keeps rebooting for a few times AND does now allow input for SIM pin?

**Comment by rubencarneiro** [comment]
Yes and some random reboots wile turned on without even been using anything.

**Comment by Danfro** [comment]
Then I can confirm this on my E5 happening in edge (while I was living on the edge) and now in dev. I have several confirmations on different devices from our German group.

This definitely affects multiple devices (all devices?) in edge and now dev channel.
If you are lucky it works on the first attempt (only very few occasions) but generally needs 2 up to 8 times rebooting until you can actually type in the SIM pin(s). 

This behaviour - or its intensity regarding the number of reboots - seems to change from update to update somehow. After on update I even thought it was fixed. ;-)

Could you please change the title to cover this? -> Random reboots on Edge and Devel channel on multiple devices

**Comment by lutin11** [comment]
IT happens also to me on a Nexus 5.
I think those issue is related to Unity8 as restarted it throw UT Tweak tool does same problem. Some time I ve got the sim unlock screen that start to be displayed and then a black screen until I manually restart the phone .

**Comment by Danfro** [comment]
I almost ever do see the SIM pin dialog for a splitsecond. Then in most cases it proceeds to login screen. I can then login - but no sim cards available. Unlockong them from indicator does not work. Then I have to reboot manually.

On Wed, 13 Nov 2019 22:16:24 -0800, saveurlinux wrote:
> IT happens also to me on a Nexus 5.
> I think those issue is related to Unity8 as restarted it throw 
> UT Tweak tool does same problem. Some time I ve got the sim 
> unlock screen that start to be displayed and then a black screen 
> until I manually restart the phone .
>

--

**Comment by Flohack74** [comment]
Well guys, if its the same I see, then its not a reboot as like you would see the device logo. Its a unity8 crash, and after some seconds you will get the spinner again (5 dot animation).
It is important to keep those things separated. Normally a unity8 crash does not reboot the device.
So please sort out the facts here: Is the device rebooting or is unity8 crashing? To me its the latter only.
And yes, we know this bug already, and it will be a blocker for the next OTA-12.

**Comment by mariogrip** [comment]
Should be fixed by: https://github.com/ubports/mir-android-platform/pull/17

**Comment by jonnius** [comment]
If not seen these reboot much any more on dev lately, nor on RC, FP2, now.
