### ISSUE TITLE
Messaging app: After sending a SMS, the thread is scrolled to top

### ISSUE THREAD

**Issue by howmanycharacters** [ubports/ubuntu-touch#1282]
### Illustrations

- Device:  Nexus 5
- Channel:  Stable
- Build:  OTA 11

### Steps to reproduce
Send a message to anyone and observe screen going up to top of the thread by itself.

### Expected behavior
Screen remained where it is. On the bottom with latest messages.

### Actual behavior
Screen goes up by itself after sending a message.

**Comment by lduboeuf** [comment]
confirmed also here

**Comment by james-lyon** [comment]
This is almost the same as https://github.com/ubports/messaging-app/issues/66

**Comment by UniversalSuperBox** [comment]
Yes, while the steps to reproduce the bug are slightly different, I think it may be the same cause. Closing as a duplicate of https://github.com/ubports/messaging-app/issues/66
