### ISSUE TITLE
Background setting does not persist after reboot

### ISSUE THREAD

**Issue by tallero** [ubports/ubuntu-touch#1283]
- Device: Hammerhead
- Channel: stable
- Build:  OTA-10 and OTA-11

### Steps to reproduce
Set background, reboot the device

### Expected behavior
Background should remain the one I set.

### Actual behavior
Default background is set in the background; apps scope gets black (or white, depending on whether you enabled scope bg.

### Logfiles and additional information
Where are unity log files?

**Comment by mateosalta** [comment]
Is this still the case, I think this may have been fixed in recent versions?

**Comment by tallero** [comment]
If you can confirm I will close.

**Comment by Fuseteam** [comment]
doesn't seem to be an issue on OTA 15 nor on the latest devel
