### ISSUE TITLE
WiFi networks not recognized by OPO with 16.04 OTA-11

### ISSUE THREAD

**Issue by sportFitDotCom** [ubports/ubuntu-touch#1286]
WiFi Issues

- Device: One Plus One
- Channel:
- Build: 16.04 OTA-11

### Steps to reproduce
Attempting to connect to WiFi

### Expected behavior
Expect that the various networks in the immediate area will show up, and one may be selected...

### Actual behavior
The categories "Previous Networks" and "Connect to Hidden Networks" appears at top of screen. No networks actually show up, as they do on computers, iPads, other phones.

### Logfiles and additional information
Seems like some others have had similar issues but, and evidently over some time, no solution has been found. Have reinstalled ubuntu Touch two or three times, wiping and not wiping; have rebooted numerous times; have toggled WiFi buttons numerous times. Have searched for over a week for something that might prove useful in solving this issue (aside from returning to Android). BTW, WiFi networks did show on Android / Cyanogen Mod prior to Ubuntu Touch installation.

**Comment by Flohack74** [comment]
Please follow the thread at https://github.com/ubports/ubuntu-touch/issues/995, and specifically https://github.com/ubports/ubuntu-touch/issues/995#issuecomment-456349657 - please tell me if you can solve it with that.

**Comment by sportFitDotCom** [comment]
Hi Florian,

Thanks for your reply and direction.

The instructions seem clear enough: generate random MAC address; replace first 3 bytes with OPO-specific code; insert into script; insert script into ini folder (file).

Thing is, I’m not yet sophisticated enough to navigate into the device’s files and make adjustments.

Over the coming weeks I plan to view videos / read articles on Linux and hopefully learn enough to take said recommendations and apply them.

Again, thanks. I’ll let you know how it works out after I can get into it.

One interesting thing is that the several iterations of the OPO seems to be a factor in how each responds to UT. Mine is bacon but it’s also A0001, as far as how it was described on eBay when I bought it. (A0001 on eBay; bacon within phone itself.)

Best,

Christopher

*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by ferlanero** [comment]
After patching WCNSS_qcom_cfg.ini file with

`Intf0MacAddress=C0:EE:FB:xx:xx:xx`

and doing 

`adb push WCNSS_qcom_cfg.ini /persist/WCNSS_qcom_cfg.ini`

Sadly, there is no WiFi on the 16.04 (OTA-11) OPO UBport

**Comment by sportFitDotCom** [comment]
"Sadly, there is no WiFi on the 16.04 (OTA-11) OPO UBport”

Hard to believe, but I suppose that could be the case.

I bought the OPO to explore Linux as a learning experience (and for the promise of greater privacy/security), and I guess I’m learning.

Will probably explore the one or two other distros that supposedly work with the OPO.

Thanks much for your help.

*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by sportFitDotCom** [comment]
I do have to ask, though, how it is that WiFI appears to be, in some cases, seemingly disregarded insofar as updates are concerned? I installed 16.04.06 last night and there was no reference to solving OPO WiFi issues. 


*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by Flohack74** [comment]
@ferlanero did you replace the xx with valid numbers?

**Comment by Flohack74** [comment]
@sportFitDotCom The answer is easy: There are at least 2 different models of the OPO on the market, some of them have their MAC address stored differently. We actually fixed a problem for group A of devices and created a new problem for group B. Now, it seems that none of the developers has a device from group B, so we cannot confirm or even solve the bug.
Someone needs to send us a non-working device, then we can take a look. But until then it will remain unsolved, since it works for all people in the dev team...

**Comment by sportFitDotCom** [comment]
I figured as much. Hard to solve a problem when phone isn't presenting it. I do seem to have a non-working device.

**Comment by undrwater** [comment]
The thread #995 worked for me. To provide some assistance, one needs to enable developer mode in settings. Then connect with a device with adb tools installed. 

Then:
`adb shell`

Once you're in the shell:
`sudo mount -o remount,rw /`
That is to mount the root partition read/write. Now you can replace or edit the WCNSS_qcom_cfg.ini file. The one mentioned in #995 was sufficient to get wifi working for me.

Hope this helps

**Comment by sportFitDotCom** [comment]
Thank you. Will explore.


*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by sportFitDotCom** [comment]
Have installed ADB Tools via Homebrew and will sort out next steps hopefully sooner rather than later. Again, thanks.

C.


*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by Flohack74** [comment]
Any feedback on this?

**Comment by sportFitDotCom** [comment]
Nope. Nothing.

Kind of giving up on trying to get Ubuntu to work on OnePLus One. For whatever reason my phone’s wireless does not work with Ubuntu Touch. (Just updated to latest version.)

C.


*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by Flohack74** [comment]
@sportFitDotCom you need to do manual steps. This is not fixable by an update.

**Comment by sportFitDotCom** [comment]
Thanks for reply. Yes, no doubt, some tweaking is required. Last year I was exploring videos on learning Linux, but had to shift focus to another project. Still working on the other project, now. Do not know enough to begin noodling with various commands. Some things might seem easy, perhaps cut and paste, but without deep enough understanding of what I’m doing in modifying a Linux OS it’s possible I’d miss something that to someone else (who’s skilled) would be obvious and create bigger problems. (That said, I don’t use the phone, per se. It’s not a daily driver.)

C.


*****
Christopher Drozd
www.sportfit.com
310 795 0639

**Comment by UniversalSuperBox** [comment]
Since we're unable to continue troubleshooting on this issue, I'll close it
