### ISSUE TITLE
cannot add custom background, fresh install hammerhead/nexus 5

### ISSUE THREAD

**Issue by iambumblehead** [ubports/ubuntu-touch#129]
cannot add custom background, fresh install hammerhead/nexus 5

System Settings -> Background 
 * this screen shows a gallery of given backgrounds
 * at the bottom is a label, 'custom ^'
 * clicking 'custom ^' changes the label to show 'custom v'

there are no other buttons near the 'custom' label and there is no way to add a custom background

**Comment by iambumblehead** [comment]
the phone went into 'sleep' and after entering the pin in the unlock screen, the Background panel had buttons below the custom label for setting the background.

so... I was eventually able to set the background image though the buttons were not there initally

**Comment by Flohack74** [comment]
This is indeed very strange!

**Comment by Flohack74** [comment]
Ist this still an issue?

**Comment by iambumblehead** [comment]
I'm not planning to reinstall ubports over the current installation --I recommend the closing this issue. The issue does resolve itself somehow after a short time.

**Comment by Flohack74** [comment]
Ok thx!
