### ISSUE TITLE
"silent mode" has no effect at all

### ISSUE THREAD

**Issue by ghcatt** [ubports/ubuntu-touch#1295]
<------------------------------------------------------------------------------
-------- BUG-REPORT ------------------------------------------------------------
--------------------------------------------------------------------------------
-------- Something doesn't work the way you want it? That's a bug. -------------
--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

- Device: nexus 4
- Channel: stable
- Build: ubuntu 16.04 lts-armhf (20191016)

### Steps to reproduce
tested with music clickapp - listening to music is still possible (speaker output). can't test headphones for now.

### Expected behavior
no sound ouput

### Actual behavior
sound output

### Logfiles and additional information

if the volume is set to 0 then no sound is being played

**Comment by Daniel20000522** [comment]
By using the [uVolMan](https://open-store.io/app/uvolman.mateosalta)  application you will learn why this happens.

**Comment by UniversalSuperBox** [comment]
Hi @ghcatt,

Silent mode silences notifications, not media, like on other mobile operating systems. The volume controls for media, notifications, and alarms are separate. Currently the only way to adjust media volume is to have media playing or using an app like [uVolMan](https://open-store.io/app/uvolman.mateosalta).

**Comment by ghcatt** [comment]
oh, well nevermind. thanks for suggesting uvolman application.
