### ISSUE TITLE
systemd-logind - cpu consumption

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1300]
### Description of the feature

- Device: OP3
- Channel: edge
- Build: 19/11/23

### Steps to reproduce
look resources with top
Processes in the background are consuming significant amount of resources 

### Actual behavior
![image](https://user-images.githubusercontent.com/11337464/69490427-5afca980-0e4d-11ea-8b0d-e6b873af88a7.png)

**Comment by Vince1171** [comment]
With a week old install and a fresh install, I don't have this issue...
@ernesst does this issue occure everytime or just when you're connected via ssh?

**Comment by ernesst** [comment]
I would say when i connect to ssh.

**Comment by Vince1171** [comment]
@ernesst do you still face this issue?

**Comment by ernesst** [comment]
Not really, I do face time to time a phone freezing for a 1s but I'm not sure it's link to that.
Bug can be close, i'll reopen it worst case.
