### ISSUE TITLE
Impossible to create a libertine container

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1305]
- Device: OP3
- Channel: Edge
- Build: 19-11-25

### Steps to reproduce
Try to create a Libertine container

### Expected behavior
Able to create a container from the gui or the terminal, as per http://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html

### Actual behavior
the gui comes back to the main container creation screen after validating name of the container.

### Logfiles and additional information
`phablet@ubuntu-phablet:~$ libertine-container-manager list

phablet@ubuntu-phablet:~$ libertine-container-manager create -i xenial

Enter password for your user in the Libertine container or leave blank for no password:

Password: 

libertine-container-manager:123: ERROR: create():	Failed to create container: 'No module named 'libertine.LxcContainer''
`

**Comment by ernesst** [comment]
This command seems to produce a container : 
libertine-container-manager create --id test --type chroot --name 'Libertine Demo'

Command from this bug test : https://bugs.launchpad.net/ubuntu/+source/libertine/+bug/1556303

**Comment by lakotaubp** [comment]
I can confirm this. Try to setup from system settings, tap create brief change of page then back to create page.

**Comment by Vince1171** [comment]
seems to appear on all Halium based ports

**Comment by faissaloo** [comment]
I'm getting this on the Pinephone

**Comment by xonq** [comment]
If you create a `chroot` type container it in the command line, it ultimately fails at some permission error, however, I was then able to view the libertine container in both the cl and settings. I was able to install an app via the settings GUI, and then use it by starting a bash shell in the container `libertine-container-manager exec -i $CONTAINER -c /bin/bash`

**Comment by vuldin** [comment]
When running the following command:
`libertine-container-manager create --type chroot -i vuldin-container`

I get lots of output with errors ending in the following:
```
...
Errors were encountered while processing:
 ca-certificates
 dictionaries-common
E: Sub-process /usr/bin/dpkg returned an error code (1)
ChrootContainer.py:126: ERROR: create_libertine_container(): Failure installing 'apt-transport-https' during container creation
libertine-container-manager:123: ERROR: create():    Failed to create container: 'destroy_libertine_container() missing 1 required positional argument: 'force''
```

Then trying this command says the container doesn't exist:
`libertine-container-manager exec -i $CONTAINER -c /bin/bash`

**Comment by hacker1024** [comment]
I'm getting this too, using a custom kernel (4.14) + the GSI on my Redmi K20 Pro.

**Comment by hacker1024** [comment]
`sudo apt install python3-libertine*` gets me a little further.

`libertine-container-manager:123: ERROR: create():       Failed to create container: ''`

[If I remove the try-catch, here's the stacktrace.](https://del.dog/ottimonurr.txt)

**Comment by milikhin** [comment]
> This command seems to produce a container :
> libertine-container-manager create --id test --type chroot --name 'Libertine Demo'
> but fails on initializing makedev
> https://paste.ubuntu.com/p/tjdmNMwkTt/
> 
> Command from this bug test : https://bugs.launchpad.net/ubuntu/+source/libertine/+bug/1556303

I'm also getting a similar error about makedev on Pocophone F1 running UBports GSI.
If I understand correctly the issue happens when `makedev` tries to create various files at `/dev/*` on its postinstall.
But we already have `/dev/` mounted from the host since we are using `fakechroot`, so `makedev` gets `permission denied` when tries to execute `rm /dev/sd*`.

The issues doesn't happen on my Xperia X as it doesn't have `/dev/sd*` on the host.

Uninstalling `makedev` once container created ([https://github.com/ubports/libertine/blob/xenial/python/libertine/ChrootContainer.py#L76](here for example)) resolves the issue and makes it possible to create a container.

I wonder if we need `makedev` in a container? Or it could be safely removed?

**Comment by milikhin** [comment]
> When running the following command:
> `libertine-container-manager create --type chroot -i vuldin-container`
> 
> I get lots of output with errors ending in the following:
> 
> ```
> ...
> Errors were encountered while processing:
>  ca-certificates
>  dictionaries-common
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ChrootContainer.py:126: ERROR: create_libertine_container(): Failure installing 'apt-transport-https' during container creation
> libertine-container-manager:123: ERROR: create():    Failed to create container: 'destroy_libertine_container() missing 1 required positional argument: 'force''
> ```
> 
> Then trying this command says the container doesn't exist:
> `libertine-container-manager exec -i vuldin-container -c /bin/bash`

Setting `TMPDIR=/tmp` env var resolves the issue for me: `TMPDIR=/tmp libertine-container-manager exec -i vuldin-container -c /bin/bash`

**Comment by milikhin** [comment]
Setting `TMPDIR` environment variable before executing libertine-container-manager resolves the issue with `ca-certificates` for me.
It's just: `TMPDIR=/tmp libertine-container-manager create --type chroot -i vuldin-container`.
Then `ca-certificates` package is installed successfully and a container is created.

**Comment by RoiArthurB** [comment]
Any update on this issue ?

I freshly install UT on my old OnePlus3 and none of the creation of a container by the 3 methods (GUI, cli, cli w/ `TMDIR`) works, I have `Permission denied` errors cause by `makedev` and `mknod` _packages_ 😞

**Comment by PeterCxy** [comment]
@RoiArthurB add `self.run_in_container('apt remove -y makedev')` to line 86 of `/usr/lib/python3/dist-packages/libertine/ChrootContainer.py` fixed libertine container creation for me. This basically just gets rid of makedev once `debootstrap` finishes

**Comment by RoiArthurB** [comment]
@PeterCxy it works, thanks a lot ! 🙏
Just asking, this _quick fix_ will be erased at the next UBports update, right ?
