### ISSUE TITLE
Working through ssh - connection hang

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1306]
- Device: OP3
- Channel: Edge
- Build: 19/11/25

### Steps to reproduce
While i'm working on the device, usually to develop script, with the OP3 time to time the command hangs. To resume it, it requires to push the power button only. 

### Expected behavior
Not having an ssh connection hanging like on the Nexus 5. 

### Actual behavior
Time to time the ssh connection hang.

**Comment by Flohack74** [comment]
Hmm edge channel might not be the best choice, is there a reason for still using it?

**Comment by Vince1171** [comment]
> Hmm edge channel might not be the best choice, is there a reason for still using it?

It's unfortunately the only available for now, edge-arm64

**Comment by dobey** [comment]
This is because the screen has gone off and the phone has entered lower power mode, so it seems like ssh hangs because `sshd` doesn't have priority and isn't holding a wakelock when a connection is established.

Simple workaround is to set the screen off timeout to never.

**Comment by ernesst** [comment]
the priority shouldn't be depend of the device isn't it ?

**Comment by Vince1171** [comment]
> the priority shouldn't be dependent of the device isn't it ?

it's not dependent of the device
but in your case it's maybe due to your manual start of ssh #1301

**Comment by ernesst** [comment]
I think you are right, might not be a bug.

**Comment by Vince1171** [comment]
closed as it seems to be related to #1301
