### ISSUE TITLE
Add LED charge indication on M10 HD (cooler)

### ISSUE THREAD

**Issue by jug007** [ubports/ubuntu-touch#1307]
### Description of the feature
When charging you M10 HD, the LED does not light up other than for notifications.
It would be nice to see the LED turn on when charging and it change colour depending on what charging state it is at.
Idealy the charging indication would turn off when you get a notification, so that this could be shown instead of the charging state.
Maybe also turn the charging indicator off, when the charge has reached a certain point, e.g. 85%.

Personally I want to know when my devices are ready to get removed from the charger, and I would also know if they are actually charging. When devices and charging cables get older, you might not always put the cable in securely, and it might stop charging without you noticing it.

**Comment by Flohack74** [comment]
Does the LED work when receiving notifications?

**Comment by Flohack74** [comment]
This is already already recorded and a cross-device feature request. Please also see those requests and issues:
https://github.com/ubports/ubuntu-touch/issues/463 
https://forums.ubports.com/topic/3292/support-for-led-notifications
