### ISSUE TITLE
Mobile data not working on Nexus 4 (devel)

### ISSUE THREAD

**Issue by hendrikscheewel** [ubports/ubuntu-touch#1310]
- Device: mako
- Channel: devel
- Build: 2019-11-28

### Steps to reproduce
After the last upgrade to devel on Nexus 4 I can't get a mobile data connection. The network indicator does not show "H" / "E" / "3G" etc. anymore, however, in the dropdown menu it still appears as usual. When switching to stable/rc everything works again. A second switch back to devel and the problem is there again.

### Expected behavior
Working mobile data connection and indicator on network strength on Nexus 4 devel.

### Actual behavior
No mobile data. No indicator. Calling still works.

### Logfiles and additional information
I am not sure where to find the logs for it. I'd be happy if someone could indicate the right logfile.

**Comment by simoxxx** [comment]
same here

**Comment by Danfro** [comment]
Same here on E5 devel.
Calls work, network doesn't. Wifi is fine.

**Comment by hendrikscheewel** [comment]
> same here
Which device do you have?

**It seems so far there are problems on:**
Nexus 4 (mako), devel
BQ Aquaris E5 (vegetahd), devel
BQ Aquaris E4.5 (krillin), devel

**Comment by UniversalSuperBox** [comment]
I've reverted the change that caused this issue (thanks for the testing, folks) and ofono is rebuilding now. Even though we're only a few hours away from a new image, I'll trigger a rebuild of them now to keep people who are still upgrading out of trouble. I'll post again when that finishes.

**Comment by UniversalSuperBox** [comment]
Okay, good to go. If you've got a bad update, you can update and you'll have mobile data again.

**Comment by UniversalSuperBox** [comment]
We're trying to test a revised version of the commit that caused this issue with https://github.com/ubports/ofono/pull/10, ensuring that it does *not* happen again. Could you please try the following on your devices?

```
wget https://ci.ubports.com/job/ubports/job/ofono/job/PR-10/1/artifact/ofono_1.18.0+ubports2+0%7E20191206080530.1%7E1.gbpf3ca76_armhf.deb
wget https://ci.ubports.com/job/ubports/job/ofono/job/PR-10/1/artifact/ofono-scripts_1.18.0+ubports2+0%7E20191206080530.1%7E1.gbpf3ca76_all.deb
sudo mount / -o remount,rw
sudo apt install ./ofono*.deb
sudo reboot
```

Then test if you're able to use cellular data and calling normally.

**Comment by balcy** [comment]
works on BQ Aquaris 4.5 on DEV (2019-12-06)

**Comment by Danfro** [comment]
mobile data: check
call incoming: check
call outgoing: check

Works fine on my E5 on DEV (2019-12-06).

**Comment by hendrikscheewel** [comment]
On Nexus 4 devel (2019-12-12)
- [x] mobile data
- [x] calling

**Comment by StefWe** [comment]
On MX 4 stable
- mobile data works
- calling works

**Comment by UniversalSuperBox** [comment]
Thanks, everyone. https://github.com/ubports/ofono/pull/10 has been merged!
