### ISSUE TITLE
Wiundows installer problems

### ISSUE THREAD

**Issue by n7wwk** [ubports/ubuntu-touch#1311]
Windows 7 displays large error message when instilling and closes using windows 7 64bit
--------------------------------------------------------------------------------

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

### Illustrations

- Device:
- Channel:
- Build:

**Comment by n7wwk** [comment]
tried to load screen grab of error but was un able to

**Comment by UniversalSuperBox** [comment]
Hi @n7wwk,

A better place to report issues with the installer is https://github.com/ubports/ubports-installer. You can click the "Report a bug" button in the installer at any time to do this, and all of the relevant logs will be included.

Thanks for your interest, and thanks for taking this step!
