### ISSUE TITLE
No incoming call ringtone

### ISSUE THREAD

**Issue by lakotaubp** [ubports/ubuntu-touch#1312]
### Illustrations

- Device: OnePlus3
- Channel:edge
- Build:01/12/2019

### Steps to reproduce

Call the device

### Expected behavior

 incoming call ringtone should start along with incoming call dialog box

### Actual behavior

device vibrates. incoming call dialog box does appear

**Comment by ziggutas** [comment]
The same behaviour for roughly 95% of incoming calls on OP3T,edge channel, 2019-11-22/2.

Remaining 5% incoming calls there is no visible/audible response detected and phone remains in standby. In this case turn the phone on after incoming has terminated call and the dialler app is displayed (where it was closed beforehand).Or turn phone on whilst call still incoming: phone turns on, vibrates, dialog box, no sound.

**Comment by ziggutas** [comment]
OP3T, edge , 2020-01-14/2
Incoming call ringtone is mostly working with today's update. It seems to work as expected with phone turned on but a bit hit and miss when in standby.
I would be happy to test this in a more organised way if asked. As long as it was not too technical ;)

**Comment by ernesst** [comment]
I don't experience any issue with incoming call and ringtone. Could you please confirm @Vince1171 or other ?

**Comment by ziggutas** [comment]
Incoming ringtone still hit and miss on OP3T , edge, 2020-01-20/2.
Sometimes behaves as expected. Sometimes no response until turn on device during call, then rings. Sometimes no response, end call on initiating phone, turn on device and incoming will ring endlessly until stopped by touching end call on dialogue box.

Don't know whether this is valid, but here is output of cat /system/etc/audio_platform_info.xml that you asked pglushkov on the forum post for OP3 for same issue

![Screenshot from 2020-01-21 22-37-07](https://user-images.githubusercontent.com/47629986/72849510-bf49b700-3c9e-11ea-9329-10c592c8f8c3.png)

**Comment by ernesst** [comment]
Interesting, I'm using OP3 not the OP3T,

**Comment by ernesst** [comment]
@ziggutas 
Would it be possible for you to test my Halium as per pad : https://pad.ubports.com/p/Oneplus3 ?

**Comment by ziggutas** [comment]
Sadly, no. I can't understand the instructions or make sense of the procedures; I'd be in way over my head with probably a zero chance of getting anywhere. Sorry.

**Comment by ernesst** [comment]
This bug can be close, as several person confirm the ringtone is present now:
https://forums.ubports.com/topic/3253/oneplus-3-3t/219

However there is still another bug with incoming call, i'll create it.
