### ISSUE TITLE
Ask for arm64 openstore

### ISSUE THREAD

**Issue by kissstudio** [ubports/ubuntu-touch#1313]
I'm using a oneplus3 phone and installed the 16.04, build 20191130.
I find it does not contains openstroe app.

The others phone may be armhf arch, and this one should be arm64.

i have built a arm64 arch openstore and installed on my phone, however the install button 
to a app in the store seems not really did a install operation but other functions like view app list or details is work correctly.

Will i have a official arm64 openstore app ?

By the way, advise add a arch list to a store app meta data to detail what arch's a app supported.

**Comment by jonnius** [comment]
Arm64 is WIP. Check this on how to test it: https://blog.bhdouglass.com/openstore/ubuntu-touch/2019/11/30/openstore-multi-arch.html

**Comment by kissstudio** [comment]
![15755069256838026963662816629317](https://user-images.githubusercontent.com/2771647/70194060-2be31380-173c-11ea-894f-29584bfece06.jpg)
But it can not be modified even using sudo as read only file system, any idea?

**Comment by kissstudio** [comment]
Does the tip means the build machine?

**Comment by bhdouglass** [comment]
You're need to make your image writable (you can do that easily from UT Tweak Tool)

**Comment by kissstudio** [comment]
😂 not really easy.  I have to build and install a  arch64 UT Tweak Tool. 
And the number of apps at staging.open-store.io is few. Wish most of the apps on current store have the arch64 build next year.😊

I will not change to staging store currently. i think i have more important things to do, the system is not fluent on phone sometimes. Terminal crash, browser got stuck, web page load slow... I want do something to make ubtouch more fast, more stable.

**Comment by bhdouglass** [comment]
Haha, sorry, that was a silly suggestion! Thank you for your testing :) The OpenStore will release the update for multi arch support soon.

**Comment by UniversalSuperBox** [comment]
The OpenStore has been released for ARM64 and is now in arm64 device images.
