### ISSUE TITLE
Unable to write a message when opening messaging app from the notification menu

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1327]
### Illustrations

- Device:N5
- Channel:Devel
- Build: Today

### Steps to reproduce

Receive a sms, swipe to open the notification menu, click on the icon on the right of the message.
messaging-app is opened, the input field is at the bottom, no keyboard displayed. Unable to force opening it. Need to restart the app.

### Expected behavior

be able to reply to a message

### Actual behavior

Keyboard not shown. Need to close the app and re-open it

**Comment by lduboeuf** [comment]
This occurs when phone screen is off.

**Comment by Danfro** [comment]
I can not confirm this on my E5, devel 2020-01-04. Maybe a case of #1268 ? Or maybe fixed with one of the recent changes to messaging app?

**Comment by lduboeuf** [comment]
Oh, yes seems to be good now ;-)
