### ISSUE TITLE
Going back from any specific setting, scrolls always up in the main settings menu

### ISSUE THREAD

**Issue by fcarp10** [ubports/ubuntu-touch#1331]
- Device: Nexus 5
- Channel: edge
- Build: 2019-12-29/2

### Steps to reproduce
From any setting screen e.g. About, Updates, Security & Privacy, go back to the main settings menu.

### Expected behavior
To go back to the same position of the item list that was selected

### Actual behavior
Now it always scrolls up the list to some other position, which makes hard for the user to follow up

**Comment by UniversalSuperBox** [comment]
Hi @fcarp10,

Thanks for your interest in Ubuntu Touch!

I believe this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/634. I'll close this issue in favor of the older one to keep the tracker clean.
