### ISSUE TITLE
Halium: Device does not provide MTP interface when connected to a PC

### ISSUE THREAD

**Issue by giterium** [ubports/ubuntu-touch#1332]
- Device: Oneplus 3T
- Channel: Edge
- Build: 2019-12-30

**Actual behavior**
Plugging in the Oneplus 3T to Windows or Linux computer does not mount MTP.

**Comment by Flohack74** [comment]
This is specific to Halium ports atm I think. I will ping a few folks to ask the status here.

**Comment by Flohack74** [comment]
So coming back from looking into this: Actually the porter needs to do quite some lifting here, to start mtp-server, switch the modes etc. There are patches available to help with that. In the case of OP3/T it´s @Vince1171 who can do that probably. Do you know where to find that patches ? ;)

**Comment by giterium** [comment]
I don’t know where to find them or how to install them

**Comment by Flohack74** [comment]
Take a look here:
https://github.com/fredldotme/device-sony-common/commit/0884785cd5edd74c27626a37c52a02a8d96d83f6
https://github.com/fredldotme/device-sony-common/commit/8a06f2345883e8bc0cd2e8ea6d2366e4a153aed6
But be warned, those crashed my device immediately on boot ;)

**Comment by ernesst** [comment]
Fixed by : https://github.com/Halium/android_device_oneplus_oneplus3/commit/5d186e41c70fc5f52f372a9d60769bb2542411cc

**Comment by giterium** [comment]
Thanks :) really work :)
