### ISSUE TITLE
Backlight not turned off after switched to sleep mode

### ISSUE THREAD

**Issue by Wesseldr** [ubports/ubuntu-touch#1333]
- Device: Nexus 5 (hammerhead)
- Channel: 16.04/edge | Jan 05 2020
- Build: 20200105

### Steps to reproduce

Work with the phone
Push the button Power-Button to lock the phone.
Take the phone to a dark room and you see still the backlight leak through the screen indicating it is still on.

### Expected behavior
Backlight is turned off

### Actual behavior
Backlight is still on, draining a lot of power from the battery in 24h (like mentioned in: https://github.com/ubports/ubuntu-touch/issues/387)

### Logfiles and additional information
Might be related to: https://github.com/ubports/ubuntu-touch/issues/230 & https://github.com/ubports/ubuntu-touch/issues/387

**Comment by Flohack74** [comment]
Hmm can you please retry with devel channel, edge does not get frequent updates, and it may look better there.

**Comment by Wesseldr** [comment]
- Device: Nexus 5 (hammerhead)
- Channel: 16.04/develop | Jan 08 2020
- Build: 20200108/2

Also I activated a login code this time. It looks like this works now :-) No more backlight on

Thanks!
