### ISSUE TITLE
Does not install update on Oneplus 3T

### ISSUE THREAD

**Issue by giterium** [ubports/ubuntu-touch#1334]
Device: Oneplus 3T
Channel: Edge
Build: 2020-01-04

I started downloading the update and turned off my phone. The next day I tried to install it - it did not work. When rebooting, the update screen was displayed. But in the update menu you can see that the update has not been completed.

![update](https://user-images.githubusercontent.com/16814062/71804763-7d512c00-3075-11ea-8b2b-95eb5ed73cc8.gif)

**Comment by MK1973** [comment]
I think You have full cache. Delete wth:
`sudo mount -t tmpfs tmpfs /var/cache/apt/archives`

**Comment by giterium** [comment]
It hasn't changed anything

**Comment by giterium** [comment]
The update is performed. This is a gui error.

![21563097-41A1-42CA-826D-F21ACCDED534](https://user-images.githubusercontent.com/16814062/71815427-7be12d00-3090-11ea-8d84-2e3dba972c79.jpeg)

**Comment by Flohack74** [comment]
Sometimes if update A was downloaded, and later there is a new update B, the GUI wants to still install update A, which is not available anymore. This is a bug of system-settings, and for the time being can be resolved with the UT tweak tool:
* Open tweak tool and confirm PIN
* Open upper left hamburger, go to Apps & Scopes
* Open all apps, and then look for system settings
* Delete cache & app data, NOT config! If you delete config, all your settings are lost

That should make it able for the updater to discover the more recent update, and you can continue from hereon.
