### ISSUE TITLE
Below-screen button blinking when screen off and device charging even if there are no notifications

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#1336]
- Device: Meizu MX4 arale
- Channel: devel
- Build: 2020-01-04

### Steps to reproduce
Make sure there are no unread notifications left and turn the screen off. The button below screen starts blinking.

### Expected behavior
That behaviour (blinking button) should only appear if there are unread notifications present.

### Actual behavior
Button is blinking no matter what.

This behaviour is observable on devel for at least the last ~2 or 3 weeks.

**Comment by zubozrout** [comment]
Oh, also interesting fact I only noticed now - the bellow screen button only flickers when the device is connected via USB (charging). Doesn't flicker without the cable plugged in. But since I have the phone on my desk and at night always connected to a charger, I experience this all the time.

**Comment by UniversalSuperBox** [comment]
Is the light on the MX4 a single color only? Indication of battery state while charging was merged with https://github.com/ubports/unity8/pull/226. Devices with multi-color LEDs show their charging state now.

**Comment by zubozrout** [comment]
@UniversalSuperBox Thank you very much, that makes sense then :).
And yes, AFAIK it is white only - at least I've never ever seen it flicker any other color even when I had Android on the device.

**Comment by UniversalSuperBox** [comment]
But it is flickering and not solid? Strange, maybe it's unable to light solidly. Wonder how we're going to solve that one...

**Comment by zubozrout** [comment]
Yes, it is flickering. But it can for sure light solidly - not sure if I've ever properly experienced that behaviour but I've seen it stuck many times over the years which was always fixed by turning the screen on/of and/or touching the flickering button with a finger (though have not seen it recently).

**Comment by zubozrout** [comment]
Anyway, the white light is pretty bright so at night could be very disturbing. Maybe it would be best to just disable the charging indication on MX4 completely.

**Comment by cibersheep** [comment]
I can confirm this. Notification and charging home button led is «pulsing white»

**Comment by zubozrout** [comment]
Actually, I would suggest adding this to OTA-12 as currently I have to put my phone facing screen down each night so that it doesn't light the whole room. And I certainly can't tell whether I have received a notification during charging because the flickering is the same.
