### ISSUE TITLE
Xperia X camera hardware permissions

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#1340]
- Device:  Xperia X
- Channel: Dev
- Build:  123

### Steps to reproduce

Pop up that says camera app doesn't have permission to access camera hardware with option to cancel or edit permissions.

### Expected behavior

Camera to load
### Actual behavior

No option to change hardware permissions when edit pessions option selected.

**Comment by Dave1152000** [comment]
Seems to have been fixed on next update.

**Comment by Flohack74** [comment]
So can we close it?

**Comment by Dave1152000** [comment]
Yes it's gone through 2 updates and seems to be OK.

 

Thanks Dave

 
 

Sent: Wednesday, January 15, 2020 at 10:44 PM
