### ISSUE TITLE
Camera doesn't zoom

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#1341]
### Illustrations

- Device: Oneplus 3
- Channel: Edge
- Build: 2020-01-13

### Steps to reproduce

1. Open Camera
2. Pinch to zoom

### Expected behavior

- Camera zooms in or out

### Actual behavior

- Zoom slider moves but camera does not zoom

**Comment by Flohack74** [comment]
Its the same on Oneplus One. Seems they broke it everywhere...

**Comment by giterium** [comment]
Confirmed for me too on OnePlus 3T

**Comment by ernesst** [comment]
FYI Thanks to the peat_psuwit : GStreamer-droid based camera support on the OP3 the zoom works.
More information : https://forums.ubports.com/topic/3257/how-to-test-gstreamer-droid-based-camera-support-in-ubuntu-touch-for-halium-7-1-based-port
