### ISSUE TITLE
Webapps using the standard container are rotated in external display when in portrait aspect ratio

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1344]
- Device: Nexus 5
- Channel: Devel
- Build: 20200114/2

### Steps to reproduce
1. Connect to an external display
2. Switch to desktop mode
3. Open a webapp that use the standard container. i .e Webtelegram
4. Resize the window wherein its height is bigger than its width (portrait)

### Expected behavior
The webapp will be displayed correctly.

### Actual behavior
The webapp is rotated.
![screenshot20200115_044147361](https://user-images.githubusercontent.com/29456786/72500273-72945500-3834-11ea-8d13-0ce0620da18e.png)

**Comment by mr-growl** [comment]
I'm also seeing this behaviour (I'm on  2020-W19)

**Comment by Flohack74** [comment]
I put this to OTA-14 since its really annyoing ^^

**Comment by kugiigi** [comment]
This issue also happens in Morph. Upon investigation, components thatare based from `BrowserView` are the ones that rotates the content in portrait. Not yet sure what exactly causes the issue.`OrientatiomHelper` is used in `BrowserView` which seems to relevant but replacing it stiill doesn't solve the issue.
