### ISSUE TITLE
Morph browser does not support WebGL

### ISSUE THREAD

**Issue by giterium** [ubports/ubuntu-touch#1349]
- Device: Oneplus 3T
- Channel: Edge
- Build: 2020-01-17

**Actual behavior**
Morph browser does not support WebGL. All apps that use WebGL do not work in the system.

**Comment by lduboeuf** [comment]
From what i understand, this will not be fixed until having Wayland egl working on UT and upgrading qtwebengine ( the engine under Morph ) , this is not an easy task , but it's in progress.

**Comment by lduboeuf** [comment]
https://github.com/ubports/morph-browser/issues/231

**Comment by Flohack74** [comment]
Please follow this issue at the link from @lduboeuf. I close here.
