### ISSUE TITLE
Tabs (Apps & Scopes) like a carousel ...

### ISSUE THREAD

**Issue by Gabriele69** [ubports/ubuntu-touch#135]
Hello to all
I had already reported this thing on Launchpad.
I think it would be better if we scrolled in the tabs that contain the Apps page and the scopes like a "carousel" so that once you get to the last element, continuing scrolling, go back to the first (similar to what happens on Android devices). 
When we activate many areas it's tough, having to go back looking for it. Yes, it is true, we can click the "ubuntu" logo on the sidebar to go back to the first card, but if we need to get to another card the "carousel" could solve it more easily

**Comment by Flohack74** [comment]
Would tnhis be then a unity8 feature? I am just thinking if we shall start tracking issues specifically for unity8 in a separate tracker :)

**Comment by dobey** [comment]
It would be a unity8 feature, but this is also not how it works on any android device i've ever used. Plus, if we're getting rid of the dash and scopes, this won't matter.

**Comment by NeoTheThird** [comment]
Closing, since scopes are going to be removed https://github.com/ubports/unity8/issues/14
