### ISSUE TITLE
Apps sorting in Scopes doesn't respect current language

### ISSUE THREAD

**Issue by ezze** [ubports/ubuntu-touch#1350]
An order of apps (Приложения) when using Russian language (and probably any other language) doesn't seem to respect locale sorting. I thought apps are sorted by their internal names (in English) but not by their labels (translations) but comparing lists of applications on two devices with different languages (Russian and English) I can't understand what's the sorting algorithm in the first case. I believe it would be better to sort applications according to locale settings in order to make their searching much easier.

I was looking for a repo where I can help with contribution to resolve it but unfortunately didn't manage to find it.

**Sorting in Russian**

"Календарь (Calendar)" should be before "Калькулятор (Calculator)", and "Галерея (Gallery)" should be before both of them just like "Заметки (Notes)". "Медиаплеер (Media Player)" should go after all of them. Here is the desired order of first six applications in the list:

- Галерея (Gallery)
- Заметки (Notes)
- Календарь (Calendar)
- Калькулятор (Calculator)
- Медиаплеер (Media Player)
- Музыка (Music)

![scopes-sort](https://user-images.githubusercontent.com/665479/72663144-1716c280-3a00-11ea-8249-098251e39592.png)

**Sorting in English**

In English all apps are sorted in alphabetical order and are easy to be found.

![screenshot20200118_145329881](https://user-images.githubusercontent.com/665479/72663325-6a8a1000-3a02-11ea-8d06-2a5055ffe829.png)

**Comment by dobey** [comment]
I'm closing this as scopes are already removed from the devel channel, and apps scope is now replaced by the app drawer, so this won't be fixed. If this is still a problem in devel with the app drawer, please open a new issue in https://github.com/ubports/unity8 for it. Thanks.
