### ISSUE TITLE
[OP3]  - No incoming call notification in sleep mode

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#1355]
- Device: OP3
- Channel: Edge
- Build: all

### Steps to reproduce
Let the phone going for a sleep or deep sleep and then call it. Randomly the phone will woke up or not. 
Somebody describe it there : https://forums.ubports.com/topic/3253/oneplus-3-3t/219

No issue when the phone is awake.

### Expected behavior
Phone wakes up all the time. 

### Actual behavior
50% of the time the phone doesn't wake up

### Logfiles and additional information
Several ideas/trial:

-  Ofono doesn't switch from LTE to GSM mode for the call <= Not for this case
- Kernel setup : I've tried 3 different kernel on the phone : Lineage, OOS, and Flashkernel. No difference found.  <= Not for this case
- Setup for the quirk for ofono, i've played with the different sink, the current situation is the best behavior we can have.  <= Not for this case

This bugreport, https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1516696, gives some information how to trace communication between ofono and telepathy-ofono. 

The msg-monitor script give :
```phablet@ubuntu-phablet:~$ tail -f ~/.cache/upstart/msg-monitor.log
dbus-monitor: unable to enable new-style monitoring: org.freedesktop.DBus.Error.AccessDenied: "Rejected send message, 1 matched rules; type="method_call", sender=":1.137" (uid=32011 pid=7420 comm="dbus-monitor --system type=signal,interface=org.of") interface="org.freedesktop.DBus.Monitoring" member="BecomeMonitor" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)". Falling back to eavesdropping.
Sat Jan 25 20:53:53 CST 2020 signal time=1580007229.707430 sender=org.freedesktop.DBus -> destination=:1.137 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
Sat Jan 25 20:53:53 CST 2020    string ":1.137"
Sat Jan 25 20:53:54 CST 2020 signal time=1580007233.774149 sender=org.freedesktop.DBus -> destination=:1.110 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
Sat Jan 25 20:53:54 CST 2020    string ":1.110"
Sat Jan 25 20:53:54 CST 2020 signal time=1580007233.774197 sender=org.freedesktop.DBus -> destination=:1.110 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
Sat Jan 25 20:53:54 CST 2020    string ":1.110"
Sat Jan 25 20:55:21 CST 2020 method call time=1580007321.636863 sender=:1.116 -> destination=:1.54 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
Sat Jan 25 20:55:21 CST 2020    string "Telephony Service Approver"
Sat Jan 25 20:55:21 CST 2020    uint32 0
Sat Jan 25 20:55:21 CST 2020    string "file:///home/phablet/.local/share/evolution/addressbook/system/photos/pas_id_5E15790C00000023_photo-file0.image%252Fjpeg" 
```

20:53 I call while the phone sleeping... no transfert of notification, at 20:55 i've wake-up the phone and then call it... no problem the notification is carried.

The on ofono log side, i've found one suspicious line:
```
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: message repeated 2 times: [ gril/gril.c:handle_unsol_req() RIL Event slot 0: UNSOL_OEM_HOOK_RAW]
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: get_property_value: ERROR reply to Get
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: plugins/accounts-settings.c:get_property_reply() property DefaultSimForCalls has value (null)
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: plugins/accounts-settings.c:get_active_seat_uid() seat seat0 with uid 32011
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: plugins/accounts-settings.c:get_active_seat_uid() seat seat0 with uid 32011
Jan 25 19:04:37 ubuntu-phablet ofonod[1939]: plugins/accounts-settings.c:get_property_reply() property DefaultSimForCalls has value /ril_0
Jan 25 19:04:38 ubuntu-phablet ofonod[1939]: src/voicecall.c:ofono_voicecall_notify() Got a voicecall event, status: 4, id: 1, number: +33XXXXXX called_number: , called_name 
Jan 25 19:04:38 ubuntu-phablet ofonod[1939]: src/voicecall.c:ofono_voicecall_notify() Did not find a call with id: 1
Jan 25 19:04:38 ubuntu-phablet ofonod[1939]: gril/gril.c:handle_unsol_req() RIL Event slot 0: UNSOL_OEM_HOOK_RAW
Jan 25 19:04:38 ubuntu-phablet ofonod[1939]: message repeated 2 times: [ gril/gril.c:handle_unsol_req() RIL Event slot 0: UNSOL_OEM_HOOK_RAW]
Jan 25 19:04:38 ubuntu-phablet ofonod[1939]: get_property_value: ERROR reply to Get
```
**src/voicecall.c:ofono_voicecall_notify() Did not find a call with id: 1**
After that nothing move and no notification ...

Seems that Mer ofono fixed a similar log output but for an active voice call and a waiting one  by : https://git.sailfishos.org/mer-core/ofono/commit/213df4e7c43a4e4e5d92b9b4e1f627e21d903e22
Update : The commit seems to be for bluez which it's not relevant + for a good incoming call this is displayed too.

Maybe this one might help too : https://www.mail-archive.com/ofono@ofono.org/msg07705.html

**Comment by ziggutas** [comment]
Somebody noticed that phone wakes up consistently when charging.
Test described here https://forums.ubports.com/topic/3253/oneplus-3-3t/249
Same results on my 3T also.

**Comment by ernesst** [comment]
Possible similar issue : https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1232093

**Comment by ernesst** [comment]
This commit has not effect unfortunately : https://git.sailfishos.org/mer-core/ofono/commit/213df4e7c43a4e4e5d92b9b4e1f627e21d903e22

**Comment by ernesst** [comment]
It appear that the bug is easily repeatable by just letting seating the for for couple of minutes, if the phone is off + charging there is no problem.

I've check the ril log, Ofono log then now repowerd log.
Most of the case I can see the incoming log information on ril and ofono... where I see the situation stalling/blocking seems to be at repowerd. 

Syslog ofono : 
https://paste.ubuntu.com/p/M9xcJc7Qzr/

Repowerd : 
https://paste.ubuntu.com/p/DJcxPQYnHF/

It can be seen that repower got the information from ofono : OfonoVoiceCallService: dbus_CallAdded(/ril_0/voicecall01,incoming)
Then wait 20 secs, I drop the incoming call from skype (for trial) and ofono send a OfonoVoiceCallService: dbus_CallRemoved(/ril_0/voicecall01)
and finally that appears : UnityScreenService: dbus_setScreenPowerMode(:1.81,on,5) etc.... and the screen turn on with the incoming call notification fading out. 

In Cannonical time, i've created this bug, and likely to be related : https://bugs.launchpad.net/repowerd/+bug/1588526

**Comment by Vince1171** [comment]
Should be fixed in the next update thanks to @ernesst :)

**Comment by Flohack74** [comment]
Can someone confirm that this is solved?

**Comment by ernesst** [comment]
Fixed :)
