### ISSUE TITLE
Remove the limitation to only 4 digit pin

### ISSUE THREAD

**Issue by AppsLee** [ubports/ubuntu-touch#1360]
### Description of the feature
To improve my phone security I would like to use more than 4 digits pin.

### Illustrations
The pin code to unlock the phone is limited to a 4 digits pin.
And the full keyboard when using a passphrase is slowing the unlock process.
So I think it may be good to be able to input at least 6 digits or maybe something like 4-12 digits.
The num pad is convenient to type the code faster and the security will be better too. 

Best regards

**Comment by mateosalta** [comment]
https://github.com/ubports/ubuntu-touch/issues/1027
https://github.com/ubports/ubuntu-touch/issues/686
