### ISSUE TITLE
Feature Request: Clock Timer / Stopwatch Ringtone Choice

### ISSUE THREAD

**Issue by LDovic** [ubports/ubuntu-touch#1362]
### Description of the feature
The same choice of ringtones for the timer and stopwatch as the alarm clock. At the moment, the timer only plays the 'Alarm clock' default ringtone when the timer has completed. It would be good to have the same selection of ringtones as the alarm clock.

**Comment by UniversalSuperBox** [comment]
Hi @LDovic, 

Could you re-open this issue on the clock-app repository, https://gitlab.com/ubports/apps/clock-app/issues? This will make it more visible to people who might be able to help.

Thanks!

**Comment by LDovic** [comment]
Done, thanks

**Comment by UniversalSuperBox** [comment]
Thank you!

**Comment by Flohack74** [comment]
Or next time you can use the transfer issue function @UniversalSuperBox ;)

**Comment by UniversalSuperBox** [comment]
Transfer to GitLab?

**Comment by Flohack74** [comment]
Uh sorry, yes we moved that already.

**Comment by LDovic** [comment]
Hi, for next time do i put @UniversalSuperBox in the issue name or the description?
cheers

**Comment by Flohack74** [comment]
Sorry to confuse you, no please don´t. That was a ping for Dalton so I can get his attention. But that should never be a part of the issue data.
