### ISSUE TITLE
OSK On screen keyboard is not showing.

### ISSUE THREAD

**Issue by MrCyjaneK** [ubports/ubuntu-touch#1367]
### Description of the feature

- Device: zerofltexx (Samsung Galaxy s6)
- Channel: Stable? (Not sure I've got it from there: https://ci.ubports.com/job/xenial-rootfs-arm64/)
- Build: (???)

### Steps to reproduce
After flashing halium-boot, and using halium-install script to install ubuntu touch rootfs, adding udev rules I had to execute one more command before device booted succesyfully: `cp /usr/lib/lxc-android-config/70-zerofltexx.rules /lib/udev/rules.d/` then device worked, I was able to run some apps, (some not, they were stuck at loading screen, but that's not issue now).

I had only one issue, keyboard is not showing, when I tried to enter some textbox, I see blank space for keyboard, like on this photo: https://telegra.ph/file/a4ac382473ce385f4dbdb.png

### Expected behavior
I expect keyboard to work.

### Actual behavior
Keyboard is not working.

I don't know what log files to send, I'll add them later, if somebody will tell me what logs should I add.

**Comment by lduboeuf** [comment]
OSK should reload after touching on "Cancel" and try to gain focus again on password .
this is a known bug that seems to be corrected now, your image seems fairly outdated

**Comment by UniversalSuperBox** [comment]
Hi @MrCyjaneK,

This issue tracker is not an appropriate place to ask about issues related to an Ubuntu Touch device that you're porting. Please see the links in the "getting help" section of our porting guide: http://docs.ubports.com/en/latest/porting/introduction.html#getting-community-help

**Comment by MrCyjaneK** [comment]
> OSK should reload after touching on "Cancel" and try to gain focus again on password .
> this is a known bug that seems to be corrected now, your image seems fairly outdated

It doesn't.

**Comment by MrCyjaneK** [comment]
Ok @UniversalSuperBox
