### ISSUE TITLE
RC pre-OTA12, Nexus5 camera only shows front camera

### ISSUE THREAD

**Issue by AlanGriffiths** [ubports/ubuntu-touch#1369]
- Device: Nexus5
- Channel: RC
- Build: 2020-W07/2

### Steps to reproduce
Start the camera app

### Expected behavior
Shows image from rear camera

### Actual behavior
Shows image from front camera

Clicking the "switch cameras" icon gives a rotation transition, but still shows front camera

**Comment by AlanGriffiths** [comment]
Actually, this might be hardware - reverting to OTA11 didn't correct the behaviour.

**Comment by mr-growl** [comment]
I am using the same build on a nexus 5 and am seeing a similar issue.

When i start the camera app it shows a black screen with the usual camera interface. If i click the icon to switch to the front camera it works. However, if i switch back to the back camera it also starts working.

So my workaround, to sum up, is to switch to the front camera and then back to the back camera. At that point the back camera works as expected.

**Comment by mr-growl** [comment]
I've noticed that the problem only happens sometimes. For instance, today i opened the camera app 3 times and only saw the problem once, the other two times it was fine.

**Comment by mr-growl** [comment]
I have not seen the problem with 2020-W10 on nexus 5 yet (opened camera several times with no issues)

**Comment by Flohack74** [comment]
So do you think we can close it?

**Comment by AlanGriffiths** [comment]
> So do you think we can close it?

If nobody else sees it, I think it's the phone.

**Comment by mr-growl** [comment]
I saw this issue earlier today again (opened the camera app and just got a black screen).  I was still able to work around it by switching to the front camera and then to the back one again.

**Comment by AlanGriffiths** [comment]
> I saw this issue earlier today again (opened the camera app and just got a black screen). I was still able to work around it by switching to the front camera and then to the back one again.

That isn't _this_ issue. See, for example, the title: "Nexus5 camera only shows front camera".

**Comment by AlanGriffiths** [comment]
@mr-growl it isn't helpful to combine multiple issues into one report. The developers need to track what needs fixing and that's easier with a separate report for each problem. That is, is easier to close two or three reports, than it is to close half or a third of a report.

**Comment by mr-growl** [comment]
Fair enough.  I did some more investigation and found a way to reliably reproduce the issue I am seeing and have logged a new issue.
