### ISSUE TITLE
inconsistent width of OSK

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1373]
With todays devel update (2020-02-17) the launcher did get fixed open if no apps are open.

With no open apps the osk does get raised when entering search in the space between launcher and other side of screen.

Once another app is open e.g. Teleports, when entering the search the OSK does get opened across the full width of the screen.

Case 1 - no app open:

![screenshot20200217_183542665](https://user-images.githubusercontent.com/37637312/74675798-a7d5ef00-51b4-11ea-8eb7-3e45eb13a2e5.png)

Case 2 - app open:

![screenshot20200217_183534239](https://user-images.githubusercontent.com/37637312/74675810-ae646680-51b4-11ea-85e8-da2e14a73fa1.png)

**Comment by Fuseteam** [comment]
oh no more issues with the launcher having an exception for for apps open revert! :p

jokes aside the osk not drawing over the launcher looks usefull to me

**Comment by Danfro** [comment]
Keys are quite narrow then. So the user will have to get used to that. I suppose portrait is the most common usecase here. So we need to make sure that this is want we want to present to the user. 

The OSK not stretching across full width has it pros and certainly would solve #1370. But then I think it should be squeezed/narrow all the time to be consistent. If only to allow the user to get used to the fact that the keyboard will be narrower when used from the drawer.

**Comment by Flohack74** [comment]
The keyboard width in Case 1 is a joke. We need to fix that.

**Comment by Fuseteam** [comment]
yeah let's use it to fix #1370 and make case 1 the default xD

**Comment by Danfro** [comment]
Trouble is, it fixes #1370 only if no other apps are open. It is inconsistent and it is hard to use with those small keys.

So, as Florian said it quite straight forward 😉, it is rather a bug than a feature.

On Tue, 18 Feb 2020 03:45:38 -0800, Merkhad Luigton wrote:
> yeah let's use it to fix #1370 and make case 1 the default xD
>

--

**Comment by Fuseteam** [comment]
@Danfro i _am_ saying it should be consistent i'm saying it should always leave room for the launcher if the launcher is visible :p

**Comment by UniversalSuperBox** [comment]
@Fuseteam, no, it gets too narrow in that case, especially on smaller devices. The Launcher should instead cause the keyboard to dismiss.

**Comment by Fuseteam** [comment]
@UniversalSuperBox fair enough
