### ISSUE TITLE
Only partial drop down lists on Morph Browser (OPO rc and Raspberry Pi)

### ISSUE THREAD

**Issue by MenmuirMark** [ubports/ubuntu-touch#1379]
- Device: OPO
- Channel: rc
- Build: 2020-W07
*Also repeatable on Raspberry Pi

### Steps to reproduce
Log into Nationwide Building Society website
Try to fill in data in drop down list

### Expected behavior
Selecting the drop down shows full list of choices

### Actual behavior

Lists open on page but only top few choices are available - unable to find way to scroll down on touch screen but can use an external keyboard and mouse to select. This is the same for text or numeric drop downs (Months, dates or numbers 0-9). It was not a problem before the recent update.

**Comment by MenmuirMark** [comment]
Issue repeatable on other websites including scotrail.co.uk
![screenshot20200223_104717156](https://user-images.githubusercontent.com/35196780/75110751-150cd880-562a-11ea-949a-97975162c604.png)

**Comment by MenmuirMark** [comment]
![image20200223_104638045](https://user-images.githubusercontent.com/35196780/75110792-79c83300-562a-11ea-91f7-25dbfdb48024.jpg)
Behaviour on Firefox/Raspian

**Comment by lduboeuf** [comment]
yes noticed that too on some websites ( but not all ), i can't work on it now, but hopefully next week will have a look. Hope that RC will not land on stable since then

**Comment by MenmuirMark** [comment]
Thanks.

**Comment by lduboeuf** [comment]
humm, that is strange, i've tested those website now, and dropdowns display well ( i'm on a 2 weeks old image ). But i confirm i had the display problem last time

**Comment by lduboeuf** [comment]
![screenshot20200227_081505737](https://user-images.githubusercontent.com/11663835/75421358-5c50dd00-593a-11ea-8f05-834812e4ef26.png)

**Comment by MenmuirMark** [comment]
Strange indeed. Still a problem here on OPO rc (up to date).
Your screenshot showed a different scaling. Could that be a factor?
Mark

On Thu, 27 Feb 2020 07:21:43 +0000, Lionel Duboeuf wrote:
> humm, that is strange, i've tested those website now, and 
> dropdowns display well ( i'm on a 2 weeks old image ). But i 
> confirm i had the display problem last time
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by lduboeuf** [comment]
no, it cannot, we need confirmation from others too. And logs might help

**Comment by MenmuirMark** [comment]
http://paste.ubuntu.com/p/3GWd7TGnMn/

**Comment by MenmuirMark** [comment]
I have a very slow internet connection - but this is the only bit in the log that pertains to the Scotrail site.

**Comment by MenmuirMark** [comment]
http://paste.ubuntu.com/p/Cmkzm76XRv/

**Comment by MenmuirMark** [comment]
There was discussion on the UBports QA and testing Telegram group on Sunday.

**Comment by lduboeuf** [comment]
so nothing wrong on logs, very weird issue. 
I didn't do anything on my side ( no OTA updates ) since the day it was not working, and now it works as expected. The only things that have changed is the wifi connection. Even though, how can this affect the dropdown detection ?. The only thing i'm thinking off, is that the website has not been properly loaded, and thus the script that detect dropdowns is not loaded too. I will test something when i'm back

**Comment by lduboeuf** [comment]
on your side can you test those website with a better internet connection ?

**Comment by MenmuirMark** [comment]
Hopefully be able to test it when out and about tomorrow.

**Comment by giiba** [comment]
I have noticed this behaviour and it seems to happen if the page has not fully loaded when the select item is clicked.

If the page is loading still, the old glitchy behaviour happens. But once the page is fully loaded, clicking the same element again brings up the nice new interface.

So it may well be a connection issue.

**Comment by MenmuirMark** [comment]
Interesting. When I can get to a better connection I'll try it and let you know.

On Fri, 28 Feb 2020 07:40:14 -0800, giiba wrote:
> I have noticed this behaviour and it seems to happen if the 
> page has not fully loaded when the select item is clicked.
>
> If the page is loading still, the old glitchy behaviour 
> happens. But once the page is fully loaded, clicking the same 
> element again brings up the nice new interface.
>
> So it may well be a connection issue.
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by lduboeuf** [comment]
ok, i see how we can improve that, will PR this as soon as i'm back

**Comment by lduboeuf** [comment]
please try PR-302 if it fix your issue:
`sudo ubports-qa install PR-302`
if disk space issue, run before:
`sudo mount -t tmpfs tmpfs /var/cache/apt/archives/`

**Comment by MenmuirMark** [comment]
That has fixed it. I thought I had enough space but I didn't. Got there eventually if a bit messily.
 :)
phablet@ubuntu-phablet:~$ apt list --upgradeable
Listing... Done
thumbnailer-service/xenial 2.5+ubports1+0~20200219154510.1~1.gbpa4387b armhf [upgradable from: 2.5+ubports1+0~20190514224648.4~1.gbpa4387b]
N: There are 4 additional versions. Please use the '-a' switch to see them.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/morph-browser/pull/302
