### ISSUE TITLE
Regression: google account broken

### ISSUE THREAD

**Issue by dekkerj1** [ubports/ubuntu-touch#1381]
### Illustrations

- Device: OPO 1
- Channel: release and stable
- Build: latest

### Steps to reproduce
See https://github.com/ubports/ubuntu-touch/issues/1202

**Comment by nathangiovannini3** [comment]
Hello I verified your problem with the latest development build. It seems to have been solved. I think a resolution will come soon with OTA 12

**Comment by dekkerj1** [comment]
Hi, thanks for your respone. I confirm that the development build is
working on the OPO.

Met vriendelijke groet,
Jaap Dekker.

Op zo 1 mrt. 2020 15:38 schreef nathangiovannini3 <notifications@github.com

**Comment by UniversalSuperBox** [comment]
Hi @dekkerj1,

I'll close this issue because it's a duplicate of #1202 and fixed in `devel`. Thank you for your report!
