### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by SaimonL** [ubports/ubuntu-touch#1385]
Hello I am just reporting what I found. If this could be store in the documentations somewhere it would help a lot of people.
For all devices 90% of the problem with installing Ubuntu touch with ubports can be solved with first fast booting in to TWRP then formatting every thing to ext4 then while in TWRP, boot up ubports app in on the computer and just install ubuntu touch. In OnePlus3T during install it will drop to "Android Recovery" screen with options. The user must ignore it and should not touch anything and let the install finish in that state. after reboot of the phone all will be well.

**Comment by lduboeuf** [comment]
feel free to  improve/ update the documentation as it is open source and submit it to the community

**Comment by ruedigerkupper** [comment]
If you have (safe and reprodicible) installation instructions for a new device (you mention the OP3T) let me know.

**Comment by UniversalSuperBox** [comment]
Thanks for this information @SaimonL. As mentioned, if you'd like to add this to devices.ubuntu-touch.io, you can edit the Oneplus3 and Oneplus3T files (https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/blob/master/devices/oneplus3.md and https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/blob/master/devices/oneplus3t.md).

Do note that it is already being edited and proposed for merge as https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/merge_requests/10, though. It might be good to coordinate your changes with the existing author.

If you have any questions, you can reply here. Thanks again!
