### ISSUE TITLE
Nexus 5 failing to boot after upgrade to 2020-03-10 image

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1395]
- Device: Nexus 5
- Channel: Devel
- Build: 2020-03-10

### Steps to reproduce

1. Upgrade from any (possibly only the last 5, untested as of now) `devel` images on the Nexus 5 to 2020-03-10

### Expected behavior

The device boots

### Actual behavior

The device fails to boot. It appears that the image has many key binaries removed, such as `dpkg` and `lxc-*`.

### Logfiles and additional information

The below excerpt from syslog shows extremely early system services failing to start.

```
Jan 30 13:06:24 ubuntu-phablet kernel: [    3.684340] init: ureadahead-touch main process (623) terminated with status 5
Jan 30 13:06:24 ubuntu-phablet kernel: [    3.830533] init: resolvconf pre-start process (632) terminated with status 1
Jan 30 13:06:24 ubuntu-phablet kernel: [    3.853135] init: resolvconf post-stop process (648) terminated with status 1
Jan 30 13:06:24 ubuntu-phablet kernel: [    3.871557] dwc3 f9200000.dwc3: Avail curr from USB = 1500
[... charging information]
Jan 30 13:06:24 ubuntu-phablet kernel: [    5.240554] init: Failed to spawn lxc-android-config main process: unable to execute: No such file or directory
Jan 30 13:06:24 ubuntu-phablet kernel: [    5.441424] bq24192_set_input_i_limit: input current limit = 1500 setting 0x05
Jan 30 13:06:24 ubuntu-phablet kernel: [    5.497730] init: Failed to spawn click-system-hooks main process: unable to execute: No such file or directory
Jan 30 13:06:24 ubuntu-phablet kernel: [    5.513360] init: dbus pre-start process (777) terminated with status 127
```

Listing the contents of `/usr/bin` reveals a short list, which should be many pages long

```
root@localhost:/# ls /usr/bin/
address-book-app  ciborium     hex2hcd	      rctest
bccmd		  ciborium-ui  l2ping	      rfcomm
bluemoon	  ciptool      l2test	      sdptool
bluetoothctl	  dialer-app   messaging-app  system-settings
btattach	  gatttool     morph-browser  webapp-container
btmgmt		  hciattach    obexctl	      webapp-container-hook
btmon		  hcitool      pasted
```

**Comment by UniversalSuperBox** [comment]
I've deleted the bad update, 1424, from the system-image repository. I have added a file to `/usr/bin` in the system-image with the theory that system-image will not attempt to delete the directory if there is still something in it: https://github.com/ubports/android_device_lge_hammerhead/commit/45571956d0c2c59bf0dc02aa6fc23e9c65fddca7

`daily-hammerhead` is building now on CI and should trigger a new image being created. I will update this ticket when it has finished and I have checked for the issue again.

**Comment by UniversalSuperBox** [comment]
After the build completed, the image `1425` appeared in system-image as expected. Installing this image, even from the previously erroneous upgrade path `1423->1425`, appears to work correctly. I am now testing other upgrade paths to ensure they do not suffer the same issues.

**Comment by Flohack74** [comment]
It remains the question what happened here?

**Comment by UniversalSuperBox** [comment]
The upgrade path `1420->1425` is still experiencing the issue as before.

**Comment by Flohack74** [comment]
Can we remove the deltas and force a full upgrade?

**Comment by UniversalSuperBox** [comment]
By removing the delta from `1423` to `1424`, the problem delta upgrade chain was broken and devices can now update again.

I will attempt to run `ota-push` to ensure that a delta does not get created again.

**Comment by UniversalSuperBox** [comment]
`ota-push` did not recreate the problematic delta update.

@Flohack74, I believe we should push this week's RC image early to ensure the problem does not happen on RC, while we're all awake. Shall we turn off the upgrade notifications, push the image, then turn the notifications on again?

**Comment by UniversalSuperBox** [comment]
Since the immediate issue of upgrades failing has been fixed, this issue can be closed. I'll continue to track the RC push in this issue.

**Comment by UniversalSuperBox** [comment]
The upgrade on RC completed successfully. I have disabled the `ota-push-rc` job. There is an RC update this week, but no one will receive a push notification for it unfortunately.
