### ISSUE TITLE
Cannot trigger multi-touch incrementally (one finger at a time)

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-touch#1397]
Starting from here (https://t.me/ubports_qa_team/27761), where we were discussing closing apps from the app spread:

> myii, [19.12.19 17:21]
> [In reply to Danfro]
> I used to be able to multi-swipe 4 apps (4 fingers) at a time before.  Can't seem to do that any more; multi-touch is hard to trigger these days.
> 
> Danfro, [19.12.19 17:24]
> [In reply to myii]
> I can only manage to swipe off three apps at a time.
> 
> myii, [19.12.19 17:26]
> It still works but at my end, you have to touch all of the apps at the same time.  Whereas before, you could incrementally touch and all would be recognised.
> 
> myii, [19.12.19 17:30]
> Can you place your fingers on the apps one-by-one and then close the apps?  I used to be able to do that before.
> 
> Dalton Durst, [19.12.19 17:30]
> [In reply to myii]
> Up to three
> 
> myii, [19.12.19 17:30]
> OK, but starting with one, can you select other apps with your second and third fingers?
> 
> myii, [19.12.19 17:30]
> I could before, I can't now.
> 
> Dalton Durst, [19.12.19 17:30]
> No, I'm not able to do that.
> 
> Tobiyo Kuujikai, [19.12.19 17:31]
> can confirm
> 
> myii, [19.12.19 17:31]
> Right, that changed from before.  Multi-select was much easier.
> 
> Dalton Durst, [19.12.19 17:31]
> I'm not sure how likely it would to be fixed, but it's worth filing. Thanks for bringing it up!

Another way to test this is with the [Finger Painting](https://open-store.io/app/finger-painting.bhdouglass) app.  You can use up to three fingers at a time but all of the contact points need to be made simultaneously.  If you're off by one, then you'll only have two fingers drawing in the app.

**Comment by mauricioduarte01** [comment]
> This issue seems to be effecting Gearboy as well: https://gitlab.com/bhdouglass/gearboy/-/issues/6
> And it seems to be more of an issue on the current rc/dev than on stable (@cibersheep can confirm).

Confirmed. This was an issue since the good old days from being in the Edge channel. We discussed before but for some reason I've never issued a report.

**Comment by peat-psuwit** [comment]
This seems to be some interaction between Ubuntu.Gesture's TouchRegistry, TouchGestureArea in shell.qml, and TouchGate in SurfaceContainer.qml. For some reason, TouchGestureArea won't ignore the additional touch and thus blocks TouchGate from knowing about it. I don't know how these components are supposed to interact. So, any help on this is appreciated.

**Comment by Bolly** [comment]
Work for me, BQM10FHD on RC.
With five fingers.

**Comment by hendrikscheewel** [comment]
I can confim that it works on Nexus4. Five fingers. Tested with QML Creator. Swiping apps incrementally also works.
