### ISSUE TITLE
Libertine apps (xmir) are distorted when in certain *width*

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1399]
- Device: Nexus 5, OnePlus One (at least)
- Channel: devel, rc

### Steps to reproduce
1 Install a known working desktop app via libertine.
2. Open the app.

### Expected behavior
The app opens properly with UI and layout correctly displayed.

### Actual behavior
The app opens but the UI is distorted.

### Logfiles and additional information

This is basically a copy of https://github.com/ubports/ubuntu-touch/issues/1115, but for width rather than height. Any app width that does not match up with the GPU's tile width will be distorted beyond recognition.

I've been testing mostly on the OnePlus One, which seems to allocate buffers with widths in increments of 128. This is only a problem with Xmir's software rendering, which manually `memcpy()'s` pixels into the buffer. Right now it appears to do it using the destination buffer's width rather than the source's... Stay tuned.

![Broken LXTerminal](https://user-images.githubusercontent.com/21966173/76810243-6177ae00-67bb-11ea-8042-ce146dc163a4.png)

**Comment by UniversalSuperBox** [comment]
Brain dump time.

We begin our journey in [`xmir_sw_copy(struct xmir_screen, struct xmir_window, RegionPtr)`](https://github.com/ubports/xmir/blob/93be1a6efec32c33ed30787aa3462d5d74a7d5c4/hw/xmir/xmir.c#L400-L443). This snippet of code performs some of the most important work within Xmir, taking data from the X server's screen and copying it into the graphics buffer allocated by Mir. If this code doesn't work right, *nothing* will display from Xmir properly. Everything here seems pretty good, except for one value in use that's a little fishy...

```
    dst = region.vaddr + y1*region.stride + x1*bpp;
[...]
        dst += region.stride;
```

A `stride` value in this context represents the number of bytes in a *row* of pixels. We need to know this because memory, to our software, is linear. Where we want a 2 dimensional table of pixels represented as (alpha, red, green, blue), all it sees is a long strand of ones and zeroes. The `stride` value tells the software "go this many bits in a row, then go to the next row and begin at the first column". In this case, we have four bytes per pixel (ARGB, each component takes up one byte) and 1080 pixels in a row. Therefore, we'd expect the stride to be 4320. However...

```
(gdb) print region.stride
$6 = 4608
```

That doesn't seem right. 4608 bytes would correspond to 1152 pixels, a far cry from 1080. Indeed, Xmir is spitting 1152 pixels out into the buffer then moving on to its next row. Since the application running under Xmir has a correct width of 1080, though, 72 pixels of each row are blank (fully transparent). That's how we end up with transparency in the middle of the app, as shown in the screenshot above! It's also what causes the strange ripple effect throughout the entire image. The "start" of each row is coming 72 pixels into the next row, then 148, then 222...

I traced this back through Mir into buffer creation, into the [mir-android-platform `Buffer::Buffer()` constructor](https://github.com/ubports/mir-android-platform/blob/adc4a1199e38f306c388879c9816ede14b090c73/src/platforms/android/client/buffer.cpp#L34-L34), then got lost. Andreas helped by pointing me to [`IpcOperations::pack_buffer()`](https://github.com/ubports/mir-android-platform/blob/adc4a1199e38f306c388879c9816ede14b090c73/src/platforms/android/server/ipc_operations.cpp#L36), which dispatches the information about a buffer to an application which is receiving a new one, then to [`GraphicBufferAllocator::alloc_software_buffer()`](https://github.com/ubports/mir-android-platform/blob/adc4a1199e38f306c388879c9816ede14b090c73/src/platforms/android/server/graphic_buffer_allocator.cpp#L121), which creates the buffer to send. Stepping deeper, we found the exact point where we transition from `glibc` code and move into Android, inside [`GrallocModule::alloc_buffer()`](https://github.com/ubports/mir-android-platform/blob/814875e673b55e345b4d92cea7ae39e6d453a4c9/src/platforms/android/server/gralloc_module.cpp#L70-L71).

After a couple (read: six hours) of red herrings involving impossible mathematics and possible bit flips caused by transitioning the Libhybris border from [the default `gralloc_alloc()`](https://github.com/ubports/android_hardware_libhardware/blob/ubp-5.1/modules/gralloc/gralloc.cpp#L199) in the Android side, we realized we were actually looking at the wrong gralloc... [Qualcomm provides their own](https://github.com/ubports/android_hardware_qcom_display/blob/ubp-5.1-caf-8974/libgralloc/gpu.cpp#L344). It jumps over to [`alloc_impl()`](https://github.com/ubports/android_hardware_qcom_display/blob/ubp-5.1-caf-8974/libgralloc/gpu.cpp#L257), which does a neat little call to [`getBufferSizeAndDimensions()`](https://github.com/CyanogenMod/android_hardware_qcom_display/blob/d7dc8cdb1201962f93d4f6fb4371ed0083cf1f5d/msm8974/libgralloc/alloc_controller.cpp#L273). That, finally, calls to [`AdrenoMemInfo::getStride()`](https://github.com/CyanogenMod/android_hardware_qcom_display/blob/d7dc8cdb1201962f93d4f6fb4371ed0083cf1f5d/msm8974/libgralloc/alloc_controller.cpp#L103) where we make our discovery...

It's working perfectly as designed. We are always receiving a buffer stride that is a multiple of 32, but larger than our requested width. This allows the GPU to perform ["tiled rendering"](https://en.wikipedia.org/wiki/Tiled_rendering), or splitting the big body of work (the entire application's surface) into manageable chunks (32x32 squares). Turns out, both the Qualcomm Adreno and Mali400 GPUs used in the known affected devices do this.

So, at this point, I've written 708 words and spent 14 hours debugging to tell you... that everything lower than Xmir is working as expected. However, knowing things are working properly is just as important as knowing they aren't...

All the way back up to Xmir, then. Given the information we know so far, it's obviously wrong to use the stride value returned by Android. We end up splatting pixels over rows and causing a huge mess. What's the correct way to solve that, then? Using the source stride value rather than the destination? What do we do while resizing the window, when the source and destination will be radically different? How much effort do we put in before stopping, knowing that Xmir is a dead platform and Xwayland is the future?

That's all to be determined.

**Comment by APokorny** [comment]
So a solution would be to detect adreno and probably mali gpus in the android platform. Then at the very same place in which we already have the vegeta quirk that realigns the width of buffer allocations we should add a quirk call to make the width and height of the allocation call multiplies of 32. 

So the quirk shall only apply to software buffer allocations, shall only affect the call to gralloc, shall not change width and height of the android native buffer, shall not change the width and height mir server or mir client sees.

**Comment by nanu-c** [comment]
This is the same error as on raspberry 4 with the tilling? Looks nearly the same but way more distorted

**Comment by prog66** [comment]
Hi for my oneplus one is not good.. Xmir is  distorted again ...

**Comment by UniversalSuperBox** [comment]
@prog66, the change (https://github.com/ubports/mir/pull/27) has not yet been merged. It is expected that this issue would still occur without the PPA installed.

**Comment by abkro** [comment]
N5 running RC. 
Looks normal to me. Tested with Lxterminal.

**Comment by cibersheep** [comment]
M10HD RC, app looks good resizing main window in desktop mode
