### ISSUE TITLE
Camera app BQ-M10 frieza not working

### ISSUE THREAD

**Issue by dekkerj1** [ubports/ubuntu-touch#1400]
### Illustrations

- Device: BQ-M10
- Channel: Release candidate
- Build: Version 67

### Steps to reproduce
Camera app opens but shows black screen. Reinstalled the app (3.1.2). After reboot still the same problem.

### Expected behavior
Ready to take pictures and videos after opening the camera app.

### Actual behavior
Just a black screen, no image, no buttons.

**Comment by hankschwie** [comment]
Could you try to check the camera function using the factory mode? You can reach it pressing the power and volume down button on the device for about 10 sec. You'll find a menu with different options, choose Item check an test the camera. I had a similar issue with a bq aquaris HD M10 (cooler). Now it works as expected

**Comment by dekkerj1** [comment]
Thanks for your advice. I switched back to stable and the camera(app) was working as expected. Switched back to release candidate and camera(app) still works. So I will close the issue.
