### ISSUE TITLE
Camera is blank when opening camera app from lock screen

### ISSUE THREAD

**Issue by mr-growl** [ubports/ubuntu-touch#1403]
Phone: Nexus 5 (hammerhead)
Build: Ubuntu 16.04 (2020-W10)

PREREQUISITES:  
-have a pin set so the screen locks when you press the power button 
-have the camera app pinned to the favorites/app/whateveritscalled bar on the left so that you will be able to see it while the screen is locked

TO REPRODUCE:

1. Make sure the camera app is closed (and anything else that might be using the camera)
2. Press the power button momentarily (so the screen powers off)
3. Press the power button again (so the screen powers on)
4. swipe from the left to open the favorites bar 
5. tap the camera app icon
6. enter your pin

EXPECTED RESULT
the camera app is opened and the image from one of the cameras is shown

ACTUAL RESULT
the camera app is opened but there is no camera image

WORKAROUND
tap the icon which switches between the front and back cameras.  At this point both cameras work as expected.

**Comment by mr-growl** [comment]
i tried this agaim with 2020-W13 and it seems like it is fixed! So if no one else sees this problem this could be closed. Thanks!

**Comment by thilovv** [comment]
This bug is fixed on my OnePlus 3t.

**Comment by Bolly** [comment]
Checked this on an BQM10FHD running RC 2020 W-14.
It doesn't work. 
A password is required for the test.

**Comment by thilovv** [comment]
This bug is now also fixed on my BQ E5 (rc) and the BQ M10 (dev)

**Comment by Bolly** [comment]
Checked this on an BQM10FHD running RC 2020 W-15.
It works
