### ISSUE TITLE
Feature Request Wifi toggle ON/OFF

### ISSUE THREAD

**Issue by FPfabi** [ubports/ubuntu-touch#1405]
#Description of the feature#
Similiar to cellular data ON/OFF toggle, there should be a Wifi ON/OFF toggle in the drop-down menu
Could not find this option in my phone:
- Device: FP2
- Channel: Ubuntu Touch 16.04/stable (OTA-11)

### Steps to reproduce
Swipe from the top of the screen to show dropdown menu.

### Expected behavior
Below Flight-Mode and Cellular Data, there should be an ON/OFF toggle for Wifi.

**Comment by UniversalSuperBox** [comment]
Hi @FPfabi,

It appears you are affected by https://github.com/ubports/ubuntu-touch/issues/168. You can normally fix this issue by rebooting your device.

**Comment by UniversalSuperBox** [comment]
Hi @FPfabi,

Since we have not had anyone else confirming this issue and no response here, I'm assuming that it's been fixed. I'll close this report. Please let me know if this is in error.
