### ISSUE TITLE
File Manager Authentication

### ISSUE THREAD

**Issue by dtarrant2019** [ubports/ubuntu-touch#1406]
<!File Manager authentication dialogue is now missing (Nexus 4 and BQ M10, both running devel 469). Same for Terminal. What is intention for the future?
(See recent discussion in Support channel.)--------------------------------------------------------------------------
--------------------------------------------------------------------------------

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

- Device: Nexus 4 and BQ M10
- Channel: devel
- Build: 469 onwards

- Steps to reproduce
Launch File Manager

- Expected behavior
Authentication dialogue should be presented

- Actual behavior
No Authentication Dialogue appears and File Manager is already unlocked

**Comment by myii** [comment]
Also affects the Nexus 5 `hammerhead`.

**Comment by peat-psuwit** [comment]
This (merge) commit changes the meaning of the DBus property these apps rely on to see if the device has a password.

https://github.com/ubports/unity8/commit/6d9907ef7fdbf470f3331b0feade1656f34089a2

**Comment by dtarrant2019** [comment]
> This (merge) commit changes the meaning of the DBus property these apps rely on to see if the device has a password.
> 
> [ubports/unity8@6d9907e](https://github.com/ubports/unity8/commit/6d9907ef7fdbf470f3331b0feade1656f34089a2)

dobey said "Yes. It is a bug resulting from the new Mir/Unity8 builds. Though I am not sure where exactly the issue is."

**Comment by Flohack74** [comment]
@peat-psuwit so do I see this correctly, we would just need to reverse the logic in the App and the prompt would be there again?

**Comment by peat-psuwit** [comment]
@Flohack74 No, this requires a fix in Unity8. The way it's changed is that it always returns `false` whenever the screen is unlocked. I'm going to make a PR soon.

**Comment by thilovv** [comment]
This bug affected the OnePlus 3t as well, and is now fixed.

**Comment by dtarrant2019** [comment]
Fixed on M10 :)
