### ISSUE TITLE
Libertine: some application fails with SIGSEGV at launch

### ISSUE THREAD

**Issue by peat-psuwit** [ubports/ubuntu-touch#1407]
- Device: bq Aquaris M10 FHD
- Channel: devel
- Build: apt up-to-date as of 24 March 2020 16:01 UTC (which includes ubports/mir#27)

### Steps to reproduce

1. Create (or reuse) a chroot-based xenial libertine container.
2. Install `pavucontrol` or `mousepad`. Restart `unity8` if it doesn't appear in the drawer after install.
3. Launch the application from the drawer.

### Expected behavior

Application launches successfully.

### Actual behavior

The splash appears for a couple of seconds, then disappears. The log suggests that the app gets a SIGSEGV.

### Logfiles and additional information

`~/.cache/upstart/application-legacy-default_pavucontrol_0.0-.log` have the following content:

```
** (pavucontrol:7233): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
proot info: vpid 1: terminated with signal 11
```

This is very similar to #701. I've tried building the latest version of proot from https://github.com/termux/proot, but the problem isn't fixed.

The problem seems to happen only if the app is launched using the drawer/ual. I can start the app successfully by running Xmir manually and uses libertine-launch to launch the app in another terminal.

Also, if I launched another application that doesn't crash (such as LXterminal) and then launch `pavucontrol`, the app seems to work properly (except that it won't open another window, which is fixed by ubports/libertine#77).

**Comment by cibersheep** [comment]
Tested on lastest RC, M10HD. Pavucontrol doesn't start

![imatge](https://user-images.githubusercontent.com/6640041/77942320-bb986900-72bb-11ea-998a-8323e5fe919e.png)

**Comment by peat-psuwit** [comment]
Well, the fix hasn't landed on RC yet. Please wait until the next RC, on Wednesday IIRC.

**Comment by cibersheep** [comment]
Oh, I see. Sorry about that

**Comment by Flohack74** [comment]
Which is today @cibersheep ^^

**Comment by cibersheep** [comment]
Yay! Tested and it works! :) I see pavucontrol on M10HD
