### ISSUE TITLE
mms is lost if any error occured

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1408]
### Illustrations

- Device:N5
- Channel:devel
- Build:last

### Steps to reproduce

I'm sometimes unable to receive  mms

### Expected behavior

mms is received, or at least a notification if any pb

### Actual behavior

mms not received, lost

### Logfiles and additional information

It appears to be when something wrong with authentication :
in dbus.log , got a ContentAccessDenied from the file_download.cpp file 

Note that i'm using french ISP free, and i don't activate data by default

**Comment by sergiusens** [comment]
After being disonnected from nuntium for some time I think I am willing to work on forwarding a message through telepathy to the messaging-app to get it to render a retry. I think that is how most UXes would work. I don't think that randomly having nuntium _cron_ a retry would be the best UX experience.

Who can I work with to move forward with this on the UX and messaging app side?

**Comment by lduboeuf** [comment]
Awesome @sergiusens 
I agree, a cron will going to be harder to handle and not UX clean. For the messaging-app part i can give a try as i did some recent work on it.
You can ping me on TG with the same handle as in github
@UniversalSuperBox other ideas or developer available for that ?

**Comment by Flohack74** [comment]
No, Lionel, if you can handle it from a coordination/review/unblocking perspective this would be great. If there are any CI issues relay to me plz.

**Comment by lduboeuf** [comment]
@cybersheep do you have UX UI suggestion

**Comment by mateosalta** [comment]
does it send an error or fail silently?

**Comment by lduboeuf** [comment]
it fails silently for instance

**Comment by mateosalta** [comment]
if data is off then is there any way to retrieve these missed messages?

**Comment by lduboeuf** [comment]
Yes on every other OS ( i think ), a message ( sms like ) is displayed with a link to download and an info to activate data

**Comment by lduboeuf** [comment]
So i managed as a workaround to just display a sms when something went wrong so that users get notified if someone try to send a mms. I had success but wonder where translation need to occur? The logic is at lower level, and not translatable. So it seems that i need to translate on messaging app and for the notification

**Comment by mateosalta** [comment]
I bet you would have to let the app know in some way - like a signal or something? send error message x > then inside the app:  if recieves "error message x" ( show translated string "message in language translated" - hope that makes sense?

that sounds better than receiving nothing.
- maybe some wording on the message [ (retry circle) Download mms - Requires data connection] once downloading a retry can be done. 

maybe until then, for the error something like [Error Recieving mms - Requires data connection] (possible suggest strength of connection? Requires strong data signal)

**Comment by lduboeuf** [comment]
Yes can't we share translations between components ? I mean, for my special case, i would flag the message with a "error something", store it like that in history-service, and then translate it in messaging-app when displayed, but need also to do it for the notifications in a different component.

**Comment by lduboeuf** [comment]
follow-up for a "quick first step" solution:  https://forums.ubports.com/topic/5100/the-mms-lost-story/26

**Comment by rik-shaw** [comment]
As of devel channel 2021-12-17 I will get "oops" error messages with download link if wifi is enabled when mms is received but cant be downloaded, and if cellular data is off I will get a different notification that there is a new MMS message with the download link.

So I would mark this one "resolved" even though there could theoretically be other use cases depending on the user's provider and network.
