### ISSUE TITLE
SDL apps broken on some devices at least, or in certain weird situations

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#1409]
- Device: arale (Meizu MX4)
- Channel: devel
- Build: 487 (2020-02-27)

### Steps to reproduce
Hi,
I've been trying to run this SDL demo app by zub on my device:
https://gitlab.com/zub2/SDLDemo

and have found out it is no longer working on my phone as of today. 

It also seems based on a comment on the forum that on some devices this has been broken for at least a while longer: https://forums.ubports.com/post/27969

Here is an old build that I am 100% positive worked yesterday but does not work today:
https://iubuntu.cz/apps/zub.sdldemo_0.2_armhf.click

So, to reproduce this, just launch the app and it will immediately crash on startup with the following error:
```
Using SDL version: 2.0.4
Using resource path root: "/opt/click.ubuntu.com/zub.sdldemo/0.2/media"
shm_open() failed: Permission denied
```

and this in the respective upstart log:
```
terminate called after throwing an instance of 'SDL2pp::Exception'
  what():  SDL_Init failed: No available video device
```

### Expected behavior
The app launches and runs.

### Actual behavior
The app crashes on startup.

It is possible the app is doing something else than other apps using SDL but don't know of any other to test this.

So the main question is, what has changed on devel today that broke this?
Thank you.

**Comment by zubozrout** [comment]
Actually, this seems to be a weird issue caused by installing a more recent SDL version based app (SDL 2.0.9) on top of an older SDL app (2.0.4). The 2.0.9 version won't run but when uninstalled and the older app installed again the 2.0.4 app won't launch either. Not even reboot helps, but surprisingly a system image update fixed this for me.

However, I won't be closing this issue just yet as it seems (based on the forum link in the above bug description) some other devices are affected by the original report anyway.

**Comment by UniversalSuperBox** [comment]
@zubozrout, I'm unable to compile SDLDemo locally. Could you please provide an example of both clicks you need, the one that works initially *and* the one that breaks everything? Additionally, could you find another app that exhibits the same symptoms?

**Comment by zubozrout** [comment]
Hi @UniversalSuperBox, thank you for the reply. I am for some reason unable to compile it as well though apparently that works on Debian. Anyway, here is the newer SDL version compiled app:
https://iubuntu.cz/apps/zub.sdldemo_0.3_armhf.click

As for other apps I don't know of any. The other one mentioned on the forum linked in the description of this ticket is based on the same demo. And there were apps like Extreme Tux Racer, Neverball and Neverputt ages ago but I am unable to find there anywhere unfortunately :(. Albeit Extreme Tux Racer was in the OpenStore at one point but since it was not updated from Vivid it got lost despite Vivid package working on Xenial just fine. Perhaps it is still somewhere on the OpenStore servers though?. If it is then I would love to get my hands on that package too :).

Nevertheless, the main question is probably whether the older SDL app linked in the description can be launched on all devices as based on the forum it doesn't seem to be the case. If you could please test it that would be great.

Thank you very much :).

**Comment by UniversalSuperBox** [comment]
No, neither click you've linked starts correctly on the newest devel image on the Nexus 5, OnePlus One.

I used Cube Chron from the OpenStore to test an older RC image (March 4th) to confirm your report of it working correctly before. On the RC image, Lomiri crashes immediately while the Cube Chron app makes a sound. On a new devel image, the app closes immediately without making a sound. Attempting to start it a second time causes Lomiri to crash.

**Comment by UniversalSuperBox** [comment]
Unfortunately, the Cube Chron app has no source available. I suspect that the app would work if it was built with a newer version of SDL. However, I'm unable to test this and I am unable to build the SDLDemo app.

**Comment by UniversalSuperBox** [comment]
As mentioned in the SDLDemo app's README, it's possible that both it and other apps experiencing this problem should upgrade to a newer version of SDL. Mir's APIs were not stable between 0.24 (present in Stable) and 1.2 (which we're using now)

**Comment by zubozrout** [comment]
@UniversalSuperBox Well, please note that app is based on the same SDL stuff as the demo I've shared click packages of: https://forums.ubports.com/topic/2178/c-and-sdl-with-clickable-a-little-help-please/23?_=1585602037833

So I am not sure it is the best reference point. However, since the SDL app can be launched on some devices and won't run on others that seems to be an issue which I do not understand.

If you wish to build the SDL demo yourself, you can try this branch & commit as it has the clickable config fixed for the latest version and it is still the revision made prior an attempt to use latest Mir supported SDL: https://gitlab.com/zub2/SDLDemo/-/commit/a526758bf3805747219e857eb99ded939ae7472c

**Comment by zubozrout** [comment]
As for using SDL 1.2+, there is no longer support for Mir there so it would have to run as a Wayland app. The last time I tried that I was not lucky at all: https://forums.ubports.com/topic/3003/running-wayland-apps-on-edge

I've compiled it but it didn't run. Then it turned out I was not even able to run that on my computer (which Rodney suggested as a good starting point). Apparently it needs skills of someone more capable than me.

**Comment by zubozrout** [comment]
Also, upgrading SDL means Wayland. And there I was not lucky at all :'(
https://forums.ubports.com/topic/3003/running-wayland-apps-on-edge

Not even on desktop as Rodney suggested me to try so it may need someone more capable as the app was not able ta launch for some reason.

**Comment by UniversalSuperBox** [comment]
The README of SDLDemo implies that SDL 2.0.5 had Mir support but not Mir 0.24 support. Does that version work?

**Comment by Danfro** [comment]
@zubozrout  I am just right now sending you the Tuxracer click via Telegram. Upload here is not possible due to file size.

It does still work on current devices. I did get that of Brian the other day to put it on my new phone for the kids to spend corona - times. ;-)

**Comment by UniversalSuperBox** [comment]
@zubozrout, https://github.com/ubports/mir/pull/28 mostly fixes the start of the Cube Chron app in the store. It's the only app I'm particularly concerned about fixing for now because the SDLDemo app appears to have its own bugs that probably stem from the update to a newer version of SDL.

In particular, if SDL is allowed to perform `static int MIR_Available()` in `src/video/mir/SDL_mirvideo.c`, Lomiri thinks the app has crashed after the availability check ends.

Then the demo app tries to get a new window for its actual drawing. This succeeds. However, the app never draws any video frames. Because of this, the new window can't be displayed. This can also be tested by replacing the contents of `static int MIR_Available()` with `return true`.

I believe these are related to the SDLDemo app itself, not Mir or Lomiri.

**Comment by myii** [comment]
Might be another step towards getting KOReader working again:

* https://github.com/koreader/koreader/issues/4361
* https://github.com/koreader/koreader/pull/4946
* https://github.com/koreader/koreader/issues/4960

Will https://github.com/ubports/mir/pull/28 be available in tomorrow's `devel`?

**Comment by Flohack74** [comment]
@myii yes this should be in todays devel...

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/qtmir/pull/49 and https://github.com/ubports/mir/pull/28

**Comment by myii** [comment]
Cube Chron crashes the Lomiri session with the latest `devel` on my N5 (`2020-04-09/2`).  Maybe tomorrow's update will fix this?

**Comment by UniversalSuperBox** [comment]
See https://github.com/ubports/ubuntu-touch/issues/1417

**Comment by myii** [comment]
Working now, thanks.
