### ISSUE TITLE
Unity8 crash when touching opened menu in LibreOffice

### ISSUE THREAD

**Issue by peat-psuwit** [ubports/ubuntu-touch#1412]
- Device: bq Aquaris M10 FHD
- Channel: devel
- Build: APT-updated as of 2 April 2020

### Steps to reproduce

1. Create a Libertine container if not exists. Install LibreOffice inside it.
2. Launch LibreOffice Writer. If the new entries don't appear, restart Unity8.
3. **Use a finger,** touch File > Close.

### Expected behavior

Unity8 stays running. LibreOffice should be closed, but I'll leave it outside the scope of this bug.

### Actual behavior

Unity8 crash with the following error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
()
```

**Comment by dobey** [comment]
Is this with or without `-flatten` option for xmir?

**Comment by peat-psuwit** [comment]
> Is this with or without `-flatten` option for xmir?

Without `-flatten`.

**Comment by dobey** [comment]
I'm guessing this is caused by unity8 trying to reference the menu's window still after it has disappeared, and this will not happen with `-flatten` enabled.

**Comment by peat-psuwit** [comment]
Turns out the `-flatten` removal creates a more severe problem elsewhere. So, we decided to re-introduce `-flatten`, which makes this issue obsolete.

**Comment by UniversalSuperBox** [comment]
Should this issue be moved somewhere more appropriate or closed entirely?
