### ISSUE TITLE
Press the "Super" key twice does not hide the launcher

### ISSUE THREAD

**Issue by peat-psuwit** [ubports/ubuntu-touch#1425]
- Device: M10 FHD
- Channel: Devel
- Build: APT up-to-date as of 2020-04-16

### Steps to reproduce
1. Connect a keyboard to the tablet.
2. With the tablet unlocked, press the "Super" key (maybe called Windows™ key or Command key). The drawer will be opened.
3. Press the Super key again.

### Expected behavior
The drawer and the launcher are closed together.

### Actual behavior
Only the drawer is closed. The launcher stays visible.

### Logfiles and additional information

Video of reproduction: https://t.me/ubports_devel/4895

**Comment by josevidalrt** [comment]
Device: Bq E4.5 krillin
Channel: rc
Build: 2020-w16
**Steps to reproduce**
1. Connect a keyboard to the phone.
2. With the phone unlocked, press the "Super" key (maybe called Windows™ key or Command key). The drawer and the launcher are open.
3. Press the Super key again.

**Actual behavior**
Only the drawer is closed. The launcher stays visible.

**Notes**
1. Pressing the super key again closes the launcher for a moment and immediately reopens it together with the drawer. 
2. Pressing the esc key closes both the drawer and the launcher.

**Comment by toehold** [comment]
Same behaviour on Nexus 5, 2020-W16 both using an external Keyboard and without.

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-16.
It doesn't work
Checked this on a BQM10FHD running RC 2020 W-17.
It works.
