### ISSUE TITLE
Closing flip cover switches off screen

### ISSUE THREAD

**Issue by abkro** [ubports/ubuntu-touch#1428]
### Description of the feature

Flip covers for phones are common and on other systems (Android, iOS) closing the flip cover locks/turns off the screen. This does not happen with UT. 

With UT you have to perform two operations to obtain the same result:
1. Hit power button to lock screen
2. Close flip cover.

I suggest implementing the same functionality in UT, i.e. closing flip cover causes screen to switch off and lock itself.

Ideally the user should be able to choose between two modes:

A. 
Closing flip cover causes both screen to switch off and lock.

B. 
This causes the screen to turn off without locking before the preselected time interval. It should then illuminate by itself without requiring a passcode if the cover is reopened before the preset locking time interval.

Mode B would save power, while being more convenient in situations where the user frequently inspects the phone.

**Comment by abkro** [comment]
Edit: 

Actually, both modes (A and B) should include automatic illumination of the screen upon reopening the flip cover, the difference being that in mode A you would have to enter the passcode because the screen would be locked.

**Comment by UniversalSuperBox** [comment]
@abkro, I believe this is now in Ubuntu Touch since the merge of https://github.com/ubports/repowerd/pull/8. This fix should be in the `rc` or `devel` channels now, releasing in OTA-13.

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-33.
It doesn't work

**Comment by UniversalSuperBox** [comment]
@Bolly, do you know if it is possible to have the device go to sleep when a flip cover closes on it in Android? If it doesn't have the hardware for this, this software fix won't help.

**Comment by Bolly** [comment]
oooh, sorry.
I thinked we were using the proximity sensor.

**Comment by duckunix** [comment]
Testing on an ASUS Nexus 7 (2013) Wi-Fi [flo], OS build Number 2020-W35/2, UBports image part 20200827-287, Device Image part 20181229-30682.

Closing the cover does in fact turn off the screen and lock the device.

**Comment by Flohack74** [comment]
@Bolly No, the proximity sensor would be very inconclusive, the screen would constantly lock if you just accidentially come too close, even with your hand to touch the screen maybe. Proximity is only used in calls.
Those devices must have kinda Hall sensor or so that tells them the cover is closed.

**Comment by abkro** [comment]
Tested on Nexus 5 running RC (2020-W35/2). Does not work.

**Comment by duckunix** [comment]
So, after seeing @abkro update, I tested.  My Nexus 7 works only when a magnet is close to the screen.  The case I use has magnets.  Proximity sensor does nothing.

**Comment by abkro** [comment]
I have tested now on my bq E4.5 also which has a flip cover, but this cover, like the one on my N5, does not have a magnet and it does not switch off/lock the screen. But I suppose that was to be expected if the magnet is what triggers it.
