### ISSUE TITLE
No favorite contacts tab

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1429]
Dear all,

Favorite contacts tab from contact app is OK. But that favorite tab is not available from phone app. Only complete list. 
I noticed that on mako, OTA 11.
Best.

**Comment by lduboeuf** [comment]
WIP here https://github.com/ubports/dialer-app/pull/117

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/dialer-app/pull/117
