### ISSUE TITLE
App drawer is empty and device (usually) recovers upon reboot

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-touch#1437]
- Device: `hammerhead` (but also reported on other devices)
- Channel: `devel` (but also reported on `rc`)
- Build: 2020-04-17, recurred 2020-05-01

### Steps to reproduce

Installed the update and after restarting, bug was present when I opened the app drawer.

Here are the relevant conversations from Telegram.

---

https://t.me/ubports_qa_team/33346

> myii, [17.04.20 21:08]
> ![photo_2020-05-05_15-34-04](https://user-images.githubusercontent.com/10231489/81078332-02dece80-8ee6-11ea-990e-5a833fe8bd69.jpg)
> ^ What's going on here?  Nothing's showing up and the blue progress bar is moving from side to side.
> 
> Joan CiberSheep, [17.04.20 21:09]
> [In reply to myii]
> ¿Pull to refresh?
> 
> myii, [17.04.20 21:09]
> [In reply to Joan CiberSheep]
> No, nothing.  Shows the "Release to refresh..." message but still not finding anything...
> 
> myii, [17.04.20 21:10]
> Search doesn't work, either.
> 
> Joan CiberSheep, [17.04.20 21:11]
> [In reply to myii]
> Sorry, I ment that might be Pull to Refresh (it was added recently) stuck there. That's why the progress bar
> 
> myii, [17.04.20 21:18]
> [ GIF ]
> 
> myii, [17.04.20 22:00]
> At least I had Launcher Modular available in my launcher...

---

https://t.me/ubports_qa_team/33402

> Florian Leeber, [19.04.20 18:52]
> Can anyone confirm an empty app drawer with todays devel?
> 
> Dalton Durst, [19.04.20 19:00]
> the question, specifically, was if the Drawer was empty.
> 
> Florian Leeber, [19.04.20 19:14]
> After reboot its fixed, bu strange
> 
> Florian Leeber, [19.04.20 19:14]
> I never had this ever
> 
> myii, [19.04.20 20:32]
> [In reply to Florian Leeber]
> I had it in devel a day or two ago: https://t.me/ubports_qa_team/33354.

---

https://t.me/ubports_qa_team/33855

> myii, [01.05.20 12:11]
> Got this again on the latest update on my N5 devel (2020-05-01 — 1509).
> 
> myii, [01.05.20 12:11]
> [Forwarded from myii]
> [ GIF ]
> 
> Matteo, [01.05.20 12:28]
> [In reply to myii]
> I got the same behavior on the pro5
> 
> myii, [01.05.20 12:29]
> [In reply to Matteo]
> Updated today?
> 
> Matteo, [01.05.20 12:29]
> On RC though
> 
> Matteo, [01.05.20 12:30]
> And I couldn't do anything other than rebooting the phone
> 
> myii, [01.05.20 12:30]
> [In reply to Matteo]
> A workaround is to use Launcher Modular as an app.
> 
> myii, [01.05.20 12:30]
> [In reply to Matteo]
> And did it start working again? It doesn't at my end.
> 
> Matteo, [01.05.20 12:31]
> [In reply to myii]
> Didn't know that, thanks for the tip
> 
> Matteo, [01.05.20 12:31]
> [In reply to myii]
> Yes, apparently it seems it is a random behavior
> 
> myii, [01.05.20 12:32]
> [In reply to Matteo]
> You should still be able to access the OpenStore from the launcher.
> 
> Matteo, [01.05.20 12:35]
> [In reply to myii]
> Yes ok, but having the drawer empty is an issue we should really avoid to occur anyways, since the UT UI is now investing in this, after removal of scopes
> 
> myii, [01.05.20 12:40]
> [In reply to Matteo]
> Sure, that's the idea by sharing it here. I wonder if there's a better place to share it...
> 
> Johannes Renkl, [01.05.20 12:59]
> create an issue if there is none yet. But posting here is a good thing also i'd say

---

https://t.me/ubports_devel/5932

> Ratchanan Srirattanamet, [05.05.20 09:55]
> @​imraniqbal, have you ever seen the problem with pull-to-refresh drawer again?
> 
> myii, [05.05.20 11:00]
> [In reply to Ratchanan Srirattanamet]
> It first happened around mid-April and then at the end, so maybe we can expect it again after another 15 days have passed(!).  Joking aside, I personally haven't seen it again but it might be worth tapping into the wider community since others have also come across this.  You might find someone who has it now — the last person I spoke to was on rc, so they may have faced it for a number of days...
> 
> Ratchanan Srirattanamet, [05.05.20 13:28]
> @​UniversalSuperBox @​mariogrip Should we delay the OTA due to this?
> 
> Dalton Durst, [05.05.20 13:29]
> It is quite a problem, but it's also infrequent and solved by a reboot. What do you think?
> 
> Ratchanan Srirattanamet, [05.05.20 13:36]
> I think we can delay OTA-12 for 1 more week. My current plan is to try to investigate this issue by Friday. If the problem can't be root-caused, I'll revert my pull-to-refresh PR and let that day's devel be the RC.
> 
> Dalton Durst, [05.05.20 13:47]
> So you have at least been able to reproduce it reliably?
> 
> Dalton Durst, [05.05.20 13:52]
> This is completely experience-breaking, and could happen to anyone, but only occasionally.
> 
> myii, [05.05.20 13:56]
> [In reply to Dalton Durst]
> I hope it can be solved by a reboot. The first time I encountered it, nothing made a difference until the next day's devel.
> 
> Dalton Durst, [05.05.20 13:59]
> Okay. @​Flohack, I'm withdrawing the QA and Development SC consent to release OTA-12 tomorrow.
> 
> Florian Leeber, [05.05.20 14:16]
> [In reply to Dalton Durst]
> Ok what happened
> 
> Dalton Durst, [05.05.20 14:17]
> The Drawer can be stuck in loading with no apps available, and this may or may not be solved by a reboot
> 
> Florian Leeber, [05.05.20 14:18]
> Plz create an issue for the board so I can point to it

### Expected behavior

All apps displayed.

### Actual behavior

No apps displayed, with the blue progress bar is moving from side to side at the bottom of the drawer (see attached GIF).

**Comment by Bolly** [comment]
It's happened to me more than once, I don't remember RC.
BQM10FHD.
Do you need a log?

**Comment by peat-psuwit** [comment]
@Bolly The log in the current build isn't very helpful. So, not now. But I'm preparing a debug build which should reveal more about the issue. So, please stay tuned. :D

**Comment by peat-psuwit** [comment]
I need help to reproduce this problem. For anyone that ever experienced this issue, please install the debug build of Unity8 using the command below. After that, when the issue manifests again, please attach the Unity8 log file, `~/.cache/upstart/unity8.log`.

```sh
sudo mount -o remount,rw /
cd `mktemp -d`
wget \
    https://ci.ubports.com/job/ubports/job/unity8/job/PR-310/2/artifact/unity8-common_8.20+ubports+0~20200505160356.2~1.gbp9cbc01_all.deb \
    https://ci.ubports.com/job/ubports/job/unity8/job/PR-310/2/artifact/unity8-private_8.20+ubports+0~20200505160356.2~1.gbp9cbc01_armhf.deb \
    https://ci.ubports.com/job/ubports/job/unity8/job/PR-310/2/artifact/unity8-schemas_8.20+ubports+0~20200505160356.2~1.gbp9cbc01_all.deb \
    https://ci.ubports.com/job/ubports/job/unity8/job/PR-310/2/artifact/unity8_8.20+ubports+0~20200505160356.2~1.gbp9cbc01_armhf.deb
sudo dpkg -i *.deb
rm *.deb
initctl restart unity8 # Or, if failed, restart the phone.
```

**Comment by peat-psuwit** [comment]
@Bolly Here you are. Please.

**Comment by dtarrant2019** [comment]
Not experienced this issue with my BQ M10 HD. All has been working fine yesterday and today.

**Comment by dtarrant2019** [comment]
Not experienced this issue with my Nexus 4. All has been working fine yesterday and today.

**Comment by giiba** [comment]
I saw this once after the last rc update. I rebooted and all was fine. Hasn't happened since.

**Comment by vicseq** [comment]
I did experience this on RC on bacon a couple days ago. After reboot it become fine again.

**Comment by prog66** [comment]
Hello for me on my oneplus one has no problems at this level I am in edge last updates so the 05/06/2020

**Comment by lduboeuf** [comment]
happened just today after a cold boot, N5 devel. Unfortunatly haven't installed @peat-psuwit packages. Will try

**Comment by myii** [comment]
> happened just today after a cold boot, N5 devel. Unfortunatly haven't installed @peat-psuwit packages. Will try

@lduboeuf Try to avoid restarting the device!

**Comment by lduboeuf** [comment]
unity8.logs: https://paste.ubuntu.com/p/rHgPb3n8Zh/
dmesg: https://paste.ubuntu.com/p/P4tmtqVf79/

anything else needed ?

**Comment by myii** [comment]
@lduboeuf You _might_ want to post those directly to @peat-psuwit on Telegram, since there _may_ be sensitive data there.

**Comment by peat-psuwit** [comment]
I've managed to reproduce the issue on my end and is now working on the fix. Thank you for everyone trying to reproduce this.
