### ISSUE TITLE
Cannot change brightness, autobrightness is not available

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1446]
- Device: Nexus 5 (hammerhead)
- Channel: edge
- Build: 2020-05-11/2

### Steps to reproduce

1. Boot the device
1. Get blinded
1. Oh no oh no I gotta turn down the brightness
1. Open the Battery indicator and turn down the brightness (or, alternatively, go to Settings -> Brightness & Display)

### Expected behavior

I am no longer being blinded

### Actual behavior

Nothing changes, I am still being blinded.

It should also be noted that auto-brightness is not available in the Battery indicator or Brightness & Display settings.

### Logfiles and additional information

It seems likely that this is related to repowerd, here is its log file: https://paste.ubuntu.com/p/354WVhB48T/

**Comment by Flohack74** [comment]
Interestingly the same happens on the Halium 7.1 port: We are not able to get autobrightness working...

**Comment by UniversalSuperBox** [comment]
https://github.com/ubports/ubuntu-touch/issues/1493 supersedes this since it is in devel
