### ISSUE TITLE
Resume takes long on busy applications

### ISSUE THREAD

**Issue by LiohMoeller** [ubports/ubuntu-touch#1447]
On Unity 8, resuming of some applications takes quite long (2-3 seconds). Examples are uMastonauts, teleport, morph etc.

Reproduced on different devices with -devel (unity 8) this issue does not occur on stable ubtouch.

[video_2019-12-09_14-37-56.zip](https://github.com/ubports/unity8/files/3939939/video_2019-12-09_14-37-56.zip)

**Comment by fredldotme** [comment]
It's a possibility. I could only reproduce the issues on the Xperia X, compared to the MX4 or Pixel 3a though.
But spawning a new setuid binary for every process in a process group is highly inefficient anyways.
The only issue currently with that PR is arm64 not working properly, the service not being spawned by dbus when called.
I need more input on that though as my daily driver is still running armhf, and my dev phone is gone for the short term.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/ubuntu-app-launch/pull/16

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

What did I try? Launched messages app and then teleports with net turned off. There is a blue loading bar animation indicating load process in teleports. Swiped from the right to see all applications in app switcher. The loading bar still moved. After focusing to messages and then again back to app switcher, the loading bar was freezed in teleports indicating that the app is suspended (unsuspended app would still animate in app switcher). After focusing to teleports, I didn't spot any lag as loading bar animation resumed.
