### ISSUE TITLE
Cannot switch between more than two keyboard layouts

### ISSUE THREAD

**Issue by Zorandon** [ubports/ubuntu-touch#1448]
-------- BUG-REPORT ------------------------------------------------------------
I chose three current keyboard layouts under "System Settings > Language & Text > Keyboard Layouts". In my case they are german, spanish and swedish. But in applications like Messages, Dekko or TelePorts I can only switch between two keyboard layouts, in my case german and spanish. I also tried to add other combinations of layouts, but I can always only choose between two.

- Device: Nexus 5 (hammerhead)
- Channel: Release candidate
- Build: 2020-W19

### Steps to reproduce
Choose more than two keyboard layouts and you won't be able to switch between more than two.

### Expected behavior
One should be able to switch between all keyboard layouts that are in the "current keyboard" list.

### Actual behavior
When more than two keyboard layouts are chosen, one can only switch between two of them.

**Comment by UniversalSuperBox** [comment]
You can open a menu to switch between 2 or more layouts by pressing and holding the Language button

**Comment by Zorandon** [comment]
Indeed, sorry and thank you, somehow that completely escaped me. I expected the keyboard to switch through all current layouts when repeatedly pressing the language-button.
