### ISSUE TITLE
Feature Request: Copy and Paste SMS Messages

### ISSUE THREAD

**Issue by LDovic** [ubports/ubuntu-touch#1449]
### Description of the feature
Copy and paste incoming SMS messages to forward to other contacts. Would be good to copy the whole message or just a part of it. Probably iPhone and Android solutions are a couple of steps to far ahead for now:
![ip](https://user-images.githubusercontent.com/20361294/81922254-c1c87780-95d3-11ea-8e43-adfb2bfe0cf5.jpg)
![an](https://user-images.githubusercontent.com/20361294/81922522-2683d200-95d4-11ea-96f9-83536388cc3a.jpg)
But I don't think copying the whole SMS block as to the clipboard would be as complicated as an initial implementation.

**Comment by lduboeuf** [comment]
Copy the full sms already exit, see swipe left actions on the message

**Comment by LDovic** [comment]
Ah ok I didn't know that thanks. I just tried to use it, how do you paste into the text field for sms? The paste option is greyed out

**Comment by lduboeuf** [comment]
humm, it works for me ( OTA-12 ) devel

**Comment by LDovic** [comment]
i close this an reopen as an issue
