### ISSUE TITLE
Can't Paste Copied Message To Text Field In SMS

### ISSUE THREAD

**Issue by LDovic** [ubports/ubuntu-touch#1450]
- Device: FP2
- Channel: Dev
- Build: 16.04

### Steps to reproduce
Copy message to clipboard by swiping left and tapping the copy symbol. Long press the text field to try to paste into text field.

### Expected behavior
Paste option should be available and message should be pasted in text field.

### Actual behavior
Copy to clipboard seems to work fine but Paste symbol is greyed out.

**Comment by lduboeuf** [comment]
Paste action should be available when long pressing in the TextField

**Comment by LDovic** [comment]
Oh yeah long press not double tap my bad. i'll look for logs

**Comment by lduboeuf** [comment]
@LDovic still an issue ?

**Comment by lutin11** [comment]
> @LDovic still an issue ?
I do have this issues some time to.
If I want to copy from sms to email (Dekko) I have to have both opened to be able to copy/past. If I copy a message then close the SMS app then open Dekko past doesn't work.

**Comment by lduboeuf** [comment]
so maybe more a generic issue, i have also that when copy from morph to Teleport for example on N5

**Comment by lduboeuf** [comment]
so we can close it for now
