### ISSUE TITLE
Can I install OTA-12 on OnePlus 3t?

### ISSUE THREAD

**Issue by giterium** [ubports/ubuntu-touch#1453]
OnePlus 3t doesn't have a stable branch in the installer. Does this mean that OTA-12 can't be put on the OnePlus 3t?

**Comment by dobey** [comment]
"OTA-N" labeled releases are only on `stable` channel, which is promoted from the `rc` channel, which gets promoted from `devel`.

I think the OP3/3t is currently on `edge` and so already has the changes that you'd see in OTA-12.

**Comment by giterium** [comment]
I thought so, too. only the interface looks the same as before.

**Comment by dobey** [comment]
What do you mean looks the same as before? OP3 only has the edge channel, so it should have always had the new interface. I do not have one, so I don't know what you are seeing though. Post a screenshot?

**Comment by giterium** [comment]
![407642F8-5962-45C4-A4F8-D2D99F8D4AEE](https://user-images.githubusercontent.com/16814062/82123191-b2e2f000-97a0-11ea-92f4-2cddb50fc67f.jpeg)

**Comment by giterium** [comment]
In the article about the ota-12 release, the interface looks different: the white background of the screen with applications and grouping of applications

**Comment by Flohack74** [comment]
You are right, this is a mistake in the blog post, I will ask to fix it...

**Comment by giterium** [comment]
Now I understand thank you :)
