### ISSUE TITLE
Can't login with Google to add contacts

### ISSUE THREAD

**Issue by xela92** [ubports/ubuntu-touch#1456]
- Device: Oneplus One
- Channel: stable
- Build: ota-12

### Steps to reproduce

- open contacts application
- open settings
- try to add google account

### Expected behavior

Should be able to login to Google and sync contacts (maybe using a native form instead of Google desktop website)

### Actual behavior

Google desktop login experience is shown through web browser. Google complains that the browser is not safe and stops the login.

**Comment by jwillikers** [comment]
I think I am having a similar issue. When I click Google to add an account, the loading symbol just keeps spinning and nothing happens.

**Comment by knipp30** [comment]
I have the same issue as jwillikers. I cannot get to the login screen - loading wheel spins.

**Comment by jwillikers** [comment]
@knipp30, I created issue #1472 to track this since I realized I don't hit this issue in the Calendar app, but in Online Accounts in Settings.

**Comment by ruedigerkupper** [comment]
Confirmed. You can't currently add Google account in UBPorts: Google claims the browser "may be unsafe".

**Comment by ruedigerkupper** [comment]
Today Google announced that not even desktop Ubuntu will be allowed to access the useeir's Google account any longer. It does not meet Google's security requirements...

**Comment by xela92** [comment]
@ruedigerkupper can you please provide more information about this announcement? I think it could be useful, I'm also wondering what is "unsecure" about it, what else should be implemented in order to have a Google-prof "secure login experience"?

**Comment by ruedigerkupper** [comment]
I received this mail today (sorry it's German):
> Lieber Google-Nutzer,
>
> ab dem 8. Juli 2020 hat die folgende App keinen Zugriff mehr auf Ihre Gmail-Daten:
> 
>  Ubuntu
>
> Die Sicherheit von Daten und Nutzern ist seit jeher ein zentraler Aspekt bei der Entwicklung von Google-Tools und ‑Diensten. 
> Letztes Jahr haben wir aus eigener Initiative unsere Nutzerdatenrichtlinien aktualisiert, um Gmail-Nutzer noch besser zu schützen.
> 
> Die oben angegebenen Apps haben unserer Überprüfung nicht standgehalten und dürfen deshalb ab dem 8. Juli 2020 nicht mehr auf Ihre Gmail-Daten zugreifen.
> 
> Ohne diesen Zugriff funktioniert diese App möglicherweise nicht wie gewohnt. Wenn Sie Fragen haben, wenden Sie sich bitte an den Entwickler der App.
> 
> Sie können auch unser Tool "Sicherheitscheck" verwenden und damit alle Apps ansehen, verwalten und entfernen, denen Sie Zugriff zu Ihrem Google-Konto gewährt haben.
> 
> Viele Grüße
> Das Google Konten-Team

I'd expect that other Ubuntu users who have their Google account connected have received the same mail. I'm afraid it just says that the "Ubuntu app" has not met the requirements and all access rights will be withdrawn at July 8th (next week). They don't specify what the requirements actually are.
Using this tool: https://myaccount.google.com/security-checkup/ I see that "Ubuntu" is listed as an app "posing potential security risks". However, it also states that this "app" is used by 1.000.000–5.000.000 Google users. Not a small number …

**Comment by ruedigerkupper** [comment]
Oh, I just realized it's specifically about Gmail …

**Comment by xela92** [comment]
Uhm, still I can't see what should change. Should we open a issue to Google to better address this situation? Or maybe someone has a clue of what is needed to provide a Google-proof login experience?

**Comment by ruedigerkupper** [comment]
They may be separate issues:
1. The one addressed here (no login from UBPorts) may simply being the Morph browser being recognized as too old. (Supposing that it is Morph rendering the login page). It may be worth asking what they require to have the login work.
2. The issue mentioned in today's mail seems to refer to Ubuntu desktop, not UBPorts specifically. Here it may be Canonical's job to convince Google that Ubuntu is a secure operating system used by millions of users, not just some third party app.

**Comment by Flohack74** [comment]
Please see https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html and https://support.google.com/accounts/answer/7675428?hl=en - there is nothing Google will do to fix that. We are using QtWebEngine embedded into another application, and that could theoretically allow MitM attacks. So they detect this and disable login from such a browser. Basically what they say is we would need a "full" browser (preferably Chrome), call that with a request URL, then the browser does the signing and redirects to a localhost listener from the App. That won´t work at all for UT at the time being.

**Comment by UniversalSuperBox** [comment]
Hi everyone!

There are many reports of this issue around the UBports GitHub-sphere, but I think the most complete one at the moment (due to the discussion contained within) is https://github.com/ubports/account-plugins/issues/40. I will close this report in favor of that one.

Thanks for your report!
