### ISSUE TITLE
Feature request: Better text selection controls

### ISSUE THREAD

**Issue by xela92** [ubports/ubuntu-touch#1457]
### Description of the feature

On other touch-oriented systems, when you select a word you're able to extend selection quickly with selection controls. 

Actually on ubuntu touch I'm able to

- select just a word
- select all the text 

But I can't extend the selection manually.

I noticed that in some places (for instance if I select a text in a div) I got more controls, like "Select More" or "Select Less", but it should be possible to handle it more precisely.

I also noticed that, in some input boxes (in TELEports for instance) there is a separate option to handle precise selection of what you're writing. I think it should be something handled system-wide.

![selection_example](https://user-images.githubusercontent.com/342809/82127033-065d3a00-97b1-11ea-9c03-587f38c67d5a.jpg)

**Comment by Rargente** [comment]
The pull up menu in the keyboard has some pretty good text selection controls. Is that what you are looking for?

**Comment by xela92** [comment]
That's it, thanks. It's a little difficult to find (opening the keyboard's unnamed submenu) and understand at a first glance, but it works. But I saw that on Morph's address bar the UX is different, it's more android-style. I think that's more imediate and confortable, and that could be useful to add those cursor controls system-wide, side by side to keyboard's ones.

**Comment by kugiigi** [comment]
Although the OSK text selection features does help on this, I think this is indeed a real issue that needs to be tackled. The touch control for selecting is quite hard to use and currently it's only available in apps that use UITK. The browser/webapps and qqc2 doesn't have this handle.

**Comment by UniversalSuperBox** [comment]
@xela92, were you referring only to text selection inside Morph-Browser and webapps with this request?

If so, I believe this may be closed as part of OTA-13 with our recent switch to QtWebEngine 5.14. This brings text selection handles as part of the browser.

Elsewhere in the system, text selection handles should be available in text boxes in apps using the Ubuntu UI Toolkit.

**Comment by xela92** [comment]
Hi @UniversalSuperBox , 

I will soon test OTA-13 in depth and report to you!

Thanks

**Comment by UniversalSuperBox** [comment]
Fixed by including QtWebEngine 5.14 with better text selection. The UITK already had text selection controls.

**Comment by EmilAlipiev** [comment]
Hi All, what is the solution here actually? i dont understand "The pull up menu in the keyboard " what was meant with this? Where do i find it?  should I install QtWebEngine for this?

**Comment by kugiigi** [comment]
> Hi All, what is the solution here actually? i dont understand "The pull up menu in the keyboard " what was meant with this? Where do i find it? should I install QtWebEngine for this?

There are a couple of things here. Selecting texts in "readonly" texts (i.e. in the browser or webapps) and selecting texts in editable fields (i.e. text boxes in apps or webviews). The keyboard solution is for the latter. You can press and hold on the spacebar or swipe up from the bottom of the keyboard to bring up a mode where you can swipe to move the cursor and also supports selecting texts by double tapping. It will look, but not exactly, like this 
![screenshot20230910_122236017](https://github.com/ubports/ubuntu-touch/assets/29456786/91ac92fd-5134-43cd-9141-ab9c2d999ae1)

As for selecting readonly texts, this is now possible in the browser/webapps. This can be done by long pressing on texts and dragging the handle. It'll look something like this
![screenshot20230910_122452341](https://github.com/ubports/ubuntu-touch/assets/29456786/2ff7d8d1-6d77-4302-a2b1-942e0434aba1)
