### ISSUE TITLE
Apps take a while to load

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#146]
when you tap an app it can sometimes take a while to load, you expect an app especially one like contacts app to load instantly.

**Comment by BlueKenny** [comment]
I think this is more important  than a new feature.. Good coding and speed is a priority...

**Comment by NeoTheThird** [comment]
With the move to xenial as a new base, we'll also introduce a newer version of the Qt framework (version 5.9), which greatly improves loading speed. You can already try it on some devices on the 16.04/devel channel.

**Comment by ChloeWolfieGirl** [comment]
How is 16.04 coming along, I tried it a little bit ago, but then came back to 15.04 due to apps not loading, sound not working, and not having the update option in system settings, So i think I'm gonna wait until 16.04 gets an rc channel

**Comment by NeoTheThird** [comment]
After Ota-3 (eta 21. december), we will give all our attention to xenial. The problems with apps not starting have been resolved, but it's still definitely not stable yet, so there's no release candidate there.

**Comment by UniversalSuperBox** [comment]
App loading was very heavily improved by the move to 16.04, and I feel this bug is no longer actionable. "App loading is delayed by *xyz*" would be a better issue for the future.
