### ISSUE TITLE
[ sdm636 ] Hangs On The Ubuntu Logo 10 to 15 Minutes.  Then System Extremely Lag

### ISSUE THREAD

**Issue by dopaemon** [ubports/ubuntu-touch#1460]
# UbPorts armhf
Device : Redmi Note 5 Pro 
Halium Version : Halium 9.0
At the Ubuntu Logo I Need At least 10 Minutes Warm Up.  And after that.  Is Very Lag.  When I am at the Ubuntu Boot Logo I can turn the screen on and off

Open Terminal Or Other App. I Wait 5 Min. 
                                                  => Auto Reboot
                                                  => Open  And Don't Lag

Key Board Not Lag
Unity8 Wait 5 Min And Not Lag ( Turn Off Screen And Turn On Screen => Lag => Auto reboot )

This Log 
https://github.com/Linux-On-Whyred/Log/blob/master/log.txt

Thanks Support Me

**Comment by Vince1171** [comment]
Hi
First, thanks for trying to increase the devices supported list :)
Unfortunately this isn't the right place for asking help about porting.
Issues listed here are only about the Operating System itself or about devices officially supported/present in the ubports installer...
if you need help to port your device, you can ask in the [halium telegram channel](https://t.me/halium) or the [ubports porting channel](https://t.me/ubports_porting)

Good luck and keep it up
