### ISSUE TITLE
Opening Camera App takes 10-15sec

### ISSUE THREAD

**Issue by FPfabi** [ubports/ubuntu-touch#1461]
- Device: FP2, New Camera Module
- Channel: Edge
- Build: 2020-W18, 16.04 LTS

### Steps to reproduce
Open Camera App

### Expected behavior
Start should take 2-3 sec. Max.

### Actual behavior
Instead screen is black for 10-15sec until Camera App is loaded

**Comment by 23RoMax** [comment]
> pine64 braveheart
> ubuntu 16.04 20 06 08
> camera app opens. remaiins black screen.

Camera is, AFAIK, not in a working state on the pinephone.
So no "issue"/Bug, just missing implementation.

**Comment by alexukalex** [comment]
> > pine64 braveheart
> > ubuntu 16.04 20 06 08
> > camera app opens. remaiins black screen.
> 
> Camera is, AFAIK, not in a working state on the pinephone.
> So no "issue"/Bug, just missing implementation.

erk...Quite right - not implemented. Nice bit of kit so far.

**Comment by Bugsbane** [comment]
> pine64 braveheart

Also, be aware that the dev team have asked Pinephone related issues be filed on Gitlab [here](https://gitlab.com/ubports/community-ports/pinephone/-/issues) rather than Github.

**Comment by Ublublu** [comment]
Great! No more problem on my FP2, opening of camera takes now a few seconds, and taking a picture is now very reactive.
On my side problem is solved. I did not identify where was done the correction, I discover it was fixed by chance. May be thanks to a recent camera update (I have version V3.2.3). Thanks a lot to people doing this fix!

**Comment by Flohack74** [comment]
Can you just tell us on which channel you are?

**Comment by Ublublu** [comment]
On stable channel.

**Comment by Flohack74** [comment]
So maybe we can close this?

**Comment by Ublublu** [comment]
I test on FP2 OTA-16, with Camera v3.2.3, v3.2.1, v3.1.0, I get the same results:
- opening takes around 4s
- taking a picture is almost immediate

**So for me yes this is fixed, it can be closed.**
_I suppose this was fixed by OTA-16_

**Comment by Ublublu** [comment]
note: for opening time I count from pushing the camera button, until display of picture (from camera lens) on the screen.
