### ISSUE TITLE
cannot install document viewer from openstore

### ISSUE THREAD

**Issue by Abuabdelah** [ubports/ubuntu-touch#1464]
peace be upon those who follow guidance,

I tried more than once to install the app but without success!

I'm using nexus 4.

**Comment by lduboeuf** [comment]
do you have slow internet connection ?

**Comment by Abuabdelah** [comment]
I didn't receive error, and internet speed is fine for other downloads.

**Comment by lduboeuf** [comment]
so installation failed or launching the app fail ?
If so you could provide logs ( could be done with the logviewer )

**Comment by Abuabdelah** [comment]
I tried after receiving your last message and worked.

thank you for the initiative.

**Comment by lduboeuf** [comment]
you're welcome, i've heard already that some people had issues with big application, but can't remember when and where and it was for whom that has bad internet connection.
