### ISSUE TITLE
QtContacts is missing from the amd64 rootfs

### ISSUE THREAD

**Issue by mymike00** [ubports/ubuntu-touch#1465]
### Steps to reproduce

Run `clickable desktop` of an app that `import QtContacts 5.0` ([`import_contacts`](https://gitlab.com/ubports/apps/teleports/-/tree/import_contacts) branch of TELEports in my case)

### Expected behavior

I expect the app to work just fine as it does on the phone

### Actual behavior

Instead I get
```
QQmlComponent: Component is not ready
qrc:/Main.qml:33:9: QML StackView: push: qrc:/pages/UserListPage.qml:248 Type VCardParser unavailable
qrc:/components/VCardParser.qml:18 module "QtContacts" is not installed
```

**Comment by lduboeuf** [comment]
if you update your clickable container, it should work

**Comment by lduboeuf** [comment]
have you updated the container. Contacts have been imported in clickable image since 4 days now

**Comment by mymike00** [comment]
yes `clickable update -a amd64` solved it. Thanks!
