### ISSUE TITLE
Bluetooth keyboard (BLE) issues on Pinephone

### ISSUE THREAD

**Issue by deckaddict** [ubports/ubuntu-touch#1469]
- Device: Pinephone
- Channel: ?
- Build: 20200608-18105

### Steps to reproduce
Story first. With factory image Bluetooth seemed to work. It was possible to pair my Bluetooth Low Energy keyboard using pin code on the keyboard. The keyboard didn't work however. This reminded me of the first OTA so I performed that. After the reboot, the Bluetooth settings couldn't find any device.

### Expected behavior
It should be possible to pair and type with the keyboard.

### Actual behavior
Not able to pair.

### Logfiles and additional information
Currently unknown what files to look for.

### Additional information
I should probably learn this code myself and help out. Is it possible to rebuild features of UBPorts on the Pinephone itself?

**Comment by Flohack74** [comment]
I would suggest you repost this issue here: https://gitlab.com/ubports/community-ports/pinephone/-/issues and close the one on Github. For Pinephone we somehow went to a separate community :)

**Comment by deckaddict** [comment]
Posted to pinephone specific area on GitLab as suggested above.
