### ISSUE TITLE
initial setup keyboard not registering touch lag

### ISSUE THREAD

**Issue by alexukalex** [ubports/ubuntu-touch#1470]
on initial setup eng uk keyboard registers incorrect characters and suffers extreme lag.           
Reproduced after resetting phone and doing setup again.             
changed keyboard appearance from ambiance to grey and much less lag.
os ubuntu 16.04 2020 06 08
pine 64 ubports community ed - braveheart.
love the phone just delivered by the way. kudos and thanks to developers.

**Comment by UniversalSuperBox** [comment]
Hi @alexukalex, thanks for your report!

I've tried reproducing this issue on a Braveheart device but haven't been able to manage. Initial setup wasn't speedy for me, but it wasn't failing either.

We're currently tracking issues which only affect the PinePhone at https://gitlab.com/ubports/community-ports/pinephone/-/issues. I'll close this report in anticipation of a new report there.

Please file any new issues that only affect the PinePhone there in the future.

Thanks again!
