### ISSUE TITLE
Invalid Last Updated Date in About in System Settings

### ISSUE THREAD

**Issue by jwillikers** [ubports/ubuntu-touch#1474]
- Device: PinePhone
- Channel: Stable
- Build: 2020-06-08

### Steps to reproduce

1. Go to System Settings.
2. Go to About.

### Expected behavior

The `Last Updated` row should provide the date the OS was last updated.

### Actual behavior

The `Last Updated` row reports `12/31/69` as the date, which is a surprisingly long time ago 🧐

### Logfiles and additional information

I can attach logfiles if required.

**Comment by blackfireburn** [comment]
If you haven't updated before, that sort of makes sense although it is pre epoch.

**Comment by jwillikers** [comment]
@blackfireburn It shows the date after having updated once. 😕

**Comment by UniversalSuperBox** [comment]
Hi @jwillikers!

I've recreated this report at https://gitlab.com/ubports/community-ports/pinephone/-/issues/143. We're currently tracking issues for the PinePhone separately since it's so different from our other devices.

Thanks for your report!

**Comment by jwillikers** [comment]
Great, thank you! I'm tracking the issue there now.
