### ISSUE TITLE
Set Date Automatically Does not Work

### ISSUE THREAD

**Issue by Charckle** [ubports/ubuntu-touch#1475]
- Device: PinePhone
- Channel: Stable
- Build: 2020-06-08

### Steps to reproduce

Any state of the phone, even at phone reset.

### Actual behavior

The option to get the date automatically does not work, meaning no certificate works either, etc.
The date must be inserted manually.

Also, the GUI for date insertion if not user friendly, as the numbers tend to scroll really fast with just a light touch.

### Logfiles and additional information

I believe the logs are not necessery, as the problem appears at first boot of the phone, and does not go away after the date is inserted manually. IF needed, I can get the logs.

**Comment by Bugsbane** [comment]
Hi there and thanks for filing a bug report! The dev team have asked Pinephone related issues be filed on Gitlab [here](https://gitlab.com/ubports/community-ports/pinephone/-/issues). I took a look there and didn't see any issue matching your description, so if you'd like this issue to get the attention it deserves, I'd suggest closing this and refiling there.

Thanks!

**Comment by Charckle** [comment]
Hello,will do, thank you.RegardsAndrej Z.-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 27/06/2020, 19:20 Bugsbane <notifications@github.com> wrote:

   
  Hi there and thanks for filing a bug report! The dev team have asked Pinephone related issues be filed on Gitlab here. I took a look there and didn't see any issue matching your description, so if you'd like this issue to get the attention it deserves, I'd suggest closing this and refiling there. 
  Thanks!
