### ISSUE TITLE
SD card does not mount automatically on PinePhone

### ISSUE THREAD

**Issue by jwillikers** [ubports/ubuntu-touch#1477]
- Device: PinePhone Community Edition
- Channel: Stable
- Build: 2020-06-08

### Steps to reproduce

1. Format 32GB microSD card on Desktop with GNOME Disks: MBR/FAT32.
2. Remove the battery and insert microSD card into PinePhone.
3. Power-on the phone.
4. Open "File Manager"
5. Go to "Places" by clicking the hamburger icon in the upper left-hand corner.
6. Note that there is only one device listed: "My Device".
7. Open "My Device".
6. See that `/media` is empty.
7. Go to `/dev/disk/by-label` and see that SD card is indeed listed.

### Expected behavior

From what I was able to find online, I expected the microSD card to be auto-mounted as a device in "Places" in "File Manager" and under `/media/phablet/` on "My Device" so long as it was formatted as FAT32.

### Actual behavior

The disk is not automatically mounted when the phone is turned on.

### Logfiles and additional information

I can supply logs if requested.

Attempting to format the SD card using the "External Drives" app on the phone fails with a generic "Format Error".

**Comment by UniversalSuperBox** [comment]
Hi @jwillikers, thank you for your report!

This issue is already filed as https://gitlab.com/ubports/community-ports/pinephone/-/issues/8. To keep the issue tracker clearer, I'll close this report.

Thanks again!
