### ISSUE TITLE
ear speaker not work

### ISSUE THREAD

**Issue by tetsuo-tek** [ubports/ubuntu-touch#1479]
### Illustrations

- Device: Bq E4.5
- Channel: 16.04/Stable
- Build: OTA-12

### Expected behavior
i would ear speaker usable

### Actual behavior
ear speaker is NOT usable

**Comment by tetsuo-tek** [comment]
all phone hw-parts work good, but only ear speaker has issue

**Comment by jonnius** [comment]
On my Xperia X my Headset does not seem to be recognized as well. Somebody in the german group reported that only headphones without microphone worked.

**Comment by Flohack74** [comment]
What is meant here? Earphone or headset, handset, loudspeaker speakerphone? :)

**Comment by tetsuo-tek** [comment]
> What is meant here? Earphone or headset, handset, loudspeaker speakerphone? :)

"ear speaker" means phone "ear speaker" ... some times it stops to work and i must go on "live voice" to continue the call .. it happens, on my BQ E4.5, some time without some specific cause ...

**Comment by Flohack74** [comment]
Interesting, the old BQ E5 and E4.5 are very stable regarding calls (had one for myself for years), and even if we suspect a problem there, we cannot fix it. We do not have the source code available for the Android parts. So this looks like being out of luck, sorry.

**Comment by lduboeuf** [comment]
can't reproduce on BQ4.5, hardware issue @tetsuo-tek ?

**Comment by tetsuo-tek** [comment]
The problem exists during normal activity, only occasionally and sporadically, for no apparent reason. However, I have decided, for now, to put the Bq-E4.5 aside.

**Comment by Flohack74** [comment]
I close this for now. At least all BQ devices I know had this working. @jonnius problems with a community port may not realte to the commercial devices. I can confirm that on my port e.g. headset with microphone works.
