### ISSUE TITLE
Media-hub server stop when screen is turn off

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1482]
### Illustrations

- Device: turbo
- Channel: devel
- Build: 

### Steps to reproduce
- Start playing music on the device let the screen go black
- Tested on devel channel.
- On stable its works as it should

### Expected behavior
- Music should continue playing with the screen off.
- On stable its works as it should

### Actual behavior
- Music stops as soon the screen goes off

### Logfiles and additional information

![photo_2020-06-15_14-24-19](https://user-images.githubusercontent.com/40370995/84821466-11ef8b00-b013-11ea-904c-59d43a096ff2.jpg)

**Comment by sergiusens** [comment]
I see something similar with _turbo_ when using Podbird, media-hub seems to be requesting wake_locks and releasing them on play/pause but when the system goes to sleep, audio becomes intermittent.

**Comment by wdehoog** [comment]
same happens on opo. I noticed that:
- media-hub has a wakelock even when the audio is being interrupted
- systemd-logind (15%) and polkitd (10%) have unusual high cpu usage when the problem occurs 
- when the display goes off by itself (auto suspend?) the music continues ok, when I turn the display off with the power button the music starts to be interrupted
- when audio goes wrong /var/log/repowerd is flooded with
```
2020-06-17T18:46:27.219057+02:00 ubuntu-phablet repowerd[930]: LogindSessionTracker: change_seat_properties(/org/freedesktop/login1/seat/seat0), ActiveSession=(,/)
2020-06-17T18:46:27.219088+02:00 ubuntu-phablet repowerd[930]: LogindSessionTracker: deactivate_session()
2020-06-17T18:46:27.256259+02:00 ubuntu-phablet repowerd[930]: LogindSessionTracker: change_seat_properties(/org/freedesktop/login1/seat/seat0), ActiveSession=
```

**Comment by gbdomubpkm** [comment]
For me:

- on the BQ E5 HD (dev 532) the problem doesn't appear: the music continues normally even if the screen is off.

- on the OPO (dev 1477), even when the screen turns off by itself after a delay, the music is suspended.

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-26.
It doesn't work
Checked this on a BQM10FHD running RC 2020 W-28.
It works.

**Comment by Fuseteam** [comment]
works fine on BQE5

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W36

Tested on internal speaker (no bluetooth):
- started music app :musical_note: & start playing all music
- wait until screen goes blank

Result:
- music plays as expected


Continuing test:
- wake up phone using power button 
- unlock to see music app still playing
- suspend using power button

Result:
- music plays as expected

**Comment by gbdomubpkm** [comment]
Observed on the Volla OTA-18, music app : the problem seems back on the SECOND piece of music played next, not the first one when the screen is off: the piece of music is chopped, the playback becomes normal again once the screen is on. Same effect on a playlist on the second piece of music. Has the problem already been noticed, reported for OTA-18 ? I don't know.
