### ISSUE TITLE
Is android sdk possible with this?

### ISSUE THREAD

**Issue by ZhenFTW** [ubports/ubuntu-touch#1483]
Hello, do you think it is possible to do android development with this? Can i compile apk using this? Even it is arm64?

**Comment by lduboeuf** [comment]
UbuntuTouch is not Android, and don't rely on java vm for its apps. 
There is an aside project ( Anbox ) though that can run apk apps but at early stage now and you will not benefit of the platform

**Comment by ZhenFTW** [comment]
Tho can i run terminal apps with this? Maybe like vim, android sdk, etc.

**Comment by ZhenFTW** [comment]
I've heard that gui apps are still not that ready. But how about terminal apps? Can they possibly work like the thing on desktop?

**Comment by lduboeuf** [comment]
you should ask  in the forum: https://forums.ubports.com/ or Telegram as it is a better place for questions.

**Comment by dobey** [comment]
I don't think Android Studio nor CLI SDK tools supports building on an ARM host. Only on 64-bit linux at this point.
