### ISSUE TITLE
Pinephone: system crashes when copying file from downloads to music

### ISSUE THREAD

**Issue by Zetdor** [ubports/ubuntu-touch#1487]
When trying to copy a single or multiple mp3 music files from downloads folder to music folder, 
system goes into what looks like an infinite reboot loop. This feature works normally in BQ E4.5 and FP2.

**Comment by UniversalSuperBox** [comment]
Hi @Zetdor, thanks for your report.

This issue is already filed as https://gitlab.com/ubports/community-ports/pinephone/-/issues/53.

In the future, please file issues that apply only to the PinePhone at https://gitlab.com/ubports/community-ports/pinephone/-/issues/

Thanks again for your report!
