### ISSUE TITLE
Pinephone: Contents of screen appears briefly before lockscreen when waking from sleep

### ISSUE THREAD

**Issue by faissaloo** [ubports/ubuntu-touch#1489]
### Illustrations

Here's a video of the bug:
https://www.youtube.com/watch?v=Z1heLe9s6zI

- Device: Pinephone
- Channel: Idk
- Build: 2020-06-18

### Steps to reproduce
 1. Lock the screen
 2. Unlock the screen

### Expected behavior

When the screen comes to life I should see the lockscreen

### Actual behavior

I briefly see what I was doing before I locked my phone

**Comment by UniversalSuperBox** [comment]
Hi @faissaloo, thanks for your report!

This issue is already filed as https://gitlab.com/ubports/community-ports/pinephone/-/issues/154. To keep project management easier, I'll close this report. Thanks again!
