### ISSUE TITLE
Pinephone: Settings scroll resets when hitting back 

### ISSUE THREAD

**Issue by faissaloo** [ubports/ubuntu-touch#1490]
### Illustrations

Here's a video of the bug:
https://www.youtube.com/watch?v=4N8hsQJhhVI

- Device: Pinephone
- Channel: Idk
- Build: 2020-06-18

### Steps to reproduce
 1. Open the settings app
 2. Scroll to the end
 3. Pick one of the options towards the end
 4. Hit back

### Expected behavior

I should be just as scrolled as I was before I selected the option

### Actual behavior

It scrolls up when I go back

**Comment by UniversalSuperBox** [comment]
Hi @faissaloo, thanks for your report!

When filing issues which affect the PinePhone, please file them at https://gitlab.com/ubports/community-ports/pinephone/-/issues.

This issue, however, is already filed as https://github.com/ubports/ubuntu-touch/issues/634. I'll close this report so we can focus on the existing one.

Thanks again!
