### ISSUE TITLE
Bluetooth issues

### ISSUE THREAD

**Issue by SleepIsLife** [ubports/ubuntu-touch#1496]
Hi I just received my pinephone, running the most recent stable ubports image/updated. I ran into some issue with the bluetooth icon always turned on. This being with airplane mode on too, this happens when I lock the phone and unlock the phone and the bluetooth automatically turns on. 

### Illustrations

- Device:
- Channel:
- Build:

**Comment by NTpspE** [comment]
I'm having the same issue. Both the toggle in the top bar, and the toggle in settings seems to have no effect and bluetooth remains on, and it also remains on when flight mode is enabled.

**Comment by Flohack74** [comment]
Did you read the issue template that you should file Pinephone issues on a different tracker? Obviously not. Please move it to https://gitlab.com/ubports/community-ports/pinephone/-/issues thanks!
