### ISSUE TITLE
Display turns on randomly - Pinephone

### ISSUE THREAD

**Issue by NTpspE** [ubports/ubuntu-touch#1498]
* Device: Pinephone Ubports community edition
* Channel: Stable
* Build: 2020-06-18

# Steps to reproduce
Leave device idle when screen is turned off / sleep mode

# Expected behavior
Device screen remains off unless notification occurs

# Actual behavior
Screen seems to turn on randomly. Initially I thought it only happened when the device was charging to show the battery was full, but after using the device regularly it can be sat on my desk and the screen will just turn on.

# Logfiles and additional information
N/A But happy to provide if necessary

**Comment by Flohack74** [comment]
Did you read the issue template that you should file Pinephone issues on a different tracker? Obviously not. Please move it to https://gitlab.com/ubports/community-ports/pinephone/-/issues thanks!

**Comment by NTpspE** [comment]
@Flohack74 I read the issue template from here yes: https://github.com/ubports/ubuntu-touch/blob/master/ISSUE_TEMPLATE.md but that doesn’t mention anything about the separate tracker - thanks for making me aware of it though.

**Comment by Flohack74** [comment]
The hint is in the comments of the template and wont be shown in the Markdown rendering. When you create a new ticket you will see the note in the beginning.
