### ISSUE TITLE
Clicking on added VPN produces dialogue with no good way to close

### ISSUE THREAD

**Issue by XenonFiber** [ubports/ubuntu-touch#1501]
When clicking on a VPN configuration, there's no way to dismiss the dialog produced without clicking 'Remove' or 'Change.' I've already accidentally deleted a configuration because of this, and I'm having to click 'Change' then immediately click 'Cancel' in the edit window because of the lack of a dismiss button while trying to turn the VPN on/off and missing the small switch.

**Comment by UniversalSuperBox** [comment]
Hello @XenonFiber,

I've opened issue https://github.com/ubports/system-settings/issues/254 to address the trouble you've seen with the VPN dialog in system-settings. Please continue discussion there if I've missed something!
