### ISSUE TITLE
Call Audio (send/receive) failing [pinephone]

### ISSUE THREAD

**Issue by xonq** [ubports/ubuntu-touch#1502]
Any outgoing/incoming calls do not have audio in or out. PinePhone UBports community edition. Carrier: ATT USA. Using nano->micro sim adapter. June 18th update.

also worth noting I cant make outgoing calls On 4G band. will open separate issue for this. audio problem is the same across bands.

**Comment by UniversalSuperBox** [comment]
Hi @zonq, thanks for your report.

We're currently tracking issues which only affect the PinePhone at https://gitlab.com/ubports/community-ports/pinephone/-/issues. There are several issues relating to call audio and calls failing to be sent or received.

Please file any new issues that only affect the PinePhone there in the future.

Thanks again!

**Comment by xonq** [comment]
Hey @UniversalSuperBox, my bad. ill start following that repository. cheers.
