### ISSUE TITLE
Meizu Pro 5 does not boot

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1504]
- Device: Meizu Pro 5 (turbo)
- Channel: devel
- Build: 2020-06-27 and higher

### Steps to reproduce

1. Turn on the device

### Expected behavior

The device boots to a lock screen

### Actual behavior

The device stays on the Meizu logo

### Logfiles and additional information

Here is a log of unity-system-compositor when the new libhybris is installed: https://paste.ubuntu.com/p/rGNHT2xkHc/
From the start to 15:22, the compositor is failing to start. At 16:10 it starts normally since the user has moved back to stable.

Here's lightdm's log from two crash loops followed by the successful run: https://paste.ubuntu.com/p/dYhdVNfbd7/

It appears that the Mir Android Platform is failing very early in its initialization with a segmentation fault. The cause of this is unclear, and every Pro 5 that I know about is in use as a daily device, not available for debugging. Someone has offered me theirs and I've accepted, though it will be some days before I receive it.

**Comment by mariogrip** [comment]
Attaching gdb 

```
Thread 1 "unity-system-co" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt full
#0  0x00000000 in ?? ()
No symbol table info available.
#1  0xf43d7b7e in hybris_gralloc_initialize ()
   from /usr/lib/arm-linux-gnueabihf/libgralloc.so.1
No symbol table info available.
#2  0xf4d137fa in ?? ()
   from /usr/lib/arm-linux-gnueabihf/libhybris//eglplatform_null.so
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/libhybris/pull/21
