### ISSUE TITLE
action on Ubuntu logo of the launcher bar has no effect

### ISSUE THREAD

**Issue by lutin11** [ubports/ubuntu-touch#1505]
Pressing on Ubuntu icon does not make application launcher to be displayed.
This happen after a moment. I haven't identified what cause the problem.
Restarting Unity throw UnityTweak make it works again for a while.
Devices: Nexus 5 and Meizu 4
Channel: stable and devel
Same comportment after reinstallation and wip data

**Comment by lduboeuf** [comment]
confirmed there on N5, randomly

**Comment by Arc676** [comment]
App drawer working fine for me on Nexus 5/hammerhead running build 2020-07-02 on `devel`.

**Comment by lutin11** [comment]
I thought the problem was gone but It is back again on devel (2020-07-08/2)

**Comment by Arc676** [comment]
Odd. I'm on 2020-07-09/2 on devel and it's still fine (again, Nexus 5).

**Comment by balcy** [comment]
problem not present on BQ Aquaris 4.5 devel 2020-08-13

**Comment by UniversalSuperBox** [comment]
I am currently unable to reproduce this issue as well. If anyone sees this again, please tap the button a few times then take the contents of `~/.cache/upstart/unity8.log`. That will help us diagnose the issue.

**Comment by lutin11** [comment]
> I am currently unable to reproduce this issue as well. If anyone sees this again, please tap the button a few times then take the contents of `~/.cache/upstart/unity8.log`. That will help us diagnose the issue. I'm closing this report for now until we can get more information.

This bug is back !
while tapping the button there are no logs put on unity8.log file but there were some on ubuntu-push-client.log one.
ubuntu-push-client.log: https://paste.ubuntu.com/p/sGkbSkYvZK/
This are the log when i flip right then left the apps panel.
unity8.log: https://paste.ubuntu.com/p/4MjRRwxRXk/
