### ISSUE TITLE
Clicking the links in support.MD doesn't work

### ISSUE THREAD

**Issue by kramer65** [ubports/ubuntu-touch#1509]
I'm writing this from my ubports pinephone, so first of all props to you guys for building this awesome software.

I just had a question. I wanted to install spotify. So seeing that I'm used to Ubuntu I typed `sudo apt update && sudo apt upgrade` to start off, but that got me into permission errors. I then wanted to try a `snap install` but snap is not installed. So I then wanted to ask a quescion somewhere on how to install snap, but I didn't know where. So I opened the UBPorts app on the phone. That shows a text with several links, but none for general user questions. So I clicked the link for sending bugs and feature requests, which got me to this github page. I then wanted to open an issue to ask my question, and that gave me a pop up with a suggestion for a page with a text called suppprt.MD (or similar) where there are a couple links to telegram and a forum etc. None of those links work however, I think because none of them start with `https://`.

So yeah, maybe sharing my first 20 minutes on my ubports phone can not only gve you a tip on fixing those links, but also give you an insight on how a user uses the phone.. :-)

Anyway, thanks for creating this. I hope it can improve over time.

And one more thing. These are the things I would need to start using this phone as my daily driver: a working camera, gps and whatsapp.

**Comment by dobey** [comment]
> whatsapp

We have no control over WhatsApp. You can request them to provide a native app for UT, but it's not something that can be provided by third parties. If reliable WhatsApp is required, then you will likely need to use Android or iOS (and to use whatsapp webapp, you'll need to have one constantly connected to server anyway).

**Comment by kramer65** [comment]
@dobey - Yes I know Whatsapp is not really possible now, although I do want to try to set up a matrix bridge. 

I'm actually more interested how I can do "normal stuff" on the command line. How do I upgrade the system? How do I install stuff (apt/snap/flatpak)? What if I want to install for example nginx. Is that possible?

**Comment by Flohack74** [comment]
Do you want to have a personal mobile device or a server :D - TLDR; none of the install methods you mention is recommended, the root file system is readonly and should stay that way. You can use a so-called libertine container to install other Unix-like tools, but leave the rootfs alone, mainly because of image-based upgrades, but also for security and stability. You can easily render your device unusable with installing incompatible packages. And there is no console with keyboard you can use to repair it, you need GUI and touch screen more or less (ignoring adb and ssh options but they might not be available all the time).

**Comment by dobey** [comment]
> I'm actually more interested in how I can do "normal stuff" on the command line. How do I upgrade the system? How do I install stuff (apt/snap/flatpak)? What if I want to install for example nginx. Is that possible?

You can install apps through _Open Store_ app on the phone. Snaps are not supported. The rootfs is readonly and apt is not supported. If you need to install some legacy or CLI apps for some reason, there is Libertine to create a container and install things in there. If what you want is a traditional PC Linux distribution on your phone, then Ubuntu Touch is probably not what you want, as it's designed to be a usable phone/tablet operating system with enhanced security features (like the readonly rootfs, app confinement, and app lifecycle policy).

**Comment by UniversalSuperBox** [comment]
Hello @kramer65,

I've opened https://github.com/ubports/ubuntu-touch/pull/1570 to fix the problem with the links in SUPPORT.md. I hope you stick around and join us on our [forum](https://forums.ubports.com) for more support and questions!

Thanks for letting us know about those links.

**Comment by kramer65** [comment]
I know this is closed, and that's fine. I just wanted to respond to this one by @Flohack74  :

> Do you want to have a personal mobile device or a server :D

Actually I would love to be able to ssh into my phone. To work with it like I do with any Ubuntu machine. I just love it that I've got Ubuntu both on my laptops and my servers and that any knowledge is interchangeable. I'd love for the same to be true about my Phone. It makes that I can tinker on the phone. Mess around with it. Try to get stuff working on it.

In its current state Ubuntu Touch is not working out for me as a developer interested in tinkering with it. I've resorted to using Mobian on my Pinephone instead. I wish the UBports project of course all the best (I actually donated money in its early days to UBports when I bought the BQ Aquaris M10 Ubuntu Edition.. :-) )

Anyway, just my 2 cents.. :-)

**Comment by Flohack74** [comment]
There are different user personas, yes. And we try to find a balance between all, but its hard when you have stability and resilience for the non-tech users in mind that need a phone "just working", and at the same time tech nerds that want to play with it. In fact, its not possible really to balance that.

This discussions are ongoing for a long time, but we think, from the "normal users" point of view, there is no regular need to for example modify the root fs with installing apt packages, so why not make this part readonly. Apps dont need to have write access to all files in the users home, so why allow it. The less can be modified, the less can go wrong during normal use or updates. Partially applied updates with apt can be a horror if your internet dies in the moment of this process, and you migfht be left with an unusable device until you can find a laptop and USB cable to repair your phone.

If a user makes a system upgrade, it should be atomic, either be on the new system, or stay at the old one. That works pretty well with Ubuntu Touch, we do not get many complaints about our upgrade process.

Yes it introduces a lot of contraints, as you might feel it, but it also allows to hand out the device to unexperienced users, which is the majority on this planet probably :P and to try challenging their current mobile phone plus ecosystem. We aim not to stay in the niche of tech nerds, we need to take "normal users" onto the journey.

**Comment by kramer65** [comment]
Fair points, and I definitely see the advantages of it. The thing is that this is an open source Linux phone, so the first big chunk of users will inevitably be tech nerds such as myself. And they can be the ones helping improve the system as well.

But hey, it's open source, which means fragmentation and everyone trying something different. In the end I just hope there will be a good Linux for mobile distro. I don't really care which one it will be. For now Ubuntu Touch is not really for me, but I wish you guys all the best.

Cheers!
