### ISSUE TITLE
Proposals for the calendar App

### ISSUE THREAD

**Issue by KrisbyZottle** [ubports/ubuntu-touch#1517]
- Device: Nexus 5

### Expected behavior / Proposals
- choose colours for appointments like in the picture previews in the OpenStore
- (outside the calendar app in the main window) -> delete reminders directly in the top navbar (time & date section)

Sry if I wrote it wrong here because theese are not really Issues. If I`m wrong, please write me, if or where I can make proposals to contribute to the UT project.

**Comment by UniversalSuperBox** [comment]
Hello @KrisbyZottle!

This repository isn't the best place to make requests for the calendar app, we might end up losing them. The best place for that is https://gitlab.com/ubports/apps/calendar-app/. When making requests, it is very helpful to visually show what you mean and only make one request per opened issue. That will help us better understand what you mean and better determine when your requests have been completed.

I'll close this report pending filing on https://gitlab.com/ubports/apps/calendar-app/. Thank you so much for your report!
