### ISSUE TITLE
Possible system crashes caused by morph-browser

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1519]
This report is only to prevent devel pushing to rc, see the real report: https://github.com/ubports/morph-browser/issues/341

**Comment by UniversalSuperBox** [comment]
This is actually caused by https://bugreports.qt.io/browse/QTBUG-85802 causing the browser to crash. Sometimes on an app crash, Lomiri also crashes. But since the QtWebEngine bug is still valid, I will keep this issue open.

**Comment by jezek** [comment]
There was a call for testing, how to test this?

**Comment by cibersheep** [comment]
> There was a call for testing, how to test this?

I think was the bug that made Morph to crash on very long websites. Try to scroll this website: https://secure.endless.horse/

**Comment by cibersheep** [comment]
I seem to scroll endlessly with no problem (E5HD RC)

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-36.
It works in https://secure.endless.horse.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W36

Scrolled https://secure.endless.orse for about 5 minutes, experienced n crash.
