### ISSUE TITLE
The "circle" points are missing on the first day of the month

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1522]
BUG-REPORT 

- Device: bq E5 HD
- Channel: stable (and devel)
- Build: 

(It's not an important bug! Just for the record!)

On the first day of the month, the first time the display is activated, the dots in the circle are missing (from the second time onwards all OK)
See screenshoot
Seen in May June and July

Tomorrow is August 1st. then you can check!

**Comment by FlavioMala** [comment]
![screenshot_circle](https://user-images.githubusercontent.com/50835740/89020746-b574d080-d31f-11ea-9227-92f141e40a2c.png)

**Comment by UniversalSuperBox** [comment]
Hi @FlavioMala, thanks for your report!

This issue has already been reported as https://github.com/ubports/ubuntu-touch/issues/1059. To prevent any confusion, I'll close this report in favor of that one. Please continue any further discussion there.

Thanks again!
