### ISSUE TITLE
Change the name to the wrong file

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1523]
BUG-REPORT

- Device: bq E5 HD
- Channel: devel
- Build: 564 30 (or 31) July 2020

### Steps to reproduce
Go to memory (internal) > Picture > Screenshots
Select a file, edit the name, save

### Expected behavior
Change the name to selected file

### Actual behavior
Change the name of another file (the first on the list, if I'm not mistaken)

**Comment by lduboeuf** [comment]
The relevant issue tracker for fileManager, here: https://gitlab.com/ubports/apps/filemanager-app/-/issues/85
