### ISSUE TITLE
VPN settings not saving

### ISSUE THREAD

**Issue by FatBirdie** [ubports/ubuntu-touch#1524]
When trying to add a VPN connection, setting "Key direction" for TLS and/or Cipher type, the "OK" button does not become active for saving. If something else (like server address or port is changed) the button becomes active. Although saving the profile with a "Key direction" or "Cipher" by doin so, it still does not keep the setting for those two options.

**Comment by UniversalSuperBox** [comment]
Hi @FatBirdie,

I am unable to confirm this problem on my Xperia X running the OTA-13 release candidate or my FP2 running OTA-12 stable. I tried:

1. Tapping "Add Manual Configuration..." in VPN settings
1. Tapping the new configuration
1. Tapping "Change"
1. Checking "Use additions TLS authentication"
1. Setting "Key direction" to "1" or "0"

The "OK" button at the bottom of the screen became active.

Could you show your settings before and after your changes which cause this problem?

**Comment by UniversalSuperBox** [comment]
Hi @FatBirdie,

Since we haven't heard from you for a while, I'm going to close this issue report. If you're still having trouble with this on Ubuntu Touch, please let us know and we can reopen the report.

Thank you!
