### ISSUE TITLE
BQ MH10 does not remember wifi passwords

### ISSUE THREAD

**Issue by ernmander** [ubports/ubuntu-touch#1535]
Device MH10 Development Channel Build 20-08-28

Every time the device reboot I have to re-enter the WiFi password for any WiFi network.

**Comment by Flohack74** [comment]
Please check your MAC address in system-settings - information or about. Does it read all 000´s ?

**Comment by ernmander** [comment]
I have a WiFi address 00:08:22:6C:93:FB but I don't have any MAC address or any listing of Mac anywhere in setting.

**Comment by Flohack74** [comment]
Ok can you observe if this address changes after each reboot?

**Comment by ernmander** [comment]
Hi there yes that address changes after each reboot / then reconnection to the network

**Comment by Flohack74** [comment]
Then your device generates a random/fake MAC address. This is typically happening after using the SPFlashTool to change from Android to Ubuntu Touch or vice versa, and pressing the wrong button. Did you do anything like this?

**Comment by ernmander** [comment]
The original Canonical Ubuntu Touch was installed using the BQ instructions, but I didn't have any button presses to do. The install went fine and WiFi worked and didn't forget WiFi passwords. Then I installed UBports UbuntuTouch over the Canonical install using the UBports installer. Then the WiFi password issue happened from first reboot of that install.

**Comment by Flohack74** [comment]
Thats weird that should not touch it....

**Comment by UniversalSuperBox** [comment]
Hi @ernmander,

Are you still experiencing a problem with your M10 failing to reconnect to WiFi networks?

**Comment by ernmander** [comment]
Hi Dalton. Yes the issue is still there. I'm going to try a reflash with the latest UBports installer

**Comment by Flohack74** [comment]
As I remember this issue would only occur if you have damaged the persistent storage during a change from Canonical old version or Android to UT. When using spflash tool this could happen, and then everytime you reboot you would get a random MAC only.

**Comment by UniversalSuperBox** [comment]
It is possible that the information in https://github.com/ubports/ubuntu-touch/issues/1262 will help you fix or work around the issue. Since we have not received more reports of this issue, I'm inclined to believe it is a problem that occurred while flashing from Android to Ubuntu Touch on your device.

**Comment by ernmander** [comment]
I'd thought you guys had forgotten about the fault. Hence no reason for me to keep engaging
