### ISSUE TITLE
Draft: inconsistency in database

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1537]
As stated in PR comment: https://github.com/ubports/messaging-app/pull/167#issuecomment-683239915 draft can lead to inconsistency in the database, we should better not handle for now draft without a recipient.

fixed by: https://github.com/ubports/messaging-app/pull/227

**Comment by mariogrip** [comment]
Review in progress, so closing this :)

**Comment by Flohack74** [comment]
@lduboeuf can we somehow confirm its fine now?

**Comment by lduboeuf** [comment]
for me it is fixed but maybe it is not too much tested by others. Now i've disabled the save draft when no contact is selected to avoid such issue.
