### ISSUE TITLE
The interface not smooth 

### ISSUE THREAD

**Issue by nexus5ubuntutouch** [ubports/ubuntu-touch#1543]
hammerhead ota 12 stable. scrolling in browser have lags. when open most recent apps, multitasking. swipe from left and right corner. in Ubuntu a lot of animations and scrolling are not smooth. please fix it. in android better animations and scrolling.

**Comment by lduboeuf** [comment]
Hey, don't forget your playing with a 7 year old device.
Contribution welcome...

**Comment by nexus5ubuntutouch** [comment]
android 7 have better animations and scrolling

**Comment by lduboeuf** [comment]
Please do not compare Android with UT. As you cannot compare the Google team of hundreds of developers with Ubports

**Comment by kugiigi** [comment]
Although this may be true and may actually be improved, this issue may be hard to quantify and say that it's already fix. It's too broad.
