### ISSUE TITLE
720p youtube browser Laggs

### ISSUE THREAD

**Issue by nexus5ubuntutouch** [ubports/ubuntu-touch#1555]
Laggs youtube 720p browser
Hammerhead ota 12 pre relieze

**Comment by nexus5ubuntutouch** [comment]
Realize candidate

**Comment by Flohack74** [comment]
Sorry man if you cannot a) search for existing issues here in this tracker or b) cannot follow the issue reporting template I have to close all of your issues. We are doing this in our free time and nobody has patience to check for duplicates or ask you for each of them for making the bug report valid.

**Comment by MrCyjaneK** [comment]
This issue exist, and it's a known issue.
