### ISSUE TITLE
Unable to enable preexisting alarm without repetition anymore

### ISSUE THREAD

**Issue by randomchars42** [ubports/ubuntu-touch#1558]
- Device: FP2
- Channel: RC
- Build: 2020-W37 (and the two builds before that)

### Steps to reproduce

 1. open "Clock" core app
 2. try to enable preexisting alarm
      * case 1: e.g. 05:00, no repetition
      * case 2: e.g. 04:00, repeats "weekdays" or any other form of interval for that matter

### Expected behaviour

Slide will become green, alarm symbol appears in indicator at top, alarm is set.

### What happens

Case 1: Slide moves to the right but remains greyed-out, no alarm is set (no indicator symbol, restarting the app shows the alarm disabled).

Case 2: Slide moves to the right, becomes green, indicator appears, alarm is set.

Creating a new alarm without repetition works as expected.

**Comment by UniversalSuperBox** [comment]
Hi @randomchars42,

The clock-app is currently maintained on GitLab, at https://gitlab.com/ubports/apps/clock-app.

I believe this may be an issue inside clock-app and that would be the best place to start looking at this. I would like to move this report there, but the previous maintainer of the app required logs of the app when the issue occurred.

Might I ask you to create a new issue report at https://gitlab.com/ubports/apps/clock-app/-/issues with the required information? That will help this issue get fixed faster.

I'll close this report in anticipation of the next. Thank you!
