### ISSUE TITLE
Unknown missed call

### ISSUE THREAD

**Issue by c4pp4** [ubports/ubuntu-touch#1561]
### Illustrations

- Device: Xperia X
- Channel: arm64/RC
- Build: 2020-W37

### Steps to reproduce

miss a call from known contact

### Expected behavior

indicator-messages shows name from contact list

### Actual behavior

indicator-messages shows number instead of name

**Comment by UniversalSuperBox** [comment]
This issue has also been reported as https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/66.

But there was a reason why some Xperia X users experienced it, others not: it's only broken when an arm64 build is used!

This code disables the check for a contact on arm64 devices: https://github.com/ubports/telephony-service/blob/926913a3ff83d8268a49dd234e6c1339a6fddf40/indicator/messagingmenu.cpp#L394-L397

**Comment by c4pp4** [comment]
@UniversalSuperBox 
Yes, it's on arm64 (I've edited the first post). Thank you.

**Comment by jonnius** [comment]
I just tested and confirm it works on RC channel.
