### ISSUE TITLE
No Access To Dialer During Call to Voicemail

### ISSUE THREAD

**Issue by gf-1231** [ubports/ubuntu-touch#1563]
- Device: BQ Aquaris 4.5 Ubuntu Edition
- Channel: Release candidate
- Build:  Ubuntu Touch 16.04 armhf 2020-w37

### Steps to reproduce
1) Open the phone app
2) Press and hold the number “1” on the number pad to auto-dial the voicemail service
3) Screen goes black
4) Voicemail service is dialed and the auto-voice is asking for me to put in my password
5) Since the screen is black, I can't put in my password

### Expected behavior
After phone call has engaged, the dialer screen should be showing, if the phone proximity sensor is not covered (ie. not against my ear)

### Actual behavior
Screen goes black after call engages and I am unable to activate screen to punch in requested voicemail number-code.

I tried:
press finger over proximity sensor and drag downward toward center of screen and the screen pops up
but release your finger from the screen and it goes black again.

Also tried:
Push and hold the on/off button and the screen turns on but as soon as you release the on/off button, the screen goes black.

Dialing the voicemail phone number like a regular number works fine.

Workaround:
Dial the voicemail phone number like a regular phone number (find the number in the previous calls list and add it to your contacts list)

**Comment by mateosalta** [comment]
works on xperia xp

**Comment by lduboeuf** [comment]
@gf-1231 can you test with that PR if you see a difference ?: https://github.com/ubports/dialer-app/pull/134

I can't repeoduce here with BQ4.5

**Comment by UniversalSuperBox** [comment]
Given https://github.com/ubports/dialer-app/pull/134 has been merged and there has not been another confirmation, I will close this issue. Please let us know if you're still experiencing this problem on Ubuntu Touch OTA-15 or newer.
