### ISSUE TITLE
Wifi Not working

### ISSUE THREAD

**Issue by marthinx** [ubports/ubuntu-touch#1564]
On my Aquarius  M10 hd the wifi is Not t working.
1. i habe Go reenter the Passwort
2. no Internet gut connected Go the wifi

**Comment by UniversalSuperBox** [comment]
Hello @marthinx, thank you for your report!

It sounds like your tablet is unable to connect to WiFi. Could you please answer the following questions for me?

1. Did your device come with Ubuntu Touch, or did it come with Android? How did you install Ubuntu Touch on your device?
1. What is the security type of your WiFi network? WEP, WPA, WPA2, or WPA-Enterprise?

**Comment by UniversalSuperBox** [comment]
Hi @marthinx,

Since we haven't heard from you with more information, I'll close this report for now. Please let us know more information about this problem so we can help troubleshoot and solve it.
