### ISSUE TITLE
Can access files via MTP without unlocking device

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#1582]
### Illustrations

- Device: Kagura
- Channel: devel
- Build: 2020-10-10

### Steps to reproduce

1. Plug in device via USB to computer

### Expected behavior

* files inaccessible unless device unlocked

### Actual behavior

* can access all files without unlocking device
* device is not in developer mode

**Comment by fredldotme** [comment]
I would not consider this a bug, it's a security feature.

The mtp-server specifically has been hooked up with the lockscreen state to not allow random strangers to plug in the device without requiring a password or PIN code.

**Comment by userj** [comment]
> I would not consider this a bug, it's a security feature.
> 
> The mtp-server specifically has been hooked up with the lockscreen state to not allow random strangers to plug in the device without requiring a password or PIN code.

Yes, I agree. What I am saying is that the opposite of this is the case. So anyone can plug my device in right now and access the files.

**Comment by fredldotme** [comment]
Sorry, my bad. AFAIK it doesn't relock MTP as soon as you access the device after an unlock, maybe that's what's happening?

**Comment by kugiigi** [comment]
Not sure if this is what you're experiencing but if I'm not mistaken, MTP is available after you unlock at least once. Afterwards, it'll still be available even locked. This is the same behavior on Android.
