### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1585]
BUG-REPORT

Time

- Device: bq Aquaris E5 HD
- Channel: dev
- Build: "608" 18 oct 2020

### Steps to reproduce
The time in the top bar  (and in the "circle") is UTC (e.g. 13:35); the time in the settings is UTC+2 (e.g. 15:35) as before upgrade.

In 'settings ' it is "manual", but: 
I can change the time, but changes are lost exit from 'settings'.
The same if I set to 'auto' (return to manual) and also is not possible to set a different UTC (test with 'Berlin, Rome, Milan, Genua....')... lost after exit from 'settings'.

Still present with upgrade to "609" and "610".

**Comment by Daniel20000522** [comment]
Confirmed on Nexus 5 devel 1756

**Comment by FlavioMala** [comment]
Addendum:
If I have got an alarm set at 7:35 (for example), the alarm will sound at 11:35, 4 hours later !!
This while the top bar shows 9:35 (UTC) and the phone time in setting (not editable) shows 11:35 (UTC+2).
In summary:
I need to setan alarm at UTC-2 (e.g. 3:35) to make it sound at a time set on the phone UTC+2 (e.g. 7:35), while the top bar shows UTC (e.g. 5:35)...

**Comment by bjm39** [comment]
The same on bq Aquaris E4.5

**Comment by TellingBerto** [comment]
Device: VollaPhone
Channel: rc
Build: 2020-W43

Top bar shows 9:46 (UTC+1), the phone time in 'settings' (not editable) shows 9:46 (UTC+1).
If 'settings ' it is set to "manual": Changed time are kept when exiting from 'settings'. Manually changed time remain after reboot.

No problem on Volla.

**Comment by FlavioMala** [comment]
I confirm that after upgrade ("612" 22 Oct or "613" 24 Oct, now I do not remember well) the problem is over.
Thanks a lot !

**Comment by jezek** [comment]
Device: FP2
OS: 2020-W43

Top bar shows 17:12. In the settings the timezone is UTC+1, time is set to "auomatic" and the non editable time says "... 17:12:55 CET".
When time setting it is set to "manual", changed time (16:12) is kept after settings are closed and remains after reboot.
After switching to "automatic", the time changes back to right value (17:12) after few seconds (internet connection has to be turned on).
