### ISSUE TITLE
Issues after system update on Oct. 7 2020

### ISSUE THREAD

**Issue by Davenothere** [ubports/ubuntu-touch#1588]
Phone
LG Nexus 5

OS
Ubuntu-Touch
Distro Ubuntu 16.04.7 LTS

System Platform

**Comment by Davenothere** [comment]
Dammit did it again

System Platform armv71

Isuse is

After update

Lost spell check, morph browser freezes, locks up, becomes unresposive and forces a restart. 

Would like to restore back before system update. That's when everything worked

**Comment by Arc676** [comment]
For the record, you can edit posts on GitHub to add more information if you accidentally post before you're done.

**Comment by dobey** [comment]
What channel are you on? You can see in system settings under update settings.

**Comment by Davenothere** [comment]
It says stable

**Comment by dobey** [comment]
OK. That is very odd. But there is a release candidate ready for testing now that should become a stable release update soon. If you'd like to try it before, you could switch to the RC channel in update settings and see if the issues still occur for you. Thanks.

**Comment by Davenothere** [comment]
Hey thanks, ill try it and let you know how it goes

**Comment by Davenothere** [comment]
Hey Dobey, sorry the RC update did not fix the problems. 

Any other ideas I can try. 

What I really want to do is restore the phone back before Oct 7 update. When everthing worked

**Comment by dobey** [comment]
The last stable release was Sept 24, so I'm not sure what specifically you changed on Oct 7.  If you go to "About" page in system settings, what exactly is shown next to the `OS` entry in the list there?

**Comment by Davenothere** [comment]
Okay thats a lot of typing

OS Build Number
2020-W43

UBports Image Part
20201022-1222

Ubuntu Build Disription
Ubuntu 16.04 LTS-armhf(2020 1022)

Device Image Part
20201023-12780

Device Build Discription
aosp-hammerhead-userbug 5.1.1MY 48W 1562 Test-keys

Customization Image part
Unavilable

Thats a lot of typing

**Comment by Davenothere** [comment]
Sorry for spelling errors

**Comment by Fuseteam** [comment]
do you still have issues?

**Comment by Davenothere** [comment]
Yes nothing has change. I'm about to give up and throw it drawer.

**Comment by Fuseteam** [comment]
Hmm i don't experience the lock ups but i can confirm spell check broken atm for browser apps

**Comment by Davenothere** [comment]
Well I like the OS before that system update. What I really want to do is restore it back before October 7

**Comment by Fuseteam** [comment]
That's no trivial to do, i have no idea how to do that but perhaps we can check what changed and simply fix it

**Comment by UniversalSuperBox** [comment]
Hello everyone,

Autocorrect in the browser became broken when we upgraded to QtWebEngine 5.14 in OTA-13. This issue is now tracked at https://github.com/ubports/morph-browser/issues/406.

@Davenothere, could you contact me directly when you have a moment? We may be able to get the logs we need from your Nexus 5 and create a new issue report which helps us resolve the problem. I'm @UniversalSuperBox on Telegram, if you're not on Telegram please reply here and I can find another way.

Until then, I don't believe this report is actionable. It includes two separate issues and does not contain the information needed to reproduce the problem. I'll close this for now.

**Comment by Davenothere** [comment]
Yeah  I have nothing else. All I got is this site and my E-Mail. The only Telegram thing I know is the Western Union Telegram That got sent to your house back in the day and that was gone in the early 1970s.

(hint I fairly new to the internet and cellphone use)

**Comment by Fuseteam** [comment]
@Davenothere considering you're on ut, you can search for "teleports" in the openstore it is the [telegram](telegram.org) client for ut

**Comment by Davenothere** [comment]
No I am on a 20 year laptop on dial-up internet. Where I live Cellphone service don't here, The cellphone is mostly for driving emergencies when I drive to the city. I mean it works great in the city, but in the middle of nowhere its a paper weight
