### ISSUE TITLE
predictive text gone on certain apps post update

### ISSUE THREAD

**Issue by iam01110011** [ubports/ubuntu-touch#1589]
### Illustrations

- Device: oneplus one
- Channel: (i have no idea!)
- Build: OTA 13

### Steps to reproduce

(a constant bug/error on certain apps)

### Expected behavior

predictive text/ spell check to work on all apps

### Actual behavior

post latest update of ubuntu today....apps such as morph browser, duo lingo, axolotl dont have predictive text/ spell check feature. whereas text messaging does, note app does have the feature.

### Logfiles and additional information

tried turning the features on and off in settings, makes no difference. spell check/ predictive did not appear on the keyboards on the mentioned apps.

thankyoooou : )

**Comment by Fuseteam** [comment]
this seems fixed in OTA 14

**Comment by UniversalSuperBox** [comment]
Hello @iam01110011, thank you for your report!

Predictive text stopped working on webapps and the browser after the QtWebEngine 5.14 update in OTA-13. This issue has been reported and is tracked at https://github.com/ubports/morph-browser/issues/406 (though I could swear we were tracking it somewhere else at some point...

Please continue any further discussion over there. Thanks again!
