### ISSUE TITLE
ussd not working

### ISSUE THREAD

**Issue by novhy** [ubports/ubuntu-touch#1592]
### Illustrations

- Device: Xiaomi Redmi 8 android 9 gsi
- Channel:
- Build: Erfan GSI arm64 v10

### Steps to reproduce

send ussd code in dialer *123# 

### Expected behavior

got reply

### Actual behavior

it just showing please wait dialog
but when i use /usr/share/ofono/scripts/send-ussd *123#
it worked

**Comment by lduboeuf** [comment]
can you provide logs from the dialer-app ?

**Comment by novhy** [comment]
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Creating a QMirClientScreen now
void installIconPath()
qml: Has mouse: false
The phone number is not a valid number: "dummy"
The phone number is not a valid number: "dummy"
qml: Starting a call to *123#
The phone number is not a valid number: "*123#"
The phone number is not a valid number: "*123#"
qml: 'caller' is DEPRECATED. It has no effect.
[PERFORMANCE]: Last frame took 568 ms to render.
QObject::startTimer: Timers cannot be started from another thread

**Comment by lduboeuf** [comment]
humm nothing wrong here

**Comment by novhy** [comment]
are this like with this issue?
https://bugs.launchpad.net/ubuntu/+source/telephony-service/+bug/1438273
where i can get telephony-service logs?

**Comment by lduboeuf** [comment]
in telephony-service-indicator.log or dbus.log

**Comment by novhy** [comment]
just got dbus.log

tp-qt 0.9.7 DEBUG: BaseConnection::status =  0   oFonoConnection(0x113b9c30) 
tp-qt 0.9.7 DEBUG: BaseConnection::status =  0   oFonoConnection(0x1139b550) 
tp-qt 0.9.7 DEBUG: BaseConnectionRequestsInterface::requestableChannelClasses 
tp-qt 0.9.7 DEBUG: BaseConnectionRequestsInterface::requestableChannelClasses 
getContactAttributes (1) ("org.freedesktop.Telepathy.Connection.Interface.SimplePresence")
oFonoConnection::inspectHandles contact (1)
oFonoConnection::inspectHandles  ("")
getContactAttributes (1) ("org.freedesktop.Telepathy.Connection.Interface.SimplePresence")
oFonoConnection::inspectHandles contact (1)
oFonoConnection::inspectHandles  ("")
tp-qt 0.9.7 DEBUG: BaseConnection::status =  0   oFonoConnection(0x113b9c30) 
tp-qt 0.9.7 DEBUG: BaseConnection::status =  0   oFonoConnection(0x1139b550) 
tp-qt 0.9.7 DEBUG: BaseConnectionRequestsInterface::requestableChannelClasses 
tp-qt 0.9.7 DEBUG: BaseConnectionRequestsInterface::requestableChannelClasses 
getContactAttributes (1) ("org.freedesktop.Telepathy.Connection.Interface.SimplePresence")
oFonoConnection::inspectHandles contact (1)
oFonoConnection::inspectHandles  ("")
getContactAttributes (1) ("org.freedesktop.Telepathy.Connection.Interface.SimplePresence")
oFonoConnection::inspectHandles contact (1)
oFonoConnection::inspectHandles  ("")

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://dekko2.dekkoproject_dekko.desktop
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/Operations" interface="com.canonical.libertine.Service.Operations" member="list" mask="send" name="com.canonical.libertine.Service" pid=9831 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="running" mask="send" name="com.canonical.libertine.Service" pid=9831 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="last_error" mask="send" name="com.canonical.libertine.Service" pid=9831 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="result" mask="send" name="com.canonical.libertine.Service" pid=9831 label="morph-browser" peer_pid=5399 peer_label="unconfined"

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://seabass2.mikhael_seabass2.desktop
bool com::ubuntu::content::detail::Service::CreatePaste(const QString&, const QString&, const QByteArray&, const QStringList&) PID:  9972

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://seabass2.mikhael_seabass2.desktop
bool com::ubuntu::content::detail::Service::CreatePaste(const QString&, const QString&, const QByteArray&, const QStringList&) PID:  9831

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://com.ubuntu.terminal_terminal.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://seabass2.mikhael_seabass2.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://dekko2.dekkoproject_dekko.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://dekko2.dekkoproject_dekko.desktop
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/Operations" interface="com.canonical.libertine.Service.Operations" member="list" mask="send" name="com.canonical.libertine.Service" pid=11219 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="running" mask="send" name="com.canonical.libertine.Service" pid=11219 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="last_error" mask="send" name="com.canonical.libertine.Service" pid=11219 label="morph-browser" peer_pid=5399 peer_label="unconfined"
dbus[3763]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/OperationsMonitor" interface="com.canonical.libertine.Service.OperationsMonitor" member="result" mask="send" name="com.canonical.libertine.Service" pid=11219 label="morph-browser" peer_pid=5399 peer_label="unconfined"

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://ubuntu-app-launch.desktop

** (zeitgeist-fts:9369): WARNING **: Unable to get info on application://com.ubuntu.terminal_terminal.desktop

**Comment by lduboeuf** [comment]
So nothing special there too

**Comment by novhy** [comment]
oh ok,
Is there anything I can help?

**Comment by lduboeuf** [comment]
So if with ofono it is ok, that is more a telephony-service issue i guess.
Does it happen with every ussd numbers ?

I don't know much about all that, but the dialer-app keep the "Please wait" until no callback from ussdmanager.
Just for the test, can you try with that PR: sudo ubports-qa install dialer-app 134

**Comment by novhy** [comment]
it happend any number ussd,
i was tried with that PR
dbus,dialer logs nothing changed

**Comment by lduboeuf** [comment]
just for further investigation, is still the same if only one SIM  card inserted ?
After searching in Telegram groups, ussd seems an issue on Halium devices

**Comment by novhy** [comment]
yeah its still same

**Comment by rubencarneiro** [comment]
This issue alsi confirmed on volla phone.

**Comment by UniversalSuperBox** [comment]
Hello everyone,

This issue should have been resolved with https://github.com/ubports/telepathy-ofono/pull/18. If you can upgrade your version of telepathy-ofono somehow (most likely via switching to `devel` on your device, but I'm not sure how the GSI updates), you can test out the fix.

To QA testers: This problem only occurred on Android 9 devices and the PinePhone. QA is not required for other devices.

**Comment by jonnius** [comment]
I confirm I get a response to `*123#` (Xperia X RC).

**Comment by rubencarneiro** [comment]
Is working on devel channel on the volla phone.

A quarta, 2/12/2020, 18:28, Jonatan Hatakeyama Zeidler <
notifications@github.com> escreveu:
