### ISSUE TITLE
SMS & incoming calls: no sound

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1594]
BUG-REPORT

- Device: BQ E5 HD
- Channel: dev
- Build: "619"

After upgrade to "619" (08 nov 2020) [from "615" (31 oct 2020)] no more sound/ring tone.

Upgrading to "620" (today) does not resolve the problem.

During a incoming call the volume bar is shown (ring tone), but moving the cursor has no effect.
![screenshot20201109_134803171](https://user-images.githubusercontent.com/50835740/98543283-895bda80-2292-11eb-9857-30f8b3f95b84.png)

**Comment by lduboeuf** [comment]
It happens for me as well sometimes ( BQ4.5), when i go in silent mode and try to get back but all that is random :-|

**Comment by Fuseteam** [comment]
Confirmed no sound on incoming calls E5
Tho Push notifs sounds appears to work fine on my end fwiw

**Comment by UniversalSuperBox** [comment]
This should have been fixed by https://github.com/ubports/media-hub/pull/21, please test by running `sudo ubports-qa update` on your devel image after its build completes (https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmedia-hub/detail/xenial/7/)

**Comment by Fuseteam** [comment]
Confirmed calling works again after `sudo ubports-qa update` and a reboot

**Comment by FlavioMala** [comment]
Idem. Thanks!
