### ISSUE TITLE
MicroSD not mounted

### ISSUE THREAD

**Issue by xxirioxx** [ubports/ubuntu-touch#1595]
-------- BUG-REPORT ------------------------------------------------------------

MicroSD is not mounted. It is only visible in External Devices app but not in File Manager app, so you can't read or write it.

- Device: Xperia X Compact (f5321 Kugo)
- Channel: All (stable, beta, devel and edge)

### Steps to reproduce
Turn your phone on with microSD inserted, on insert it once OS is started.

### Expected behavior
A notification of a new external device should appear and the microSD should be visible in File Manager app.

### Actual behavior
MicroSD is not visible in File Manager. I tried the same card in Aquaris E4.5 Ubports and it works (I also formatted it).

**Comment by UniversalSuperBox** [comment]
Hello @xxirioxx,

Does the microSD card appear in the External Drives application when it is plugged in?

**Comment by xxirioxx** [comment]
Yes, it appears in the External Devices application when you insert it and disappears when you remove it. But the filesystem is not mounted (no notification appears), so you can't browse it using the file manager app.

**Comment by Flohack74** [comment]
Just a question, which format did you choose?

**Comment by xxirioxx** [comment]
The first time I tried to format it in fat32 using Ubuntu desktop. The second time I formatted it using a Bq E4.5 running Ubuntu touch. In Bq e4.5 sd card is working flawlessly. Instead in Xperia X Compact both times didn't work. I think it's related to Xperia X Compact only. Does anyone have the same problem with this device?

**Comment by xxirioxx** [comment]
Hello, I think this problem is solved in OTA18. Now microsd can be read and written.
