### ISSUE TITLE
[FEATURE REQUEST] Add an option to customize the lockscreen. Bringing back the fullScreen keys for input pin code

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#1598]
### Description of the feature
Add an option in System-Settings that allow users to customize their lockscreen. Since the very first OTA's with Canonical we've the lockscreen with full-edge for PIN input (like we do on a fresh start with simlock pin enable). Now, we get an the login screen and then the keyboards popsup in the bottom. So, I think having such option to select the layout woul'd be great.

### Illustrations
[LockScreenOptionSuggestion](https://i.stack.imgur.com/Q4hTP.jpg)

- Device: Nexus 5
- Channel: Stable
- Build: OTA13

### Steps to reproduce
Lock your phonewith a pin code, then lock your phone. Turn your screen on, then swipe from right to left.

### Expected behavior
A bigger input keys

### Actual behavior
Less bigger keys

**Comment by Fuseteam** [comment]
so you want see this on the lockscreen instead if what we have now
![screenshot20201120_083345180](https://user-images.githubusercontent.com/10421851/99796149-b9657200-2b0b-11eb-815d-fb7da18be0e9.png)

it does look nice

**Comment by ivoxavier** [comment]
@Fuseteam Yes, re-using that layout used in the early days of ubuntu touch. The one we currently have it's the default, but by adding such option to change it in system settings would be nice

**Comment by Fuseteam** [comment]
this is the current lock screen voor sim unlock, i wonder where the code is voor that

**Comment by ivoxavier** [comment]
This must be related to Lomiri repo

**Comment by Fuseteam** [comment]
doesn't have to be could system-settings

**Comment by kugiigi** [comment]
This seems to be a personal aesthetic preference though and I don't see any benefits adding  settings for this.

**Comment by UniversalSuperBox** [comment]
Hi @ivoxavier,

The full-screen PIN keyboard is no longer appropriate for use as we continue to port Ubuntu Touch to more devices with different screen sizes. Instead, we would rather focus our effort on making the system keyboard adapt to its current situation more accurately. That will provide benefits both on and off the lockscreen. The full-screen keypad could cause issues on many devices which are taller than they are wide, or similar (much like the full-screen keypad causes problems in the dialer app now).

For that reason, I believe this request should be closed.
