### ISSUE TITLE
OP3T - devel build broke twitter and linkedin web apps

### ISSUE THREAD

**Issue by andybleaden** [ubports/ubuntu-touch#1600]
- Device: OP3T
- Channel: DEVEL
- Build:114

### Steps to reproduce
Moved from stable to development - smooth upgrade (thankyou!) from Version 2 Stable to Version 114 

![screenshot20201111_125148230](https://user-images.githubusercontent.com/34811990/98922678-a4189400-24ca-11eb-9e4a-a6a89575f3f6.png)

### Expected behavior
Installed apps such as twitter/linked in to open as usual 

### Actual behavior

Web apps threw up Error message 
![screenshot20201111_125213975](https://user-images.githubusercontent.com/34811990/98922522-77647c80-24ca-11eb-93f3-941cc3da4c62.png)

Solved by downgrading back to stable (from where I never should have left!! I hear) 

Problem immediately solved

This looks as if the browser is breaking webapps?

**Comment by UniversalSuperBox** [comment]
Hello @andybleaden,

I'm not able to reproduce this. There do not appear to be any relevant changes to the browser or the OnePlus3 between October 23, the time that OTA-14 was sent to release candidate, and November 10, when the image you tested was released. It is possible that you were affected by a transient network issue or were temporarily blocked by these services. Could you please try upgrading to the `devel` release and repeating these tests?

**Comment by andybleaden** [comment]
Well....lets see

Upgraded to devel

Ran the upgrade,install


Before:

![screenshot20201117_102944672](https://user-images.githubusercontent.com/34811990/99380516-fc340980-28c1-11eb-8dc0-90ea5b7c3809.png)
![screenshot20201117_104144724](https://user-images.githubusercontent.com/34811990/99380522-fd653680-28c1-11eb-902b-1fc06592b04f.png)
![screenshot20201117_104216723](https://user-images.githubusercontent.com/34811990/99380524-fe966380-28c1-11eb-8c9d-b20c30eb4526.png)


After

![screenshot20201117_104204099](https://user-images.githubusercontent.com/34811990/99380611-1cfc5f00-28c2-11eb-8d1d-c133bb7faeab.png)
![screenshot20201117_104635467](https://user-images.githubusercontent.com/34811990/99380735-3f8e7800-28c2-11eb-97dc-3b61919aed06.png)
![screenshot20201117_104204099](https://user-images.githubusercontent.com/34811990/99380741-40bfa500-28c2-11eb-98d5-774c06d05fa0.png)


![screenshot20201117_102848724](https://user-images.githubusercontent.com/34811990/99380753-44ebc280-28c2-11eb-9841-37e4af0c6376.png)


So

You must be correct and it was a lapse

**Comment by andybleaden** [comment]
Seems to be fixed
