### ISSUE TITLE
Ubuntu touch no keyboard 

### ISSUE THREAD

**Issue by gregoryaul** [ubports/ubuntu-touch#1610]
Hi im using op3t im trying to sign into my google account to sync my contacts an it wont bring up my keyboard to type on. Wundering if this can be looked at????

### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Hello @gregoryaul , thanks for your report!

Unfortunately, this report does not contain enough information to reproduce the issue you are experiencing. Please follow our bug reporting document at https://docs.ubports.com/en/latest/contribute/bugreporting.html.

It sounds like you may be experiencing https://github.com/ubports/ubuntu-touch/issues/1607, could you please add more information to that report if it seems the same?

Thanks again.
