### ISSUE TITLE
Keyboard can't type letters to far right margin (english) "P"

### ISSUE THREAD

**Issue by skybasedc** [ubports/ubuntu-touch#1611]
- Device: Nexus 5
- Channel: stable
- Build: OTA-14

### Steps to reproduce
bring up the keyboard (any app) and try to type the P character (english).  the button only is clickable on the extreme left side of the P key.  Most of the time, typing on the "P" letter the "O" letter is typed.  this is only in Portrait mode.  In landscape the keys work fine.

### Expected behavior
Letter "P" works.  Button should be accessible all the way to the the right side.

### Actual behavior
Letter O is typed 9/10 times instead of P

**Comment by UniversalSuperBox** [comment]
Hello @skybasedc,

It sounds like you may have a dead region on your device's touchscreen. Please download an app like [Finger Painting](https://open-store.io/app/finger-painting.bhdouglass) and use it to see if the area around the P key can be drawn in. If not, your device's touchscreen has failed.

**Comment by skybasedc** [comment]
you are right.  it's an entire column on the right side of the screen about 3/8" down the entire region.

**Comment by skybasedc** [comment]
so if it was my device having a bad area of the touchscreen sensor, why does the swipe to clear the apps work?  Also, in the 'Messages' application the 'send' button is lined up directly above the 'P' character and there is no issue sending messages only typing the 'P'.   There has to be another way to validate this.  I did see what you thought was a problem by using the finger painter.

**Comment by UniversalSuperBox** [comment]
The right edge swipe is pretty forgiving on where it starts and the "Send" button is wider than the "p" key. If you take a screenshot of your Finger Painting output (push both volume buttons at once) I can confirm if what you're seeing is a hardware issue.

**Comment by skybasedc** [comment]
ok.  I will take your word for it.  I've recently dusted off this phone as I'm waiting on my PinePhone to arrive.  thanks for your time.
