### ISSUE TITLE
Crash System Settings on BQ Aquaris E5 HD on Dev Channel

### ISSUE THREAD

**Issue by marlboro50** [ubports/ubuntu-touch#1612]
Since the last few updates it is impossible to access the "System Settings" by either using 
the "system app icon" or the "system indicator". 
Though it is possible to reach the "System Settings" by i.e. the "battery indicator" or other indicators. 
When in the System Settings the app will crash when touching the "info icon". 
I think the initial Problem is the "Info menu" inside the "System Settings".
This behaviour does not exist in the stable branch.

 That's a bug. 

BQ Aquaris  E5 HD
Dev Channel
At least since version 617

**Comment by dobey** [comment]
I just updated my E5HD to latest devel and tried to replicate this issue. However, System Settings is working fine here. Is _Developer Mode_ enabled on your device? Can you get the log file for system settings to see what the issue might be?

**Comment by Fuseteam** [comment]
Works fine here as well

**Comment by dano6** [comment]
See also https://forums.ubports.com/topic/5253/system-settings-does-not-start-anymore-on-rc-channel
