### ISSUE TITLE
Bug: Sometimes when waking up device it freezes screen for 2-3 seconds

### ISSUE THREAD

**Issue by shoukolate** [ubports/ubuntu-touch#1615]
- Device: Xiaomi Mi A2 (jasmine_sprout)
- Channel: devel
- Build: All builds

### Steps to reproduce
Press power button when phone is asleep.

### Expected behavior
Waking up the device should not freeze the screen.

### Actual behavior
Unlocking the device sometimes freezes screen for a few seconds.

### Logfiles and additional information
Didn't manage to get opportunity to capture logs yet because it happens sometimes randomly.

**Comment by shoukolate** [comment]
Does not seem to happen anymore.

**Comment by c4pp4** [comment]
Still happening all the time I'm using it (OTA-17 - OTA-22).

**Comment by c4pp4** [comment]
It looks like it's fixed via https://github.com/ubports/unity8/pull/443 from OTA-24.
