### ISSUE TITLE
[Language] Bangla/Bengali does not show (gibberish) as text or in the web.

### ISSUE THREAD

**Issue by Pavel-Sayekat** [ubports/ubuntu-touch#1617]
Sms in Bangla/Bengali from Telco does not show properly (gibberish) in build 24/10/2020 for jasmine_sprout.

**Comment by lduboeuf** [comment]
humm, is it only for SMS ? Only from Telco ?

**Comment by Pavel-Sayekat** [comment]
> humm, is it only for SMS ? Only from Telco ?

not likely, chances are that it is more like a general Language integration issue.

**Comment by lduboeuf** [comment]
@Pavel-Sayekat so please edit the issue  title

**Comment by Pavel-Sayekat** [comment]
locale-gen with bn_BD UTF-8 didn't help.

**Comment by UniversalSuperBox** [comment]
Tested with https://en.wikipedia.org/wiki/Bengali_alphabet

Indeed, it appears that the browser is unable to render anything but boxes for bengali text. Contrast this with Firefox on Ubuntu 20.04, which renders these characters correctly.

![Bengali Alphabet on Wikipedia being rendered with many character errors in Morph Browser on Ubuntu Touch](https://user-images.githubusercontent.com/21966173/106972709-fe667100-6716-11eb-89b5-7be6ab581c09.png)

![Bengali Alphabet on Wikipedia being rendered correctly in Firefox on Ubuntu 20.04](https://user-images.githubusercontent.com/21966173/106972746-150cc800-6717-11eb-8e15-79671c786798.png)

**Comment by Fuseteam** [comment]
here's a work around courtesy of @mateosalta
```
sudo mount -o remount,rw /
sudo apt update
sudo apt install fonts-beng
sudo mount -o remount,ro /
```

**Comment by cibersheep** [comment]
Device: Arale
Channel: RC 2021-W45
Result: text show correctly in Morph

![imatge](https://user-images.githubusercontent.com/6640041/141339040-846eadb6-4861-4d67-b14e-ff04523d510b.png)

**Comment by Fuseteam** [comment]
wait this is now QA?

**Comment by cibersheep** [comment]
> wait this is now QA?

I think I followed the link in https://github.com/orgs/ubports/projects/29
Did I answer the wrong place?

**Comment by Fuseteam** [comment]
no, no, you're in the right place! i just wasn't expecting this to be fixed yet :joy:

**Comment by Flohack74** [comment]
@Fuseteam yeah we sneaked this in quickly before freeze xD - it seems to work however I got this message today:
![grafik](https://user-images.githubusercontent.com/16186470/141649567-08e0c39c-50be-4b7f-b640-27c789a33b95.png)
So numbers have fancy circles now. Probably needs a new issue...

**Comment by Fuseteam** [comment]
sneaky~

**Comment by Pavel-Sayekat** [comment]
> @Fuseteam yeah we sneaked this in quickly before freeze xD - it seems to work however I got this message today: ![grafik](https://user-images.githubusercontent.com/16186470/141649567-08e0c39c-50be-4b7f-b640-27c789a33b95.png) So numbers have fancy circles now. Probably needs a new issue...

How did you get that message or managed to get that message, you are from Austria.

**Comment by Flohack74** [comment]
@Pavel-Sayekat not me, some user sent me this ^^
