### ISSUE TITLE
Xiaomi Redmi Note 7 cellural data

### ISSUE THREAD

**Issue by warriormaster12** [ubports/ubuntu-touch#1619]
- Device: Xiaomi Redmi Note 7
- Channel: devel and rc 
- Build:

### Steps to reproduce
Put sim-card into sim2 slot, disable wi-fi, enable cellural data and open any application that connects to the internet.  

### Expected behavior
In sim2 slot phone should be able to connect to the internet without any issues (2g/3g/4g).

### Actual behavior
It seems to be able to enable 4g but when trying to go to youtube for example, it won't connect to it. You have to use wi-fi

### Logfiles and additional information
[msyncd.log](https://github.com/ubports/ubuntu-touch/files/5682924/msyncd.log)

**Comment by warriormaster12** [comment]
[sync-monitor.log](https://github.com/ubports/ubuntu-touch/files/5682928/sync-monitor.log)

**Comment by shoukolate** [comment]
Try enabling LTE, set apn if not already set, turn on mobile data (make sure wifi is off), reboot, try opening any website?

**Comment by Flohack74** [comment]
It could be this: https://gitlab.com/ubports/core/rootfs-builder-debos/-/merge_requests/19/diffs - is the 2nd SIM working, can you make calls with it? In any case, try installing a new rootfs from after Dec 9th.

**Comment by warriormaster12** [comment]
It's already set to always on Redmi note 7's github page
https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7/xiaomi-lavender/-/blob/master/overlay/system/etc/ofono/main.conf

Phone calls and text messages work just fine but internet drops like crazy. Update 24 seems to have fixed some of the issues. It at least works a bit better but still at some point it will drop and never recover unless you reboot device.

**Comment by alexjoverton** [comment]
Having similar issues to the above, I live within 500mtrs of a phone mast 4g so it's not signal issue. I did a reset of the APN settings, by default it is not working. I think this information is provided by the carrier automatically ...? I noticed flipping between adding the details manually ...nothing was saved . I have ended up resetting and it's shows full bar 3g or lte depending on my settings. Just no connection for now. 
I don't see any updates in updater so assuming I am at latest version. Thanks for your work on this!! cheers Alex

**Comment by alexjoverton** [comment]
calls work fine GPS ok Text ok

**Comment by warriormaster12** [comment]
For me calls work, wi-fi works, bluetooth works but LTE and gps don't

**Comment by alexjoverton** [comment]
correction , GPS takes a while to load, and sometimes doesn't want to work at all, bluetooth not had any luck just yet, would not pickup the car not tried anything else just yet.

**Comment by padhitheboss** [comment]
This bug is due to ipv6 support issue for mobile data. Disabling IPv6 will work for some operators but not for those operators who are using only IPv6 in their network.
Execute the following command to disable IPv6
./usr/share/ofono/scripts/set-context-property 0 Protocol IP
(mobile data needs to be disabled before changing the property)

Credits to @shoukolate and @ubports_porting (Telegram Group)

**Comment by shoukolate** [comment]
Credits to @notkit

**Comment by UniversalSuperBox** [comment]
I've filed a new report to consolidate information spread across multiple similar reports for all Android9 devices. This new report is https://github.com/ubports/ubuntu-touch/issues/1657. I'd appreciate if any further conversation happened there, I will close this report now.

Thank you all!
