### ISSUE TITLE
Feature request: night light and change time format

### ISSUE THREAD

**Issue by warriormaster12** [ubports/ubuntu-touch#1622]
Night light: every other os has it including Linux. Good for eyes.

Time format: customization options. All other os has it including Linux.

**Comment by Flohack74** [comment]
For the first one, do you mean https://github.com/ubports/ubuntu-touch/issues/191?
The second one: Where exactly would this display? On the lockscreen? Which time formats do you expect?

**Comment by warriormaster12** [comment]
@Flohack74 essentially warmer colors at night time so that eyes wouldn't hurt as much. 

I personally prefer time format 24 hours instead of 12 hours and I just expected that you can toggle between them without changing language.

**Comment by dobey** [comment]
24/12 hour selection i guess is also ubports/clock-app#7

**Comment by UniversalSuperBox** [comment]
Hi @warriormaster12, thanks for your report!

It's always helpful for us to have different requests or bug reports as separate tickets. That helps us better plan our resources and decide when something is *done*. Also, it seems like your issue has been filed as other issues which are listed by Florian and Rodney.

For those reasons, I will close this ticket. Thanks again for your report.
