### ISSUE TITLE
Lockscreen , lock out user without touching keyboard

### ISSUE THREAD

**Issue by alexjoverton** [ubports/ubuntu-touch#1623]
Device: Xiaomi Redmi Note 7 Channel: devel
- Build: 16.04 13/12/2020
- Fingerprint sensor enabled, text based password setup.

### Steps to reproduce
Reboot > lock screen presented > screen flashes as if I had entered password > 5 failed login attempts >locked out 5 mins

### Expected behavior
should present me with a login but don't have the possibility

### Actual behavior
5 rapid failed attempts without touching screen or sensor, locked out for 5 minutes (well can reboot and it's ok... )
forced reboot. 

### Logfiles and additional information

uSensord  haptic.go:236: Error opening haptic device (not sure if this is relevant ...so including anyway)

**Comment by warriormaster12** [comment]
I can confirm same issue when fingerprint is enabled

**Comment by warriormaster12** [comment]
@alexjoverton the behavior seems to be fixed with update 26

**Comment by alexjoverton** [comment]
@warriormaster12  thanks for the tag, will check this out, and thanks Dev's for your time. Have a nice day . Cheers Alex

**Comment by alexjoverton** [comment]
confirm this is fixed , many thanks.

**Comment by warriormaster12** [comment]
@alexjoverton  it started happening again.

**Comment by Danct12** [comment]
This should now be fixed with the latest devel (172).
