### ISSUE TITLE
Feature request > Terminal > keyboard hide>UX

### ISSUE THREAD

**Issue by alexjoverton** [ubports/ubuntu-touch#1625]
hide keyboard icon . Similar to the one presented in Terminal app to "show" keyboard. This would enable you to hide keyboard when it overlaps information . Currently if I do "top" command in terminal , I see no easy way of seeing all the screen (the keyboard remains)

I believe ios and android have this feature
Thanks

**Comment by Arc676** [comment]
I believe you can dismiss the keyboard by dragging down from the top of the keyboard.

**Comment by alexjoverton** [comment]
@Arc676 Thanks did not realize, its easy enough when you know.. 
This is nice, but maintain that it would be nice to have a simple visual reminder to help transmission from other OS . Also .. I like buttons :-)

**Comment by tank-trax** [comment]
> I believe you can dismiss the keyboard by dragging down from the top of the keyboard.

thanks for this 

however this gesture is not entirely accurate as this has a tendency of also opening the Menu with

```
Select
Copy
Paste
------------
Split horizontally
Split vertically
Close Close view
------------
New tab
Close Close tab
New Window
------------
Cancel
```
this Menu also opens when pressing and holding down on the Terminal window

**Comment by UniversalSuperBox** [comment]
Hi @tank-trax,

You can actually pull down from anywhere on the keyboard, not just the top. If you do this, do you still open the context menu?

**Comment by mateosalta** [comment]
I think we might want to implement the grey bar that has three dots, this would be more uniform with our other slide-able areas (drawer, indicator pannel, sidestage, ect.) give a visual, and be better ux for both touch and mouse interaction

**Comment by UniversalSuperBox** [comment]
Hi @alexjoverton,

I've filed this issue on the terminal-app as https://gitlab.com/ubports/apps/terminal-app/-/issues/96. Please continue any further discussion there.

Any other discussions should be had in new issue reports. Thanks!
