### ISSUE TITLE
Bug (lazy)> fingerprint confirmation page > how to exit > ux

### ISSUE THREAD

**Issue by alexjoverton** [ubports/ubuntu-touch#1626]
Device: Xiaomi Redmi Note 7 Channel: devel

Build: 16.04 15/12/2020 (26)

### Steps to reproduce
add fingerprint >summary success page presented>Stcuk ...a little :-)

### Expected behavior
add fingerprint > summary box confirmation dialog  with little "x" to close > notification disappears > system settings last location redirection>lazy boy happy 

Feature request 
could add link in dialog box > add another fingerprint etc.. 

### Actual behavior
Presented with success page but no way of closing easily.

### Logfiles and additional information
This is less of a bug, because strictly speaking you can close with swipe down after sliding from right edge. But from a UX perspective, someone who is new to this OS may be frustrated and wonder how to get out! Perhaps a simple dialog box rather than a full page. I expect this is WIP so I guess you have this planned anyway.

**Comment by UniversalSuperBox** [comment]
Hi @alexjoverton,

I'm having trouble figuring out on which page of system-settings you are getting stuck. Could you please give me step-by-step instructions to getting stuck?

**Comment by alexjoverton** [comment]
Hi @UniversalSuperBox 
I have just added a new "finger" to my fingerprint dbase. The interface has now been improved with a big green tick and the all important "OK" button at the bottom. This was not present last time I looked. So this bug/UX improvement has been implemented. The "ok" button was not showing, so there was no way of closing the window without swiping down on the open apps view. Hope this makes sense. So as far as I am concerned .. you can close this . Cheers Alex

**Comment by UniversalSuperBox** [comment]
Excellent! Thanks for your feedback. Glad we were able to get this solved.
