### ISSUE TITLE
BUG > Fingerprint >Window close/menu draw sliding> fails

### ISSUE THREAD

**Issue by alexjoverton** [ubports/ubuntu-touch#1627]
Device: Xiaomi Redmi Note 7 Channel: devel

Build: 16.04 15/12/2020 build 26
### Steps to reproduce
set fingerprint as unlocking method> reboot> open apps 

 >navigate to open apps (scroll from right to left screen> window starts to scroll but jumps back to close> cannot select app or close app

>open menu draw > draw opens slightly > then jumps back in place> cannot select 

>navigate to settings >page frozen >no setting selection possible> reboot required

> on reboot > fail > 
>reboot hard reset (hold on button) loads ok

Problems go away if fingerprint lock disabled. 
I notice this behavior before the last update.

### Expected behavior
scroll and close like normal

### Actual behavior
as above

### Logfiles and additional information
haptic.go:236: error opening haptic device
Untrusted0helper ....
critical  main: assertion 'con !=NULL' failed

**Comment by amadeusgoethoven** [comment]
Same problem here. Seems the system is hitting "enter" permanently. Its impossible to dial a number or write a message or open a webaddress in browser. No problems if unlocking with fingerprint is disabled.

**Comment by Flohack74** [comment]
Probably needs this hack: 
https://github.com/fredldotme/android_device_google_bonito/commit/6873b812da8ac697c17fceb02e539e7372b7dd4d
and https://github.com/fredldotme/android_device_google_bonito/commit/974da1c15e14b86f8c24aeafd6bf5e7504c80814

**Comment by Danct12** [comment]
This is now fixed with the latest devel (172).
