### ISSUE TITLE
Feature request > Keyboard > Degree symbol?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1628]
Dear all,
I have noticed that there is no degree (°) symbol on the keyboard. Unless there is an individual option to activate, is it possible to implement this extra symbol?
Thanks,
Best. 

(OTA-14, nexus4)

**Comment by mardy** [comment]
It should be possible, yes. It will probably not be an extra key, but just a secondary symbol available with a long press on some other character. The question now is to decide on which key to put it. I'd propose to add it to the `'` (apostrophe) key, but maybe someone else has a better suggestion.

**Comment by Thieb67k** [comment]
On my desktop's keyboard "°" degree is the secondary symbol of the ")" closing bracket.
I am just used to see that but that could be another character.

**Comment by kugiigi** [comment]
On google keyboard, it is a separate key on the second page of symbols. On HTC keyboard it is in the second layer of `•`. Just a few reference 😄

Since `-` already has a second layer then maybe we can add it to there. Though adding it to ``` is a good idea too since it's the lone second layer and can be easily seen on the key's label.

**Comment by cibersheep** [comment]
Update: On European keyboard is on alt+shift+0

**Comment by Fuseteam** [comment]
confirmed ° can now be typed via the symbols layout
