### ISSUE TITLE
Feature request // disable images in Morph

### ISSUE THREAD

**Issue by Alaraajavamma** [ubports/ubuntu-touch#1634]
Feature request // 
Option to disable images when browsing 

Description of feature //
Option to not load images when browsing in Morph or Webapps
This would save lot of data + as bonus it wil make sites/webapps much faster

**Comment by gbdomubpkm** [comment]
Hi.
I suggest you put your feature request here:
https://github.com/ubports/morph-browser/issues and maybe here https://github.com/timsueberkrueb/webber/issues for webber webapps.

**Comment by UniversalSuperBox** [comment]
This has now been reported as https://github.com/ubports/morph-browser/issues/443
