### ISSUE TITLE
Android secret codes disable?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1636]
Dear all,

I noticed that "secret codes" available on Android are not available (anymore?) on Ubuntu Touch, like: *#*#4636#*#* (Battery status) or *#2663# (Touch screen)...
How to reach those info using the terminal?

Thanks in advance,
Thieb.

- Device: Nexus4
- Channel: stable OTA-15

**Comment by UniversalSuperBox** [comment]
Hi @Thieb67k,

The Android secret codes are ways to access Android-specific debug menus. They do not exist on Ubuntu Touch.

Thanks for your report!

**Comment by Thieb67k** [comment]
Thanks @UniversalSuperBox .
But is there any other way to access (easily - because dummy) to those infos? Via the terminal (how)?
Thanks.
