### ISSUE TITLE
Bacon: Update kernel from 3.4.0 to 3.10.x

### ISSUE THREAD

**Issue by TronFortyTwo** [ubports/ubuntu-touch#164]
Device: Bacon

The device kernel is still at version 3.4.0, while there is the 3.10 version available for it. This I suppose the upgrade should be done with the move to Halium.

**Comment by NeoTheThird** [comment]
Afaik 3.10 is only available in Android 7.1, since the Oneplus One currently is ported to that, porting Halium 5.1 to it for 16.04 will be a lot less work...

**Comment by TronFourtyTwo** [comment]
Sure
