### ISSUE TITLE
no adb authorization on flo

### ISSUE THREAD

**Issue by doniks** [ubports/ubuntu-touch#1646]
- Device: flo
- Channel: rc
- Build: 16.04 2020-W50

### Steps to reproduce
- fresh install on flo 
- (not sure this matters) during initial configuration I selected: just swipe, no pin
- change lock security to 4 digit pin
- enable developer mode
- connect usb cable
- on laptop: adb shell

### Expected behavior
get a confirmation dialog on the device to allow adb connection

### Actual behavior
no dialog on device and
error on laptop:
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
```

### debugging
I tried adb kill-server, toggle dev mode off and on, remove ~/.android folder, add vendor id to ~/.android/adb_usb.ini, but none of that made a difference

I remember that first adb after the installer gave some message about different adb server running or so. I guess that's because the installer brings it's own adb binaries, but I don't think this really matters here. 

with pgrep, ps on the device I see that indicator-display-service and adbd are running. when I pkill adbd I get the notifications on the laptop about newly plugged in device - I think that's the mtp thingy, but nothing changes afterwards

**Comment by doniks** [comment]
huh. after rebooting the device, the authorization request popped up, and now I can adb...

**Comment by just-carlod** [comment]
so maybe close the issue ^^

**Comment by UniversalSuperBox** [comment]
Alright, if it's working now, I think this issue can be closed. Thank you!

**Comment by belohoub** [comment]
Hello all, I experienced it on 2021-W09 - it happens randomly and it is resolved by the device restart.

**Comment by Flohack74** [comment]
Sorry to say, but the chances that this gets fixed on such an old device are rather minimal. We have a limited work force, and we badly need to focus on more modern devices with Android 9, 10 and 11 base to satisfy the need of devices that can be bought as new. Many users want this, and not be required to search for them on the 2nd hand market.

**Comment by belohoub** [comment]
I understand! Sorry for partial information - I forgot to mention, that I've a different device: Xiaomi Mi A2 (jasmine_sprout). On the other hand this is still rc-only.
