### ISSUE TITLE
Number of missed call is displayed instead of name in the notifications

### ISSUE THREAD

**Issue by greskom** [ubports/ubuntu-touch#1648]
- Device: Volla phone
- Channel: stable
- Build: OTA-15

### Steps to reproduce
Receive a missed call form the number stored in contacts.
Open notifications by sliding down the green envelop icon.
Number of the caller is displayed instead of contact name.

Strange this works on BQ Aquaris E4.5 but not on Volla phone.

### Expected behavior
Contact name is displayed.

### Actual behavior
Phone number is displayed.

**Comment by UniversalSuperBox** [comment]
Hello @greskom,

This issue was related to an old version of telephony-service in the Android9 branch of the operating system. The old version has been removed between the release of OTA-15 and now, so this issue will be fixed with the next stable release of Ubuntu Touch.

Thanks for your report!
