### ISSUE TITLE
Dialpad white (unusable) on edge and development Volla 

### ISSUE THREAD

**Issue by stefanomelchior** [ubports/ubuntu-touch#1653]
### Description of the feature

On #239 release of Jan 24th of `development` and `edge` UT for Volla, dial-pad/ofono-telepathy was completely white and unusable.
Inbound calls worked, but there was no way to stop or move to other app meanwhile (GUI frozen).

### Illustrations

[Image](https://t.me/utonvolla/1208)

- Device: Volla (yggdrasil)
- Channel: edge and development
- Build: #239 (edge)

### Steps to reproduce

Just open dial-pad gui

### Expected behavior

To show dialpad as in the stable version (UBports Image part 20201209-10685, Device image part 20201209-32282)

### Logfiles and additional information

Logs [here](http://paste.ubuntu.com/p/4btvmvNzGd/)

**Comment by UniversalSuperBox** [comment]
Hi @stefanomelchior, is this still a problem?

**Comment by stefanomelchior** [comment]
@UniversalSuperBox with `development #243` is not an issue anymore (whilst with #239-240-241 it had been).
I also tried with `edge #343`, and the issues is not present either.
Shall I close the issue?

**Comment by UniversalSuperBox** [comment]
Yes, if it's working now, there's no reason to keep this open. Please let me know if the problem recurs.
