### ISSUE TITLE
Critical - Lavender OTA-15 based seems like press continously enter button

### ISSUE THREAD

**Issue by CristianSw** [ubports/ubuntu-touch#1658]
- Device: Redmi Note 7 (lavender)
- Channel: stable
- Build: OTA-15 installer based version

### Steps to reproduce
I didnt determiante the cause for this case, at the moment i think that this is random action because it appear and dissapear without some actions from my part. System is clear, just apps that are preinstalled

### Expected behavior
System works without this enter pressing or what is it.

### Actual behavior
This problem make system very hard to use, this bug create problems to call dialer, and every text input field, also observed that when watch for ex. video on youtube play/pasue button are press by system for many times. Actual behavior watch in video attached
https://user-images.githubusercontent.com/60692725/107117412-db58d000-6882-11eb-980c-68e19c68bf57.MOV

### Logfiles and additional information
I dont know what of log files to upload, i wait for comments to this case and add necessary log files.

**Comment by UniversalSuperBox** [comment]
Hi @CristianSw,

This issue appears to be the same as https://github.com/ubports/ubuntu-touch/issues/1627. I'll close this report in favor of that one. Thanks for your report!
