### ISSUE TITLE
Call Echo

### ISSUE THREAD

**Issue by drym4rch0n** [ubports/ubuntu-touch#1662]
### Illustrations

- Device: lavender
- Channel:
- Build:

### Steps to reproduce
Make phone call

### Expected behavior
No echo

### Actual behavior
Sounds great for me but the other person hears themselves talking as an echo.

**Comment by fredldotme** [comment]
Maybe call audio distortion and echoes are similar enough to test this command on lavender too: https://github.com/fredldotme/android_device_google_bonito/commit/7e9036d26312cb3171a600d9cd128c422880a017

**Comment by Xray1870** [comment]
I have test this and indeed seems echo is not there anymore add last on my device.

**Comment by Danct12** [comment]
This should now be fixed with version 187 on devel.
