### ISSUE TITLE
Nexus 6P (angler): Front (selfie) camera photos are rotated by -90°

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1665]
- Device: Nexus 6P (angler)
- Channel: devel
- Build: 2021-01-31

### Steps to reproduce
1. Take a picture with the selfie camera

### Expected behavior
Picture has correct orientation

### Actual behavior
Picture is rotated by -90° - Note that videos are oriented correctly.

**Comment by severin-lemaignan** [comment]
I can not reproduce the issue with OTA-16 on Nexus 6p: the selfie pictures are correctly oriented for me.

**Comment by Flohack74** [comment]
True, lets close this ;)
