### ISSUE TITLE
Can't stream on twitch.tv

### ISSUE THREAD

**Issue by uratom962** [ubports/ubuntu-touch#1667]
### Illustrations

- Device: Nexus 5
- Channel:
- Build:  OTA-15

### Steps to reproduce

I can't streaming my camera when I go on Twitch TV: for have live stream with viewers, the phone is too slow. No app for that.

**Comment by UniversalSuperBox** [comment]
Hi @uratom962, thanks for your report!

It is currently impossible to use the camera on the Nexus 5 and many other devices from morph-browser. This problem carries to webapps. You can find the bug report here: https://github.com/ubports/morph-browser/issues/62

Does this sound like the problem you are experiencing?

**Comment by UniversalSuperBox** [comment]
Hi @uratom962, just checking in to see if you received my previous message.

It is currently impossible to use the camera on the Nexus 5 and many other devices from morph-browser. This problem carries to webapps. You can find the bug report here: https://github.com/ubports/morph-browser/issues/62

Does this sound like the problem you are experiencing?

**Comment by UniversalSuperBox** [comment]
Since we haven't heard from you @uratom962, I'll assume this issue is a duplicate of https://github.com/ubports/morph-browser/issues/62. Please let me know if this is an error.
