### ISSUE TITLE
mms sending

### ISSUE THREAD

**Issue by netpipe** [ubports/ubuntu-touch#1670]
https://source.puri.sm/Librem5/chatty/-/issues/30#note_132222

mms not encoding pictures from browser or camera

**Comment by lduboeuf** [comment]
humm are you sure it concern Ubuntu Touch ?

**Comment by netpipe** [comment]
yes, i just noticed when picking them that it does not do the task for me, should there be a preview that shows up or does it just send it automatically ?

**Comment by lduboeuf** [comment]
there is a generated thumbnail that appears in the attachment panel, and disappear when mms is sent
