### ISSUE TITLE
N5 GPS

### ISSUE THREAD

**Issue by maximumhax** [ubports/ubuntu-touch#1672]
- Device: Nexus 5
- Channel: OTA15 stable 16.04
- Build:

### Steps to reproduce

Open unav or pure maps

### Expected behavior

Find my location

### Actual behavior

Just says getting gps

**Comment by UniversalSuperBox** [comment]
Hi @maximumhax,

Ubuntu Touch currently does not correctly use any GPS assistance which is available on some devices, including the Nexus 5. This means that it can take a very long time to receive GPS location data. Have you been able to leave the device, with its screen on, next to a window or other similarly open place for a while to see if location starts working?

After getting a location the first time, subsequent attempts to acquire location should be faster.

You can learn more about this at https://docs.ubports.com/en/latest/userguide/dailyuse/location.html#time-to-first-fix.

Does this help solve the problem you're having with GPS?

**Comment by UniversalSuperBox** [comment]
Hi @maximumhax, were you able to solve your problem with GPS on your Nexus 5?

**Comment by UniversalSuperBox** [comment]
Since we haven't heard from you @maximumhax, I'll close this request now.
