### ISSUE TITLE
Alarm just on headphones when is connected

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1676]
- Device: all
- Channel: all
- Build:

### Steps to reproduce
Set the alarm keep the headphones connected

### Expected behavior
Alarm sound should be on speaker or both headphones and speaker

### Actual behavior
alarm just ring on headphones

**Comment by UniversalSuperBox** [comment]
Hi @rubencarneiro, thanks for your request.

This request is already filed on the clock-app as https://gitlab.com/ubports/apps/clock-app/-/issues/149. If you would like to add more details, please do so there.

Thanks again for your request.
