### ISSUE TITLE
Volla phone cannot send or receive attached photos.

### ISSUE THREAD

**Issue by VOZQ** [ubports/ubuntu-touch#1677]
My new Volla Phone that came installed with ubuntu touch cannot send or receive attached photos.

It does however send and receive text as long as there is no attached photo/image.

It should be sending and receiving any attachment.

When sending a picture, the word "Failed!" appears next to the attached picture. When receiving pictures, there is nothing received.

I made sure the phone is up to date and turn it off and on. So far nothing works.

OS is ubuntu 16.04 (OTA - 15)

A fix would be much appreciated.

Thanx.

**Comment by gbdomubpkm** [comment]
Hello
I am not a developer but i own a Volla :
The first thing is to check is if your operator's APN is correctly filled in:
the path is : system settings / cellular / operator and access point name / acces point name.
The APN must be configured twice: once for the INTERNET and once for the MMS.
Once this is done restart your phone and test.

**Comment by VOZQ** [comment]
I see, thank you, I would have preferred it automatically filled out.

Thank you for your time and efforts.



Feb 28, 2021, 03:13 by notifications@github.com:

**Comment by UniversalSuperBox** [comment]
Hi @VOZQ, were you able to receive picture MMS after setting your APN settings?

Note that there are still problems with MMS receipt on all devices, but you should at least receive a message that MMS retrieval failed if that happens.

**Comment by VOZQ** [comment]
After configuring my APN settings I still was unable to receive pictures. But I can send them now, its something positive.


Mar 1, 2021, 06:14 by notifications@github.com:
