### ISSUE TITLE
qapplication using qtwidgets - example fails with blank screen qt 5.12

### ISSUE THREAD

**Issue by mateosalta** [ubports/ubuntu-touch#1679]
### Description

Wen using qapplication and qtwidgets on dev/5.12, app shows a blank screen.

### Illustrations

- Channel: dev
- Build: 271
-amd64

### Steps to reproduce

build example project: https://github.com/mateosalta/ubuntu-touch-qtwidgets-calculator-demo/blob/master/clickable.json
use on a device with mir

### Expected behavior
example calcuator should show window

### Actual behavior

blank window shown

### Logfiles and additional information

http://paste.ubuntu.com/p/Hy3vN6ZWSk/
(trying  Qt::WA_PaintOnScreen as log suggests ends up with multiple blank windows)

**Comment by dobey** [comment]
This was fixed by ubports/qtubuntu#19 which was opened before this issue was.

**Comment by lduboeuf** [comment]
confirmed fixed, tested wirh Game of life app
