### ISSUE TITLE
Screenshot and camera shutter do not play on Android9 devices

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1684]
- Device: Volla Phone, Pixel 3a
- Channel: rc, devel
- Build: 2021-W10

### Steps to reproduce

Take a screenshot by pressing the Volume Up and Volume Down keys at the same time, or take a picture in the camera app.

### Expected behavior

A shutter sound is played.

### Actual behavior

No shutter sound is played.

### Logfiles and additional information

This issue does not occur on any devices except android9 devices.

**Comment by UniversalSuperBox** [comment]
The default camera click sound is `/system/media/audio/ui/camera_click.ogg`. It's not included on halium 9.

**Comment by amartinz** [comment]
Newer Android versions moved media files to `/product`, which means that this path is broken now.
For devices, which do not have a product partition, it places it in `/system/product` and sets up a symlink `/product` pointing to it.

I have adjusted the AppArmor profiles for media-hub (https://github.com/ubports/media-hub/pull/46) but i still need to figure out where this path is actually set and add a fallback for `/product`.

**Comment by amartinz** [comment]
I found there it got set (qtubuntu-camera) and sent a PR: https://github.com/ubports/qtubuntu-camera/pull/18

However the halium image itself also needs a patch to include the files.
We could just divert from the path Android is going and place it in `/system` instead of `/product`, making above PRs obsolete.

**Comment by amartinz** [comment]
Above PR (https://github.com/Halium/android_vendor_halium_config/pull/1) only fixes it for H10 for the generic builds and device specific builds, which include `vendor/halium/config/halium.mk` in their device tree.

Something similiar still needs to happen for H9.

**Comment by amartinz** [comment]
Alright, we got new sounds here: https://gitlab.com/ubports/core/ubuntu-touch-sounds/-/merge_requests/3

We make use of them in [camera](https://github.com/ubports/qtubuntu-camera/pull/18) and [unity for screenshots](https://github.com/ubports/unity8/pull/411).

**Comment by Flohack74** [comment]
After a bit of settling that should appear in the next 1 or 2 devel images... give it 24hrs or so to build everything ;)

**Comment by gbdomubpkm** [comment]
Is the bug supposed to be fixed in RC 30 on the Volla? If so, I can't confirm that the bug is fixed: no sound when taking a picture or a screenshot (sound activated of course). If the bug isn't fixed in RC 30, that is normal 😉

**Comment by amartinz** [comment]
You may need to wait for a rebuild.
There was an issue with updating the ubuntu-touch-sounds package (version was not bumped and not pulled in because of that).

**Comment by mardy** [comment]
Works fine on Redmi Note 7 using RC 2021 WK36/2. Both on camera app and when taking screenshots.

**Comment by gbdomubpkm** [comment]
The bug seems back to focal OTA-3 (on volla for me only ? ). No  shutter sound when taking a photo. No vibration too. Shutter sound works when taking a screenshot.

**Comment by lduboeuf** [comment]
no issue on P3a deve
