### ISSUE TITLE
<approot>/bin is not in PATH when launching click apps 

### ISSUE THREAD

**Issue by nicolasfella** [ubports/ubuntu-touch#1687]
- Device: PineTab
- Channel: Development
- Build: https://ci.ubports.com/job/rootfs/job/rootfs-pinetab-systemimage/53/

Traditional Linux apps typically install their executable to <prefix>/bin, e.g. /usr/bin/alligator and have something like `Exec=alligator` in their .desktop file.

When packaging the app as click this won't work since <approot>/bin is not in PATH when launching, only <approot>/lib/<arch-triplet>/bin and <approot> are.

This can be worked around by either changing the install dir for the executable or adding `Exec=bin/alligator` to the desktop file, but both would require Ubuntu Touch-specific changes in the build system.

Adding <approot>/bin to PATH when launching a click would make things work out of the box, which would be greatly appreciated by app developers.

**Comment by nicolasfella** [comment]
This would not only help the case of packaging existing Linux apps for click but also the case of packaging Ubuntu Touch apps for other Platforms (Manjaro ARM, postmarketOS etc.)

Currently Ubuntu Touch apps seem to install their executables to / (https://gitlab.com/ubports/apps/teleports/-/blob/master/CMakeLists.txt#L85). If apps would install it to <prefix>/bin instead this would greatly improve the ability to package them for more traditional Linux distros

**Comment by dobey** [comment]
This is intentional, because a click package can contain binaries for multiple architectures, so the executable should be installed to `lib/${ARCH_TRIPET}/bin/` instead, which _is_ in `${PATH}`.

Ubuntu Touch isn't a traditional PC Linux distribution, and so it is acceptable that some things may need to be changed when porting traditional apps over. In particular, apps may also need to be modified to deal with the restrictions of apparmor confinement, as they may try to write to locations which they normally can on traditional distributions where they are not confined.

**Comment by dobey** [comment]
> Currently (some) Ubuntu Touch apps seem to install their executables to / (https://gitlab.com/ubports/apps/teleports/-/blob/master/CMakeLists.txt#L85). If apps would install it to /bin instead this would greatly improve the ability to package them for more traditional Linux distros

For specific cases like this, I'm sure patches would be appreciated. I'm sure some of the stuff in teleports could probably be simplified as well.

**Comment by UniversalSuperBox** [comment]
@dobey, would we accept patches which added `bin/` to PATH, or is this WONTFIX?

**Comment by dobey** [comment]
> @dobey, would we accept patches which added `bin/` to PATH, or is this WONTFIX?

I think this is probably WONTFIX for a general solution, but I think it would be acceptable to propose changes to the Teleports CMake files in order to build a traditional layout package following the standard hierarchy in Debian/etc… there.

**Comment by nicolasfella** [comment]
From a CMake POV the proper thing to do would be using `CMAKE_INSTALL_BINDIR` for everything. Then the caller can override it to whatever it needs. That could be done in the clickable.json or in clickable itself. In any case _something_ has to be adjusted, and IMO a solution that automatically benefits all apps would be preferrable
