### ISSUE TITLE
is there a ubuntu touch port for Samsung Galaxy A20e

### ISSUE THREAD

**Issue by Xellerate005** [ubports/ubuntu-touch#1692]
just want to know if there is a developer/porter out there that can or willing to do it or if theres a port of it already, seems like theres not even any roms for this phone

**Comment by UniversalSuperBox** [comment]
Hi @Xellerate005,

You can find our list of supported devices at https://devices.ubuntu-touch.io. If your device is not there, you can learn more about porting Ubuntu Touch to your device at https://docs.ubports.com/porting/
