### ISSUE TITLE
Missing python and other libs on rootfs

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#1698]
Missing python on android9-rootfs
Nor python 2 or 3 on rootfs.
Also no libopenal so a lot things is missinh on android9 rootfs. Including sound effects for camera "audio files"

**Comment by dobey** [comment]
Why do you think python3 isn't installed? it most certainly is, as `system-image` at the very least requires it. Did you change your rootfs to r/w mode and do something to cause it to get removed, perhaps?

**Comment by rubencarneiro** [comment]
> Why do you think python3 isn't installed? it most certainly is, as `system-image` at the very least requires it. Did you change your rootfs to r/w mode and do something to cause it to get removed, perhaps?

At least not on android9rootfs of the pixel 3a , when i run python --version, cannot find python, so i sudo mount -o remount,rw / && sudo apt update && sudo apt install python3-all-dev after sudo ln -s /usr/bin/python3.5 /usr/bin/python now i have python installed.

**Comment by dobey** [comment]
Yes, `python` is not the binary for `python3`. You must run it as `python3`. The `python` executable in Ubuntu and Debian is only for Python 2.x.

**Comment by rubencarneiro** [comment]
I can confirm python3 is istalled by default, what about openal, seems like supertux2 does run on pixel 3a , strange it does run o volla that also uses android9rootfs. But app fail to run with missing shared libopenal lib.

**Comment by dobey** [comment]
OpenAL is not installed in the rootfs in Ubuntu Touch on any device. There is nothing special about android9 in this case. There is a separate issue for the camera sound on android9 devices. If SuperTux needs OpenAL, it should be included in its click package.

Closing this as it is not an issue with Ubuntu Touch.
