### ISSUE TITLE
Cant connect Google account: browser not supported

### ISSUE THREAD

**Issue by Jan-ops79** [ubports/ubuntu-touch#1707]
### Illustrations

- Device:Xiaomi Mi A2
- Channel:Accounts
- Build:OTA16

### Steps to reproduce

Connect Google account to calendar: error that Google doesnt support browser.

**Comment by UniversalSuperBox** [comment]
Hi @Jan-ops79, thanks for your report!

This issue is already filed as https://github.com/ubports/account-plugins/issues/40. Please continue any further discussion there.

**Comment by Jan-ops79** [comment]
Thx for the quick answer! The fix worked!
