### ISSUE TITLE
Camera issues on Xiaomi Mi A2

### ISSUE THREAD

**Issue by Jan-ops79** [ubports/ubuntu-touch#1711]
- Device:Xiaomi Mi A2
- Channel:Stable
- Build:OTA16-Jasmine Sprout

### Steps to reproduce

Pictures are clear without zooming in, when you take a picture a and use a little to max zoom, pictures become granular.
Wehn using video mode image freezes on screen and counter goes until pressed stop. App doesnt reapond, when swiping right you can see a video file in black that wont play.
(maybe, because when go to video mode, allowed sound recording?)

About zoom issue: feature request?

### Expected behavior

Just taking normal fotos and videos.

### Actual behavior

Fotos ok, until zoom. 
Video capture freezes.

**Comment by Jan-ops79** [comment]
Extra: video recording only works on frontcamera.

**Comment by UniversalSuperBox** [comment]
Hi @Jan-ops79, thanks for your report.

I'm unable to fully understand your requests from what you've given us here. Additionally, trying to track multiple issues in one post is very difficult for us; it makes it impossible to schedule a single task out of the two that you've requested.

Could you please create separate issue reports for each problem you are experiencing, possibly with photos attached to show us what you mean? That would be extremely helpful as we try to fix these issues.

I'm going to close this report as we're unable to manage it with multiple issues in one post. If you are still experiencing the problems, please make a separate post for each.

Thanks again for your report.

**Comment by Jan-ops79** [comment]
Ok thanks for the feedback! I just made 2 separate issues.
