### ISSUE TITLE
Please make ubuntu touch for samsung j8!

### ISSUE THREAD

**Issue by Darklord071** [ubports/ubuntu-touch#1714]
Can anyone build ubuntu touch for j810g Please? I have a huge need for it urgently..

**Comment by UniversalSuperBox** [comment]
Hi @Darklord071,

You can find our list of supported devices at https://devices.ubuntu-touch.io. If your device is not there, you can learn more about porting Ubuntu Touch to your device at https://docs.ubports.com/porting/

Someone who owns the device must be the one who creates the port.
