### ISSUE TITLE
Ship image with davfs2 pre-installed to allow mounting WebDAV files

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#172]
With davfs2 installed, syncing files with Nextcloud or WebDAV servers would be a lot easier. This would allow for easy creation of click apps to handle the configuration.

**Comment by mariogrip** [comment]
Fix pushed https://github.com/ubports/ubuntu-touch-meta/commit/d63457249176714604ce24d043e2d6ddb589ec1e

**Comment by Flohack74** [comment]
Please close only after QA approved, thats the new workflow ;)
