### ISSUE TITLE
Unable to ping Ubuntu Touch in LAN

### ISSUE THREAD

**Issue by ravikv123** [ubports/ubuntu-touch#1721]
### Illustrations

- Device: hammerhead
- Channel: stable
- Build: OTA-16

### Steps to reproduce

Unable to ping or ssh when devices are connected in LAN.
Able to adb shell when device is connected via USB.

### Expected behavior

Should be able to ping with in LAN network

### Actual behavior

Getting timeout error.

### Logfiles and additional information

![image](https://user-images.githubusercontent.com/43967054/116094229-fa6a3f80-a6c4-11eb-971e-0f971304063d.png)
![image](https://user-images.githubusercontent.com/43967054/116095134-c04d6d80-a6c5-11eb-8ae9-841e8138f402.png)
![image](https://user-images.githubusercontent.com/43967054/116094397-1f5eb280-a6c5-11eb-94c8-0cb2f2774fa1.png)

**Comment by ravikv123** [comment]
Looks to be my LAN issue... resolved...
thankyou

**Comment by Anas-Sherif** [comment]
> Looks to be my LAN issue... resolved... thankyou

Hi, can you share how you solved it? I'm having the same issue.
