### ISSUE TITLE
Nexus 4 16 GB only showing 9 GB storage size

### ISSUE THREAD

**Issue by dnisbetjones** [ubports/ubuntu-touch#1735]
Using the UBPorts installer 0.8.8 on my 16 GB Nexus only allocates 9 and leaves me with just 4 free. I don’t remember this happening last time I installed Ubuntu Touch on this device. Let me know how I can help troubleshoot.

**Comment by Flohack74** [comment]
Please check in recovery with adb how much space is really free. The calculation is often misleading. For example, old devices have 2 files system.img and ubuntu.img with both approx 3GB, but in fact one is a hardlink to the other, consuming no space. But our size tool in system settings might count them both.

**Comment by dnisbetjones** [comment]
Hi there, thanks for the reply. I went poking around and `df -H` spits out the following:


udev                            960M  4.1k  960M   1% /dev
tmpfs                           193M  771k  192M   1% /run
/dev/mmcblk0p23                 6.1G  2.0G  3.9G  34% /userdata
/dev/loop0                      2.1G  1.8G  258M  87% /
/dev/loop1                      164M  163M  349k 100% /android/system
none                            4.1k     0  4.1k   0% /android
tmpfs                           962M  4.1k  962M   1% /etc/fstab
tmpfs                           962M  975k  961M   1% /var/lib/lxc/android/rootfs
/dev/disk/by-partlabel/cache    579M   11M  569M   2% /android/cache
/dev/disk/by-partlabel/persist   17M  4.4M   13M  27% /android/persist
/dev/disk/by-partlabel/modem     68M   56M   12M  84% /android/firmware
none                            4.1k     0  4.1k   0% /sys/fs/cgroup
tmpfs                           962M   13k  962M   1% /tmp
none                            5.3M     0  5.3M   0% /run/lock
none                            962M  181k  962M   1% /run/shm
none                            105M     0  105M   0% /run/user
cgmfs                           103k     0  103k   0% /run/cgmanager/fs
tmpfs                           962M     0  962M   0% /media
tmpfs                           962M     0  962M   0% /var/lib/openvpn/chroot/tmp
tmpfs                           962M     0  962M   0% /var/lib/sudo
tmpfs                           193M     0  193M   0% /run/user/0
tmpfs                           193M   46k  193M   1% /run/user/32011

So it looks like the whole 16 GB is there but it's just not appearing that way. I'm still confused as to how much actual storage there is available to the user but I think you answered my question. Thanks!
