### ISSUE TITLE
Brick Phone, no valid slot to boot

### ISSUE THREAD

**Issue by FireGod13** [ubports/ubuntu-touch#1738]
I have re-loaded ubuntu touch x3 times on a Pixel 3a and the unit is not loading into the OS.
The unit only goes to the recovery screen once process is completed.

After restart the fastboot comes up and says

"no valid slot to boot"

I have previous experience with the Nexus 5, just thought to upgrade to a pixel 3a for the bump in hardware.

I have attached photos as my comprehension level to fix issues of this nature is very limited.
![PXL_20210523_001202845](https://user-images.githubusercontent.com/84648054/119244520-8bef9480-bb3f-11eb-876a-7b1349039a7a.jpg)
![PXL_20210523_001047856](https://user-images.githubusercontent.com/84648054/119244521-8db95800-bb3f-11eb-84f5-2de0e05ecba7.jpg)
![PXL_20210522_232727351](https://user-images.githubusercontent.com/84648054/119244525-901bb200-bb3f-11eb-9385-1ca96c8f921d.jpg)

**Comment by FireGod13** [comment]
Only thing I can think of is that i didn't check what version of android i was on before doing the process... I noticed that it required downgrade.

Would this be my issue?

**Comment by fredldotme** [comment]
You definitely need to follow the instructions, including the downgrade to Android 9 carefully.

Before doing the downgrade though you will need to download the platform tools for Android from Google's website (which contain newer fastboot and adb binaries than available in Ubuntu archives), and run the `flash-all.sh` with that.

You can also switch the boot slot using the `fastboot` tool. To do this run `fastboot --set-active=a` to switch the boot slot to A. Change the command to switch to B if necessary.

After the downgrade you can try the UBports Installer again.

**Comment by Flohack74** [comment]
Alos, you might need to format the encrypted userdata partition.

**Comment by FireGod13** [comment]
Using the flash.android.com site... Trying that now...

I will redo the UBports after this is done... Thank you Thank you Thank 
You!!!


I will update, your advise and guidance is most appreciated!

**Comment by FireGod13** [comment]
It worked!!! OMG thank you!!!

It was the updated version of Android I was on...

you are amazing Alfred, keep helping the noobes like me please... It is 
so appreciated!!!!

By Google and Apple !!! finally free!!!

Brett
