### ISSUE TITLE
Wifi asks for password and drops connection at least once a day

### ISSUE THREAD

**Issue by wagafo** [ubports/ubuntu-touch#1745]
### Illustrations

- Device: Volla
- Channel: Stable
- Build: OTA-17

### Steps to reproduce

Connect to WIFI

### Expected behavior

The connection should stay until we go out of the network reach or disable WIFI

### Actual behavior

At least once a day, my Volla asks for the WIFI password. Clicking cancel and connecting to WIFI it connects again and it stays connected for many hours, but before 24 hours it will ask for password again.

**Comment by wagafo** [comment]
Somebody reported the following workaround:
`nmcli connection modify PROFILE 802-11-wireless.mac-address WIFI_MAC_ADDRESS
nmcli connection modify PROFILE connection.interface-name wlan0`

where PROFILE is the connection name (SSID of the Wifi Network) and WIFI_MAC_ADDRESS is the MAC ADDRESS of the wifi device (can be obtained with "ifconfig" and check HWadress for wlan0).

I've applied this work around and I will tell if this fixes the dropping of the WIFI connection.

**Comment by wagafo** [comment]
It still drop the connection, but with the above commands, it does not ask for the password again.

**Comment by cyrneko** [comment]
I wasn't able to reproduce this on my OnePlus 5T so far, I'd assume that it is a device-specific issue 🤔

**Comment by Flohack74** [comment]
It can be device-specific if the device has no stable MAC address setup in the port. But it also can happen when you reach a WiFi "just so" but it cannnot log in multiple times. We tried to improve the situation but it is still not perfect. But we need feedback from more devices, especially the Vollaphone.

**Comment by luksus42** [comment]
In the past, I experienced this issue sometimes on the FP3. I could just dismiss the prompt and connect to wifi again without entering credentials again.
This did not happen in the last month anymore (dev) so I would confirm this as fixed.

**Comment by Flohack74** [comment]
I close this @luksus42 the only additional problem I see is now that the WiFi should maybe retry forever to connect to a known network. After all, if you are on the edge of reception (you are coming closer to your home with the phone in your pocket e.g.) then it might be that multiple tries fail, and the phone gives up. But IMHO it shouldnt.
