### ISSUE TITLE
Audio is routing to headphones when not using headphones

### ISSUE THREAD

**Issue by gibcheesepuffs** [ubports/ubuntu-touch#1746]
- Device: Xiaomi Mi A2, Fxtec Pro1
- Channel: devel
- Build: 409 (Mi A2)

### Steps to reproduce
Method 1: After booting wait for some time.
Method 2: Make or receive a phone call and then end the call.

### Expected behavior
Audio should keep working/routing through the main speaker.

### Actual behavior
Audio starts routing to headphones.

### Logfiles and additional information (Mi A2)
`phablet@ubuntu-phablet:~$ apt policy audiosystem-passthrough
audiosystem-passthrough:
  Installed: 1.0.0+0ubports1+0~20210529172459.4~1.gbp6cc52e
  Candidate: 1.0.0+0ubports1+0~20210529172459.4~1.gbp6cc52e
  Version table:
 *** 1.0.0+0ubports1+0~20210529172459.4~1.gbp6cc52e 2000
       2000 http://repo.ubports.com xenial/main arm64 Packages
        100 /var/lib/dpkg/status
     1.0.0+0ubports1+0~20200501204628.2~1.gbpe44197 2000
       2000 http://repo.ubports.com xenial/main arm64 Packages`

**Comment by UniversalSuperBox** [comment]
It appears that, on android9 devices, there is an audio sink called `output-a2dp_headphones`. This sink, along with *all* of Android's provided sinks, is always set as available.

https://github.com/ubports/telephony-service/pull/21 fixed audio routing on devices where the default hardcoded values didn't work correctly. It did this by looking for sinks with names like `*headphones*` and `*earpiece*` which are available on non-Android devices. The new comments in the code state that this detection does not override previous detection of the hardcoded values.

The comments might be lying. I'm not sure yet. I'm having trouble reasoning through the path of the code without having more information and a better look.

The exact issue might be in https://github.com/ubports/telephony-service/pull/21/files#diff-0130ea1ee57b6fd3e170a095898861ac4477dc0b4ce9e011c094bab607901abfR743. Still, not sure.
