### ISSUE TITLE
Auto brightness stopped working

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#1747]
- Device: Xperia X
- Channel: dev
- Build: 419

### Steps to reproduce
Enable auto brightness (it doesn't matter whether this is done via system settings or the pulldown menu). Expose the device to light or to darkness.

### Expected behavior
The brightness adapts to the environmental brightness.

### Actual behavior
The brightness does not change at all.

### Logfiles and additional information
After a `sudo stop repowerd && sudo env REPOWERD_LOG=console repowerd`:

On enabling auto brightness:
```
[2021-06-12 01:08:59.277885] DefaultStateMachine[c1]: handle_user_activity_extending_power_state
[2021-06-12 01:08:59.405772] UnityScreenService: dbus_userAutobrightnessEnable(enable)
[2021-06-12 01:08:59.408785] DefaultStateMachine[c1]: enable_autobrightness
```
Then no further log messages.

**Comment by ruedigerkupper** [comment]
Confirming the problem and the logs as described above.

**Comment by lduboeuf** [comment]
confirmed N5 devel

**Comment by wilfridd** [comment]
Hi, same issue on Meizu PRO5 and MX4
Best,
W.

**Comment by MenmuirMark** [comment]
Same issue on OPO, rc.

**Comment by Openanonwriter** [comment]
Confirmed with pixel 3a, RC 2021-W24

**Comment by MenmuirMark** [comment]
> Same issue on OPO, rc.

and on my N5, rc

**Comment by UniversalSuperBox** [comment]
I can confirm this issue. This now blocks the release of Ubuntu Touch OTA-18. It must be resolved for the release to continue.

**Comment by Openanonwriter** [comment]
RC OTA-18 Did not did not fix this issue for pixel 3a

**Comment by Flohack74** [comment]
Yes please do not post "still not working" messages, we will notify here when it can be tested again...

**Comment by Openanonwriter** [comment]
> Yes please do not post "still not working" messages, we will notify here when it can be tested again...

I removed my message, I do apologize, about that. .

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/core/repowerd/-/merge_requests/31

**Comment by ruedigerkupper** [comment]
Yeah! Thank you!

**Comment by terrorzelle77** [comment]
Hello,
since some weeks auto brightness on Volla Phone isn't working further. 
Reboot not helps. 

So much months everything was ok. 
I think it's since version 443 on the DEV-Channel. 

Is this problem known? Someone works on a fix?

Best regards

**Comment by stekalb** [comment]
I can confirm it's an issue again on current volla dev images

**Comment by stekalb** [comment]
It seems to be no issue on mx4, bq e4.5 (both on dev) and opo on halium-dev.
In some tg-chat an other user mentioned he is also affected on a different halium9/64bit device.

**Comment by mattbel10** [comment]
It doesn't work either on my Pixel 3a, Halium 9 device, devel channel.

**Comment by stekalb** [comment]
According to sensorsstaus app light sensor works on dev

**Comment by Flohack74** [comment]
@stekalb a) proximity sensor is different to light sensor and b) Its not sufficient to test if it works with sensorsstatus app, you must do a call and see if the display goes black when you come closer with your face or palm of your hand :) I reopen this.

**Comment by stekalb** [comment]
Also got a confirmation on TG for not working in OP 6T either.

**Comment by lduboeuf** [comment]
auri brightness works on N5 devel

**Comment by UniversalSuperBox** [comment]
Should be fixed by a force-push to https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9 (old version was https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9-before-aug-2021-rebase). Will take another day before it lands in images.
