### ISSUE TITLE
Speaker stays on during call, can not turn off.

### ISSUE THREAD

**Issue by Openanonwriter** [ubports/ubuntu-touch#1750]
- Device: Pixel 3a (Sargo)
- Channel:  RC 
- Build: 2021-W24

Once you make a phone call and hit speaker the phone call stays on speaker, even if you take it off. 

### Steps to reproduce
1. Make Call
2. Place call on speaker
3. Take phone off of speaker. 

### Expected behavior
Once off of speaker you phone should go back to using the ear peace built in to the phone. 

### Actual behavior
Speaker stays on, whole café can hear your conversation. Fun times. 
Also audio from the device does not work after, and you must restart the phone.
### Logfiles and additional information
Photos posted here. 
https://forums.ubports.com/topic/6307/speaker-phone-will-not-turn-off?_=1623893861828

**Comment by Openanonwriter** [comment]
Video of this happening, let me know the logs you need. https://youtu.be/R4SMCwhaIyg

**Comment by captainzer0** [comment]
This seems related. I'm RC channel, Pixel 3a, my phone does not get the volume stuck on but leaves the phone in headphone mode with no sound until I either restart the phone our plug in and then remove earbuds from the headphone jack.

**Comment by Openanonwriter** [comment]
**Fixed with OTA-18**
