### ISSUE TITLE
Pixel 3a does not show 5Ghz WIFI network in settings. 

### ISSUE THREAD

**Issue by Openanonwriter** [ubports/ubuntu-touch#1754]
- Device: Pixel 3a (Sargo)
- Channel: RC
- Build: 2021-W24

No 5GHz shows up to connect to using the pixel 3a. 

### Steps to reproduce
1.) look for WIFI networks in settings of Ubuntu Touch
2.) Notice only 2.4Ghz networks
3.) Open network mon and see 5GHz networks 
4.) Scratch Head

### Expected behavior
1.) look for WIFI networks in settings of Ubuntu Touch
2.) See 5ghz Network
3.) Select Network
4.) Use Network

### Actual behavior
No 5Ghz wifi

### Logfiles and additional information
What logs do you need?

**Comment by fredldotme** [comment]
I can't reproduce that, sadly. I'm in a crowded area with plenty of 5Ghz APs available, also my main connection goes through 5Ghz. It would be interesting to check kernel logs and maybe find details about NetworkManager.

**Comment by Openanonwriter** [comment]
Issue resolved. My own stupidity caused this.
