### ISSUE TITLE
Lost the ability to recive sms and mms

### ISSUE THREAD

**Issue by Openanonwriter** [ubports/ubuntu-touch#1758]
Phone: Pixel 3a
Channel: RC ota 18
Cycle: 2021-w25

Issue: I can no longer recive SMS/MMS. Restarted phone several times, sent 7 messages and 3 MMS. 

No message has arrived, but im able to send.
___
Steps to reproduce: Update to rc ota-18 
send sms to phone
___
what should happen: recive sms/mms
____
Logs- Let me know what logs you want.

**Comment by UniversalSuperBox** [comment]
Hello @Openanonwriter,

Which carrier is your Pixel 3a on?

**Comment by Openanonwriter** [comment]
Im on mint mobile, worked just fine before update. They are an mnvo of t-mobile. SMS/MMS/Data/calling worked before update

**Comment by Openanonwriter** [comment]
I reset all APN setting, selected 2G and then rebooted, then went back to LTE and now im reciving and sending.
