### ISSUE TITLE
Request: Missing Khmer fonts from system

### ISSUE THREAD

**Issue by pagnchanak** [ubports/ubuntu-touch#1759]
### Include Khmer fonts to system out of the box
Khmer fonts are not presented on the system (it's normally come out of the box for other OSes e.g. iOS, Android, including Ubuntu)

### Steps to reproduce
Try to read below texts from Ubuntu Touch, they are written in Khmer unicode font:
Khmer texts: អក្សរសម្រាប់សាកល្បងអាន

### Steps to resolve
sudo mount -o rw,remount /
sudo apt update && sudo apt install -y fonts-khmeros fonts-khmeros-core

**Comment by cibersheep** [comment]
Device: Arale
Channel: RC 2021-W45
Result: Text is visible in Morph

![imatge](https://user-images.githubusercontent.com/6640041/141338484-ff098e21-dbf0-408e-9b72-4e0cecf3b8b5.png)
