### ISSUE TITLE
reattempt download of MMS logic is ineffective

### ISSUE THREAD

**Issue by laubster** [ubports/ubuntu-touch#1761]
- Device: nexus4
- Channel: release candidate
- Build: 105

### Steps to reproduce
(I'm testing the proposed "reattempt download" logic if cellular data is disabled when an MMS arrives.)
Change to Release Candidate channel, then verify you can send a png via MMS to yourself. Also verify the stable branch functionality of "have sender resend" message by quickly disabling cellular data after sending is complete but before receipt occurred. Next, follow the steps at https://forums.ubports.com/topic/5100/the-mms-lost-story/124 .

### Expected behavior
MMS messages should be delivered when cellular data is enabled.

### Actual behavior
I always get the "tap the download button to try again" message when I send myself an MMS, even when cellular data is enabled. (SMS works fine.) The "download" button seems to do nothing but buzz the phone after 4 seconds or so.

### Logfiles and additional information
nuntium log reports:
2021/06/27 22:39:33 Starting download of http:[...] with proxy [...]
2021/06/27 22:39:36 Download issues:
2021/06/27 22:39:37 Received unknown method call on org.ofono.mms.Message MarkRead
2021/06/27 22:39:37 message [...] is not responded and not expired, not deleting.

**Comment by lduboeuf** [comment]
do you receive or send MMS usually without issue when cellular data is on  ?

**Comment by laubster** [comment]
After a reboot while on the stable branch - and before I applied the 5 "ubports-qa install" commands on the RC branch - yes, I could successfully send & receive a small png file to myself.

(It's likely unrelated, but I have noticed that after a few days uptime, at some point I'd start receiving the "have sender resend" notice instead of an actual MMS, even when cellular data was on. I usually receive very few MMS messages - perhaps a couple a month - so it hasn't yet caused enough annoyance to report. A reboot gets it working again.)

**Comment by lduboeuf** [comment]
ok, there can be some many case where a MMS could not be retrieved  that it is hard to know if the new feature is the cause or would happen in previous case. 
@jezek ( the author of this new feature ) is not available now, but he will be noticed of that issue

**Comment by jezek** [comment]
I've stumbled upon the empty "Download issues:" log right from the start of the work on the re-download issue. I'm pretty sure it was there before.

In code the log is written directly after ```MNotificationInd.DownloadContent(...)``` function. I don't know why it happens, I didn't debug it, nor touched the download logic. I think the function calls some C code to download MMS and sometimes it fails and returns empty error. It sometimes occurred when testing on localhost with ```nuntium-inject-push``` tool, if I recall correctly

**Comment by UniversalSuperBox** [comment]
Is there any reason to keep this report open? Seems like it should be discussed in the relevant PRs or on a forum post as directed by @jezek.

**Comment by laubster** [comment]
Closing per @UniversalSuperBox proposal.
