### ISSUE TITLE
Xiaomi Pocofone F1

### ISSUE THREAD

**Issue by MarkusM1966** [ubports/ubuntu-touch#1763]
Hi,
ich habe am Sonntag auf meinem **Xiaomi Pocofone F1** Ubuntu Touch aufgespielt. 
Die Installation ... naja, nach einigen Anläufen hat es dann geklappt. Habe eben noch nie ein anderes OS auf ein Smartphone aufgespielt.
Vom ersten Kontakt mit Ubuntu Touch war ich begeistert und bin es immer noch. Sehr übersichtlich und intuitiv zu bedienen. . Auch wenn die Auswahl an App´s für einen Android - User nicht gerade üppig erscheint, sind eigentlich alle "grundlegenden" Apps vorhanden. Wer braucht da schon Android oder Apple?
**Inzwischen zeigen sich aber die ersten Probleme:**
1. Der Start wird mindestens 1 x abgebrochen, beim Neustart funktioniert das System dann aber ohne Probleme.
2. Der Akku-Verbrauch ist **deutlich** zu hoch. Gegen 08:00 zuletzt vollgeladen (100%), 14:36 Uhr Ladezustand 36 %. 
Unter Android hielt der Akku fast 48 Stunden.
3. Beim "liebgewonnenes" SIGNAL funktioniert nicht - das ist aber ein MUSS.
Kann mir jemand sagen, wie ich zumindest die ersten beiden Probleme beheben kann?

Viele Grüße
Markus

P.S Mein Englisch ist ein wenig eingerostet, daher gerne auf Deutsch.

### Illustrations

- Device:
- Channel:
- Build:

**Comment by svenha** [comment]
> Signal

Have you tried Axolotl from the Open Store?
