### ISSUE TITLE
Broken dependency tree for ubuntu-touch-core, repowerd-data when apt-get upgrade

### ISSUE THREAD

**Issue by devbrones** [ubports/ubuntu-touch#1765]
- Device: Nexus 6P
- Channel: 
- Build: 16.04-arm64-hybris-stable

### Steps to reproduce

Bug occures during various apt commands, i.e sudo apt-get upgrade, sudo apt-get -f install, etc.

### Expected behavior

Usual apt behavior, dependencies should be fixed with apt-get install -f, but rather dpkg returns an error.
When i try to force overwrite the repowerd package, i get  `invalid cross device link`

### Actual behavior

see https://pastebin.com/1ZmFyUBg

**Comment by fredldotme** [comment]
Using `apt` to update your device and install software is not officially supported,
because it breaks expectations of our image-based upgrade mechanism and software delivery.
The expected behavior is not part of our goals.

**Comment by UniversalSuperBox** [comment]
Hi @devbrones, thanks for your report.

The only way we agree to support upgrading the system is via the built in `system-image` utility. This utility will download the changes to full Ubuntu Touch system images (a "delta update"), if possible, and install them using an upgrader in the device's recovery. If a delta update is not possible, it will download a new system image and install that (a "full update"). Any changes you have made to the system using `apt` or an app like uAdBlock will be overwritten if a full update is used.

You may be able to get apt working by unmounting the bind-mounted files which are causing problems with the upgrade. However, be warned that you are in uncharted waters and if anything breaks on your device, you will have to keep the pieces and recover yourself.
