### ISSUE TITLE
Duplicated icons with anbox

### ISSUE THREAD

**Issue by olgabaranov** [ubports/ubuntu-touch#1767]
- Device: Nexus 5
- Channel: rc
- Build: Ubuntu 16.04 LTS - armhf (20210628)

### Steps to reproduce
Activate anbox and install an app (later might not be necessary)

### Expected behavior
You can now see the  general android apps and whatever you just installed

### Actual behavior
Android apps are present multiple times, the number changes upon restart and other random activity on the phone

### Logfiles and additional information
![screenshot20210704_130826717](https://user-images.githubusercontent.com/8818141/124383324-2fe66700-dccc-11eb-886a-bfc84a7a7aae.png)
![screenshot20210704_131116550](https://user-images.githubusercontent.com/8818141/124383327-31179400-dccc-11eb-8eea-12c642409b8f.png)

**Comment by olgabaranov** [comment]
Resolved with the most recent update. Thank you!

**Comment by olgabaranov** [comment]
Have to reopen it, after restart nr. 4 the issue is back again. Can I provide any helpful logs?

**Comment by olgabaranov** [comment]
Did it work?

**Comment by SevralT** [comment]
OnePlus 6/6T on stable, rc and devel channels have this problem too.

**Comment by Flohack74** [comment]
This is old Anbox and will not be fixed anymore. Migration to Waydroid will solve all those issues...
