### ISSUE TITLE
Please add qml-module-qtwebview and libqt5webview5-dev

### ISSUE THREAD

**Issue by mzanetti** [ubports/ubuntu-touch#1769]
### Description of the feature
Please add qml-module-qtwebview and libqt5webview5-dev to the SDK so apps can make use of it. On Linux, qt webview uses qtwebengine as a backend which already is available. So it should be a matter of just running the webview wrapper through dpkg.

I am aware that there are already means of displaying a WebView in Ubuntu Touch apps (e.g. by directly using the already provided QtWebEngine qml component), but for compatibility with other platforms supporting Qt, the upstream Qt WebView would come in very handy so apps don't need to be patched for this. I.e. QtWebEngine is not available on Android and iOS which is exactly the problem Qt WebView solves by wrapping it in a backend independent manner.

**Comment by dobey** [comment]
The packages are now included in the rootfs image along with 16..04.7 framework version, which will be required for using QtWebView imports. The [PR for click-reviewers-tools](https://gitlab.com/clickable/click-reviewers-tools/-/merge_requests/10) is still pending, but as soon as it gets merged and deployed, it should be possible to upload an app to the open store using the new framework version and import.

**Comment by dobey** [comment]
The review tools PR was merged, so should now be possible to use the `ubuntu-sdk-16.04.7` framework, Closing this issue now.
