### ISSUE TITLE
libgles2 is not available in the arm64 repository

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch#1771]
The `libgles2` package is not available to be installed from the arm64 repository. It is however, available in the armhf repository as seen in the clickable docker image build logs: https://gitlab.com/clickable/clickable-docker-images/-/pipelines/334004630

Including libgles2 there is an effort to support a new [godot template](https://gitlab.com/clickable/ut-app-meta-template/-/merge_requests/29) that is in the works.

**Comment by fredldotme** [comment]
I wonder where that `libgles2` package comes from. It's certainly not provided by libhybris.
In a focal world that is provided by libglvnd, which is the vendor-neutral dispatch library for all things OpenGL.

Do you know where this libgles2 comes from, which source package it's built from?

**Comment by fredldotme** [comment]
Oh wait, I see `libGLESv2.so.2` being provided in the `libhybris-egl` directory, by the `libhybris` package.
It could certainly be used by the build system, assuming one makes an unversioned symlink to it.

**Comment by dobey** [comment]
I would guess that what you want to include is `libgles2-mesa-dev` for building things that link to `libGLESv2.so.2` in clickable. On devices, the runtime may be provided by something other than mesa, such as `libhybris` on the Android HAL devices. For `clickable desktop` usage, the one provided by mesa as `libgles2-mesa` should do, generally. Note that NVidia drivers provide their own version too.

**Comment by bhdouglass** [comment]
Thanks, I'll try out your suggestion and reopen if we run into issues!
