### ISSUE TITLE
Redmi note 7 pro (Violet), unable to sync google contacts / open gmail on browser due to security browsing issues

### ISSUE THREAD

**Issue by shreeramkvn** [ubports/ubuntu-touch#1772]
Steps:
Contacts:
1. Go to contacts
2. Click on three dots
3. Click on Import contacts from gmail
4. Input user name / gmail id and click on sign in

Browser:
1. Open native morph browser
2. Go to www.gmail.com
3. Input user name / gmail id and click on sign in

Expected:
Application should reflect the user to password page in order to sign in.

Actual:
Application throw an alert (every time when we try to login to google) stating

"This browser or app may not be secure" error when trying to sign in with Google on desktop apps - Google Account Community. Try using a different browser. If you're already using a supported browser, you can refresh your screen and try again to sign in."

Device : REDMI NOTE 7 PRO (VIOLET)
Variant : 4/64 GB
Installed UT via : Ubports application (.deb)
Android version : android 9 / P
UT version : 16.x

**Comment by mardy** [comment]
This is not specific to violet. I'm closing this as it's essentially a duplicate of https://github.com/ubports/account-plugins/issues/40
