### ISSUE TITLE
(Request) Tie operability/viability of Libertine to 20.04 launch; only release 20.04 when Libertine is release-worthy

### ISSUE THREAD

**Issue by TartanSpartan** [ubports/ubuntu-touch#1773]
- Device: Any
- Channel: Any 
- Build: Any

Unfortunately many Libertine apps on 16.04 either crash with segmentation faults or have functionality compromised in some other way (menus which obscure elements of other menus, or which don't launch to begin with). These are detailed in numerous other issue reports. Knowing this was the case on my phones, I had intended to leave my M10 tablet at 15.04 until such time as Libertine would work on a newer version (and I knew this would likely be until 20.04 with the change to a Wayland display server). However I was forced to upgrade to be able to substitute coding temporarily for my laptop which needed repairs. In doing so this took away the Libre Office suite, so no more word processing, spreadsheets etc on a very compact, portable and convenient tablet. Among several other solid apps. This was a very bitter pill to swallow, a real case of "the lesser of two evils". I think other users would also prefer knowing that Libertine is promised to work out of the box for the 20.04 upgrade, rather than have it put on the back burner as it felt was the case for the whole time Ubuntu Touch has been on 16.04, and _still_ leaving a Ubuntu version which is now 5 years extinct as the only viable way to use desktop apps on the platform in the meantime.

**Comment by dobey** [comment]
Libertine has always been a fairly experimental feature. There are very few people available to maintain Ubuntu Touch. If Libertine is an important feature for you, then the best solution would be volunteering your time to make it better. It is not a point of reliability, and most people do not need it at all. Issue reports are not the place to rant about your personal pet peeves, either. This doesn't describe any specific or actionable issue. And Libertine itself has already been moved to gitlab. Therefore I am closing this issue.

**Comment by TartanSpartan** [comment]
This wasn't a rant, but a request.
