### ISSUE TITLE
Please add support for XIAOMI MI 10 T (Apollo)

### ISSUE THREAD

**Issue by Saikatsaha1996** [ubports/ubuntu-touch#1775]
Device - XIAOMI MI 10 T/10T pro
Processor - Snapdragon 865
Code name - Apollo
Ram - 8gb LPDDR5
Storage - UFS 3.1

**Comment by fredldotme** [comment]
Thank you for your interest in Ubuntu Touch.
Sadly, we cannot provide support for every device, especially if they are too new and nobody had the time to make it work for Ubuntu Touch.

Typically porting and supporting a device is done by those who're interested in it, they're doing it by themselves.
Also it seems your device is using an Android version that is too new and cannot be supported right now.

**Comment by Saikatsaha1996** [comment]
Thank you for your response
🥺☹️😐
