### ISSUE TITLE
Too short vibrations when phone is ringing

### ISSUE THREAD

**Issue by zlamalp** [ubports/ubuntu-touch#1778]
- Device: Google Pixel 3a XL
- Channel: Stable
- Build: OTA-18

### Steps to reproduce
- Have vibrations enabled.
- Someone calls you and phone is ringing.

### Expected behavior
I would expect the phone to vibrate strongly and for a longer period of time when its ringing and also not to vibrate when any kind of popup/about dialog appears (I have "other vibrations" disabled).

### Actual behavior
Phone vibrates for a fraction of the second, then it's silent for a few seconds and then again vibrates for a fraction of the second. It behaves more like haptic response for the on screen keyboard. There is no way I could notice the phone is ringing in my pocket when it's in silent mode. I could barely feel it when it was in my hand.
Also it vibrates when any dialog appears or when I open "about" page of any app (but only first display of that page) and there doesn't seem to be a way to disable this behavior.

Its not related to recent OTA-18 update and it doesn't happen on my Nexus 5. It was like this since I installed the phone.

**Comment by mattbel10** [comment]
I confirm same behavior on my pixel 3a. Vibrations happens but veeery light and intermittently, which doesn't make much sense.

**Comment by fredldotme** [comment]
I've committed a fix for xenial here: https://github.com/fredldotme/android_device_google_bonito/commit/e78d6c87d34bb48913be2a71780981ab14148a0e

Should be available within a day on the devel channel.

**Comment by mattbel10** [comment]
> I've committed a fix for xenial here: [fredldotme/android_device_google_bonito@e78d6c8](https://github.com/fredldotme/android_device_google_bonito/commit/e78d6c87d34bb48913be2a71780981ab14148a0e)
> 
> Should be available within a day on the devel channel.

Thank you Alfred for your work with UT in general and the Pixel 3a in particular. I'll definetely send a donation to youin order to show you my gratitude the better way ;)

**Comment by mattbel10** [comment]
> I've committed a fix for xenial here: [fredldotme/android_device_google_bonito@e78d6c8](https://github.com/fredldotme/android_device_google_bonito/commit/e78d6c87d34bb48913be2a71780981ab14148a0e)
> 
> Should be available within a day on the devel channel.

Thank you Alfred for your work with UT in general and the Pixel 3a in particular. I'll definetely send a donation to youin order to show you my gratitude the better way ;)

**Comment by mattbel10** [comment]
Same behavior after devel image update (build 2021-08-16/2 for Pixel 3a): vibration has a too low magnitude, impossible to be noticed when device in a pocket.

**Comment by zlamalp** [comment]
I can confirm that it still doesn't work on devel image.

**Comment by fredldotme** [comment]
Next change: https://github.com/fredldotme/android_kernel_google_bonito/commit/6da42e919a8e1f3c73cdae971c08444f04d0cf8b

In testing this improved vibration timing using `hfd-service-tools-vibrator`. Should be in the next devel update.

**Comment by mattbel10** [comment]
Just updated to devel image build 2021-08-19/2 and now vibration works!! Are loud and effective to the purpose of awakening attention of the owner. Thank you Alfred for your outstanding work. Matteo

**Comment by fredldotme** [comment]
Nice, and thanks! Closed then!
