### ISSUE TITLE
Device does not enter deep sleep

### ISSUE THREAD

**Issue by farkasdvd** [ubports/ubuntu-touch#1779]
- Device:  BQ E5
- Channel: rc
- Build: 2021-W28

### Steps to reproduce

Not exactly sure what causes the issue but it already happened 2 times since I switched to OTA-18. It always appeared after using the device for few days without a reboot.

### Expected behavior

The device doesn't drain the battery when the screen is off.

### Actual behavior

When the screen is off it usually takes 1-2 seconds for the phone to wake up (after the power button is pressed). However, when this issue appears the phone wakes up instantly. After restart the phone is back to normal.

### Logfiles and additional information

It was charging till 11 PM. Then next morning the battery level was down to 40%. At 11 AM I rebooted and it stabilized:
 
<img width="360" alt="screenshot20210719_183310644" src="https://user-images.githubusercontent.com/30418389/126209379-bc8678d2-09fe-4426-9ef7-4d64cda3c414.png">

**Comment by UniversalSuperBox** [comment]
This was likely fixed by https://github.com/ubports/media-hub/pull/40
