### ISSUE TITLE
Double battery consumption since update to OTA-18

### ISSUE THREAD

**Issue by yhervouette** [ubports/ubuntu-touch#1780]
### Illustrations

- Device: BQ E4.5
- Channel: RC
- Build: 20210708-27954

### Steps to reproduce

Update to OTA-18

### Expected behavior

Battery can hold one day long on normal use (like it is with previous OTA version)

### Actual behavior

Battery consumption is faster and the battery is discharged is less than one day.

### Logfiles and additional information

Linked to/same as  #1779 ?

**Comment by yhervouette** [comment]
Seems less obvious after several shutdowns and restarts.

**Comment by UniversalSuperBox** [comment]
Duplicate of https://github.com/ubports/ubuntu-touch/issues/1779
