### ISSUE TITLE
Can't choose in some dialog boxes

### ISSUE THREAD

**Issue by naizena** [ubports/ubuntu-touch#1781]
Aquaris e4.5 OTA18. Since OTA17 update, I cannot choose "Accept" in dialog boxes (like file Delete confirmation) unless rotate the phone. It just lets me "Cancel", wich works without rotation. 
![Aceptar_does_not_work](https://user-images.githubusercontent.com/87756164/126669470-aaba64cb-05fd-4eb4-a287-c28d63ac9627.png)
![Aceptar_works_after_rotation](https://user-images.githubusercontent.com/87756164/126669539-016d929f-c0ad-4112-bb7f-eee17745ec55.png)

**Comment by naizena** [comment]
![screenshot20210723_071459837](https://user-images.githubusercontent.com/87756164/126744233-6723820f-05e3-48e3-ae57-860d1fac03a0.png)
![screenshot20210723_081226127](https://user-images.githubusercontent.com/87756164/126744259-5df45c04-5877-4295-97a9-bf585b7ff5e6.png)
o

**Comment by naizena** [comment]
"Clean, Close and Confirm" only work if I rotate the phone.

**Comment by kugiigi** [comment]
Maybe your screen has dead zones for touch?
My bq E5 has that issue and I can't press the shutdown button unless I rotate the screen. You can confirm this using drawing apps like Finger Painting.

**Comment by naizena** [comment]
You are right. Confirmed as you suggested with Finger Painting. Thanks a lot.
