### ISSUE TITLE
Regression in OTA-18 means audio won't cut out when the headphone cable is removed

### ISSUE THREAD

**Issue by TartanSpartan** [ubports/ubuntu-touch#1782]
- Device: ygdrassil, cooler (likely device-agnostic?)
- Channel: Stable
- Build: OT1-18

### Steps to reproduce
Have audio (likely any kind but certainly music, or podcasts from Podbird) playing on your favourite cans. Remove the headphone cable.

### Expected behaviour
The audio will cut out without having to pause the playback via touchscreen. This can be very convenient if you need to switch your attention to something else at the drop of a hat; just like clicking off a radio handset when there's too much chatter which doesn't concern your attention.

### Actual behaviour
The audio will switch to playback via the device speakers instead, which is not intended behaviour and seems to show a regression for this feature with OTA-18. 

### Logfiles and additional information
Unknown which logfiles would be relevant. At first I thought this may be an Android 9 devices-only issue, but it is evident on my M10 HD/cooler which I just updated too, so it is probably present on all devices.

**Comment by c4pp4** [comment]
Hi, is it possible to fix it for usb headphones too via this issue or I have to submit a new one?

**Comment by UniversalSuperBox** [comment]
Hi @c4pp4, please create a new issue. Please include more information, such as which headphone interface you are using and on which device.

**Comment by mardy** [comment]
> Hi, is it possible to fix it for usb headphones too via this issue or I have to submit a new one?

The fix might apply to USB headphones too (I haven't one so I couldn't test it). On which image are you seeing the issue?

**Comment by c4pp4** [comment]
Image: 20210819-16931
Device: Xiaomi Mi A2
Headphones: Mi Dual Driver Earphones (Type-C)
Maybe it's important to mention headphones are analog (without DAC, passive).

**Comment by Flohack74** [comment]
Idk if Android kernels have USB audio drivers enabled at all...

**Comment by c4pp4** [comment]
> Idk if Android kernels have USB audio drivers enabled at all...

The headphones work without problem. After connect audio switch to it and after disconnect audio goes back to speakers. Volume indicator reflects the connection via on screen display notification.

**Comment by c4pp4** [comment]
I can confirm it works on Xperia X with 3.5mm jack plugged out - RC 2021-W36/2. (note: the issue with "USB type C" I mentioned above is opened here https://github.com/ubports/ubuntu-touch/issues/1815)
