### ISSUE TITLE
Proximity sensor reverse function

### ISSUE THREAD

**Issue by greskom** [ubports/ubuntu-touch#1787]
- Device: Volla
- Channel: stable
- Build: OTA-18

### Steps to reproduce
Make a call.

### Expected behavior
Screen turns off when putting the phone to the ear and light up when putting it off the ear and looking into the screen.

### Actual behavior
Exactly opposite.

**Comment by stekalb** [comment]
Can't confirm it on stable.
On dev it doesn't get dark neither on table nor on ear.

Maybe it's related to this bug https://github.com/ubports/ubuntu-touch/issues/1747
As far as I can see the display behaviour is triggered on volla the same way as autobrightness. If I cover the sensor (right of front cam) with my finger autobrightness change as well as display off are triggered on stable. Maybe both sensors are just placed side by side 🤔

**Comment by stekalb** [comment]
Tested with 'sensor status' app: the sensors seem to be side by side.

**Comment by Flohack74** [comment]
@stekalb maybe you need to know that there are special device quirks in the proximity sensor evaluation that generate different behaviour, and maybe we have messed with that. Ill take a look.

**Comment by greskom** [comment]
I am now unable to reproduce. Probably some reboot fixed it. Seems like some random trigger issue fixed by reboot. I am experiencing many of them.

Marek

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by UniversalSuperBox** [comment]
Should be fixed by a force-push to https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9 (old version was https://gitlab.com/ubports/core/repowerd/-/commits/ubports/xenial_-_android9-before-aug-2021-rebase). Will take another day before it lands in images.

**Comment by greskom** [comment]
Hi Dalton,

great news. Thanks

Marek

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by greskom** [comment]
Hello,

I reproduced yesterday on OTA-23.

Marek
