### ISSUE TITLE
Pressing "Shutdown" or using poweroff in terminal restarts device

### ISSUE THREAD

**Issue by KSPAtlas** [ubports/ubuntu-touch#1790]
### Illustrations

- Device: Sony Xperia X
- Channel: Stable
- Build: OTA-18

### Steps to reproduce

1. Power off the device from Ubuntu Touch
2. Enjoy

### Expected behavior

The device powers off completely

### Actual behavior

The device simply reboots back into Ubuntu Touch. I'm guessing it was trying to load the battery symbol but it loaded ubuntu touch instead

**Comment by KSPAtlas** [comment]
I've managed to shut it down successfully now, but this still happens most of the time.

**Comment by PhoenixLandPirate** [comment]
Is this only a problem when the phone is plugged in/charging, or does it also reboot when its not plugged in?

**Comment by KSPAtlas** [comment]
both

**Comment by Xozk** [comment]
My Pixel 3a does this everytime I shutdown. If I shutdown twice it turns off.

**Comment by bobblkabb** [comment]
Same here (volla)

**Comment by Flohack74** [comment]
@PhoenixLandPirate its a common Problem on Halium 9 devices also when not plugged in, unfortunately :) - but seems not all area ffected, and not all are affected every time.

**Comment by gbdomubpkm** [comment]
@bobblkabb I have never encountered this issue on the Volla (Stable or RC channels).

**Comment by Flohack74** [comment]
@KSPAtlas @PhoenixLandPirate @Xozk @bobblkabb can you please retest with latest RC? thx!

**Comment by Jan-ops79** [comment]
Works successfully without restart on Xperia X (OTA-19 QA)

**Comment by ivoxavier** [comment]
On FP2 and N5 works successfully

**Comment by bobblkabb** [comment]
Still happening on volla phone with OTA-19 but updating was strange. Booted into recovery and said "updated failed" or so. After reboot it showed "OTA-19" in the system information.
