### ISSUE TITLE
[Feature Request] Option to enable ringer/alerts through external speaker of phone when headphones connected.

### ISSUE THREAD

**Issue by toastedsocks** [ubports/ubuntu-touch#1791]
**Feature Request**

### Description of the feature

When headphones/handset is plugged in (or connected by bluetooth), provide option to allow ringer/alerts to sound through external speaker of phone. This allows the user to be alerted of incoming calls/messages when not wearing headphones, or for those who use an external handset connected to their device.

Thanks for your consideration,
T.

**Comment by UniversalSuperBox** [comment]
Since there are multiple similar reports, I have opened https://github.com/ubports/ubuntu-touch/issues/1795 to replace them. Please continue further discussion there.
