### ISSUE TITLE
Pixel 3a (Sargo) - during a call screen remains on when close to the ear

### ISSUE THREAD

**Issue by mattbel10** [ubports/ubuntu-touch#1796]
### Description of the feature

During a call proximity sensor doesn't seem to be effective and screen remains on when close to the ear.

- Device: Pixel 3a Sargo
- Channel: devel
- Build: 2021-07-31/2

### Steps to reproduce

When in a call, not in loud speaker mode, put the phone close to your hear and check whether the screen goes off.

### Expected behavior

The proximity sensor detects the vicinity of your ear and immediately the screen goes off.

### Actual behavior

The screen remains on.

### Logfiles and additional information

I wanted to double check whether the proximity sensor in general works on this device and I can confirm that it works employing the SensorStatus app.

**Comment by fredldotme** [comment]
This must be a new one. I wonder what changed in xenial that would expose this behavior.
Thanks for testing with SensorStatus, I'll forward this issue.

**Comment by stekalb** [comment]
Same behaviour on volla dev.

**Comment by Flohack74** [comment]
Can you please take a repowerd log during a call to see the log messages like the ones from here: https://gitlab.com/ubports/core/repowerd/-/blob/08419b8bad1298fd94b8578b59cd06b21db26a5a/src/adapters/android_device_quirks.cpp#L105

**Comment by Flohack74** [comment]
Bascically service stop repowerd, then use the same cmdline from etc/init/repowerd.conf but keep it in foreground (maybe it does that already) and then place a call.
And then cover/uncover the sensor.

**Comment by stekalb** [comment]
repowerd does not log anything during a call:

> sudo /usr/sbin/repowerd
> sudo: unable to resolve host yggdrasil
> Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
> [info] No device yaml config found!
> [info] No device yaml config found!
> [info] No device yaml config found!

**Comment by fredldotme** [comment]
Fix should be available in devel. Please retest so we can close this issue.

**Comment by mattbel10** [comment]
I confirm proximity sensor works as expected now for Sargo, build 2021-08-16/2. Thank you!
