### ISSUE TITLE
Mi A2 GPS doesn't work very fast. It take a lot of time, to found my postion. Often my position is not found. Does anyone have any idea how gps can be accelerated?

### ISSUE THREAD

**Issue by MarkusM1966** [ubports/ubuntu-touch#1797]
### Illustrations

- Device: Xiaomi MiA2
- Channel:
- Build:

**Comment by gibcheesepuffs** [comment]
Unfortunately ubuntu touch does not have A-GPS support at the moment so GPS will take at least 4-5 minutes or even more. This behavior is not specific to this device.

**Comment by MarkusM1966** [comment]
OK, actually no real supprise, but ...still a pity. But i still try to use UT as the default OS for my Mi A2.
Thanks ....

Am 10. August 2021 07:30:33 MESZ schrieb gibcheesepuffs ***@***.***>:
>Unfortunately ubuntu touch does not have A-GPS support at the moment so
>GPS will take at least 4-5 minutes or even more. This behavior is not
>specific to this device.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubports/ubuntu-touch/issues/1797#issuecomment-895740928

-- Gesendet von /e/ Mail.
