### ISSUE TITLE
Music app : Stuttering of the second piece of music played when the screen is off

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/ubuntu-touch#1798]
Device
Seen on Yggdrasil, OTA-18

The problem
Music app : SECOND piece of music played next, not the first one when the screen is off: the piece of music is chopped, the playback becomes normal again once the screen is on. Same effect on a playlist on the second piece of music. Same effect whether the songs are played from the SD card or from the internal memory. Enabling 'do not suspend app' music in UTTT does not solve anything.

What is expected
That several pieces of music can be played in succession without stuttering with screen off.

**Comment by mardy** [comment]
This is fixed by https://github.com/ubports/media-hub/pull/47

**Comment by dadandalive** [comment]
On Nexus 5, RC build 2021-W36/2, it is working as expected (tested with playing different audio files within a same genre, and with playing different audio files within a playlist).

**Comment by stekalb** [comment]
On volla it works as expected.
