### ISSUE TITLE
Missing package 'patch' in repo

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#1805]
- Device: volla (yggdrasil)
- Channel: dev
- Build: 20210812-21322
### Steps to reproduce
Try to install the notch-hax-patch (Scriptsource: https://github.com/JamiKettunen/unity8-notch-hax)
### Expected behavior
Package 'patch' can be installed by apt.

### Actual behavior
Package 'patch' can not be found.

The package is installable if you switch to stable channel. Therefore I assume the package has accidentitially been removed from repo.

**Comment by stekalb** [comment]
Maybe this is not necessary anymore due to https://github.com/ubports/unity8/pull/403

**Comment by UniversalSuperBox** [comment]
Hello @stekalb, thanks for your report!

It appears that the `patch` package is still in the Ubuntu 16.04 repositories, just like always:

```
patch/xenial-updates,xenial-security 2.7.5-1ubuntu0.16.04.2 arm64
  Apply a diff file to an original
```

Please run `sudo apt update` on your device and ensure that it succeeds, then try installing the package again. Also note that installing packages with `apt` in the rootfs is not supported, so bugs caused in other apps or scripts by the inability to do this will not be scheduled for fixing in Ubuntu Touch. Anyone can submit their own patch to fix it if need be, though.
