### ISSUE TITLE
Snoozed alarm is lost

### ISSUE THREAD

**Issue by angelomaragna** [ubports/ubuntu-touch#1806]
- Device: pixel 3a xl
- Channel:
- Build: OTA-18

### Steps to reproduce
Set a 1 minute timer, let it expire and snooze the alarm. The snozed alarm is not visible anymore and can not be disabled.

### Expected behavior
Find a notification allowing you to disable the snoozed alarm, see how much time is left orsee the alarm has been snoozed in the clock app so it can be disabled.

### Actual behavior
The snozed alarm is not visible anymore and can not be disabled.

### Logfiles and additional information
Was not able to copy the text nor an upload to pastebin button did work so took a snapshot)

![screenshot20210816_080207290](https://user-images.githubusercontent.com/6837687/129525400-cf8b55e2-31b5-44a4-a2d2-56889be73445.png)

**Comment by fredldotme** [comment]
That particular bug seems like something to report here: https://gitlab.com/ubports/apps/clock-app
