### ISSUE TITLE
Call in loud speaker mode is noisy and inaudible from other end

### ISSUE THREAD

**Issue by mattbel10** [ubports/ubuntu-touch#1808]
### Illustrations

- Device: Pixel 3a
- Channel: Devel
- Build: 2021-08-19/2

### Steps to reproduce

Start a call with someone else and enable loud speaker mode by pressing relevant button in Dialer app.

### Expected behavior

To be heard with no struggle and with a clear voice at the other end.

### Actual behavior

The interlocutor complains my voice isn't audible at all and there is a lot of noise in the background.

**Comment by fredldotme** [comment]
You might want to try to disable Fluence on the speaker phone as follows:

- Reboot into the recovery
- Open an `adb shell`
- Run the following commands:

```
mount /system_root
mount /system_root/var/lib/lxc/android/android-rootfs.img /tmp
busybox vi /tmp/system/bin/on-post-fs-data.sh
```

- Prepend the following line: `setprop persist.audio.fluence.speaker false`
- Exit vim and reboot

Please let me know how well it works for you.

**Comment by mardy** [comment]
Thanks @fredldotme for the hint, I didn't know about this stuff and I wonder if it will help the Xiaomi Redmi Note 7 Pro, because I'm having issues with bad quality from the internal mic. I'll try in the next few days.

Also I found this post which was a few properties related to fluence: https://xiaomi.eu/community/threads/mido-very-low-speaker-volume-after-disable-noise-cancellation.40071/

**Comment by fredldotme** [comment]
> Thanks @fredldotme for the hint, I didn't know about this stuff and I wonder if it will help the Xiaomi Redmi Note 7 Pro, because I'm having issues with bad quality from the internal mic. I'll try in the next few days.
> 
> Also I found this post which was a few properties related to fluence: https://xiaomi.eu/community/threads/mido-very-low-speaker-volume-after-disable-noise-cancellation.40071/

Might be, considering it's a QCOM device as well it might be susceptible to the same type of issues as with the P3a.

**Comment by fredldotme** [comment]
Reopening issue because it's been auto-closed and I want people to test this thoroughly

**Comment by mattbel10** [comment]
Hi @fredldotme, followed your procedure step by step but it didn't make any difference: still interlocutor barely could hear me in the middle of a lot of noise when in loud speaker mode. I noticed though there was a similar statement there, but for voicecall, which I didn't touch at all. In the end, the manipulated file looked as here below reported:
`#!/system/bin/sh        
setprop persist.audio.fluence.speaker false 
setprop persist.audio.fluence.voicecall false
bootctl mark-boot-successful`
Notwithstanding, there is a drawback I noticed after having made the modification and having rebooted the device: MTP via usb cable didn't work anymore. I don't know how this behavior is related but, no matter what, my Pixel 3a wasn't detected anymore; only after I deleted the row previously added at the top of the file, restoring the file as it was before, MTP started to work again. Thank you and regards. Matteo

**Comment by fredldotme** [comment]
This fixes the issue in my testing: https://github.com/Halium/hybris-patches/pull/36

**Comment by Fazarel** [comment]
Problem solved for me with latest devel, build n° 2022-01-31/2

**Comment by rik-shaw** [comment]
I can also confirm fixes are in place, all works GREAT with speakerphone now. Thanks again @fredldotme .

**Comment by mattbel10** [comment]
It works for me as well and also volume in the call is now modifiable. Only little issue remained is that counterpart when in loudspeaker mode complains that my voice comes with an echo. Don't know if anybody can confirm this. Notwithstanding, this is ready to be merged for OTA 22. Thanks to all!

**Comment by fredldotme** [comment]
> It works for me as well and also volume in the call is now modifiable. Only little issue remained is that counterpart when in loudspeaker mode complains that my voice comes with an echo. Don't know if anybody can confirm this. Notwithstanding, this is ready to be merged for OTA 22. Thanks to all!

@mattbel10 could you please run `getprop persist.halium.speaker_plus_handsetmic` and let me know whether it returns output?

**Comment by mattbel10** [comment]
Nope, just typed in your command and it only returns a blank row.
