### ISSUE TITLE
autobrightness not correctly working

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#1817]
- Device: yggdrasil
- Channel: dev
- Build: 2021-08-26

### Steps to reproduce
1. Autobrightness on
2. Go to a bright place: screen is bright
3. Turn off screen
4. Go to a really dark place with almost no light
5. Switch screen on => screen stays bright
6. Leave screen on and move to a bright place => after brightness reaches a higher level autobrightness starts to work again.

### Expected behavior
Autobrightness works also in low light environments

### Actual behavior
Autobrightness does not work in low light environments

### Logfiles and additional information
autobrightness is not triggered if light level = 0 when screen is switched on.

**Comment by stekalb** [comment]
Retested with volla this morning after applying the latest ubport-qa (see https://t.me/ubports_qa_team/45658)
New behaviour:
Works initially after reboot. But still not completely fixed:
light level 0, reboot. Brightness is adapted automatically, but:
1. Brightness is not at lowest level
2. Deactivate autobrightness and activate it again: Background light remains at the manually set level

It works as soon as light sensor is greater than 0

**Comment by stekalb** [comment]
Installed "sudo ubports-qa install xenial_-_android9_-_screenonlightevent"
Works after a reboot.

But after device goes to sleep, the light sensor just returns "0". 
As a result the autobrightness level sticks at the lowest level.
repowerd restart did not fix it. After a reboot it works again until next sleep.

**Comment by Flohack74** [comment]
Thats strange, it basically works here for 2 devices.
I have another issue:
on the Pixel 2 when the device was at sleep for a longer time it seems to take ages now to get screen woken up, probably sensor is warming up? If we can make this more async I am all in

**Comment by stekalb** [comment]
The prescribed behaviour seems not to be trggered if you press the powerbutton to lock the device / turn the screen off.
I need to wait 10+ minutes.
After waiting 10+ minutes it's reproducable for me.

**Comment by stekalb** [comment]
I think I figured it out. 
As soon as  the 'suru dark mode' indicator is deactivated, followed by a reboot, I am also not able to reproduce the autobrightness issue. AFAIK it's already enough to deactivate the autotrigger, but I didn't test this long enough to can say for sure.

So I think Mario's patch is fine and fixes the reported issue.

**Comment by Flohack74** [comment]
Fix in progress here: https://gitlab.com/ubports/core/repowerd/-/merge_requests/37

**Comment by stekalb** [comment]
It worked for the lsst builds just fine. But I think within the last three days there's a regression again. I test it that way:
1. Go to your cellar, lights switched on, autobrightness on.
2. Switch screen off
3. Turn light off
4. Switch screen on
The result is a bright screen which won't get darker until the light sensor receives a value larger than 0.
You can als achieve this by holding your finger beneath the notch. But as long as the sensor returns zero there won't be an adjustment.

**Comment by Flohack74** [comment]
Yes its not perfect now, we will still release the OTA like this, we cannot hold it much longer. Lets try to fix that finally for OTA-20...

**Comment by mardy** [comment]
I installed the RC (2021-W36/2) on the Redmi Note 7 and auto brightness is not working at all. But I never used it, so I maybe it never worked? (though according to the devices page it should be supported)

**Comment by mardy** [comment]
It's also strange that although I have "auto brightness" on, I can still use the slider to regulate the brightness. IMHO it should either be disabled, or it should disable auto brightness once moved.

**Comment by Flohack74** [comment]
@mardy yes the slider being able to be moved in autobrightness is a longstanding bug. Its probably easy to fix though :)

**Comment by ivoxavier** [comment]
On 6T it's working fine

**Comment by c4pp4** [comment]
I can confirm https://github.com/ubports/ubuntu-touch/issues/1817#issuecomment-917361396 it's not fixed. Mi A2 - RC 2021-W36/2.

**Comment by girlwithnoname** [comment]
On my 6T it works fine, too.

**Comment by Danfro** [comment]
Works on Xperia X devel, 64bit. Tested on two devices. There seems to be maybe a second or two until it does change the brightness, but I guess that is to be expected (I normally don't use that feature).

**Comment by Flohack74** [comment]
Yeah we will fix that later, it starts still too bright. But thats better than what was before ^^
