### ISSUE TITLE
Boot often fails on Redmi Note 7 Pro (violet)

### ISSUE THREAD

**Issue by mardy** [ubports/ubuntu-touch#1819]
- Device: violet
- Channel: OTA-18 and devel
- Build: 20210830-19597

I've not been using my `violet` for a couple of months (maybe even more), and now I realize that boot often fails (about 75% of the times), both on the latest OTA (18) and in the devel images. The device stays on the boot logo forever (though I can see a small flash after about 10 seconds).

The device is not reachable via adb, but the syslog is saved, so I can inspect it in the next [syslog-working.txt](https://github.com/ubports/ubuntu-touch/files/7086118/syslog-working.txt). The first message that caught my attention is this:
```
watchdog: 'lightdm' (instance '') hit respawn limit - not rebooting as rebooted recently
```

And indeed the log file under `/var/log/lightdm/lightdm.log` shows that lightdm was terminated and restarted a few times:
[lightdm.txt](https://github.com/ubports/ubuntu-touch/files/7086091/lightdm.txt)

Running the kernel with the `drm.debug=0x1ff` command line option and comparing the logs from a [successful boot](https://github.com/ubports/ubuntu-touch/files/7086120/syslog-working.txt) with those of a [failed boot](https://github.com/ubports/ubuntu-touch/files/7086119/syslog-fail.txt), shows that when the boot fails a process is getting an error -13 (permission denied) when invoking the `DRM_IOCTL_MODE_ATOMIC` ioctl:

```
Aug 31 11:35:58 ubuntu-phablet kernel: [    7.152338] [drm:drm_ioctl] pid=2643, dev=0xe200, auth=0, DRM_IOCTL_MODE_CREATEPROPBLOB
Aug 31 11:35:58 ubuntu-phablet kernel: [    7.152385] [drm:drm_ioctl] pid=2643, dev=0xe200, auth=0, DRM_IOCTL_MODE_ATOMIC
Aug 31 11:35:58 ubuntu-phablet kernel: [    7.152389] [drm:drm_ioctl] ret = -13
Aug 31 11:35:58 ubuntu-phablet kernel: [    7.181026] [drm:drm_ioctl] pid=2643, dev=0xe200, auth=0, DRM_IOCTL_MODE_ATOMIC
Aug 31 11:35:58 ubuntu-phablet kernel: [    7.181030] [drm:drm_ioctl] ret = -13
```

For comparison, here's the successful case:

```
Aug 31 11:28:16 ubuntu-phablet kernel: [    7.699706] [drm:drm_ioctl] pid=2544, dev=0xe200, auth=1, DRM_IOCTL_MODE_CREATEPROPBLOB
Aug 31 11:28:16 ubuntu-phablet kernel: [    7.699768] [drm:drm_ioctl] pid=2544, dev=0xe200, auth=1, DRM_IOCTL_MODE_ATOMIC
```

Note the difference in the value of the `auth` variable, which is `0` when the boot fails, and `1` when it succeeds; this seems consistent with the client getting a permission error. The logs are a bit hard to read because it appears that there are several processes accessing the drm device (I count 4 different PIDs in the success case, and 3 in the failure case), and the order of the operations seems to be different. So it may be that the issue is caused by the order in which processes are started.

In the failure case, the first process (2643) calling DRM_IOCTL_MODE_ATOMIC (and failing) is the third PID  I see dealing with drm in the logs (after 2172, which also appears in the lightdm logs as "`[+0.04s] DEBUG: Launching process 2172: /usr/share/ubuntu-touch-session/usc-wrapper --file '/run/mir_socket' --from-dm-fd 11 --to-dm-fd 14 --vt 1`" and 2531), and also the highest of the three (meaning that it's started after the other two); in the success case, the first process calling DRM_IOCTL_MODE_ATOMIC (2544) is the **first** process which I see dealing with drm in the logs, and the **second** (after 2160) in order of startup number.

**Comment by seisdr** [comment]
Can i have higher kernel using UT?

**Comment by Flohack74** [comment]
@seisdr no sorry. We are bound to the Android kernel at time of release of that device.

**Comment by mardy** [comment]
This is fixed with https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7-pro/xiaomi-violet/-/commit/3f3af471fad5848c98ffaddb4081439a092a295b

I'm closing this since so far it appears that only `violet` was affected by this.
