### ISSUE TITLE
nabi

### ISSUE THREAD

**Issue by wangafei** [ubports/ubuntu-touch#1829]
希望能支持 nabi 系列平板电脑,我这里收集的有一些相关的源代码和驱动代码,希望能提供帮助
https://github.com/wangafei/FUHU_INC_nabi2_xd-device
https://github.com/wangafei/FUHU_INC_nabi2_xd-kernel
https://github.com/wangafei/android_device_fuhu_nabi2_xd

**Comment by UniversalSuperBox** [comment]
Hello @wangafei,

Please file issues in English in the future.

If you would like to port Ubuntu Touch to a new device, please find our porting documentation at https://docs.ubports.com/porting.
