### ISSUE TITLE
volla phone: lxc-attach / logcat broken

### ISSUE THREAD

**Issue by osmith42** [ubports/ubuntu-touch#1836]
- Device: Volla Phone (yggdrasil)
- Channel: Stable
- Build: OTA-19

### Steps to reproduce

```
phablet@ubuntu-phablet:~$ sudo su -
root@ubuntu-phablet:~# lxc-attach -n android
CANNOT LINK EXECUTABLE "/bin/sh": library "libtls-padding.so" not found
```

Also:
```
root@ubuntu-phablet:~# lxc-attach -n android /system/bin/logcat
CANNOT LINK EXECUTABLE "/system/bin/logcat": library "libtls-padding.so" not found
root@ubuntu-phablet:~# /system/bin/logcat
CANNOT LINK EXECUTABLE "/system/bin/logcat": library "libtls-padding.so" not found
```

If not using `sudo su -` first to clear environment variables (fixing that too would make it more intuitive / or maybe mention in the guide that this won't work?):
```
phablet@ubuntu-phablet:~$ sudo lxc-attach -n android
CANNOT LINK EXECUTABLE "/bin/sh": "/system/lib/libc++.so" is 32-bit instead of 64-bit
```

### Expected behavior

Run logcat / attach to the lxc as documented [here](https://docs.halium.org/en/latest/porting/debug-build/debug-android-userspace.html#logcat).

### Actual behavior

See output above.

### Logfiles and additional information

Should be enough, let me know if you need more information.

For my use case I worked around with a statically built busybox, but creating this issue to note that it's broken.

**Comment by Flohack74** [comment]
Please try `LD_PRELOAD= LD_LIBRARY_PATH=  lxc-attach -n android -e -- /bin/sh` to get a shell inside the container. Replace /bin/sh with whatever executable. Unfortunately changes during recent upgrades made it necessary to always unset those 2 vars.

**Comment by osmith42** [comment]
This works, thanks Flo!
