### ISSUE TITLE
CalDAV calendars on Let's Encrypt-using servers fail to sync

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1838]
- Device: Pixel 3a
- Channel: devel
- Build: 2021-10-01

### Steps to reproduce

1. Have a Nextcloud calendar on a server with a Let's Encrypt certificate. Be signed in.

### Expected behavior

The calendar syncs

### Actual behavior

The calendar does not sync, in fact. Syncevolution reports:

```
[DEBUG syncevo-dbus-helper-7545 00:00:00] TransportException thrown at src/backends/webdav/NeonCXX.cpp:800
[DEBUG syncevo-dbus-helper-7545 00:00:00] transport problem: PROPFIND: Neon error code 1, no HTTP status: Server certificate verification failed: bad certificate chain
```

### Logfiles and additional information

Yep, they were right. The Let's Encrypt old root certificate expiring did actually affect us.

https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/core/packaging/ca-certificates/-/commit/02658ea4e3b113507ad701ea444ee601f8fa888c, should land in 2021-10-04 builds of Ubuntu Touch.

**Comment by Danfro** [comment]
I can confirm that on current devel calendars do again sync with LetsEncrypt certs on my nextcloud server.
