### ISSUE TITLE
[devel] no sound on incoming notifications

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1845]
On current devel (tested on 2 Xperia X) there is no sound on incoming notifications for Dekko, Teleports or FluffyChat.
Sound for incoming SMS work, sound for incoming calls works too.
When picking a sound from the list in system settings that is played too.

Media hub log has got the following error:

```
media-hub: Warning: Failed to open uri file:///usr/share/unity8//Components/sounds/ubuntu/notifications/Noti Karinding.ogg because it can't be found.
```

There seems to be a wrong `/Components` part in the file path.

**Comment by gbdomubpkm** [comment]
For me, the PR installed on Volla OTA-19 fixed the issue  https://forums.ubports.com/topic/6797/dekko-no-sound-notifications-with-ota-19/11 Thanks

**Comment by Flohack74** [comment]
Sure!

**Comment by Danfro** [comment]
I can confirm, that on current devel the issue is no longer existent.
