### ISSUE TITLE
Pixel 3a: echo for the recipient during calls

### ISSUE THREAD

**Issue by Fazarel** [ubports/ubuntu-touch#1860]
- Device: Google Pixel 3a - Sargo
- Channel: stable
- Build: OTA-19

### Steps to reproduce

Calling or receiving a call, loudspeaker off.

### Expected behavior

No echo.

### Actual behavior

**The called recipient** hears a annoying echo of his own voice, with a small delay of 1/2 second. Everyone I called mentioned the problem.

I installed UBports two days ago on a new phone. I never used the phone with android so I can't tell if the problem was already there before.

**Comment by Fazarel** [comment]
The echo persists with the last update (OTA-21).
**Does anyone else have this problem?**

To complete the issue description: there is no echo if you use headphones.

**Comment by lev4i4ek** [comment]
I have the same issue on my Pixel 3a, found a minor solution: if you turn the volume down a bit during the call, sometimes it might help. But obviously i want that to be fixed in another way.

**Comment by fredldotme** [comment]
Please test with latest devel, it's possible this bug might be fixed now.

**Comment by Fazarel** [comment]
Great, I just made a call, there is no more echo!
build n° 2022-01-31/2
Thank you very much!

**Comment by ramu191193** [comment]
i am facing same issue on my pixel 3..pls help
