### ISSUE TITLE
2台小米4，刷了16.04的系统，发现wifi的mac地址都是一样的，没法接入同一个路由器

### ISSUE THREAD

**Issue by wangke1993** [ubports/ubuntu-touch#1862]
目的：
    在同一个wifi下，使用两个ubuntu tounch手机来做服务器集群（还有一台笔记本centos的）
问题：
    刷完机后发现两台手机wifi的mac地址都相同，没办法接入同一个路由。各位大佬有没有解决办法？试过各种方法都不行，看看有没有成功解决的大佬，帮忙指点一下迷津？感谢

**Comment by wangke1993** [comment]
00:0a:f5:89:89:ff

**Comment by Arc676** [comment]
## Translation/Issue Details
Device: Xiaomi 4
OS: 16.04

OP has two devices but after installing, the MAC address on both devices is the same, so they can't connect to the same network.

## Notes
Possibly related to #541?

@wangke1993 Ubuntu Touch的问题都是用英文汇报的。如果你可以提供型板里要求的细节会让别人更容易帮助你，比如installation channel (devel, stable, etc)还有安装的版本（设置里能找到更详细的版本号）。手机是小米还是红米？你可以通过 https://devices.ubuntu-touch.io/ 找到你的手机的代号（比如santino, cancro, rolex是Ubuntu Touch支持的名字包括小米4的手机）。

**Comment by wangke1993** [comment]
> ## Translation/Issue Details
> Device: Xiaomi 4 OS: 16.04
> 
> OP has two devices but after installing, the MAC address on both devices is the same, so they can't connect to the same network.
> 
> ## Notes
> Possibly related to #541?
> 
> @wangke1993 Ubuntu Touch的问题都是用英文汇报的。如果你可以提供型板里要求的细节会让别人更容易帮助你，比如installation channel (devel, stable, etc)还有安装的版本（设置里能找到更详细的版本号）。手机是小米还是红米？你可以通过 https://devices.ubuntu-touch.io/ 找到你的手机的代号（比如santino, cancro, rolex是Ubuntu Touch支持的名字包括小米4的手机）。
> 
> (Translation for reference: Ubuntu Touch issues are reported in English. It would be easier for others to help if you provide the details requested in the template such as installation channel and installed version. Is it Xiaomi or Redmi? You can find the device codename via the Ubuntu Touch devices page.)

ok

**Comment by Arc676** [comment]
Comment for triage purposes: issue reposted in English in #1863.

**Comment by UniversalSuperBox** [comment]
Closing, superseded by https://github.com/ubports/ubuntu-touch/issues/1863
