### ISSUE TITLE
Can't copy file to restricted directory - Setting up PIA VPN connection

### ISSUE THREAD

**Issue by lindsayb37** [ubports/ubuntu-touch#1871]
Trying to copy a vpn config file to the /etc/openvpn directory but the system won't let me do it.

from the /home/phablet/openvpn/ folder I issue this command:
sudo cp vpn.conf /etc/openvpn/
[sudo] password for phablet: <entered>
cp: cannot create regular file'/etc/openvpn/vpn.conf': Read-only file system

I have tried this via SSH also. Tried entering su mode with 'su -' but it gives the same error. 

Any clue as to what I'm missing here would be appreciated.

Device: LG Nexus 5
OS: Ubuntu 16.04 (OTA-19) last updated 11/8/21
    UBPorts image part: 20210909-21755
    Ubuntu 16.04 LTS - armhf(20210909)
    Device build description: aosp_hammerhead-userdebug 5.1.1 LMY48W 31 test-keys

### Illustrations

- Device:
- Channel:
- Build:

### Steps to reproduce

sudo -i
cd /home/phablet
cp <any txt file> /etc/<any directory>

### Expected behavior

Expect it to copy file

### Actual behavior

cp: cannot create regular file'/etc/openvpn/vpn.conf': Read-only file system

**Comment by UniversalSuperBox** [comment]
Hi @lindsayb37,

The Ubuntu Touch root filesystem is read-only to allow for image-based system upgrades. The way that you are trying to set up your device will not work.

For what reason are you trying to modify the vpn.conf file on the filesystem? Maybe there is a better way to accomplish what you are trying to do.

**Comment by lindsayb37** [comment]
Trying to setup my vpn connection and this file was easier (I thought) than figuring out what to fill in the vpn program form.

However, I finally just figured this problem out with the following commands:
     df /etc/openvpn
     mount -o remount,rw /dev/loop0
 Now I am able to copy the file.

**Comment by UniversalSuperBox** [comment]
I'm happy you were able to find a solution to your problem, but note that your changes may be overwritten when you update Ubuntu Touch.  If you would like to keep your system configured like this, please note that it will be difficult for us to provide support for you.

Maybe an app like [VPN Editor](https://ubports.com/blog/ubports-news-1/post/vpn-on-ubuntu-touch-3022) might help in the future.

Either way, thanks for getting in touch with us. It helps us decide what to work on next.

**Comment by lindsayb37** [comment]
I will give it a try. I just find it is like pulling hen's teeth trying to get the info to put in the various fields and I definitely don't want to become a subject matter expert on VPN. Thanks.

**Comment by lindsayb37** [comment]
@UniversalSuperBox - I'm glad your pointed me in the right direction. It took a little bit of work along with trial and error but I finally got a VPN PIA (PrivateInternetAccess) connection working. I'm attaching images of the settings I used. Thanks again.

**Comment by lindsayb37** [comment]
![screenshot20211111_153531043 1](https://user-images.githubusercontent.com/15956734/141373006-61d87fd1-e983-4162-a760-4c947353ca48.png)
![screenshot20211111_153544983 1](https://user-images.githubusercontent.com/15956734/141373143-e314b857-e8ff-4ddd-a0bb-fed0131fa234.png)
![screenshot20211111_153604653 1](https://user-images.githubusercontent.com/15956734/141373230-7d7f72ac-467b-43bd-a7ca-73cc977afc9c.png)
![screenshot20211111_153610955 1](https://user-images.githubusercontent.com/15956734/141373278-8ee1aeef-b447-4382-a8fa-968a4ef81408.png)
![screenshot20211111_153617786 1](https://user-images.githubusercontent.com/15956734/141373326-c50f5eae-edae-4d33-ac7b-66b5441e4685.png)

**Comment by UniversalSuperBox** [comment]
I'm glad you were able to get it working. I'll close this issue again, you may have re-opened it accidentally.
