### ISSUE TITLE
SIM card not recognized after updating to OTA-20

### ISSUE THREAD

**Issue by Vistaus** [ubports/ubuntu-touch#1879]
My SIM card isn't recognized anymore after updating to OTA-20. It still works fine in a different phone, so it's not an issue with the SIM itself.
Not only that, but the SIM unlock and Mobile Network options are missing entirely from System Settings.

Phone: Xiaomi Poco F1
Carrier: Tele2 (T-Mobile)
Country: Netherlands

I hope you guys can fix this soon as this is a severe issue (I mean: I can't use the phone if I cannot even receive calls and stuff). If you need any more information or logs or something, please let me know.

**Comment by Flohack74** [comment]
@NotKit another failed delta?

**Comment by Vistaus** [comment]
I solved it. I downloaded https://gitlab.com/ubports/community-ports/android9/xiaomi-poco-f1/xiaomi-beryllium/-/blob/master/overlay/system/etc/ofono/ril_subscription.conf and moved it to the appropriate location on my device. After a reboot, all seems to be working again.

But this issue should still be fixed upstream.

**Comment by supernany** [comment]
Hello,

I have the same issue on Xiaomi Mi A2.
I’ve found /etc/ofono/ril_subscription.d/dual-sim.conf but I’m unable to edit it. Maybe because I’m on stable channel?
Actualy only slot2 is recognized.

**Comment by laguna66** [comment]
Had same issue on Xiaomi Mi A2.
Solved it by copy https://gitlab.com/ubports/community-ports/android9/xiaomi-mi-a2/xiaomi-jasmine_sprout/-/blob/master/overlay/system/etc/ofono/ril_subscription.conf to /etc/ofono/ril_subscription.d/dual-sim.conf.
After restart both SIM card were recognized.
@supernany: For write access use UI-Teak-Tool App and Menu->System->Write Access

**Comment by Flohack74** [comment]
Also please try to switch channels, e.g. from stable to RC and back. We had a bad delta in the update maybe, and a full reinstall by switching channels hould fix that.

**Comment by Vistaus** [comment]
> Also please try to switch channels, e.g. from stable to RC and back. We had a bad delta in the update maybe, and a full reinstall by switching channels hould fix that.

Tried that, but it didn't fix it.

**Comment by supernany** [comment]
> @supernany: For write access use UI-Teak-Tool App and Menu->System->Write Access

Thx.

**Comment by rey42** [comment]
Same problem with Oneplus 6: no SIM detected after upgrade to OTA-20 (SIM is in slot 2 as recommended for OP6).
Solved by replacing `/etc/ofono/ril_subscription.conf` as above but I don't know what is the correct content for this file on OP6 (not found in `https://gitlab.com/ubports/community-ports/android9/oneplus-6/kernel-oneplus-sdm845`...)

**Comment by supernany** [comment]
> but I don't know what is the correct content for this file on OP6 (not found in `https://gitlab.com/ubports/community-ports/android9/oneplus-6/kernel-oneplus-sdm845`...)

The right content of /etc/ofono is here: https://gitlab.com/ubports/community-ports/android9/oneplus-6/oneplus-enchilada-fajita/-/tree/master/overlay/system/etc/ofono

**Comment by rey42** [comment]
OK, maybe the problem is `ril_subscription.d` folder was not created in `/etc/ofono` during upgrade to OTA-20?

**Comment by Flohack74** [comment]
Yes its missing from the delta upgrade. Thats why I am saying, a full reinstall should fix it.

**Comment by Vistaus** [comment]
Update: this week, I switched to the RC channel and it seems to be fixed on RC.
