### ISSUE TITLE
GPS not working on BQ M10 HD Tablet OTA20 

### ISSUE THREAD

**Issue by dtarrant2019** [ubports/ubuntu-touch#1881]
<Just upgraded from OTA19 Stable to OTA20 and Location no longer works.
Tested using uNav set not to suspend. Left to run for 90 minutes. Waiting for GPS message was displayed and Location Indicator icon was solid white.
No fix was obtained.
GPS in OTA19 was fast and worked indoors.---------------------------------------------------------------------------
--------------------------------------------------------------------------------

IMPORTANT: Please file PINEPHONE ISSUES here: https://gitlab.com/ubports/community-ports/pinephone/-/issues

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

### Illustrations

- Device:
- Channel:
- Build:

**Comment by gbdomubpkm** [comment]
My BQ is not with OTA-20  but in RC 2021-W45 : il corresponds to OTA-20 i think and GPS works.

Found location in 2 minutes. Attempted outdoors. Make sure GPS is enabled for uNav in security/position settings. Make an attempt by restarting the smartphone.

**Comment by dtarrant2019** [comment]
I am on OTA-20 stable, so I will switch to RC and report back.

________________________________

**Comment by dtarrant2019** [comment]
Updated my software to RC 2021-W45 as suggested.

I am pleased to confirm that uNav location service is now working. 😀

________________________________

**Comment by dtarrant2019** [comment]
uNav and Pure Maps Slim both worked indoors and apart from the first fix, found location in 2 minutes.
I noticed the reset recommended by gbdomubpkm above was essential.
