### ISSUE TITLE
[Language] Tamil does not show (gibberish) as text or in the web.

### ISSUE THREAD

**Issue by jefrisingh** [ubports/ubuntu-touch#1884]
Tamil Language shows correctly in contacts app but in all other places it shows only [] squre boxes,

- Device: MI A2
- Channel: stable
- Build:

### Steps to reproduce
Just with the fresh install , go to https://ta.wikipedia.org/wiki site to check

**Florian Leeber** did helped me to fix it by the following commands 
`sudo mount / -o remount,rw`
`sudo apt update`
`sudo apt install fonts-taml`

After this commands everything is working as expected , but I need to run this commands on some updates If I switch to channel or some major updates. Hope you guys add tamil to UT, It's the one of the oldest language, spoken by more then 75M peoples (ref:https://en.wikipedia.org/wiki/Tamil_language) and one of the official language of India,Srilanka and Singapore,It also a recognised minority language of malaysia and South Africa , If you guys add it in UT, It will help more peoples move to UT without having issues :).

Thank you so much UT team.

**Comment by Flohack74** [comment]
Will be fixed by https://gitlab.com/ubports/core/seeds/ubuntu-touch/-/merge_requests/34
