### ISSUE TITLE
FileNotFoundError during update from OTA-18

### ISSUE THREAD

**Issue by nbremond** [ubports/ubuntu-touch#1888]
Hello,

I am not able to update my fairphone with the new release. (I forgot to do the last update, so I am still on OTA-18).

- Device: Fairphone3
- Channel: stable
- Build: Ubuntu 16.04 (OTA-18)

### Steps to reproduce
Try to update OTA (through settings -> update or trough CLI `sudo system-image-cli -v -p 0 --progress dots` )

### Expected behavior
OTA-19 or OTA-20 should be installed

### Actual behavior
I get the error `FileNotFoundError: http://system-image.ubports.com/pool/ubports-185b88d03d8570862e53ad88fcd086abf29a36d3158935e411277e95c12b882f.delta-ubports-068763c9a76973ddaf10ed07d730a6beec9e0449ed88ab65d3e41d1eb8e4fc3d.tar.xz:` 

### Logfiles and additional information

There is a colon at the end of the url (`.tar.xz:`) and when I tried to open the link from web browser and I got a `404 Not Found` error. If I remove the last character and keep only `tar.xz` I am able to download from web browser. I don't know if the colon is part of the url used by updater or just an additional display during formatting of the error.

![screenshot](https://user-images.githubusercontent.com/6490911/143674687-6ef6b032-d30e-4d33-8280-067a7f882866.png)

```
[systemimage] Nov 26 19:48:20 2021 (11484) http://system-image.ubports.com/pool/ubports-185b88d03d8570862e53ad88fcd086abf29a36d3158935e411277e95c12b882f.delta-ubports-068763c9a76973ddaf10ed07d730a6beec9e0449ed88ab65d3e41d1eb8e4fc3d.tar.xz:
[systemimage] Nov 26 19:48:20 2021 (11484) [/com/canonical/applications/download/41d087d33e0c4ff7a9a3408b1ff7a091] Group download reactor done
[systemimage] Nov 26 19:48:20 2021 (11484) Reactor error: http://system-image.ubports.com/pool/ubports-185b88d03d8570862e53ad88fcd086abf29a36d3158935e411277e95c12b882f.delta-ubports-068763c9a76973ddaf10ed07d730a6beec9e0449ed88ab65d3e41d1eb8e4fc3d.tar.xz:
[systemimage] Nov 26 19:48:20 2021 (11484) uncaught exception in state machine
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 515, in _download_files
    downloads, pausable=True, signal_started=True)
  File "/usr/lib/python3/dist-packages/systemimage/download.py", line 209, in get_files
    self._get_files(records, pausable, signal_started)
  File "/usr/lib/python3/dist-packages/systemimage/udm.py", line 175, in _get_files
    raise FileNotFoundError(reactor.error)
FileNotFoundError: http://system-image.ubports.com/pool/ubports-185b88d03d8570862e53ad88fcd086abf29a36d3158935e411277e95c12b882f.delta-ubports-068763c9a76973ddaf10ed07d730a6beec9e0449ed88ab65d3e41d1eb8e4fc3d.tar.xz:
Exception occurred during update; see log file for details
[systemimage] Nov 26 19:48:20 2021 (11484) system-image-cli exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/systemimage/main.py", line 402, in main
    list(state)
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 133, in __next__
    step()
  File "/usr/lib/python3/dist-packages/systemimage/state.py", line 515, in _download_files
    downloads, pausable=True, signal_started=True)
  File "/usr/lib/python3/dist-packages/systemimage/download.py", line 209, in get_files
    self._get_files(records, pausable, signal_started)
  File "/usr/lib/python3/dist-packages/systemimage/udm.py", line 175, in _get_files
    raise FileNotFoundError(reactor.error)
FileNotFoundError: http://system-image.ubports.com/pool/ubports-185b88d03d8570862e53ad88fcd086abf29a36d3158935e411277e95c12b882f.delta-ubports-068763c9a76973ddaf10ed07d730a6beec9e0449ed88ab65d3e41d1eb8e4fc3d.tar.xz:
[systemimage] Nov 26 19:48:20 2021 (11484) state machine finished
```

This is easy to reproduce on my phone, do not hesitate to ask if you need others informations

**Comment by Flohack74** [comment]
Well it seems we have issues with one delte file for this device on the system image server. A quick fix is to switch channel briefly to RC for example and then back, this will force a full upgrade.

**Comment by nbremond** [comment]
I tried to switch the channel to 'Candidate' and then wait for the download, but I got a similar issue (but with a different url). I also tried the develop  channel but it didn't succeed.
When switching back to stable, the download is estimated to 500Mo (it was arround 250Mo before) and once again, I got the FileNotFoundError

**Comment by nbremond** [comment]
This morning, the update was marked as downloaded. I was able to install it.
(Now, after the update, I do not have mobile connection : no mobile settings in the top menu, no cellular parameter in the 'settings' app, I cannot send SMS. I don't think this is linked to my previous issue. I will investigate a little bit on my own)

**Comment by Flohack74** [comment]
@nbremond please try again to switch channels. Some of the delta images seem to have missing files in OTA-20, but its only 1 or 2 devices affected. A successful switch from stable => RC => stable should clean that up, or reinstall with the installer without marking "Wipe" option (careful).

**Comment by nbremond** [comment]
I tried to switch to RC but I get the FileNotFoundError again...
I'm trying the develop channel to see if I'm able to download the file properly.

**Comment by nbremond** [comment]
I tried to use the installer but I also have an error : 
`Error: core:download: Error: core:download Error: Error: Checksum mismatch on file /home/user/.cache/ubports/FP3/Ubuntu Touch/boot-21bbf1907114f217e2784179a25325119b5bca7022e34f2ad9c3da34d9722ce5.tar.xz`

**Comment by nbremond** [comment]
After trying again and again, I finally succeed to get the file for the candidate channel through the updater in settings app.
I clicked on `install` but now my phone always start to bootloader. If I select `start` or `recovery mode` the phone reboot to bootloader.
I tried to reinstall with installer but the phone doesn't go to recovery mode and the installer stay in a waiting mode.
As it seems that the reinstallation will be quite difficult and I am not sure to keep my data, I will switch to halium10 in the same time, I don't know if this will help me, but this is a good occasion to do it :-)

**Comment by luksus42** [comment]
Hey @nbremond,
I am the porter of this device. If you still need help, just give me a sign.
Best regards, Lukas.

**Comment by nbremond** [comment]
Hello,
I was a bit busy last week and I didn't had time to try it.
Yesterday, I finally tried to install ubuntu touch again on my FP3 using ubport installer. At first I got an error about bad checksum on one downloaded file, but after that I figured out that I was running out of space on my hard drive. After cleaning my hard drive, the installer succeeded to flash my phone.

However, I have one question @luksus42  : I flashed android with Halium 10 but the installer has selected a channel with halium 9 : `16.04/arm64/android9/stable`. Did I miss something during installation ?

**Comment by luksus42** [comment]
> I flashed android with Halium 10 but the installer has selected a channel with halium 9 : `16.04/arm64/android9/stable`. Did I miss something during installation ?

I know that is confusing, but it is expected. There is no dedicated android10/halium10 rootfs. Only the systemimage is based on Halium 10. The rootfs tarballs are still lying in the android9 server path.

So everything is alright.

**Comment by nbremond** [comment]
> I know that is confusing, but it is expected. There is no dedicated android10/halium10 rootfs. Only the systemimage is based on Halium 10. The rootfs tarballs are still lying in the android9 server path.

Ok, great !
Thank you for your help and for your work for FP3 porting :)
