### ISSUE TITLE
lancelot - touchscreen not working correctly

### ISSUE THREAD

**Issue by drrate** [ubports/ubuntu-touch#1890]
- Device: Xiaomi Redmi 9
- Channel: Development
- Build: 234

### Steps to reproduce

Power on phone, attempt to use touchscreen.

### Expected behavior

Touchscreen works on first attempt, without turning the screen on and off, or being finicky,

### Actual behavior

The touchscreen fails to work without turning the screen off and back on, and even there, it doesn't work well on most attempts.

**Comment by luksus42** [comment]
Are you sure, you did flash the right stock firmware, prior to installing Ubuntu Touch?
See: https://github.com/ubuntu-touch-redmi-mt6768/lancelotfw/blob/main/README.md

**Comment by drrate** [comment]
I used the Ubuntu Touch installer found on the lancelot page. I don't use UT on my phone though anymore due to the fact that it is still in progress, and there were was no response for two weeks here.

**Comment by luksus42** [comment]
Please close the issue then.
