### ISSUE TITLE
Missing/outdated SSL-Certificates

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#1895]
- Device: yggdrasil
- Channel: dev && stable
- Build: 2021-12-05 && OTA20

### Steps to reproduce
Open morph and navigate to https://m.webtoons.com (or webtoons webapp)
You receive a not trusted message.

### Expected behavior
Display the website as the certificate (chain) is valid

### Actual behavior
You receive a not trusted message.

### Logfiles and additional information
Maybe the issue is related that digicert renewed/replaced some of its intermediate and root certificates as they acquired several certificate issuers.
Here the certificate chain is: *.webtoons.com -> geotrust RSA CA 2018 -> Digicert Global Root CA

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/core/packaging/ca-certificates/-/merge_requests/1
