### ISSUE TITLE
LED keeps blinking when plugged for charging

### ISSUE THREAD

**Issue by wilfridd** [ubports/ubuntu-touch#1896]
### Information
- Device: Mi A2
- Channel: RC 
- Build: 2021-W49

### Steps to reproduce
Plug device for charging = LED is blinking even when device is 100% charged
- Notification arrives = LED is blicking
- Clear notification = LED is blicking

### Expected behavior
Plug device for charging = LED is on
- Notification arrives = LED is blicking
- Clear notification = LED is on again

Additional suggestion
LED become off when device 100% charged.

### Actual behavior
LED is blinking as soon as the device is plugged for charging.
It's confusing when a notification arrives

### Logfiles and additional information
Please ask for appropriate logs

**Comment by Flohack74** [comment]
I have the same now on my Pixel, that was solid before! Strange things happening...

**Comment by luksus42** [comment]
I have this already for nearly two weeks, I think.
I thought, it would be some work in progress...
(FP3 Halium10)

**Comment by fredldotme** [comment]
hfd-service in the main branch has been changed twice in end of November:
https://gitlab.com/ubports/core/hfd-service/-/commits/main/

Since there's no ubports/xenial branch I would assume it has something to do with that.

**Comment by Flohack74** [comment]
Probably fixed by https://gitlab.com/ubports/core/hfd-service/-/merge_requests/6

**Comment by Flohack74** [comment]
Fixed - please test with today´s devel build.

**Comment by wilfridd** [comment]
Fix confirmed! Thx
