### ISSUE TITLE
bq Aquaris M8 and UBTouch?

### ISSUE THREAD

**Issue by acutbal** [ubports/ubuntu-touch#1898]
Hello!!

I have a bq Aquaris M8 tablet, which has the same hardware as the M10:

M10 => https://devices.ubuntu-touch.io/device/cooler/

M8 => https://www.devicespecifications.com/en/model/558c3f49

I wonder if it could be possible to install Ubuntu Touch on it...

Best regards!!

**Comment by ivoxavier** [comment]
Hi @acutbal,

No. It needs a port as every other device.

Cloud you close this issue please?

Thank you.

**Comment by acutbal** [comment]
Ok, thank you very much!! :smile:
