### ISSUE TITLE
Cannot send or receive SMS on CDMA network

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#19]
I am unable to send or receive SMS messages on hammerhead using a CDMA network (Sprint). Data and calling work.

reported by https://launchpad.net/~alecks-g.

log: https://bugs.launchpad.net/ubports-n5/+bug/1674496/+attachment/4841239/+files/monitor-ofono.log

**Comment by UniversalSuperBox** [comment]
I haven't found any duplicates of this issue so far, nor has anyone confirmed it.
