### ISSUE TITLE
Fingerprint not working (Redmi Note 7)

### ISSUE THREAD

**Issue by papasfilmsofficial** [ubports/ubuntu-touch#1909]
### Illustrations

- Device: Xiaomi Redmi Note 7
- Channel: Stable
- Build: OTA-21

### Steps to reproduce

Set up the device using a PIN instead of a password. Then set up a fingerprint.

### Expected behavior

The device should unlock without prompting the user for their PIN

### Actual behavior

When you use the fingerprint the device will still ask you for your PIN and so the fingerprint is useless (if the fingerprint is not recognized then it will do nothing

### Logfiles and additional information

Can't find any related logs.

**Comment by papasfilmsofficial** [comment]
After disabling Fingerprint and re-enabling it everything works fine

**Comment by 42madorna** [comment]
I have the same issue but in MIX 3 (perseus) also OTA-21
