### ISSUE TITLE
Pixel 2: Latest devel / RC images are messed up

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1916]
- Device: taimen, walleye
- Channel: devel, RC
- Build: since a few days

Since a few days devel and now also RC is messed up for Pixel 2:

- WiFi broke since kernel and vendor partition images are not from the same build
- Pixel 2XL (taimen) got the system image from Pixel 2 (walleye) in its channel, resulting in funky things

Its confirmed that the latest artifacts from the Jenkins server are okay. A way how to fix it:
- Download the halium_taimen.xz or halium_walleye.xz from here: https://ci.ubports.com/job/UBportsCommunityPortsJenkinsCI/job/ubports%252Fcommunity-ports%252Fjenkins-ci%252Fwalleye-taimen/job/main/
- Extract to a new folder
- fastboot flash boot.img dtbo.img and vendor.img

This will bring back WiFi at least. system image replacement is a bit more complex

- Boot into recovery
- adb shell and mount /system_root folder
- exit adb, and adb push the android_rootfs.img file from system/var/lib/lxc/android folder in the xz file to system_root/var/lib/lxc/android

**Comment by UniversalSuperBox** [comment]
I have determined that the `halium_taimen.tar.xz` and `device-72c23661310412eb665cfb9622ab121ed3d01d133a496a89e5d52e70cac1f59c.tar.xz` on the server as of right now match; and that `halium_walleye.tar.xz` and `device-72c23661310412eb665cfb9622ab121ed3d01d133a496a89e5d52e70cac1f59c.tar.xz` match. This shows that the files being provided by Jenkins are being consumed and served by system-image-server correctly. If the assumption that Jenkins is serving the correct files holds, the issue is somewhere else.

Continuing...

**Comment by UniversalSuperBox** [comment]
@Flohack74, please check that the content of `/etc/system-image/channel.ini` is correct. On Walleye, this file should have the following contents:

```
[service]
base: system-image.ubports.com
http_port: 80
https_port: 443
channel: 16.04/arm64/android9/devel
device: walleye
build_number: 543
version_detail: tag=2022-01-13,ubports=20220113-32373,device=20220111-8683,keyring=archive-master,version=543
```

On Taimen, it should have the following contents:

```
[service]
base: system-image.ubports.com
http_port: 80
https_port: 443
channel: 16.04/arm64/android9/devel
device: taimen
build_number: 543
version_detail: tag=2022-01-13,ubports=20220113-32373,device=20220111-10907,keyring=archive-master,version=543
```

**Comment by Flohack74** [comment]
So critical RC can be removed: Its an issue with the recovery´s fstab on only that device. More later.

**Comment by Flohack74** [comment]
Fixed by https://github.com/Flohack74/android_device_google_wahoo/commit/5c3a3ffbc2bf76d8056d9f5a2c8b5086cfc54364
