### ISSUE TITLE
Impossible to stop sound reproduction after closing System-Settings

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#1918]
### Illustrations

- Device: Nexus 5, OnePlus 6T
- Channel: Devel & Stable
- Build: 20220112 & OTA-21

### Steps to reproduce

I know this may not be an issue, because there is an pause button an the bottom and an 'arrow' at the pageheader that will stop the sound reproduction. But this time, I've closed the app instead, assuming it would stop the sound reproduction. 

1. Go to System Settings
2. Sound
3. Tap on RingTone
4. Tap on UBports ringtone
5. Once starts playing close the App. 
6. Go to sound indicator and try stop soundPlaying. You can't
7. Sound on will stop after music ends

### Expected behavior

Music stops once page is destroyed or having the option to stop from the indicator.

### Actual behavior

If user accidentally closes the system settings without stopping the sound reproduction, it will only stop after time length reaches the end.

**Comment by c4pp4** [comment]
RC OTA22: 2022-W04 (device: Mi A2)
Works. Music stops playing when sound settings window is closed.
