### ISSUE TITLE
OnePlus 6 : After apt update the phone does not start anymore

### ISSUE THREAD

**Issue by GreUms78** [ubports/ubuntu-touch#1919]
- Device: One Plus 6
- Channel: Stable
- Build: OTA-21

### Steps to reproduce
New install, after apt update/upgrade the phone stuck on boot loader (tested 2-3 times)

### Expected behavior
After the upgrade, start the system

### Actual behavior
After the update impossible to start on UT the phone remains stuck on the bootloader (or fast boot?) forced to reinstall completely

### Logfiles and additional information
Sorry for my english

**Comment by ivoxavier** [comment]
Hi,

If you modify your root file system, you will eventually break it. ubuntu touch is not a tradiotional linux.

I think you can close this issue by yourself.

Thank you!

**Comment by GreUms78** [comment]
Hello @ivoxavier  

Isn't it good to do apt update & apt upgrade on ubuntu touch?

**Comment by fredldotme** [comment]
No. We generate images on the server side using apt but the users themselves should not interact with it.
Also, mounting the system read-write essentially breaks all security, logically.

Closed.
