### ISSUE TITLE
FM radio: add service to rootfs

### ISSUE THREAD

**Issue by mardy** [ubports/ubuntu-touch#1922]
We need to proceed in steps:
1. Add the [service](https://gitlab.com/ubports/core/fm-radio-service) to the rootfs ([PR](https://gitlab.com/ubports/core/seeds/ubuntu-touch/-/merge_requests/47))
2. Create a new framework ([PR](https://github.com/ubports/ubuntu-touch-meta/pull/63))
3. Update the apparmor-easyprof-ubuntu for the `fm-radio` capability ([PR](https://gitlab.com/ubports/core/apparmor-easyprof-ubuntu/-/merge_requests/4))
4. Check if the click-review-tools need to be updated.

It's not necessary that all steps are performed in the course of the same OTA, but it's important that they are done in this order.

(If you think I forgot some step, please comment!)

**Comment by Fuseteam** [comment]
All of them appear to be merged, how do we test if all's well?

**Comment by Danfro** [comment]
I guess by using this app: [https://open-store.io/app/it.mardy.fmradio](https://open-store.io/app/it.mardy.fmradio). But might be working only on one device now as stated in the app description.

**Comment by Danfro** [comment]
Seems to be not working on Xperia X right now.

**Comment by Fuseteam** [comment]
So that would be violet(redmi note 7 pro)

**Comment by Flohack74** [comment]
Well:
- Does your device have FM radio at all?
- If so, does it use a supported chipset? Currently this will only work for old BQs on Mediatek.
I am afraid we will end up again with special solutions for every FM-capable device.

**Comment by Fuseteam** [comment]
It should yes, however starting up reboots the device. It's likely an issue in my device's kernel or vendor

**Comment by Fuseteam** [comment]
Ok i take that back, the app mentioned by danfro doesn't reboot my device. I hear what i think is radio static, i'm unsure if i should be able to tune to a frequency with the app

**Comment by mardy** [comment]
> Ok i take that back, the app mentioned by danfro doesn't reboot my device. I hear what i think is radio static, i'm unsure if i should be able to tune to a frequency with the app

Yes, the `<` and `>` buttons should search for the previous and next station, respectively. What phone are you trying the app with?

In some cases it might be relatively easy to add support to a new phone; feel free to write me in Telegram, that would make things progress faster :-)

**Comment by Fuseteam** [comment]
i'm trying it on a redmi 9. it doesn't appear to search for new stations. i'll ping ya on telegram later. Pm or devel group?

**Comment by Fuseteam** [comment]
sounds good, will do that later

**Comment by Fuseteam** [comment]
so @Flohack74 what do we need to confirm to clear this from the QA column? the service is definitely in the rootfs, but it certainly doesn't work on all devices

**Comment by Flohack74** [comment]
Yeah thats enough :P

**Comment by Fuseteam** [comment]
lol
