### ISSUE TITLE
SMS in notification panel.

### ISSUE THREAD

**Issue by jjmax25** [ubports/ubuntu-touch#1923]
Hello,
When the phone is locked, when receiving an SMS, you open the notification panel, is there it is possible by pressing on the message, to answer it! The problem is that this one does not appear in full, if it exceeds a certain length...
Thank you for this OS that I use daily.
Pixel 3a
(translated from French!)

**Comment by lduboeuf** [comment]
humm, i have no issue writing a long answer. It allows me to scroll if text is too long

![screenshot20220119_100048246](https://user-images.githubusercontent.com/11663835/150098240-460b7773-8259-4960-8c1a-58af81410517.png)

**Comment by jjmax25** [comment]
it's not when replying, but the received sms;
example :
![screenshot20220119_134129806](https://user-images.githubusercontent.com/96914380/150133830-26a0a163-01b8-4800-bc9e-6a352145d939.png)

Original sms :
![screenshot20220119_134205645](https://user-images.githubusercontent.com/96914380/150133920-ee1bce71-a2c1-49ba-8bbb-e75cf3d71f89.png)

**Comment by lduboeuf** [comment]
i see sorry. Well i think it is a UI design decision. To not display the whole message and let places for other notifications

**Comment by jjmax25** [comment]
Ok, I understand, if one day you have some time, it would be cool to add a small arrow at the top right of the message, which would allow you to develop this one!!!
Thank you!
