### ISSUE TITLE
OnePlus 5T: Fingerprint unlock cannot be set

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1926]
- Device: Oneplus 5T (dumpling)
- Channel: all
- Build: all

### Steps to reproduce
- Register at least 1 fingerprint
- Try to set unlock method to fingerprint unlock

### Expected behavior
- Unlock method available

### Actual behavior
- Unlock method is not available

### Logfiles and additional information
This will be fixed by https://gitlab.com/ubports/core/biometryd/-/merge_requests/12 and https://github.com/Flohack74/android_device_oneplus_dumpling/commit/60e7b141b067d6aa488fb3ca8f28c90f89c87458

**Comment by MoemUT** [comment]
For me, the fingerprint lock can definitely be set and I can actually use it most of the time. It does not recognise my finger 100% of the time, but it does so more often than not.
