### ISSUE TITLE
Unclarity on ubports.com

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ubports/ubuntu-touch#1927]
Hello there.

The first paragraph of [the landing page of your main website](https://ubports.com/) mentions (1) 'the UT core' and (2) 'Ubuntu Touch' and is sandwiched between mentions of (3) 'UBports'. That situation will boggle the neophyte. You should explain how those three things interrelate (and indeed if possible reduce the number of entities that you mention). Or so it seems to me. Please move this report if it belongs elsewhere.

**Comment by Ka1z3n** [comment]
Hey thank you for the comment. 
UBports narrative is pretty much important 

However the right place for this issue would be on the Gitlab account [Website](https://gitlab.com/ubports/teams/marketing/website/website-design/-/issues)

**Comment by LinuxOnTheDesktop** [comment]
Thank you. Moved to [here](https://gitlab.com/ubports/teams/marketing/website/website-design/-/issues/38).
