### ISSUE TITLE
Morph Browser crasches

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1929]
Device: BQ E5
Channel: dev

Morph browser crashes (as well as Demo/Onion browsers, Apps like Tutanota, etc.) after update to "835" 30 Jan 2022 (from "816" 23 Dec 2021).

Changing the channel in Release Candidate ("133") has no effect.

Only with the Stable channel ("19") resumes to work partially (Morph crashed by clicking on bookmarks. It was necessary to delete them...)

**Comment by fredldotme** [comment]
Should be fixed by: https://gitlab.com/ubports/core/hybris-support/lxc-android-config/-/merge_requests/66

**Comment by FlavioMala** [comment]
Fixed/works again with devel "837" (DL 31 Jan 2022) - BQ E5.

Thanks/Grazie/Vielen Dank/Gracias/ 
Merci/Mulțumesc/Köszönöm...
