### ISSUE TITLE
Support for Fairphone 4

### ISSUE THREAD

**Issue by sorinirimies** [ubports/ubuntu-touch#1931]
### Description of the feature

I would like to ask for Fiarphone 4 device support. 
Is there a possibility this can happen? 
If yes? How complex would it be and how can I support in any way.

**Comment by Fuseteam** [comment]
port request are not typically taken as the developer that ports it needs to own the device and it can take a significant amount of time for them to complete it. all the information needed to get into porting can be found through devices.ubuntu-touch.io and docs.ubports.com/porting
that said, someone is already working on a fairphone 4 port, they are usually on telegram

**Comment by Flohack74** [comment]
@z3ntu is playing with this ATM...

**Comment by Fuseteam** [comment]
> that said, __someone__ is already working on a fairphone 4 port, they are usually on telegram

:p

**Comment by isle9** [comment]
Seems like this has been implemented?

https://devices.ubuntu-touch.io/device/fp4/release/focal
