### ISSUE TITLE
Morph Browser Crash at Start

### ISSUE THREAD

**Issue by ChiefPete** [ubports/ubuntu-touch#1937]
- Device: Google Nexus 7 2013 WiFi - Flo
- Channel: Release Candidate
- Build: 2022-W06

Morph-Browser crashes upon starting on RC, Edge, & Development Channels.

It works on the Stable Channel.

Last line in the log is: `[6553:6612:0211/123212.371043:ERROR:gl_ozone_egl_qt.cpp(102)] eglGetProcAddress not found.`

Here is a link to the full [morph-browser log](https://susepaste.org/89301038)

**Comment by Flohack74** [comment]
@ChiefPete please confirm this for me, as this is a release blocker for Friday´s OTA-22 release...

**Comment by Flohack74** [comment]
Should be fixed by https://gitlab.com/ubports/core/hybris-support/lxc-android-config/-/merge_requests/70
