### ISSUE TITLE
Flight mode only turns on/off cellular

### ISSUE THREAD

**Issue by IanHasman** [ubports/ubuntu-touch#1943]
In OTA 22 toggling flight mode only turns on/off cellular. On previous releases it used to do the same for wifi and bluetooth at the same time.
 That meant that one button push turned off all radio emissions from the device.

I mentioned it in a discussion on the ubports forum. I am seeing this issue on a Volla Phone X. Another user reported that it works as expected on a Meizu MX4 at OTA 22 so pronably just a VPX issue.

The discussion was
https://forums.ubports.com/topic/7481/where-did-all-the-phone-options-go/8

**Comment by Flohack74** [comment]
Strange we did not touch anything in this area. But Vollaphone X got upgraded to Halium 10, that might be a problem. Please move this to https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues in this case.

**Comment by IanHasman** [comment]
While looking at strange issues with Volla Phone X how about being unable to turn blue tooth off and if you turn off wifi in the pull down menu it disappears?

See https://forums.ubports.com/topic/7419/ota-22-call-for-testing-companion-post/27 

for details.

**Comment by IanHasman** [comment]
Both issues fixed in OTA-23.
