### ISSUE TITLE
Bluetooth in Volla Phone X running OTA-22 turns on automatically in 30 seconds after turning it off.

### ISSUE THREAD

**Issue by Talkless** [ubports/ubuntu-touch#1945]
- Device: Volla Phone X
- Channel: Stable
- Build: OTA-22

After upgrading to OTA-22 I've noticed that now there's Bluetooth indicator visible. After sliding-down from top I see that Bluetooth slider is set to ON. But even if I turn it of, it switches back on after 30s.

### Steps to reproduce
Turn Bluetooth off, wait for 30 seconds

### Expected behaviour
Bluetooth switch in settings, indicator, should turn off Bluetooth for good.

### Actual behavior
Bluetooth turns back on.

**Comment by OanaGS** [comment]
I have encountered the same issue today, after updating my Volla Phone X to Ubuntu v.5.
Are there any workarounds?

**Comment by Talkless** [comment]
@OanaGS do you have issues with powering WiFi On and Off? https://github.com/ubports/ubuntu-touch/issues/1946

**Comment by OanaGS** [comment]
> @OanaGS do you have issues with powering WiFi On and Off? #1946

@Talkless no, wifi works fine for me. Only bluetooth it activates after about half minute, even if switched off.

**Comment by Flohack74** [comment]
Probably some process crashes before it realizes that BT should be off now ;) have a similar thing on the Pixel 1, there it takes only 1 second before BT is back ;)

**Comment by Talkless** [comment]
@OanaGS have you tried 23rc?

**Comment by OanaGS** [comment]
@Talkless no, I haven't.

**Comment by Talkless** [comment]
Looks like OTA-23 fixed it! It does not boot with BT on, and turing BT off leaves it off.
