### ISSUE TITLE
WiFi cannot be turn off, or on, without help of reboot on Volla Phone X running OTA-22

### ISSUE THREAD

**Issue by Talkless** [ubports/ubuntu-touch#1946]
- Device: Volla Phone X
- Channel: Stable
- Build: OTA-22

### Steps to reproduce

Turn WiFi off, WiFi slider switches to "off" position, but WiFI is still active:

![screenshot20220224_202422550](https://user-images.githubusercontent.com/292191/155585714-b197891c-c4dd-41af-9859-724f80de6f1d.png)

After rebooting, WiFi is On again:

![screenshot20220224_202601638](https://user-images.githubusercontent.com/292191/155585742-f1a27f60-0feb-41ee-a6d1-005e735485e7.png)

But after swithing it Off (finally), WiFi is "gone" completely:

![screenshot20220224_202605082](https://user-images.githubusercontent.com/292191/155585806-2108c0ae-5135-4aed-9eaf-a204db9f045d.png)

Only after rebooting *again* you can turn it On again. And cycle repeats. Worked fine in OTA-21.

### Expected behavior

WiFi should turn on/off successfully without reboots.

### Actual behavior

WiFi can be turned off or on only with help of reboots.

### Logfiles and additional information

Let me know what log files I should check, what to grep, etc.

**Comment by Talkless** [comment]
Workaround is to issue `nmcli r all off` to turn off WiFi without any "side-effects" described.

**Comment by RobertAlienBob** [comment]
Also switching on the Flight Mode does not switch off the Wifi

**Comment by Talkless** [comment]
Also, **sometimes** using `nmcli r all off` workaround makes WiFi functionality completely dissapear, so I have to reboot to be able to enable WiFi again.

**Comment by Talkless** [comment]
@RobertAlienBob Have you tried 23rc?

**Comment by RobertAlienBob** [comment]
Well, no. Received notification about update available, using system updater files downloaded. Then clicked INSTALL, confirm reboot to instal, phone reboots to recovery mode and there is no option to update. Reboot goes back to OTA 22.

**Comment by koenvervloesem** [comment]
@RobertAlienBob Have you tried this workaround? https://github.com/ubports/ubuntu-touch/issues/1999#issuecomment-1173449818

**Comment by Talkless** [comment]
I can confirm that this issue is fixed in OTA-23!
