### ISSUE TITLE
Is Ubuntu touch will work with a Xiaomi Mi note 10 ?

### ISSUE THREAD

**Issue by MagnusDot** [ubports/ubuntu-touch#1951]
### Description

- Device: Xiaomi Mi note 10

I would very much like to install Ubuntu touch but I would like to know if it will work with my Xiaomi mi note 10?

**Comment by ghost** [comment]
yes if anyone port it

**Comment by ghost** [comment]
Nobody port it ?

**Comment by MagnusDot** [comment]
the project has been abandoned it seems

**Comment by fredldotme** [comment]
It is not abandoned. Everything moved to GitLab and *do not* expect us to accept requests for new ports there either.

**Comment by MagnusDot** [comment]
@fredldotme when a maintainer, doesn't give any more info and migrates an open source project without leaving any link and any info, we call it a project abandonment
