### ISSUE TITLE
When will Nokia N1 tablet be supported？

### ISSUE THREAD

**Issue by WUYANGHAO** [ubports/ubuntu-touch#1959]
When will Nokia N1 tablet be supported？

**Comment by fredldotme** [comment]
Never unless someone works on it, and you can only work on it if one has the device.

**Comment by dobey** [comment]
As stated, someone who owns the device would have to do the work to create and maintain a port. Documentation is at https://docs.ubports.com/porting if you wish to attempt a port.

Please do not open issues asking when X device will be supported. Thanks.
