### ISSUE TITLE
WiFi autoconnection Volla Phone

### ISSUE THREAD

**Issue by Heorhi-Puhachou** [ubports/ubuntu-touch#1960]
Problem:
WiFi connection can disconnected to short time. I expected that phone will be reconnected to network if it will be avaliable. But password for network not saved and connect must be performed manualy

Expected behaviour:
- If password was wrote for network once it will be remembered
- Network can be marked for autoconnection
- If saved network will be avaliable and marked for autoconnection connection will be performed automaticly

Actual behavior:
Volla Phone after short disconnect forgot wifi password and connection must be performed manually with password input.

**Comment by Heorhi-Puhachou** [comment]
Not reproduced now.

**Comment by Heorhi-Puhachou** [comment]
Same problem now. For reconnecting to Wi-Fi network I must input password. Volla phone not remember password for Wi-Fi
![photo_2022-04-17_08-05-36](https://user-images.githubusercontent.com/60034257/163702818-27ad9a7d-f6ff-4228-a95d-9435130fcccb.jpg)
.

**Comment by Flohack74** [comment]
Please retest this with latest OTA-23 update, we tried to improve the situation.

**Comment by Heorhi-Puhachou** [comment]
> Please retest this with latest OTA-23 update, we tried to improve the situation.

Right now, I haven't Volla Phone and cannot retest. You can close the ticket if you are sure that the problem was fixed.

**Comment by Flohack74** [comment]
I think so, yes :)
