### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by deepak01negi** [ubports/ubuntu-touch#1961]
Where to get the official source code for the project(Ubuntu Touch)?

**Comment by lduboeuf** [comment]
You can find the source code here in https://github.com/ubports and there https://gitlab.com/ubports

**Comment by dobey** [comment]
And https://launchpad.net/ubuntu/+source for the parts that come from Ubuntu upstream.

Ubuntu Touch is not an Android ROM. You don't build an image by building the source of all the projects comprising the distribution, and all the source is not placed in a single repository.
