### ISSUE TITLE
bluetooth with volla phone broke beginning of April

### ISSUE THREAD

**Issue by ulrichard** [ubports/ubuntu-touch#1977]
### Description of the problem
When I received the Volla phone, I was so relieved that I finally had a phone again with an OS that I can trust where bluetooth handsfree in the car worked again.
But since I installed the latest update on April 1st, this feature that is quite important to me broke.

Now if I make or receive a call in the car, I don't hear the other side, nor do they hear me. And even after ending the call, and switching off bluetooth, audio for calls is broken. I have to reboot the device to be able to make calls again.

- Device: Volla
- Channel:RC
- Build:51

### Steps to reproduce
* connect the phone with bluetooth to the car (e.g. Tesla Model S)
* try to make a call (doesn't matter if incoming or outgoing)
* No audio neither in nor out
* When disabling bluetooth, or leaving the car, call audio is now also broke with the headset.
* Need to reboot the device in order to make calls again

### Expected behavior
Before the latest update, making calls in the car with bluetooth handsfree worked very well.

### Actual behavior
No call audio

**Comment by tusch001** [comment]
also on VollaX

**Comment by CesarHerreraG** [comment]
Also on Xiaomi Mi A2

**Comment by Flohack74** [comment]
@ulrichard can you switch to stable channel and see if the problem is gone? RC is release candidate channel, and of course it happens from time to time that a bug slips through.

**Comment by CesarHerreraG** [comment]
In Stable with Xiaomi Mi A2.

**Comment by CesarHerreraG** [comment]
And cant hear the music of the phone in the car.

**Comment by stefan-kalb** [comment]
> @ulrichard can you switch to stable channel and see if the problem is gone? RC is release candidate channel, and of course it happens from time to time that a bug slips through.

I switched to stable today and successfully tested it. Bluetooth calls are working on stable with volla but don't on dev.

**Comment by CesarHerreraG** [comment]
I'm in Stable now.

**Comment by ulrichard** [comment]
After my phone refused to install the stable release for a while, it finally did. Yes, bluetooth calls are working on stable.
I hope somebody can add a comment to this issue, once it's working again on the RC channel.

**Comment by Qetuteq** [comment]
It seems that the bug is now in stable channel too. After upgarding to OTA-23 in stable channel I confirm this bug on Volla.

**Comment by ulrichard** [comment]
> It seems that the bug is now in stable channel too. After upgarding to OTA-23 in stable channel I confirm this bug on Volla.

Yes indeed, after switching to stable two months ago, it was working until a few days ago.

**Comment by Qetuteq** [comment]
Anybody has idea what is the cause? I have not seen anything related to bluetooth in OTA-23 release notes..

**Comment by Barpfotenbaer** [comment]
[Volla Phone on stable v10 AND release candidat v54]

It seems, that the bluetooth HSP-profile is completely missing.

This really annoying bug destroys the most important functionality of a smartphone!

(But perhaps the existence of an audio mixer would already help to unmute the appropriate audio and microphone channels?)

**Comment by Flohack74** [comment]
It seems we found the problem. We are working on a fix now

**Comment by ulrichard** [comment]
With the latest v56 from the RC channel for Volla, BT audio works again.
Thanks for fixing this important feature.
But now, the car doesn't have access to the address book of the phone any longer.

**Comment by JamiKettunen** [comment]
> But now, the car doesn't have access to the address book of the phone any longer.

This is most likely caused by #997 (`Switching contacts backend to QtContacts-SQLite`)
