### ISSUE TITLE
Exit chat in Telegram

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/ubuntu-touch#1981]
If you are in a chat of Telegram oppened with ZwebTelegram and turn the phone 90 degrees, it exits the chat and goes to the screen of all your chats. You can avoid this fixing the orientation.
My phone is Xiaomi Mi A2.

**Comment by lduboeuf** [comment]
More a Morph issue isn't it ?. Is it the web client ?

**Comment by CesarHerreraG** [comment]
No problem anymore. I do not know the reason. I recently did a Reset in System Settings. Thank you very much.
________________________________________
De: Lionel Duboeuf ***@***.***>
Enviado: sábado, 4 de junio de 2022 15:54
Para: ubports/ubuntu-touch
Cc: CesarHerreraG; Author
Asunto: Re: [ubports/ubuntu-touch] Exit chat in Telegram (Issue #1981)

More a Morph issue isn't it ?. Is it the web client ?
