### ISSUE TITLE
Enable FM radio on BQ kernels

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1991]
Krillin: https://github.com/ubports/kernel_krillin/pull/3
VegetaHD: https://github.com/ubports/kernel_vegetahd/pull/4

For Cooler, I created a new repo at https://gitlab.com/ubports-legacy-devices/cooler/kernel_bq_m10
(we need to sort out how to move this into the ubports space)

In any case, merging the PRs is not enough: we also need to upload the kernel binaries (listed in https://forums.ubports.com/topic/7484/new-kernel-builds-call-for-testing) to the system-image server.

**Comment by Flohack74** [comment]
List of kernel update MRs:

- https://gitlab.com/ubports/community-ports/krillin/-/merge_requests/4
- https://gitlab.com/ubports/community-ports/vegetahd/-/merge_requests/3
- https://gitlab.com/ubports/community-ports/legacy-5.1/cooler/device-cooler/-/merge_requests/3

**Comment by lduboeuf** [comment]
Tested with krilin and FM Radio app: It works ;-) The app need to be more solid, but signal is fine.
