### ISSUE TITLE
OTA 23 PIXEL 3a video record. useless file. 

### ISSUE THREAD

**Issue by UriStri** [ubports/ubuntu-touch#2000]
- Device: Pixel 3a
- Channel: stable
- Build: OTA 23 

### Steps to reproduce
Record a Video 
Reproduce it. 

### Expected behavior
Reproduction of the video.

### Actual behavior
Results: Black screen no sound. 
file size small. 
Unable to reproduce it on ubuntu desktop. 

### Logfiles and additional information
No logs.

https://user-images.githubusercontent.com/6860057/177037749-2fdb31a3-ed30-442f-bc16-eb9926da1e00.mp4

**Comment by UriStri** [comment]
Just rebooted the phone. 
It works again...
Thanks.

**Comment by cizya** [comment]
Same problem for me, even after reboot it still doesn't work.
Pixel 3a.
Black screen no sound.
file size small.
Unable to reproduce it on ubuntu desktop.

**Comment by cizya** [comment]
Oups, 

work fine after second reboot !

**Comment by cizya** [comment]
Hello,

Doesn't works again ..... Still same problem with useless files.

**Comment by UriStri** [comment]
YES. 
possible workarround: 
reboot before you rec...
It seems that after a reboot it works.

**Comment by cizya** [comment]
It worked a moment after reboot then it started again.
The durations displayed for defective videos are false: 86 hours displayed for a 30 -second video

**Comment by alistair23** [comment]
Same problem here. Everything indicates that the video recording is working, but when you actually try to re-watch it it's useless

**Comment by fredldotme** [comment]
Are you testing this on stable or devel? Improvements have gone into devel to make sure it works.

**Comment by alistair23** [comment]
Testing on the latest RC

**Comment by alistair23** [comment]
Just updated this morning, the video recording seems to be working now :)
