### ISSUE TITLE
Desktop wallpaper shows rotated images taken with device camera

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#2009]
- Device: Device with physically rotated camera
- Channel: all
- Build: all

### Steps to reproduce
Take a picture with device camera
Go to system settings, and try to set that picture as wallpaper

### Expected behavior
Gallery, preview and final background image are shown correctly

### Actual behavior
Everything is tilted by the camera roation

Please merge:
- https://gitlab.com/ubports/development/core/lomiri-system-settings/-/merge_requests/339
- https://github.com/ubports/unity8/pull/444

**Comment by ivoxavier** [comment]
On the OnePlus 6T is working as expected. Don't know if it is related or not, but I remember a few weeks ago a contact said me that the videos I record with my phone on teleports was always played in landscape (on offical telegram app for ios) even if I recorded them in portrait  with the 6T. Made a video for myself and things are also as it should be, videos recorded in portrait can be viewed in that mode. 

when I get home will test in Fairphone2

Thanks!

**Comment by Flohack74** [comment]
@ivoxavier no, the video recording thingie must be something else. I only fixed picture rotation in Lomiri, system-settings and camera-app :)
