### ISSUE TITLE
phone freezes often when playing music

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#201]
When you play music or the song moves to the next one (Not sure which one) the phone freezes, and won't react to anything other then turning the screen off and on.

**Comment by NeoTheThird** [comment]
What device and version?

**Comment by ChloeWolfieGirl** [comment]
Oneplus One rc-proposed

**Comment by TronFourtyTwo** [comment]
I experienced the same issue, on bacon devel channel

**Comment by ernesst** [comment]
Never got it on Hammerhead

**Comment by stekalb** [comment]
I this still an issue? I can't reproduce it on my bacon (rc r6)

**Comment by Flohack74** [comment]
Closed due to inactivity.
