### ISSUE TITLE
(Bug) GPS not working on Pixel 3a (sargo, stable)

### ISSUE THREAD

**Issue by gabriel-gehrke** [ubports/ubuntu-touch#2011]
- Device: Google Pixel 3a (sargo)
- Channel: stable
- Build: OTA-23 20220617-16778

Apps like Weather and uNav can apparently not use the GPS signal. I made sure that it is enabled and the correct permissions are granted.

**Comment by Flohack74** [comment]
Are you also running Waydroid?

**Comment by gabriel-gehrke** [comment]
No, I am not. I have just installed Ubuntu Touch yesterday and it did not seem to work right from the beginning.

**Comment by gabriel-gehrke** [comment]
Does seem to work now. It took really long to load the location but it finally did (and accurately)
