### ISSUE TITLE
Google Pixel 3a: A/V desync during video recording

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubuntu-touch#2015]
- Device: Google Pixel 3a
- Channel: devel
- Build: 2022-07-25

### Steps to reproduce

- Record a video using the camera-app
- Snap fingers or make a sound associable with happenings on video

### Expected behavior

Video stays synchronized with audio

### Actual behavior

Video and audio are off by around half a second

### Logfiles and additional information

Fixed by: https://github.com/Halium/hybris-patches/pull/58

**Comment by ilyakooo0** [comment]
Seems to be fixed for me

https://user-images.githubusercontent.com/6209627/181483049-c9e0b7fa-b706-4c0b-b244-af9f5514df49.mp4
