### ISSUE TITLE
Wrong network selected

### ISSUE THREAD

**Issue by cliffcoggin** [ubports/ubuntu-touch#2024]
<-----------------------------------------------------------------------------
--------------------------------------------------------------------------------

IMPORTANT: Please file PINEPHONE ISSUES here: https://gitlab.com/ubports/community-ports/pinephone/-/issues

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

**Comment by Flohack74** [comment]
What exactly do you want to say here?

**Comment by cliffcoggin** [comment]
I did type a description of the problem, plus a reference to discussion on the UB Ports forum, but it seems none of it has been saved. This Github system is far too complicated for me to understand, so please delete this entire matter. I give up.

**Comment by Flohack74** [comment]
Its not complicated, its just a text editor with a pre-filled text you can edit :) But doing so...
