### ISSUE TITLE
FEATURE-REQUEST: Allow Launcher To Be Moved Top, Bottom, Left, Right

### ISSUE THREAD

**Issue by BaAl-BaShMu** [ubports/ubuntu-touch#2037]
### Description of the feature

A setting to allow the Launcher to be positioned left, right, top and bottom, not fixed to the left hand side of the screen. Different people prefer different layouts, on Ubuntu desktop I like Gnome classic, on a phone I like my Launcher on the bottom. I know not everyone is the same, so at the least a level of customisation to move the Launcher bar other than just on the left.

**Comment by fredldotme** [comment]
Impossible since it would flip around the other edges which also have their purpose, especially the bottom edge which is controlled by the app.
