### ISSUE TITLE
Bug: Custom background images cannot be removed

### ISSUE THREAD

**Issue by likeadragonmaid** [ubports/ubuntu-touch#2041]
- Device: Mi A2
- Channel: devel
- Build: 2022-09-05

### Steps to reproduce
I added two images to custom backgrounds in system-settings. Later I wanted to remove the images but when I tap on remove images button and select the image I want to remove, the remove button stays greyed out or disabled. Also if I press Cancel button, instead of cancelling the operation, it prompts to select an image from an app to import as new background.

### Expected behavior
It should be able to remove backgrounds that user added themselves.

### Actual behavior
When I tap on remove images button and select the image I want to remove, the remove button stays greyed out or disabled. Also if I press Cancel button, instead of cancelling the operation, it prompts to select an image from an app to import as new background.

### Logfiles and additional information
https://pastebin.com/YctSit55

**Comment by mateosalta** [comment]
https://gitlab.com/ubports/development/core/lomiri-system-settings/-/issues/274

**Comment by cincykid67** [comment]
Device:  Google Pixel 3a
OS build number:  OTA-23 updated 11/9/22

I can confirm this bug exactly as described above.

**Comment by lduboeuf** [comment]
fixed on 20.04
