### ISSUE TITLE
No USB on bonito (Pixel 3a XL)

### ISSUE THREAD

**Issue by GreekSummer** [ubports/ubuntu-touch#2051]
- Device: bonito (but it reports sargo)
- Channel: stable
- Build: 10

### Steps to reproduce
1. Connect to computer with USB
2. Enable Developer Mode in settings after setting a pin code
3. Watch as it fails to detect any sort of device (I used dmesg to monitor USB events)

### Expected behavior
Computer recognizes phone as a USB device

### Actual behavior
Absolutely nothing happens because there are no events shown in dmesg

**Comment by Flohack74** [comment]
@fredldotme any ideas?

**Comment by Flohack74** [comment]
Its bonito, but maybe you flashed the sargo image on it? =)

**Comment by GreekSummer** [comment]
Bonito and sargo use the same kernel, so it's fine.

By coincedence, I re-installed Ubuntu Touch and the issue was solved. Don't know what went wrong the first time.

**Comment by Flohack74** [comment]
The kernel is the same yes, but not the Android build properties. How did you find "reports as sargo"? With getprop?
