### ISSUE TITLE
ubuntu apt-get upgrade

### ISSUE THREAD

**Issue by jhay06** [ubports/ubuntu-touch#2052]
hi , just to report the issue , i ran apt-get upgrade , it downloads fine but during install , it hangs on bluez , then when i reboot the phone , it does not boot , it hangs on my vendor logo

**Comment by lduboeuf** [comment]
Even if idk why you are using `apt upgrade` you might work around that issue with: https://github.com/ubports/bluez-packaging/pull/6#issuecomment-592493552

**Comment by Flohack74** [comment]
You are not supposed to use apt to install anything on your phone. Ubuntu Touch is not working like Ubuntu, and phones are not PCs. We do not support this scenario, except for development, where devs only upgrade certain single packages.
Please use the UBports installer to reinstall your system without data wipe and it will boot again.
