### ISSUE TITLE
Fairphone 4 testing with Multi-Port USB-C Adapter

### ISSUE THREAD

**Issue by Turvaldeon** [ubports/ubuntu-touch#2056]
# Ubuntu Touch Fairphone 4 with Multi-Port USB-C Adapter

- Device: Fairphone FP4
- Channel: 16.04/arm64/android9/devel
- Build: 2022-09-18

## USB-C Adapter

[USB-C Adapter](https://i-tec.pro/en/produkt/c31nanodocklanpd-2/):
- Model number: C31NANODOCKLANPD
- ASIN: B07M6WV1J4

### Working

- LAN
- basic USB (mouse, keyboard)
- HDMI (desktop mode) works way better than in 2022-09-15

#### Audio

- 3.5 mm jack adapter not recognized (sound plays still over phone)
- my other phone (Android) recognizes if a audio jack is connected to the USB-C adapter and then plays sound over USB

#### Desktop mode (HDMI)

- keyboard window button (e. g. on lock screen window or terminal authentication window) doesn't work reliably (doesn't always open keyboard (without USB keyboard connected))
- after disconnecting / connecting USB-C adapter with HDMI or / also after sleep mode:
  * phone crashes frequently and then hangs in boot screen
  * or phone still works, but HDMI not activating correctly anymore (switching black and grey screen)
  * or phone stuck in desktop mode (with onscreen left/right keys) even after disconnecting USB-C adapter
  * or phone stuck in desktop mode (but just grey screen **without** onscreen left/right keys)
- battery loading:
  * doesn't seem to work
  * shows battery at 0%
    + sometimes also shows the real value (blinks in)

#### Keyboard

- Alt + Tab not working (switching applications) (USB keyboard)
- frequently stops working (no input anymore), but also no onscreen keyboard popup
  * not sure what causes it; reconnecting doesn't help

## Misc. Problems

- FP4s screen layout doesn't fit well with the standard Ubuntu Touch layout:
  * camera in middle top covers top bar
  * corners of the screen are rounded and not accounted for by Ubuntu Touch (e. g. "AM/PM" of the clock is partly covered)
- terminal
  * shortcuts: "Cmd" (like: "top", "clear", "ls", ...) don't work
- settings
  * if you search something, then close the search / keyboard with the X, the settings get cramped into one screen with some symbols overlapping and you can't scroll anymore

## Feature suggestions

- customizable top bar (reorder or completely hide tabs)
- add mouse scrolling in top bar
- different PW for terminal `sudo` and the lock screen (i. e. PW for `sudo`, 4-digit-code for lock screen (pattern would be even better, but that isn't even implemented (yet?))
- more easily accessible back buttons (i. e. at the bottom of the screen) would be **really nice**
  * or as a gesture:
    + swipe from bottom?
    + swipe from bottom half of right side (top half for open apps)?
- browser:
  * forward button
  * more keyboard shortcuts (i. e. ALT + RIGHT / LEFT ARROW for history back / forward like in browsers on PC)
- option for: lock / unlock phone by double tap on screen (or anywhere on phone)
- add an English (PC) keyboard, with more easily accessible keys (like tab, and others)

**Comment by Flohack74** [comment]
@Turvaldeon thx for your comprehensive report. I have some issues with it, though:
- We have an official bug tracker for this device here: https://gitlab.com/ubports/porting/community-ports/android11/fairphone-4/fairphone-fp4/-/issues/
- Please break up your summary report into single, workable issues. Some of them are feature requests, and overall this needs detailed triaging in whats a bug, whats a feature, and what will probably stay as it is. If you like I can hint you, based on the past experience, what will be acce3pted by us and what not. Feel free to contact me on Telegram at @Flohack for that.

Thanks again for your effort!

**Comment by Turvaldeon** [comment]
I see, this is the wrong git, and I was wondering why its so empty here ^^
And also sorry for just kinda dumping my notes here, when I find the time, I'll see to look into whats already posted there and then post my stuff accordingly.
And yea, I obviously wouldn't expect that all feature requests would be accepted, but I think just showing that there is interest for certain things is good.
Greetings

**Comment by Flohack74** [comment]
Super thx! Are you already in the TG group for the FP4?
