### ISSUE TITLE
Messaging application cannot display all the information contained inside a vcard

### ISSUE THREAD

**Issue by pnguyen9** [ubports/ubuntu-touch#2059]
I'm not entirely sure if this is a feature request or a bug; more likely the former.

- Device: Volla Phone 22
- Channel:
- Build: 2022-08-18/2

### Steps to reproduce
A relative used the "Share my real-time location" to send me their location as an MMS using an iPhone, which sent a vcard of a contact called "Current location".

### Expected behavior
<del>A map of the current location of the person, or a link to open the map in the browser.</del> Upon opening the vcard, it should display information about the "contact" (a link to open a map in the web browser).

### Actual behavior
The vcard of the "Current location" contact is empty. There's a share/download button on the upper right corner. Upon downloading it. the file is named "2". When I open it on my computer, it contains some metadata:

BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iPhone OS 15.6.1//EN
N:;Curent location;;;
FN:Current location
URL;type=pref:http://maps.apple.com/?ll=5\,-5&q=5\,-5 (replaced actual coordinates with a placeholder)
END:VCARD

**Comment by lduboeuf** [comment]
oh, they use the vcard format for that... I don't think it is a standard solution. Is it working when received on Android devices ?

**Comment by pnguyen9** [comment]
That's a good question. I'll have to try moving my SIM card back to my previous phone and see what it does.

Edit : Just tried again, both on my previous phone and someone else's, and now I understand what vcards are.

On Android, I could open it as a contact details panel and then open the link in the "website" line or something like that. Which made me realise it's also a contact details panel that opens on Ubuntu Touch, but it doesn't know how to display the website link.

**Comment by lduboeuf** [comment]
Yes confirmed address-book-app doesn't support the URL field currently

**Comment by lduboeuf** [comment]
i've created an issue here https://gitlab.com/ubports/development/core/address-book-app/-/issues/209

**Comment by lduboeuf** [comment]
fixed on 20.04
