### ISSUE TITLE
high CPU & no fingerprint with Version 242 update

### ISSUE THREAD

**Issue by KamoCode** [ubports/ubuntu-touch#2069]
With installation of version 242 today, the CPU load increased extremely. In addition, the fingerprint unlock no longer works. The text is also not displayed in the lock screen in the event of several failed scans. 
The condition remained also after multiple reboots. 
As in the screenshot below, these are always the same processes going to 100%. (unity8, biometryd, ubuntu-location, 3x trust-stored-sk)

- Device: FP4
- Channel: Dev
- Build: Ubuntu 16.04 (2022-11-15) - Version 242

screenshot top:
![screenshot20221115_095744420](https://user-images.githubusercontent.com/37157200/202025076-ddf55725-f675-4cfc-ae5a-285da5271f21.png)

Before saving the log I restarted the phone to get possible further information.
[dbus.log](https://github.com/ubports/ubuntu-touch/files/10016399/dbus.log)

**Comment by Flohack74** [comment]
Please update to tomorrow´s devel. It should be fixed then...

**Comment by KamoCode** [comment]
Yes, with the update to 243 today the CPU load is ok again and the fingerprint unlock works fine.
