### ISSUE TITLE
OTG not working

### ISSUE THREAD

**Issue by Jakuko99** [ubports/ubuntu-touch#2072]
### Description of the feature

Ability to connect external peripherals or storage to the phone using USB-C port.
### Illustrations

- Device: Xiaomi Redmi Note 9 Pro
- Channel: Stable
- Build: OTA-24

### Steps to reproduce

Plug into the phone USB mouse, keyboard or USB drive using OTG adapter or directly if the device has USB-C plug.

### Expected behavior

Device is recognized and it is possible to use it (or access storage is case of USB drive).

### Actual behavior

Nothing happens and no power is supplied to connected device either. This feature was working in OTA-23 without problems. No new storage device shown using `lsblk` in terminal either.

**Comment by Jakuko99** [comment]
OTG is working now, only problem is with auto mount of exFAT drives, but I guess there should be some sort of easy fix for that.

**Comment by liujinlong123** [comment]
I flash one plus 6, and the otg doesn’t work either . I wonder the way you make the otg work .

**Comment by Jakuko99** [comment]
Actually it worked fine before OTA-24, now it works only if I reboot the phone by holding down power button until it reboots, but after normal reboot after, it isn't working again. Also it depends on the device and its port, it otg is working at all, you should ask in the group for your device or on the forum.
