### ISSUE TITLE
Sargo 20.04 focal devel updates do not install

### ISSUE THREAD

**Issue by catalyst1987** [ubports/ubuntu-touch#2081]
### Illustrations

- Device:  Sargo
- Channel: 20.04 Focal devel
- Build: r360

### Steps to reproduce
Whenever attempting to install an update, the phone restarts but goes into the Ubuntu recovery menu and the update doesn't install.  Only way to install it is through the Ubports installer.  

### Expected behavior
Updates to install successfully after restart.  

### Actual behavior
Goes into the Ubuntu recovery menu

**Comment by lduboeuf** [comment]
I had success by doing a full reinstall. Meaning reinstalling Android and then UT.

A Copy Paste from @Rondarius in the forum:

This is the steps that I have done to reinstall Android:
Install latest version of adb and fastboot on your pc.
Install the ubports installer
Download the android 9 factory version sargo-pq3b.190801.002 from here:
https://developers.google.com/android/images#sargo
Connect your phone to your pc
In terminal run
adb devices
to check if everthing is working as it should, a serial number will show up after the server is started.
In terminal run:
adb reboot bootloader
Extract the archive sargo-pq3b.190801.002
Open the sargo folder, right click on an empty space and choose Open terminal here(or type the path manually in the terminal to the flash-all(dot)sh script)
In the terminal run:
fastboot devices
to check that the phone is recognized by the pc, the same serial number will show up as the one that adb output
In the terminal run
sudo ./flash-all.sh
enter your sudo code and it will take a moment to reinstall Android.
After the phone reboots, enter developer mode and tick Usb debugging
Once again run in terminal
adb reboot bootloader
When the phone enters the bootloader run the ubports installer and follow the steps.

**Comment by catalyst1987** [comment]
> I had success by doing a full reinstall. Meaning reinstalling Android and then UT.
> 
> A Copy Paste from @Rondarius in the forum:
> 
> This is the steps that I have done to reinstall Android: Install latest version of adb and fastboot on your pc. Install the ubports installer Download the android 9 factory version sargo-pq3b.190801.002 from here: https://developers.google.com/android/images#sargo Connect your phone to your pc In terminal run adb devices to check if everthing is working as it should, a serial number will show up after the server is started. In terminal run: adb reboot bootloader Extract the archive sargo-pq3b.190801.002 Open the sargo folder, right click on an empty space and choose Open terminal here(or type the path manually in the terminal to the flash-all(dot)sh script) In the terminal run: fastboot devices to check that the phone is recognized by the pc, the same serial number will show up as the one that adb output In the terminal run sudo ./flash-all.sh enter your sudo code and it will take a moment to reinstall Android. After the phone reboots, enter developer mode and tick Usb debugging Once again run in terminal adb reboot bootloader When the phone enters the bootloader run the ubports installer and follow the steps.

I hope they come up with a fix for it because I have no desire to flash android back on and then run through the installer again.  But good to know that there is a workaround.  thanks!

**Comment by lduboeuf** [comment]
@catalyst1987 can we close that issue now ?.

**Comment by catalyst1987** [comment]
> @catalyst1987 can we close that issue now ?.

I guess if there is no intention to fix this then it can be closed.  I personally think that asking people to reinstall android and then Ubuntu touch is rather cumbersome.  If it won't be fixed then there isn't a whole lot of point in allowing users to change the update channel if it will end up bricking the application of updates and cause them to go through a process of reinstalling android and then Ubuntu touch.  Just my opinion though.

**Comment by lduboeuf** [comment]
> > @catalyst1987 can we close that issue now ?.
> 
> I guess if there is no intention to fix this then it can be closed. I personally think that asking people to reinstall android and then Ubuntu touch is rather cumbersome. If it won't be fixed then there isn't a whole lot of point in allowing users to change the update channel if it will end up bricking the application of updates and cause them to go through a process of reinstalling android and then Ubuntu touch. Just my opinion though.

Idk if it can be fixed in other way than reinstalling all. That makes me wonder how users that already flashed P3a with 16.04 last year do ?

**Comment by catalyst1987** [comment]
> > > @catalyst1987 can we close that issue now ?.
> > 
> > I guess if there is no intention to fix this then it can be closed. I personally think that asking people to reinstall android and then Ubuntu touch is rather cumbersome. If it won't be fixed then there isn't a whole lot of point in allowing users to change the update channel if it will end up bricking the application of updates and cause them to go through a process of reinstalling android and then Ubuntu touch. Just my opinion though.
> 
> Idk if it can be fixed in other way than reinstalling all. That makes me wonder how users that already flashed P3a with 16.04 last year do ?
> 

Not sure as I went straight to 20.04. I would have thought it would be fixable since applying the updates through the ubports installer works fine.  

If doing a full reinstall once solves it and I won't have to do it again after changing update channels then I could live with that. It would just be frustrating if I had to do a full reinstall every time I decided to change the update channel.

**Comment by lduboeuf** [comment]
> If doing a full reinstall once solves it and I won't have to do it again after changing update channels then I could live with that. It would just be frustrating if I had to do a full reinstall every time I decided to change the update channel.

Yes only have to do it once

**Comment by catalyst1987** [comment]
I installed the latest devel update using the installer and now i can install the latest devel updates normally again so didnt need to reinstall Android and Ubuntu Touch to my phone.  this issue can be closed.
