### ISSUE TITLE
GPS not working on OnePlus 6 using Giffgaff

### ISSUE THREAD

**Issue by drgnomage** [ubports/ubuntu-touch#2082]
- Device: OnePlus 6
- Channel: Stable
- Build: OTA-24

### Steps to reproduce
Turn on location services.
Use any application that requires GPS and grant it access.

### Expected behavior
GPS to work.

### Actual behavior
Nothing happens even after reboot or swapping to a different sim on the same provider.

### Logfiles and additional information
I couldn't see any relevant logs that contained an error, only that access was granted.

**Comment by Flohack74** [comment]
1) What is GiffGaff?
2) Have you been using Waydroid before trying to use GPS?

**Comment by drgnomage** [comment]
1.  GiffGaff is a mobile service provider in the UK that "piggyback" off O2's network.
2.  I had not.




Sent with Proton Mail secure email.

------- Original Message -------

**Comment by ivoxavier** [comment]
Keep in mind that Ubuntu Touch currently does not have AGPS, so if you're trying to get GPS inside a building is not going to work. 

I've an OnePlus 6T and GPS works pretty fast outside.

**Comment by drgnomage** [comment]
It was so long ago now that I don't remember if I was testing it outside or inside.  I'm now on pmOS which I'm daily driving so I don't want to reflash.  Feel free to close.

**Comment by ivoxavier** [comment]
No problem :)

I don't have the permission to close it. Could you close it for us? Thank you!

**Comment by drgnomage** [comment]
Sure, no worries.  Cheers for touching base on this!
