### ISSUE TITLE
Clipboard copies formatted text, which stops the ability to paste inside the main Messages.

### ISSUE THREAD

**Issue by adim-att** [ubports/ubuntu-touch#2090]
All mobile OS disables text formats to be copied within the clipboard, that's because SMS doesn't support html content. 
Please look into this, because I can't copy to Messages until I unformat it, which is a tedious process.

**Comment by lduboeuf** [comment]
Please provide context, step to reproduce

**Comment by adim-att** [comment]
> Please provide context, step to reproduce

I wouldn't be able to copy text from my Facebook Messenger -at the browser- to the Messages App -for sim card-. The `paste`  option won't be visible.
Although, I am able to do that if I copy text from Notes onto the Messages App. 

The mainly presumed reason for that is because the text is only able to be copied into the clipboard as long as it's unformatted. The clipboard in this case has either issues with encoding or with its mark up language whatsoever. 

The other assumption is as follows: The clipboard actually copies the text, but formatted and it keeps it that way.  While the Messages App is unable to input formatted text, so the clipboard option won't show `paste` as available.

**Comment by lduboeuf** [comment]
@jindiggs Can you Paste your clipboard when using the extended keyboard ( long press on space key, then tap on the paste icon ) while on messaging app or elsewhere ?

**Comment by adim-att** [comment]
> @jindiggs Can you Paste your clipboard when using the extended keyboard ( long press on space key, then tap on the paste icon ) while on messaging app or elsewhere ?

I have just tested again, and the problem is no longer there !! Both with touch paste and keyboard as you said. 

I have no clue as to why it happened to me a few days ago ..

**Comment by lduboeuf** [comment]
yes clipboard does not seems to work every time. At least with the keyboard it appears to be more stable

**Comment by adim-att** [comment]
> yes clipboard does not seems to work every time. At least with the keyboard it appears to be more stable

Thanks for letting me know. Should I close this ticket ?

**Comment by lduboeuf** [comment]
Yes i close it for now. And iif ssue persist on 20.04, you could create a new one ( there is no global issue tracking for 20.04) yet
