### ISSUE TITLE
issue/feature request

### ISSUE THREAD

**Issue by develperbayman** [ubports/ubuntu-touch#2091]
this issue is actually very obvious to everyone ubuntu touch permissions is all screwed up (so libertine is useless)

 also to be more linuxy UBT should have apt work right out of the box also shell scripts should just work

 i understand its locked to keep the system files from being corrupted but thats the point of sudo these should be very critical issues because without these things we are basically using a really expensive glorified flip phone just in touch format

 this could be the bridge from mobile to pc seamless ....but alas.... 

i would rather see these things work before any other updates ......

dont get me wrong this is awesome and could be the best dev mobile tool out there .....

sorry if this isnt the place and thanks everyone for all your hard work!   

 edit: is it possible for libertine to just work in the background then when you apt install something it just works? libertine front end to just manage installed programs?

**Comment by dobey** [comment]
> sorry if this isnt the place and thanks everyone for all your hard work!

It is not appropriate to be rude and demanding, in any place, regardless of whether you follow it with a "thanks." You clearly disagree with the fundamental design of Ubuntu Touch, so it seems odd for you to thank us for all the hard work, which you don't actually appreciate.

This isn't an issue report or feature request, but a rant.  _Ubuntu Touch is not a traditional PC Linux distribution, and phones are not traditional PCs._ That isn't going to change. I'm closing and locking this. If you have a valid, specific, and actionable issue with Libertine, please open an issue for that. I'm going to close and lock this issue. Please do not post other rants on here, which are not valid reports, nor actionable. Thanks.
