### ISSUE TITLE
Do you guys ship DEBUG-KERNEL in production builds?

### ISSUE THREAD

**Issue by ATroubleshooter** [ubports/ubuntu-touch#2094]
- Device: onclite (Redmi 7)
- Channel: Stable
- Build: OTA 24

### Steps to reproduce
Turn on the device.

### Expected behavior
To work fine.

### Actual behavior
Everything works relatively well.

### Logfiles and additional information
I'm asking, because I'm seeing  like that in dmesg output:
```
[    0.000000] ** If you see this message and you are not debugging    **
[    0.000000] ** the kernel, report this immediately to your vendor!  **
[    0.000000] **                                                      **
[    0.000000] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    0.000000] **********************************************************
```
The kernel version is:
```
Linux version 4.9.214-perf+ (root@runner-jhcjxvh-project-23350609-concurrent-0) (Android (6875598, based on r399163b) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)) #1 SMP PREEMPT Tue Apr 19 17:00:02 UTC 2022
```

Thank you.

Yours, Alex

**Comment by fredldotme** [comment]
Huh. This device is not maintained by a core developer, so no idea. Please contact your device maintainer though to fix this situation, debug kernels have no reason to exist in production devices.

**Comment by ATroubleshooter** [comment]
Hi. Thanks for agreeing with me on that.
Should I close the issue?

Regards, Alex
