### ISSUE TITLE
Front Camera Image get 90º rotated right

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#21]
Pictures taken with Front camera get rotated at 90º right.

**Comment by Flohack74** [comment]
Confirmed, still an issue.

**Comment by ebeton-ro** [comment]
Confirmed on r26 build also

**Comment by dark-eye** [comment]
This might actually be an issue in the camera app and might suggest an issue with the orientation sensor as the video preview is rotated based on the orientation when the camera first loaded : 
`
ViewFinderView.qml:265:                 orientation = Screen.primaryOrientation === Qt.PortraitOrientation  ? -90 : 0;
`

**Comment by Flohack74** [comment]
Sorry, does not work for me... :( Does it need a camera app update?

**Comment by dark-eye** [comment]
Hey @Flohack74   can you test if [this](https://my.owndrive.com/index.php/s/9VWDmqIpwU5qTwJ)  solves changes the results?

**Comment by Flohack74** [comment]
Well its not perfect but different xD:

![grafik](https://user-images.githubusercontent.com/16186470/34223100-63c4577a-e5be-11e7-839f-0320952be5bd.png)

**Comment by dark-eye** [comment]
Great! I've rotated it the other way just to make sure it`s the issue, that means that the fix for nexus is the issue! I can disable the fix and it should be OK.

However i think that it should be tested on all other devices as changing this might surface issue that were hidden on other devices.

**Comment by mariogrip** [comment]
This works on devel for me?

**Comment by Flohack74** [comment]
@mariogrip My N5 is not your N5 ^^

**Comment by mariogrip** [comment]
What? if you turn off flash it works..... but setting it on auto fails...

**Comment by Flohack74** [comment]
Wait a sec did I use the wrong phone xD @dark-eye @mariogrip forget my test. I tested on FP2 so the rotation picture is invalid

**Comment by mariogrip** [comment]
Fix is now committed, building new hammerhead image: https://ci.ubports.com/job/daily-hammerhead/420/console

**Comment by mariogrip** [comment]
So the camera app is not at fault here, it's beacuse it tries to set a invalid value, and that result in that ANY value dies.... so what i did is just to let it set the other values. but this needs to be fixed on xenial at some point, but it works for now

**Comment by Flohack74** [comment]
![grafik](https://user-images.githubusercontent.com/16186470/34228083-bbf7e2f2-e5cf-11e7-9ff1-25310d395280.png)

Better. Is it normal that selfie pictures are mirrored?

**Comment by NeoTheThird** [comment]
Works, thanks everyone

**Comment by dark-eye** [comment]
yes I have the same mirroring issue on my device (meizu pro ) I'll open an issue about it in the camera app

**Comment by Flohack74** [comment]
@mariogrip is this av framework specific to hammerhead or do we have to cross-test a nothter device(s)?

**Comment by Flohack74** [comment]
@dark-eye That might be also intentional: To better select the picture its good if the camera moves in the same way as you move your hand. However, the camera "sees" the picture from the other side. So I would keep it for the moment.

**Comment by mariogrip** [comment]
@Flohack74 the framework is global, but only hammerhead has been promoted to rc with this patch so no need to test others devices before ota3. but this should not effect others devices anyway.
