### ISSUE TITLE
Not all videos are shown

### ISSUE THREAD

**Issue by speedracer08861** [ubports/ubuntu-touch#211]
- Device: Turbo
- Channel:ota1 stable
- Build:Turbo ota1

## Steps to reproduce

1. ...Install more than 200 videos in phone under the video scope.
2. ... You will see that only 100 are viewable
3. ...The rest of the videos are no where in sight

## Expected behavoir

... All videos should be displayed no matter how many you have

## Actual behavior

... only 100 are viewable

## Logfiles and additional information

...

**Comment by speedracer08861** [comment]
I have over 200 videos are only a 100 or so are displayed. The others one are displayed only by search

**Comment by NeoTheThird** [comment]
Hey @speedracer08861, thanks for reporting this issue, but could you please edit the first comment (click on the pen in the top right corner) to include all the important information? Please fill in the prefilled text and remove the unnecessary headings. If you're interested, you can also read our guide on writing a good bug report: https://docs.ubports.com/en/latest/contribute/bugreporting.html

Thanks again for reporting :)

**Comment by speedracer08861** [comment]
I currently have 500 videos on my phone now and only a 100 are displayed in the video scope, but I have over 3000 pictures and they are all displayed perfectly

**Comment by dobey** [comment]
Is this in the "Video" scope, or the "My Videos" scope? The former is an aggregator show will likely show fewer results from each scope it queries. Do they all display in the Gallery app?

**Comment by NeoTheThird** [comment]
Closing, because scopes are going to be removed https://github.com/ubports/unity8/issues/14
