### ISSUE TITLE
no audio output on Volla X (focal / 20.04 RC and Dev)

### ISSUE THREAD

**Issue by tusch001** [ubports/ubuntu-touch#2114]
BUG-REPORT

- Device: Volla X
- Channel: Focal 20.04 RC (2) and DEV (647)
- Build: r647
- Build Description: lineage_halium_arm64-userdebug 10 QQ3A.200805.001 254 test-keys
- Kernel: 4.9.190+ (arm64)

### Steps to reproduce

I switched from stable 16 to focal 20.04, cleared all data

### Expected behavior

have audio

### Actual behavior

no audio output, none at all
- no ringtone with calls, no audio within calls
- no audio in music / video playback

### Logfiles and additional information

logviewer app: pulseaudio-trust-stored says
```
Error during initialization and startup: Dynamic exception type: std::system_error
std::exception::what: No such file or directory
```

**Comment by cybercash23** [comment]
Same at Poco X3 Pro - no audio, no ringtone

**Comment by tusch001** [comment]
@cybercash23 
Due to recommendations from the UT Forum to report issues with focal / 20.04 over there I opened a post there

https://forums.ubports.com/topic/8727/no-audio-output-on-volla-x-focal-20-04-rc-and-dev/1

So far no solution but I think that's the place for follow-ups

**Comment by tusch001** [comment]
@whoever fixed this - Thank you.

Audio works in Dev Version 273
