### ISSUE TITLE
qtwebengine with hardcoded cmdline is annoying for porters

### ISSUE THREAD

**Issue by novhy** [ubports/ubuntu-touch#2119]
try latest ubport rootfs in focal,
feel morph browser slower than old xenial,

check log, and chrome://gpu
             
[47659:47681:0321/012214.990357:ERROR:gpu_init.cc(145)] Vulkan not supported with in process gpu                   

morph-browser --ignore-gpu-blocklist --enable-features=Vulkan --use-vulkan --enable-gpu-rasterization --disable-composited-antialiasing --disable-smooth-scrolling --enable-accelerated-video-decode --enable-features=MojoVideoDecoder --browser-subprocess-path=/usr/lib/aarch64-linux-gnu/qt5/libexec/QtWebEngineProcess --application-name=morph-browser --no-sandbox --enable-threaded-compositing --disable-speech-api --enable-features=AllowContentInitiatedDataUrlNavigations,NetworkServiceInProcess,TracingServiceInProcess,MojoVideoDecoder --disable-features=MojoVideoCapture,FontSrcLocalMatching,UseSkiaRenderer,DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,SmsReceiver,WebPayments,WebUSB,PictureInPicture --use-gl=egl --in-process-gpu --gpu-preferences=OAAAAAAAAAAoAABQAAAAAAAAAAAAAAAAAABgAAAAAAAYAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAIAAAAAAAAAA== --use-gl=egl

where is annoying cmdline come from?
because --in-process-gpu i cannot use vulkan
--ignore-gpu-blocklist is become completely ignored too

and its show alot gpu workarround that not shown in xenial

some of them:
Adreno 5xx support for EXT_multisampled_render_to_texture is buggy on Android < 7.0: [612474](http://crbug.com/612474)
Applied Workarounds: disable(GL_EXT_multisampled_render_to_texture)
Adreno 5xx support for EXT_multisampled_render_to_texture is buggy on Android 7.1: [663811](http://crbug.com/663811)
Applied Workarounds: disable(GL_EXT_multisampled_

im suggesting, make porters happy with not jailing them in hardcoded configuration, alot of device out there with different characteristic,different driver version,,

the env QTWEBENGINE_CHROMIUM_FLAGS
is useless, because porters is in jail

**Comment by fredldotme** [comment]
If you would stop overdramatizing the situation and actually understood what was happening under the hood you'd have a better life.

Simply speaking: There is no Vulkan integration anywhere in UT *yet*.

**Comment by novhy** [comment]
![screenshot20230321_040721754](https://user-images.githubusercontent.com/7148317/226466524-ca2ad1ca-955c-4bad-94a6-3f4a45131bbf.png)

many people often think badly of other people's intentions.
whether vulkan worked before, it's up to you to assume,
closing, got what to do
