### ISSUE TITLE
OTA-25 galaxy s3 neo + must be turned on 2 times before launch the system

### ISSUE THREAD

**Issue by mosiubuntu** [ubports/ubuntu-touch#2126]
When i turn on the device, it shows the galaxy pic then the ubuntu touch animation and then it turns off by itself. So i have to turn it on again and after that it starts.

**Comment by lduboeuf** [comment]
confirmed on many devices.

**Comment by lduboeuf** [comment]
duplicate of https://github.com/ubports/ubuntu-touch/issues/2124
