### ISSUE TITLE
Wrong font used clock and battery percentage in panel

### ISSUE THREAD

**Issue by mtbu** [ubports/ubuntu-touch#2142]
- Device: FP3
- Channel: 20.04 Development
- Build: r36

### Steps to reproduce
Normal device usage.

### Expected behavior
The panel at the top should use the Ubuntu font as per the rest of the UI.

### Actual behavior
A different font is used for the clock and battery percentage. The 1 and 7 are obviously different, other numbers are more subtle. The indicators/pulldown menu use the Ubuntu font as expected.

![screenshot20230625_144104890](https://github.com/ubports/ubuntu-touch/assets/25207962/28794582-c5f8-4615-821f-ec388756619a)

**Comment by mateosalta** [comment]
https://gitlab.com/ubports/development/core/lomiri/-/merge_requests/108

**Comment by mtbu** [comment]
Yes that has fixed it, thanks mateosalta!
