### ISSUE TITLE
libhybris  android12.0

### ISSUE THREAD

**Issue by LXL94** [ubports/ubuntu-touch#2153]
The device I want to port, only android 12.0 environment, and in android system using allocator_hidl_4.0 interface and mapper_hidl_4.0. in the process of porting reported error: gralloc4: Buffer: 0x7f8800c540 has not been registered with Gralloc, not sure if this is related to libhybris or not?

1、In github I found that libhybris is only supported up to android-9.0
https://github.com/ubports/libhybris/blob/xenial/hybris/configure.ac

2、Replacing only libhybris-related libraries while keeping all the system's files intact will end up reporting gralloc-related errors, although there are different behaviors.
Note: libhybris-*.so are from separate images of different devices from ubports (e.g. jingpad, oneplus nord 3 5G, Samsung Galaxy A33 - A53, etc.)
https://gitlab.com/ubports/porting/community-ports/android12

Based on the above, do I need to compile libhybris for my device?
Is anyone else experiencing a similar situation？

**Comment by fredldotme** [comment]
Everything moved to GitLab as indicated by the About section on the repository page, so the GitHub xenial link you posted is out-of-date.

Please head over to the the porting group on Telegram: https://t.me/ubports_porting
