### ISSUE TITLE
FairPhone2 Camera Module upgrade is not working

### ISSUE THREAD

**Issue by Fuchur777** [ubports/ubuntu-touch#232]
- Device: FP2
- Channel: Stable
- Build: 15.04 r1

## Steps to reproduce

1. Update New Camera Modules for FairPhone ( [https://www.fairphone.com/en/upgrade-fairphone2-camera/](https://www.fairphone.com/en/upgrade-fairphone2-camera/) )
2. Reboor Device
3. Open Camera app

## Expected behavoir

To take pictures

## Actual behavior

Giving error
![photo_2017-09-05_10-19-06](https://user-images.githubusercontent.com/798891/30056215-33f5326a-9232-11e7-9ad4-6be6e1e4e7b1.jpg)

## Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubports-touch/files/1277011/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubports-touch/files/1277009/UTlogcat.txt)

**Comment by olisax** [comment]
If it can help, here is the list of [updated drivers](https://github.com/FairBlobs/proprietary_vendor_fairphone-fork/pull/2/commits/59d221c231fafb88d749efa6b6df9eea86a9e9ba) that were incorporated in the [LineageOS port](https://github.com/LineageOS/android_device_fairphone_FP2/commit/331f4cee708094e6eceb009f8216ca8a62ca4b06) for FP2 to support the new camera.

**Comment by jaapjansma** [comment]
I also have this issue with the Fairphone production batch of late august 2017 (which does include the new camera)

**Comment by NeoTheThird** [comment]
A new devel build has been triggered which includes the fix in the current state. It has been a lot more work than we anticipated, and there's still one issue left: Pictures and Videos captured with the front camera will be rotated by 180°, but I guess it's better than nothing.

https://github.com/ubports/android_device_fairphone_fp2/pull/9
https://github.com/ubports/android_system_core/pull/2

**Comment by tforgione** [comment]
Tested on my new Fairphone 2: works fine !

> but I guess it's better than nothing

It's waaaaaaaay better than nothing !

**Comment by NeoTheThird** [comment]
Because we're so close to release, the front-camera rotation-issue (#370) will remain.

My testing for the patch included taking pictures both with the front- and rear-camera of the old and the new fairphone, as well as switching the modules between old and new devices. No issues found, general stability and image quality seems OK.

Presumed fixed.
