### ISSUE TITLE
Graphic bug in scopes with dash background on (text unreadable and icons not visible)

### ISSUE THREAD

**Issue by mymike00** [ubports/ubuntu-touch#237]
- Device: BQ Aquaris E4.5
- Channel: rc
- Build: r3

## Steps to reproduce

1. switch on the dash background
2. go to the dash
3. use different scopes

## Expected behavoir

all the text, icons, etc... should be visible
other text are white but some are black and they aren't visible at all
also in some scopes' header icons are white and if the header as a white background they aren't visible.
without the dash background enabled icons in scopes' header are black by default, but they became white if the bg is too dark. there should be something like that, if the bg is too bright icons should become black/dark

## Actual behavior

some text, icons, etc... aren't very visible

Header (icons visible only when focused):
![screenshot20170910_233407520](https://user-images.githubusercontent.com/28359593/30253369-a5ea8492-9683-11e7-92a0-2cf01aa6ed10.png)

and text:
![screenshot20170910_233326495](https://user-images.githubusercontent.com/28359593/30253322-dad28e1c-9682-11e7-97f1-da9a0cd16b7b.png)

**Comment by Flohack74** [comment]
Yes thats true, as scope designers never expected to have smth different than a plain white background. We are currently researching a replacement for scopes, so probably we wont invest too much time in fixing this...

BR

**Comment by mymike00** [comment]
then this could be closed as scopes will be removed
