### ISSUE TITLE
no mms notification when  cellular data is disabled

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#239]
- Device: krillin
- Channel: stable
- Build: 1

## Steps to reproduce

Make sure "cellular data" is disabled.
From another phone send a MMS. 
nothing is received.

## Expected behavior

A sms notification is received.

## Actual behavior

nothing is received, mms is lost

**Comment by Flohack74** [comment]
I quote myself here:

> Well cellular data is necessary to send/receive the MMS, see for example: https://forum.telus.com/t5/Mobility-Services/Why-do-I-need-Cellular-Data-turned-on-to-send-receive-MMS/td-p/39622
> Please also read this https://en.wikipedia.org/wiki/Multimedia_Messaging_Service fully to understand the service.

That means, technically it is not possible to receive an MMS without mobile data. But of course there should be an SMS notifications, but this could be provider dependent.

**Comment by lduboeuf** [comment]
this issue is already known, see `Current Issues` section https://wiki.ubuntu.com/Touch/Specs/MMSInfrastructure

**Comment by rik-shaw** [comment]
With devel channel updates as of 2021-12-17 I can confirm this is fixed. I disabled cellular data and wifi and sent a photo MMS to UT. I got the message that there was a new MMS with the filesize and a download link. I then enabled cellular data and clicked "Download" link and image was delivered.

**Comment by gbdomubpkm** [comment]
Fixed on Volla RC 43.
