### ISSUE TITLE
rotation is goofy when in upside-down orientation

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/ubuntu-touch#257]
- Device: mako
- Channel: devel
- Build: not sure

## Steps to reproduce

1. ...use phone
2. ...flip 180 degrees so power plug usb port is facing the sky
3. ...try swiping upper, lower, left or right and the menus are not in the right orientation

## Expected behavoir
to be the same behaviour as the other 3 sides
...

## Actual behavior
acts goofy
...

## Logfiles and additional information

...

**Comment by mariogrip** [comment]
Could Explain "acts goofy"

**Comment by wayneoutthere** [comment]
yes.  it doesn't auto-rotate.
that is goofy. but maybe that's designed goofiness for a reason

**Comment by wayneoutthere** [comment]
to be more precise, try like this: have phone facing normal top up (earphone jack up).  Then immediately flip 180 degrees so that the usb charger is up.  It will remember the oritenation of the first one.  NOw try on the side so that it's in horizontal mode.  Now quickly flip it so the usb charger is up.  It will remember the last one (horizontal)

**Comment by mateosalta** [comment]
seems to work proper for me, do you mean when you pull the top bar down?

**Comment by UniversalSuperBox** [comment]
Resurrect... **BUG REPORT!!!**

The Nexus 4 is set to never rotate to the bottom-up orientation on purpose. It's so people don't put the phone to their ear the wrong way, I assume. It might be a bug that this orientation is *allowed* on other devices, it is correct for it to be prohibited on the Nexus 4.

**Comment by mateosalta** [comment]
Aw, no :( I always turn my phone around upside down - so you can charge out the front
