### ISSUE TITLE
Flashlight 

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubuntu-touch#262]
- Device:Nexus 4
- Channel: Stable
- Build: Rev 1

## Steps to reproduce

1. ...Display top bar
2. ...Go battery menu

## Expected behavoir

......Flashlight activation button

## Actual behavior

...No flashlight activation button

## Logfiles and additional information

...

**Comment by BlueKenny** [comment]
Fixed in OTA 2

**Comment by NeoTheThird** [comment]
Good catch, thanks
