### ISSUE TITLE
Sound with slimport

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubuntu-touch#269]
- Device:Nexus 4
- Channel:Stable
- Build:Rev. 1

## Steps to reproduce

1. ...connect device to monitor
2. ...
3. ...

## Expected behavoir
...Desktop mode

## Actual behavior

The audio output is through the device

## Logfiles and additional information

...

**Comment by dobey** [comment]
Looking at pulseaudio-modules-droid it seems that audio on slimport is not supported at all there. That is where this needs to be resolved primarily.
