### ISSUE TITLE
Lock screen disables USB debugging and MTP

### ISSUE THREAD

**Issue by paulmueller** [ubports/ubuntu-touch#272]
- Device: krillin (Aquaris 4.5)
- Channel: stable
- Build: r2

Currently, whenever the device is connected to a PC it must be unlocked to allow USB debugging or MTP. This is a convenient security feature.

However, it would be nice to keep MTP or USB debugging enabled even after the (automatic) lock-screen comes up again. For copying large files or during a hacking session, a workaround is to disable the lock screen temporarily via the battery settings or to use the "Active Screen" app from the Ubuntu Store.

One way of accomplishing this would be a switch that allows to keeps MTP or debugging alive until the USB cable is unplugged.

**Comment by dobey** [comment]
Are you saying if you connect to MTP with the screen unlocked, it stops working immediately when the screen is locked?

Likewise with developer mode?

For developer mode, you simply need to unlock the screen the first time, to accept the host key for adb. Once it is accepted, you can connect to the phone again at any time, from the same PC, without unlocking the screen. You do still need to unlock the screen for MTP though, as there is no such ACL for it, but only to initially mount the device. Once the device is mounted with MTP on the PC, it should continue to work.

**Comment by Flohack74** [comment]
Just tried, MTP stays active if once unlocked...

**Comment by paulmueller** [comment]
I am not able to test this currently. Might be related to #522.

**Comment by paulmueller** [comment]
I can confirm that it works as expected with frieza (not krillin).

**Comment by paulmueller** [comment]
Works with OTA5 on krillin as well.
