### ISSUE TITLE
Low Audio on speaker mode and stuttering

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-touch#277]
- Device: hammerhead
- Channel: devel
- Build: r155

## Steps to reproduce

just make a call an turn on speaker

## Expected behavoir
No stuttering
Higher volume

## Actual behavior

Suttering
Low Volume

**Comment by Flohack74** [comment]
Please do not add it to a milestone which has been closed...

**Comment by rubencarneiro** [comment]
Fixed

**Comment by NeoTheThird** [comment]
Works now
