### ISSUE TITLE
Enable autocompletion in the shell

### ISSUE THREAD

**Issue by doniks** [ubports/ubuntu-touch#278]
- Device: deb
- Channel: devel
- Build: ?

Command auto completion in the shell is for me an important part of a "real linux" experience. It makes working in the shell so much more efficient and this is how basically every other "real linux" (not android) distribution comes out of the box.
 
## Steps to reproduce

1. Open terminal app
2. type a partial command like ``libertine-container-manager c`` 
3. tab the display twice (acts as "Tab key")

## Expected behavoir
I expect that tab shows me the possible ways to complete the command. In this example the two subcommands ``create`` and ``configure``.

## Actual behavior
bash completion does not work 

## Logfiles and additional information
I can enable it with making the root fs writable and then:
 
    sudo apt update
    sudo apt install bash-completion 

Please preinstall this package.

**Comment by mariogrip** [comment]
Fix pushed https://github.com/ubports/ubuntu-touch-meta/commit/37fbf3eebe4de3d8577b1f313aacbb369342bdcd

**Comment by Flohack74** [comment]
Please close only after QA approved, thats the new workflow ;)
