### ISSUE TITLE
GPS problem

### ISSUE THREAD

**Issue by HendriXXX** [ubports/ubuntu-touch#282]
- Device: Nexus 4 (mako)
- Channel: Stable (rc, devel also)
- Build: r1

## Steps to reproduce

1. try to get your location with any gps app

## Expected behavoir
In few minutes you should be seeing coordinates or your location on map.

## Actual behavior
Nothing happens. uNav and SensorsStatus shows instantly some strange location (lat. 65.2333, log. 25.3833) far away (~20km). I tried at balcony also, same result and no location updates.

## Logfiles and additional information
When I run test_gps from terminal, I get location fix (cold start ~7min to fix, re-try ~30sec to fix) and if I open SensorsStatus right after fix, it shows location right and updates it.

uNav and web-browser shows also my real location IF I immediately switch from terminal to an app. In apps location updates when I'm moving. Sometimes it hangs to fake position and sometimes not.

Behavior is same with Wifi on or off.

Without test_gps running in backround:
![nofix](https://user-images.githubusercontent.com/30898849/31117989-83a4202e-a834-11e7-9638-24db6c22af02.jpeg)

test_gps running in terminal:
![fix-testgps](https://user-images.githubusercontent.com/30898849/31118017-a084dd46-a834-11e7-9e64-c174dafea59f.jpeg)

SensorsStatus fix with test_gps running in backround:
![fix-sensorsstatus](https://user-images.githubusercontent.com/30898849/31118049-b683918c-a834-11e7-8ec7-0cdabbe0f473.jpeg)

I tried to dig some related logs, but I didn't find any.

**Comment by ernesst** [comment]
Unfortunatly, i cannot reproduce it with the latest devel image on a fresh install.

**Comment by ernesst** [comment]
Did you replace some component inside the phone ? What version is your Nexus 4 - 8 or 16g ?

**Comment by HendriXXX** [comment]
No, I havent touch inside anything else than battery. I replaced it year ago. Gps works with Canonical image. It is 16Gb version.

**Comment by ernesst** [comment]
Look at these posts : 
https://bugs.launchpad.net/ubuntu/+source/location-service/+bug/1368647
https://bugs.launchpad.net/touch-preview-images/+bug/1367884
https://wiki.ubuntu.com/Process/Merges/TestPlan/location-service#Forensics

Some log file are mentioned, try to pull some, i'll try to compare with mine (8 giga). 

Between Canonical image and Ubports, did you flash the radio per chance ?

**Comment by HendriXXX** [comment]
Ok. Thanks! I will try to find something useful from logs to compare. I didn't flash any new radio. I dont know if that Android 4.4.4 has anything to do it. I had that installed for a while between Canonical and Ubports.

**Comment by HendriXXX** [comment]
I have been trying to solve this gps problem. I managed to get it work couple of times without "test_gps" running backround.
I did run "sudo service ubuntu-location-service status" command and it said service wasnt running so I started it and then GPS worked right away. But it worked only couple of times.

Ernesst, what is your baseband (modem) version?
My version shows here.. M9615A-CEFWMAZM-2.0.1701.03
![nexus4-fastboot](https://user-images.githubusercontent.com/30898849/31848343-2d247330-b639-11e7-950c-8371daae7ca0.jpeg)

Today I try to gather some log info..
Can I change baseband somehow? Long time ago in Android- world I flashed some zip files from recovery when I wanted to try different modems. Is it possible in UT also?

I'm trying to get this phone to my wife, because she want's to try UBports. For she, GPS is a big "must work". She is tired of Android phones and any iphones arent even option for us!

**Comment by HendriXXX** [comment]
I did some testing with uNAV:
- Fresh reboot, phone **NOT CONNECTED** to computer by USB, 10min waiting and no gps fix.
- Fresh reboot, phone **NOT CONNECTED** to computer by USB, "sudo /system/bin/logcat > UTLogcat.txt" running, 10min waiting and no gps fix. (see UTLogcat_without_computer.txt)
- Fresh reboot, phone **CONNECTED** to computer by USB, 10min waiting and no gps fix.
- Fresh reboot, phone **CONNECTED** to computer by USB, adb shell open and "sudo /system/bin/logcat > UTLogcat2.txt" running, 4min,16sec waiting and it had GPS fix. (see UTLogcat_with_computer.txt)

I can reproduce this behavior every time. It is strange why it behaves like this. I'm not any programmer so this goes way over my head..

I found that in this case, GPS did not get more that **1 space vehicles** (satellites) **ever**..
`V/LocSvc_api_v02(  892): V/locClientHandleSatReportInd:649]: len = 2568 , altitude assumed = 0, num SV's = 1 validity = 1 `
[UTLogcat_without_computer.txt](https://github.com/ubports/ubuntu-touch/files/1403902/UTLogcat_without_computer.txt)

In here **22 space vehicles** in short time.. in **92seconds**.
`V/LocSvc_ApiV02(  893): V/void LocApiV02::reportSv(const qmiLocEventGnssSvInfoIndMsgT_v02*):1806]: num of sv = 22`
[UTLogcat_with_computer.txt](https://github.com/ubports/ubuntu-touch/files/1403903/UTLogcat_with_computer.txt)

However, it is not possible to get fix again without reboot. Catlog says that same story as "UTLogcat_without_computer.txt"

Hope this helps, I try to get more info later..

**Comment by HendriXXX** [comment]
Seems like problem is solved for now. I flashed older radio firmware (M9615A-CEFWMAZM-2.0.1700.84) and now gps works good. I extracted it from 4.3 Android factory image.
First phone to the fastboot mode and then I run "fastboot flash radio radio-mako-m9615a-cefwmazm-2.0.1700.84.img"

**Comment by ernesst** [comment]
@HendriXXX Well done. 
I've the same baseband than you the 1700.84. 

@NeoTheThird @Flohack74 , Would it be possible to add a note on the Ubports Nexus 4 page ?

**Comment by NeoTheThird** [comment]
@ernesst What do you want the note to say?

**Comment by ernesst** [comment]
I would add a note like : 
* GPS performance is optimal with the radio firmware M9615A-CEFWMAZM-2.0.1700.84

What do you think ?

**Comment by sonigfr** [comment]
I could say I have pretty same issue on Oneplus One (bacon) 16.04 OTA-08. Gps is less sensitive than other phones. Can't be activated at home and take a while to be activated outside. If it interests someone I talk about this issue here https://github.com/ubports/ubuntu-touch/issues/1130 and some logs can be checked.

**Comment by UniversalSuperBox** [comment]
Basically, this is a limitation of GPS hardware. We were using an assisted GPS service before, but our implementation was not very good causing these problems. We believe we've made this behave in a more sane way in the upcoming OTA-10. Instead of getting a random location from far, far away and sticking to it for a while, you'll just get... no location for a while.

I've written an article to hopefully explain how this works and how to work around it: https://docs.ubports.com/en/latest/userguide/dailyuse/location.html#using-apps-with-location-services

Note that getting an initial location after wiping the device or not using it for weeks *will be slow now*. But it'll be accurate.

**Comment by mardy** [comment]
> We were using an assisted GPS service before, but our implementation was not very good causing these problems. We believe we've made this behave in a more sane way in the upcoming OTA-10. 

Can you please clarify what has changed? We don't have assisted GPS anymore? I remember that I saw that @mariogrip had a repository with some wifi-based solution (I don't remember if it was a port of the MerProject's one, or Mozilla Location Services).

**Comment by UniversalSuperBox** [comment]
https://github.com/ubports/lxc-android-config/pull/25 and https://github.com/ubports/ubuntu-touch-meta/pull/48 changed, specifically. We no longer have assisted GPS.

Marius was working on using [locationd](https://docs.ubuntu.com/core/en/stacks/location/location-service/docs/), which is more a replacement for ULS that supports lots of backends.
