### ISSUE TITLE
Provide daily builds of rootfs on cdimage.ubports.com

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#287]
Currently people can obtain builds of Ubuntu Touch (vivid and xenial) for testing their ports on https://ci.ubports.com. There is also a great folder, http://cdimage.ubports.com/rootfs/, for providing these builds. However, there is only an outdated xenial build over there. The CI server should be set up to upload images to cdimage so that we have one place to point people to.

**Comment by Flohack74** [comment]
Ok I will take a look for this one...

**Comment by Flohack74** [comment]
For the time being, I provide this with a simple pull script in the web server. It will copy this daily in case smth has changed (we can decide for the time). It wil also keep a copy of the previous version. Does this satisfy our needs?

**Comment by Flohack74** [comment]
![grafik](https://user-images.githubusercontent.com/16186470/39469364-1e7bc2b6-4d38-11e8-8809-bed562efbe6e.png)
Current state
