### ISSUE TITLE
Date of previous update

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/ubuntu-touch#289]
- Device:update turbo
- Channel: devel
- Build: 41

## Steps to reproduce

1. Go to Settings
2. Click to check for Updates

## Expected behavoir

To check for new updates while the date of the last update remains unmodified.

## Actual behavior

Whether it finds or not an update, it changes the date of the precious update to today.

**Comment by NeoTheThird** [comment]
Thanks for reporting. :)
Not reproducible on my devices, but i don't have a Meizu Pro 5. Can someone else try?

**Comment by pixelr0** [comment]
same here on Fairphone 2 (stable and RC)
so in system settings  / Updates - Recent updates i have 2 entries 
ubuntu touch version 7 (this is RC) Uploaded 9 October 
ubuntu version 2 (this is the previous OTA2 stable) Updated 9 October <<< but this is not right, OTA2 was installed a week or so ago. 

the bug is that is shows the same date (the last date when you update) on both entries

**Comment by pixelr0** [comment]
fairphone 2 https://i.imgur.com/2HsdXqu.jpg

i just noticed this bug now on fairphone but on mx4 this bug is since forever at least on canonical images

**Comment by TischlerWilly** [comment]
The same on my E5.
It shows the date of today and not the date of the update in the past.
This bug was there with the canonical updates in the past too.

**Comment by Stefano0101** [comment]
Yes, on Pro5 after the check for update, it shows updated today, but no real update was performed, just changes the date. I've seen this happening for a while now.
Pro 5/stable/ota-2

**Comment by mihaelmilea** [comment]
![screenshot20171016_203254594](https://user-images.githubusercontent.com/30057613/31854803-ff63f9b0-b6a7-11e7-9ea5-f1e6ef462c74.png)
![screenshot20171009_200347034](https://user-images.githubusercontent.com/30057613/31854804-ff7f48b4-b6a7-11e7-83a8-b99c5669125a.png)
![screenshot20171017_163612978](https://user-images.githubusercontent.com/30057613/31854805-ff9b1120-b6a7-11e7-8971-c2508e1bfe0e.png)
![screenshot20171012_080232432](https://user-images.githubusercontent.com/30057613/31854806-ffb59f54-b6a7-11e7-8138-9c52c03c7973.png)
![screenshot20171011_072533782](https://user-images.githubusercontent.com/30057613/31854807-ffcfc3de-b6a7-11e7-91fa-cbfede40aefd.png)
![screenshot20171018_151837452](https://user-images.githubusercontent.com/30057613/31854808-ffec939c-b6a7-11e7-92de-6fb5b502a7bc.png)
![screenshot20171015_214426910](https://user-images.githubusercontent.com/30057613/31854809-000806ae-b6a8-11e7-9cfe-8a35dd574837.png)

**Comment by NeoTheThird** [comment]
@mihaelmilea when you have more than one picture, please add it as a link rather than a picture. Else it makes it impossible to work scroll through the issue report.

**Comment by mihaelmilea** [comment]
@NeoTheThird you are right, I didn't realise that and thank you for editing my comment. I really appreciate all this!

**Comment by advocatux** [comment]
Confirmed this bug in BQ E4.5 and Nexus 5.
AFAIK this bug has been present since Canonical's times.

**Comment by Stefano0101** [comment]
On Pro 5 it's fixed as well.
