### ISSUE TITLE
Answer incoming calls dialog box not visible on Bacon

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#290]
- Device: Bacon
- Channel: Devel
- Builds: 171-173

## Steps to reproduce

1. Call your Bacon device from another phone
2. Wait for incoming phone call

## Expected behavoir
With screen off:
Screen turn on and show the answer incoming call dialog box and audible ring signal
With screen on:
Show the answer incoming call dialog box and audible ring signal

## Actual behavior
With screen off:
Screen stays off and no audible ring signal
With screen on:
Shows the answer incoming call dialog box briefly, upon which it disappears and no audible ring signal

My phone is connected to a Pebble Time Round via RockWork and the watch shows incoming call, but due to the missing dialog box I can't answer the incoming call. The missed calls are visible in the notifications and under missed calls in the dialer-app.

## Logfiles and additional information
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1367878/UTlogcat.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1367879/UTdmesg.txt)

**Comment by NeoTheThird** [comment]
Interesting, thanks for reporting. Does this also happen when your pebble is not connected?

**Comment by tomoqv** [comment]
Yes, same thing with bluetooth off. A small update to the above though. With screen off: screen turns on and briefly flashes the answer dialog box, this is the same with our without bluetooth and Pebble.

**Comment by stekalb** [comment]
Same behaviour on rc r6. Incoming call is just shortly visible. Although on rc I have a constant ring tone.

**Comment by tomoqv** [comment]
I switched to stable for a while and switched back to devel again a couple of days ago. This bug has not reappeared since being on devel again.

**Comment by tomoqv** [comment]
Maybe this bug can be closed. I have had no problem with this for weeks (at least on devel).

**Comment by stekalb** [comment]
I can confirm that it works now on devel (r204)

**Comment by stekalb** [comment]
Maybe it related to #305 
I'll give it a try as soon as the wakeup issue reappears on my bacon.

**Comment by Flohack74** [comment]
Ok will close for now.
