### ISSUE TITLE
Fork libertine to ubports

### ISSUE THREAD

**Issue by delijati** [ubports/ubuntu-touch#302]
There is already a github repo for `libertine` but it seams unmaintained and building also did not work for me. https://github.com/ubuntu-libertine/libertine/issues/1

The deb, snap version should be packed as click and put on the phone.

**Comment by ShadowEO** [comment]
I agree with @delijati, this would be a good idea as the current version of Libertine is now broken due to changes on the ports.ubuntu.com mirror. They have moved the vivid repository off of the ports server and into old-releases, meaning that changes are needed to be made to ChrootContainer.py of Libertine to ensure it is able to create a container under Vivid.

Now, obviously, this ticket is less of a priority once the switch to Xenial is made, since Xenial will become the target distribution for the chroot container as Libertine forces chroot containers to match their host distribution, and the LXC container backend doesn't enforce this restriction. However until then Vivid will be running without the advertised ability to run legacy applications.

**Comment by Flohack74** [comment]
Done: https://github.com/ubports/libertine

**Comment by dpniel** [comment]
Do we really want libertine as a click? It's certainly possible to do as an unconfined click and a helper to install the upstart jobs for libertined etc. It would also make it  somewhat safer to some degree as users wouldn't need to go using apt to install it on their phones.

I'm just not sure how this would this affect current libertine installs? 

Would we keep it seeded into the image for the "convergent" capable devices (currently only the M10). Or would we just include it as a click from xenial onwards?

**Comment by delijati** [comment]
@dpnie currently i'm installing everything by hand with `libertine-container-manager` there is also a app for this now [1] and chris is working on getting everything installed native on the device. But there is a newer working `qml` gui doing this but it is not the one installed in `vivid`.

[1] https://github.com/TronFortyTwo/OnTheRoad

**Comment by dpniel** [comment]
@delijati not sure i follow? Could you expand a bit more please. 

What does "chris is working on getting everything installed native on the device" mean?

Are you just wanting the latest libertine gui or are you happy using OnTheRoad?

**Comment by NeoTheThird** [comment]
> What does "chris is working on getting everything installed native on the device" mean?

I'm also intrigued. Who is chris, what is everything?

**Comment by delijati** [comment]
@dpniel the version on launchpad and on ubports includes already a `qml` gui to create a container list, install, remove native apps. 

@NeoTheThird https://kriscode.blogspot.de/2017/ he is posting on telegram about his progress about installiing XApps without libertine or chroot.

**Comment by Flohack74** [comment]
Kris does a special workflow for his own needs, in case you find it useful you can jump there but I doubt we can mainline this. In the end he proposes to have Desktop first, then adapt it to a phone, and Canonical (and UBports) come from Mobile first approach. So if you install X apps this way, just keep in mind that they are likely very unusable without X forwarding to a normal desktop, and they will not interface with content hub, click apps or any other aspect of UT easily. Just saying...

**Comment by delijati** [comment]
@Flohack74 the risk of bricking the phone by installing on the root system is way to high what Kris is doing is fine but to risky for me.

All i say is that the libertine on launchpad is a newer version with already included gui elements to `create a container, list, install and remove native apps.`. I tried it on 17.04 unity8 by installing libertine. So by getting it as a click or replacing the libertine currently in vivid we would get a newer version.

**Comment by NeoTheThird** [comment]
https://github.com/ubports/libertine/pull/1#pullrequestreview-83675455

**Comment by dpniel** [comment]
Libertine is now in the ubports vivid repo but it doesn't include the latest qml ui. I wound back the commits to the last vivid release and applied a patch for the apt sources now being on old-releases.ubuntu.com. I will try and get the latest and greatest packaged for xenial as it seems to have dependencies on newer library versions (like content hub) which should be fine from xenial+

**Comment by Arc676** [comment]
Is there a way to make Libertine access the old-releases repositories so containers can be created in OTA-2? I'm trying to create a container to install LibreOffice, but it just says:
```
E: Failed getting release file http://ports.ubuntu.com/ubuntu-ports/dists/vivid/Release
```

**Comment by dpniel** [comment]
You would need to upgrade to OTA-3 to be able to create containers or you can follow the steps in this forum post if your staying on OTA-2 https://forums.ubports.com/topic/792/libertine-installation-broken-on-vivid

**Comment by doniks** [comment]
I think this issue should be closed. The original problem is solved. A bunch of other things discussed are solved as well. Let's close. One problem per issue.
