### ISSUE TITLE
flash should turn OFF in Camera/Photo Roll

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#306]
open camera app, turn ON flash for video recordings, record video, swipe from right to left to get into Photo Roll, the flash is still ON. this is so annoying to me, since i usually watch the video after recording and i have to manually turn the flash OFF so it doesn't stay ON while i watch the video, and then i have to turn it ON again when i record another video and so on, i think you can see where i'm going. loop

**Comment by dark-eye** [comment]
I think this is a [camera-app](https://github.com/ubports/camera-app/issues) issue , The question should it work like that?
I there a way to create polls in github ? :)

**Comment by NeoTheThird** [comment]
@dark-eye Yes, please move it.

**Comment by dark-eye** [comment]
@NeoTheThird  I`m not sure how to do that :) Is there a Button/action in github  that i`m missing or should i just Copy&Paste the conversation?

**Comment by Flohack74** [comment]
This issue was moved to ubports/camera-app#36

**Comment by Flohack74** [comment]
No its fine, actually we need to move it ^^
