### ISSUE TITLE
some core apps/preinstalled have like really really old previews/screenshots

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#309]
long press on Phone, Messaging, Contacts etc  to see the app details. you'll see some really old previews/screenshots

**Comment by ChloeWolfieGirl** [comment]
I dont believe this is anything we can fix as they are brought from the ubuntu software center, with that being said, we do need to, and are talking about plans for legacy devices, these are devices which wont get 16.04 and see what we can do for them, when we move to 16.04 the app scope should be gone, replaced with the App draw, which to my knowledge, takes away that dependency.

**Comment by NeoTheThird** [comment]
Yep, Chloe is right. This is an issue with the Canonical click store that will die with it.
