### ISSUE TITLE
some scopes are missing icons and don't load

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#310]
fp2/devel r183
swipe from the buttom (on home screen) to bring up the Manage for scopes. there are a bunch of scopes with missing icons 7digital, amazon,ebay, reddit etc. even if you tap on them to make the scopes active they are blank, don't load.

**Comment by j2g2rp** [comment]
Same here on BQ E4.4 devel R40. But I noticed reading that post. Sincerely, i don't care about them, maybe just wikipedia scope was few usable, but also was a pain to search something.

**Comment by Gabriele69** [comment]
Same here BQ 4.5 RC r8: 7digital, Amazon, eBay,Open Library,Reddit, The Weather Channel, Wikipedia and Yahoo Finanza

**Comment by jonnius** [comment]
I think this one can be closed, because it seems like those old scopes have been removed. At least I can't find them on my phone.

**Comment by dobey** [comment]
These are remote scopes and not actually on the phone. They should not appear any more if the server has now been taken down. The server side may have been partially taken down before, which led to this weird interim state where they showed up but without any content.
