### ISSUE TITLE
FP2 devel16.04 Can't boot recovery image

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#313]
i'm trying to flash 16.04 on FP2 as described here https://wiki.ubports.com/wiki/How-to-install-Ubuntu-Touch-16.04

sudo ubuntu-device-flash --server=http://system-image.ubports.com touch \
> --device=FP2 --channel=ubports-touch/16.04/devel --bootstrap --wipe
[sudo] password for zzz: 
2017/10/23 03:28:20 Device is |FP2|
2017/10/23 03:28:20 Flashing version 1 from ubports-touch/16.04/devel channel and server http://system-image.ubports.com to device FP2
Can't boot recovery image

**Comment by pixelr0** [comment]
same with 16.04/devel r2 

sudo ubuntu-device-flash --server=http://system-image.ubports.com touch --device=FP2 --channel=ubports-touch/16.04/devel --bootstrap --wipe
[sudo] password for zzz: 
2017/10/23 14:25:02 Device is |FP2|
2017/10/23 14:25:02 Flashing version 2 from ubports-touch/16.04/devel channel and server http://system-image.ubports.com to device FP2
69.26 MB / 69.26 MB [=================================================================================] 100.00 % 7.32 MB/s 
Can't boot recovery image

am i doing something wrong?

**Comment by NeoTheThird** [comment]
Sorry about that, the FP2 does not support `--bootstrap`. You should be able to use the UBports installer: ubports/ubports-installer

**Comment by NeoTheThird** [comment]
I also updated the wiki page.

**Comment by pixelr0** [comment]
Thanks! o/
