### ISSUE TITLE
short power button press detected as a long press 

### ISSUE THREAD

**Issue by startcloud** [ubports/ubuntu-touch#315]
- Device: Nexus 5
- Channel: stable
- Build: 15.04 r2

## Steps to reproduce
Sometimes a short click on power button is detected as a hold press that makes the reboot/turn off menu appear on the screen, when you click on cancel button, the phone seems to be stuck and it reboots his graphical interface 

## Logfiles and additional information
Issue reproduced several times 

Please let me know if you want logfiles if reproduced again

**Comment by NeoTheThird** [comment]
Does not happen on my device, it might be a hardware issue with the button being worn out.

**Comment by startcloud** [comment]
reproduced again 
logs got after reboot I get the /var/log/dmesg.0 
[UTdmesg_old.txt](https://github.com/ubports/ubuntu-touch/files/1424427/UTdmesg_old.txt)

**Comment by advocatux** [comment]
Hi @startcloud are you suffering this bug with 15.04 r3 (aka OTA-3)? Because I have never had this problem in my Nexus 5.

**Comment by startcloud** [comment]
Indeed I am not able to reproduce this issue with recent updates sorry I forget to update this issue. Not it is much more stable. I don't know if it has a fix done explaining the improvment but I think we can close this one
