### ISSUE TITLE
16.04/devel missing update option

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#319]
- Device:fp2
- Channel:16.04/devel
- Build:r5

i don't see any update options in system settings. 
silly question, how do i update? o_O

**Comment by NeoTheThird** [comment]
Please keep in mind that 16.04 is highly experimental and in no way intended to be used as a daily driver solution yet. If you need to update, just flash your device again (if necessary without wipe) for the moment.

**Comment by ChloeWolfieGirl** [comment]
This is a known problem, this was brought in when canonical decided that 16.04 was going to be entirely snappy based, so removed the update option.

Marius wil bring the update option back in further releases, but I dont know where that is on the release map.

**Comment by nfsprodriver** [comment]
To update your system, connect via ssh/adb and run:
```sudo system-image-cli -b 0 -f delta -v```
Leave -f delta if you want a fresh reinstall of xenial (keeoing user data).

**Comment by pixelr0** [comment]
hm.. so i run that but i am not sure it did anything :>

sudo system-image-cli -b 0 -f delta -v
[sudo] password for phablet: 
[systemimage] Oct 31 05:33:38 2017 (30392) running state machine [ubports-touch/16.04/devel/FP2]
[systemimage] Oct 31 05:33:38 2017 (30392) No valid image master key found, downloading
[systemimage] Oct 31 05:33:38 2017 (30392) [0xb60f8450] Requesting group download:
	https://system-image.ubports.com/gpg/image-master.tar.xz -> /android/cache/recovery/keyring.tar.xz
	https://system-image.ubports.com/gpg/image-master.tar.xz.asc -> /android/cache/recovery/keyring.tar.xz.asc

[systemimage] Oct 31 05:33:38 2017 (30392) Allow GSM? No
[systemimage] Oct 31 05:33:38 2017 (30392) [/com/canonical/applications/download/a8642848bfdc4f9a912cf1ddd66f5265] Running group download reactor
[systemimage] Oct 31 05:33:38 2017 (30392) self: <UDMDownloadManager at 0xb60f8450>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb60ec270> :1.4609 /com/canonical/applications/download/a8642848bfdc4f9a912cf1ddd66f5265 at 0xb60f8530> implementing 'com.canonical.applications.GroupDownload' at 0xb60f8490>
[systemimage] Oct 31 05:34:23 2017 (30392) [/com/canonical/applications/download/a8642848bfdc4f9a912cf1ddd66f5265] Group download reactor done
[systemimage] Oct 31 05:34:23 2017 (30392) Looking for blacklist: https://system-image.ubports.com/gpg/blacklist.tar.xz
[systemimage] Oct 31 05:34:23 2017 (30392) [0xb617a9f0] Requesting group download:
	https://system-image.ubports.com/gpg/blacklist.tar.xz -> /var/lib/system-image/keyring.tar.xz
	https://system-image.ubports.com/gpg/blacklist.tar.xz.asc -> /var/lib/system-image/keyring.tar.xz.asc

[systemimage] Oct 31 05:34:23 2017 (30392) Allow GSM? No
[systemimage] Oct 31 05:34:23 2017 (30392) [/com/canonical/applications/download/82e9a32607a64f0fa10e0c0525eda6b6] Running group download reactor
[systemimage] Oct 31 05:34:23 2017 (30392) self: <UDMDownloadManager at 0xb617a9f0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb60ec270> :1.4609 /com/canonical/applications/download/82e9a32607a64f0fa10e0c0525eda6b6 at 0xb60f8890> implementing 'com.canonical.applications.GroupDownload' at 0xb60f8850>
[systemimage] Oct 31 05:34:23 2017 (30392) [/com/canonical/applications/download/82e9a32607a64f0fa10e0c0525eda6b6] Group download reactor done
[systemimage] Oct 31 05:34:23 2017 (30392) Local blacklist file: /var/lib/system-image/blacklist.tar.xz
[systemimage] Oct 31 05:34:23 2017 (30392) No valid image signing key found, downloading
[systemimage] Oct 31 05:34:23 2017 (30392) [0xb617a9f0] Requesting group download:
	https://system-image.ubports.com/gpg/image-signing.tar.xz -> /android/cache/recovery/keyring.tar.xz
	https://system-image.ubports.com/gpg/image-signing.tar.xz.asc -> /android/cache/recovery/keyring.tar.xz.asc

[systemimage] Oct 31 05:34:23 2017 (30392) Allow GSM? No
[systemimage] Oct 31 05:34:23 2017 (30392) [/com/canonical/applications/download/b2b8b8c4746046e284e83f1895c0ad05] Running group download reactor
[systemimage] Oct 31 05:34:23 2017 (30392) self: <UDMDownloadManager at 0xb617a9f0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb60ec270> :1.4609 /com/canonical/applications/download/b2b8b8c4746046e284e83f1895c0ad05 at 0xb60f8a90> implementing 'com.canonical.applications.GroupDownload' at 0xb60f8710>
[systemimage] Oct 31 05:34:23 2017 (30392) [/com/canonical/applications/download/b2b8b8c4746046e284e83f1895c0ad05] Group download reactor done
[systemimage] Oct 31 05:34:24 2017 (30392) Looking for: https://system-image.ubports.com/channels.json
[systemimage] Oct 31 05:34:24 2017 (30392) [0xb60f82b0] Requesting group download:
	https://system-image.ubports.com/channels.json -> /tmp/system-image-jg3x_qqz/channels.json
	https://system-image.ubports.com/channels.json.asc -> /tmp/system-image-jg3x_qqz/channels.json.asc

[systemimage] Oct 31 05:34:24 2017 (30392) Allow GSM? No
[systemimage] Oct 31 05:34:24 2017 (30392) [/com/canonical/applications/download/33a2545c954b41b489db8256b0df3c2a] Running group download reactor
[systemimage] Oct 31 05:34:24 2017 (30392) self: <UDMDownloadManager at 0xb60f82b0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb60ec270> :1.4609 /com/canonical/applications/download/33a2545c954b41b489db8256b0df3c2a at 0xb69241f0> implementing 'com.canonical.applications.GroupDownload' at 0xb60f8bd0>
[systemimage] Oct 31 05:34:24 2017 (30392) [/com/canonical/applications/download/33a2545c954b41b489db8256b0df3c2a] Group download reactor done
[systemimage] Oct 31 05:34:24 2017 (30392) Local channels file: /tmp/system-image-jg3x_qqz/channels.json
[systemimage] Oct 31 05:34:24 2017 (30392) got channel: ubports-touch/16.04/devel
[systemimage] Oct 31 05:34:24 2017 (30392) found channel/device entry: ubports-touch/16.04/devel/FP2
[systemimage] Oct 31 05:34:24 2017 (30392) [0xb60f82b0] Requesting group download:
	https://system-image.ubports.com/ubports-touch/16.04/devel/FP2/index.json -> /tmp/system-image-jg3x_qqz/index.json
	https://system-image.ubports.com/ubports-touch/16.04/devel/FP2/index.json.asc -> /tmp/system-image-jg3x_qqz/index.json.asc

[systemimage] Oct 31 05:34:24 2017 (30392) Allow GSM? No
[systemimage] Oct 31 05:34:24 2017 (30392) [/com/canonical/applications/download/4713d4ed0aa9423c9ad6ea5f5baec84f] Running group download reactor
[systemimage] Oct 31 05:34:24 2017 (30392) self: <UDMDownloadManager at 0xb60f82b0>, self._iface: <Interface <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0xb60ec270> :1.4609 /com/canonical/applications/download/4713d4ed0aa9423c9ad6ea5f5baec84f at 0xb617a9f0> implementing 'com.canonical.applications.GroupDownload' at 0xb69241d0>
[systemimage] Oct 31 05:34:24 2017 (30392) [/com/canonical/applications/download/4713d4ed0aa9423c9ad6ea5f5baec84f] Group download reactor done
[systemimage] Oct 31 05:34:25 2017 (30392) Already up-to-date
[systemimage] Oct 31 05:34:25 2017 (30392) state machine finished

**Comment by pixelr0** [comment]
system-image-cli -i
current build number: 5
device name: FP2
channel: ubports-touch/16.04/devel
last update: 1970-06-24 01:40:33
version version: 5
version ubports: 20171022-31460
version keyring: archive-master
version device: 20171026-23137

looks to me that i'm still on the same old image r5 devel, the newest one is r10 https://system-image.ubports.com/ubports-touch/16.04/devel/FP2/

**Comment by nfsprodriver** [comment]
That's because the rootfs and the device image hasn't been updated since October 22, so there are no deltas. Everything seems to be fine.

**Comment by pixelr0** [comment]
great then! thanks o/

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/system-settings/pull/34

**Comment by ChloeWolfieGirl** [comment]
Thank you!

**Comment by NeoTheThird** [comment]
fixed
