### ISSUE TITLE
 Vibrate on keypress is too weak 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#32]
I know that many people prefer their phone without haptic feedback, but I'm one of the loons who loves it.

On the keyboard (and possibly in other places, such as the Dash) there should be a vibration every time that a key is pressed. It seems that this event fires, but it is far too weak to be noticed. If you put your ear right up to the phone, you can hear the motor clicking.

It seems that this is configurable via the /sys filesystem on some devices: http://askubuntu.com/questions/422518/disable-vibration-when-pressing-key-on-ubuntu-touch

However, the /sys/class/timed_output/vibrator/ folder does not contain the 'amp' file on this phone.

Reported by https://launchpad.net/~universalsuperbox.

**Comment by giiba** [comment]
I don't know if this helps or not, but...

I've been annoyed by the lack of haptic feedback on the 1+1 I recently flashed to UT. I've been using a Nexus 5 and everything works fine as far as vibrations goes so I figured this wasn't a hardware issue as the 1+1 does vibrate, sometimes.

I started digging in the keyboard files:
/usr/share/maliit/plugins/com/ubuntu

and in KeyboardContainer.qml I found lines 85-93: 'HapticsEffect'

and... changing 'duration' to 25 and rebooting, I now have a reasonable haptics feedback for the keyboard.


So, perhaps all of these missing vibrations are from individual components using too small a duration for the device in question?

**Comment by Flohack74** [comment]
Yes thats true, the motor of the OPO is too small/slow to actually start vibrating for short durations. I would however love to have a "vibration ratio" per device, rather than increasing the timer for all devices. I was already looking into this a bit but were not sure how to place that ratio.

**Comment by Flohack74** [comment]
This has been fixed in https://github.com/ubports/android_device_oneplus_bacon-1/pull/20

**Comment by Flohack74** [comment]
@NeoTheThird are you sure the vibration is too weak on teh FP2? I find it quite usable.
