### ISSUE TITLE
Volume warning message is confusing

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#326]
- Device: Bacon
- Channel: Devel
- Build: r192

## Steps to reproduce

1. Open audio player
2. Play audio on high volume
3. Plug in headphones

## Expected behavoir

Device automatically supresses volume. Or asks if supression OK.

## Actual behavior

Device asks if its OK to damage your ears.

## Logfiles and additional information
Original bug post https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1572343information

Screenshot http://i63.tinypic.com/ddl5y9.png

**Comment by userj** [comment]
Bug report https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1572343

**Comment by NeoTheThird** [comment]
https://github.com/ubports/indicator-sound/pull/1

**Comment by NeoTheThird** [comment]
Closing this due to [changed issue tracking process](https://github.com/ubports/docs.ubports.com/pull/92). Fixed.

**Comment by userj** [comment]
I noticed that this change hasn't appeared in latest 16.04 builds. When moved to "Release Candidate" when do those changes get implemented?
