### ISSUE TITLE
Ubuntu 17.10 and future 

### ISSUE THREAD

**Issue by delijati** [ubports/ubuntu-touch#333]
There are several packages that where removed when updating to 17.10 aka "Artful":

- [ubuntu-ui-toolkit](https://launchpad.net/ubuntu-ui-toolkit/+packages)
- [phablet-tools](https://launchpad.net/ubuntu/+source/phablet-tools)
- [content-hub](https://launchpad.net/content-hub)
- ...

To prevent developing on a VM or downgrading to 16.04LTS this packages should be preserve in a ppa controlled by ubports.

**Comment by pixelr0** [comment]
we also need an unity8 desktop session to run unity8 on the desktop (x86). :D

**Comment by pixelr0** [comment]
interesting discussion here https://forum.yunit.io/viewtopic.php?f=4&p=671#p671

**Comment by Flohack74** [comment]
TBH I would suggest only jumping on LTS versions... For a phone probably its better to not constantly update the base OS, and also not necessary. We already now have a lot of overlayed and backported stuff, which is more like rolling release feature.

**Comment by mymike00** [comment]
I think he's talking about packages there are no more installed on Ubuntu Desktop: make them available so people (for example to develop) doesn't need a VM or downgrade to 16.04

**Comment by kwah-gh** [comment]
Just submitted [issue against magic-device-tool](https://github.com/MariusQuabeck/magic-device-tool/issues/118). It misses dependencies on Ubuntu 17.10 too.

**Comment by dobey** [comment]
@mymike00 What @Flohack74 is swaying though, is that it's not worth the trouble to add interim Ubuntu releases as something else we have to build all those packages on, and then ensure they work, when they're only supported for 9 months, and the phone builds will stick to LTS releases (once 16.04 is made stable).

Once the SDK situation is resolved and we have something good to offer people there again, perhaps it could be built as a snap too, so then people on 17.10 or such could just install the snap and develop with it. I don't think we should support the runtime dependencies on interim releases to be running apps there. If you want to build an app for that target, you can always build the dependencies yourself as well, or ask the app dev to perhaps build snaps in the Ubuntu snap store as well.

**Comment by Flohack74** [comment]
I am closing this now, we are upgrading to 20.04 and thats already enough work for the time being :)
