### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubuntu-touch#334]
- Device:
- Channel:
- Build:

## Steps to reproduce

1. ...
2. ...
3. ...

## Expected behavoir

...

## Actual behavior

...

## Logfiles and additional information

...

Libreoffice ne fonctionne pas, il s'allume puis s'éteint de suite.
VLC ne reconnait aucun support vidéo
Libreoffice does not work, it turns on and off.
VLC does not recognize any video support

**Comment by NeoTheThird** [comment]
Duplicate of #22.
