### ISSUE TITLE
Call button does not work

### ISSUE THREAD

**Issue by Sinai65** [ubports/ubuntu-touch#337]
- Device: Nexus 4 (mako)
- Channel: 15.04/devel
- Build: r154

## Steps to reproduce

1. Try to make a phone call

## Expected behavoir

After pressing the call button, I should be able to make a call.
...

## Actual behavior

When I press the call button nothing's happened!!!

## Logfiles and additional information
Where should I check the log files?
I had install ubuntu touch a few days ago. It had the same problem on my phone. I reinstall android 5.1.1 because I though its development is discontinued, but I found out it is under development with ubports so I installed its version for nexus4 from the following link:
https://devices.ubports.com/#/mako
But I am facing the same problem.Any help is appreciated.

**Comment by wayneoutthere** [comment]
I have tested this bug and I am not affected whatsoever. I can perfectly make a call and I'm using rc155, just downloaded today.  I have never seen this bug after Marius did the 'big update' a few months back, but, but, before that I did have this bug.  So maybe needs reflashing or something??  sorry I'm not skilled enough to help more but my N4 mako is calling perfectly...

**Comment by bam80** [comment]
Should we close this bug then?

**Comment by Sinai65** [comment]
Yes please. Thank you.
