### ISSUE TITLE
Bring back the app drawer

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#338]
In 16.04 there used to be an app draw, this has been taken out, for one reason or another, it'd be nice to see it back in.

**Comment by NeoTheThird** [comment]
For clarification, it has not been removed, but the idea of project sudoku is to do one step at a time, so for now the same version of unity 8 is used as in 15.04.

**Comment by lduboeuf** [comment]
We can say now that the app drawer is back with OTA-12, isn't it ?
