### ISSUE TITLE
Outdated browser needs upgrade. Web apps not working, limited functionality.

### ISSUE THREAD

**Issue by Stefano0101** [ubports/ubuntu-touch#341]
- Device: Turbo
- Channel: 15.04/Stable
- Build: r2

## Steps to reproduce

1. ...Web-apps  or browser itself reports that is outdated. Google plus app or Google plus website report the same.
2. ... Occasionally ( 1 in 20 app opening ) it works
3. ... Also Skype has issue as no calling is available anymore due outdated browser(Skype for web is browser based)
![screenshot20171114_120113357](https://user-images.githubusercontent.com/29058699/32900849-54af048a-cae6-11e7-879d-efc447017417.png)
 ( it worked (previously without any issue)

## Expected behavoir

...Just tap on app icon and work
## Actual behavior

... not working, maybe 1 in 20 or more app opening it might work and not displaying  outdated browser.
See the picture/screenshot attached.

## Logfiles and additional information

...

**Comment by ChloeWolfieGirl** [comment]
Oxide is getting a big update in the 16.04 update, cant comment else.

**Comment by NeoTheThird** [comment]
Thanks for reporting :)

Please see my comment on https://github.com/ubports/webbrowser-app/issues/15, i also added a hint on how to fix this issue :)
