### ISSUE TITLE
While installing a software update there are old background and writing

### ISSUE THREAD

**Issue by mymike00** [ubports/ubuntu-touch#342]
- Device: krilin (BQ E4.5)
- Channel: rc
- Build: while installing the r10

## Steps to reproduce

1. Install a OTA update
2. the phone shuts down and a screen with a progress bar appears
3. in this screen there's the old background default image and the writing doesn't has "touch" under "Ubuntu"

## Expected behavoir

the background image should be updated to the new default image (the one shown also when switching on the phone) and "touch" should be visible under "Ubuntu"

## Logfiles and additional information

I report this issue because I noticed now while updating my phone, but maybe it has been corrected in the last build...

**Comment by Flohack74** [comment]
Hello, this is unfortunately not changeable for us on the BQ devices, since we have no sourcecode for the recovery. That's an issue with all Mediatek devices...

**Comment by mymike00** [comment]
Oh, idk it is in the recovery...
I hope in the future we could di something for Mediatek devices 😫
