### ISSUE TITLE
Add support for Nextcloud to account plugins

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#346]
Add all what's needed to enable authentication with Nextcloud.

**Comment by ruedigerkupper** [comment]
For clarification: I cannot currently download any file from Nextcloud via the browser. Is this your issue or should I file another bug?

**Comment by NeoTheThird** [comment]
@ruedigerkupper That's unrelated, please file another bug.

**Comment by NeoTheThird** [comment]
For clarity, what it does is it enables logging in with nextcloud with syncmonitor, which is a backend service that provides these accounts for example to the calendar (which already works), the address book (which doesn't work yet) or any other app. There's one that syncs your bookmarks with nextcloud, for example, that already works as well.

**Comment by Flohack74** [comment]
Closing because it apparently works (report by various users).
