### ISSUE TITLE
Add support for x forwarding over ssh

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#347]
Some additional packages would enable support for x forwarding.

**Comment by NeoTheThird** [comment]
Fixed in https://github.com/ubports/ubuntu-touch-meta/commit/ff9ec414ae5e62a6c71db3c90ac1ce72755a82ff.

**Comment by mardy** [comment]
Does it actually works? Is Mir able of handling X connections?

**Comment by NeoTheThird** [comment]
Yep, xmir saves the day: https://kriscode.blogspot.de/2017/12/ssh-and-ubuntu-touch.html#xforwarding
