### ISSUE TITLE
Add various small packages on community request

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#348]
- Added htop for better/alternative process statistics view
- Added libnotify-bin which provides notify-send executable to send pop-up notifications from scripts etc.

**Comment by toehold** [comment]
Would it be possible to include vpnc package? It could use it to access our VPN Network (Cisco style)

**Comment by delijati** [comment]
vim-nox :) i sure hate nano

**Comment by Flohack74** [comment]
Done

**Comment by mymike00** [comment]
something like `ncdu`?
there's no way to see which files take too much space on the disk...

**Comment by NeoTheThird** [comment]
> something like ncdu?

That's not even shipped by ubuntu by default, i would draw a line here. We should also not make the system image too big.

**Comment by mymike00** [comment]
ok, doesn't matter

**Comment by Flohack74** [comment]
We are 1 week before OTA, so its freeze time ;) - not more requests for this one. If you need smth plz open a new ticket...

**Comment by NeoTheThird** [comment]
Fixed.

**Comment by balcy** [comment]
Hi i am on xenial RC and tried the htop and notify-send commands (phablet user in terminal app) and got the message 'command not found' both times. Is it possible they are not in the xenial image? If they are missing, can we get them in again in OTA-5 ?

**Comment by Flohack74** [comment]
Hmm that is strange, normally the xenial list should be the same as the vivid list. I will check

**Comment by toehold** [comment]
Yes, vpnc is missing, Version 544, 22-08-2018

**Comment by Flohack74** [comment]
Please make a new request about the imbalance of both releases ;)
