### ISSUE TITLE
Switch devices to UBports push server

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#349]
The devices will need to be switched to our push server before end of year. OTA-3 is the perfect occasion to do it for all users rather smoothly.
- [x] Modify the config file in /etc/xdg/ubuntu-push-client so that it points to our service
- [x] set up certificates for the push server
- [x] install push server binary on a DO server
- [x] Contact Telegram for a test run with a few device IDs
- [x] With OTA-3 rolling, contact Canonical to give the GO! to Telegram to take over the whole notifications
- [x] Check if updated push config is visible on the device (/etc/xdg/ubuntu-push/config.json) in devel & rc

**Comment by ChloeWolfieGirl** [comment]
If I get a notification on Devel from Telegram, it should now, successfully come from this new push server?

**Comment by NeoTheThird** [comment]
@Flohack74 Do we have to log in with ubuntu one in telegram again, or does that all happen automatically?

**Comment by dpniel** [comment]
@NeoTheThird It should just carry on as normal. You will just need to open telegram after the OTA to get it to register with the new server.

**Comment by Flohack74** [comment]
@ChloeWolfieGirl only after Dec 21st when Telegram moves their push target to us ^^

**Comment by Flohack74** [comment]
Closing here. All preparations for OTA are done.

**Comment by NeoTheThird** [comment]
@Flohack74 Shouldn't we wait with closing this until Telegram changed their target?

**Comment by Flohack74** [comment]
Not really since this is nothing that has to do with the OTA. All client side changes are in and working, and I wont block the OTA even if Telegram is late with switching ^^ BTW they confirmed to switch tomorrow 10:00 GMT as we discussed
