### ISSUE TITLE
libGLESv2S3D_adreno.so" not found

### ISSUE THREAD

**Issue by BlueKenny** [ubports/ubuntu-touch#352]
- Device: Bacon
- Channel: Stable / Devel
- Build: OTA 2 and R240

## Steps to reproduce

1. View any logfile

## Expected behavoir

No missing library..

## Actual behavior

Every app say :
'library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found'

## Logfiles and additional information

http://paste.ubuntu.com/26131659/

**Comment by rubencarneiro** [comment]
This a common terror, but does not affect in anything you can just ignore, por you can sysmlink  
libGLESv2.só and the terror will desapegar.

**Comment by BlueKenny** [comment]
This "issue" needs only a small:
"ln -s /vendor/lib/egl/libGLESv2_adreno.so /vendor/lib/egl/libGLESv2S3D_adreno.so"

i think the developer can push it in our images?

**Comment by NeoTheThird** [comment]
I can confirm it for FP2 as well.

**Comment by rubencarneiro** [comment]
all devices will work with that hack,not having that blob is not critical, but if you want to remove the missing lib error, just symlink.

**Comment by rubencarneiro** [comment]
This is the best way to do it on the vendor folder.
![captura de ecra de 2017-12-08 20-51-42](https://user-images.githubusercontent.com/6282290/33784726-bfcd90fe-dc59-11e7-929d-5ff056897a38.png)

**Comment by NeoTheThird** [comment]
@rubencarneiro Can you take take care of this and send PRs to the affected repos?

**Comment by rubencarneiro** [comment]
Yes i will take caré of this

**Comment by rubencarneiro** [comment]
FP2 https://github.com/ab2ut/proprietary_vendor_fairphone/pull/6

**Comment by Flohack74** [comment]
Who is the maintainer of those repos? Should we fork them just in case?

**Comment by NeoTheThird** [comment]
@Flohack74 We can't due to copyright protection. But it's fine like this.

**Comment by rubencarneiro** [comment]
@Flohack74, dont need to fork, that repos are in good hands.

**Comment by Flohack74** [comment]
Was this ever solved?

**Comment by BlueKenny** [comment]
No its still in the logs

**Comment by Flohack74** [comment]
I see all the PRs are still open. Meh.

**Comment by luksus42** [comment]
Hi,
I tried to apply the symlink for some tests, but my device keeps saying, that the file system is read-only, though I made it writable (`sudo mount -o rw,remount /`).
Any advice how to get around this?

**Comment by dobey** [comment]
> Hi,
> I tried to apply the symlink for some tests, but my device keeps saying, that the file system is read-only, though I made it writable (`sudo mount -o rw,remount /`).
> Any advice how to get around this?

The affected location is not part of the Ubuntu rootfs, but the Android system. You might find it easier to do from within the recovery. It's the `/vendor` partition that needs to be mounted `rw` not `/`, for this specific change.

**Comment by giiba** [comment]
I'm seeing this issue in the location trust log at the same time I am having location service freezing. Seems odd to see it there.

I am hoping to do some testing, having aquired a copy of the 'missing' library.

See:
https://forums.ubports.com/topic/2724/libglesv2s3d_adreno-so/6

**Comment by lduboeuf** [comment]
It appears we don't have that issue anymore
