### ISSUE TITLE
 rotation doesn't work if rotation lock is activated on boot up 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#36]
After boot / switching button rotation lock "off" / screen does not rotate. If you boot with rotation activated, it does rotate the screen. Seems to be a similar issue regarding cellular data button.

Reported by https://launchpad.net/~ut4fp

**Comment by jonnius** [comment]
I cannot confirm this. Turning on rotation works for me, even if it was disabled on boot. I am on 16.04 r299.

**Comment by Flohack74** [comment]
Seems to work.
