### ISSUE TITLE
HDMI image does not fit to screen

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#365]
BQ M10 FHD/ota2
parts of the desktop are off screen, the top bar is not visible and the left side is partially off screen (see screenshot). i am not sure if it's a bug with ubuntu touch or my TV is just silly. so yeah.. try it yourself on diff TVs over HDMI

screenshot https://i.imgur.com/NO049md.jpg

**Comment by NeoTheThird** [comment]
Hmm, it works on my screen, maybe it depends on the display or tv. Maybe we could include overscan settings...

**Comment by jonnius** [comment]
I have the same issue on my TV with my notebook, independent from the OS (Ubuntu or Windows). So it might be the TV not UT.

**Comment by pixelr0** [comment]
it is the TV indeed
