### ISSUE TITLE
Add turkish keyboard

### ISSUE THREAD

**Issue by turanmahmudov** [ubports/ubuntu-touch#373]
https://github.com/ubports/keyboard-component/pull/17

**Comment by NeoTheThird** [comment]
Should be fixed https://github.com/ubports/keyboard-component/pull/41

**Comment by Flohack74** [comment]
@turanmahmudov the keyboard is now added to the xenial 16.04 devel channel. Can you check (from tomorrow) if it works as intended?

**Comment by turanmahmudov** [comment]
@Flohack74 thanks. Sure I will check it this evening.
