### ISSUE TITLE
404 on practically all APT sources in sources.list

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#375]
- Device: Nexus 7 flo
- Channel: Stable
- Build: 15.04 (r1) armhf 20170923

I believe these issues are linked, so I'll include both in this report. 

### Steps to reproduce
Running `sudo apt update`settings
OR
Opening the "updates" section in settings

### Expected behavior
Updates package lists
OR
Tells me there's an update available (OTA-3 is out! Woooo!)

### Actual behavior
Practically all sources in `sources.list` gives a 404.
Settings tells me that my softwareis up to date. 

### Logfiles and additional information
Here is some of the output of `sudo apt update` (as much as would fit in the screen, since I'm posting this from Ubuntu Touch).
```
W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-updates/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-updates/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/main/source/Sources  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/universe/source/Sources  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.150 80]

W: Fehlschlag beim Holen von http://ports.ubuntu.com/ubuntu-ports/dists/vivid-security/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.150 80]
```

I have tried visiting ports.ubuntu.com in the browser and it works fine. I have not modified my `sources.list`.

I had originally installed the Canonical version of Ubuntu Touch, but then I reinstalled using the UBports installer to switch (hopefully), unless that didn't work and that's the source of these issues.

**Comment by lduboeuf** [comment]
Cannonical moved repo to "old-releases", 
your `ports.ubuntu.com/ubuntu-ports` urls must point to `old-releases.ubuntu.com/ubuntu` now.
`sed -i -e 's/ports.ubuntu.com\/ubuntu-ports/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list`

**Comment by lduboeuf** [comment]
OTA updates are not related to apt repos i think

**Comment by Arc676** [comment]
Ok, thanks for the quick reply. I will change the repository links later today and change the post title.

**Comment by NeoTheThird** [comment]
The OTA-problem is unrelated, let's track that seperately. Let's track that in #378.

As @lduboeuf said, vivid is now factually end of life, so we can not use apt any more. We will move to 16.04 Xenial Xerus in the next release and the problem will resolve itself.

**Comment by Flohack74** [comment]
You need to change apt sources to point to old-releases: https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release

**Comment by Arc676** [comment]
@NeoTheThird I see. So I should just use the repositories-for-unsupported-releases method until 16.04?

**Comment by Flohack74** [comment]
@Arc676 what do you want to do? If you want to get our OTA updates, you should not work with apt at all. If you want to install additional packages, then follow this method, yes.

**Comment by Arc676** [comment]
@Flohack74 Yes, I intended for installing packages. Still no OTA 3 though, tracking in the other issue. Thanks.
