### ISSUE TITLE
No mobile data in OTA3

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#376]
I lost the mobile data connection after OTA-3

- Device: Hammerhead
- Channel: Stable
- Build: Ubuntu 15.04 (r3)

### Steps to reproduce

Install OTA3 in hammerhead. Bye bye mobile data.

### Expected behavoir

That OTA3 doesn't kill mobile data.

### Actual behavior

RIP mobile data

### Logfiles and additional information

[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1581904/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1581906/UTlogcat.txt)

**Comment by advocatux** [comment]
Just in case is useful too, the baseband version is M8974A-2.0.50.2.30.

**Comment by HendriXXX** [comment]
My N5 too is affected. I tried xxx.1.13, xxx.1.16, xxx.2.26, xxx.2.30 modems. Still not working.
I will try later to switch stable to devel or rc, then it will (at least i think it will) install whole image and if i switch from there back to stable.. It could work. I report results later..

**Comment by AlanGriffiths** [comment]
Me too. Switching to devel recovered mobile data. But switching back to stable errored. (No time to investigate further ATM)

**Comment by wagafo** [comment]
I confirm that in devel r266 there is mobile data.

**Comment by ernesst** [comment]
I was having this issue lately, without knowing if it's my new old n5 hardward or software.
To solve it, I switched from devel to rc then back to devel. No more prob.

**Comment by advocatux** [comment]
I've switched from stable to devel (that recovered mobile data) and then switched to stable again, and it keeps the mobile data.

**Comment by tim-sueberkrueb** [comment]
Having this issue right now on devel.

**Comment by SaltyCybernaut** [comment]
From the start receiving MMS on my Nexus 5 running 15.04 r3 (stable) did not work. Recently when I put my GSM SIM back in my Nexus even data did not work. What I did was change the update channel to "Release Candidate" and then back to "Stable" this allowed me to re-download the Stable update r3 and re-apply it (even though I was already on r3). After the reboot both data and MMS were working.

**Comment by tim-sueberkrueb** [comment]
I switched back from 16.04 devel to 15.04 stable and mobile data is working again.

**Comment by UniversalSuperBox** [comment]
Has anyone been able to reproduce this issue lately?

**Comment by timsueberkrueb** [comment]
I personally didn't encounter this issue since.

**Comment by wagafo** [comment]
I've been using the stable channel both in OTA-5 and now in OTA-6 and I haven't seen this issue.

**Comment by ernesst** [comment]
Me neither :)

**Comment by advocatux** [comment]
Okay, then I close the issue

**Comment by firstbyteubp** [comment]
As mentioned in the forum, I still have this problem in OTA-6, even with a fresh installation (including data wipe). I've attached the standard logs.
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2688440/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2688441/UTlogcat.txt)

**Comment by advocatux** [comment]
As it seems some users are still experiencing this issue, I reopen it.

Can anyone else confirm this issue?

**Comment by AlanGriffiths** [comment]
It isn't obvious to me that the latest comment refers to the same issue as described by the OP. In particular, the workaround that resolved it last year is ineffective.

**Comment by advocatux** [comment]
After further monitoring of this issue, I can close this issue again.

For the record: https://forums.ubports.com/topic/2134/no-mobile-data-for-n5-in-ota-6
