### ISSUE TITLE
[xenial] Merge changes done on vivid to xenial

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#384]
Since we (ubports) have been making changes to vivid base using older version of components, We need to merge our changes over to xenial. 

Things that need to merge/change target:
- [x] webbrowser-app
- [x] system-settings
- [x] unity8
- [ ] ofono
- [x] dash-scope
- [ ] oxide
- [ ] camera-app
- [ ] phone-app
- [ ] messaging-app
- [ ] calendar-app
- [ ] filemanager-app
- [ ] gallery-app
- [ ] music-app
- [ ] terminal-app
- [ ] all indicators!
- [ ] geo-clue things
- [ ] notes-app
- [x] repowerd

Please add / comment if i missed something

**Comment by NeoTheThird** [comment]
Should we close the vivid branches after that? Are your keeping track of what's merged and what isn't somewhere?

**Comment by mariogrip** [comment]
@NeoTheThird @Flohack74 can you check if i missed something on the list?

**Comment by balcy** [comment]
for oxide https://github.com/ubports/oxide/pull/2/commits would be appreciated (I've only put them to 1.19)

**Comment by nfsprodriver** [comment]
We may remove those apps from the list, which are base-independent I think.

**Comment by nfsprodriver** [comment]
I think we need to add repowerd etc. We have the three-time-tap-screen issue again.
