### ISSUE TITLE
Permisson switch not deleted when app is removed

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#385]
- Device: Nexus 5
- Channel: Stable
- Build: OTA-3

### Steps to reproduce
Install app (e.g. SensorStatus) having a permission switch under "System settings/Security&Privacy/App Permissions/Location" using Open Store. Remove this app using Open Store.

### Expected behavoir
Permission switch is removed too.

### Actual behavior
Permission switch is not removed. Only the name of the app is deleted.

**Comment by Flohack74** [comment]
Can confirm this!

**Comment by mardy** [comment]
I've done some work with the trust-store in the past, so I might be able to fix this issue, when I find some time. For that reason I'm assigning this to myself.
But if someone wants to work on this before I do, please write here and I'll happily leave this to you :-)

**Comment by NeoTheThird** [comment]
Closing this due to [changed issue tracking process](https://github.com/ubports/docs.ubports.com/pull/92). Can someone confirmed this is fixed?
