### ISSUE TITLE
Add new search engine: Startpage

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#389]
Tracking issue for OTA-4, already done in https://github.com/ubports/webbrowser-app/pull/16.

**Comment by nfsprodriver** [comment]
Already tried around with search suggestions without success, so if someone can add that, would be great!

**Comment by NeoTheThird** [comment]
Closing this due to [changed issue tracking process](https://github.com/ubports/docs.ubports.com/pull/92). Can someone confirmed this is fixed?

**Comment by NeoTheThird** [comment]
Works, thanks guys
