### ISSUE TITLE
[xenial] The os version not showing in the "System settings"->"About"

### ISSUE THREAD

**Issue by BigET** [ubports/ubuntu-touch#391]
- Device:turbo
- Channel:devel/16.04
- Build:??

### Steps to reproduce

Open "System Settings" application.
Open About pane.

### Expected behavoir

In the About pane you should see an entry stating the os version with OTA number in parentheses.
Also he last updated entry and the Check for updates button.

### Actual behavior

There is no version information. Nor last updated nor check for updated button.

The whole "Sofware:" section is missing.

**Comment by jonnius** [comment]
I do not see this issue on FP2, build r93
