### ISSUE TITLE
The "updates" button missing in "System Settings"

### ISSUE THREAD

**Issue by BigET** [ubports/ubuntu-touch#392]
- Device:turbo
- Channel:devel/16.04
- Build:??

### Steps to reproduce

Open "System Settings" application.

### Expected behavoir

There should be an "updates" button near the bottom, also there should be a "reset" button.

### Actual behavior

There is no "updates" button anywhere, also there is no "reset" button.

**Comment by Flohack74** [comment]
Should be resolved by https://github.com/ubports/system-settings/pull/34, but I dont know when this will land.

**Comment by jonnius** [comment]
I have both buttons in build r93 on FP2.

**Comment by ernesst** [comment]
i've too on hammerhead

**Comment by NeoTheThird** [comment]
Fixed.
