### ISSUE TITLE
[xenial] auto-rotation doesn't work

### ISSUE THREAD

**Issue by BigET** [ubports/ubuntu-touch#393]
- Device:turbo
- Channel:devel/16.04
- Build:??

### Steps to reproduce

Power the device.
Make sure the auto-rotation is on.
Rotate the device.

### Expected behavoir

The display should go from portrait to landscape.

### Actual behavior

The display remains to portrait.

### Some more info.
The accelerometer information seems ok. you can see from the numbers (x,y,z) where is down. Tested with SensorsStatus application.

If an application is asking for landscape mode, the display is rotating.
Only the automatic rotation is not happening.

### Logfiles and additional information

[dmesg.log](https://github.com/ubports/ubuntu-touch/files/1593659/dmesg.log)

**Comment by lapor** [comment]
I can confirm this bug in M10 FHD as well.

**Comment by jonnius** [comment]
Same on FP2, build r93

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/qtmir/commit/5ac96a900ed5166e257b3a7ac1939c9cafeaabed

**Comment by riccardovidotto** [comment]
I've the same problem on BQ M10 FHD, Xenial 16.04/rc, build 2018-W28
