### ISSUE TITLE
[xenial] audioflingerglue broken (result in no audio & osk keyboard)

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#395]
On devices that uses this (FP2 and bacon) this will result in no audio at all (and even no osk keyboard since maliit uses pulse, i know BAD!)

**Comment by ChloeWolfieGirl** [comment]
Very BAD!

**Comment by NeoTheThird** [comment]
If a bugreport ends like a tweet from donald trump, you know it's gonna be interesting. BAD!

**Comment by ChloeWolfieGirl** [comment]
These illegal bugs come across the to our operations system, they crash our audio, and break our keyboards, if you vote me for president of Ubports, I'll get these illegal bugs out, and I will make Ubports great again!

**Comment by dpniel** [comment]
No promise of a wall @ChloeWolfieGirl? got to keep the illegal bugs out you know!

**Comment by mariogrip** [comment]
What's going on here? I need to get this bug fixed fast, so we can close this madness

**Comment by ChloeWolfieGirl** [comment]
@dpniel WE WILL BUILD A FIREWALL!

**Comment by jonnius** [comment]
Is this one fixed? I have sound and keyboard in FP2, 16.04/devel, r93.

**Comment by mariogrip** [comment]
Yes this is fixed

**Comment by walidham** [comment]
how did you fix this bug ? audio and keyboard work only when use vivid libhybris-common.so.1.0.0 file.
After change this file, audio work, but when try making call there is no audio.
