### ISSUE TITLE
[xenial] Notifications framework not working

### ISSUE THREAD

**Issue by BigET** [ubports/ubuntu-touch#397]
- Device:turbo
- Channel:devel/16.04
- Build:??

### Steps to reproduce

Power the device with an sdcard in it.
Do anything that would send a notification.
For instance use the "Notification Sender" application form open store.

### Expected behavoir

At the startup with an sdcard you should get 2 messages that about external data being available and being scanned.
You should get some sort of notification.

### Actual behavior

Nothing happens.

### Logfiles and additional information

[dmesg.log](https://github.com/ubports/ubuntu-touch/files/1594518/dmesg.log)

**Comment by ch0001** [comment]
same behavior on frieza

ubuntu-push-client, which provides the dbus interface com.ubuntu.Postal,  is crashing all the time.

I just copied the binary ubuntu-push-client from 15.04/devel and put it into directory /usr/lib/ubuntu-push-client/ . The interface com.ubuntu.Postal was then available, and I got a notifcation when putting in a sdcard.
After recompiling "Notification Sender" this app works too.

I tried to build ubuntu-push-client on xenial but I am stuck with the same error 
> panic: runtime error: cgo argument has Go pointer to Go pointer

**Comment by ch0001** [comment]
I hope there's a more qualified guy working on this (i've no idea about go), but adding 

env GODEBUG="cgocheck=0" 
export GODEBUG

to /usr/share/upstart/sessions/ubuntu-push-client.conf 
_solved_ the problem for me (with ubuntu-push-client from 16.04/devel)

Logfile from fresh reboot and sending a message with npost
[ubuntu-push-client.log](https://github.com/ubports/ubuntu-touch/files/1657398/ubuntu-push-client.log)

**Comment by mariogrip** [comment]
Fix released

**Comment by UniversalSuperBox** [comment]
This issue was a symptom of https://github.com/ubports/ubuntu-touch/issues/446, which was closed by https://github.com/ubports/ubuntu-push/commit/1921122388353e8e840e84dc37663060351fdd04
