### ISSUE TITLE
No keyboard overlay to enable PIN on 16.04

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#399]
- Device: FP2
- Channel: 16.04/dev
- Build: ?

### Steps to reproduce
Start the phone and try to enter PIN.

### Expected behavoir
The keyboard should appear.

### Actual behavior
The keyboard does not appear

### Logfiles and additional information
Can't get in to produce them.

**Comment by ChloeWolfieGirl** [comment]
#395
