### ISSUE TITLE
OPO Camera flash

### ISSUE THREAD

**Issue by rocky58** [ubports/ubuntu-touch#401]
### Illustrations

- Device: OnePlus One
- Channel:
- Build:

**Comment by Flohack74** [comment]
@rocky58 Can you please describe what exactly is the problem?

**Comment by NeoTheThird** [comment]
Thanks for reporting, @rocky58. This seems to be a duplicate of #258. Also, please read the [bugreporting guide](https://docs.ubports.com/en/latest/contribute/bugreporting.html)

**Comment by rocky58** [comment]
Yes, I saw after this issue opening. Flash don't light during photo shut
