### ISSUE TITLE
stats.ubports.com "Total Devices" is wildly inaccurate

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#402]
This bug is also tracked on https://github.com/ubports/ubports.com/issues/50, but its solution will likely involve a change to the system image.

### The problem

Right now, https://stats.ubports.com counts a "new device" for almost every time that a device hits the system-image server asking for an update. There is no provision for deleting devices, so the count continues to go up indefinitely.

This is leading to many problems: People (especially news outlets) quote incorrect device installation numbers and we aren't able to use the stats to make decisions.

In the long-term, we want to be able to track the number of active devices in a way that is anonymous and can be disabled by the user. This means randomly generated IDs that can be reset, an ability to opt-out... Probably some other parts that I'm missing.

An option to opt out of this tracking should be presented in the first-time setup and in Settings > Security and Privacy after that.

**Comment by NeoTheThird** [comment]
As for the short-term solution, i already changed the description in july, but the website was never updated: https://github.com/ubports/stats.ubports.com/commit/c9539bc698dfa4779a2550671e9a69be03f88e0a

Pinging @Flohack74 from the Infrastructure team.

**Comment by Flohack74** [comment]
ping-relaying to @mariogrip because I have no credentials to this server/service and can´t deploy ;)

**Comment by NeoTheThird** [comment]
I don't think we should simply bring back the old tracking, it was inaccurate and not really great for privacy. We might also want to add a mechanism for perfect deniability client-side: https://www.kryogenix.org/days/2018/02/20/collecting-user-data-while-protecting-user-privacy/

**Comment by DigitalPlunderer** [comment]
In general, I opt out of all tracking & analytic feedback for software.  For this project, however, I'd gladly sacrifice a little bit of privacy as a show of support.

Keep up the great work, and I can't wait for a stable 16.04 on my Nexus 5!

**Comment by NeoTheThird** [comment]
@DigitalPlunderer That's the thing, if you integrate a perfect deniability mechanism, you do not have to sacrifice your privacy, and we can still statistically analyze the information w/o being able to connect it to one user. Nobody should have to sacrifice their privacy!

**Comment by Flohack74** [comment]
Adding Infra team here, it definitely intersects also this area.

**Comment by NeoTheThird** [comment]
We should maybe drop this from the OTA-4 milestone.

**Comment by DiogoConstantino** [comment]
This has GDPR/privacy related implications (further work to be done). I think we should drop this at least until we don't have anything better to do this properly.

**Comment by NeoTheThird** [comment]
Of course. The purpose of this issue is to do it properly ;)
