### ISSUE TITLE
[xenial] Remove need for stable-phone-overlay ppa

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#403]
We need to remove the need for the stable-phone-overlay ppa on xenial

**Comment by dpniel** [comment]
Am i right in thinking for this we are wanting to move & rebuild everything in the stable-phone-overlay into the ubports xenial repo?

**Comment by mariogrip** [comment]
Yes

**Comment by dpniel** [comment]
Meh! there looks like there's quite alot of cruft in the stable-phone-overlay we probably don't need like lxqt-qtplugin, kwin, akonadi, kdeclarative. 

Anyway, i'll start at the top with the address-book-app and service it has quite a few deps as well so a good one to get going with

**Comment by mariogrip** [comment]
Yeah that's true, but we do use a updated qt version, so it might be needed at a later on so user is able to install these

**Comment by mariogrip** [comment]
Here is a automated tool that fixes changelog, adds jenkinsfile and do all the importing from bzr to git automatically https://github.com/mariogrip/bzr-to-git

**Comment by dpniel** [comment]
Nice one! that will be handy :-)

**Comment by dpniel** [comment]
Done so far (mainly a note for myself to keep track :-p ):

* account-plugins
* accounts-qml-module
* address-book-app
* address-book-service (need to check this is being seeded)
* akonadi (build failing in ci environment)
* apparmor-easyprof-ubuntu
* autopilot
* libaccounts-glib (MR waiting)
* libaccounts-qt (MR waiting)
* libphonenumber

**Comment by mariogrip** [comment]
Awesome! got the two MR merged :)

**Comment by dpniel** [comment]
bluez 5.41is now in xenial and is a no change rebuild from what's in stable-phone-overlay. But it lacks the blueborne patch. So i've built latest bluez 5.46 including the blueborne patch and is currently in xenial-dev. We need to test this works and if so move it into xenial otherwise i'll apply the patch to 5.41

**Comment by Flohack74** [comment]
Erm that means Bluez is on the same version as in 15.04?

**Comment by dpniel** [comment]
That's correct 5.41 would have landed in yakkety and backported to xenial & vivid

**Comment by Flohack74** [comment]
Hmm no good news :( I was hoping we get a new Bluez in 16.04 which will fix those 1000 problems people have now with pairing, audio and calls etc

**Comment by dpniel** [comment]
Well if bluez 5.46 (from artful) currently in the [xenial-dev](http://repo.ubports.com/pool/xenial-dev/main/b/bluez/) repo works for us, then we can certainly have a new bluez. It just needs testing :-)

**Comment by mariogrip** [comment]
Here are the packages that are still using the ppa:

libsignon-glib1
gir1.2-signon-1.0
libsignon-plugins-common1
signon-plugin-oauth2
libprotobuf-lite9v5
libsignon-extension1
signond
signon-plugin-password
libsignon-qt5-1
signon-ui-service
libgeonames-common
libgeonames0
gnome-desktop3-data
libgnome-desktop-3-12
libzeitgeist-2.0-0
accountsservice-ubuntu-schemas
gsettings-ubuntu-schemas
libprotobuf9v5
qtcore4-l10n
libqtcore4
libqt4-xml
libqtdbus4
qdbus
libqt4-dbus
libqt4-network
libtelepathy-qt4-2
libtelepathy-qt5-0
qt5-image-formats-plugins
qtdeclarative5-ubuntu-syncmonitor0.1
accountsservice-ubuntu-touch-schemas
libtelepathy-qt5-farstream0
zeitgeist-core
account-polld
libbuteosyncfw5-0
buteo-syncfw
qtvideonode-plugin
qtdeclarative5-unity-notifications-plugin
indicator-session
android-tools-adbd
initramfs-tools-ubuntu-touch
syncevolution-common
libgdbussyncevo0
libmtpserver1
libnet-cpp2
libsyncevolution0
libzmq5
mtp-server
nuntium
qtorganizer5-eds
qttranslations5-l10n
signon-apparmor-extension
syncevolution-libs-gnome
syncevolution-libs
syncevolution-dbus
syncevolution-provider-uoa
sync-monitor-helper
sync-monitor
sync-monitor-uoa
syncevolution
libpresage-data
libpresage1v5
libgstreamer-plugins-bad1.0-0
gstreamer1.0-hybris
gstreamer1.0-plugins-bad-faad
gstreamer1.0-plugins-bad-videoparsers
mediaplayer-app
ubuntu-touch-customization-hooks
ubuntu-touch-generic-initrd
unity-scope-mediascanner2
unity-webapps-qml
urfkill

**Comment by dpniel** [comment]
Hmm my list is much shorter than that. Seems i've missed something :-( Out of curiosity how did you generate that list?

**Comment by mariogrip** [comment]
I took the console log from the latest build: https://ci.ubports.com/job/xenial-rootfs-armhf/263/consoleFull

and made a little quick and messy python script to extract the packages:

```
content=[]

with open("consoleOutput.txt") as f:
    rcontent = f.readlines()
    
for x in rcontent:
    if "ppa.launchpad.net/ci-train" in x:
        s=x.strip().split(" ")
        if len(s) > 4:
            if not "[" in s and not "Packages" in s: 
                print(s[4])
```

**Comment by dpniel** [comment]
Hah! very clever. Didn't think of doing that :-)

**Comment by dpniel** [comment]
I don't get why qt4 qdbus is used

```
qtcore4-l10n
libqtcore4
libqt4-xml
libqtdbus4
qdbus
libqt4-dbus
libqt4-network
```
Couldn't we just change that for using qdbus-qt5

**Comment by mariogrip** [comment]
No idea, but yeah, that would be much better.

**Comment by mariogrip** [comment]
Seems like it might be libtelepathy-qt4-2 that requires qdbus

**Comment by dpniel** [comment]
Yeah looks like libtelepathy-qt5-0 is the one pulling those in. 

```
phablet@ubuntu-phablet:~$ apt-cache rdepends libtelepathy-qt4-2
libtelepathy-qt4-2
Reverse Depends:
  libtelepathy-qt5-0
  libtelepathy-qt5-farstream0
```

**Comment by dpniel** [comment]
I've created https://papad.org/p/overlay-2-ubports so we can track easier whats been done of the remaining packages

**Comment by dpniel** [comment]
All that's left now is buteo-syncfw which is failing on jenkins atm. @mariogrip could you take a look at that one please?

**Comment by NeoTheThird** [comment]
Let's keep it open until we have the last package fixed.

**Comment by dpniel** [comment]
seems buteo-syncfw was finished a few days ago.

@mariogrip what is still blocking your rootstock-ng patch to disable overlay being merged?

**Comment by mariogrip** [comment]
Right now it's only https://github.com/ubports/gst-plugins-bad-packaging that is failing to build. I will take a look at that one tomorrow. 

Else then that i think we are good!

**Comment by mariogrip** [comment]
Ok gst-plugins-bad is now building! We are ready, lets break thing! :)

There are the things left, but these are in the xenial repo so no need to import. Some of there may have some difference. So we might want to take a last look and see if we need some of the patches or not.

libprotobuf-lite9v5
gnome-desktop3-data
libgnome-desktop-3-12
libzeitgeist-2.0-0
libprotobuf9v5
zeitgeist-core
android-tools-adbd
initramfs-tools-ubuntu-touch
syncevolution-common
libgdbussyncevo0
libmtpserver1
libsyncevolution0
libzmq5
mtp-server
nuntium
qtorganizer5-eds
signon-apparmor-extension
syncevolution-libs-gnome
syncevolution-libs
syncevolution-dbus
syncevolution-provider-uoa
syncevolution
libpresage-data
libpresage1v5
ubuntu-touch-customization-hooks
ubuntu-touch-generic-initrd
urfkill

**Comment by dpniel** [comment]
\o/ looks like we can close the ppa usage now then. IIRC alot of those remaining ones didn't have many patches, if any, comparing with what was in the archive. I will have another look over them this afternoon just to be sure :-)

**Comment by dpniel** [comment]
@mariogrip yep let's do it :-)

**Comment by mariogrip** [comment]
Done! now let's wait and see how the results are :)
