### ISSUE TITLE
More messages overlapped when searching

### ISSUE THREAD

**Issue by segeta** [ubports/ubuntu-touch#408]
- Device: hammerhead
- Channel: 15.04/rc
- Build: r23

### Steps to reproduce
Open messages (sms) app and search for anything.

### Expected behavoir
Lists the sms that match the search criteria.

### Actual behavior
List the sms but unreadable, because more then one text is in the same line.

**Comment by BlueKenny** [comment]
Same on Bacon with every channel

**Comment by lduboeuf** [comment]
already tracked here: https://github.com/ubports/messaging-app/issues/2 
but would be great if fixed :) same here on BQ 4.5
