### ISSUE TITLE
combind all device spesific configs into once file

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#409]
combind all device specific configs into once file, now we have it spread across different files, this is really really confusing for a porter, we need to be able to have ONE device config file. And if they cannot be placed in a single file, let's place them in the same place so it's easier to understand.

This should also work across the different init systems (upstart, systemd)

Things that is needs device spesific configs:
- [ ] Ofono -> /etc/ofono.override
- [ ] Bluetooth -> /usr/share/bluetooth-touch
- [ ] Touch session.d -> /etc/ubuntu-touch-session.d
- [ ] Repowerd -> /usr/share/repowerd/device-configs

Things that cannot be placed in a config file

- Udev rules -> /usr/lib/lxc-android-config

**Comment by UniversalSuperBox** [comment]
We should probably come to a solution that works for most Halium OSs.

**Comment by mariogrip** [comment]
Moved to: https://github.com/Halium/projectmanagement/issues/38
