### ISSUE TITLE
Hammerhead: r168 ubports-touch (16.04) can´t see wifi, neither connect to wifi

### ISSUE THREAD

**Issue by stefanomelchior** [ubports/ubuntu-touch#414]
- Device: hammerhead (nexus5)
- Channel: ubports-touch/16.04/devel 
- Build: r186

### Steps to reproduce
$ ubuntu-device-flash -v --server=http://system-image.ubports.com touch --device=hammerhead --channel=ubports-touch/16.04/devel
to upgrade my system.
After boot, no wifi detected.
Deleted /home/phablet/.cache directory and reboot
Nothing happened again.
In System setting/wifi/Previous network canceled all the home networks and reboot: nothing happened. System can't detect any network.

Note: NOT sure it can be related with https://github.com/ubports/ubuntu-touch/issues/252

Note: on-ff wifi switch is visible and working

UTdmesg:
[  106.282722] =========== WLAN placed in RESET ========
[  116.116028] Dongle Host Driver, version 1.88.45 (r)
[  116.116040] Compiled in drivers/net/wireless/bcmdhd on Jan  7 2018 at 02:26:10
[  116.116296] wl_android_wifi_on in
[  116.116332] wifi_set_power = 1
[  116.116354] WiFi: trying to acquire BT lock
[  118.111467] ** WiFi: timeout in acquiring bt lock**
[  118.111479] bcm_wifi_set_power: btlock acquired
[  118.111619] ####ignore lock release,  cookie mismatch: WiFi owner BT35 
[  118.263301] bcm_wifi_set_power: wifi power successed to pull up
[  118.471459] =========== WLAN going back to live  ========
[  118.528362] F1 signature OK, socitype:0x1 chip:0x4339 rev:0x1 pkg:0x2
[  118.529022] DHD: dongle ram size is set to 786432(orig 786432) at 0x180000
[  118.597116] _dhdsdio_download_firmware: dongle nvram file download failed
[  118.597159] dhd_dev_reset: dhd_bus_devreset: -35
[  118.597218] dhd_open : wl_android_wifi_on failed (-35)
[  118.597227] wl_android_wifi_off in
[  118.597235] dhd_prot_ioctl : bus is down. we have nothing to do
[  118.597244] dhd_dev_reset: dhd_bus_devreset: -35
[  118.597300] wifi_set_power = 0
[  118.597307] WiFi: trying to acquire BT lock
[  120.591490] ** WiFi: timeout in acquiring bt lock**
[  120.591502] bcm_wifi_set_power: btlock acquired
[  120.591593] ####ignore lock release,  cookie mismatch: WiFi owner BT35 
[  120.692192] bcm_wifi_set_power: wifi power successed to pull down
[  120.692199] =========== WLAN placed in RESET ========
[  120.692743] wl_android_wifi_on in
[  120.692749] WiFi: trying to acquire BT lock
[  122.691688] ** WiFi: timeout in acquiring bt lock**
[  122.691726] bcm_wifi_set_power: btlock acquired
[  122.692204] ####ignore lock release,  cookie mismatch: WiFi owner BT35 
[  122.842291] bcm_wifi_set_power: wifi power successed to pull up
[  123.051644] =========== WLAN going back to live  ========
[  123.123653] net_ratelimit: 2 callbacks suppressed
[  123.123689] F1 signature OK, socitype:0x1 chip:0x4339 rev:0x1 pkg:0x2
[  123.125496] DHD: dongle ram size is set to 786432(orig 786432) at 0x180000
[  123.211804] _dhdsdio_download_firmware: dongle nvram file download failed
[  123.211848] dhd_dev_reset: dhd_bus_devreset: -35
[  123.211906] dhd_open : wl_android_wifi_on failed (-35)
[  123.211914] wl_android_wifi_off in
[  123.211923] dhd_prot_ioctl : bus is down. we have nothing to do
[  123.211931] dhd_dev_reset: dhd_bus_devreset: -35
[  123.211987] wifi_set_power = 0
[  123.211994] WiFi: trying to acquire BT lock
[  125.211564] ** WiFi: timeout in acquiring bt lock**
[  125.211584] bcm_wifi_set_power: btlock acquired
[  125.211750] ####ignore lock release,  cookie mismatch: WiFi owner BT35 
[  125.312064] bcm_wifi_set_power: wifi power successed to pull down
[  125.312072] =========== WLAN placed in RESET ========

UTlogcat: no reference on bug and network issue

phablet@ubuntu-phablet:~$ lsmod | grep -i bcm
lsmod | grep -i bcm
bcmdhd                617922  -2

phablet@ubuntu-phablet:~$ dmesg | grep -i bcmdhd 
dmesg | grep -i bcmdhd 
[    8.656950] Compiled in drivers/net/wireless/bcmdhd on Jan  7 2018 at 02:26:10
[   15.482378] Compiled in drivers/net/wireless/bcmdhd on Jan  7 2018 at 02:26:10
**[   18.156225] dhd_bus_start: dhdsdio_probe_download failed. firmware = /vendor/firmware/fw_bcmdhd.bin nvram = /etc/wifi/bcmdhd.cal**
[   20.594007] Compiled in drivers/net/wireless/bcmdhd on Jan  7 2018 at 02:26:10
...
[  116.116040] Compiled in drivers/net/wireless/bcmdhd on Jan  7 2018 at 02:26:10

guf@Guf-Book:~$ adb shell /bin/bash
phablet@ubuntu-phablet:~$ nmcli -p g
nmcli -p g
================================================================
                     NetworkManager status
================================================================
STATE         CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
----------------------------------------------------------------
disconnected  none          enabled  enabled  enabled  enabled

phablet@ubuntu-phablet:~$ nmcli -p d
nmcli -p d
===========================================
             Status of devices
===========================================
DEVICE  TYPE      STATE        CONNECTION 
-------------------------------------------
ril_0   gsm       unavailable  --         
**wlan0   wifi      unavailable  --**         
sit0    iptunnel  unmanaged    --         
lo      loopback  unmanaged    --

**Comment by nfsprodriver** [comment]
I can confirm (no logs yet).

**Comment by nfsprodriver** [comment]
That problem occured after switching from devices-files to ubuntu-overlay. Looks like the different etc paths or wifi files are incorrect or at the wrong place.

**Comment by ernesst** [comment]
On 16.04 r189 & r190, I didn't noticed the problem. it's fixed i guess ?

**Comment by stefanomelchior** [comment]
I don't know if it is the same problem, but neither with frieza r9-r10-r11 xenial I couldn't connect to any wifi network. On top of this, I can not see any on-off wifi switch.
For QA team: does it make sense to add a new label to this issue to include frieza?

**Comment by ricmm** [comment]
I dont see this on r191 hammerhead. @stefanomelchior could you re-check?

**Comment by stefanomelchior** [comment]
@ricmm hello Ricardo! I confirm with r191 this issue disappeared and now WiFi is back and working

**Comment by muskrat215** [comment]
I had a similar problem on my OnePlus One.  When I pulled up Wifi settings, I could only see 'Previously connected devices.'  No button.  No Wifi icon at the top of the screen.  Rebooting didn't fix it.  I finally fixed mine by turning off 'Developer Mode' and rebooting...
