### ISSUE TITLE
Ubuntu Touch 16.04 does not boot

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#416]
- Device: FP2
- Channel: 16.04/dev
- Build: ?

### Steps to reproduce
16.04/dev using the official installer. Start the phone.

### Expected behavoir
The phone boots.

### Actual behavior
The phone displays the boot screen with the dots forever and gets hot.

### Logfiles and additional information
Not possible, I guess. Or would it after reverting it to 15.04?

**Comment by ivoxavier** [comment]
I can confirm also. Does not boot, even after many flashes using UBports installer.

**Comment by mariogrip** [comment]
Fix has been released, please try now

**Comment by jonnius** [comment]
I confirm, the issue is solved.
