### ISSUE TITLE
[xenial] Can't activate Bluetooth on FP2 16.04

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#417]
- Device: FP2
- Channel: 16.04/devel
- Build: r93

### Steps to reproduce
Try to enable Bluetooth using the indicator or via system settings.

### Expected behavoir
Bluetooth is enabled. Devices can be found.

### Actual behavior
Bluetooth is not enabled. When leaving leaving and entering Bluetooth menu again, the switch is disabled again. No devices are found.

### Logfiles and additional information
[UTdmesg.log](https://github.com/ubports/ubuntu-touch/files/1610813/UTdmesg.log)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1610815/UTlogcat.txt)

**Comment by ernesst** [comment]
Same behavior on r199 Xenial hammerhead

**Comment by Jujuyeh** [comment]
I can't deactivate bluetooth on **turbo**. It might be related to this issue.

The Bluetooth indicator switch seems not to be sync'd with the System Settings one.

Deactivating bluetooth from System Settings won't take any effect, as if I close and reopen the System Settings, bluetooth will appear as turned on.

![screenshot20180128_121911321](https://user-images.githubusercontent.com/13997685/35481952-0be274d6-042e-11e8-9b14-b653fd22bb15.png)

Logs from this [issue](https://github.com/ubports/ubuntu-touch/issues/455) might be useful.

**Comment by Dantali0n** [comment]
I experience the same behavior on Oneplus Bacon with devel build r128. Using the system settings about page it shows the wrong Bluetooth mac address for my physical adapter.
