### ISSUE TITLE
Make OpenStore pinned by default on the side launcher

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#418]
### Description of the feature
Since OTA-3, OpenStore is the only Store we can install apps from and, thus, part of the eco system. So, we could "promote" the app to the launcher, as the other already placed there. For first users, its easy to spot it. Also, its make the process of opening OpenStore faster since its just one swipe and click.

**Comment by mateosalta** [comment]
Ok, trying this out. I'm not sure if I got the syntax right - but I think this is the file responsible for setting the default favorites for gsettings - https://github.com/mateosalta/unity8/commit/ce819e77e7d9a107c4c5296cd052f781e19f82b9#diff-298cdd2a2f175ae0dba130e2b16f4404

Also, which position do we want the open store to be in? this will put it just after the webbrowser, or perhaps do we want it one down next to system settings?

**Comment by dpniel** [comment]
@mateosalta personally i would have it between system-settings and camera so it's roughly in the centre. IIRC the software-centre was in a similar position on Unity 7

**Comment by mateosalta** [comment]
Cool, that sounds like a good position, needs testing to see if the namespace is correct to launch.
