### ISSUE TITLE
[xenial] Messages are still marked as unread after reading

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#419]
- Device: FP2
- Channel: 16.04/devel
- Build: r93

### Steps to reproduce
Get some SMS. Open messages app. Open unread messages. Leave them.

### Expected behavoir
Messages are not marked as unread any more.

### Actual behavior
Messages are still marked as unread, indicated by a green number on the top left of the contact icon.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1612833/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1612834/UTlogcat.txt)

**Comment by brispete** [comment]
Happens on my Nexus 5 too.

**Comment by mariogrip** [comment]
Fixed with https://github.com/ubports/history-service/commit/4cc0bcc3e74dcdbe34faafc46e879004fba917f4
