### ISSUE TITLE
[xenial] Cannot enable SIM card on FP2 16.04

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#420]
- Device: FP2
- Channel: 16.04/devel
- Build: r93

### Steps to reproduce
Insert SIM card. Start the phone. Look at the network indicator. Go to system settings -> Net and try to change settings. 

### Expected behaviour
The phone asks for the PIN and enables the SIM card.

### Actual behavior
The network indicator shows Unknown ("Nicht bekannt") under SIM 1. The system settings Net menu shows disabled switches for mobile data and data roaming. The provider & APN menu does not open. In short I cannot use phone, SMS or mobile data.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1612966/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1612967/UTlogcat.txt)

**Comment by ernesst** [comment]
I got similar behavior  on the N5 r199 xenial, except that i get cell signal and i can receive and make call. Otherwise the same, in the setting it says no sim detected.

**Comment by UniversalSuperBox** [comment]
I can confirm this on the FP2. The Settings page simply stays at "No SIM detected." The following appears in the Settings app's logs when trying to load the page:

```
QProcess::start: Process is already running
file:///usr/share/ubuntu/settings/system/qml-plugins/cellular/PageComponent.qml:30:1: QML PageComponent: Binding loop detected for property "height"
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
QQmlComponent: Component is not ready
qml: Failed to create Sim qml: file:///usr/share/ubuntu/settings/system/qml-plugins/cellular/Components/Sim.qml:93 OfonoMtkSettings is not a type

QQmlComponent: Component is not ready
qml: Failed to create Sim qml: file:///usr/share/ubuntu/settings/system/qml-plugins/cellular/Components/Sim.qml:93 OfonoMtkSettings is not a type

file:///usr/share/ubuntu/settings/system/qml-plugins/cellular/PageComponent.qml:30:1: QML PageComponent: Binding loop detected for property "height"
[PERFORMANCE]: Last frame took 35 ms to render.
```

**Comment by jonnius** [comment]
On r113 the SIM card is working. The network indicator works correctly and mobile data works fine. But the system settings page now only shows "No Sim card found" and "Insert Sim card an restart phone" (translated). This is different than before and therefore, this is another bug.
