### ISSUE TITLE
[xenial] M10 FHD doesn't turn off from first try

### ISSUE THREAD

**Issue by lapor** [ubports/ubuntu-touch#424]
### Description of the feature
Tablet should turn off when you want to turn it off.

### Illustrations

- Device: M10 FHD
- Channel: 16.04/devel
- Build:?

### Steps to reproduce
Go the right top panel, swipe it down and click on the turn off button. Confirm it that you want to turn off.

### Expected behavior
It should turn off.

### Actual behavior
It restarts. After the restart it does turn off.

**Comment by gabriel-lucas** [comment]
In r16 I can´t reproduce it. It works as expected.

**Comment by lapor** [comment]
Yes, it has been fixed. Thanks
