### ISSUE TITLE
[xenial] Nexus 5: you can activate Bluetooth, but dropdown menu and system setting are not sync'd; moreover no devices can't be found

### ISSUE THREAD

**Issue by stefanomelchior** [ubports/ubuntu-touch#427]
- Device: Hammerhead
- Channel: 16.04/devel
- Build: r197

### Steps to reproduce

On hammerhead (xenial/r197) I noticed that when you enable bluetooth from dropdown menu, then you go into the bluetooth setting, the on/off switch is disabled.

###Steps to reproduce

Enable BT from dropdown menu (turn it on)
Tap on Bluetooth setting and enter in its configuration.

###Expected behaviour
I expect the switch to keep on being on

##Actual behaviour
The switch is off.
When I set it up to on (into BT settings menu), Hammerhead can not find any bluetooth device nearby (I tested with other 2 devices there are some devices with bluetooth active closed by)

### Logfiles and additional information
[UTsyslog-hammerhead-xenial-r197.txt](https://github.com/ubports/ubuntu-touch/files/1625810/UTsyslog-hammerhead-xenial-r197.txt
[UTdmesg-hammerhead-xenial-r197.txt](https://github.com/ubports/ubuntu-touch/files/1625814/UTdmesg-hammerhead-xenial-r197.txt)
[UTlogcat-hammerhead-xenial-r197.txt](https://github.com/ubports/ubuntu-touch/files/1625811/UTlogcat-hammerhead-xenial-r197.txt)

**Comment by stefanomelchior** [comment]
It might be related to https://github.com/ubports/ubuntu-touch/issues/417

**Comment by mariogrip** [comment]
This seems to be similar to this https://github.com/ubports/ubuntu-touch/issues/482

Can you confirm?
