### ISSUE TITLE
[xenial] Online account missing

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#428]
### Description of the feature
Online account are missing on the current build. 
The online account menu offers only to create Google and Ubuntu one account.

Vivid build offers owncloud and nextcloud for caldav purpose and bookmarks applications.

### Illustrations

- Device: hammerhead
- Channel: 16.04
- Build: 199

### Expected behavior
The Xenial offers the last improvements from https://github.com/ubports/account-plugins

### Actual behavior
The account-plugins is build from another repository

### Logfiles and additional information

Strangely there is a onwcloud plugins build in the phone : 

root@ubuntu-phablet:/home/phablet# ls /usr/share/accounts/qml-plugins/
facebook/  flickr/    google/    owncloud/  twitter/   ubuntuone/

**Comment by mariogrip** [comment]
@mardy Any thoughts?

**Comment by mardy** [comment]
If the account is there, it might be a problem with sync-monitor; either it's not installed, or for some reason it's not installing the needed `.service` files. I'll check.

**Comment by mariogrip** [comment]
Sync-monitor seems to be running

```
cat .cache/upstart/sync-monitor.log
[03/04/1970 12:30] Loaded tempaltes: ("google", "owncloud", "yahoo")
[03/04/1970 12:30] Loading accounts...
[03/04/1970 12:30] Remove old config...
[03/04/1970 12:30] Network is offline
[03/04/1970 12:31] Network is offline
[03/04/1970 12:31] New connection type: "WLAN"
[03/04/1970 12:31] Network state changed: Online
[03/04/1970 12:31] Device is online sync pending changes 0
[03/04/1970 12:31] No change to sync

```

**Comment by mardy** [comment]
So, the owncloud account is there. The nextcloud account is not there, because the `ubuntu-touch` meta package lacks a dependency on `account-plugin-nextcloud`. @mariogrip, can you please add it back? 

I can see the owncloud account, @ernesst , so I wonder why you don't see it. Do you have the `/usr/share/accounts/services/owncloud-caldav.service` file in your phone? And what about `~/.local/share/accounts/applications/com.ubuntu.calendar_calendar.application`?

**Comment by mariogrip** [comment]
@mardy humm, i cannot see ownclould, evernote or generic caldav ether. I only got google and Ubuntu one

**Comment by mariogrip** [comment]
@mardy added the account-plugin-nextcloud to the meta

But when i install it, it does not appear

**Comment by ernesst** [comment]
```
root@ubuntu-phablet:/home/phablet# ls /usr/share/accounts/services/
facebook-microblog.service     google-drive.service
facebook-sharing.service       google-im.service
flickr-microblog.service       owncloud-caldav.service
flickr-sharing.service         picasa.service
google-buteo-contacts.service  twitter-microblog.service
google-caldav.service          ubuntuone.service

```
and ~/.local/share/accounts/applications/com.ubuntu.calendar_calendar.application is empty.

**Comment by mardy** [comment]
The accounts appear only if there's at least one application which can use them. It looks like you don't have the calendar application installed?

**Comment by ernesst** [comment]
I've the icon, but the app doesn't start...

**Comment by dpniel** [comment]
This seems to be fixed for me on arale r51. Could someone else confirm they see all accounts now?

**Comment by NeoTheThird** [comment]
[Moving to QA to test]
