### ISSUE TITLE
[xenial] Flight mode - button and indication missing.

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#429]
- Device: Hammerhead
- Channel: 16.04
- Build:199

### Steps to reproduce
Put the phone in flight mode

### Expected behavior
- Toggle menu in the wireless menu
- flight icons showing up

### Actual behavior
- Going to the phone setting
- empty icon wifi showing up.

**Comment by NeoTheThird** [comment]
Still an issue

**Comment by mariogrip** [comment]
Fixed with: https://github.com/ubports/ubuntu-touch/issues/429
