### ISSUE TITLE
[xenial] - Windows list : backward apps selection

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#430]
- Device: hammerhead
- Channel: 16.04
- Build: 199

### Steps to reproduce
Windows list, while moving the finger slowly in one direction the windows selection could go on the other direct.

### Expected behavior
Like vivid

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/unity8/commit/035c3fefdb716358810cb2528757ac2cd0d3eef2
