### ISSUE TITLE
Krillin (BQ Aquaris E4.5): Excessive battery consumption when screen is on and connected to mobile data

### ISSUE THREAD

**Issue by manolollr** [ubports/ubuntu-touch#433]
- Device: Krillin
- Channel: OTA 3 / stable

**Steps to reproduce**
Switch on mobile data and use the phone (ie: view Telegram, view Internet, play an offline game, etc.)

**Expected behaviour**
Before OTA 3 battery life was longer, connected to wifi or to mobile data.

**Actual behaviour**
When phone is in sleep mode (screen off) there is no battery drain, but when screen is on and phone is connected to 3G there is excessive battery consumption, about 1% per minute, even if playing an offline game, without transferring data from Internet. If you connect to wifi battery consumption is lower, about 1% every 5 minutes, it's acceptable.

Screen brightness is set to 25%

**Logfiles and additional information**
If logfiles are needed, I can provide them. I could also provide screenshots with battery graph from the settings, if needed.

**Comment by NeoTheThird** [comment]
Thanks for reporting. Is the behavior you're experiencing different from #154 #295 #387 and #407 ?

**Comment by lduboeuf** [comment]
@manolollr do you still face that issue since ?

**Comment by manolollr** [comment]
No.
