### ISSUE TITLE
Update portugese keyboard

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#436]
See https://github.com/ubports/keyboard-component/pull/31. Thanks to @ivoxavier.

**Comment by NeoTheThird** [comment]
@ivoxavier Please confirm everything works in the latest 16.04/devel build.

**Comment by ivoxavier** [comment]
@NeoTheThird not landed yet. Still have the old layout.

**Comment by Flohack74** [comment]
Interesting it was built and sent to repo.ubports.com - should be picked up from there.

**Comment by ivoxavier** [comment]
I'm on ubports-touch/16.04/devel/FP2. I'll make a clean install and see if something change. 

For 15.04/devel no updates

**Comment by Flohack74** [comment]
Uh yes forget it, I was looking into 16.04, and its there. In 15.04 we dont build right now I think. Clean installation will change nothing, if the daily build did not have it.

**Comment by ivoxavier** [comment]
It landed today! So far so good. Thanks!

**Comment by NeoTheThird** [comment]
Great!
