### ISSUE TITLE
[xenial] No Gps

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#440]
- Device: hammerhead
- Channel: 16.04
- Build: r215

### Steps to reproduce

test_gps

### Actual behavior
No gps localisation

### Logfiles and additional information
https://paste.ubuntu.com/26441697/
&
https://paste.ubuntu.com/26441736/

**Comment by tomoqv** [comment]
I just installed 16.04 (r216) on my Nexus 5 and GPS works for me, although it takes a while for it to fix. I opened uNav and tried to determine my position. The positioning indicator lit up and after putting it near a window it had found my position after some time (not sure how long, though).

**Comment by NeoTheThird** [comment]
GPS being slow is not a new issue on Ubuntu Touch. As @tomoqv wrote, it does work in general on xenial, it's just slow. Closing for now.
