### ISSUE TITLE
[xenial] Huge battery drain after 24h offline

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#441]
- Device: Hammerhead
- Channel: 16.04
- Build: r215

### Steps to reproduce
Put the phone in flight mode and wait 24h, 

### Expected behavior
couple of % down

### Actual behavior
the battery will be close to 5% from 100%.

### Logfiles and additional information
I'm missing idea where to pull log

https://paste.ubuntu.com/26441755/

**Comment by yancelawang** [comment]
i'm in 15.04 (r3) also got this issue. 97% at 01.00 AM drain to 60% at 06.00 AM when offline

**Comment by NeoTheThird** [comment]
A little too vague and also present in vivid: #387.
