### ISSUE TITLE
Camera image quality setting has no effect

### ISSUE THREAD

**Issue by masda-gib** [ubports/ubuntu-touch#443]
- Device: BQ Aquaris 5 HD
- Channel: Release
- Build: 15.04 r14 (OTA-3)

### Steps to reproduce
Select highest image quality in camera app and take a picture. Then select lowest image quality and take a picture. 

### Expected behavior
I would expect to have some kind of jpeg compression when I select low image quality. File size should not be like that of an uncompressed image.

### Actual behavior
The files have (roughly) the same size regardless of set image quality and the file size is huge!
I have 9.4MP (1270x720) selected and my pictures are 2.5 - 4 MB. (Those files are jpegs)
Even saving those images with 98% jpeg quality in an image manipulation programm reduces the size to a ranges around 100 kilobyte.

**Comment by dark-eye** [comment]
this might also be  a camera app issue, i'll investigate...

**Comment by Flohack74** [comment]
Since @dark-eye introduced the size selector to list all possible resolutions the files are being smaller. Do you switch the quality or the resolution?

**Comment by masda-gib** [comment]
I switched the quality setting.
I just made 4 images of the same motive:
- 9,4 MPixel low quality: 3,5MB
- 9,4 MPixel high quality: 3,5MB
- 19,5 MPixel low quality: 6,5MB
- 19,5 MPixel high quality: 6,5MB

So, the file size changes as expected, half size for half megapixels. But quality seems to have no influence. Looking at the file size, it seems to be stuck at ultra-high quality. :)

**Comment by Flohack74** [comment]
Quality has no influence, yes, but this was always like that. We inherited that from Canonical times ;)

**Comment by NeoTheThird** [comment]
Does this affect all devices?

**Comment by dark-eye** [comment]
@Flohack74  Maybe move this to the camera app  by a short overview of the code it seems that theres a bug in the code were it maps the encodingQuality to the resolution property instaed of the advanced property.

**Comment by Flohack74** [comment]
This issue was moved to ubports/camera-app#60
