### ISSUE TITLE
[xenial] Timezone lost between reboot

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#447]
- Device:hammerhead
- Channel:16.04
- Build:R217

### Actual behavior

Appear empty after each reboot

![image](https://user-images.githubusercontent.com/11337464/35424652-8ba406be-021a-11e8-9818-961a7f563d1b.png)

**Comment by zubozrout** [comment]
I can confirm the same behaviour on MX4.

**Comment by Ingo-FP-Angel** [comment]
I can confirm for FP2 on 16.04 r166

**Comment by Flohack74** [comment]
Here we go again...

**Comment by mariogrip** [comment]
Fixed with: https://github.com/ubports/systemd-packaging/commit/744063301a0a73501d8f62aa244f506c221edd8b 

Please note may you need to reset your timezone!
