### ISSUE TITLE
[xenial] ssh x11 forwarding doesn't work

### ISSUE THREAD

**Issue by ch0001** [ubports/ubuntu-touch#449]
- Device: frieza
- Channel: 16.04/devel
- Build: r24

### Steps to reproduce
run 
`> ssh -X phablet@192.168.xxx.xxx.`

### Expected behavior
i can foward x11 clients from device to my local Xserver

### Actual behavior
ssh X11 forwarding doesn't work, because xauth is not installed

### Logfiles and additional information
`> ssh -v -X phablet@192.168.xxx.xxx`
`debug1: Remote: No xauth program; cannot forward with spoofing.`
`X11 forwarding request failed on channel 0`

`> dpkg-query -L xauth`
`dpkg-query: package 'xauth' is not installed`

**Comment by NeoTheThird** [comment]
Does not work for me.

**Comment by mariogrip** [comment]
Seems to work fine for me. not sure what app you tried @NeoTheThird, but you will need to set qt qpa to x11 to to run any qt apps btw. I tried here with xeyes

![screenshot from 2018-05-05 16-28-18](https://user-images.githubusercontent.com/1642635/39664296-72098e4e-5081-11e8-81ae-f6fccd36c132.png)

**Comment by NeoTheThird** [comment]
Huh, you are right. I don't know what i did there...
