### ISSUE TITLE
[xenial] - Nexus 4 Doesn't boot

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#450]
- Device: Mako
- Channel: 16.04
- Build: r15 to 23

### Steps to reproduce
Install xenial

### Expected behavior
Boot

### Actual behavior
Doesn't boot, doesn't show any ubuntu screen, after the goole goes black, high drain of the battery
r12  does actually boot every 2 starts.

### Logfiles and additional information
Let me know where to pull the log

**Comment by simoxxx** [comment]
i confirm this bug is present in version r33 too. 
1st boot shows google log, then 3 sec ubuntu boot and black screen forever.
2nd boot i need to press a bit longer and it boot normaly.

**Comment by HendriXXX** [comment]
Boots fine here. Latest r47 installed.

**Comment by mariogrip** [comment]
This issue seems to be fixed, Please open if you still have problems
