### ISSUE TITLE
OSK Space bar cursor control needs recalibration

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#451]
- Device: bq E5 HD
- Channel: Stable
- Build: OTA3

### Steps to reproduce
1. Tap on any text fields preferably multi-line.
2. Input any texts (multiple line if multi-line text field)
3. Hold the space bar until the cursor control is active.
4. Try to move the cursor to where you intend it to go.

### Expected behavior
The cursor should stay in its current position until you swipe in any direction.

### Actual behavior
Most of the time, the cursor already moves at the moment the cursor control is activated. This causes the control not smooth.

### Logfiles and additional information
This issue is mostly noticeable when in a multi-line text field. The cursor would go up often even if not intended.

**Comment by NeoTheThird** [comment]
Hmm, still an issue. @mariogrip This PR was merged into master, we need to get it into vivid and xenial, right?

**Comment by mariogrip** [comment]
@NeoTheThird Ah! will merge it into xenial.
