### ISSUE TITLE
Improvements for the Italian keyboard

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/ubuntu-touch#452]
Hello!
I would like to point out an improvement for the Italian keyboard.
In Italian **_there is_** is written **_c'è_** and it would be great if typing **_ce_** appeares **_c'è_** between the suggestions.
In general it should suggest the words joined by the apostrophes also writing only the letters, without typing them because they waste time.

**Comment by Flohack74** [comment]
This issue was moved to ubports/keyboard-component#33
