### ISSUE TITLE
Porting to new device.

### ISSUE THREAD

**Issue by zhenyolka** [ubports/ubuntu-touch#454]
Hello!
I want to port ubuntu touch to my device.
Where is a guide to porting?
And I have old pc(x86_64, intel celeron, 2GB RAM), can i port with this pc?
Sorry for my English and thanks for you answer.

**Comment by Flohack74** [comment]
Hello,

Ubuntu Touch uses Halium abstraction layer to boot and prepare the initial ramdisk, so please follow this guide: http://docs.halium.org/en/latest/

Until you can run the reference root fs you do not need start using Ubuntu Touch root fs. You need a successful boot into that Halium root fs first.

For the second question, 2GB is very limited, but could work still. You need more time. How much harddisk do you have? The Android tree will consume up to 40GB or so of your disk for building.
