### ISSUE TITLE
[xenial] No SIM on turbo

### ISSUE THREAD

**Issue by Jujuyeh** [ubports/ubuntu-touch#455]
- Device: Meizu Pro 5 (turbo)
- Channel: devel/16.04
- Build: r24

### Steps to reproduce
Fresh install the latest version of Ubuntu Touch 16.04 on *turbo*

### Expected behavior
Ask for SIM passcode and all it's functions (cellular data, mobile settings, ...)

### Actual behavior
It won't ask for the PIN.

### Logfiles and additional information

I tried with both SIM trays, same bug.

#### dmesg

https://etherpad.net/p/turboIssueDataDMESG1

#### logcat

```
D/libEGL  (12299): loaded /vendor/lib/egl/libGLES_mali.so
D/mali_winsys(12299): new_window_surface returns 0x3000,  [1080x1857]-format:2
E/cutils-trace(12299): Error opening trace file: Permission denied (13)
```
![screenshot20180128_115409523](https://user-images.githubusercontent.com/13997685/35481903-1ccba570-042d-11e8-886c-9a115c59048d.png)

**Comment by Ruditimmermans** [comment]
@mariogrip

**Comment by tomoqv** [comment]
Do you have Anbox installed?

**Comment by Jujuyeh** [comment]
Yes, I installed Anbox.

(I went back to 15.04/devel... It's my daily driver and I just wanted to try 16.04 and give some feedback)

**Comment by Ruditimmermans** [comment]
If im not wrong the mobile network get lost when you install Anbox.

**Comment by Ruditimmermans** [comment]
Lets hope the fix this soon se we can do more testing ....

**Comment by dark-eye** [comment]
This seems to still happen when installing anbox on turbo... might it be a good idea to open an issue about it?

**Comment by tudorels** [comment]
It acts the same for me. When I tried to install Anbox I lost wifi and cellular connection. I used the latest version of 16.04 r85 on my Meizu Pro 5. Thank you!
