### ISSUE TITLE
[xenial] audio stops when device when put to sleep

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#459]
### Illustrations

- Device: bacon
- Channel: 16.04/devel
- Build: r129

### Steps to reproduce

1. Play audio on device: eg. podbird, music, etc
2. Press power button to sleep / turn of screen

### Expected behavior

- Audio keeps playing 

### Actual behavior

- Audio stops
- If the device is allowed to timeout and sleep on its own then the audio keeps playing, but the power button kills all audio.

**Comment by HendriXXX** [comment]
I have this problem with N4 xenial r48. When I listen podbird and screen goes off, sound starts stuttering. If I wake device sound is good again.

**Comment by Flohack74** [comment]
Same on FP2, sound gets really bad when device is locked.

**Comment by mariogrip** [comment]
Fix pushed, downgraded https://github.com/ubports/repowerd

**Comment by ivoxavier** [comment]
I'm still facing this issue on rev.252 (xenial)Fairphone2. If I use music app for continuasly after 10 min aprrox the sound stop, and keep back and going. When I woke the screen sound goes ok. Closing and opening the app fix the issue, but after sometime same problem.
