### ISSUE TITLE
Application Window size and position resets when the app is opened in Staged mode

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#460]
- Device: Nexus 5
- Channel: Stable
- Build: OTA 3

### Steps to reproduce
1. Switch to Desktop/Windows mode (i.e. via UT Tweak Tool)
2. Open an app and resize it and position in anyway you want.
3. Close the app and then reopen. The app's window size and position is restored correctly.
4. Switch to Staged mode.
5. Open the same app and then close.
6. Switch back to Desktop/Windows mode (i.e. via UT Tweak Tool)
7. Open again the same app.

### Expected behavior
The app's window size and position should be restored correctly to their last cached values.

### Actual behavior
The app's window size and position are not restored correctly after opening the same app in Staged mode prior to opening it in Windowed mode.

### Logfiles and additional information
None

**Comment by doniks** [comment]
I've played around a bit with opening/closing/desktop/staging while checking the.cache/unity8/window...sql
and it seems that upon closing an app in staged mode we store dimension and position 0

**Comment by doniks** [comment]
Id like to try and solve this myself, but @NeoTheThird can you give me a pointer where to start looking? where is the code responsible for starting / tearing down an app?

**Comment by dpniel** [comment]
@doniks You probably want to be looking at https://github.com/ubports/unity8/blob/xenial/plugins/Utils/windowstatestorage.cpp and it's usage in qml here https://github.com/ubports/unity8/blob/e40217fc434c8de8d7a0485ca6e18b3b33c00edf/qml/Stage/WindowResizeArea.qml#L98

**Comment by doniks** [comment]
Thanks @dpniel !

I have changed that method now to simply not store 0 width: 

```
    function saveWindowState() {
        var state = target.windowState;
        if (state === WindowStateStorage.WindowStateRestored) {
            state = WindowStateStorage.WindowStateNormal;
        }
        windowStateStorage.saveState(root.windowId, state & ~WindowStateStorage.WindowStateMinimized); // clear the minimized bit when saving
        if ( priv.normalWidth !== 0 )
        {
            windowStateStorage.saveGeometry(root.windowId, Qt.rect(priv.normalX, priv.normalY, priv.normalWidth, priv.normalHeight));
        }
    }
```

One could argue that we should do something smarter, but I think writing 0 is always wrong, so let's stop doing it. 

I have played around now for about half an hour, closing, opening, resizing and switching back and forth between staged and desktop. All windows kept their size and position now after I had once dragged them  to a reasonable size. 

I couldn't find anything else that breaks.

**Comment by kugiigi** [comment]
I think if it's possible, the geometry should not be saved when in staged mode. I guess that's when geometry values are 0.

**Comment by doniks** [comment]
Yeah, I thought about it. But I couldn't immediately find out how to detect staged at that place in the code. And again, I doubt that there is ever a valid reason why it is expected to write 0. Staged mode, Desktop mode, or project it on the moon mode. 0 is never meaningful.

**Comment by kugiigi** [comment]
Okay, I agree.
This does not affect the window position right? Because I think 0 value for x and y is valid.
@doniks can you PR it as per @Flohack74 ? :stuck_out_tongue_winking_eye:

**Comment by Flohack74** [comment]
Ah sry @kugiigi I did not look for the OP (original poster) xD

**Comment by doniks** [comment]
Will do

**Comment by NeoTheThird** [comment]
Thanks guys! Adding to QA...
