### ISSUE TITLE
[xenial] list of apps not working properly

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#461]
### Illustrations

- Device: bacon
- Channel: 16.04/devel
- Build: r129

A lot of apps are not opening or functioning properly. This is probably due to a related issue, so I lumped them all together.

### Steps to reproduce

- Try to open app

### Expected behavior

- App opens and functions normally

### Actual behavior

- Dekko2: loads indefinitely
- Timer: loads indefinitely
- OpenStore: loads but does not display apps or functionality
- Calendar: loads indefinitely
- Telegram: loads but gets stuck at the phone number verification
- Gallery: closes immediately
- UT Tweak Tool: loads but has no access to functions / displays no content
- Indicator Weather: loads but loses field to enter API key
- File manager: blank screen
- Notes: loads indefinitely
- Translator: Loads but language selection doesn't work
- Terminal: "Ubuntu" color scheme is all white? / typing "exit" causes terminal to hang instead of quit / cursor starts mid text.
-

### Logfiles and additional information

Cannot access logs on bacon due to computers not recognizing it plugged in on Ubuntu 17.10 , adb issue?

**Comment by Ingo-FP-Angel** [comment]
For the FP2 (with new 12 MP camera module) these are my observations on r179:

- Camera: loads indefinitely
- Clock: loads but exits almost immediately
- Media player: loads but cannot display anything
- Music: loads but doesn't find MP3 files in ~/Music
- Notes: loads but notes are not saved
- OpenStore: loads but does not display apps or functionality
- Dekko2: loads indefinitely
- Logviewer: loads but exits almost immediately
- Telegram: loads but gets stuck at the phone number verification

**Comment by mariogrip** [comment]
All core apps should now be fixed, OpenStore will land in next devel. For the non-core apps those needs to be no-change rebuilt to xenial by there creators, since xenial has an abi breakage.

**Comment by zubozrout** [comment]
Has the new OpenStore landed in the new devel images? It doesn't seem to be working on my MX4 arale though it may just be that it has not been pushed to the images yet.
