### ISSUE TITLE
[xenial] no  sim detected in  settings menu

### ISSUE THREAD

**Issue by Kosztyk** [ubports/ubuntu-touch#470]
Ubuntu touch 16.04 r238
Nexus 5
In Settings menu at mobilei receive”no sim detected”
Calls ansd sms are working but i cannot use mobile inernet because i can't settup the APN.

**Comment by devonman01** [comment]
identical issue,turbo, r35

**Comment by mariogrip** [comment]
Fixed with https://github.com/ubports/libqofono/commit/40428f44de9e8c644132a4209c3687232e5ad8d0
