### ISSUE TITLE
"Agent admitted failure to sign using the key" when using pubkey authentication with ssh

### ISSUE THREAD

**Issue by Talkless** [ubports/ubuntu-touch#475]
- Device: BQ E5
- Channel: Stable
- Build: 20171218 

### Steps to reproduce
```
ssh-keygen
ssh-copy-id user@server
ssh user@server
```
I get:
```
Agent admitted failure to sign using the key
```
Workaround:
```
SSH_AUTH_SOCK=0 ssh user@server
```

### Expected behavior
ssh pubkey authenticatin should work from terminal app by default.

### Actual behavior

Error `Agent admitted failure to sign using the key` occurs, workaround needed.

**Comment by stekalb** [comment]
- Device: mx4
- Channel: devel
- build: 281

works as expected on mx4

**Comment by stekalb** [comment]
- Device bq e4.5
- channel: 15.04/devel
- build: r60

works as expected on bq e4.5

**Comment by hummlbach** [comment]
I can confirm this on turbo@15.04. Did the same workaround to start mycroft...
But imho thats somehow really _extra_... ;-)

**Comment by ruedigerkupper** [comment]
Confirmed on hammerhead OTA-3 vivid. It is around since OTA-3. And I'm pretty sure there's already a bug report for it. Trying to look it up...

**Comment by ruedigerkupper** [comment]
There's a bug report on launchpad since 2008(!).
https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/201786
 Does Ubuntu Touch use gnome-keyring?

**Comment by Flohack74** [comment]
Ah so you created the key already locally?

**Comment by ruedigerkupper** [comment]
Quick update: I flashed Xenial/RC yesterday and the problem appears to be fixed there.

**Comment by Flohack74** [comment]
So we can close this? @Talkless please re-test with latest 16.04

**Comment by Talkless** [comment]
@Flohack74 Uhm, my device haven't received OTA-5 udpate yet.

**Comment by Flohack74** [comment]
That must have workded already in OTA4 ^^

**Comment by Talkless** [comment]
I had Stable channel selected, and did not received update.. as expected?

**Comment by Flohack74** [comment]
OTA-4 was not automatically rolled out. If you di dnot install it manually, you stayed on OTA-3 from 2017. OTA-5 should come to your device latest on Wed or Thu. Please check for it in system settings - updates :)

**Comment by Talkless** [comment]
I am checking almost every day, not udpate yet.

**Comment by Talkless** [comment]
Sorry for the delay. Got OTA-5, pubkey auth works fine. Thanks!
