### ISSUE TITLE
[xenial] LED does not work

### ISSUE THREAD

**Issue by Ingo-FP-Angel** [ubports/ubuntu-touch#477]
- Device: FP2
- Channel: 16.04
- Build: r166

### Steps to reproduce
Charge the phone. Or miss an incoming phone call.

### Expected behavior
The LED should indicate that the device is loading. Or that a call was missed.

### Actual behavior
LED stays dark

Looks similar to the 15.04 issue at https://github.com/ubports/ubuntu-touch/issues/48

**Comment by NeoTheThird** [comment]
This *is* #48.

**Comment by Ingo-FP-Angel** [comment]
Oops, sorry, I thought #48 was just about 15.04 where it was closed (as in fixed), while for 16.04 it looked like a regression to me.
