### ISSUE TITLE
[xenial] Ubuntu One account can't be configured without snapd

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#478]
- Device: hammerhead
- Channel: xenial/devel
- Build: r261

### Steps to reproduce
Go to System Settings -> Accounts -> Ubuntu One and enter your credentials.

### Expected behavior
The sign in process should complete successfully and then show me which accounts I have added.

### Actual behavior
A red error is displayed at the top, which states:
```
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.snapcraft.SnapdLoginService was not provided by any .service files
```
This leads me to believe that there's an unnecessary snapd dependency or it's just not installed/working.

**Comment by tsimonq2** [comment]
After manually installing the `snapd-login-service` package, I get an additional error:
```
GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._snapd_2derror_2dquark.Code9: Permission denied by Polkit
```
So at least I know now that system-settings needs a hard dep on `snapd-login-service`, which I can fix after the root cause is figured out.

**Comment by tsimonq2** [comment]
Seems [Launchpad bug 1739849](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1739849) is this same problem. I'll play around a bit more...

@mariogrip @Flohack74 @UniversalSuperBox ideas?

**Comment by Flohack74** [comment]
No ideas, sry. Maybe just try to get rid of the dependency.

**Comment by tomoqv** [comment]
I can confirm this error also on Meizu Pro 5 on Xenial r37, but also present in previous versions.

**Comment by mariogrip** [comment]
@mardy Any thoughts?

**Comment by mardy** [comment]
I don't know that much about the UbuntuOne account, but it's likely that we need to use an older version of libubuntuone-credentials. I need to double check this once I have some time.

**Comment by dobey** [comment]
Don't use trunk ubuntuone-credentials. It is not suitable for ubports. Really, we need to get rid of the ubuntuone account usage on ubports entirely, as at some point Canonical will stop supporting the old API that uses the fake oauth token, and will only support what's needed for snappy.

**Comment by mariogrip** [comment]
Should i downgrade it to the same version used on vivid? or should i revert https://code.launchpad.net/~dobey/ubuntuone-credentials/snapd-login/+merge/309697

**Comment by dobey** [comment]
Just reverting that change should do I think.

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/ubuntuone-credentials/commit/240cfdff007a985f5a7fed200bf7c057607c2ce0
