### ISSUE TITLE
Include kirigami QML library as an option to develop apps

### ISSUE THREAD

**Issue by JBBgameich** [ubports/ubuntu-touch#479]
### Description of the feature
The Kirigami QML Library is very useful for building cross-platform QML apps that also run on most desktop distributions, Plasma Mobile and Android, not only on Ubuntu Touch. One of it's primary aims is to support convergence, which fits to Ubuntu Touch very well. It would allow to share a few apps with Plasma Mobile, for example [Kaidan](https://github.com/kaidanim/kaidan).

### Illustrations
![image](https://user-images.githubusercontent.com/13609393/36643723-fced81e0-1a4f-11e8-8d33-8a66eb28cd34.png)
App Drawer
![image](https://user-images.githubusercontent.com/13609393/36643726-0356ac64-1a50-11e8-905b-2ded4f2b7a33.png)
An example page as displayed on a phone
![image](https://user-images.githubusercontent.com/13609393/36643734-1e385ce4-1a50-11e8-86e9-48c0cee765bf.png)
The same page displayed on the desktop (convergence!)

**Comment by NeoTheThird** [comment]
Postponed to OTA-5 due to #521.

**Comment by JBBgameich** [comment]
I worked on making the packages compile on Ubuntu Xenial. It should be possible to add them to the ci now. https://github.com/JBBgameich/extra-cmake-modules, https://github.com/JBBgameich/kirigami-packaging

Something like [this](https://raw.githubusercontent.com/JBBgameich/kirigami-packaging/e74c039f5356f8b6816cfb1f599cb7db5426e176/debian/patches/ubuntu-grid-unit.patch) (untested) patch will probably be needed for proper scaling.

**Comment by mardy** [comment]
How much disk space is needed by this? While I think it's worth having it, if the size needed to support kirigami applications is considerable, it might be better if the kirigami applications ship their dependencies in their click package (though we should still provide them in the repository, so in any case we should take the effort of packaging and adapting them for ubports).

**Comment by JBBgameich** [comment]
It should take less than a MB of space. A quick calculation resulted in about 130kb, maybe it's missing some dependencies though.

**Comment by Flohack74** [comment]
@JBBgameich we already got https://github.com/ubports/cmake-extras - should this be updated with what you need there? Clearly I cant add 2 packages with such similar names. Furthermore the link to your repo is broken :)

**Comment by Flohack74** [comment]
Ok I see... So I am supposed to fork it right? Otherwise its hard for our CI :)

**Comment by JBBgameich** [comment]
Yes, just forking my repos into the ubports org should work.

**Comment by Flohack74** [comment]
Now the fun starts... https://ci.ubports.com/blue/organizations/jenkins/extra-cmake-modules-packaging/detail/master/1/pipeline

**Comment by Flohack74** [comment]
This was resolved by https://github.com/ubports/extra-cmake-modules-packaging/commit/8e497a7133a4e85cee2e12f7cb58aeb3fd54f1e3 and https://github.com/ubports/kirigami-packaging/commit/76b72e1832d1bd802545fc45559a9f24efcec314

**Comment by Flohack74** [comment]
Well this was too easy: We got a lot of dependency problems now:
```
kirigami-gallery : Depends: kpackagelauncherqml (>= 5.49) but 5.18.0-0ubports1 is to be installed
 kpackagelauncherqml : Depends: libkf5declarative5
 libkf5declarative5 : Depends: qtbase-abi-5-9-0
Package qtbase-abi-5-9-0 is a virtual package provided by:
  libqt5core5a 5.9.1+dfsg+ubports [Not candidate version]
E: Package 'qtbase-abi-5-9-0' has no installation candidate
```
Please advise.

**Comment by JBBgameich** [comment]
This was already solved in the Telegram chat. For the record: only the gallery needs this dependencies, not the actual library that should be included in the image.

**Comment by JBBgameich** [comment]
@Flohack74 it seems like you only included the cpp part of kirigami, you also need the qml-module-org-kde-kirigami2

**Comment by Flohack74** [comment]
Yeah sorry my apologies. Thx for fixing...

**Comment by mardy** [comment]
I don't have complaints about this being included in the image (as long as the kirigami-gallery is not included): it looks like the QML module doesn't bring in any extra dependencies.

**Comment by JBBgameich** [comment]
The Kirigami Gallery shouldn't be installed as a debian package probably. I created a click package for interested developers: https://open-store.io/app/org.kde.kirigami2.gallery

**Comment by padraic7a** [comment]
Checked on Hammerhead running 16.04 build 2018-10-02
Checked on Frieza running 16.04 build 2018-10-01

Using ```sudo dpkg -l | grep -i kirigami ``` I can see that the following packages are installed:

- libf5kirigami2-5
- qml-module-org-ke-kirigami2

From the discussion above I believe that the fix is valid.
