### ISSUE TITLE
 LED has no function 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#48]
Ubuntu 15.04 r7
The RGB LED is off in every case. It would be great if it would indicate charging or notifications anyway but ideally in different colors.

Reported by https://launchpad.net/~sebastian-gallehr

**Comment by bastos77** [comment]
I observe when on charger after battery drain during this permanent rebooting the LED is showing function....

**Comment by Stefano0101** [comment]
Same here on Meizu Pro 5. No charging or notification led function at all.

**Comment by YougoCodes** [comment]
FP2 on 15.04 r24

LED does nothing with notifications, but is functional. when running this script:
https://github.com/nfsprodriver/uttweaks/blob/master/disco

the LED indeed displays a disco effect, rotating through all colors.
note: after ending the script with CTRL+Z the led remains on, and on the last displayed color. to shut off the LED, reboot.

**Comment by rubencarneiro** [comment]
Its a permissions problem

**Comment by Flohack74** [comment]
@rubencarneiro can you fix it like you did for hammerhead?

**Comment by rubencarneiro** [comment]
change init.qcom.factory.sh
Lines to 
chown -h 0666 system.system /sys/class/leds/red/brightness
    chown -h 0666 system.system /sys/class/leds/green/brightness
    chown -h 0666 system.system /sys/class/leds/blue/brightness
    chown -h 0666 system.system /sys/class/leds/red/device/grpfreq
    chown -h 0666 system.system /sys/class/leds/red/device/grppwm
    chown -h 0666 system.system /sys/class/leds/red/device/blink
    chown -h 0666 system.system /sys/class/leds/red/brightness
    chown -h 0666 system.system /sys/class/leds/green/brightness
    chown -h 0666 system.system /sys/class/leds/blue/brightness
    chown -h 0666 system.system /sys/class/leds/red/device/grpfreq
    chown -h 0666 system.system /sys/class/leds/red/device/grppwm
    chown -h 0666 system.system /sys/class/leds/red/device/blink

that should fix the problem

**Comment by Flohack74** [comment]
I add hammerhead label until we have rolled out the fix. Thx Ruben as always for quick response!

**Comment by vandys** [comment]
> LED does nothing with notifications, but is functional. when running this script:
> https://github.com/nfsprodriver/uttweaks/blob/master/disco

Is there source code somewhere for that binary?  TIA...

**Comment by nfsprodriver** [comment]
[disco.zip](https://github.com/ubports/ubports-touch/files/1192493/disco.zip)
The cpp is the source code.

**Comment by nfsprodriver** [comment]
Where is this file: init.qcom.factory.sh ?

**Comment by rubencarneiro** [comment]
https://github.com/ubports/android_device_fairphone_fp2/blob/ubp-5.1/rootdir/root/init.qcom.factory.sh

**Comment by rubencarneiro** [comment]
but i fixed leds on init.qcom.rc 

# Leds
    chmod 0666 /sys/class/timed_output/vibrator/enable
    chmod 0666 /sys/class/leds/keyboard-backlight/brightness
    chmod 0666 /sys/class/leds/lcd-backlight/brightness
    chmod 0666 /sys/class/leds/button-backlight/brightness
    chmod 0666 /sys/class/leds/jogball-backlight/brightness
    chmod 0666 /sys/class/leds/red/brightness
    chmod 0666 /sys/class/leds/green/brightness
    chmod 0666 /sys/class/leds/blue/brightness
    chmod 0666 /sys/class/leds/red/blink
    chmod 0666 /sys/class/leds/green/blink
    chmod 0666 /sys/class/leds/blue/blink
    chmod 0666 /sys/class/leds/led\:flash_torch/brightness

https://github.com/ubports/android_device_fairphone_fp2/blob/ubp-5.1/rootdir/root/init.qcom.rc

**Comment by bastos77** [comment]
IN OTA 2 the FP2 has function :-)
It is blinking green when notifications arrive. Thank you for this :-)

But that’s it. No charging information or other infos signalled. Would be great if charging also will be indicated in the future. As mentioned, when phone is off,charging is indicated with RGB (red if empty, green if full)

**Comment by Flohack74** [comment]
We will close this for the time being, new features for the led will come up later, but all 3 devices have now notification blinks working. Thats what was the original function provided by Canonical.

**Comment by Flohack74** [comment]
Please make a more specific new feature request.

**Comment by bastos77** [comment]
(FP2) LED feature request: Charging notification like already working when phone is switched off. GRB: From red when empty, over yellow when half charged to green when fully loaded.
Interesting is, that this behaviour can already be observed if the phone is shut down. So I see a chance to bridge this feature from ?bios? to the OS
