### ISSUE TITLE
"Request Desktop site" in the browser

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#480]
### Description of the feature
Chrome in Android/iOS supports this feature. You can tell the browser to request for the desktop version of the site. Whenever I connect my Nexus 5 to a monitor and switch to desktop mode, I still get mobile versions of sites like youtube and facebook. It would be good if sites will detect my phone as a desktop automatically when in desktop mode but it will be better to just have the "Request Desktop Site" in the menu.

**Comment by balcy** [comment]
similar to https://github.com/ubports/webbrowser-app/issues/9 ?
then it might be solved for 16.04

**Comment by mariogrip** [comment]
duplicate of https://github.com/ubports/webbrowser-app/issues/9

**Comment by mariogrip** [comment]
Woops, didn't see that this was in two different repos! but since this is fixed by https://github.com/ubports/webbrowser-app/pull/23 i added this to ota4
