### ISSUE TITLE
[xenial] hammerhead stuck in reboot loop after recent update

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#481]
- Device: hammerhead
- Channel: xenial/devel
- Build: r262

### Steps to reproduce
Either update the phone or reflash it.

### Expected behavior
The phone should boot into Ubuntu Touch.

### Actual behavior
It gets stuck in a reboot loop, only displaying the Google screen. Reflashing doesn't help.

**Comment by tsimonq2** [comment]
Ah ok, new to this :)

**Comment by ebeton-ro** [comment]
@tsimonq2 I think you can work arround this by: 
1. restart phone into recovery mode; 
2. Choose boot from recovery menu.

Hope this will help.

**Comment by zubozrout** [comment]
I can confirm the same on Meizu MX4 (arale). The last two releases (36 and 37) don't boot at all.

**Comment by ivoxavier** [comment]
On my Fairphone2 its happening the same rev. 169 and 170 don't boot

**Comment by NeoTheThird** [comment]
Fixed with https://github.com/ubports/unity-system-compositor/commit/96c78459ca4f81607008cfa86a8b238e0529971e
