### ISSUE TITLE
wrong casing of UBports in the recovery

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#486]
It's "UBports" or "ubports". "Ubports" is frowned upon and "UbPorts" is just ridiculous.

**Comment by NeoTheThird** [comment]
That didn't work. Any Ideas @mariogrip @UniversalSuperBox?

**Comment by UniversalSuperBox** [comment]
The majority of text in the recovery (that doesn't look terrible, font smoothing wasn't in our budget) is provided by images in the res-*/images folders. They will need to be re-rendered.

**Comment by UniversalSuperBox** [comment]
Specifically, `icon_header.png` needs to be re-rendered for each size with the correct casing.

**Comment by Flohack74** [comment]
Oh boy. Do we have the sources for that pictures. And BTW we need to fix FP2 recovery, the text / pictures is waaaay to small...

**Comment by UniversalSuperBox** [comment]
@mymike00 created this as a possible replacement for the current image.

![ubports-recovery](https://user-images.githubusercontent.com/21966173/40437524-2d0e6ef6-5e7b-11e8-983a-b0955e7bc419.png)

[UBports-recovery.svg.zip](https://github.com/ubports/ubuntu-touch/files/2031908/UBports-recovery.svg.zip)

**Comment by NeoTheThird** [comment]
https://github.com/ubports/android_bootable_recovery/pull/6
