### ISSUE TITLE
screen rotation does not work

### ISSUE THREAD

**Issue by timpppa** [ubports/ubuntu-touch#489]
- Device: Frieza 
- Channel: 16.04/devel
- Build: all 

### Steps to reproduce
None needed

### Expected behavior
When device is rotated from portrait to landscape or the other way around screen should rotate accordingly.

### Actual behavior
Screen stays in landscape orientation.

**Comment by NeoTheThird** [comment]
This should actually work now, are you sure you are running the latest version? Duplicate of #393.

**Comment by NeoTheThird** [comment]
You might have to re-flash from your PC, if you are running a very old version.
