### ISSUE TITLE
Installer hangs with Aquaris 4.5 in Fastboot...

### ISSUE THREAD

**Issue by skvamme** [ubports/ubuntu-touch#490]
Device: BQ Aquaris 4.5 Ubuntu with Canonical images
Installer: MAC version
### Steps to reproduce
Start Installer. Connect Phone. Installer identifies Phone correctly. Type Password. Phone goes to Fastboot. Installer hangs indefinitely. Phone stays in Fastboot until manually rebooted.

I tried to manually put the phone in fastboot mode, same result.

**Comment by NeoTheThird** [comment]
Duplicate of https://github.com/ubports/ubports-installer/issues/111. Thanks for reporting!
