### ISSUE TITLE
[xenial] telegram notifications come through though telegram does not function

### ISSUE THREAD

**Issue by userj** [ubports/ubuntu-touch#493]
### Illustrations

- Device: bacon
- Channel: 16.04/devel
- Build: r170

### Steps to reproduce

1. Presumably *try* to register telegram account (doesn't complete)
2. Wait for a message to come in

### Expected behavior

1. Telegram registers and starts working
2. Notifications come through normally

### Actual behavior

1. Telegram does not register the account, and asks for new account on every open
2. Telegram notifications sometimes come through the push nofications

**Comment by mariogrip** [comment]
Since this is not a backlog issue, i will remove it from there.

**Comment by Flohack74** [comment]
And by the way, there is now a working build for Telegram in 16.04 :)
