### ISSUE TITLE
[Oneplus One] UBports installer (ubports-installer.0.1.11-beta) for windows hangs at "please reboot into bootloader"

### ISSUE THREAD

**Issue by arronlacey** [ubports/ubuntu-touch#495]
Oneplus One A00001 can be detected both by adb and fastboot, however when rebooting into bootloader as directed by UBports installer, the installer does not detect the device, it just hangs waiting for it. I can see the authorised device using fastboot:

$ ./fastboot.exe devices
a3672b68        fastboot

Other info:

- USB debugging/dev options/MTP are all enabled.
- TMwin recovery in installed
- I have wiped the device (including internal storage)

any other suggestions?

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/ubports-installer#116
