### ISSUE TITLE
[xenial] multiple versions of apps installed 

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#496]
Bug Report

- Device: BQ M10 frieza
- OS: 16.04
- Channel: Devel
- Build: R41

### Steps to reproduce
Install updates up to those available on March 3rd, 2018

### Expected behavior
For just one copy of 'system' apps to be installed.

### Actual behavior
there are multiple versions of some apps installed. These are:

- calculator
- file manager
- gallery
- terminal

### Logfiles and additional information
(sorry, in a rush now, will try to add logs tomorrow)

**Comment by NeoTheThird** [comment]
We're doing some black-magic with shipping the system-apps as debs and installing clicks alongside them once an update comes along, that might be what's causing this. Where exactly do you see these duplicates? On the home screen? Are you on 16.04 or 15.04?

**Comment by padraic7a** [comment]
On 16.04. Can see them on the home screen. 
Can open both versions of terminal and calculator - for file manager and gallery only the newer version actually works and opens.

**Comment by padraic7a** [comment]
Happy to add logs or whatever you think may be useful.

**Comment by padraic7a** [comment]
Multiple versions present in the Apps screen
![screenshot20180303_230157052](https://user-images.githubusercontent.com/3010391/36945973-a1de31f6-1fad-11e8-8de6-f465d41c8fba.png)

Multiple versions open at once.
![screenshot20180303_232532275](https://user-images.githubusercontent.com/3010391/36945975-a46caf2e-1fad-11e8-91a1-cd1ba0291705.png)

**Comment by padraic7a** [comment]
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1778510/UTdmesg.txt)

**Comment by UniversalSuperBox** [comment]
I can confirm this on the FP2 after updating apps from the global "Updates" screen.

![screenshot20180305_185452519](https://user-images.githubusercontent.com/21966173/36993777-9a8261f8-2074-11e8-9b6f-9b1cbeb32e43.png)

**Comment by UniversalSuperBox** [comment]
The "Close and comment" button is dangerous.

**Comment by mariogrip** [comment]
I would assume this is because you already had a click package installed when you upgraded, Since we switched from click to deb on many of the packages. I will try to recreate it.

**Comment by mebruno** [comment]
Xenial r47 on M10 no issue anymore. Only one gallery app visible.

**Comment by mebruno** [comment]
Xenial r47 on M10 no issue anymore. Only one gallery app visible.

**Comment by dobey** [comment]
If there are debs for terminal/gallery/etc on 16.04 then yes this is the problem. We should probably remove the 15.04 frameworks on 16.04 images for now, so that those apps can't be installed from the store, to avoid duplicates. Or should just not ship them as debs, and let the clicks be semi-broken until things get stabilized.

**Comment by j2g2rp** [comment]
Looks like it's also related to clock app.
If I open through apps scope one clock app is open.

If i open through topbar another app clock app is open.

One of them looks like don't works propperly. They share the information and configurarion but one of them don't shows the hour in the widget or the date. The one with the version 3.9.559 looks the one that works correctly.

**Comment by Flohack74** [comment]
Both of my clock apps dont work in 16.04/FP2. Crash after some seconds, no interaction needed...

**Comment by tim-sueberkrueb** [comment]
@Flohack74 Same here on my 16.04 Nexus 5.

**Comment by hoh61** [comment]
I can confirm this on device frieza, 16.04, r86.

Especially by my camera app I got the following experience:
two apps were instalaled: one deb and one click package.
The deb app was running correctly, the click package was friezing the app due to access right errors (apparmor settings and implementation of trust-prompt pup-up). 
Once the "bad" application was started, this run command was cached, even the start of the deb app was failing and I couldn' clear this settings without a reboot.

**Comment by mariogrip** [comment]
We have now switched back to clicks on most of the apps

except for file-manager and terminal, there might be duplicates of these. There brings in some extra dependencies that's not already included, so that's why they stays deb for now.
