### ISSUE TITLE
[xenial] System settings crashes when trying to adjust keyboard opacity

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#499]
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
System Settings -> Language & Text

Try to drag the "Keyboard opacity" slider.

### Expected behavior
The slider should adjust and the keyboard opacity should then be changed.

### Actual behavior
The whole system settings app just crashes

**Comment by HendriXXX** [comment]
I can confirm this bug with N4. Xenial build r47.

**Comment by zubozrout** [comment]
And so can I with Meizu MX4 arale - r47.
