### ISSUE TITLE
Alarms in Clock should allow me to swipe down from the title bar after being maximized

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#503]
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
Open the clock app and swipe up on the Alarm icon.

### Expected behavior
After maximizing, I should be able to swipe down on any of the blank space on the title bar and Alarms should minimize. This makes it quick to take back down if I lift my finger up.

### Actual behavior
I have to tap the arrow for the menu to minimize.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/clock-app#68
