### ISSUE TITLE
Timer is extremely unclear on how to use

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#504]
- Device: hammerhead
- Channel: xenial/devel
- Build: r273

### Steps to reproduce
Go to the Timer section of the Clock app.

### Expected behavior
It should be clear on how to use the timer app. Specifically:
 - Dragging the hands on the clock move the time (which should be bigger fwiw for people with fat fingers like me).
 - A time (somewhere) should be displayed if the clock hasn't been touched quite yet.
 - Tapping the start button before setting a time should display a small error telling you that you don't have a time set so it can't do anything quite yet.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/clock-app#67
