### ISSUE TITLE
In Calendar, tapping on the default calendar to select makes that whole part of the menu disappear

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#505]
- Device: hammerhead
- Channel: xenial/devel
- Build: r279

### Steps to reproduce
Open the Calendar app and go to Settings. Try to set a default calendar other than the one you have selected.

### Actual behavior
The whole "Default calendar" part of the menu just goes away. Only after restarting the app does it show up again.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/calendar-app#56
