### ISSUE TITLE
Tapping on the space to the left of the checkmark in Calendar's settings should toggle the checkbox

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#506]
- Device: hammerhead
- Channel: xenial/devel
- Build: r279

### Steps to reproduce
Open the Calendar app and navigate to the settings. Try to check/uncheck any of the buttons.

### Expected behavior
You have to tap _right on the checkmark_ for it to be toggled.

### Actual behavior
I should be able to tap anywhere on that line and it should toggle.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/calendar-app#55
