### ISSUE TITLE
Numeric error in Calculator app

### ISSUE THREAD

**Issue by Nativeworld** [ubports/ubuntu-touch#508]
Device: Nexus5, BQ M10FHD, BQ E5
15.04 r61  rc

App: Calculator

In simple arithmetic steps (addition and subtraction) with decimal places the result sometimes is wrong, because there are decimal places like: "....,109999999999999..." instead of "....,11"
This bug is repeatable.
Last log:
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
could not open containers config file  "/home/phablet/.local/share/libertine/ContainersConfig.json"
qml: Page_QMLTYPE_17_QML_41(0x329b50)"Taschenrechner": In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.
[PERFORMANCE]: Last frame took 42 ms to render.

**Comment by NeoTheThird** [comment]
This is not a bug we can solve, it's related to the way decimal numbers are represented in a computer.

https://en.wikipedia.org/wiki/Double-precision_floating-point_format

**Comment by the-Mitu** [comment]
Still I believe most calculator applications don't *show* thay have such issues. For me it should be worked around by limiting the presition to 8, 10 or 12 (whatever is sufficient) fractional digits and rounded.

In most cases we do not need that many digits - reducing their number will at least hide the numerical errors from the user.
