### ISSUE TITLE
[xenial] Days of the week not fitting properly on datetime-indicator

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#510]
- Device: Fairphone2
- Channel: 16.04/devel
- Build: 187

### Expected behavior
Days of the week showing properly on European Portuguese

### Actual behavior
Missing Sunday, see attachment
![sem titulo](https://user-images.githubusercontent.com/16002474/37100629-5e25280a-221b-11e8-982c-940877fd0f80.png)

**Comment by NeoTheThird** [comment]
Maybe we could just roll back the portugese translation? @Flohack74

**Comment by Flohack74** [comment]
I dont think this is the issue, as I dont think there is a translation project for this indicator already.

**Comment by NeoTheThird** [comment]
Of course there is, it comes from the unity 8 component in xenial. If we just update our own indicator, it will get built into the image.

**Comment by dobey** [comment]
This looks more like the date format for day of week changed for some reason. I think these translations come straight from libc's date format code.

**Comment by mariogrip** [comment]
Can some check if this is fixed after https://github.com/ubports/systemd-packaging/commit/744063301a0a73501d8f62aa244f506c221edd8b but not sure if it have anything to do with this.

**Comment by mflotynski** [comment]
I'm running 16.04 on BQ M10 fhd (build description says it's version from 16th march 2018) and after changing to Portuguese I can see Sunday (Domingo)

![sunday](https://user-images.githubusercontent.com/3848216/37564499-964184fc-2a97-11e8-97ab-f62cb2327c6a.png)

**Comment by ivoxavier** [comment]
The problem still persist on my FP2. On the calendar app I can also see domingo, but there is no space between sabado and domingo. 

![screenshot20180322_111046065](https://user-images.githubusercontent.com/16002474/37767650-bec265da-2dc2-11e8-8e5f-5bfea4a9e127.png)

**Comment by dobey** [comment]
I've removed the dependency on Ubuntu.Components from the aformentioned test qml, and can verify the issue happens as well with upstream Qt build on Ubuntu 18.04.

I'm still not sure where Qt is actually pulling this result from, though it is apparently not from the system locale as `LC_TIME=pt_PT.UTF-8 date --date "Sun"` does give the correct short result.

**Comment by UniversalSuperBox** [comment]
This appears to be an issue in Qt since we've been able to reproduce it across versions and Linux ditributions. I've raised the bug here: https://bugreports.qt.io/browse/QTBUG-68021

**Comment by UniversalSuperBox** [comment]
Well, as noted in the last comment's linked report, this bug is about as upstream as upstreams go. The error is actually in [Unicode.org's CLDR](https://www.unicode.org/cldr/charts/33/summary/pt.html#1736 data) for the pt_PT locale. It looks like we will need to make a hack in both calendar-app and the calendar indicator if we want to fix this.

I'm not entirely sure that this is even an error in the CLDR data, it's been in the data since [release 28](https://www.unicode.org/cldr/charts/28/summary/pt.html#1705).

**Comment by UniversalSuperBox** [comment]
I see a couple possible options for fixing this bug:

1. Cut the string returned by the locale to three characters so it fits in the slot. This might get strange with non-ASCII languages. 
1. Use the "Narrow format" when possible, which gives a single character result in most languages for each day name. For example, `S M T W T F S` for the day names in en_US. We'd still need to fall back to the short format when the narrow format isn't available. It seems like the only way we'd be able to tell is to grab the narrow format, check if the string is empty, and then grab the short format instead. There's no look-ahead possibility.

**Comment by Flohack74** [comment]
3. Open an issue with unicode.org, if they got an issue tracker xD (or just write them by mail) - we need to find out about the reasoning behind this. Then, if we do such an exception, it should only be for the affected langauges. No default cutting of 3 letters for all languages, this is too dangerous.

**Comment by dobey** [comment]
@UniversalSuperBox RE: narrow format and falling back, my understanding of the Qt API here is that it will fall back to short if narrow is not available, so we shouldn't need to do anything extra in that case.

However, I still don't understand why this issue only appears in the Qt implementation. Does the libicu in Ubuntu 18.04 use an older CLDR where it's not an issue? If so, Qt is shipping it's own copy of the data, so even if the CLDR were fixed upstream, we'd still need a re-built qtbase with the fixed data, or a new release of 5.9.x with it. So this still seems like something Qt has to deal with, even if the bug is not "in" Qt itself.

**Comment by UniversalSuperBox** [comment]
@dobey you're right, Qt will fall back.

It looks like Qt does indeed include its own data in the build, according to https://wiki.qt.io/Locales#QLocale: "In this case, Qt refers to qlocale_data_p.h to determine how to format data. qlocale_data_p.h is generated from CLDR [...]."

I'm not sure why your copy of libicu is different, but it seems that Qt indeed has the correct behavior here. There is definitely [an override of the short day names for pt_PT](https://www.unicode.org/cldr/charts/33/summary/pt.html#1736) (furthest column to the right).

**Comment by UniversalSuperBox** [comment]
Looks like Unicode doesn't accept this as their bug either. https://unicode.org/cldr/trac/ticket/10859

**Comment by dobey** [comment]
maybe we should just remove pt_PT from locale support, and have only pt and pt_BR. I thought that was how it was supposed to work anyway.

**Comment by Flohack74** [comment]
There is a workaround now released, please test with tomorrow´s nightly build if it was successful.

**Comment by ivoxavier** [comment]
It worked! Thanks to all involved :)
