### ISSUE TITLE
[xenial] Missing auto-update option under Update Settings

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#511]
- Device: Fairphone 2
- Channel: 16.04/devel
- Build: 189

### Steps to reproduce
Open Update Settings

### Expected behavior
Option to configure the way we want the updates are handle

### Actual behavior
No option given like 15.04

![sem titulo](https://user-images.githubusercontent.com/16002474/37154344-99f16eea-22d7-11e8-8799-649416f12415.png)

**Comment by ivoxavier** [comment]
Still missing on r.201

**Comment by mariogrip** [comment]
Still not landed in the images. Will be the in next release
