### ISSUE TITLE
[Xenial] flaky race condition on startup

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#512]
Unity8 and USC seems to have a fight to be the first to startup. This result in unity8 crashes on bootup.

**Comment by PhoenixLandPirate** [comment]
We should try toprevent fighting like such in the ubports community, and project itself

**Comment by UniversalSuperBox** [comment]
Assuming this was the cause of rebooting on every other boot, I'm not able to reproduce this on a dirty FP2 r197. That's possibly due to having some userdata on the device, I'll have to test after a wipe.

**Comment by mariogrip** [comment]
I cannot reproduce it anymore. seems to got fixed by another package. Will close for now, please open again if this still exists!
