### ISSUE TITLE
[xenial] Camera-app causes system to reboot.

### ISSUE THREAD

**Issue by HendriXXX** [ubports/ubuntu-touch#514]
- Device: Nexus 4
- Channel: Xenial devel
- Build: r47

### Steps to reproduce
Start Camera app

### Expected behavior
Camera starts and you can take pics.

### Actual behavior
Camera startup causes system to reboot, every time.

### Logfiles and additional information
- Original camera-app (which comes with image) is .deb based. That one crashes and forces system to reboot in startup.
- I installed click version from openstore and it starts fine but crashes when taking picture, changing to front camera or video mode.

I got this from syslog.
https://paste.ubuntu.com/p/PKXwSXcJwz

**Comment by mebruno** [comment]
**Camera on Xenial r48 on bqm10 frieza is now working for the first time!**

**Comment by simoxxx** [comment]
i confirm this still on r50 on Nexus4

**Comment by UniversalSuperBox** [comment]
I've heard multiple people unable to reproduce this. Can you try to reproduce the issue again?

**Comment by HendriXXX** [comment]
It's still a problem in Nexus 4 with r69. Behaves just like in description..

**Comment by samuelig** [comment]
I can also reproduce it in my Nexus 4 with r69.

**Comment by mariogrip** [comment]
humm this one is a bit weird, i don't seem to be able to reproduce it myself. Will try a clean reflash on r69. 

Did camera work fine on vivid btw?

**Comment by dark-eye** [comment]
I suggest to try and check  with tagger or instagrph to see if it`s the camera API or some other weird behavior of the camera-app.

**Comment by vlladdrakk** [comment]
I am on 16.04 r77, camera is rebooting the phone for me too and tagger will just show a white screen and nothing else. I would love to help more if I can, what is the best way to get logs? I am pretty new to ubports.

**Comment by HendriXXX** [comment]
Wish I could help more with this. Still issue with latest dev. I cannot understand why everyone cant reproduce this? What is the difference? Is there different camera modules or what?
I tried to gather more logs. Logviewer gave me this..
http://paste.ubuntu.com/p/wFRWQ2FfFV/

**Comment by dobey** [comment]
I got the same crash on my Nexus 4 just now, but having trouble getting the log off of the device. I also tried Authenticator app after, and it is working just fine to use the camera. Tagger is I think only built against 15.04, so the white screen there is probably an issue with the app, not the camera.

**Comment by dobey** [comment]
[camera-crash.log](https://github.com/ubports/ubuntu-touch/files/2087241/camera-crash.log)

**Comment by mariogrip** [comment]
Can someone re-test this in the next devel rev, to see if https://github.com/ubports/libhybris/pull/5 had any effect on this issue?

**Comment by dobey** [comment]
It still reboots with latest image on nexus 4, here.

**Comment by HendriXXX** [comment]
Problem is still present with my N4, latest devel image..

**Comment by vlladdrakk** [comment]
Yep, still exists just tested it on 16.04 (2018-w25)

**Comment by Flohack74** [comment]
Please stop reporting that nothing has changes, about 10 people get a Github notification for each of them, telling us nothing new ;)

**Comment by bam80** [comment]
Any progress with it?

**Comment by dobey** [comment]
@bam80 Yes, it's been put on the backlog for OTA-5. :)

**Comment by Mappaschreck** [comment]
My (poor) workaround: Use the app Tagger and take screenshots.

**Comment by APokorny** [comment]
I just took todays 16.04 devel build and it still happens

**Comment by APokorny** [comment]
Ok There is a problem in our CI system the device image is from 09/2017 so the fix is not included in the current 16.04 devel device image.

**Comment by mariogrip** [comment]
New kernel pushed.
