### ISSUE TITLE
Character counter for SMS/MMS

### ISSUE THREAD

**Issue by buchnerh** [ubports/ubuntu-touch#519]
-------- FEATURE-REQUEST -------------------------------------------------------

### Description of the feature

It might be useful if there will be a counter of already typed characters in a SMS. It would be nice if the structure can be like this:

67/160(1)

--> 67 characters already used from the available 160 characters. The 1 in brackets mean, that this is the first SMS. So if you type more than 160 characters the counter may look like this:

34/160(2)

or like this:

194/320(2)

I don't know if there's a similar limitation for MMS because I don' use this, but if it exist, this counter would be useful for MMS too.

- Device: BQ Aquaris E4.5
- Channel: 15.04 stable

**Comment by Flohack74** [comment]
This issue was moved to ubports/messaging-app#25
