### ISSUE TITLE
 Keyboard does not show up when working with multiple windows

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#52]
When I open a second window in the browser, I don't have access to the keyboard until I close the previous window. A workaround is to open the keyboard in the search on the homescreen.

reported by https://launchpad.net/~auberge-tilleul.

**Comment by Flohack74** [comment]
Not reproducible here...

**Comment by lduboeuf** [comment]
sorry but still happens here on my BQ4.5 update#6 .

**Comment by lduboeuf** [comment]
as a work around, i bookmarked a search engine and use it ( keyboard appears with input forms)

**Comment by NeoTheThird** [comment]
@Flohack74 can you try again? Are there any logs that might be useful for @lduboeuf to attach?

**Comment by Flohack74** [comment]
Yes will do. @lduboeuf can you send a video? To be sure I do the same steps

**Comment by lduboeuf** [comment]
sorry for the proposed work around. i still need to kill other browser window before.. i will look at logs as soon as i can. step to reproduce: in top-right menu, click on "new window" then focus on addressbar, keyboard is not shown

**Comment by Flohack74** [comment]
Ok now we are talking. I never use this menu to open a new window, I swipe from the bottom for a new window, and there it works...

**Comment by lduboeuf** [comment]
yes, what you are doing is opening a new tab, but don't allow you to be in private mode.

**Comment by lduboeuf** [comment]
output from `.cache/upstart/application-legacy-webbrowser-app-.log` when starting webbrowser-app:

```shell
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
could not open containers config file  "/home/phablet/.local/share/libertine/ContainersConfig.json"

(process:15228): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:15228): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:15228): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:15228): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.
This plugin does not support raise()
OxideQQuickWebView: canGoForward is deprecated. Please use the API provided by OxideQQuickNavigationHistory instead
OxideQQuickWebView: canGoBack is deprecated. Please use the API provided by OxideQQuickNavigationHistory instead
Input device added: "mtk-kpd" "/dev/input/event0" QFlags(0x1)
Input device added: "ACCDET" "/dev/input/event1" QFlags(0x1)
Input device added: "hwmdata" "/dev/input/event2" QFlags()
Input device added: "m_mag_input" "/dev/input/event3" QFlags()
Input device added: "mtk-tpd" "/dev/input/event4" QFlags(0x1|0x8)
qml: Loaded 12 UA override(s) from file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Web/ua-overrides-mobile.js
[0606/141223:ERROR:layer_tree_host_impl.cc(2189)] Forcing zero-copy tile initialization as worker context is missing
[0606/141223:ERROR:oxide_compositor_gpu_shims.cc(258)] Error creating EGLImage: EGL_BAD_PARAMETER
getrlimit(RLIMIT_NOFILE) failed
```

and by launching new window

```shell
[0606/140632:ERROR:layer_tree_host_impl.cc(2189)] Forcing zero-copy tile initialization as worker context is missing
[0606/140632:ERROR:oxide_compositor_gpu_shims.cc(258)] Error creating EGLImage: EGL_BAD_PARAMETER
getrlimit(RLIMIT_NOFILE) failed
unity::action::ActionManager::ActionManager(QObject*):
	Could not export the main action group. Actions will not be available through D-Bus.
	Reason: Un objet est déjà exporté pour l'interface « org.gtk.Actions » en « /com/canonical/unity/actions »
[0606/140749:ERROR:layer_tree_host_impl.cc(2189)] Forcing zero-copy tile initialization as worker context is missing
[0606/140749:ERROR:oxide_compositor_gpu_shims.cc(258)] Error creating EGLImage: EGL_BAD_PARAMETER
```

**Comment by ChloeWolfieGirl** [comment]
We have another bug about the keyboard not working proper when you open a private window, is this exactly the same?

**Comment by NeoTheThird** [comment]
Good catch @ChloeWolfieGirl. You can reference issues using `#` and the number, or just typing the name to search and hitting enter when the right issue comes up, btw.

**Comment by NeoTheThird** [comment]
This seems to happen on all devices. When trying to reproduce, keep in mind to open a new *window*, not a new tab.

**Comment by the-Mitu** [comment]
I experience this on Pro 5:

1. Open a browser
2. Open new private window
3. Try to enter URL: no keyboard visible.
4. Switch to previous window (short swipe from right): keyboard is there
5. Switch back to private window again: keyboard is OK now.

In fact, I don't have to close the previous window - just switch it back and forth.

**Comment by Flohack74** [comment]
This happens now also in Dekko 2 test build. Shall we shift this issue to the keyboard component tracker?

**Comment by dpniel** [comment]
@Flohack74 I think this is more a window focus issue in qtubuntu than an issue in the keyboard component, so I don't think moving it there will help.

**Comment by simoxxx** [comment]
This bug was not present on the last canonical stable release.

**Comment by mihaelmilea** [comment]
It is working now for me on turbo, devel, r36. Thanks!!!

**Comment by Flohack74** [comment]
I LOVE IT! =)
