### ISSUE TITLE
Misleading error message on adding a nextcloud account "invalid host url"

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#524]
- Device: FP2
- Channel: 15.04/dev
- Build: r280

### Steps to reproduce
Try to add a nextcloud account via system settings and do one of the following three mistakes:

- Enter unknown user name
- Enter wrong password
- Try without an internet connection

### Expected behavior
I expect to see an error message that points to what I did wrong.

### Actual behavior
I see an error message claiming a "invalid host url", which is misleading, as I entered the url correctly.

### Logfiles and additional information
This is not a duplicate of #468.

**Comment by ruedigerkupper** [comment]
possibly a duplicate of #468?

**Comment by jonnius** [comment]
I'd like to try to fix this one if I knew how to build and debug changes. My plan is to use Unity8 on desktop for that. But it cant be installed at the moment. Is there any other way I could go, maybe on the phone itself?

**Comment by jonnius** [comment]
Fixed by ubports/account-plugins#15
