### ISSUE TITLE
Ended call keeps being shown as active

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#527]
- Device: FP2
- Channel: 16.04 dev
- Build: r203

### Steps to reproduce
I played around with connecting a bluetooth headset and switching to it during a call, trying to reproduce another issue. The call came from another phone and was ended by the other phone. I have not been able to reproduce this one, yet. But I remember that I have seen this issue before.

### Expected behavior
After the call ends, no active call is shown anymore.

### Actual behavior
An active call is shown in the green top bar. The counter keeps counting the call time. If you swipe down, one of the following two will happen (it chooses randomly):

- the phone app is shown normally as if there was no active call
- the phone app is shown with a red button to end the call, which does nothing. After a few seconds, a message is displayed, stating that the call failed. Then the app is shown normally.

In both cases, if you leave the phone app, the green top bar returns, showing the active call again. While having this issue, the gallery app won't start. If you call someone
 who declines the call, your phone app will show the call as active and you can end it pushing the red button. Once you leave the phone app, the green top bar returns again with the initial call time counter. The only way to stop the phantom call is to reboot the phone.

### Logfiles and additional information
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1822076/UTlogcat.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1822075/UTdmesg.txt)

**Comment by UniversalSuperBox** [comment]
Have you been able to reproduce this issue since?

**Comment by jonnius** [comment]
Nope. So probably not worth bothering.
