### ISSUE TITLE
[xenial] Sound does not go to bluetooth headset

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#528]
- Device: FP2
- Channel: 16.04 dev
- Build: r203

### Steps to reproduce
Connect a bluetooth headset. Try to play music or any other sound or simply change sound volume.

### Expected behavior
Sound output goes to bluetooth device. The sound volume overlay shows a bluetooth icon, when changing the sound volume level.

### Actual behavior
The phone connects to the bluetooth headset (the headset says "phone connected"). But there is no sound, neither in the bluetooth device, nor in the phone. The sound volume overlay does not show a bluetooth icon, when changing the sound volume level.

### Logfiles and additional information
On 15.04 this happened just sometimes and usually it was enough to reconnect the headset. On 16.04 this issue is permanent. Neither rebooting, nor repairing solves the issue.

[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1822094/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1822095/UTlogcat.txt)

**Comment by HendriXXX** [comment]
I can confirm this with my N4 and latest dev. It pairs ok, but sound doesn't go to bluetooth speaker, neither it doesn't show a bluetooth volume overlay.

**Comment by hoh61** [comment]
I can confirm this for my device:

    Device: BQ M10 FHD (frieza)
    Channel: 16.04 dev
    Build: r66

Here BT headset is detected and correctly shown but sound output is not switched.
option for high fidelity outout is not available.

**Comment by Flohack74** [comment]
Marked as regression for 16.04

**Comment by mariogrip** [comment]
Seems to work for me in the car bluetooth, not sure if thats the same. Will need to buy some cheep bluetooth headphones (I need one anyway :) ) to digg deeper into this.

**Comment by Flohack74** [comment]
Carkit and Heaphone are different things IMHO

**Comment by ivoxavier** [comment]
My FP2 connects to my radio car by bluetooh, but no sound either. 
Channel: 16.04/devel
version: 269

But with 15.04 works perfectly, already tested it

**Comment by UniversalSuperBox** [comment]
It appears that Bluetooth headsets are not being added as audio devices at all. In 15.04, the "Speakers" text on the sound indicator or volume control would change to "Bluetooth headphones" upon connection. You'd also be able to see the device from Pulse. It's possible that this will resolve itself when AudioFlingerGlue is working correctly. 

I can tell that Bluetooth is connecting, though. For one, my headset chirps on connection. Also, a new input device appears and responds to button presses on the headset.

**Comment by hoh61** [comment]
Confirmed, headset is used as audio-sink after connection (device frieza, r76)
