### ISSUE TITLE
[xenial] Microphone does not work

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#529]
- Device: FP2
- Channel: 16.04 dev
- Build: r203

### Steps to reproduce
Install [Sound recorder](https://open-store.io/app/audio-recorder.ubuntu-dawndiy). Try to record sound. 

### Expected behavior
Sound gets recorded.

### Actual behavior
No sound gets recorded. An error message is shown instead (see screenshot). Resetting the app settings does not help. As far as I can see, this affects all apps using the microphone.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1822122/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1822123/UTlogcat.txt)
[recorder.log](https://github.com/ubports/ubuntu-touch/files/1822124/recorder.log)
![screenshot20180317_221958053](https://user-images.githubusercontent.com/4456588/37560244-ffc9a0ac-2a34-11e8-8f77-e05179288d8a.png)

**Comment by mariogrip** [comment]
This might be an issue with the app not been compiled to 16.04, i will test it

**Comment by jonnius** [comment]
Maybe we have two issues here at the same time. Recording sound works on 15.04, but the sound file does not contain sound. The same happens when calling someone. The other person can only hear me, if I put them on the speaker or use a headset.

**Comment by hoh61** [comment]
Similar behaviour:


    Device: frieza
    Channel: 16.04 dev
    Build: r77

error message on screen: 
"Failed to build media capture pipeline. Reset of the settings will solve the problem"

Actually it doesn't.

**Comment by jonnius** [comment]
As marius mentioned, the app might need recompilation. Lets just wait for it and check again, then.

**Comment by hummlbach** [comment]
The same on the nexus 4 here.
I've recompiled the app (considering Marius' advices posted in the forum). But when the app tries to create subdirectories in ~/.cache, apparmor doesn't allow it. It gets a step further when creating stuff manually... What has to be done, to allow an app to write to .cache?

**Comment by jonnius** [comment]
I have built it for 16.04 (see [here](https://github.com/dawndiy/recorder/pull/6)): [audio-recorder.ubuntu-dawndiy_1.0.3_armhf.zip](https://github.com/ubports/ubuntu-touch/files/2078082/audio-recorder.ubuntu-dawndiy_1.0.3_armhf.zip) (the click is inside the zip. github does not accept click files)

I still get the error. This is what I find in the logs:
```
ERROR: "Not compatible codecs and container format."
qml: Not compatible codecs and container format.
ERROR: "Not compatible codecs and container format."
qml: Not compatible codecs and container format.
Could not create a media muxer element: ""
ERROR: "Failed to build media capture pipeline."
qml: Failed to build media capture pipeline.
```

**Comment by tomoqv** [comment]
I was going to test this using the camera and record a video, but following the latest OTA (r91) the camera won't load. New issue or just a temporary setback?

**Comment by mariogrip** [comment]
So there has been changes to the codecs and container types mime.type names, and since this apps hardcodes these names it fails. I set the defaults to the new names and it worked as it should.

New names
codec: "audio/x-vorbis" 
container: "audio/ogg" 

setting this as an "app bug"
