### ISSUE TITLE
Cannot enable developer mode

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#530]
- Device: FP2
- Channel: 16.04 dev
- Build: r206

### Steps to reproduce
Go to dev mode settings page. Enable switch. Close settings and reopen it.

### Expected behavior
Developer mode switch is still enabled and the device can be found via adb.

### Actual behavior
The Developer mode switch is disabled and the device cannot be found via adb.

### Logfiles and additional information
Can't access the device to grab logs...

**Comment by HendriXXX** [comment]
You could connect to it by ssh and try to grab logs there.
https://docs.ubports.com/en/latest/userguide/advanceduse/ssh.html

**Comment by jonnius** [comment]
This is not an issue anymore on r299
