### ISSUE TITLE
Hotspot activation / deactivation not consistent

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#532]
- Device: bacon
- Channel: 15.04/devel
- Build: 

### Steps to reproduce
Try to activate /deactivate hotspot from the indicators menu

### Expected behavior
Hotspot is activated /deactivated with a brief delay

### Actual behavior
Hotspot can only be activated /deactivated via the system settings menu, though sometimes deactivation works in the indicator it seems

**Comment by lfortanet** [comment]
Yes, confirmed .. Currently working according to comment.

**Comment by NeoTheThird** [comment]
I can confirm this on bacon on all channels, this issue has been around for a while.

**Comment by wagafo** [comment]
For me on 15.04/stable it activates, but the indicator is not shown and my devices can't see the wifi signal.

**Comment by stekalb** [comment]
For some unknown reason it worked today directly from the indicator menu, including the display of the hotspot icon. Usually it doesn't. (opo/devel/r281)

**Comment by p-conrad** [comment]
I'm experiencing the same issue on my OPO (r281). What I found out is that enabling the hotspot once, disabling it, then enabling it again will reliably turn it on even from the indicator menu. With some luck (~30%) even the icon shows up in the status bar.
This still doesn't influence the switch in the system settings menu. Those two appear to act completely independent from each other.

**Comment by UKPhil** [comment]
I have been having this issue for some time now. Sometimes it will take more that five attempts  to activate it via the systems settings and other time air have had to reboot the phone to get it to work. I do not think that I have ever been able to activate hotspot via notifications.

**Comment by UKPhil** [comment]
Forgot to add that I am on RC and using a OnePlus One.

**Comment by Flohack74** [comment]
Related to #281

**Comment by ichnaton777** [comment]
I use 16.04 on fairphone 2 and the hotspot just works as expected. Seems like this one is listed on FP2 as malfunction but is it really?

**Comment by Tob-end** [comment]
On my FP2 I dont have issues with the hotspot. It works fine.

**Comment by ExoPlant** [comment]
Hope this works completely in the end

**Comment by GermanAizek** [comment]
Wifi hotspot has already been tested and is working perfectly.

**Comment by GermanAizek** [comment]
@NeoTheThird

**Comment by darkdragon-001** [comment]
Has this been resolved for Google Pixel 3a as well? Then you should update the [devices page](https://devices.ubuntu-touch.io/device/sargo/).

**Comment by fredldotme** [comment]
> Has this been resolved for Google Pixel 3a as well? Then you should update the [devices page](https://devices.ubuntu-touch.io/device/sargo/).

It never was a problem on the P3a. The reason it shows as problematic because it's an non-deterministic problem on most devices and hence globally applied. But I can give my stamp of approval that it's not a problem for that device.

**Comment by capsia37** [comment]
The issues with the devices website not being able to override the globally set feature is now fixed. If hotspot works on your port, you can set `overrideGlobal` to `true`. The Pixel 3a was already set.

**Comment by RJDan** [comment]
> On my FP2 I dont have issues with the hotspot. It works fine.

I'm using FP2 with ubuntu touch since September 2021. I have had no issues with the hotspot. It even works better than hotspotting from my android phone.

**Comment by garro95** [comment]
I have the impression that after deactivating the hotspot, the battery drains faster then normal until the phone is rebooted. I thought this was tracking that issue
