### ISSUE TITLE
Multiple Notifications for the Calendar

### ISSUE THREAD

**Issue by Amolith** [ubports/ubuntu-touch#538]
I would love to see multiple notifications for the Calendar app in UT, like there is in the Google Calendar app. This is, perhaps, one of the features I'm missing most in UT as opposed to Android or iOS.

**Comment by hummlbach** [comment]
@Amolith I guess you want to be notified multiple times for an event, right? Can you please file this again in the calendars issue tracker, if you're still missing this?

**Comment by Amolith** [comment]
Moved the issue [here](https://github.com/ubports/calendar-app/issues/113)
