### ISSUE TITLE
Screening rotation doesn't work on frieza

### ISSUE THREAD

**Issue by riccardovidotto** [ubports/ubuntu-touch#539]
### Illustrations

- Device: Frieza
- Channel: Stable
- Build: 15.04

### Actual behavior 
  
Hi everybody, on my frieza lockscreen is always on landscape mode, while the rest of the system is on portrait mode and I can't change it. The rotation isn't locked and I tried the development channel, butvthe problem remains.

**Comment by hoh61** [comment]
Description of the feature
Illustrations

    Device: Frieza
    Channel: develop
    Build: 16.04 (r66)

Steps to reproduce
Expected behavior
Actual behavior
Lockscreen is always on landscape mode, Rotation is working smoothly.after unlocking.

**Comment by NeoTheThird** [comment]
It's intended that way, and the behavior is consistent across all devices: The lock-screen is always in the devices' default rotation.
