### ISSUE TITLE
[xenial] Cannot set Location On / Use GPS

### ISSUE THREAD

**Issue by mebruno** [ubports/ubuntu-touch#540]
Cannot set Location On / Using GPS

- Device: Frieza
- Channel: 16.04 
- Build: r56

### Steps to reproduce

System Settings / Security & Privacy / Location / Using GPS

### Expected behavior

Location must be On when set using GPS

### Actual behavior

Location stays Off

**Comment by lfortanet** [comment]
I can confirm it also Bacon device .

**Comment by tomoqv** [comment]
Same on Turbo.

**Comment by UniversalSuperBox** [comment]
I got access errors on my FP2, but it started working after wiping the device. I'm able to turn location off and on on both hammerhead and fp2 now, and both of them are able to get a location lock (though the FP2 takes considerably longer, as usual).

Is this problem of not being able to switch on location still happening? Does it start working after a factory reset?

**Comment by mebruno** [comment]
No, after factory reset still not working on bqm10fhd


Op Ma, 23 april, 2018 4:06 pm schreef Dalton Durst:

**Comment by NeoTheThird** [comment]
Duplicate of #582.
