### ISSUE TITLE
MAC Adress for every Bacon is the same

### ISSUE THREAD

**Issue by BlueKenny** [ubports/ubuntu-touch#541]
- Device: bacon
- Channel: all
- Build: all

### Steps to reproduce
Check wifi mac adress in settings

### Expected behavior
MAC adress should be taken from hardware and not fixed by software

### Actual behavior
On every bacon phone the wifi adress is B0:AA:33:88:88:88
This is the same for every Channel...
If multiple bacons are connected to the same network, all are connected but none works

**Comment by Flohack74** [comment]
What I found so far is the hint from the WLAN config file `WCNSS_qcom_cfg.ini `: 
```
# Assigned MAC Addresses - This will be used until NV items are in place

# Each byte of MAC address is represented in Hex format as XX

Intf0MacAddress=B0AA33888888
Intf1MacAddress=D4AA33888888
Intf2MacAddress=000AF58989FD

Intf3MacAddress=000AF58989FC
```
So we are looking for more knowledge about what are "NV items" and why they are not in place ;)

**Comment by einserpasch** [comment]
I have the same issue.
Could thus bug also be related to more general connection problems that i and other bacon users have?

**Comment by einserpasch** [comment]
Like stated here 
https://github.com/ubports/ubuntu-touch/issues/219

**Comment by Flohack74** [comment]
Maybe, who knows...

**Comment by BlueKenny** [comment]
I found this about NV items

https://forum.xda-developers.com/showthread.php?t=1804117

**Comment by BlueKenny** [comment]
Should it be possible to set the Mac Adreas randomly to 'fix' the problem for the moment ?

**Comment by Flohack74** [comment]
yes and no. I have currently no OPO build tree checked out to experiment with this, but I will do it soon probably. I would also need expertise from @mariogrip on that one...

**Comment by BlueKenny** [comment]
@flohack74 How is the status oft this bug ? Is someone working on it ?

**Comment by Flohack74** [comment]
No I am afraid no one has picked this up yet :(

**Comment by T-5dotEU** [comment]
If someone could tell me how to check out a build tree for the OPO i would gladly start hacking on ubuntu touch and especially this one.

**Comment by Flohack74** [comment]
Awesome! you will need:
- the usual android base tree: https://github.com/ubports/android/blob/ubp-5.1/default.xml
- the UBports local manifest entries: https://github.com/ubports/build-scripts/blob/master/devices.xml
Then you can use lunch to configure for the following target: "name": "bacon", "target": "cm_bacon-userdebug", "device_dir": "device/oneplus/bacon"

**Comment by Flohack74** [comment]
@T-5dotEU Any news on this?

**Comment by BlueKenny** [comment]
@Flohack74 
i have the same old problem on my 3 Bacon phones...

**Comment by Flohack74** [comment]
Yes I also got the wrong one again! It seems to be either a race condition on startup or idk...

**Comment by BlueKenny** [comment]
Is there a way to change the adress with the file "/android/system/etc/wifi/WCNSS_qcom_cfg.ini" ? Its read only (with read write file system mounted..)
Or is there another way to set another MAC adress ?
With "ifconfig" it dosnt work as the old one is take on each new connection

**Comment by Flohack74** [comment]
Oops closed already. That was not the idea ;)

**Comment by Flohack74** [comment]
OK guys here comes the test for all of you ;)
* Download this script: https://github.com/janimo/phablet-porting-scripts/blob/master/build/replace-android-system and make it executable (chmod 755)
* Download this special test android image **only for OPO!** from here: https://nc.ubports.com/s/r8s9qpAPYatH2yi => system.img
* Connect your phone and enable developer mode
* Execute `./replace-android-system system.img` in a shell of your choice
* After reboot: It might be that you have to delete and re-create your WiFi connections
* Tell me if you still see `B0AA888888` or a new, shiny Oneplus MAC starting with C0: ...

**Comment by Flohack74** [comment]
Done!

**Comment by wangke1993** [comment]
@Flohack74mogul，https://nc.ubports.com/s/r8s9qpAPYatH2yi ,404,down,Do you have a new address?

**Comment by Flohack74** [comment]
@wangke1993 No, sorry, that system image was only for testing the issue on the Oneplus One, the problem was fixed there, but I do not believe it can help with the issue on this other device.
