### ISSUE TITLE
down scroll rejected in vertical orientation 16.04 devel

### ISSUE THREAD

**Issue by j2g2rp** [ubports/ubuntu-touch#542]
- Device: Bq M10 FHD ubuntu edition
- Channel: devel
- Build: r56

### Steps to reproduce
scroll rejected in vertical orientation.

### Expected behavior
You should can displace to up or down through apps scope.

### Actual behavior
In apps scope when you released the finger or the butom of the mouse the screen returns where it was before when you are in a vertical orientation.
As i described it happens when you are in touch mode or in desktop mode.

**Comment by UniversalSuperBox** [comment]
Hello @j2g2rp, sorry for the wait on this one.

Judging by the time this bug was opened, I believe the issue you were experienced has been fixed. Are you able to reproduce this issue any more?

**Comment by j2g2rp** [comment]
Hi @UniversalSuperBox  you are right. I can't reproduce it.
Thanks!

**Comment by UniversalSuperBox** [comment]
No problem, thanks for taking another look.
