### ISSUE TITLE
Fairphone not detected

### ISSUE THREAD

**Issue by stemy2** [ubports/ubuntu-touch#543]
Hello,

I try to flash my fairphone 2, but the install app doesn't detect it. The adb driver is installed, developer mode is enabled, but this is like if my phone was not connected. Same problem with the adb app i downloaded with platform-tools.I'm on Windows.

What step have i missed ?

Thanks.

**Comment by helguson** [comment]
You may have missed to make `adb` recognize your FP2.
I tried today to use `adb` on my computer with Ubuntu 16.04LTS to connect to my FP2 with UbuntuTouch 16.04 rc over usb. `adb` was also not able to recognize my FP2. After adding the hardware code for FP2 `0x2ae5` to `adb_usb.ini` file - as proprosed in [the docs](https://docs.ubports.com/en/latest/userguide/advanceduse/adb.html#add-hardware-ids) - `adb` was able to recognize it.
