### ISSUE TITLE
Camera zoom not working on OPO

### ISSUE THREAD

**Issue by wagafo** [ubports/ubuntu-touch#548]
### Illustrations

- Device: OPO 
- Channel: 15.04/devel
- Build: 281

### Steps to reproduce

Open the camera application, try to zoom the image out

### Expected behavior

The camera should zoom out

### Actual behavior

The camera does not zoom out

**Comment by Berlinuxer** [comment]
same with mine OPO.
Possibly same error like flashlight-problem?

**Comment by Flohack74** [comment]
Duplicate of #355
