### ISSUE TITLE
can't recognized to be reflash it with ubuntu touch system already installed (BQ M10 HD not FHD!)

### ISSUE THREAD

**Issue by 243750496** [ubports/ubuntu-touch#549]
first I downloaded Universal ADB driver but it still show up the page: ADB drivers needed
second I choose continue then it still no recognize it 
then I choose select device manually 
then boot into bootloader but still can't get start , here's image of all steps : 
![1](https://user-images.githubusercontent.com/6311930/38307941-0cd35d58-3848-11e8-8b62-041d6a60abbd.png)
![2](https://user-images.githubusercontent.com/6311930/38307942-0d399d0c-3848-11e8-9c72-4c360c1ab3d4.png)
![3](https://user-images.githubusercontent.com/6311930/38307944-0dafaa2e-3848-11e8-9790-3c45fc949cf4.png)
![5](https://user-images.githubusercontent.com/6311930/38307946-0e08b40c-3848-11e8-8478-ec1177742e87.png)
![6](https://user-images.githubusercontent.com/6311930/38307947-0e6e6ea0-3848-11e8-9bcd-b99a7a68f0da.png)

**Comment by UniversalSuperBox** [comment]
Hello @243750496,

Sorry about the long wait. I hope you were able to get help installing Ubuntu Touch on your device. If not, you can find links to resources and support at https://docs.ubports.com/en/latest/userguide/install.html.
