### ISSUE TITLE
Invisible keyboard

### ISSUE THREAD

**Issue by greskom** [ubports/ubuntu-touch#552]
- Device: BQ Aquaris E4.5
- Channel: Stable
- Build: OTA-3

### Steps to reproduce
Try to type SMS or contact name or any other activity where keyboard should be present.

### Expected behavior
Keyboard appears and is visible.

### Actual behavior
Keyboard randomly disappears. It is functional, but keys are invisible (blind). If you know where to find the keys you can type. Best workaround is to remember the position of the shift key. By pressing it keyboard appears, but sometimes disappears again. After reboot it works normally for longer time. When the issue triggers first time, then it is reproduced very often, if not always, until next reboot.

**Comment by Flohack74** [comment]
Is this still an issue?

**Comment by mgresko8** [comment]
Yes, sure it is.

2018-06-29 19:23 GMT+02:00, Florian Leeber <notifications@github.com>:

**Comment by Flohack74** [comment]
Hmm as this is very old, please re-test this with the xenial release. I got an E 4.5 here with my GF and she never complained about that, so I must say its strange. But we wont fix it on 15.04 anymore, if it is really an issue. If you can test the 16.04 rc it would be great.

**Comment by mgresko8** [comment]
Hello,

16.04 rc is available for BQ Aquaris E4.5? And so will be available
the final release? Is the rc stable enough? I use it as my primary
phone. Is it possible to upgrade or shoould I reimage?

Thanks.

Marek


2018-07-08 9:05 GMT+02:00, Florian Leeber <notifications@github.com>:

**Comment by mgresko8** [comment]
Great news, there were rumours 16.04 version will not be supported on
32-bit platforms. When is the stable over the OTA expected? I am quite
afraid installing rc, since this is my primary phone.

Thanks.

Marek


2018-07-10 14:27 GMT+02:00, Florian Leeber <notifications@github.com>:

**Comment by Flohack74** [comment]
The rumors had nothing to do with the bitness, we do not have a single phone right now that is arm64, all are just 32bits.

It was about the problems of too old kernels, but we decided to remove systemd and restore upstart, and by this change all phones will be supported. Well for now. We will see in the future when there is the right time to retire old hardware,

The stable will take another 2 weeks or so, I think. But dont take my full word for this, we still face some nasty bugs where we do not know exactly how long it will take.

**Comment by mgresko8** [comment]
Sure I upgrade to stable 16.04 when it is available over OTA. I hope
there will be no bugs affecting primary phone functions. Making phone
calls and SMS messages are essential for me.

Marek


2018-07-10 21:49 GMT+02:00, Florian Leeber <notifications@github.com>:

**Comment by Danfro** [comment]
Related (or even duplicate?) to #915 .

**Comment by jonnius** [comment]
So you tested this on xenial?

**Comment by mgresko8** [comment]
Hello,

yes, seems fixed.

Thanks

Marek


2018-12-19 13:42 GMT+01:00, jonnius <notifications@github.com>:

**Comment by Danfro** [comment]
If it is fixed please close the issue.
One more done! :-)

**Comment by mgresko8** [comment]
Hello,

this issue reappeared in OTA-8.

Marek

**Comment by mgresko8** [comment]
Hello,

issue reappeared after upgrade to OTA-8. Somebody going look at it?

Thanks

Marek


2018-12-19 17:31 GMT+01:00, Danfro <notifications@github.com>:

**Comment by lduboeuf** [comment]
What is the status of this issue, still there @greskom ?

**Comment by greskom** [comment]
Hello,

I use the BQ phone very rarely now. I just tested and it was not present. I do not know whether it is fixed or only randomly appears. As I read backwards the original issue was random.

Marek

**Comment by lduboeuf** [comment]
ok, so i'm closing it for now ;-)
