### ISSUE TITLE
No refresh option on Browser

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubuntu-touch#554]
There is no refresh iption on the browser app. If you want to refresh a page you have to either click in the address bar and then click return or leave the tab page and then return. There is no easy option to refresh the page like a reload bottom.

**Comment by arubislander** [comment]
Is this on the browser app running under 16.04? Because the refresh button on the browser app in 15.04 is in the address bar where the favicon normally is. It only appears after you tap on the address bar.

**Comment by dpniel** [comment]
The refresh option is in the URL bar. You have to tap on the bar to see the icon on the left hand side

**Comment by UKPhil** [comment]
Yes it is there, but why have two clicks when if the refresh button was moved to be visible without tapping on the address bar, there would only be one click. Most other browsers have basic functionality like this always on view and people may not thing of tapping the bar to bring up the refresh option. If you are tapping the bar, it is easy enough to click return rather than refresh.

**Comment by UniversalSuperBox** [comment]
A very similar issue has been filed as https://github.com/ubports/morph-browser/issues/169. To keep the discussion somewhat local, I'll close this bug in favor of that one.
