### ISSUE TITLE
Nexus 6

### ISSUE THREAD

**Issue by hussaini1** [ubports/ubuntu-touch#555]
1 year complete
When Nexus 6 get Ubuntu touch .

Please dev release it for shamu

**Comment by UniversalSuperBox** [comment]
Hello @hussaini1, sorry about the wait.

Please see [our porting documentation](https://docs.ubports.com/en/latest/porting/introduction.html) for information on bringing Ubuntu Touch to a new device. Also check https://github.com/halium/projectmanagement for information related to a specific device's status.
