### ISSUE TITLE
Initializing the Mic from any application results in kernel panic and reboot on bacon-Oneplus One

### ISSUE THREAD

**Issue by AIIX** [ubports/ubuntu-touch#557]
Bug: Initializing the Microphone from any application results in kernel panic and reboot on bacon-Oneplus One 

- Device: OnePlus-One Bacon
- Channel: 16.04/devel
- Build: ubuntu-phablet 3.4.0-Sultan-CAF

### Steps to reproduce

[1]
- Build portaudio: http://www.portaudio.com/
- Compile and run examples 

[2]
- Compile and build: https://github.com/Kitt-AI/snowboy
- Run examples
 
### Actual behavior
Kernel panic and reboot

### Logfiles and additional information
[onepluskernelpanic.txt](https://github.com/ubports/ubuntu-touch/files/1906284/onepluskernelpanic.txt)

**Comment by UniversalSuperBox** [comment]
Hello @AIIX,

I'm unable to reproduce this issue on my Oneplus One with Ubuntu Touch applications. To test, I downloaded [Recorder](https://open-store.io/app/audio-recorder.luksus) from the store and recorded some audio. It worked correctly.

Please let me know if you feel this closure was in error.
