### ISSUE TITLE
Can not send or receive calls, sms, mms (randomly)

### ISSUE THREAD

**Issue by zacardec** [ubports/ubuntu-touch#559]
- Device:MEIZU MX4 (MEIZU ARALE)
Ubuntu(r3) 15.04-armhf(20171218)
- Channel: Stable
- Build:

First, scuse for my poor english .
The application telephone freeze randomly, the screen remains illuminate when I wear the phone to the ear, I no longer receive sms, mms, the GSM network icon remains active simulating a good reception. 

logfile:

[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1910131/UTlogcat.txt)
[dmesg.txt](https://github.com/ubports/ubuntu-touch/files/1910137/dmesg.txt)

This bug already existed with ubuntutouch. This bug is very disabling because I randomly no longer receive calls and sms, and requires a restart of the system. My bad English level did not allow me to find a similar bug on the documentation.

**Comment by zacardec** [comment]
Do you need a particular log that I could keep for the next bug as described? If so, can you tell me the path of the log file to provide?

**Comment by lduboeuf** [comment]
@zacardec is this issue still there ?

**Comment by zacardec** [comment]
Sorry but i don't know.... I left ubports, but i'll install it again as soon as possible to try again.

**Comment by lduboeuf** [comment]
ok, time to come back then, things are moving fast :). I close it for now but can be reopened if needed.
