### ISSUE TITLE
contacts import only from google

### ISSUE THREAD

**Issue by ctheuring** [ubports/ubuntu-touch#562]
- Device: BQ Aquaris M10 FHD
- Channel: 16.04 devel
- Build: r61
### Steps to reproduce
app contacts
### Expected behavior
import vcards from SD-card
### Actual behavior
only possibility to import from google or SIM-card (here: is inactive because this is a tablet without a SIM-Card-Slot)

**Comment by hummlbach** [comment]
Unless you have more specific needs, this is already covered by https://github.com/ubports/address-book-app/issues/3.
