### ISSUE TITLE
Fairphone 2, Stereo Sound goes out in wrong direction

### ISSUE THREAD

**Issue by blaubaer01** [ubports/ubuntu-touch#563]
When using a headset, the left sound goes right, right sound goes left.

**Comment by blaubaer01** [comment]
Left sound goes right, right sound goes left

**Comment by blaubaer01** [comment]
By using headset

**Comment by V0ssi** [comment]
I can confirm this bug. I tested it on my FP2 (15.04 r3) with different youtube videos (e.g. https://www.youtube.com/watch?v=hTvJoYnpeRQ). I tried it with the youtube app and the browser app.

**Comment by blaubaer01** [comment]
Still the same issue with 16.04 stable.

**Comment by blaubaer01** [comment]
I confirm, it runs perfect after modification.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed.

On standart stereo headphones (with cord, jack and labeled left/right speakers) the [above mentioned youtube video](https://www.youtube.com/watch?v=hTvJoYnpeRQ) produces correct stereo sound.
