### ISSUE TITLE
Ubuntu touch 15.04 stable in dual boot with android dont see android files

### ISSUE THREAD

**Issue by Remix65** [ubports/ubuntu-touch#565]
Good afternoon i have ubuntu touch 15.04 stable in dual boot with android 7 on my one plus one and then i open file manager in ubuntu touch it doesn t see android files.may help me ?i have to mount android from terminal command ?thanks

**Comment by Flohack74** [comment]
Hello, I am afraid this will not work, as the data partition cannot be mounted in UT.

**Comment by UniversalSuperBox** [comment]
As posted on the forum and here, MultiROM will not provide you the same files. We also do not support MultiROM officially, so bugs should be filed on the relevant projects to make that happen.
