### ISSUE TITLE
Speed dial

### ISSUE THREAD

**Issue by Amolith** [ubports/ubuntu-touch#566]
### Description of the feature
I'd love to see a speed dial feature! Maybe users could open the phone app and swipe from the right to see cards of the contacts most called.

**Comment by UniversalSuperBox** [comment]
The only allowable gesture point in Ubuntu Touch is from the bottom of the screen, and that point is already used in [dialer-app](https://github.com/ubports/dialer-app). You might be able to add a speed dial tab in that pull-up menu. Either way, a good place to file this bug would be on the dialer itself.
