### ISSUE TITLE
[xenial] Some icons and Animation Circle are not align and fitting properly

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#568]
- Device: Fairphone 2
- Channel: 16.04/devel
- Build: 251

### Actual behavior
On update manager the animation circle is bigger than it should be. 

On settings app, the reset icon is not aligned with the others.

![photo_2018-04-24_12-15-37](https://user-images.githubusercontent.com/16002474/39183823-3aed08a8-47b9-11e8-9ddf-ee4f8bb4ebd4.jpg)
![photo_2018-04-24_12-15-39](https://user-images.githubusercontent.com/16002474/39183824-3b203a52-47b9-11e8-8a8b-22747b98e4b2.jpg)

**Comment by PhoenixLandPirate** [comment]
I don't believe the reset icon is meant to be the same size as the other icons, the updater manager certainly has a problem with how its displaying information, the box for the updater should be larger, and the spinning icon should be a bit smaller.

**Comment by Daniel20000522** [comment]
Confirmed on Nexus 4 (Ubports 16.04 r67).

**Comment by mariogrip** [comment]
These two commits fixes this:
- https://github.com/ubports/ubuntu-ui-toolkit/commit/5c803c0709311c6685380c75bba0ac1e74517e0a
- https://github.com/ubports/system-settings/commit/f8db533f8f22a05eb75de99b8a3718271200833b

**Comment by NeoTheThird** [comment]
Confirmed fixed.
