### ISSUE TITLE
OPO overheating when on battery which drains, normal if plugged in

### ISSUE THREAD

**Issue by wagafo** [ubports/ubuntu-touch#569]
### Description of the feature

My OPO with 15.04 Devel overheats when unplugged, and the battery drains quite fast (it lasts only half a day). Sometimes it does not overheat, I can' tell when, and the battery lasts much more.

If I plug the phone it never overheats and it charges quite fast.

### Illustrations

- Device: OPO
- Channel: 15.04 Devel
- Build: r281

### Steps to reproduce

Have the phone unplugged

### Expected behavior

Normal temperature and battery should last at least one day.

### Actual behavior

The phone overheats and the battery drains.

**Comment by lduboeuf** [comment]
@wagafo are you still concerned by that bug ?

**Comment by wagafo** [comment]
Thanks, I'm using only Nexus 5 with UT right now, no OPO, so we close.
