### ISSUE TITLE
Battery level stuck at 100%

### ISSUE THREAD

**Issue by frgigr** [ubports/ubuntu-touch#571]
### Description of the feature
Battery level not working properly in certain circumstances

### Illustrations

- Device: krillin
- Build: Canonical OTA-15

### Introduction
Feel free to assign a lower priority to this issue!
A small introduction to highlight some (hoping useful) infos before describing the issue. I started experiencing the issue after a thunderstorm: despite my mobile being in my pocket, some drops of water got into the the loudspeaker holes, damaging the left one (and probably the microUSB connector since the device is no longer seen when connected with USB cable, although the battery charge works; that's why I'm stuck with Canonical image. For transfer files I rely on ssh and adb over Wifi)
Before that day, everything worked properly. 

### Steps to reproduce
Simply charge the phone and turn it on

### Observed behaviour
The problem is the following: if I turn the phone on while being connected to a generic power supply (PC or socket) and then detach it, the battery level drops as expected
Otherwise, if I turn it on after detaching it from the power supply, the battery level is stuck at 100%, suddenly dropping when the battery is about to die

### Logfiles and additional information
I attached the /var/log/repowerd.log files in both cases. It seems to be related to battery management system which is not initialized in the right way in absence of an external power supply
[repowerd_good.log](https://github.com/ubports/ubuntu-touch/files/1950591/repowerd_good.log)
[repowerd_bad.log](https://github.com/ubports/ubuntu-touch/files/1950592/repowerd_bad.log)
Is there a way to initialize/reset it manually? Thanks in advance for any kind of support!

**Comment by jonnius** [comment]
Maybe you should switch to the UBports image and try again. This repo is not meant for the unmaintained Canonical image.

**Comment by Flohack74** [comment]
I agree, we are not able to helpp you if you do not switch to our image. See instructions here: https://github.com/ubports/ubports-installer
