### ISSUE TITLE
OpenStore is empty or unsearchable

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#572]
- Device: Nexus 5 (hammerhead)
- Channel: devel
- Build: 16.04 (r351)

### Steps to reproduce
Open the OpenStore app and view any tab.

### Expected behavior
The OpenStore shows me all the glorious apps available for Ubuntu Touch, such as the ones I downloaded on my Nexus 7 (but on the stable channel).

### Actual behavior
The Discover tab is empty. Until yesterday, I could at least see the app categories but now that's empty too. Entering any search query yields no results. I've tried searching for apps that I've already installed via the OpenStore on the stable channel (Twitter, GitHub) but still nothing. Under "My Apps" it says I have no apps from the OpenStore installed, but yesterday it offered to update OpenStore itself. That update was the first thing I did, so I can't confirm that the update is what caused this.

### Logfiles and additional information
None so far. Is there a place where I can get OpenStore logs?

**Comment by Arc676** [comment]
Ah oops. Yes, the OpenStore offered to update itself so I did. Good to know.

Is there a way to revert to the previous version, perhaps via `apt`? Or do I have to re-flash?

**Comment by Flohack74** [comment]
TBH I need to take a look. Somewhere there should be a download for this possible ;)

**Comment by Arc676** [comment]
It's worth noting that updating Ubuntu Touch to the new `devel` build also reverted the OpenStore to its previous state, so this is no longer a critical problem for me personally. It's still offering to update the OpenStore though.

In any case, for future reference, it might be worth having a post somewhere indicating how to revert an app in case something like this happens.
