### ISSUE TITLE
[xenial] Some apps not launching from main scope if already open

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#573]
- Device: Nexus 5 (hammerhead)
- Channel: devel
- Build: 16.04 (r351)

### Steps to reproduce
Open any of the following standard, preinstalled apps:
- Clock
- Terminal
- File Manager
- Calculator

Return to the main Apps scope
Tap on the same app again

### Expected behavior
The app should reopen.

### Actual behavior
No response. If I close the app from the launcher and tap on it again in the Apps scope, it reopens.

### Logfiles and additional information
None so far. Where should I look?

**Comment by UniversalSuperBox** [comment]
This is very likely related to https://github.com/ubports/ubuntu-touch/issues/496. We need to stop shipping the core apps as debs in the base image, make them clicks instead.

**Comment by Flohack74** [comment]
I agree. It would also benefit the fact that people would get outdated core apps preinstalled, and then have to upgrade them. The clicks on Openstore will always be recent, and the image builder can pull them inside the rootfs as before.

**Comment by mariogrip** [comment]
We have now switched back to clicks on most of the apps

except for file-manager and terminal, there might be duplicates of these. They brings in some extra dependencies that's not already included, so that's why they stays deb for now.
