### ISSUE TITLE
[xenial] Closing a single browser window crashes app

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#574]
- Device: Nexus 5 (hammerhead)
- Channel: devel
- Build: 16.04 (r351)

### Steps to reproduce
Open the Browser app and use the menu button at the top right to open some new windows. Swipe left from the right edge of the screen to open the multitasking view. Swipe up or down on any browser window to close it.

### Expected behavior
The swiped window is closed.

### Actual behavior
The Browser app crashes, all the open browser windows disappear from the multitasking view, and the window is not closed. If the Browser app is reopened, the same number of windows is reopened. The browser state persists across reboots, so the number of browser windows cannot be decreased.

### Logfiles and additional information
![Multitasking view](https://user-images.githubusercontent.com/30745465/39463935-74d7d82e-4d4d-11e8-9030-faf8be7dfeac.png)

**Comment by Arc676** [comment]
FYI still happens on latest build (r357).

**Comment by Flohack74** [comment]
Also on the FP2 it happens that after the crash the phone reboots from time to time, mostly when there is another webapp container running...

**Comment by Flohack74** [comment]
@Arc676 A workaround for closing the windows: Go to the browser settings and disable "Restore previous state" once.

**Comment by NeoTheThird** [comment]
@mariogrip Please upgrade to the latest point release of qt 5.9

**Comment by NeoTheThird** [comment]
We won't fix this in OTA-4, since we will be moving off of oxide (our own packaged version of chrome) to QtWebEngine (from upstream). See #653. An experimental browser based on that can already be installed [from the OpenStore](https://uappexplorer.com/app/com.ubports.browserng), and the [QtWebEngine](https://wiki.qt.io/QtWebEngine) library can be used in apps on xenial.

For reference and to avoid duplicate reports, we'll leave this issue open with the `wontfix` label.

**Comment by mariogrip** [comment]
Closing since we are tracking QtWebEngine impl here https://github.com/ubports/ubuntu-touch/issues/653

**Comment by lduboeuf** [comment]
still happen today on devel. As a workaround i disabled "restore previous session" in settings

**Comment by Arc676** [comment]
From the blog post this seems to be fixed in OTA7. I haven’t tested it yet, but it may be worth relabeling the issue for proper filing.
