### ISSUE TITLE
Ubuntu touch no mount on PC with Linux mint

### ISSUE THREAD

**Issue by Remix65** [ubports/ubuntu-touch#576]
ubuntu touch 15.04 no mount on PC with Linux mint...

**Comment by UniversalSuperBox** [comment]
Hi @Remix65,

We're going to need more of the information that's mentioned in [our documentation](https://docs.ubports.com/en/latest/contribute/bugreporting.html#making-the-bug-report) as well as in the comments that you deleted while filing this bug report.
