### ISSUE TITLE
Cant Change default call forwarding settings

### ISSUE THREAD

**Issue by ManyHatsOfLinux** [ubports/ubuntu-touch#577]
- Device: Nexus 5
- Channel: Development
- Build: Ubuntu15.04 (r285) armhg (20171221)

### Steps to reproduce
 System Settings > Phone > Call forwarding | [[ change anything you want here. ]]
### Expected behavior
configuration changes persist after leaving the menu
### Actual behavior
they do not. 

Is someone getting my phone calls?

**Comment by ManyHatsOfLinux** [comment]
After looking the number up, i think its just the voicemail number att uses.

**Comment by UniversalSuperBox** [comment]
So is this still an issue with Ubuntu Touch, or do you think that the forward is from AT&T?

**Comment by ruedigerkupper** [comment]
Confirmed on hammerhead OTA-3 vivid.
I  ended up calling the phone codes from the dialer app to change call forwarding. It works, but is not reflected in system settings.

**Comment by NeoTheThird** [comment]
Just to be sure, can someone confirm this for xenial?

**Comment by Flohack74** [comment]
This is neither release nor device specific, on the OPO I get:
![grafik](https://user-images.githubusercontent.com/16186470/41963282-6922e7cc-79f7-11e8-8f33-be15f09f9e4f.png)

Red text saying that call forwarding cannot be changed "just now" ... Well it seems to be persistent.

**Comment by Flohack74** [comment]
Here on N5 and xenial same story, maybe this never worked:
![grafik](https://user-images.githubusercontent.com/16186470/41972333-e0941e60-7a11-11e8-99ec-5fbfa0b9d412.png)

**Comment by WillemHexspoor** [comment]
On my Nexus 5, Xenial and OTA-5, call forwarding works the way it should. I can't reproduce.

**Comment by UniversalSuperBox** [comment]
I'm also able to change call forwarding settings under OTA-5 and 16.04 `devel`. Closing barring any new confirmations.
