### ISSUE TITLE
missing support for actual video formats

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#579]
UBtouch on a tablet shall be capable of working with all actual codecs (like it is provided in ffmpeg library). Actually only *.flv files are shown correctly. 
Video playing actually fails for *.mp4, *.mpeg, *.mpg, *.ts files.

For the playback the applications shall not !!!! copy the file into a cache area. When handling a film with 1-2 GB the caching of the whole file will take nearly the time of the file duration itself. The playback needs to be handled in a streaming manner.

**Comment by arubislander** [comment]
On the codec support issue: I have succesfully displayed *.mp4, *.mpeg and *.mpg files on my Ubuntu Touch tablet and phone. I have never tried *.ts files, so not sure about those.

**Comment by lduboeuf** [comment]
@hoh61 should we keep that issue open ?

**Comment by dobey** [comment]
I think we cannot keep this issue open. We cannot ship software decoding for all formats via ffmpeg by default, for legal reasons. If there are issues with decoding of specific codecs which are supported by the hardware, through the hybris back-end, then issues should be opened for that (such as the colorspace problem on Nexus 5, which has its own issue). But unfortunately, legally we cannot provide support for all formats and codecs by default on all devices.

**Comment by lutin11** [comment]
I've tryed open the file it UTmedia and it could be played

**Comment by dobey** [comment]
> I've tryed on OTA10 rc channel, problem still present, the video can't be played with default media player but I successfully played it with UTmedia.

If you are referring to the issue on Nexus 5, it is a separate issue, and not the one which was described here; nor was it claimed to be fixed in OTA-10, for reference.

**Comment by lutin11** [comment]
Thanks for your replied, indeed, I was referring Nexus 5 issue.
