### ISSUE TITLE
Add Bulgarian keyboard layout

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#583]
A Bulgarian keyboard layout was added in https://github.com/ubports/keyboard-component/pull/37.

**Comment by NeoTheThird** [comment]
Thanks for the PR, @skrech. Could you check if this works fully?

**Comment by NeoTheThird** [comment]
Go into settings > language > keyboard, select the bulgarian keyboard, see if it works

**Comment by skrech** [comment]
:)

I mean is there a tutorial how to flash the development version of ubports on my E4.5?
