### ISSUE TITLE
[xenial] - python set up ? 

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#585]
### Illustrations

- Device: Nexus 5
- Channel: devel
- Build: 366

### Steps to reproduce
Build umark apps according to https://forums.ubports.com/topic/1215/updating-apps-to-16-04

### Expected behavior
I'm not really sure what to expect,
Does the problem below is related to my app or do i'm facing a bug/misconfig ?

Especially : 
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

### Logfiles and additional informationLoading module: 

```
ernest@thinkpad:~/umarks$ sudo clickable -k 16.04 logs
'libubuntu_application_api_touch_mirclient.so.3.0.0'
"/opt/click.ubuntu.com/umarks.ernesst/0.15/$@" does not exist.
virtual void OnlineAccountsModule::Plugin::registerTypes(const char*) Ubuntu.OnlineAccounts
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

**Comment by NeoTheThird** [comment]
Pinging @dpniel since he worked on #95 and @bhdouglass for all things clickable.

**Comment by ernesst** [comment]
Correct Dan, 
I cleaned and removed both from my app and now it is ready foe Xenial.
Thanks
