### ISSUE TITLE
Hammerhead won't boot after devel build update

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#587]
- Device: Nexus 5 (hammerhead)
- Channel: 16.04/devel
- Build: r367 I think?

### Steps to reproduce
Checked for updates in System Settings and updated to latest build (I think it was r367, but since the device won't boot I can't check to make sure).

### Expected behavior
Device updates to latest build and reboots.

### Actual behavior
After the UBports mascot appeared for the "installing update" screen and the device rebooted, it hanged on the Google boot screen. I force powered it off because it seemed to be taking abnormally long (hanging on the boot screen has happened before, but force rebooting always worked), but after that the device would never boot fully. It either hanged on the Google screen or reached the Ubuntu Touch splash screen and died. Recovery mode still works, but rebooting the device from recovery has the same result.

Is the only option to re-flash? Is there at least any way of knowing what caused this?

### Logfiles and additional information
Is there a way to get logs if the device won't boot?

**Comment by ernesst** [comment]
Sometime it happens, i need to force the phone off and then on the second boot everything is fine.

**Comment by Flohack74** [comment]
You might try the following:
- Let it boot until its stuck
- Then force the device into recovery (its either volup or voldown together with power, please google it)
- While in recovery, attach USB, and adb shell into the phone
- Try to cat /proc/last_kmsg to try to get the latest dmesg log, or adb pull /proc/last_kmsg to transfer it to your PC

**Comment by Arc676** [comment]
Found the recovery log in `/cache/recovery/last_kmsg`. I have attached the file to this post.
[last_kmsg.txt](https://github.com/ubports/ubuntu-touch/files/1997603/last_kmsg.txt)

**Comment by Arc676** [comment]
New update: the device didn't give any warnings at the time, so I didn't suspect this, but insufficient battery may have been the cause. It's possible that the device started booting but then the battery was unable to provide sufficient power to complete the boot process.

I only became aware of this issue after obtaining the recovery log because the battery icon appeared on the screen after I had unplugged the device from my computer. After charging overnight, the device booted properly in the morning.

Closing this issue until this problem occurs again, attributing the problem to battery until then.

Sorry for opening an issue for such a negligent mistake.

For the sake of understanding the `dmesg` logs, here are the lines matched by `grep` to contain `battery` or `power`.
```
<6>[    0.300133] PMIC@SID0 Power-on reason: Triggered from KPD (power key press)
<3>[    0.605442] bluetooth_set_power set blocked=0####btlock acquired cookie: BT35
<6>[    0.684571] anx7808 anx7808_vdd_1p0_power: vdd 1.0V is already off
<6>[    0.737880] anx7808 sp_tx_hardware_poweron: anx7808 power on
<5>[    0.740516] anx7808 sp_tx_vbus_powerdown: 3.3V output disabled
<6>[    0.797865] anx7808 sp_tx_hardware_powerdown: anx7808 power down
<4>[    1.296861] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<4>[    1.298712] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<4>[    1.412682] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<6>[    2.628676] msm-dwc3 msm_dwc3: DWC3 in low power mode
```
That last one might be relevant.
```
<4>[    1.296861] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<4>[    1.298712] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<4>[    1.412682] bq24192_get_soc_from_batt_psy: battery power supply is not registered yet
<3>[    1.413585] batt_tm_psy_init: battery supply not found
<6>[    1.418224] platform battery_tm_ctrl.79: Driver batt_tm_ctrl requests probe deferral
```

**Comment by fourloop2002** [comment]
Same issue on N5 hammerhead (r412).  Battery level indicated 30-40%, hangs on Google boot screen for extended period of time (60+ seconds).  Anecdotally I think the phone eventually boots up after many minutes. Attached a charger and phone booted normally.
