### ISSUE TITLE
[xenial] Calls have no audio

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#588]
Calls have no audio on qcom devices due to missing audioflingerglue.

**Comment by darkbluelight** [comment]
Can confirm, FP2 not usable with 16.04 devel. Microphone and speaker not working with calls.

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/pulseaudio-packaging/commit/acf73f4a9a5476e6a555b006ea8ec7b46b141ea1

**Comment by walidham** [comment]
yeah, now sound work when make call, but i must change libhybris-common.so file (using old file from UT rootfs 15.04), its for Moto G 2014
