### ISSUE TITLE
Mako - Bluetooth paired and trusted devices not stored

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#59]
After a reboot the paired bluetooth devices cannot be remembered.

noticed on 2 mako, with and without multirom.

**Comment by ernesst** [comment]
The bug is still present on the last devel.

**Comment by Flohack74** [comment]
Why was this closed? Please link commit, PR etc. here @NeoTheThird @APokorny

**Comment by NeoTheThird** [comment]
I figured the issue wouldn't appear with the canonical port we're using now. Sorry.

**Comment by ernesst** [comment]
Fixed on the 144 devel !
Excellent thanks

**Comment by Flohack74** [comment]
@APokorny is it really fixed? I close it then, but plz confirm that is is really fixed ;)
