### ISSUE TITLE
cannot install ubuntu touch sdk ide

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#594]
Description of the feature

smoothly installation of the ubuntu-touch sdk ide expected

Illustrations

    Device: AMD X64
    Channel: Sarah/16.04
    Build:

Steps to reproduce:
installation of software behind a proxy

Expected behavior
running smoothly

Actual behavior
ubuntu-sdk-ide is conflicting with ubuntu-sdk-ide. When installing ubuntu-sdk-ide the reference to the image files is missing. 
After installing sdk first and subsequently sdk-ide I can see the image files, but only when starting from command line. When starting form icon of desktop (ALT + F2) they don't appear.
Finally instead of installing the images an error message comes up saying that they cannot access the files server (although I can download them with the browser)!

How can I install these files manually?

And please, tell those bloody script kiddies to handle the proxy server correctly and do not download files as user "root" !!!!!!!!!! (they all seems to care a shit about security issues).

Logfiles and additional information

**Comment by NeoTheThird** [comment]
The Ubuntu SDK IDE is not supported by UBports. More information: https://docs.ubports.com/en/latest/appdev/index.html
