### ISSUE TITLE
[xenial] No mobile connection

### ISSUE THREAD

**Issue by tydell** [ubports/ubuntu-touch#598]
- Device: Nexus 5 D821
- Channel: 16.04
- Build: r375 and newer

It seems that on 16.04 switch (in indicators area and in settings area) for mobile internet works (it is not grayed out sometimes). I can turn mobile internet on and off, but it looks like there is no access to internet through mobile. 

There is also only one option to choose in network settings which type of connection user want to use - 2G/3G. On 15.04 2G and 3G were separate options and there also was 4G/LTE option.

Modem firmware: 2.0.50.2.30

Logfiles:
dmesg: https://paste.ubuntu.com/p/3G5Nd6pZn7/
syslog: https://paste.ubuntu.com/p/S62VqWGX3M/
![screenshot20180514_100556127](https://user-images.githubusercontent.com/1691858/39989263-c68e38cc-5769-11e8-906a-2d7ba92fbd4f.png)
![screenshot20180514_100612400](https://user-images.githubusercontent.com/1691858/39989264-c6a85568-5769-11e8-8dba-a0101df7d53a.png)

**Comment by fw190d13** [comment]
I can confirm this when it goes for switching the network speed. I can't pick anything else except 2G/3G. Touching this option gives a spinning circle and nothing else happens.

**Comment by fourloop2002** [comment]
I also experience this issue.  Nexus 5 hammerhead D821(H) 32Gb Baseband version M8974A-2.0.50.2.30.  I switched to 16.04 about 3 hours ago, so latest dev build (r383).  Phone unstable keeps locking up and not responding forcing a reboot.  Will do a complete reinstall using ubports-installer.

**Comment by brispete** [comment]
This issue also affects my Nexus 5.

**Comment by ernesst** [comment]
Thanks for cross reference, i miss it.

**Comment by fourloop2002** [comment]
Nexus 5 D821 hammerhead xenial r395.  Not able to make or receive phone calls.  Text messages are flaky -today I can send/receive SMS, yesterday not. MMS failed to send/receive.  I updated to r395 today.

**Comment by fourloop2002** [comment]
This is definitely a bug.  Under 15.04/stable mobile data, phone calls, tests, mms in/out, bluetooth file transfer, speaker, headset all worked without making any adjustments.  Reinstalled 16.04/devel and nothing worked - bluetooth, mobile data, calls, texts, mms

**Comment by abkro** [comment]
Device: Nexus 5 D821
Channel: 16.04
Build: r401

I tested this today and can confirm the same problems. As the screen shots show, the device reports a 4G connection, but I am unable to access any website using the browser without switching on the wifi.

Log files:
dmesg [https://paste.ubuntu.com/p/nR8jzVyDhJ/](url)
syslog [https://paste.ubuntu.com/p/8drXM2q5RJ/](url)

3 screen shots. First two without wifi while testing cellular data connection. Last one with wifi (maybe superfluous).

![screenshot20180601_192900188](https://user-images.githubusercontent.com/7359038/40857289-febe5388-65da-11e8-9b0c-f00f3146a9aa.png)
![screenshot20180601_195230138](https://user-images.githubusercontent.com/7359038/40857307-0da5e654-65db-11e8-8510-c5d7c37ed83c.png)
![screenshot20180601_195611693](https://user-images.githubusercontent.com/7359038/40857334-1ff97d34-65db-11e8-8de8-746613203ec5.png)

**Comment by abkro** [comment]
No change in r416.
