### ISSUE TITLE
[xenial] Upgrade Mir to its latest version

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#60]
Hello,
I've noticed Canonical is still working on Mir and there is currently a much newer version available on Launchpad than it is on the 15.04 based phones: https://launchpad.net/mir

My phone says I have version 0.24 while the latest stable release is 0.26 as far as I know.

The reason why I am asking is that there has been a lot of progress made since 0.24 was released and some things like SDL2 etc. do require the latest Mir installed.

There is of course this SDL demo which can be built with Ubuntu SDK and works but there is a hack in it forcing it to use old SDL code: https://github.com/zub2/SDLDemo

Although I expect this to be partially fixed with 16.04 it would still be nice to see the latest Mir on the legacy devices as well - that is if adding them to 15.04 is not that much work (I have no idea, that is why I am asking here).

Thank you very much for considering it.

**Comment by zubozrout** [comment]
Another thing I forgot to mention is that with 0.26 changing DPI should be possible: https://bugs.launchpad.net/mir/+bug/1556142 (that may be very usable on a phone or a tablet and actually I am missing that feature a lot).

**Comment by Flohack74** [comment]
For 15.04 I think thats not possible, if you look on the dependencies. We would need to backport everything and on top maybe break a lot of stuff. For 16.04 it looks maybe better.

**Comment by zubozrout** [comment]
Ok, that is fair enough and understandable. Thank you for looking into it :).

**Comment by nfsprodriver** [comment]
This state needs to be converted to "In Process", right? There are some task in work on ci.ubports.com.

**Comment by nfsprodriver** [comment]
https://github.com/nfsprodriver/ut-indicator-torch This is an attempt tested on hammerhead/devel (because it accesses sys leds directly). It's meant to be chaned to CameraAPI, I think. The work is based on bhdouglass' indicator-weather - project. [https://github.com/bhdouglass/ut-indicator-weather](url)

**Comment by NeoTheThird** [comment]
@nfsprodriver you pick up on things :D

**Comment by NeoTheThird** [comment]
Closing for now. This issue was added before we had the "sudoku" plan for 16.04, so it is not fit for OTA-4. We'll see how to tackle this after OTA-4, when we're working out the roadmap to land latest Unity-8 and Mir.
