### ISSUE TITLE
switch off doesn't work when USB cable is connected

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#601]
### Illustrations

- Device: frieza
- Channel: 16.04/devel
- Build:R77

### Steps to reproduce

connect USB cable
switch off device with power menu

### Expected behavior

Device switched off

### Actual behavior

Device is restarting

### Logfiles and additional information

No logfiles. but:

Device is switched off directly without USB cable

With USB cable connected the switch off procedure has to be repeated, after that it worked (up to now). With USB canle connected you have to switch off twice!

**Comment by hsbyter** [comment]
Device: frieza
Channel: 16.04/devel
Build:R191

I could not replicate this. After i shut down and connected the USB Cable to the tablet it just charges without booting. Not necessary to switch off twice.

**Comment by Flohack74** [comment]
Closed due to inactivity.
