### ISSUE TITLE
[xenial] OpenStore update fails

### ISSUE THREAD

**Issue by fw190d13** [ubports/ubuntu-touch#604]
- Device: Nexus 5
- Channel: 16.04
- Build: r382

### Steps to reproduce
After fresh install go to OpenStore where there is an option to update it. Hit the upgrade. The app icons in the store are gone. After the reboot the store wants to be upgraded again.

### Expected behavior
Update allows to use the store.

### Actual behavior
The store can't be used.

**Comment by PhoenixLandPirate** [comment]
This is a known issue, when you upgrade your os the open store upgrades to a version which works on xenial, this how ever is reversed when you upgrade, there is a new open store in the works by the actual developer of the open store which makes it so you dont have that conflict, and also only shows xenial apps, how far along development this is I cannot be certain though.
