### ISSUE TITLE
[xenial] Ubuntu Touch 16.04 (r78) freezes BQ E4.5 constantly

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#606]
- Device: Krillin
- Channel: 16.04
- Build: r78

### Steps to reproduce

Use your dear E4.5 phone as usual

### Expected behavior

The phone should have a warm response to your care.

### Actual behavior

It's response is cold, so cold it gets frozen. Doesn't react to the touch of my fingers. The only way to make it reconsider its behavior is a long press on the power button to reboot it.

After a while, it goes back to the bad conduct. That never happened before installing r78.

### Logfiles and additional information

I'm unable to get the `dmesg` output using `adb`
>dmesg: read kernel buffer failed: Operation not permitted

but here's the logcat output https://paste.ubuntu.com/p/KNG6C6Y8Kd/

**Comment by hoh61** [comment]
I can confirm this behavior for device frieza. 16.04 r78)

I can provide a syslog with  at least the ubuntu-location-errors filtered out. But there seems to be no clue for this behavior
[crashdump.log](https://github.com/ubports/ubuntu-touch/files/2010193/crashdump.log)

The behavior can be reproduced in this way:
Start a program
switch to the start screen by the left panel.

You can close the application using the left application panel, but when trying to switch to the application by clicking the icon or wipe from left to switch between applications  the device freezes.

**Comment by dark-eye** [comment]
Same in Meizu Pro (turbo) since i downloaded r78 revision

**Comment by tydell** [comment]
Nexus 5 also freezes today after update to r383, but it freezes in random situations also without any action.

**Comment by ivoxavier** [comment]
Confirmed on my Fairphone 2 today (16.04/devel). Use it a bit then the it freezes, only reboot fix the situation, but then it happens again. Loop

**Comment by UniversalSuperBox** [comment]
This, along with a few other problems (like the MTP problem mentioned above) may be due to the completion of https://github.com/ubports/ubuntu-touch/issues/403. It's possible that many somethings (https://paste.ubuntu.com/p/ntDKMZ6qcf/) have broken ABI due to switching to the Ubuntu repository's version of several packages. Marius is working on an update to Qt. After that's finished, we'll be rebuilding most of the repository. That may fix everything.

**Comment by hoh61** [comment]
update r80 installed, problem still there on frieza

**Comment by tydell** [comment]
Ok, it looks like Nexus 5 16.04 devel r387 freezes no more.

**Comment by mariogrip** [comment]
Fixed

**Comment by Flohack74** [comment]
Can we know how it was fixed (QA process) @mariogrip :)

**Comment by UniversalSuperBox** [comment]
Rebuilding all the packages

**Comment by hoh61** [comment]
For frieza there is a qurious behavior with R81: device seems to work properly (the first minuts), but the installation process was interrupted: device showed the boot screen for reboot but didn't proceed.

Manual start of the reboot installed the package, but it was not registered. Can be downloaded again, but installation then fails.!

**Comment by dark-eye** [comment]
Great work @mariogrip ( and Team :smile:  ) !!
Working without any issue for over an hour :+1:
