### ISSUE TITLE
Text message quick reply does not auto focus

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch#607]
- Device: MX4
- Channel: stable
- Build: r3

### Steps to reproduce
- Receive text message
- Tap the message in the indicator to open the auto reply

### Expected behavior
The keyboard should popup immediately and the reply box should be focused.

### Actual behavior
The reply box shows, but is not focused and the keyboard remains hidden.

**Comment by Flohack74** [comment]
Are you sure it works? For some reason my text msg notification now has no quick reply at all...

**Comment by dpniel** [comment]
Weird it's working for me here but that's not using the deb in the archive. Let me update to the latest xenial image and check

**Comment by Flohack74** [comment]
Sorry was my fault. I tested accidentially the white popup notification that arrives, not the indicator lol.
