### ISSUE TITLE
Run Anbox on all devices

### ISSUE THREAD

**Issue by sirredbeard** [ubports/ubuntu-touch#608]
### Description of the feature

Adopt Anbox or Chromium OS's implementation of Android app support to ubuntu-touch so that Android apps can be run on the ubuntu-touch flavor for the Librem Purism 5.

Maintaining support for all  Android apps will be a nightmare and there is no way Google would license Play for the effort, though maybe you could get some Amazon money putting there stor ein there. Reasonably though Ubuntu-touch could launch on the Librem with it's own apps and a repo of just 5-10 supported and tested popular android apps that there just aren't going to be ubuntu apps for, like instagram.

Anbox is [going to need a lot of help](https://github.com/anbox/anbox/issues/711) to get there. It hasn't even been updated to run on 18.04. But Anbox and Chromium OS's implementation are both based on LXD, so putting something together may not be too hard, for someone a lot smarter than I am.

**Comment by morphis** [comment]
This is already real. See https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html :-)

**Comment by sirredbeard** [comment]
I know. It could be a killer feature for UBports going forward. UBports should prioritize working with you to ensure continued progress on this, such as xenial support and support for key high-demand Android apps as part of their Purism Librem 5 push.

**Comment by delijati** [comment]
Should maybe go into a new issue: It would be nice to have some minor documentation on how to **build** anbox, what parts are needed what for and what was changed in thee anbox sources.

**Comment by Flohack74** [comment]
Closed this, Anbox is now deprecated in favor of Waydroid.
