### ISSUE TITLE
Updates fail with exit code 7

### ISSUE THREAD

**Issue by Arc676** [ubports/ubuntu-touch#609]
- Device: Nexus 7 (flo)
- Channel: 15.04, Stable
- Build: r2

### Steps to reproduce
System Settings tells me there are two updates available: Calculator and OpenStore. Tap on any appropriate button to attempt to update these applications.

### Expected behavior
Updates downloaded and installed.

### Actual behavior
Updates fail with exit code 7 and no output.

### Logfiles and additional information
![Screenshot](https://user-images.githubusercontent.com/30745465/40263752-9369b046-5b49-11e8-830b-ffb0b24b7d8f.png)

**Comment by Arc676** [comment]
Updates installed successfully with no issues when I updated from within the OpenStore instead of System Settings.

**Comment by advocatux** [comment]
Did you try to install those packages with OpenStore app immediately after failing with System Settings or you waited to do it?

**Comment by Arc676** [comment]
If I remember correctly, the chain of events on that day went like so:
- See updates in OpenStore
- Reminded about this issue
- Went back to Settings to try to update
- Updates fail with exit code 7
- Go back to OpenStore to update
- Update succeeds

**Comment by advocatux** [comment]
OK thank you. I asked to discard OpenStore as the culprit failing.

**Comment by Flohack74** [comment]
Is this still a problem?

**Comment by Arc676** [comment]
Hasn't happened since. I recently updated some apps from System Settings with no issues. I'll close until it happens again.
