### ISSUE TITLE
[xenial] cannot load available libraries (disk full)

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#610]
### Illustrations

- Device: frieza
- Channel: 16.04/devel
- Build: r81

### Steps to reproduce

I'm trying to port several old applications to the new device, but therefore I need additional libraries installed.
In the actual case I need the libqt5serialport5 library, which seems to be available in the repository but cannot be installed.

### Expected behavior

installation of library

### Actual behavior

error message from apt: write error: no space left on device

### Logfiles and additional information

As reference the output of df:

[df.log](https://github.com/ubports/ubuntu-touch/files/2019276/df.log)
The device /dev/loop0 is mounted rw.

**Comment by dpniel** [comment]
Any libraries not already provided by the rootfs should be included in your click package. `/lib/$ARCH_TRIPLET` (so `/lib/arm-linux-gnueabihf` on the phone) is added to the `LD_LIBRARY_PATH` on launch of the app, so as long as you place libqt5serialport5 in the correct location when building the click you shouldn't hit any issues. One thing to note is ubports doesn't currently build qtserialport so you would need to compile that yourself to work with the Qt5.9.5 in the xenial archive when you get to developing for xenial.

Anyway if you think there is good reasoning to have the library in the rootfs for any app to use then I would suggest to make a feature request for it.

---
@mariogrip do you think we should at least be building it even if we aren't including in the rootfs? so at least it's easy for folks to just unpack a deb into the click

**Comment by Flohack74** [comment]
For the serial port issue please make a separate issue, we should not mix 2 topics in one.

**Comment by hoh61** [comment]
I have digged around in several comments and can finally conclude that the original issue can be closed. 

The effect is based on a silly behavior of the file system to reserve some free space for root file system.
This effect can be removed using  "tune2fs .m 0 /dev/loop0".  This is setting the reserved space to zero and the "df" output is correct.

For the USB driver I will generate a new issue.
