### ISSUE TITLE
[xenial] nexus 5 telegram-app installed but no more messages

### ISSUE THREAD

**Issue by fourloop2002** [ubports/ubuntu-touch#613]
- Device:  Nexus 5
- Channel: Devel
- Build: 16.04 (r387)

### Steps to reproduce
Install telegram-app (v2.5.3.2), log in.  

### Expected behavior
Group chats updated as new messages arrive .

### Actual behavior
No updates since the day app installed.  Icon in top left hand corner shows a flashing cloud symbol with exclamation mark.  On the day app installed I used telegram-app for approximately half a day before shutting down the phone. Next day app received no further updates.

### Logfiles and additional information
Reinstalled telegram-app and rebooted.  No change, same messages from the day originally installed the app (3 days ago) and no new messages.

**Comment by NeoTheThird** [comment]
@Flohack74 How do you want to do this? Have all the telegram reports in their tracker?

**Comment by fourloop2002** [comment]
Please close this.  I'll retest with latest telegram/xenial and report bugs (if any) to the Telegram tracker (whatever that is;-)
