### ISSUE TITLE
UbuntuTouch Installation Nexus 5 

### ISSUE THREAD

**Issue by Beduries** [ubports/ubuntu-touch#617]
Dear Sir or Madam

First, my English is not quite the best in town.

Second, I used to install UbuntuTouch to my new purchases GoogleNexus 5 via ebay. 
I rooted it succesfully. 

I run windows 10, and I used the installer. But unfortunately connected via USB-cable nothing happens.
What is wrong?

I red some of the threads, but nothing helped.

Thanks in advance

Beduries

### Illustrations

- Device: LG Google Nexus 5 (I'm sure!)
- Channel: UbuntuTouch
- Build: n/a

**Comment by advocatux** [comment]
I agree with @fourloop2002 
@Beduries please close this issue and join us in the supporting group or in the forum (https://forums.ubports.com/).
