### ISSUE TITLE
[xenial] No WiFi or Hotspot button visible in network indicator or WiFi settings

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#621]
- Device: FP2
- Channel: 16.04
- Build:

### Steps to reproduce
Not sure about steps, but suddenly the indicator and the WiFi settings do not show the right buttons anymore (see screenshot). Moreover, I cannot leave any WiFi anymore, since also the button for leaving is missing.

### Logfiles and additional information

Left: FP2 with 16.04, right: OPO on 15.04
![grafik](https://user-images.githubusercontent.com/16186470/40326840-ffd18aee-5d40-11e8-902e-329f42629cbe.png)

**Comment by mariogrip** [comment]
lets not use critical then we block devel releases for been built. critical is only for things that really break things

**Comment by Flohack74** [comment]
I consider a broken WiFi broken.

**Comment by Flohack74** [comment]
And actually it should only block promoting devel to rc.

**Comment by UniversalSuperBox** [comment]
Interesting.

If I go into hotspot settings, set it up, and turn it on, the hotspot switch appears in the indicator. However, the Wi-Fi switch disappears both in the indicator and in Settings.

Either switch may (seemingly randomly) appear or disappear upon a reboot. Seems like some state handling just isn't working right.

**Comment by NeoTheThird** [comment]
@mariogrip 

> lets not use critical then we block devel releases for been built. critical is only for things that really break things

That's not what that does, it prevents RCs: https://docs.ubports.com/en/latest/about/process/issue-tracking.html#labels

Imho we should add it again.

**Comment by Flohack74** [comment]
Oh forgive me. But its totally counter-intuitive in this way. Even I as a techie was confused.
