### ISSUE TITLE
[xenial] Can't scroll to the bottom of the home screen

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#624]
- Device: FP2
- Channel: 16.04/devel
- Build: r301

### Steps to reproduce
Scroll down on the home screen. (Does not happen every time. Not sure what triggers this)

### Expected behavior
I can scroll until I reach the bottom.

### Actual behavior
I can scroll like 80% of the app list. The last position is not even at the end of a row. I can try to scroll further, but the rest of the apps is not there and it bounces back when releasing the finger. Therefore, I cannot start some Apps, like the clock ("Uhr" in German).

### Logfiles and additional information
Restarting the phone fixes this temporarily.
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2031135/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2031136/UTlogcat.txt)

**Comment by Arc676** [comment]
This is similar to behavior I have experienced on my Nexus 5 (hammerhead). It's also on 16.04/devel, just updated to build r397, still reproducible.

The main application scope sometimes stops short of scrolling all the way. Unlike the issue described here, I *can* see the rest of the icons if I keep dragging, but the view jumps back and stops short of the complete view. Sometimes, switching to landscape mode and back solves the problem.

The screenshot shows the position to which the scope jumps. Half of the last row is left beyond the screen, but I can still launch these applications.

![screenshot](https://user-images.githubusercontent.com/30745465/40429764-064d900c-5ed6-11e8-8059-b9a4e92957cc.png)

**Comment by advocatux** [comment]
I can confirm this bug in Krillin (xenial) too.

My workaround is click on Search (the magnifying glass), click on whatever category, and then click on Cancel, and everything works fine until the next time :)

**Comment by Daniel20000522** [comment]
Confirmed on Nexus 4 (Ubports 16.04 r85).

**Comment by dpniel** [comment]
I think [this commit](https://github.com/ubports/unity8/commit/95d8efbee7f6d3c4ef7f1d091f36d64d2155fd80) could have caused this regression as it is no longer recalculating the height on the geometry changes. Instead it should be using the new [QQuickGeometryChange](https://code.woboq.org/qt5/qtdeclarative/src/quick/items/qquickitemchangelistener_p.h.html) in that method override to adjust the components height.

**Comment by kugiigi** [comment]
I can confirm this on my Nexus 5 on xenial.
It happens when I install new apps from the OpenStore.

**Comment by jonnius** [comment]
Seems to work fine now.
