### ISSUE TITLE
Whole-day-events are shown at the wrong day in calendar indicator

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#628]
- Device: FP2
- Channel: 16.04/devel
- Build: r301

### Steps to reproduce
Create a event for a whole day. Open the calendar indicator (swipe from the top). Tap at the day you created the event for.

### Expected behavior
The event is displayed in the list beneath the calendar.

### Actual behavior
The event is not displayed in the list beneath the calendar. But if you tap one of the days before, it gets displayed in the event list. Another detail: 0.00 is shown as the time of the event. Imho it would be better not to show any time at all or maybe something indicating it is a whole-day-event.

### Logfiles and additional information
The dot indicating the event is shown at the right day.

**Comment by Flohack74** [comment]
This issue was moved to ubports/calendar-app#88
