### ISSUE TITLE
[Xenial] Clock always crashes

### ISSUE THREAD

**Issue by jonnius** [ubports/ubuntu-touch#630]
- Device: FP2
- Channel: 16.04/devel
- Build: r304

### Steps to reproduce
Open clock core app.

### Expected behavior
It does not crash.

### Actual behavior
It crashes after a few seconds. I can't disable my daily alarm :(

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2034954/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2034955/UTlogcat.txt)
[Clock Log](https://paste.ubuntu.com/p/kfhQGHTFQn/)

**Comment by Flohack74** [comment]
This issue was moved to ubports/clock-app#75
