### ISSUE TITLE
[xenial] Unmet dependencies when installing qt creator

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#631]
- Device: Nexus 5
- Channel: 16.04 Devel
- Build: r400

### Steps to reproduce
1. Open terminal app
2. Execute the command below
sudo apt-get install qtcreator

### Expected behavior
qtcreator should be installed successfully.

### Actual behavior
Errors are encountered and qtcreator isn't installed successfully.

The following packages have unmet dependencies:
qtcreator: Depends qtbase-abi-5-5-1
                Depends qtdeclarative-abi-5-5-0

### Logfiles and additional information
This was done directly into the device filesystem and not in libertine or any kind of container. I know this isn't supported but just taking my chance that someone could at explain or provide a workaround. And maybe this could also be something that should really be fixed? Not really sure 😁

**Comment by NeoTheThird** [comment]
I don't think we can provide the 5.5.* abi, since it's compiled with an incompatible gcc version (iirc). We might just ignore this one. Thoughts, @mariogrip?

**Comment by dpniel** [comment]
For this we need just need a build of qtcreator using the Qt version in UBports repo. I think it's something we should provide, we can't really say "you need to develop Qt apps but can't use Qt development tools" :-) I can look at packaging it without the ubuntu sdk plugin parts if there is agreement.

**Comment by Flohack74** [comment]
Yes lets try this, I think thats a good way to go for a minimal support of QtCreator.

**Comment by dpniel** [comment]
Done http://repo.ubports.com/pool/xenial/main/q/qtcreator/

We now have qtcreator 4.5.2 as well as qbs 1.10 (if anyone uses it) available in the xenial UBports repo.

@kugiigi try updating your apt list and installing again :-)

**Comment by kugiigi** [comment]
Awesome! I got it installed now. I was just taking my chance here you are really cool to actually make it available. I guess I need to do my part now and make my apps available for Xenial. Thanks!
