### ISSUE TITLE
[xenial] Dynamic scaling doesn't work with external display

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#632]
- Device: Nexus 5
- Channel: 16.04 devel
- Build: r400

### Steps to reproduce
Connect device to an external display

### Expected behavior
The UI will scale (usually smaller) according to the display's detected resolution.

### Actual behavior
The UI stays the same so it looks big.

**Comment by abkro** [comment]
I can confirm this behavior on Nexus 5 hammerhead running Xenial r 415.

**Comment by NeoTheThird** [comment]
Does not seem to affect the M10's micro-hdmi output. Tested with a Full-HD monitor and 4K TV.
![image20180609_142713710](https://user-images.githubusercontent.com/12068939/41191552-ba3011da-6bf1-11e8-9470-44e74a75b60b.jpg)
![image20180609_141426833](https://user-images.githubusercontent.com/12068939/41191553-ba4f43e8-6bf1-11e8-9d71-a0b0407f020a.jpg)

**Comment by kugiigi** [comment]
Isn't that just the normal scaling of the M10 on tis own screen?
Perhaps it looks okay because the default scaling is already ideal for windowed mode.
Do you get #438  on vivid and in xenial?

**Comment by abkro** [comment]
Here's what it looks like on Nexus 5 hammerhead running r419:

![20180609_175514](https://user-images.githubusercontent.com/7359038/41193662-aaf560e4-6c0f-11e8-9e99-5ba184e4ad16.jpg)

**Comment by kugiigi** [comment]
I can confirm this on Nexus 7 2013 (flo). Same issue happens when connected to an external display.

**Comment by lapor** [comment]
I can confirm for M10 FHD. On the external screen one can see bigger UI then I think it should be. My post on [Diaspora](https://diasp.eu/posts/7490445).

**Comment by idekovets** [comment]
Confirm on Nexus 5 16.04 RC 2018-W30. I connect my phone via SlimPort cable to my TV. I try it on 15.04 Stable, and it work well. See photo
![photo_2018-07-06_19-02-46](https://user-images.githubusercontent.com/41849731/43452254-ae2052dc-94bf-11e8-980c-7824fad99aec.jpg)

**Comment by UniversalSuperBox** [comment]
This bug has been confirmed by a community member on the Fairphone 2 connected to a wireless display.

**Comment by nfsprodriver** [comment]
Shouldn't we delay it to e.g. OTA5?
