### ISSUE TITLE
[xenial] Settings page do not open in the Terminal app

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#633]
- Device: Nexus 5
- Channel: 16.04 devel
- Build: r400

### Steps to reproduce
1. Open the terminal app
2. Click the settings button at the upper right

### Expected behavior
The settings page opens as a new window.

### Actual behavior
Nothing happens when clicking the settings button.

**Comment by advocatux** [comment]
I've just test it because I remember this working in devel before and I can confirm this bug in BQ E4.5 (Krillin) running Ubuntu 16.04 (r85) too.

**Comment by Arc676** [comment]
Can confirm on Nexus 5 running r401 on 16.04/devel.

**Comment by fourloop2002** [comment]
Ditto with @abkro above

**Comment by abkro** [comment]
No change so far. Running r421 now.
