### ISSUE TITLE
 [xenial] most online account services unavailable

### ISSUE THREAD

**Issue by matv1** [ubports/ubuntu-touch#635]
### Illustrations

- Device: Meizu Pro 5
- Channel:16.04/devel
- Build: 85

### Steps to reproduce
Go to System Settings --> Accounts --> Add account
it will only show 2 services: Ubuntu One and Google.
All other services that are available on 15.04 stable are missing (like Nextcloud, Caldav, Evernote, etc)

### Expected behavior
all services that are available in online accounts in 15.04 stable should be visible.

### Actual behavior
They are not there

**Comment by ernesst** [comment]
Hello, 

Please perform a search before opening an issue, see #602 & #589
