### ISSUE TITLE
[xenial] Anbox - No onscreen keyboard

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#637]
Bug Report

- Device: BQ M10 Frieza
- OS: 16.04
- Channel: Devel
- Build: R86

### Steps to reproduce
Install Anbox. 
Try to type in any text field. e.g. Adding a new contact in the android contacts app. 

### Expected behavior
Once you tap on the text field and the cursor appears the onscreen keyboard should appear. 

### Actual behavior
The keyboard does not appear. 

### Logfiles and additional information
I'm happy to add logfiles but can't see any obvious candidates.

**Comment by padraic7a** [comment]
Hi @Flohack74 the device is frieza. I should have mentioned that - adding it now.

**Comment by tomoqv** [comment]
I can confirm this on the Pro 5.

**Comment by NeoTheThird** [comment]
Removing anbox issues from the milestone for now, since we're not targeting to ship it in OTA-4 yet. This makes it a little easier for us to maintain an overview.

**Comment by PhoenixLandPirate** [comment]
@NeoTheThird  did you meant to close the issue, or just remove it from the milestone?

**Comment by padraic7a** [comment]
@NeoTheThird are we ignoring issues with Anbox for now? Recently none of the anbox apps will work for me. I would open an issue but would it be unwanted?
