### ISSUE TITLE
device not recognized my nexus 5 when reboot bootloader

### ISSUE THREAD

**Issue by hla12** [ubports/ubuntu-touch#642]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by hla12** [comment]
I read the description on web, and when its show pop up reboot bootloader its nothing happens, i use win7 32bit btw

**Comment by advocatux** [comment]
Can you edit and file a proper bug report? Now it doesn't show any information.

What device and what OS is running in it currently? What UT version are you trying to install? Which installer version are you using? Can you paste the installer log? etc

**Comment by NeoTheThird** [comment]
Please report a bug on github.com/ubports/ubports-installer and provide more information on what steps you already took to resolve the issues. Are ADB drivers installed? See the https://github.com/ubports/ubports-installer/#device-not-detected-windows.
