### ISSUE TITLE
[xenial] Wifi on turbo not working after Anbox installation

### ISSUE THREAD

**Issue by tudorels** [ubports/ubuntu-touch#646]
### Illustrations

- Device: turbo
- Channel: 16.04
- Build: r87

### Steps to reproduce
After install r87 configure wifi for the first time and it works until restart. 

### Expected behavior
After restart wifi should work normaly.

### Actual behavior
After restart wifi did not find any networks.

**Comment by tudorels** [comment]
I installed today r89 and there is no change. Wifi does not work, if it helps I discovered that if I do Erase and Reset All, wifi can find networks and work, but after the first restart it stops working again.

**Comment by tomoqv** [comment]
I haven't noticed this behaviour on my Pro 5. It happens from time to time though, that wifi doesn't find any networks (on 15.04 as well as 16.04). I have always been able to fix this by toggle wifi off/on.

**Comment by tudorels** [comment]
I installed 15.04 again and everything works perfectly. 
Maybe in 16.04 it's happening because I tried to install Anbox. After the first Anbox installation attempt, I had no wifi or cellular network, but after the reinstall with wipe, only the cellular network works ok.

**Comment by tudorels** [comment]
If I try to install Anbox again the networks(wifi and cell) no longer works.

**Comment by tomoqv** [comment]
I also installed Anbox a while ago, but I uninstalled it because of the network issue and that there is no OSK in Android apps.

**Comment by NeoTheThird** [comment]
Okay, so it does not happen when you don't install anbox?

**Comment by tudorels** [comment]
I have not succeeded in completing Anbox installation because after write of bootimg partition and restart I have no network (internet). So maybe it's related with the first steps for installing Anbox.
I did not know how to undo the steps I've made from here https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html, and I did not try again to install Anbox.
So if you(@NeoTheThird ) can guide me to undo the partition modification I will try to install 16.04 and see what is going on without modification for Anbox. Thank you!

**Comment by tudorels** [comment]
So I've manage to complete the Anbox installation and after that I installed 16.04 with ubports-installer with wipe option and the wifi is working after restart ... so it seems the problem is generated by Anbox incomplete installation.

**Comment by NeoTheThird** [comment]
Okay, thanks

**Comment by tudorels** [comment]
Thank you, too, without your questions I would not have figured out how to fix it ... is working without Anbox.
but the problem still arises when installing Anbox, you may consider it ...
