### ISSUE TITLE
USB driver modules needed

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#647]
### Description of the feature

I'm looking forward to install an Ubuntu touch image for my Nexus 7, where I installed a long time ago the Ubuntu image (flo).
Before doing this I would like to port my applications to Ubuntu touch on BQ m10 FHD (frieza). This is failing since 
1) I need the USB port as serial interface (module usbserial and cp210x), which are standard in the ubuntu image and missing in the UBtouch image
2) I cannot compile these modules by myself because I had to learn recently that we are running on Android !?

Therefore I ask to exceed the USB support at least with these drivers (other issues are requesting some additional drivers).
### Illustrations

- Device:
- Channel:
- Build:

**Comment by Flohack74** [comment]
You misunderstood me: I did not say we are running on Android, but we need to use the same kernel version that was delivered by the manufacturer of the device with the initial Android version. Only in very special cases someone was able to make a kernel upgrade possible. On the other hand, if those drivers were already in mainline kernel versions for flo, you might be able to build a custom kernel = boot image for your device.

For the BQ devices its a bit harder as there we do not have the complete build tree (was not made public by Mediatek/BQ), so I am not sure you can build a kernel there...

**Comment by doniks** [comment]
I kinda doubt that you need another kernel driver in order to develop apps for flo .... Happily hacking away on deb (gsm variant of the flo). 

Are you in the telegram channels for app developers? I suggest to join and speak up with whatever problem you are having there, I expect it's something very different than a missing kernel driver.

**Comment by hoh61** [comment]
telegram: nice feature, but don't work on my device:

original telegram: needs a phone number from my tablet ???
Telepygram: not working.

Is there another tool, maybe for ubuntu desktop, to join the discussion groups?

**Comment by doniks** [comment]
Well there is the forum: https://forums.ubports.com/category/35/app-development 

(Also, I asked for an irc bridge in #648 , ... let's see)
