### ISSUE TITLE
[xenial] Music replay killed when device is sleeping

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#651]
- Device: Oneplus One
- Channel: 16.04/devel

### Steps to reproduce

Disconnect from power, play music from the music app, lock the device, wait about 5 minutes.

### Expected behavior

Music playback should continue.

### Actual behavior

Music playback stops. If you turn on the screen w/o unlocking, the playback starts and stops immediately when turning the screen off again. If you unlock (eg enter the code) and lock again, you get about five minutes of music and you're back to square one.

**Comment by PhoenixLandPirate** [comment]
This doesn't happen with podbird, so I think this might be a music app problem rather than a problem with the os.

**Comment by BlueKenny** [comment]
Sometime the Music isn't stopped, if i leave the display timeout it Stops and if i press the power button it works, ps this was the case some days ago, didn't tested it today (it stop on timeout)

**Comment by hoh61** [comment]
You may remember my issue 600 where the musicplayer stopped after as short timeout using the bluetooth headset. I tried to reproduce the error on frieza without bluetooth and can mostly confirm the bug on device frieza too. After approx. 5 minutes the music playback becomes chopped and continues correctly after wakeup of the device (no unlock neccessary).

**Comment by lfortanet** [comment]
I think this issue itś resolved, I've done all steps and the music doesn't stop, I am reproducing a file .mp3 with Music app and works fine with the device sleept. Around 25 minutes reproduced.

Bacon device, 16.04/devel, r322.

**Comment by NeoTheThird** [comment]
Seems to be fixed by moving the music app back to click. The issue was that the hooks weren't properly executed, so there was no life-cycle exception.

**Comment by NeoTheThird** [comment]
Turns out this can still happen on `2018-W25`, but to be fair, i had music playing without issues for at least three hours before. Do we re-open because of that? I am not sure.

**Comment by hoh61** [comment]
remains closed.
