### ISSUE TITLE
Move to QtWebEngine as default browser engine

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#653]
We currently have some regressions in 16.04 (#442, #574, #626) which are related to our use of an old version of Chromium in Oxide. Rather than spend the effort to upgrade Oxide (and possibly not fix the underlying issue anyway), we've decided that we'd rather move to QtWebEngine. 

QtWebEngine:
* Has people working on it from the Qt company
* Uses a more recent version of Chromium
* Is integrated into other operating systems already

The following tasks are needed for us to truly get rid of Oxide:

- [x] Include [QtWebEngine](https://wiki.qt.io/QtWebEngine) in the base image to allow app developers to use it in apps
- [x] Create a proper browser in [browser-ng](https://github.com/ubports/browser-ng)
   - [x] Publish an experimental build [on the OpenStore](https://uappexplorer.com/app/com.ubports.browserng)
   - [x] Reach feature parity (or preferably superiority ^^) with the current browser based on oxide
- [ ] Replace Oxide with QtWebEngine in [Ubuntu.Web](https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Web/index.html) components
- [ ] Make com.ubuntu.oxide into a wrapper that translates supported API calls to QtWebEngine

**Comment by Flohack74** [comment]
So this will be targeted for OTA-5?

**Comment by NeoTheThird** [comment]
Depends. Since we depend on webapps a lot, i'd also keep the option open to delay it to OTA-6. Also, we might need OTA-5 to be a hotfix release.

**Comment by NeoTheThird** [comment]
The experimental browser-ng can now be downloaded from [the openstore](https://uappexplorer.com/app/com.ubports.browserng) and the qtwebengine lib is included in the image. 🎉

**Comment by mardy** [comment]
While on holidays, I started working on making Ubuntu.Web a wrapper around QtWebEngine: https://github.com/mardy/webbrowser-app/tree/qtwebengine

It's a work in progress, untested, and I hope to be able to dedicate some more time to it in the near future; but if I don't, it still can be used as a starting point.

**Comment by UniversalSuperBox** [comment]
We've got the QtWebEngine-based Morph.Web and Morph Browser in for OTA-5, but replacing Ubuntu.Web has not occurred yet. This issue has been moved to OTA-6 for completion.

**Comment by arubislander** [comment]
Has this issue fallen off the radar?

**Comment by kugiigi** [comment]
This should be closed :smile:

**Comment by UniversalSuperBox** [comment]
Good point. The old browser engine, Oxide, is removed from the image now. QtWebEngine is the only engine available.
