### ISSUE TITLE
[xenial] Removed overlay PPA contained 2 more language packs

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#654]
For some weird reason there were Breton and Welsh added to the overlay PPA: https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/stable-phone-overlay/+packages?field.name_filter=langu&field.status_filter=published&field.series_filter=xenial

So if we decide to keep those, we need to again overlay them. Or does anyone have a better idea?

**Comment by Flohack74** [comment]
Update: We already copied them to our repo/xenial structure. So they are being installed from there now. But you cannot select them in the language selector. Still a bug?

**Comment by NeoTheThird** [comment]
Let's ping @dpniel since he took care of #403.

**Comment by dpniel** [comment]
Copied from telegram conversation with Flo

> I don't see them here https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=language-pack-touch so it must mean they have less than 70% coverage. I'm not sure why those two are in the ppa as xenial comes straight out the archive..

I can't seem to find where the xenial language-pack-touch-* stats are to see how complete those two are. Will keep looking... but IMO we shouldn't ship them unless they are in xenial universe as they can be deemed mostly complete.

**Comment by Flohack74** [comment]
This maybe? https://translations.launchpad.net/ubuntu

**Comment by mariogrip** [comment]
Any news on this one? does not seem like them are complete so removal is probably the way to go...
https://translations.launchpad.net/ubuntu/xenial/+lang/cy
https://translations.launchpad.net/ubuntu/xenial/+lang/br

**Comment by Flohack74** [comment]
Yes lets remove them.
