### ISSUE TITLE
Auto-focus the text input on the contact search page in the dialer

### ISSUE THREAD

**Issue by abkro** [ubports/ubuntu-touch#657]
This request is based on having used the Ubuntu phone as my main phone device for over a year. The current state of things became very annoying when frequently having to search for contacts in the contact list before placing calls.

### Description of the feature
In the phone app/dialer it takes too long to arrive at the 'search for contacts' window. Too many taps (clicks) = annoyed customers. I suggest a simplification that I believe should be fairly easy to implement. 

### Search for contact to call - actions required in current version

1. Open phone app/dialer. (First screenshot below)
2. Once in dialer, tap contact icon in top right corner. Contacts window appears (second screenshot)
3. Now you can scroll down to search for contact, but if you wish to type a name to search for, you have to tap once more on the search icon first, top right corner. This opens a search field and the screen keyboard appears. (Third screenshot)

### Suggested improvement/simplification 

When in the dialer view (first screenshot) tap the contacts icon and go directly to the contacts with search field ready to enter text (third screenshot). 

From here, it is still possible to start scrolling through displayed contacts. This causes the screen keyboard to automatically disappear, so no functionality is lost.

This simply saves time without detracting in any way from existing functionality.

### Illustrations
Screenshot 1

![screenshot20180606_220139868](https://user-images.githubusercontent.com/7359038/41065244-517d851a-69de-11e8-9382-c531bde1e676.png)

Screenshot 2

![screenshot20180606_220146024](https://user-images.githubusercontent.com/7359038/41065626-86061526-69df-11e8-8b01-61f8bfb5c848.png)

Screenshot 3

![screenshot20180606_220443947](https://user-images.githubusercontent.com/7359038/41065648-91c27bac-69df-11e8-8c10-f4c124815c57.png)

**Comment by sambuccid** [comment]
It's also possible to search directly in the phone app, tapping 2 it can list all the contacts with the letters A,B or C. However to have this feature need to rewrite the entire layout

**Comment by abkro** [comment]
I tried fo figure out how this works, but tapping '2' just gives me the digit 2 in the number field. What am I doing wrong?

Anyway, this still means one has to search through a list, scrolling before making a selection. Most of the time this is more time consuming than starting to type someone's name and watching the list being updated/narrowed down as you type, until you see the one your looking for.

Maybe this change requires more work than I thought, although I don't see why the layout should change? But if it is an excessively time consuming task,  it should not be prioritized at the expense of some more important feature or bugfix However, it will definitely boost the user experience, so I hope it can be done at some point. :)

**Comment by NeoTheThird** [comment]
This should be a pretty easy fix. If someone wants to take a shot at it, we can include it in OTA-4

**Comment by mymike00** [comment]
> It's also possible to search directly in the phone app, tapping "2" it can list all the contacts with the letters A,B or C. However to have this feature need to rewrite the entire layout

@sambuccid what you're referring to is not implemented yet, have a look at https://github.com/ubports/dialer-app/issues/3

**Comment by sambuccid** [comment]
I had not seen it, thanks

**Comment by pixelr0** [comment]
or we can just remove the dialer and replaces it with a button wololo! )99.999999999% of the times you don't use the dialer) and just show the contacts on the main screen. something like this 
![silly](https://user-images.githubusercontent.com/333589/41727034-13a9cf06-757c-11e8-8073-f1305961bf70.png)

**Comment by mymike00** [comment]
Well, just use the contact app ;)

**Comment by Flohack74** [comment]
I can understand the wish for speed dial from favorites.

**Comment by mymike00** [comment]
is it possible to have two desktop files for the same app? and maybe pass different parameters at the app? we could have a unique dial/contacts app but if you tap the dial desktop file the dial is shown in the "home" page, while if you open the contacts one you see immediately the contacts list
then there is only one app to maintain (as most of the code is the same)

**Comment by abkro** [comment]
I think the idea of an opening screen with speed dial alternatives is a good one, as long as the icon for the contacts app in the top right corner of the screen brings you straight to the field where you enter a name to search for with the on screen keyboard ready to type text.

Another alternative might be an opening screen with the dialer at the top and speed dial alternatives on the bottom half of the screen. Then, as soon as you touch either half of the screen, the other half disappears, and the green "dial" button appears, i.e. it goes into either dialer-mode, or speed dial-mode.

But in both cases, the contacts icon in the top right corner should remain.

How does that sound?

**Comment by Arc676** [comment]
What about remembering the phone app's last state? Similar to how the browser (the old one anyway) saves its open tabs and reopens them the next time the user opens the browser, the phone app could remember if the user looked at the keypad or their contacts the last time.

The implication would be that a user that always dials from the contact list would always see the contact list first while someone who uses the keypad a lot would see the keypad every time.

**Comment by NeoTheThird** [comment]
Please open separate issues for other proposals. What was accepted into the milestone is to auto-focus the text input on the contact search page, for other tasks, a new issue should be created! Adding a bottom navigation bar would go way beyond the scope of a `good first issue`.
