### ISSUE TITLE
[xenial] Clipboard pop-up paste doesn't work since r89

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#658]
### Description of the feature
Coped or cut text selection is saved to clipboard but it is not possible to paste it into a text field using text input pop-up bubble.

- Device: Meizu MX4 arale, but this is not device specific
- Channel: Xenial, devel
- Build: r89

### Steps to reproduce
Copy or cut a text selection from any app and try to paste it to any app. No text is pasted using regular pop-up method. But you can paste text in Terminal or Tedit app using their custom menus.

### Expected behavior
Text gets pasted into any text field.

### Actual behavior
Text isn't pasted at all.

### Logfiles and additional information
This may be relevant: https://github.com/ubports/telegram-app/issues/176

**Comment by doniks** [comment]
also on nexus 7 deb

**Comment by advocatux** [comment]
I can confirm the same issue on BQ E4.5 (krillin) running Ubuntu 16.04 (r89).

Maybe this is relevant?
`file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/Popups/1.3/PopupBase.qml:113: TypeError: Cannot read property of null`

**Comment by abkro** [comment]
Confirmed on Nexus 5 hammerhead running r416

**Comment by Daniel20000522** [comment]
Confirmed on Nexus 4 mako Ubuntu 16.04 r89.

**Comment by padraic7a** [comment]
And on the M10 FHD running xenial

**Comment by tudorels** [comment]
Also on Meizu Pro 5 r89
