### ISSUE TITLE
Include qml-module-qtwebengine with xenial image

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#659]
### Include qml-module-qtwebengine in Xenial image

For installing and testing the new browser it would be great to include qml-module-qtwebengine by default. 

From chatter on the forums and telegram groups it seems that a number of users on freiza, and other devices, don't have the space to install it with apt. Rather than have everyone monkeying around trying to resize their rootfs it would be great to make users lives a little easier and just include the package and it's dependencies.

**Comment by doniks** [comment]
It's certainly true that it would help with testing. But if there are space restrictions, it might be a nontrivial change to make room

**Comment by doniks** [comment]
> Thought it would be worth raising the issue anyway.
True! And sooner or later it needs to be solved. Just wanted to manage expectations
