### ISSUE TITLE
[xenial] Videos can't be played

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#661]
- Device: FP2
- Channel: 16.04/devel
- Build: r325

### Steps to reproduce

Take a video with the camera, swipe left for photo roll, tap play to open mediaplayer.

### Expected behavior

Video plays.

### Actual behavior

No thumbnail in camera app. When opening mediaplayer, you get the error message: "Error playing video: Video format not supported.". The video file it saves is OK and can played on a different device.

### Logfiles and additional information

From the mediaplayer:

```
virtual QSGVideoNode* ShaderVideoNodePlugin::createNode(const QVideoSurfaceFormat&)


** Setting GLConsumer instance:  0x16d7098


** Application is now active


void AalVideoRendererControl::onGLConsumerSet()


void AalMediaPlayerService::play()


Actually calling m_hubPlayerSession->play()


[DD 2018-06-09 11:49:42.291174] [player_stub.cpp:192@operator()] PlaybackStatusChanged signal arrived via the bus (status: PlaybackStatus::ready)


[DD 2018-06-09 11:49:42.505002] [player_stub.cpp:192@operator()] PlaybackStatusChanged signal arrived via the bus (status: PlaybackStatus::playing)


PlaybackStatus changed to:  "playing"


[DD 2018-06-09 11:49:42.591018] [player_stub.cpp:192@operator()] PlaybackStatusChanged signal arrived via the bus (status: PlaybackStatus::stopped)


[DD 2018-06-09 11:49:42.599127] [player_stub.cpp:204@operator()] Error signal arrived via the bus (error: Error::format_error)


** Media playback error:  2


PlaybackStatus changed to:  "stopped"


PlaybackStatus changed to:  "stopped"


qml: AbstractPlayer: 2:The media format type is not playable due to a missing codec.
```

From the camera app:

```
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::createFinished(): could not get thumbnail for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (32,32): ERROR


file:///usr/share/camera-app//GalleryView.qml:245:5: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::createFinished(): could not get thumbnail for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (32,32): ERROR


Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (299,299): FAILED PREVIOUSLY


Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (1920,1920): FAILED PREVIOUSLY


file:///usr/share/camera-app//PhotogridView.qml:169:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (299,299): FAILED PREVIOUSLY


file:///usr/share/camera-app//SlideshowView.qml:254:25: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180609_134930995.mp4 (1920,1920): FAILED PREVIOUSLY
```

**Comment by hoh61** [comment]
You may try the following approach:
open the video app, display all videos in the "my videos" view. Select your video and check the result. Accorging to my experience it is running or giving you a note on missing codecs. Since you took the video with the build in camera I expet that it would run.
Mediaplayer is highly buggy (as well as gallery as soon as videos are involved).

**Comment by hoh61** [comment]
Since I'm not so amused with the overall behaviour for media handling I started to dig through the mediascanner source. You have seen on your log that there are some codecs missing. Since all media activities are based on the database generated by the mediascanner this database has to be correct. If codecs are missing this will lead to problems with the data entries and subsequently with the playing of the media.
You may check the database in .cache/mediascanner-2.0/mediastore.db for the video entries. Videos (entry type = 2) can be played if width and height have values other than 0. Otherwise no suitable codec is installed. If this is OK, possible other playback issues are related to the used app!

**Comment by hoh61** [comment]
with the today update the video playback from the gallery app is working. The mediaplayer is still copying, and for each playable video a thumbnail is generated. 

I belive, upon more positive feedback this issue can be closed.

I have seen, that a lot of media libraries are provided, but I would like to ask for a proper way to have the mpeg2 codecs availabel on my device.

**Comment by NeoTheThird** [comment]
> I belive, upon more positive feedback this issue can be closed.

I think you're on the wrong issue. Video playback on the FP2 is still failing. You're looking for #614, right?

**Comment by rocky58** [comment]
on my OPO video playback is still failing.

**Comment by NeoTheThird** [comment]
@rocky58 Try now, the devel image always gets built at 7 AM UTC, so when you tried it was not there yet

**Comment by mariogrip** [comment]
gstreamer has a cache, this needs to deleted `rm .cache/gstreamer/*` then reboot and media player should work.

**Comment by Xray1970** [comment]
@mariogrip, i can confirm that it works after clear the cache and reboot on the Oneplus One.

**Comment by Flohack74** [comment]
Ok wait a sec I am testing. 3, 2, 1... No sorry, still the same.

**Comment by hoh61** [comment]
can you provide some information about the video you use for testing? size, codecs...

**Comment by Flohack74** [comment]
Yes I am on latest and I removed any files, but tbh I did not look before if anything was inside. Also, after trying to start the playback there is no file created in this .cache folder. Any example what I could find there (file name etc.)?

**Comment by hoh61** [comment]
Just a thought: you may remove the file .cache/mediascanner-2.0/mediastore.db, then restart your device. maybe the file information gathered by the mediascanner were buggy due to the upgrade. At restart this database will be generated automatically new and maintained !

**Comment by NeoTheThird** [comment]
I can confirm that this works both on bacon and FP2. On a clean flash, it works immediately.

> gstreamer has a cache, this needs to deleted rm .cache/gstreamer/* then reboot and media player should work. - @mariogrip 

Then we need a daemon that does that on upgrade. You can't expect users to read the whole tracker and look for commands to run! Btw, i think it should be `rm .cache/gstreamer*/*`, since the folder uses the version number for namespacing.

One problem is, that old videos can't be played back, only new ones. The log complains with `Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/video20180627_090749169.mp4 (1134,1950): FAILED PREVIOUSLY`. Removing the mediascanner database doesn't help.

**Comment by toehold** [comment]
Nexus 5 using Ubuntu 16.04 (2018-W26) I get this errors, when starting the Camera app:

tail -f .cache/upstart/application-click-com.ubuntu.camera_camera_3.0.2.log

```
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Import path added "/usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/lib/arm-linux-gnueabihf"
Camera app directory "/usr/share/click/preinstalled/com.ubuntu.camera/3.0.2"
virtual QMediaService* AalServicePlugin::create(const QString&) "org.qt-project.qt.mediaplayer"
[TT 2018-06-29 13:42:05.946048] [service.cpp:29@instance] 
[DD 2018-06-29 13:42:05.965174] [platform_default_sink.cpp:66@make_platform_default_sink_factory] Using hybris video sink
[TT 2018-06-29 13:42:06.183790] [player_stub.cpp:243@PlayerStub] 
virtual QMediaPlayer::State AalMediaPlayerControl::state() const 

virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

virtual void AalMediaPlayerControl::stop() 

[DD 2018-06-29 13:42:06.192573] [player_stub.cpp:192@operator()] PlaybackStatusChanged signal arrived via the bus (status: PlaybackStatus::stopped)
virtual void AalMediaPlayerControl::setMedia(const QMediaContent&, QIODevice*) 

setMedia() media:  QUrl("file:///system/media/audio/ui/camera_click.ogg")
virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

Setting media to:  QUrl("file:///system/media/audio/ui/camera_click.ogg")
mpris.Player.Error.UriNotFound: Warning: Failed to open uri file:///system/media/audio/ui/camera_click.ogg because it can't be found.
qq= QDeclarativeCamera_QML_37(0x11e2e08) 0x120b888
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.148\" (uid=32011 pid=12322 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3861 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.148\" (uid=32011 pid=12322 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3861 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.148\" (uid=32011 pid=12322 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3861 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.148\" (uid=32011 pid=12322 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3861 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
QObject::connect: No such slot AalImageCaptureControl::onPreviewReady()
Camera framerate boundaries are set by the backend
Camera framerate boundaries are set by the backend
PlaybackStatus changed to:  "stopped"
virtual void AalMediaRecorderControl::applySettings()  is not used
qq= ResponsiveGridView_QMLTYPE_90_QML_95(0x13f03b0) 0x13f2268
virtual QSGVideoNode* ShaderVideoNodePlugin::createNode(const QVideoSurfaceFormat&)
Rendering not enabled, returning without presenting frame
** Application is now active
[PERFORMANCE]: Last frame took 38 ms to render.
QFileSystemWatcher::removePaths: list is empty
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/MediaInfoPopover.qml:12:5: QML Item: Binding loop detected for property "height"
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/Popups/1.3/Popover.qml:250:9: QML Item: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/GalleryView.qml:70:5: QML OrientationHelper: All the parents must have an id.
State saving disabled for PhotogridView-photogridView:QQuickPinchArea-galleryViewPinch:_usr_share_click_preinstalled_com.ubuntu.camera_3.0.2_PhotogridView.qml:127:9:gridView, class OrientationHelper
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/AdvancedOptions.qml:86:17: QML Expandable: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/OptionsOverlay.qml:188:5: QML Information: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/OptionsOverlay.qml:188:5: QML Information: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/OptionsOverlay.qml:188:5: QML Information: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/OptionButton.qml:33: TypeError: Cannot read property 'value' of undefined
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/OptionButton.qml:24:39: Unable to assign [undefined] to QString
file:///usr/share/click/preinstalled/com.ubuntu.camera/3.0.2/SlideshowView.qml:405: TypeError: Cannot read property 'actions' of null
```

When taking a picture it takes quite a while to save it:

```
ext1: 0, ext2: 0 
	ext1: 0, ext2: 0 
virtual void AalMediaPlayerControl::play() 

void AalMediaPlayerService::play()
qml: Picture saved as /home/phablet/Pictures/com.ubuntu.camera/image20180629_154346857.jpg
[PERFORMANCE]: Last frame took 49 ms to render.
[PERFORMANCE]: Last frame took 46 ms to render.
[PERFORMANCE]: Last frame took 40 ms to render.
[PERFORMANCE]: Last frame took 37 ms to render.
	ext1: 1, ext2: 0 
** Application is now inactive
```

After that the camera picture freezes, to get it refreshed/active again I, I wipe through the apps list and return to the camera app.

**Comment by NeoTheThird** [comment]
@UniversalSuperBox Bump the ubuntu suffix version number

**Comment by NeoTheThird** [comment]
For the record, running `rm -rf .cache/mediascanner-2.0/ .cache/unity-thumbnailer/ .cache/gstreamer*/*` should show the previously recorded videos as well :)

**Comment by hoh61** [comment]
Just for the records: Mediascanner service is the background service which is constantly supervising the file system for new  files. It uses as a first instance the mime type of an file to device weather this is an media file, in a second instance it uses gstreamer to decide if it is a playable video.  These information are collected in a database in the cache area. During inquiry of the database the mediascanner checks for available thumbnails: for audio files this can be files provided in the file system like album pictures. All the found pictures as well as all video references will be processed through the thumbnailer process.
So these three services must be treated together in case of any update!

**Comment by luksus42** [comment]
I had the same issue on 15.04 (fresh wiped, coming from 16.04/RC) and cleaning the cache + reboot fixed it for me, too.

**Comment by JulienPeloton** [comment]
* device: nexus 5
* Channel: 16.04/devel
* build: 2019-W17

With the configuration above (this is my first time), I get exactly the same initial behavior:
```
No thumbnail in camera app. When opening mediaplayer, you get the error message: 
"Error playing video: Video format not supported.". 
The video file it saves is OK and can played on a different device.
```
And I also cannot play videos it in the gallery. I cleaned the cache (`rm -rf .cache/mediascanner-2.0/ .cache/unity-thumbnailer/ .cache/gstreamer*/*`) + reboot (several times), with no luck.

Anyone experiencing the same issue again?

**Comment by JulienPeloton** [comment]
Hum, it seems that it is a known issue: https://github.com/ubports/ubuntu-touch/issues/1092
Sorry for the duplicate!

**Comment by Flaburgan** [comment]
I experience this now with my FP2 but I think it was working a few weeks (month?) ago. I can't remember for sure.

**Comment by luksus42** [comment]
@Flaburgan so did you try to fix it with:
`rm -rf .cache/mediascanner-2.0/ .cache/unity-thumbnailer/ .cache/gstreamer*/*`
?
