### ISSUE TITLE
[xenial] Frieza update R92 is crashing device

### ISSUE THREAD

**Issue by hoh61** [ubports/ubuntu-touch#663]
### Illustrations

- Device:frieza
- Channel:16.04/devel
- Build:r92

### Steps to reproduce

Install upgrade (Ugrade was hold on boot-screen!!!)

### Expected behavior

running Ubuntu
### Actual behavior

Device is not starting up. Shows the ubuntu start screen and then shut down the device (ADB is still working)

### Logfiles and additional information

According to the log file the main reason is that unity 8 is crashing.
[syslog_update_r92.log](https://github.com/ubports/ubuntu-touch/files/2087641/syslog_update_r92.log)

**Comment by padraic7a** [comment]
I tried installing this on my Frieza.
"restart and install" brings me to recovery.
Note "installing Ubuntu update" text is static the last few minutes.

**Comment by hoh61** [comment]
I still can go into the boot menu and reboot the device. But the result is not different: after showing up the start screen the device shuts down.

**Comment by hoh61** [comment]
I tried it again with the command "wipe cache section" before, but still no improvement.

**Comment by padraic7a** [comment]
Hang on. I think my update did install. Multiple gallery, calendar and file manager apps are gone. Browser Next now works.
However the update still appears as ready to install.

**Comment by NeoTheThird** [comment]
There *might* be a issue with the delta upgrade, since we had quite a few changes in this one with moving core apps from deb to click. If you want to be sure you have the real deal, you can use the ubports installer to do a clean flash w/o wipe, then you should have a clean image.

**Comment by padraic7a** [comment]
Sounds like a plan. Great to see issues being resolved.

**Comment by hoh61** [comment]
I did a fresh setup for the device including wiping using UBports-installer. So device is running again  showing version r92, but:

- An update for the gallery app is annouced, it can be downloaded but the installation failed. Gallery app is not working, two versions installed.
- Camera app is not working
- SD card is not recognized when inserted

That's a first short feedback.

**Comment by hoh61** [comment]
Oh, and the list is continued:
after going to sleep and awake of the device the following issues were additionally found:
- WLAN setting forgotten: the device forgot which access point was used, the wlan was still active. After selecting the access point, the device connected to this point, the credentials were still remembered.
- open store unusable.The app started, but the content (icons) were not shown.

I restarted the device with the following results:
- SD card was found and is accessible
- Open store is usable 

I checked the bluetooth connection, which is well working at the beginning ....

**Comment by NeoTheThird** [comment]
@mariogrip Some issues introduced probably by the new click builder. Do you want us to split that up into separate reports, or do you want to take a shot at them before?

**Comment by hoh61** [comment]
In the meantime a positive feedback:
"The final countdown" was repeated over 5 times without having some issues with playback during device sleep over bloetooth.

By this I can confirm the closure of #651 as well as #600.

To complete my former set of apps I loaded the "tanken-App" from the open store. The app is opening but no settings are accepted.
I don't find the microphone recording app in the open store any longer. So I cannot find out if the microphone is actually working (formerly it wasn'T). Oh yes, and GPS is still not working.
What a useless brick.

**Comment by mariogrip** [comment]
@hoh61 Did you in modify the readonly rootfs before this happen? like example installing an apt package (like qtwebengine)

**Comment by hoh61** [comment]
@mariogrip , Yes, I tried to add some additional packages, mainly additional codecs trying to play several yet unsupported media formats. I played around unsuccessfully with the USB drivers, maybe some minor updates. But that was long before R92 (about r85 or so).

**Comment by hoh61** [comment]
@NeoTheThird :
How can I distinguish between the vivid and the xenial version? From apparmor the settings both installed versions (2.9.5 and 2.9.8) uses the policy group 1.3

**Comment by hoh61** [comment]
I repeated the initial setup (including wiping the device). The gallery out of the box is running (with the known problems). The provided gallery update from the open store is tainting the device.

**Comment by NeoTheThird** [comment]
@hoh61 
> How can I distinguish between the vivid and the xenial version? From apparmor the settings both installed versions (2.9.5 and 2.9.8) uses the policy group 1.3

It's not necessarily related to the policy group. 1.3 works both in xenial and vivid, but xenial also supports the new policy group `16.04`. What you have to look out for is the framework specified in the click manifest. If it is `ubuntu-sdk-16.04*`, it's a xenial-only app. If it's `ubuntu-sdk-15.04-qml`, it'll work on both. If it's `ubuntu-sdk-15.04`, it *might* work on both, but if it has any compiled components, it'll have to be specifically built for xenial or vivid. The OpenStore has separate channels for this purpose, but the click updater from the system settings doesn't respect that (yet, see #669).
