### ISSUE TITLE
[xenial] GPS not working on Pro 5

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#665]
- Device: Turbo
- Channel: 16.04
- Build: r91

### Steps to reproduce
1. Open uNav
2. Tap on hair cross
3. Allow permission to access GPS

### Expected behavior
Be granted access to GPS and finding a position

### Actual behavior
Error message: "GPE denied"

### Logfiles and additional information
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2089022/UTlogcat.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2089023/UTdmesg.txt)
![screenshot20180611_072147293](https://user-images.githubusercontent.com/13762919/41217997-ee051870-6d59-11e8-8b78-f56760ba6704.png)
![screenshot20180611_072120312](https://user-images.githubusercontent.com/13762919/41217998-ee1e7216-6d59-11e8-9e66-aa42538f1135.png)
![screenshot20180611_072114006](https://user-images.githubusercontent.com/13762919/41217999-ee37ed22-6d59-11e8-85a9-95777b468012.png)

**Comment by Marathon2422** [comment]
i have this on pro5 and m10 fhd , i assumed it would not be turned on until closer to 16.04 release date

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/libhybris/pull/5

**Comment by tomoqv** [comment]
Yay!

**Comment by tomoqv** [comment]
Will the fix be in the next devel, r99 for Pro5?

**Comment by Flohack74** [comment]
I guess so, yes.
