### ISSUE TITLE
[xenial] Wrong time in apps/pictures while correct in indicator

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#666]
- Device: Turbo
- Channel: 16.04
- Build: r91

### Steps to reproduce
1. Open System Settings Time & Date
2. Select Time zone Stockholm
3. Select "Automatic"

### Expected behavior
Time should display correctly in the indicator (which it does) and display correctly also in apps or as timestamp for e.g. pictures/screenshots (which it doesn't). Stockholm is UTC+2 during daylight savings time, but System Settings says UTC+0

### Actual behavior
Correct time in indicator and lock screen. Wrong time in apps and as timestamp for e.g. pictures

### Logfiles and additional information
![screenshot20180611_074140674](https://user-images.githubusercontent.com/13762919/41218774-7f129ba6-6d5c-11e8-8382-ae219b93d6a9.png)
![screenshot20180611_074116407](https://user-images.githubusercontent.com/13762919/41218775-7f2ee888-6d5c-11e8-8a4d-22efd2225562.png)

**Comment by tomoqv** [comment]
I notice now that when I search for "Stockholm" I get the following, but I can't select it.
![screenshot20180611_074921136](https://user-images.githubusercontent.com/13762919/41218863-dad42bda-6d5c-11e8-9cf1-3e4f693eec35.png)

**Comment by mariogrip** [comment]
Can you try to reset your timezone, since after https://github.com/ubports/systemd-packaging/commit/744063301a0a73501d8f62aa244f506c221edd8b  was changed and https://github.com/ubports/ubuntu-touch/issues/447 was fixed you will need to reset this so it gets saved on the readwrite paths.

**Comment by tomoqv** [comment]
I notice now that when I search for "Stockholm" I get the following, but I can't select it.
![screenshot20180611_074921136](https://user-images.githubusercontent.com/13762919/41218863-dad42bda-6d5c-11e8-9cf1-3e4f693eec35.png)

**Comment by tomoqv** [comment]
Ok, that fixed it. But I had to tap several times on Stockholm to get system settings to acknowledge.
