### ISSUE TITLE
[xenial] Pro 5 camera app broken since r91

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#667]
- Device: Turbo
- Channel: 16.04
- Build: r91

### Steps to reproduce
Tap on the Camera app

### Expected behavior
Camera launches

### Actual behavior
Camera hangs with a spinning wheel. Before r91 worked like a charm, both images and video.

**Comment by tomoqv** [comment]
r92 still broken.

**Comment by Marathon2422** [comment]
Updated to 
3.0.2
Touch the camera icon.   nothing happens

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/libhybris/pull/5

**Comment by tomoqv** [comment]
Yay no. 2!
