### ISSUE TITLE
[xenial] June 13 update does not boot

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#670]
If you install the June 13 delta update or do a clean flash, the device hangs in the Unity8 spinner. I will provide logs as soon as i find a device i can reach over adb.

**Comment by advocatux** [comment]
I can confirm this bug on BQ E4.5 (krillin) running 16.04 (r93)

**Comment by NeoTheThird** [comment]
Confirmed for M10, Nexus 5, Oneplus One and FP2. Here's last_kmesg from oneplus one: https://paste.ubuntu.com/p/RpSvQ2dvcV/

**Comment by NeoTheThird** [comment]
It might be this one: https://github.com/ubports/qtpim-opensource-src-packaging/pull/1

**Comment by Marathon2422** [comment]
same on  m10 fhd and pro5

**Comment by rocky58** [comment]
Me too, not me but my OPO. My single phone...

**Comment by NeoTheThird** [comment]
Fixed by moving back to old qtpim.

**Comment by rocky58** [comment]
For my OPO don't work, it reboot always into recovery mode!. Arghhhhhh...

**Comment by PhoenixLandPirate** [comment]
I did what you said, and my opo just boots into the ubports recovery page, rather than the os.

**Comment by Marathon2422** [comment]
Are you guys doing what it says,
Go into RECOVERY, ETC ETC. Not fastboot.
Just a thought

**Comment by NeoTheThird** [comment]
Thanks for reporting @PhoenixLandPirate and @rocky58. I can confirm this and created #673 for this.
