### ISSUE TITLE
OTA-numbers should be used consistently for all channels

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#671]
In system-image, it is possible to specify an OTA-number in addition to the build/revision number (like "r59") we use at the moment. For QA, it would be absolutely great if we could start using these consistently across all devices for all channels starting with OTA-4 (or actually starting asap on the 16.04/devel channel). The following structure would be practical in my opinion:

- devel: Date in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601): `2018-06-12`
- rc: Week-number and year in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601): `2018-W24`
- stable: The actual OTA-number `OTA-4`

This system would make it a lot easier to communicate when issues first appeared and to find out what builds they affect on what devices.

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/build-tools/commit/29dde6d357d5b47af9c46ab6020e1d2babeb9b91 and https://github.com/ubports/system-image-server/commit/a22187152f47e1d0354c3bc7b9b547c3bedc295f
