### ISSUE TITLE
[xenial] Oneplus One does not install update

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#673]
The Oneplus One image doesn't install due to out of space cache.

**Comment by rocky58** [comment]
No news yet... I'm without phone. Thanks

**Comment by Flohack74** [comment]
Just a reminder: The devel channel may break daily, and even render your device unusable. Do not use xenial on a daily driver where you have no backup.

**Comment by rocky58** [comment]
Yes, I know. I thinked that at this 16.04 stage these situations could not have happened. I was obviously wrong.

**Comment by mariogrip** [comment]
The image size has been reduced now, please check if this still is a problem. I tested with an opo 64GB version and that seems to install just fine, but im not 100% sure if these have different cache size then the white 16GB version

**Comment by NeoTheThird** [comment]
Works. Please always close issues immediately so they end up in the qa column. Makes testing easier.

**Comment by PhoenixLandPirate** [comment]
My opo still boots into recovery.

**Comment by Flohack74** [comment]
@PhoenixLandPirate did you install a new update with the installer?

**Comment by PhoenixLandPirate** [comment]
@Flohack74 Yeah I've tried a few times with the deb version, so I'm trying the flatpak version now

**Comment by PhoenixLandPirate** [comment]
It booted now, I dont quite get why, but its working now which is nice!
