### ISSUE TITLE
Camera BQ m10fhd

### ISSUE THREAD

**Issue by Marathon2422** [ubports/ubuntu-touch#675]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by Marathon2422** [comment]
M10fhd xenial r96
Camera app not working,it goes to first screen,
  black screen,camera icon and blue spinner , and no further

**Comment by doniks** [comment]
@Marathon2422 you should check your issue text again. You submitted an empty template :)

**Comment by hoh61** [comment]
This behaviour was introduced with frieza R92. Before this image the camera app was running as system tool, after that it is running as application.  I had the experience with two camera apps before R92, while the one running as app was behaving the same way you can find it now after R92, tainting the system. The system camera was available only after a reboot of the device as long as the app camera was not started.

**Comment by Marathon2422** [comment]
Re the template
On my pro5. I cannot get anything to happen there

**Comment by hoh61** [comment]
I had to re-flash my frieza with the actual image using the UBinstaller. Now the system version is 2018-W25 and nearly all services are running as expected, even the camera. However, I'm a little bit concerned that after each switch off of the tablet the camera app asks for granting access to the camera !?!
