### ISSUE TITLE
[halium-7.1] Switching to android-headers-24 and rebuilding libhybris

### ISSUE THREAD

**Issue by slp** [ubports/ubuntu-touch#678]
Switching to a LineageOS 14.1 base (halium-7.1) requires switching from android-headers-19 to android-headers-24, and rebuilding libhybris with the later. This leads to different, binary-incompatible packages, while the rest of the OS can work mostly untouched (a minor change to gstreamer-hybris is needed too, but that can be made compatible with ubp-5.1).

I'm not familiar with how the rootfs is constructed nor the way package dependencies are managed, but I suspect we'll end up needing two different variants. Is there a way to avoid that? If it isn't, how easy is keeping two different dependency sets for the rootfs image?

**Comment by NotKit** [comment]
libhybris is currently compiled against android-headers-24, so the issue can be closed. libhybris itself is backwards-compatible, so it is not an issue. Some other components like pulseaudio-module-droid do require keeping multiple versions compiled against different headers, which is not very neat, but is a separate issue to deal with.
