### ISSUE TITLE
Wakeup from notifications should not activate touch screen

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#682]
### Description of the feature
Every time the device wakes up for receiving/showing notifications there is a risk that with the enabled touch screen you do smth weird. Most of the time, when the phone is in my pocket, I start doing "PIN retries" with my body then, resulting in device locks. Or you could even dial emergency numbers etc...

**Comment by NeoTheThird** [comment]
I disagree. If you have the device laying on the table and get a notification, you might want to instantly unlock and reply. Having to lock and unlock again would be cumbersome.

**Comment by BlueKenny** [comment]
I agree with Flo, but we could make a option in the setting 'wake up screen notifications' = yes, no, or only if the phone is not in pocket (with light/ proximity sensor)

**Comment by Flohack74** [comment]
Maybe the sensitivity is too high, but I repeatedly locked my device with PIN errors, and then you have to wait for 5 minutes. Not cool if you want to look up a train or call someone :)

**Comment by kugiigi** [comment]
I agree on this. This happened to me a lot of times and sometimes when I unlock, I see a lot of apps open from my launcher. At least an option would be good and we can implement something smarter later on. How does Android handle this?

**Comment by hummlbach** [comment]
This seems to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/627 ;-)

**Comment by Flohack74** [comment]
Yes and no. 2 things happen, the screen turns on, and the digitizer gets active. So basically its not necessarily coupled together.

**Comment by hummlbach** [comment]
Yes okay, agreed. But hu... Wouldn't that be a bit counter intuitive, not accepting input while having the screen turned on?

**Comment by mateosalta** [comment]
it could be a more minimal show of the message, only the bubble message with black for the rest of the screen. or a de-saturated display of the screen

**Comment by Flohack74** [comment]
@hummlbach its not a duplicate: When the screen turns on and the proximity sensor shows _near_ the digitizer should not get active. I locked my phone multiple times in my pocket, opened apps or even tried to dial emergency. thats not accepatble.

**Comment by Flohack74** [comment]
I close this: The reason for the behaviour was Oneplus One´s broken proximity config, which I fixed last year or so at some point. The UX actually works fine, the screen is locked & blanked when proximity is NEAR and a new notification arrives.
