### ISSUE TITLE
Include QA scripts

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#688]
Include the fancy new (and still unpublished) [QA scripts](https://github.com/ubports/qa-scripts) in the base image.

**Comment by hoh61** [comment]
You should take care for the possible side effects. If you run apt update too often it will subsequently fill the cache on /var/cache/apt/ with large temporary reposiory binaries which will consume in short time a lot of the free available disk space on /. On my frieza the partition using for / (/dev/loop0) is terrible full. So using apt is sometims not possible (disk full)!

**Comment by Flohack74** [comment]
@mariogrip I can take this for initial package building: https://github.com/ubports/qa-scripts/tree/deb-packaging
