### ISSUE TITLE
[xenial] Cannot connect to VPN configured under Sytem Settings->VPN

### ISSUE THREAD

**Issue by arubislander** [ubports/ubuntu-touch#689]
### Summary
After configuring de VPN client in Ubuntu Touch to connect to my home VPN I cannot connect to my server.

- Device: frieza
- Channel: development/16.04
- Build: 99

### Steps to reproduce
Configure a VPN under System Settings->VPN with the same settings that are known to work under 15.04 (all channels).

### Expected behavior
When attempting to connect to the configured VPN, the VPN should connect, just like under 15.04 (all channels)

### Actual behavior
When the switch is toggled to ON for the VPN connection it immediately switches back to OFF and the notification is shown: 
`VPN Connection Failed
The VPN connection
'<name of connection> failed.`

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2112094/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2112095/UTlogcat.txt)

**Comment by NeoTheThird** [comment]
Awesome, thanks @arubislander.
