### ISSUE TITLE
Xenia calendar

### ISSUE THREAD

**Issue by Marathon2422** [ubports/ubuntu-touch#691]
### Illustrations

- Device:
- Channel:
- Build:

**Comment by Flohack74** [comment]
@Marathon2422 Please be more careful with filing your reports. This one is again empty. Are you looking for this bug? https://github.com/ubports/ubuntu-touch/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xenial+calendar => Please use the search function to see if you are filing a duplicate bug or not.

**Comment by Marathon2422** [comment]
I put the title in then it jumps,if i try to use the edit pencil,nothing

**Comment by Marathon2422** [comment]
Hey,Florian,sorry about the blank screen.
From my pro5, i put the title in,then i get the comment window,and no
opportunity to enter anything in the template.
I tried the little pencil in the top right corner,it highlights to show i
touched it,no more.
When i try to edit comments,from the three little dots/menu. I get to click
on the edit bar it highlights to show i touched it.and nothing else happens.
I figured this was not worth mentioning till after 16.04 release,
Colin

On Tuesday, June 19, 2018, Florian Leeber <notifications@github.com> wrote:
> @Marathon2422 Please be more careful with filing your reports. This one
is again empty. Are you looking for this bug?
https://github.com/ubports/ubuntu-touch/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xenial+calendar
=> Please use the search function to see if you are filing a duplicate bug
or not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Eyd2bxvyQHcD_Hkd108hAae5OD_XXeDDN-_L6cswAeQtK5eCP35wrpGbsviz7m-QTtQDw1n9PPLksVI5BsN2ryxPpiuMp8R36WRJ8XQEdfW3RLpkjJe55YnqNZF1pU2F5G3yMmTxG8pbi0Z_zbrnJR6qWR5n7g=s0-d-e1-ft#https://github.com/notifications/beacon/AdWVTF29pbKgt6UdPy-16SKCcKyaHFO8ks5t-P9AgaJpZM4Uthv2.gif>

**Comment by Flohack74** [comment]
Filing bugs from the device is not easy, since Githubs support on the mobile version sucks. Please use a desktop for that.

**Comment by Marathon2422** [comment]
No i was on 16.04 Dev on m10fhd,i used ubports-installer to  get RC,no wipe
Calendar comes on for 3-4 seconds then closes, on RC and Dev.
My pro 5 is on 16.04 Dev it does the same.

Google+. Apps,both of them close after a little use,
Ureadit   i get, the rendering process has been ended for this tab, frequently, browser related i guess.
Sorry for the delay, m10fhd and trying to fix nvram error,no luck,learned a lot about the flash tool tho
+

**Comment by Marathon2422** [comment]
calendar  app is working now on m10 fhd , i had it on android and flashed back to todays dev  2018-06-21  , so it had a really good wipe ,I will do the same with my pro5 ,and update this, soon

**Comment by Marathon2422** [comment]
After thoroughly trying /gallery / 2 google+ apps /uReadit ,I find everything is a lot smoother,and the blank screens and errors are not happening

**Comment by Marathon2422** [comment]
FYI
Wiped both devices, must of been junk in there, Much Better now

**Comment by Marathon2422** [comment]
well i spoke too soon  ,this is m10fhd and pro5 2018-06-21 dev.
Calendar APP             open app  it closes 3- 4 seconds
Google plus App Mateo Salta             open app   5-10 seconds goes to white screen
Google +  app Ruben Carneiro           open app    10 -12 seconds goes to white screen .
                                                                               oops something went wrong   RELOAD.
freshly wiped : i removed the Calendar app rebooted reinstalled, with google account Sync turned off 
still the same happening .
guessing this is a related problem between the apps  ?

**Comment by Marathon2422** [comment]
i cannot import /sync contacts in either device (google)  
pro5 and m10fhd ,
 could this be a related problem.

**Comment by Marathon2422** [comment]
BQ m10 fhd , I did a reset all, and then synced my google acc with Contacts app, worked ok, 
i then went to System accounts, and turned on sync Calendar ,
 then went Apps Scope ,opened Calendar app , it shut down after 3 seconds.
  i did open the apps to make sure they worked , but nothing else after the reset.

**Comment by hummlbach** [comment]
@marathon2422 I didn't get everything you wrote, but regarding the calendar I'm pretty sure you're experiencing the bug already mentioned by @flohack: https://github.com/ubports/ubuntu-touch/issues/656
Please have a look before filing an issue whether there is a bug report that possibly describes what you're seeing.

**Comment by Marathon2422** [comment]
I will close this as it is similar to another.

Just like to point out,that with a fresh install, the Calendar apps works, install other apps and sync,then it goes wrong.
