### ISSUE TITLE
[xenial] rc fails to boot on Meizu MX4 with luxembourg timezone

### ISSUE THREAD

**Issue by thepsr** [ubports/ubuntu-touch#696]
- Device: arale (Meizu MX4)
- Channel: 16.04/devel  and 16.04/rc
- Build: Ubuntu 16.04 (2018-06-19) and Ubuntu 16.04 (2018-W25)

### Steps to reproduce
* No SIM card (didn't test if this really matters)
* flash the device (with wipe)
* go through the setup steps (language, country etc.)
  EDIT: select Luxembourg timezone
* select reboot or power the device off and on again

### Alternative steps to reproduce
* No SIM card (didn't test if this really matters)
* flash the device (without wipe)
  EDIT: must be on Luxembourg timezone

### Expected behavior
* the device should start up again into ubuntu touch

### Actual behavior
* the device stops the boot process showing the normal meizu boot up logo
* It seems the device now and then reboots by itself when it is in this state

### Logfiles and additional information
System doesn't start up - don't know how to supply you with logs.

Also note that reflashing 15.04 is easily possible.

**Comment by NeoTheThird** [comment]
Is this an ubuntu edition MX4, or did you unlock it yourself? I heard that @cm-t had problems with his custom-unlocked Pro 5, so that might be the issue.

**Comment by thepsr** [comment]
It is an original Ubuntu edition with the little ubuntu logo in the boot up screen.
Also when I flash with wipe I have one successful boot.
Besides, the old 15.04 also still happily works.

**Comment by Voltcab** [comment]
Hello, same problem with an opo. it took 5 installations (16.04) to finally get started... Good luck !

**Comment by thepsr** [comment]
@NeoTheThird 
I tested the 16.04 flashing with a second device I have access to. Same result.
I can also now say that the presence of SIM or not is not relevant to the behaviour.

**Comment by NeoTheThird** [comment]
@Voltcab What do you mean "same problem"? Does it fail to boot after the first boot?

**Comment by thepsr** [comment]
I made some further tests by rebooting at different points of basic setup process.
This way I found out that booting is not working anymore after timezone setup.
I then first removed timezone settings with adb shell in the first boot. After this I was able to reboot successfully multiple times.
I then configured a different timezone. After this I could still reboot fine.
To crosscheck I configured the timezone I usually choose. The problem was back,

"Europe/Berlin" works but "Europe/Luxembourg" does not.

Just weird.

**Comment by thepsr** [comment]
On "Nexus 5" and "BQ tablet" as expected this setting has no influence.

I really wonder why this setting causes a crash on Meizu.

**Comment by NeoTheThird** [comment]
@Voltcab The installer verifies the downloaded files, so a bad internet connection should not matter. If you want to be sure, you could run `rm -rf ~/.cache/ubports ~/snap/ubports-installer/current/.cache/` to delete the cached files and install again. Also, please make sure you have the latest version of the stock android rom installed before installation, as the one it comes with when it's brand new (android 4.4 i think) does not work.

**Comment by Woody72** [comment]
I can confirm that Luxembourg time zone on mx4 stops boot up after normal boot message at bottom of screen. All was working fine on my normal time zone.
Lakotaubp
