### ISSUE TITLE
BQ Aquaris E5 2 sim cards  device reboots asking fro pass-code of second Sim 

### ISSUE THREAD

**Issue by prpldvl67** [ubports/ubuntu-touch#70]
Hi have been having this problem on my aquaris E5 hd. I have two sims and quite often the phone reboots asking for second SIM passcode. Any chance to sort it out. I have Sim 1 set as principal SIM

**Comment by Flohack74** [comment]
I also use 2 SIM cards and I never had this problem, not with Canonical, not with UBports... Any further details when it started to appear?

**Comment by prpldvl67** [comment]
Hi Florian had it since OTA 14  update.

**Comment by Flohack74** [comment]
Ok so about reboot: It really crashes? I mean you go black & then it comes up with boot animation? And then it asks only for 1 PIN? Or how?

**Comment by prpldvl67** [comment]
no it reboots with splash and asks for SIM 2 password

**Comment by simoxxx** [comment]
White bq splash screen?

**Comment by Flohack74** [comment]
Is this still an issue?

**Comment by prpldvl67** [comment]
good morning not now

**Comment by Flohack74** [comment]
I close this for the moment. No other confirmations so far.
