### ISSUE TITLE
[xenial] Libertine apps crash with "terminated with signal 11" on start

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#701]
Hello,
I've been trying to create a libertine container on a Xenial device to run some of the desktop apps on it.
While creating the container worked flawlessly for me I seem to be unable to launch any graphical apps in it.

That is I can get to the bash in it, I can launch cli apps in terminal but when trying to use ubuntu-app-launch to start graphical applications it just throws the following error:
`proot info: pid 4622: terminated with signal 11`

so for example I can try to launch Firefox:
`ubuntu-app-launch ubuntu_firefox_0.0`

and the log with the above error is then visible here:
`cat .cache/upstart/application-legacy-ubuntu_firefox_0.0-.log`

Thank you very much for looking into this.

------------

Btw, @dobey is running 15.04 container on Xenial and it seems to work for him:

> i created a container when i had 15.04 on my nexus 4, and installed xterm, and after upgrading to 16.04, i can still run xterm just fine from that container

(source: UBports Supergroup [ENGLISH], June 20, 10:45pm)

**Comment by doniks** [comment]
@zubozrout is that error the only entry in the log? If not, please attach the whole thing

FWIW, I saw some "signal 11" when I did lcm create. I found this, not sure it's the culprit: https://github.com/proot-me/PRoot/issues/112

Another thing I noticed is that the container has different apt sources than the rootfs. It adds the overlay here: https://github.com/ubports/libertine/blob/xenial/python/libertine/ChrootContainer.py#L137 
and it does not add the ubports repo

**Comment by zubozrout** [comment]
@doniks Actually it is - there is nothing else in the log :).

**Comment by dobey** [comment]
I think a "quick" fix for this would be to rebuild all the device kernels to not included the back-ported seccomp support, or to just rebuild with it disabled (CONFIG_SECCOMP=n). Or does anbox need seccomp enabled, to work?

**Comment by NeoTheThird** [comment]
> I think a "quick" fix for this would be to rebuild all the device kernels to not included the back-ported seccomp support, or to just rebuild with it disabled (CONFIG_SECCOMP=n). Or does anbox need seccomp enabled, to work?

Pinging @mariogrip

**Comment by mariogrip** [comment]
Fixed by importing an updated (and still maintained) proot https://github.com/ubports/proot/tree/xenial

@dobey libertine had seccomp disabled all together, but didn't see that after rebuilding a kernel without only find it still segfaults :) but it seems that there was some untranslated syscalls somewhere, but using an updated proot fixed it
