### ISSUE TITLE
No SIM detected message in system settings barely visible

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#704]
xenial rc, on fairphone2.
remove sims, go to System Settings -> Cellular
see the message there

**Comment by pixelr0** [comment]
https://github.com/ubports/system-settings/blob/xenial/plugins/cellular/Components/NoSim.qml

maybe change color from  color: UbuntuColors.lightGrey to black or sumtin

**Comment by Aury88** [comment]
isn't [UbuntuColors.slate](https://docs.ubuntu.com/phone/en/apps/api-qml-current/Ubuntu.Components.UbuntuColors#slate-prop) for the text color or [UbuntuColors.silk](https://docs.ubuntu.com/phone/en/apps/api-qml-current/Ubuntu.Components.UbuntuColors#silk-prop) for secondary text color? (ps i don't know how it look like after using those parameters )

**Comment by Aury88** [comment]
PR proposed for this: https://github.com/ubports/system-settings/pull/79
