### ISSUE TITLE
[xenial] Clock app crashes with sig 11

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#705]
- Device: bacon
- Channel: 16.04/devel
- Build: 2018-06-21

### Steps to reproduce

Open clock app. Watch it crash. Repeat.

This issue existed (unreported) a while back and was fixed when all the apparmor fixes came in, i have no idea why it's back. Weird things are happening in dmesg that science can not explain.

Since it's killed with signal 11, which should be a segfault (right?), i made sure it is the xenial version of the clock app.

Not reproducible on other devices.

### Logfiles and additional information

A big WTF from dmesg:

```
[  155.807816] type=1400 audit(1529601514.627:96): apparmor="DENIED" operation="sendmsg" profile="com.ubuntu.clock_clock_3.10.1" name="/dev/socket/logdw" pid=5881 comm="qmlscene" requested_mask="w" denied_mask="w" fsuid=32011 ouid=1036
[  155.808957] type=1400 audit(1529601514.627:97): apparmor="DENIED" operation="sendmsg" profile="com.ubuntu.clock_clock_3.10.1" name="/dev/socket/logdw" pid=5881 comm="qmlscene" requested_mask="w" denied_mask="w" fsuid=32011 ouid=1036
[  155.819982] type=1400 audit(1529601514.637:98): apparmor="DENIED" operation="sendmsg" profile="com.ubuntu.clock_clock_3.10.1" name="/dev/socket/logdw" pid=5881 comm="qmlscene" requested_mask="w" denied_mask="w" fsuid=32011 ouid=1036
[  155.848457] type=1400 audit(1529601514.667:99): apparmor="DENIED" operation="sendmsg" profile="com.ubuntu.clock_clock_3.10.1" name="/dev/socket/logdw" pid=5881 comm="qmlscene" requested_mask="w" denied_mask="w" fsuid=32011 ouid=1036
[  155.879928] type=1400 audit(1529601514.697:100): apparmor="DENIED" operation="open" profile="com.ubuntu.clock_clock_3.10.1" name="/usr/share/qt5/translations/qt_en.qm" pid=5881 comm="qmlscene" requested_mask="r" denied_mask="r" fsuid=32011 ouid=0
[  156.278819] type=1400 audit(1529601515.097:101): apparmor="DENIED" operation="sendmsg" profile="com.ubuntu.clock_clock_3.10.1" name="/dev/socket/logdw" pid=5881 comm="qmlscene" requested_mask="w" denied_mask="w" fsuid=32011 ouid=1036
[  183.692128] type=1701 audit(1529601542.517:102): auid=4294967295 uid=32011 gid=32011 ses=4294967295 pid=5881 comm="qmlscene" reason="memory violation" sig=11
```

**Comment by dark-eye** [comment]
this happen on turbo too, I'm investigating but have little free time lately so it will take some... hmmm.. time.

**Comment by advocatux** [comment]
I'm running 16.04 devel on krillin and the clock crashes as well (I'm using the xenial version of that app).

BUT I know one user who did Factory Reset after installing xenial and his clock doesn't crash.

**Comment by mariogrip** [comment]
This one is random af... it just *sometimes* crashes. 

for (it's fine for some days)  
   and then back to crashing;

**Comment by advocatux** [comment]
For what it's worth, I did a Factory Reset this morning just to see what happens and so far so good, the clock doesn't crash now.

BQ E4.5 (krillin) running Ubuntu 16.04 (2018-06-21)

**Comment by hummlbach** [comment]
I had the feeling that its related to the alarms... And i get the same stack trace as for the calendar all day event crash:
Thread 1 "qmlscene" received signal SIGSEGV, Segmentation fault.
0xb5fab296 in ?? () from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
(gdb) bt
#0  0xb5fab296 in ?? () from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#1  0xb5f6d7a0 in QDateTime::toMSecsSinceEpoch() const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#2  0xb5f70a34 in QDateTime::operator<(QDateTime const&) const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#3  0xae1b4992 in QtOrganizer::QOrganizerManagerEngine::compareVariant(QVariant const&, QVariant const&, Qt::CaseSensitivity) () from /usr/lib/arm-linux-gnueabihf/libQt5Organizer.so.5
#4  0xbed1eb78 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by hummlbach** [comment]
Or at least two alarms.

**Comment by nfsprodriver** [comment]
Nope, still no change on krillin (after reboot) Tested with click version.

**Comment by mariogrip** [comment]
You fix one thing another thing appears, Ok let's try again :)
