### ISSUE TITLE
[xenial] system settings main list does not remember the scrolling position

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#707]
xenial RC on Fairphone2
open System Settings app, scroll down (until you see Reset)
tap on Battery > then tap on back < Battery
the list in the main system settings in now scrolled up, the last entry is Notification
fix: don't reset the scroll position when you press back

**Comment by advocatux** [comment]
This is a duplicate of #634 
It has been moved to OTA-5

**Comment by pixelr0** [comment]
great. thanks!
