### ISSUE TITLE
[xenial]  lockscreen device name in wrong place 

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#710]
Bug Report

- Device: BQ M10 frieza
- OS: 16.04
- Channel: RC
- Build: version 101

### Steps to reproduce
Run 16.04 RC on Frieza (bq M10fhd) 

### Expected behavior
When on the lockscreen the device name (in this case 'M10') should appear in the text box. 

### Actual behavior
The device name appears outside the text box and is both difficult to read and unattractive. 
On the lockscreen the device name is above the text box. When prompted for a password it is pushed below the text box. 

### Logfiles and additional information
See images below. 

![Lockscreen withough passcode prompt](https://user-images.githubusercontent.com/3010391/41810937-bfabe536-76fe-11e8-993e-e1c0ff06ba04.jpg)

![Lockscreen with passcode prompt](https://user-images.githubusercontent.com/3010391/41810940-c553b072-76fe-11e8-89f4-c46fe87e102c.jpg)

**Comment by cibersheep** [comment]
Same happens in m10 Cooler

**Comment by cibersheep** [comment]
On Cooler (RC 2018-W47), the user name stays in the same place when OSK is shown:

![imatge](https://user-images.githubusercontent.com/6640041/48975422-be53d000-f06f-11e8-807e-df438433f10f.png)

![imatge](https://user-images.githubusercontent.com/6640041/48975429-dfb4bc00-f06f-11e8-8bb8-81251f29158f.png)

![imatge](https://user-images.githubusercontent.com/6640041/48975423-c6137480-f06f-11e8-8754-a3978f4fa9ad.png)

**Comment by Arc676** [comment]
Since this thread hasn't been updated in a while, I'd like to mention that this still happens on Nexus 7 (flo) `devel` channel running version `2019-05-04` (16.04).

**Comment by Aurnytoraink** [comment]
@Arc676 I confirm

**Comment by NeoTheThird** [comment]
Fixed in https://github.com/ubports/unity8/pull/194. Will be included in ota-11.

**Comment by padraic7a** [comment]
Great stuff

**Comment by padraic7a** [comment]
Hi, I have tested this on the development channel for the M10 and Nexus 5. Looks good.

**Comment by ziggutas** [comment]
Nexus 7 flo rc (2019-W41/2)
Fab to see the device name in the right place!!
