### ISSUE TITLE
/usr/bin/edit fails

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#711]
- Device: nexus 5 (hammerhead)
- Channel: 16.04/rc
- Build: 2018-W25

### Steps to reproduce
open terminal and type "edit test.txt"

### Expected behavior
suitable text editor comes up (vi or nano?)

### Actual behavior
Call fails with
`Can't locate Encode.pm in @INC (you may need to install the Encode module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/arm-linux-gnueabihf/perl5/5.22 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base .) at /usr/bin/edit line 12.
BEGIN failed--compilation aborted at /usr/bin/edit line 12.`

Just a minor problem, calling "vi" directly works fine.

**Comment by advocatux** [comment]
The default way to edit a file is to use the built-in Nano layout in Terminal.

See the Terminal tutorials here https://ubports.com/blog/ubports-blog-1/tag/blogs-2

**Comment by ruedigerkupper** [comment]
Nano and vi do work fine, and also the editor command. This report is about the edit command not working. It works fine in Ubuntu desktop, but fails on Ubuntu touch. The error message suggests that a Perl module is missing. It may affect other Perl code.
If it is intended that this module is not present on Ubuntu touch, feel free to close this issue.

**Comment by advocatux** [comment]
I misunderstood you then, sorry :)

**Comment by Flohack74** [comment]
I worked with Linux since 1993 but I never heard of this command. Interesting ;)

**Comment by advocatux** [comment]
Yes, it's one of the alias of `run-mailcap` IIRC

**Comment by UniversalSuperBox** [comment]
It appears that the package `libperl5.22` must be installed to run this program correctly, but the `mime-support` package which includes `run-mailcap` and `edit` does not depend on it. We do not have enough space in the root filesystem to include this package.

**Comment by Flohack74** [comment]
Sure this is a bug? I would not call it as such, and I think this would also be closed with wontfix for the time being.

**Comment by ruedigerkupper** [comment]
Agreed. It's a missing dependency we can't include. And a seldomly used command.
