### ISSUE TITLE
File manager not able to uninstall

### ISSUE THREAD

**Issue by strangerer** [ubports/ubuntu-touch#718]
### Description of the feature
 I downloaded a PDF file when I try to open it throught pdfjs app, file manager did not show up in suggest app to find directory. So I decided to uninstall and install it again to rectify it and file manager to show up in suggested app. 

But i cannot able to uninstall it and when I press and hold the file manager icon in app scope, there is no option to uninstall

### Illustrations

- Device: hammerhead
- Channel:16.04rc
- Build:

### Steps to reproduce
press and hold file manager for second to wait for options to appear

**Comment by ivoxavier** [comment]
I think this is related with this bug: 

https://github.com/ubports/ubuntu-touch/issues/496

**Comment by strangerer** [comment]
Nope this is different

**Comment by NeoTheThird** [comment]
Yes, it is. At the moment, the filemanager is installed as a deb package, we will be changing that shortly. That is why you can not uninstall it. As soon as it is installed as a click package, it will be possible to uninstall it, and the click hooks will execute, allowing you to use it with content-hub.
