### ISSUE TITLE
[Xenial] Hotspot not working

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#719]
- Device: bacon
- Channel: 16.04RC
- Build: 2018-W25

### Steps to reproduce
Turned off then on again several times

### Expected behavior
Hotspot turns on

### Actual behavior
Red indicator shows hotspot on but laptop wifi indicator shows nothing

**Comment by strangerer** [comment]
This issue also in hammerhead 16.04 2018-w25

**Comment by mariogrip** [comment]
So added https://github.com/ubports/wpa/tree/xenial to the images, hotspot seems to work now, but it's a bit funky so will keep it open for now. but please give it a test.

**Comment by mattbel10** [comment]
On Pro5 I confirm the Hotspot feature doesn't work at all, both if I set a password or not.
