### ISSUE TITLE
Displaying the percentage of battery status and remaining battery life.

### ISSUE THREAD

**Issue by Daniel20000522** [ubports/ubuntu-touch#720]
It would be good to add an on/off button to display the battery percent status and/or a separate button for the remaining battery life.

To display this information you must enter in the terminal:
- for battery percentage: gsettings set com.canonical.indicator.power show-percentage true
- for battery time: gsettings set com.canonical.indicator.power show-time true

It would be simpler for a new user.

**Comment by strangerer** [comment]
Use UT tweek tool

**Comment by J053Fabi0** [comment]
> Use UT tweek tool

What tool is that? Where can I find it?

**Comment by Daniel20000522** [comment]
You can find the UT Tweak Tool in the [OpenStore](https://open-store.io/app/ut-tweak-tool.sverzegnassi).

**Comment by pnguyen9** [comment]
It looks like the UT Tweak Tool is not available (yet?) on version 20.04 (OTA-1), although I admit it has been a wonderful app up to version 16.04 (OTA-25).

The new command to run in the terminal to display battery percentage is:

`gsettings set org.ayatana.indicator.power show-percentage true`
