### ISSUE TITLE
[Xenial] Openstore does not work after upgrade from 15.04 Stable to 16.04 RC

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#725]
- Device: Bq Aquaris E5 HD
- Channel: 16.04 RC
- Build: 2018-W26

### Steps to reproduce

1. Upgrade from 15.04 to 16.04 RC via ubports installer. 
2. After upgrade, open Openstore. Blank page is shown.
3. Remove Openstore.
4. Download xenial openstore click package from https://open.uappexplorer.com/app/openstore.openstore-team
5. Install click package from terminal emulator
6. Reboot the device. 
7. Now openstore works.

### Expected behavior
Openstore should also be directly updated to Xenial version if OS upgrade is done from 15.04 to 16.04 RC

### Actual behavior
Openstore does not work after upgrade from 15.04 to 16.04 RC

**Comment by NeoTheThird** [comment]
Should be fixed: https://github.com/ubports/ubuntu-touch/issues/694
