### ISSUE TITLE
[xenial] After 15.04 to 16.04 RC Upgrade, adb shell does not work once device is connected to Ubuntu desktop

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#726]
- Device: Bq Aquaris E5 HD
- Channel: 16.04 RC
- Build: 2018-W26

### Steps to reproduce

1. Upgrade from 15.04 to 16.04 RC via ubports installer.
2. Download any click package from Ubuntu Desktop
3. Enable Developer Mode
4. Connect device to Ubuntu desktop
5. Execute below command

`adb push /home/nikhil/Downloads/openstore.openstore-team_2.41_armhf.click /home/phablet/Downloads/`

6. Below message is shown. Device does not show any popup to trust the ubuntu desktop.
**_error: device unauthorized. Please check the confirmation dialog on your device._**

### Expected behavior
Device needs to show popup to trust the ubuntu desktop. Click package should be pushed to the device folder mentioned in the command.

### Actual behavior
Runtime error. Device does not show any popup to trust the ubuntu desktop.
**_error: device unauthorized. Please check the confirmation dialog on your device._**

**Comment by hoh61** [comment]
The message is telling you what to do: check your device: a pup-up window will appear the first after the setting of the developer mode. You have to allow the access once, then it will be remembered.

Maybe it should be highlighted in the operating instructions for the upgrade of the system and the  description of the adb tool in the ubuntu touch documentation.

**Comment by nikhilbhalwankar** [comment]
I know that. But the popup window did not come on the device. I tried rebooting. Still same issue persists.

**Comment by NeoTheThird** [comment]
Stupid question, but is your device unlocked? You don't get the authorization dialog on the lockscreen

**Comment by UniversalSuperBox** [comment]
Correct, the device needs to have a screen lock and be unlocked with the screen on when it is plugged in to the ADB server (your computer). I only have one device that shows this prompt (Nexus 7 2013 WiFi), but it works correctly both before and after the 16.04 upgrade.

**Comment by UniversalSuperBox** [comment]
That button is dangerous. -_-

**Comment by nikhilbhalwankar** [comment]
Screen is already unlocked when I tried to connect to Ubuntu Desktop. Please note this. The issue persists even after screen unlock.

**Comment by Flohack74** [comment]
The popup for the developer mode might only come when you have assigned a PIN code or password, did you do this? Otherwise I also cannot reproduce this. I upgraded my OPO and adb worked as usual.

**Comment by nikhilbhalwankar** [comment]
I have PIN set for device but still I don't get popup.

**Comment by advocatux** [comment]
I can NOT reproduce this issue with a BQ E4.5 (16.04 devel)

@nikhilbhalwankar are you still having this issue? Have you tried to first kill the adb server, and then start it, instead of going to the `adb push` command directly?

If you restart your adb server, what's the output of `adb devices` when you plug your phone?

Have you tried to remove `/data/misc/adb/adb_keys` in your phone to force it to ask for the keys again (the trust pop-up)?

**Comment by mariogrip** [comment]
Since this not reproducible by others I will move it out of the backlog for now, Please test again and see if it's still an issue or if it's fixed in newer version.

**Comment by nikhilbhalwankar** [comment]
After installing latest update, the issue is now resolved. I am now able to connect to adb shell. Thanks !
