### ISSUE TITLE
[xenial] WiFi turns ON automatically

### ISSUE THREAD

**Issue by strangerer** [ubports/ubuntu-touch#731]
### Illustrations

- Device: hammerhead
- Channel:16.04
- Build:2018-w26

### Steps to reproduce

Setting-> cellular->cellular data

### Expected behavior

Should ON only when I toggle the WiFi button

### Actual behavior
 when I turn ON data , sometime the WiFi turns ON by itself

Edit1: WiFi turn on when I boot up or boot up by restart

**Comment by strangerer** [comment]
I found the problem
WiFi turns on when I boot up or boot up by restart

**Comment by UniversalSuperBox** [comment]
I can confirm this. The interface shows an incorrect state for the Wi-Fi hardware. If you

1. Boot phone
1. Turn off Wi-Fi in the interface
1. Reboot the phone

Wi-Fi shows as turned on. Strangely, it appears that NetworkManager attempts to connect to an AP in range and succeeds, but that connection goes into the void. Running `rfkill list` shows that the Wi-Fi device is soft blocked. It is impossible to bring the device back to a functioning state using the UI. The only way I've found to get Wi-Fi working after this starts is to run `rfkill unblock` on devices 0 and 1.

**Comment by j2g2rp** [comment]
Maybe it's related.
In the case of the bluetooth in krillin it's the opossite.
Turn on bluetooth--> reboot--> bluetooth will be off at restart. In vivid the status of the wifi and the bluetooth at restart was the same as them were before the reboot, wasn't it?
In M10FHD it works as spected, restoring the status that they had before the reboot.
If I should file a newbug don't hesiate in ask for it.

Regards.

**Comment by ruedigerkupper** [comment]
Confirming. Besides rebooting I found this way of recovering:
- switch to flight mode
- switch it off again
- switch off wifi
- switch it on again
It seems to bring back WiFi most of the time.
Anyway, it's a bug.

**Comment by UniversalSuperBox** [comment]
This was fixed by Canonical in urfkill by syncing its state on every boot. I've spent today trying to get the darn thing to build, but there's something about it that Jenkins just doesn't like... The adventures can be tracked in https://github.com/ubports/urfkill-packaging/tree/xenial_-_urfkill-build.

I was able to get it to build locally with several hacks, that did fix the issue upon installation. Just gotta get that package to build.

**Comment by UniversalSuperBox** [comment]
This should be fixed in https://github.com/ubports/urfkill-packaging/pull/1. As soon as the next devel build comes out (2018-07-12), please test with these steps again. It may be essential to turn airplane mode on and off to clear the state for urfkill, but it should work after that.
