### ISSUE TITLE
Anbox page does not indicate how endusers can install extra APKs onto into AnBox on UbuntuTouch

### ISSUE THREAD

**Issue by paul-hammant** [ubports/ubuntu-touch#732]
https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html is the page in question.

I would be better if it had one more paragraph showing how end users can install further APKs they have have locally on the host computer (Mac, Windows machine, etc)

```
adb shell
sudo mount -o rw,remount /
????
```

I tried to use the regular UbuntuTouch browser to open an APK online, it wants to know what application can handle that file suffix, it only offers [OpenStore](https://open.uappexplorer.com/app/openstore.openstore-team) as a choice, and that does nothing discernible with the APK.

I also see the WebViewShell icon on the UBtouch apps page. If I click that nothing happens. I think that's supposed to be an Android browser (WebKit?), but nothing happens when I click it.

**Comment by padraic7a** [comment]
Hi @paul-hammant, I managed to install some other apps by first installing f-droid. I did that by following the advice here: https://forums.ubports.com/topic/914/installing-additional-android-app-s-in-anbox-on-ubuntu-touch/10
That said anbox apps aren't working for me a the moment on Xenial.

**Comment by UniversalSuperBox** [comment]
Information has been added to the documentation
