### ISSUE TITLE
Browser Next: Some links do not open

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#733]
- Device: hammerhead
- Channel: 16.04 RC
- Build: W26

### Steps to reproduce
Go to startpage.com and search for something. Click the result links. Observe that nothing happens.
Do the same on Google.com. Observe it works.
It is not specific to startpage.com, happens on other sites, too.

**Comment by hummlbach** [comment]
Confirmed with mako 16.04 RC.

**Comment by ruedigerkupper** [comment]
Thanks, didn't know it has its own tracker.
