### ISSUE TITLE
Browser (classic) breaks on loading pages.

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#734]
- Device: hammerhead
- Channel: 16.04 RC
- Build: W26

Since W26, on some pages, browser stalls while loading, after a while error message appears saying that loading of that tab was interrupted. Re-trying does not help.

**Comment by hummlbach** [comment]
Hi Ruediger, thanks for reporting but this wont be fixed. The work will go into browser next instead. See  #653 and #626. As well as yesterdays Q&A.

**Comment by ruedigerkupper** [comment]
Right, thanks.
