### ISSUE TITLE
Calculator app welcome guide

### ISSUE THREAD

**Issue by strangerer** [ubports/ubuntu-touch#737]
### Illustrations

- Device: hammerhead
- Channel:16.04
- Build:2018-w26

### Steps to reproduce

Appscope ->calculator
### Expected behavior

At first time the calculator app run through guide of features and tutorials

End at a slide "ok or finish"

### Actual behavior

There is a empty slide at end of slides

I have to press the "skip" button in previous slide to force close the slide and get to calculator

**Comment by balcy** [comment]
was it OK to do the PR against the xenial branch, or is it needed in the main branch of calculator-app ?
