### ISSUE TITLE
[xenial] Dialer Frozen

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#739]
- Device: oneplus one
- Channel: 16.04 RC
- Build: 2018-W26

### Steps to reproduce
Dialer screen seems frozen after ending a call

### Expected behavior
Dialer screen to go away after ending a call. 

### Actual behavior
screen frozen

**Comment by GI9VANNI** [comment]
On my Nexus 5 with 16.04 devel, the dialer crashes after a call.
I've just uploaded a video to show the problem: https://youtu.be/hMVXNpEVFoI

**Comment by hummlbach** [comment]
@GI9VANNI In the description you wrote oneplus one, but in the comment you've written nexus 5... So which one? Or both?

**Comment by Dave1152000** [comment]
Seem to be problems with dialer on both.

**Comment by GI9VANNI** [comment]
@hummlbach The author of this post, that is @Dave1152000, has problems with the Oneplus One.
I have the same problem on my Nexus 5, in addition to [what I have already reported previously.](https://github.com/ubports/dialer-app/issues/36)

**Comment by Flohack74** [comment]
I currently cannot reproduce this on hammerhead. I tried here a few calls, none of them froze or crashed the dialer.

**Comment by BlueKenny** [comment]
Same for my Bacon.. I think i never hat this problem (16.04 rc and 16.04 dev)

**Comment by GI9VANNI** [comment]
Usually problems occur with short numbers, like 3 digits.

**Comment by Flohack74** [comment]
Hmm I never dial that short numbers, whats the use case :) - unless you call 112 for emergencies. That would be bad if the dialer freezes then...

**Comment by NeoTheThird** [comment]
It crashes *after* the call, though, right?

**Comment by GI9VANNI** [comment]
Yes, right.

**Comment by Dave1152000** [comment]
Seems to be working better after update to Week 28 on my Oneplus One

**Comment by NeoTheThird** [comment]
Ok, so since it only happens after the call, i would not see this as critical. Annoying, yes, but not critical. Can someone provide the dialer-app log from directly after the crash, and maybe also dmesg?

**Comment by NeoTheThird** [comment]
You can use [logviewer](https://open-store.io/app/logviewer.neothethird) for the dialer log, but for dmesg you'll need [this guide](https://docs.ubports.com/en/latest/contribute/bugreporting.html#dmesg).

**Comment by Flohack74** [comment]
I am afraid this will not appear in dialers log, but rather needs ofono log. Which I tend to forget where it resides ;)

**Comment by Flohack74** [comment]
BTW can´t test with 3-digit telephone numbers, we dont have any in my network...

**Comment by GI9VANNI** [comment]
@Flohack74 Do not you have a telephone operator's customer service or an answering machine with 3 digits?

**Comment by Dave1152000** [comment]
3 number answer machine works on my OPO on UK GIFFGAFF network.

**Comment by Flohack74** [comment]
@GI9VANNI No, my Mailbox is 22 :D

**Comment by jonnius** [comment]
At least in germany there is 115 for calling local government offices. Should be fine for testing 😉

**Comment by Flohack74** [comment]
@jonnius I am from Austria ;)

**Comment by jonnius** [comment]
I tested this with 3 digit numbers and cannot reproduce it on FP2 16.04/devel. @Flohack74, oh, my bad. :D

**Comment by Flohack74** [comment]
Sadly to say I had 2 times now that I could not close the dialer:

* after having call-waiting and switched to the newly incoming call
* after a normal call

Dialer did not accept any input anymore, but had no chance to cut logs.

**Comment by GI9VANNI** [comment]
I had to use my Nexus 5 as first phone last week, so I installed the 15.04 stable: the phone was perfect. I almost did not remember how good the 15.04 on this device!

Now I installed the last 16.04 dev and the problem is back. So I can confirm that the hardware of my device works well and unfortunately the issue only occurs with the 16.04.

In reality, this is the second of a series of three sequential problems that occur in this order:

1. https://github.com/ubports/dialer-app/issues/36
2. The issue dealt with on this page
3. https://github.com/ubports/ubuntu-touch/issues/709

I am only a user who is passionate about technology and although I have studied a bit of programming I can not solve these problems.
However, I hope to be able to help you make the Nexus 5 usable with xenial just like vivid.

**Comment by rocky58** [comment]
I have not only dialer freeze but also soft reboot when I'm speaking on phone and receive a second call. Ending first call, if I want to answer to a second call system reboots

**Comment by GI9VANNI** [comment]
@rocky58 Same for me.

**Comment by lduboeuf** [comment]
might be related: https://github.com/ubports/ubuntu-touch/issues/195

**Comment by lduboeuf** [comment]
@Dave1152000 do you still have that issue ?

**Comment by lduboeuf** [comment]
I close that issue since we have no news
