### ISSUE TITLE
Wrong translation - Battery Lock when idle

### ISSUE THREAD

**Issue by toehold** [ubports/ubuntu-touch#742]
- Device: N5
- Channel: 16.04 Devel
- Build: 463

### Steps to reproduce
Using English UK language

### Expected behavior
Under Battery: Lock when idle: Never

### Actual behavior
Under Battery: Lock when idle: Aldrig

This is the Scandinavian word for Never.

**Comment by Flohack74** [comment]
You can find all translations on https://translate.ubports.com - if you want to contribute, create and account, go into the Search option, and search for Aldrig. Then you can fix it ;)

**Comment by toehold** [comment]
Fixed it, thanks.

**Comment by toehold** [comment]
Yes will do. Is the GB po being used? I found e.g. Dialpad tones, but the translation was Dialpad sounds.

**Comment by Flohack74** [comment]
Hmm it should be used.

**Comment by Flohack74** [comment]
Maybe en_GB is not used at all. Can you select it on first time setup properly? That would explain why no one was ever complaining about the wrong translations ;)

**Comment by toehold** [comment]
I reset N5 and selected English (UK);

**Comment by Flohack74** [comment]
Ok I will check how the system settings are built right now...

**Comment by toehold** [comment]
I check all en_GB: address-book-app,calculator-app,calendar-app,camera-app,Ciborium (Removable Media,clock-app,dialer-app,docviewer-app,filemanager-app,gallery-app,messaging-app,music-app,
Printing App,system-settings,telegram-app,terminal-app (locked),UI Extras,weather-app)
I could not update the terminal-app, because it says: This translation is currently locked for updates!
The rest is all ok. Strangely on github I don't see that the en_GB.po are updated, how does this work?

**Comment by Flohack74** [comment]
Weblate is asynchronous, that means, only once per week the files are pushed. Currently it has strange issues with the cron job so I need to take a look. But I am doing manual pushes from time to time ;)

The terminal app is locked on purpose, I managed to damage the local git repo and need to make kind of repair, or loose translation data which I want to avoid.
