### ISSUE TITLE
Introductory tour is too slow 

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#746]
- Device: Frieza, Hammerhead
- Channel: Devel
- Build: 2018-07-04

### Steps to reproduce
Wipe and reinstall Ubuntu Touch

### Expected behavior
The introductory tour should proceed once you have configured your account. One instruction / hint should follow briskly after another.

### Actual behavior
The first instruction [swipe from the Left edge] doesn't occur for aprox 30 seconds. It could be confusing for a new user because it isn't clear what triggers it.
Subsequent instructions occur after a delay.

### Logfiles and additional information
Is there something useful I can provide here?

**Comment by Flohack74** [comment]
This is from old Canonical times, and yes, it is very annoying...

**Comment by padraic7a** [comment]
I'm glad you think so - I was a little worried that I was being overly picky.

**Comment by Flohack74** [comment]
This is not a xenial problem or regression, so please do not tag it, thx!

**Comment by AlexanderPlaza** [comment]
I wonder if it would be possible to put the introduction steps into an app. That way people can view it anytime they want... Useful for when technicians or someone helps someone setup their phone.

Plus I've seen this same behavior occur with the phone codename Bacon (OnePlus One).

**Comment by Flohack74** [comment]
@NeoTheThird shall we make this part of the ubports-app? I mean even if the tour is probably injected in unity, we could trigger it from the App. Because now its really PITA.

**Comment by NeoTheThird** [comment]
I'd put a pin in this until we move to (or at least experiment with) the latest version of Unity 8 after OTA-4.

**Comment by padraic7a** [comment]
Brilliant :smiley:
