### ISSUE TITLE
[xenial] Libertine apps do not show up in the "Legacy Applications Scope"

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#748]
- Device: Nexus 5 (hammerhead)
- Channel: 16.04 RC (W27)
- Build:

### Steps to reproduce
Create libertine container via system settings (using defaults, which will create a container called "xenial" with no user password set). Install some packages (I tried emacs, libreoffice, firefox).

### Expected behavior
When you go to the Legacy Applications Scope the icons of the installed apps show up.

### Actual behavior
Legacy Applications Scope is empty.

### Logfiles and additional information
I can still launch the applications from the command line using "ubuntu-app-launch". (However, most of them crash: Emacs works, Firefox starts up but displays a crash message, libreoffice crashes. But these are probably not related to this bug report.)

**Comment by pixelr0** [comment]
same on fairphone2, 16,04 rc v3

**Comment by padraic7a** [comment]
Same on BQ M10, 16.04, 2018-07-07

**Comment by Dave1152000** [comment]
Same on my OPO but have managed to start Thunderbird from terminal.

**Comment by ShadowEO** [comment]
Flo as well, Container installs properly, application installs properly. But no applications become surfaced in the Home scope or the Libertine scope.

Attempting to launch LibreOffice (as previously stated by others) failed using u-a-l, though I may not be using the right command to attempt.

**Comment by mattbel10** [comment]
Confirmed same behaviour on Meizu Pro5.

**Comment by ruedigerkupper** [comment]
Interestingly, libertine apps do show up in the content hub.

Am Samstag, 21. Juli 2018 schrieb mattbel10 :
> Confirmed same behaviour on Meizu Pro5.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/7o5iLbMgs1wutCivHxrb4yTkQYm2vklk9P4PbkNG56TNepPaXfBx4L8D1o8U90S-4xaaudEiwds7vmMh_twMOSfypqhliq2KOXU5nYI7bflQaTkEa6IKmNjsNv3STK8AI7FdkUcN4waGlz_r0nLGqtRwdHnGGA=s0-d-e1-ft#https://github.com/notifications/beacon/AUMSlqcxe5FRIWN4SAbFl-QNeLvKBMH_ks5uIukmgaJpZM4VGRuW.gif
>

-- 
Dr. Rüdiger Kupper
Forststr. 3
72250 Freudenstadt

**Comment by NeoTheThird** [comment]
Closed in favor of #782.

**Comment by mariogrip** [comment]
As a bonus while i was working on the other (#782), this got fixed. \o/
Next devel will include this

**Comment by ruedigerkupper** [comment]
Great!! Couldn't test it, the scope is gone...
Waiting for #782...

**Comment by ruedigerkupper** [comment]
Sorry, no.
As of W30, the libertine scope (known as „legacy apps“, with a hat symbol) is gone.
I can provide sceenshots if really required.

**Comment by ShadowEO** [comment]
@ruedigerkupper You can install the older scope by setting your image to writable and installing the libertine-scope package, but it doesn't do anything at the moment. Just sits there empty regardless of if you have applications in the container or not. But I don't think it was ever included with the OS, I believe it was always a separate installation (either from the Ubuntu Store or from APT).
