### ISSUE TITLE
[xenial] webapp-container does not work in terminal

### ISSUE THREAD

**Issue by tatonuta** [ubports/ubuntu-touch#750]
- Device: Bq Aquaris E4.5 - Krillin
- Channel: 16.04 RC
- Build: 2018-W27

### Steps to reproduce
Open terminal and write: webapp-container http://www.ubuntu.com

### Expected behavior
The www.ubuntu.com webpage should appear. 

### Actual behavior
An error message appears:

> Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0.'
> UbuntuClientIntegration: connection to Mir server failed. Check that a Mir server is running, and the correct socket is being used and is accessible. The shell may have rejected the incoming connection so check its log file.
> Aborted. 

![screenshot20180707_022527488](https://user-images.githubusercontent.com/40709402/42410869-7cac24dc-81f1-11e8-9b83-1b2fb8eddf29.png)

**Comment by tatonuta** [comment]
The same error message appears when I write:

$ webbrowser-app

in terminal.

**Comment by mardy** [comment]
You'll find a similar error when launching any Qt application :-)

You need to start them as

    webapp-container --desktop_file_hint=/usr/share/applications/webbrowser-app.desktop http://www.ubuntu.com
