### ISSUE TITLE
/etc/default/locale is always set to en_US.UTF-8

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#751]
- Device: tested on krillin and hammerhead
- Channel: both vivid and xenial
- Build: all

### Steps to reproduce
See the content of `/etc/default/locale`

### Expected behavior
That content should match the real `locale` you have set on your device

### Actual behavior
The content of that file is not the real `locale` on your device but it's always `en_US.UTF-8`

### Logfiles and additional information
Connect your device with `adb` and using `adb shell` consult `locale`.
You'll get the wrong info when your device is set to any other language that is not "American English".

**Comment by dobey** [comment]
This is a problem not with the contents of `/etc/default/locale` as changing the locale setting does not alter this file (and I'm not sure this file is even in writable space on UT). Rather, the issue here is that `adb shell` does not give a login shell, and so your configured environment is not fully used. If you connect instead via `ssh` or `phablet-shell` (which does ssh over adb), then the locale is as expected.

**Comment by advocatux** [comment]
@dobey yes, that's right, `adb shell` doesn't look to `/home/phablet/.pam_environment` but to `/etc/default/locale` and that's is always set to en_US.UTF-8, and as you said, it's a non-writable file.

If I'm understanding correctly the issue, it doesn't have an easy solution because the user should be able to select the system locale by default during the UT installation process, not just for the user space, and every image update have to honor that selection.

Anyway, I just wanted to document this because it's an issue for non-American-English users.

**Comment by Flohack74** [comment]
Well @advocatux ADB is not meant to be a normal access method for the phone, not even in Android. Its a debug bridge, so limitations occur. Thats why phablet-shell exists ;) and yet better, we should promote more ssh access, as this will also work via WiFi then.

**Comment by Flohack74** [comment]
Yes for the moment I close this as wontfix :)
