### ISSUE TITLE
Libertine Manager won't parse package names if first character is uppercase

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#753]
- Device: BQ M10
- Channel: 16.04 devel
- Build: 2018-07-07

### Steps to reproduce
In the Libertine section of System Settings I want to install ruby-dev.
Within my chosen container I open the dialogue to "Enter package name or Debian file" 
I enter "Ruby-dev" (the keyboard is set to capitalise the first character) and press "Enter"

I believe the problem is that Libertine cannot parse the filename when the first character is capitalised (testing shows that installing "ruby-dev" works fine).

### Expected behavior
When I try to install "Ruby-dev" ruby-dev should be installed.
If there is a problem installing a package there should be an error message.

### Actual behavior
Ruby-dev appears momentarily as one of the apps with the spinning blue wheel and then disappears.

### Logfiles and additional information
This image is from /var/log/apt/history.log
On Libertine (Systems Settings) I tried to install the following packages in order: ruby, Ruby-dev, ruby-dev
The history log shows that ruby and ruby-dev were installed. It doesn't mention Ruby-dev so the string wasn't parsed / passed to apt in the libertine container.

![apt_history](https://user-images.githubusercontent.com/3010391/42414102-3647ea96-8226-11e8-8872-7658a89b93c3.jpg)

**Comment by NeoTheThird** [comment]
This should be a fairly simple fix, sanitizing the input and making it all lowercase should be enough, since all packages have lowercase names.

**Comment by NeoTheThird** [comment]
Fixed in https://github.com/ubports/libertine/pull/8
