### ISSUE TITLE
[xenial] External Drives GUI app doesn't allow external media to be unmounted

### ISSUE THREAD

**Issue by TartanSpartan** [ubports/ubuntu-touch#755]
- Device: arale
- Channel: Xenial RC
- Build: 2018-W27

### Steps to reproduce
* For MX4's case, plug in external media using USB OTG cable
* Go to External Drives app
* Go to drive you wish to unmount
* Touch "Safely Remove" button 

### Expected behavior
* "Confirm Remove" prompt followed by (if you press continue) "Unmounting" (stating "You can now safely remove the device" and offers an OK button) and push notification indicating that the storage device has been removed

### Actual behavior
* "Safely Remove" button is unresponsive. Device must be powered down to be assured of a safe unplug of the storage media for a clean unmount

**Comment by TartanSpartan** [comment]
On top of that, I don't know if the "Format" option works either. I didn't test because clearly I don't want to wipe a good SD card, but if I get a burner card I can try it out.

**Comment by TartanSpartan** [comment]
From memory, this wasn't an issue on arale 15.04, no. I don't have much time to flash to and from to test though. If someone else could test if it was an issue with Vivid, or if the issue is present on other devices in RC Xenial, that would be great.

**Comment by TartanSpartan** [comment]
Confirmed for turbo and cooler on 16.04 channels, including for their integrated SD card ports.

**Comment by UniversalSuperBox** [comment]
Oh look, GitHub didn't close this automatically.
*grumble grumble*

This was fixed by https://github.com/ubports/ciborium/pull/12

**Comment by Flohack74** [comment]
I think you cannot close with commit messages across different repos?

**Comment by NeoTheThird** [comment]
yes you can @Flohack74, even across different orgs. In this case it didn't work, because the PR was squashed and the "fixes issue #blahblah" wasn't in the commit message. https://github.com/ubports/ciborium/commit/771dfdf7814ba872f7ecd53cf337cbe492f9ed75
