### ISSUE TITLE
Calendar events from remote server skewed in time

### ISSUE THREAD

**Issue by ricmm** [ubports/ubuntu-touch#760]
Bug:

- Device: All
- Channel: 16.04/devel
- Build: latest

### Steps to reproduce
Import a remote CalDav

### Expected behavior
Events are imported according to the phone's timezone

### Actual behavior
Events are skewed X hours from the original event time, the skew is exactly the difference with UTC

---

Investigation from @mardy shows that EDS is reporting the timezone to the upper layers on a new format, which is not taken well by Qt's datetime implementation, thus it's considering it UTC and adjusting +/- for local timezone.

**Comment by mardy** [comment]
EDS returns the timezone in a format like this:

    /freeassociation.sourceforge.net/Tzfile/Europe/Helsinki

but `icaltimezone_get_builtin_timezone_from_tzid()` fails to parse it and returns `NULL`. From a quick search in the internet it looks like this `/freeassociation.sourceforge.net` is the default prefix used by libical, so it's weird that it doesn't recognize it.

**Comment by tomoqv** [comment]
Well done, it works now!
