### ISSUE TITLE
Nexus 5 - Stuck after Installation

### ISSUE THREAD

**Issue by neshby** [ubports/ubuntu-touch#764]
Hello,

Just installed Ubuntu Touch on my Nexus 5 D820(H) HammerHead.

The installation completes successfully but instead of loading the OS, it goes back to recover mode.
Restarting the phone , causes a loop at the Google Logo.

Using windows installer 0.1.2 as the previous version gave an error.

**Comment by NeoTheThird** [comment]
Please use the [latest version of the installer](https://devices.ubuntu-touch.io/installer/exe). If the problem persists, please use the installers bugreporting feature, so we can see what is going on exactly.

**Comment by neshby** [comment]
Hello,

I did use the latest version of the installer. The installer says the
installation is successful. But on my Nexus 5 , after it installs it goes
back to recovery mode. When I restart the phone it loops at the Google logo

**Comment by NeoTheThird** [comment]
> If the problem persists, please use the installers bugreporting feature, so we can see what is going on exactly.
@neshby

**Comment by neshby** [comment]
I can't use the bug reporting feature because the installer says installation is a success.
But on my phone after the installation finishes, it goes back to recovery mode.
After restarting, it loops at the google logo.

@NeoTheThird

**Comment by NeoTheThird** [comment]
In the top right corner you see a button "report a bug".
