### ISSUE TITLE
[xenial] Bluetooth daemon issue

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#766]
- Device: Turbo
- Channel: xenial
- Build: RC4

### Steps to reproduce
Connect a Pebble watch with Bluetooth on the phone. Open the app Rockwork.

### Expected behavior
Rockwork recognize the connection to the watch.

### Actual behavior
Rockwork doesn't recognize the connection to the watch, instead thinks it is not connected despite a bluetooth connection being established.

### Logfiles and additional information
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2193426/UTlogcat.txt)
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2193427/UTdmesg.txt)
![pebble_time_round](https://user-images.githubusercontent.com/13762919/42702077-ac07f7a2-86c8-11e8-8a28-9a0efdbf8d21.jpg)
![screenshot20180713_180016895](https://user-images.githubusercontent.com/13762919/42702078-ac30db86-86c8-11e8-921e-d1db29961a14.png)
![screenshot20180713_175924335](https://user-images.githubusercontent.com/13762919/42702079-ac50f38a-86c8-11e8-971d-080afa476184.png)
![screenshot20180713_175906570](https://user-images.githubusercontent.com/13762919/42702080-ac7f4226-86c8-11e8-9d4f-b109c254e3c7.png)
https://paste.ubuntu.com/p/QXCyBfFV53/

**Comment by NeoTheThird** [comment]
Please file a bug with rockwork for that. It might be that they just did not [compile for xenial](https://open-store.io/app/rockwork.mzanetti) yet.

**Comment by tomoqv** [comment]
I filed this bug after conferring with @bhdouglass. He believes it to be an issue with bluetooth rather than Rockwork. I know this probably needs to be complemented, but I am not sure how to label it and what info is needed.

**Comment by Flohack74** [comment]
The problem is rather that none of the devs I know has got such a watch for testing...

**Comment by tomoqv** [comment]
I understand. Is there anyway I can help you track this issue down? It seems to me that either bluetooth doesn't report the connection status correctly or that Rockwork doesn't read the connection status.

**Comment by j2g2rp** [comment]
I had the same problem about a week ago. Because of some problems i decided to make a wipe of the phone in xenial. After that I couldn't pair the watch. When I validated the pin the watch was waiting to confirmation. To pair the phone I had to back to Vivid and back again to xenial.

**Comment by Dave1152000** [comment]
Same issue with OPO and Pebble 2

**Comment by tomoqv** [comment]
I don't really know what I did, if anything new, but my Pebble watch is now recognized by Rockwork when connected in the bluetooth system settings. I went through the same hooplas as above having the same problem, but after letting it sit for a while it suddenly kicked in. No idea what was different this time around.

It seems the bluetooth daemon is still problematic and doesn't always report the connection status to apps, but I am glad it works again.

**Comment by mariogrip** [comment]
I have to move this for now, I need to get a hold of a pebble to be able to debug, i'll try get my hands on one by OTA-6

**Comment by tomoqv** [comment]
After upgrading to the latest RC (W39) last week, the connection between my watch and phone broke again. I haven't yet been able to reconnect. When I go to bluetooth settings, it briefly connects before disconnecting again.

**Comment by tomoqv** [comment]
I have managed to successfully pair my watch recently both to Pro 5 and OPO. The trick seems to be to open the Rockwork app before attempting to connect the watch through bluetooth. Also, I have connected to Pebble Time F77D and not the other instance Pebble Time LE F77D that is visible in available devices.

This is still very weird behaviour. Apps should honor established BT connections and those BT connections should remain even if not yet set up by the app. But then again, maybe the watch lets go of the connection if it can't talk to Rockwork...

**Comment by mariogrip** [comment]
I have pushed the latest version (5.50) of bluez to xenial_-_new-bluez please try this to see if it fixes the issue :)

`sudo ubports-qa install xenial_-_new-bluez`

**Comment by mateosalta** [comment]
I had the same thing happen, I let it connect once, only clicking on the bluetooth entry that did not contain "LE", then hit forget on the connection in bluetooth settings, leaving the established connection on the watch, then connect again.
