### ISSUE TITLE
[xenial] Switching weeks in calendar app doesn't work properly

### ISSUE THREAD

**Issue by hummlbach** [ubports/ubuntu-touch#768]
- Device: mako, laptop (shouldn't matter)
- Channel: 16.04 dev
- Build: 180712 (also doesn't matter i think)

### Steps to reproduce

Open week view in the calendar, zoom in s.t. you don't see midnight (neither at the top nor at the bottom) and try to switch the week (if you don't see the week in whole, swiping scrolls to the beginning or the end of the week).

### Expected behavior
(After the Flickable has scrolled to the beginning or end of the week) the PathView switches the week forth or back depending on the direction (left or right) you swiped. (Like it is case on vivid.)

### Actual behavior
The week does not switch. (Unless you do the swipe outside the (vertical) flickable area.

### Additional information
A minimal example showing the problem and working on vivid but not on xenial can be found here: https://github.com/hummlbach/MinFlickableInPathViewExample/

**Comment by stekalb** [comment]
Can confirm this on frieza (devel 20170715). Switching the week only works if 00:00 or 23:00 is visible.

**Comment by ruedigerkupper** [comment]
Confirmed on hammerhead.

**Comment by NeoTheThird** [comment]
Since calendar is a click, it can be tracked independently from the rootfs.

**Comment by hummlbach** [comment]
@NeoTheThird i still don't get where to track the bugs. I would file them where I suspect the problem to be. As showed with the minimal example above this is not a calendar specific problem... So: Is the minimal example above working/behaving as expected on xenial? If no this should stay here imho. If yes then it should go to the calendar tracker and has to be fixed there.
