### ISSUE TITLE
Re-enable autocompletion in shell

### ISSUE THREAD

**Issue by doniks** [ubports/ubuntu-touch#769]
It had previously been enabled via #278 , but it seems to have disappeared again in xenial

**Comment by hummlbach** [comment]
@doniks auto completion works for me on mako with todays 16.04 devel channel (180714). Please add more details.

**Comment by doniks** [comment]
oh, strange, I had to ``apt install bash-completion`` manually. Can you check whether you have that installed?

**Comment by NeoTheThird** [comment]
Yep, looks like that disappeared. Could you make a PR to [the meta package](https://github.com/ubports/ubuntu-touch-meta/), @doniks?
