### ISSUE TITLE
[xenial] All scopes are empty

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#776]
- Device: hammerhead (Nexus 5)
- Channel: 16.04 RC
- Build: W29

### Steps to reproduce
After today's update to RC W29 all scopes are empty (except the applications scope).

Additionally, switching scopes takes very long (but this was formerly present, too and might be unrelated).

**Comment by mariogrip** [comment]
What scope did you try? i just tried with falcon and that worked for me.

**Comment by ruedigerkupper** [comment]
I tried:

- today scope
- calls
- events
- telegram scope
- cinema scope
- media scope
- news
- euronews 
- vice news
- softpedia
- ubuntufun
- 2buntu
- omg! ubuntu

(That's what accumulated over time ;) )
They all are completely empty.

**Comment by mariogrip** [comment]
Humm i wonder if these need recompiling for xenial. Have they worked before on xenial?

**Comment by ruedigerkupper** [comment]
Many of them certainly need recompiling. But I was under the impression that at least some of them worked after update to xenial. Not 100% sure, though :-/
I'll try falcon, as you say it works for you. Other scopes you know are working?

**Comment by ruedigerkupper** [comment]
Looks like you are right and I was dumb: Falcon works fine, so my other scopes are simply broken because they have not been recompiled for xenial :-/.
(How/when will that happen? Will maintainers be "asked" to recompile? It's a release candidate, but currently when you upgrade from vivid, 80% of your applications will stop working. This may not feel like an upgrade at all to some users ;-).)

**Comment by Flohack74** [comment]
Scopes are a difficult topic for us: They created a lot of biased conversation between lovers and haters, so we need to stay a bit neutral. I would say there is no difference regarding xenial to Apps: Whatever gets recompiled and works, will work. But its hard to reach all the developer, its the same for apps and for scopes.

**Comment by rubencarneiro** [comment]
Some are working
![screenshot20181022_235547955](https://user-images.githubusercontent.com/40370995/47324037-228d0980-d656-11e8-92be-79f9ceb186b5.png)
![screenshot20181022_235535879](https://user-images.githubusercontent.com/40370995/47324038-228d0980-d656-11e8-8f68-79474666ce06.png)
![screenshot20181022_235529450](https://user-images.githubusercontent.com/40370995/47324039-2325a000-d656-11e8-8718-5cd81d853063.png)

**Comment by ruedigerkupper** [comment]
Oh, thanks for the pointer. Especially the Events and Calls scope will be very useful.
(Yes, I am one of that old-style users believing in scopes. I loved them from the start.)

**Comment by ruedigerkupper** [comment]
HM, sorry, the „calls“ scope just appears empty for me. What am doing wrong?
