### ISSUE TITLE
Load is constantly above 2.0

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#777]
- Device: hammerhead
- Channel: 16.04 RC
- Build: W29

On my Nexus 5, load is constantly around 2.3 with the phone just sitting there and doing (apparently) nothing. Is this to be expected?
I see dekkod taking up around 50% of CPU, but even after I killed the process, load does not go down.

**Comment by doniks** [comment]
which dekko?

**Comment by mauricioduarte01** [comment]
There is a WIP dekko2 for xenial which is not working yet (I think it only works when using previous config from Vivid) and its also a battery drainer so I suggest uninstalling it from Xenial until a more stable version is released.

**Comment by ruedigerkupper** [comment]
Thanks, deinstalled it. The notifications daemon was still working, I got
push notifications for new mail. That's why I kept it installed.

BTW, did soemone notice you cannot uninstall old vivid apps from the
openstore?

Am Samstag, 21. Juli 2018 schrieb mauricioduarte01 :
> There is a WIP dekko2 for xenial which is not working yet (I think it
only works when using previous config from Vivid) and its also a battery
drainer so I suggest uninstalling it from Xenial until a more stable
version is released.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/KK5y_bAUTzWsD-V7fx2cSPeWUaHAwT8oqndJOVmOKkhncWsocFEDRLkiy0Z_0u9VqA69eDlSPQqte4rB1Ny7BIMXtjGqXeuRdQH1lw0IL1e8_iXg-mngFjphd6o9j8xvLLoUtkGeEbOgo1-0xuFx0anVio98Hw=s0-d-e1-ft#https://github.com/notifications/beacon/AUMSlsjmqnYm6vP4buERr-675gpYlfN1ks5uImwqgaJpZM4VU3cv.gif
>

-- 
Dr. Rüdiger Kupper
Forststr. 3
72250 Freudenstadt

**Comment by ruedigerkupper** [comment]
Deinstalling dekko did not help reducing the load. Still constantly above 2.

**Comment by ruedigerkupper** [comment]
Need to add that although deinstalling Dekko did not help with the load, it *greatly* improved battery life time! Life time has almost doubled (but this is on a already worn-out battery. With Dekko it lasted less than 24h, now it's regularly 1,5–2 days.
Since Dekko is for me one of the essential apps that should come preinstalled, its battery demand should be reduced.

**Comment by UniversalSuperBox** [comment]
Coming back through some older bugs, and I don't believe this one should continue to stay on the radar. The load average is a [complicated](https://www.howtogeek.com/194642/understanding-the-load-average-on-linux-and-other-unix-like-systems/) measure of processes that are waiting on a system resource. Between the Android container and the power management of Android devices, it is possible that having a load average of around 2 on a 4-core device is normal.

As for the issues with Dekko, they should be tracked on its bug tracker: https://gitlab.com/dekkoproject/dekko/issues
