### ISSUE TITLE
Feature request: allow country search in clock-app

### ISSUE THREAD

**Issue by TartanSpartan** [ubports/ubuntu-touch#783]
### Description of the feature
Currently, when you tap "Add (+) City" you go to a list of cities (and the countries they are part of as tags) across the world. You can scroll down it or search by city. But it would be useful to search by country too. Perhaps you are interested in the time zone difference between say the UK and Madagascar. But you might not know any cities in Madagascar, so searching by city wouldn't help, but searching by country tag would be helpful. And this would be a handy thing to do without having to search in a browser or a map app for "which towns/cities are in country X"?

**Comment by dark-eye** [comment]
@Flohack74 I think this should be moved to the clock-app repo/project

**Comment by Flohack74** [comment]
This issue was moved to ubports/clock-app#90
