### ISSUE TITLE
[xenial] Shortcut to OpenStore from scope management screen doesn't work

### ISSUE THREAD

**Issue by ewentual** [ubports/ubuntu-touch#784]
- Device: hammerhead
- Channel: 16.04/dev
- Build: 2018-07-22/2

### Steps to reproduce
Swipe up from homescreen (this little arrow up icon)
Click the icon in top right corner

### Expected behavior
OpenStore is opened and I see more scopes to install

### Actual behavior
Homescreen is opened once again

**Comment by NeoTheThird** [comment]
It's not supposed to open the OpenStore, it used to open the Ubuntu Store, but since that is removed, it is now without function. We will not fix this, since the entire scope/homescreen/widget situation is going to change on the latest unity 8.
