### ISSUE TITLE
Contacts default settings

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubuntu-touch#786]
- Device: OPO
- Channel:RC
- Build:2018-W29

### Steps to reproduce
In Contacts alphabetic always shown list is shown first 

### Expected behavior
Favourites should be on Contacts opening screen as they are most used numbers.

### Actual behavior
Alpha list seems to be default with no apparent way of changing it.

**Comment by hummlbach** [comment]
@Dave1152000 this would most probably be implemented in the app itself, so please suggest it again in the contacts issue tracker: https://github.com/ubports/address-book-app/issues
Also please try to be more clear. Perhaps its just me, but I had to read it several times until I've got what you're asking for. ;-) Perhaps call it "Show most/recently used contacts first by default". At the moment the title is not saying much.
