### ISSUE TITLE
Compile docviewer for xenial

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#790]
The docviewer app needs to be built and compiled fro xenial. @Flohack74 started a [deb build on the CI, but it is currently failing to build](https://ci.ubports.com/blue/organizations/jenkins/docviewer-app/activity).

**Comment by balcy** [comment]
for the compile errors: https://github.com/ubports/docviewer-app/pull/24
not sure if more adaptions are needed for the build

**Comment by balcy** [comment]
for xenial branch: https://github.com/ubports/docviewer-app/pull/25

**Comment by ruedigerkupper** [comment]
...desparately wanted...!

**Comment by Flohack74** [comment]
We got a working build less the LibreOffice formats. You want to test it?

**Comment by ruedigerkupper** [comment]
It would be a huge advance to be able to view PDFs again. Viewing LibreOffice documents is great, but PDF is essential -- there are so many of them around.
Is your build available as a click package? If so, I suggest putting it in the open store with a warning that it does not currently support LibreOffice.

**Comment by Flohack74** [comment]
Ok I will talk with the guys. Not building myself right now. We also need a new maintainer for it...

**Comment by Flohack74** [comment]
Note: The PR for this issue is now at ubports/docviewer-app#27 ... We are close to merge it. Test build looks good!

**Comment by Flohack74** [comment]
This will be closed now since extended QA gave green light ;)
