### ISSUE TITLE
No obvious way of uninstalling vivid apps / no way at all of uninstalling vivid scopes

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#796]
- Device: hammerhead (but assumably all)
- Channel: 16.04 RC 
- Build:W30

There's no way at all of uninstalling dysfunctional scopes not recompiled for xenial, and just a very unobvious way of uninstalling apps not compiled for Xenial: You need to long-press the icon in the apps scope, then tap an unlabelled button an then tap it again (still unlabelled) to confirm.
Removing apps and scopes not recompiled for xenial from the open store is impossible.

**Comment by PhoenixLandPirate** [comment]
If you use the ubuntu tweak tools application, you can uninstall scopes from there.

**Comment by ruedigerkupper** [comment]
You are right, thanks 
Still, I stick to the bug I reported: There is no *obvious* way of uninstalling (broken) vivid apps. Users will get lost with a great number of dysfinctional apps upon apdate to Xenial.
They *will* bedisturbed.
They *will* wonder why almost all of their apps are suddently broken.
They *will* wonder how to recover.
You *must* guide those users on their way to Xenial, or they will abandon Ubports.

**Comment by UniversalSuperBox** [comment]
The situation is **much** more nuanced than that, @ruedigerkupper. I don't think the ultimatum is necessary.

> Users will get lost with a great number of dysfinctional apps upon apdate to Xenial.

We've made improvements to this effect. #706 introduces a prompt to update *all* apps (and, by extension, scopes) from the OpenStore. If there's a Xenial version available, it will be installed. The user may choose to skip this, but there will only be one person at fault in that case.

In the case of uninstalling apps from Vivid, that's still completely possible. If you install an app which isn't compatible, it won't work correctly but you can remove it by pressing and holding on its icon in the Dash.

I'm not sure we want to decide on removing apps and scopes *for* the user, even if they won't work correctly. My gut says that making those decisions for the user is bad news. Even Ubuntu proper will **not** remove packages from your system if you installed them.

Not being able to uninstall scopes *is* a problem. I would say that an app management area built into System Settings would be a good idea. If you agree, I can create a new bug report which details this enhancement request in more detail. What do you think?

**Comment by ruedigerkupper** [comment]
Hi @UniversalSuperBox,
if youtube have good ideas about how such app management area could look and function it will be worth filing it as a feature suggestion. Please go ahead!

Regarding app management areas, however, it appears we already have two of them (if not three, including falcon): One is the dash and the other, most obvious, is the open store app.
And here, I would, very humbly, come back to the title of the post: From the obvious app manager that the majority will try to use  (open store app) there is no way of uninstalling vivid apps. And from the dash there is no hint that it could serve for that, unless you accidentally tap and hold an icon. And even then that dialog is broken: The uninstall button is unlabelled.

So there are methods of solving this that are probably much simpler than inventing a new app:
- add an unistall option for vivid apps in the open store
- fix the missing label in the dash dialog
- add something suggesting to the user that the dash can be used for more than just launching apps.

Managing scopes is, like you say, more problematic. The most obvious way of removing scopes would again be the open store (since that is where you install them). The second obvious place would be the scopes dialog that comes up swiping from the bottom edge. There could be a remove option for indivudual scopes (like the familiar right swipe displaying a trash can icon), but I can imagine that the scopes sorter is hard to modify since it is part of the core UI since early Canonical days.

Lastly, regarding broken apps after update to Xenial: #706 is great! However, take myself as an example: I have about 50 apps on my Ubuntu Phone. Most of them do not work currently, simply because they have not been recompiled for Xenial. So this is the situation most users will face: Of 50 apps there will be around 40 that will appear broken after update  to Xenial, simply because there is no update for Xenial available. It is a great idea prompting users for an update, but for most of the apps a user may have installed there will be no update.
Does the update prompter address this problem? I know it is hard to solve, the best way appearing to suggest contacting the developer – but there again is no obvious way to do this for the user.
Alternatively the update prompter could offer to remove any app and scope for which there is no Xenial version. This will at least guarantee that all apps do work, but the user may still be disappointed that nosy of their beloved apps will be gone.

**Comment by UniversalSuperBox** [comment]
This is fixed by https://github.com/UbuntuOpenStore/openstore-app/pull/27, which allows for the removal of installed but incompatible apps and scopes via the OpenStore.

Any apps which are not upgraded for Xenial will not be upgraded in the setup wizard... however, I take issue with the idea of removing software *for* people. I do agree that a page in the wizard asking for people to remove their incompatible apps would have been ideal, but unfortunately we didn't have the bandwidth (or a contributor) available to do that in this cycle. At this point, we can direct people to the OpenStore to check for their apps and see whether they have been upgraded or not.
