### ISSUE TITLE
Applications scope freezes for 15s before it can be used

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#797]
Whenever I switch to the applications scope, it stays unresponsive for 15s (sometimes not even showing the icons). After that it works as expected. Taps and swipes get registered during that phase and execute as soon as the scope gets responsive again.

**Comment by Flohack74** [comment]
Plz give more details: Channel, release ID, device etc...

**Comment by ruedigerkupper** [comment]
Device: hammerhead (Nexus 5)
Channel: 16.04 RC
Releases: W29, W30

**Comment by ruedigerkupper** [comment]
The problem has disappeared... I do not know what caused it or fixed it. But...
One off the list ;-)!

**Comment by jonnius** [comment]
I got the exact some problem since I updated from Version 14 to 20 on the edge Channel (FP2). I can reproduce the freeze each time.

**Comment by jonnius** [comment]
[unity8-dash.log](https://github.com/ubports/ubuntu-touch/files/2654396/unity8-dash.log)

**Comment by jonnius** [comment]
A restart solved it.

**Comment by Flohack74** [comment]
I had it due to some modifications on the android container which caused a service crashing every few seconds. I think that might be one of the reasons why it happens. Note that the sidestage is still fully functional during those hangs.

**Comment by jonnius** [comment]
Correct. The side bar, indicator menus, app switcher and so on are fully functional during the app scope freeze. I didn't touch android containers or did anything special though. It happened after an system update...
