### ISSUE TITLE
Preinstall a default mail client

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#799]
- Device: Vagetahd
- Channel: 16.04 RC
- Build: 2018-W30

### Steps to reproduce
Mail client is not present in the build

### Expected behavior
Mail client is required. Currently the only option available is to login to email from browser.

### Actual behavior
N/A

### Logfiles and additional information
N/A

**Comment by strangerer** [comment]
There was a mail client called dekko2 but it's not working in 16.04rc
But I like the idea for default mail client

**Comment by ruedigerkupper** [comment]
I totally agree that an email client must come preinstalled with UBPorts. It is essential.
Dekko ist the only reasonable candidate for this.
Dekko is not available for Xenial.
This must be fixed.

**Comment by nanu-c** [comment]
This is the only reason why I don't use 16.04 and stay with 15.04

**Comment by strangerer** [comment]
How to configure Gmail in dekko can u help me(15.04)

**Comment by nanu-c** [comment]
Have a look there: https://support.google.com/mail/answer/7126229?hl=en

**Comment by strangerer** [comment]
Still not able to configure please do give some tutorial

**Comment by NeoTheThird** [comment]
Multiple issues are mixed here.

Pre-installing Dekko: The size of the images we can ship to the devices is limited by the hardware of our phones, so this will likely not happen.

Publishing Dekko for Xenial: Work in progress.
