### ISSUE TITLE
[xenial] apps do not get installed from Libertine Container

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#800]
- Device: vagetahd
- Channel: 16.04 RC
- Build: 2018-W30

### Steps to reproduce
- Go to settings
- Select Libertine Container
- Select the installed Container
- Tried installing packages - google-chrome-stable, firefox, gnome-calculator
- Installation log continuously goes on and the package does not get installed

### Expected behavior
Package needs to get installed

### Actual behavior
Package does not get installed

**Comment by ruedigerkupper** [comment]
Just to be sure: Did you wait long enough? Installation can take a very long time like 20 minutes. Watching the log you can easily get the impression that the process is stuck in a loop. But eventually comes to an end, (at least it did so for me...)
Make sure your phone does not sleep, I do not think unstallation continues in the background.

**Comment by nikhilbhalwankar** [comment]
It did not complete. I waited for almost 3 hours.

**Comment by JanArneFagertun** [comment]
Not working on bq E4.5, Ubuntu 16.04 (2018-W32) either.
Neither on newly installed W33....
But - I am new to libertine, so I don't know if I have performed all steps in creating container...
I see the message "Cannot determine package version." when I inspect details.

**Comment by padraic7a** [comment]
Not confirmed here.

Device: frieza
Build: 16.04 2018-09-05
gnome-calculator and firefox both install on my Libertine container. 
google.chrome-stable doesn't but it also doesn't appear in a search of the archives.

**Comment by lduboeuf** [comment]
should we close this issue @nikhilbhalwankar ? Still experiencing the same issue ?

**Comment by JanArneFagertun** [comment]
Sorry I haven't updated - no, I am not experiencing the same issue, so just
close it.

I haven't been able to connect to a monitor to test it, but that's another
issue :-)

Den man. 17. des. 2018 kl. 23:10 skrev Lionel Duboeuf <
notifications@github.com>:
