### ISSUE TITLE
UBPorts Installer - hint to use USB 3.0 port missing

### ISSUE THREAD

**Issue by hgvws** [ubports/ubuntu-touch#802]
The requirement to use an USB 3.0 port with ubports-installer (at least with a BQ M10) is not shown in the first screen of ubports-installer ("Please connect your device").
The user cannot proceed beyond fastboot if he uses an USB 2.0 port. This might lead to serious frustration, so a hint to connect the device to an USB 3.0 port seems appropriate.

- Device: BQ M10
- Channel:stable
- Build:ubports-installer 0.1.21-beta-37 running on Debian GNU/Linux 9.5

### Steps to reproduce
- Run ubports-installer
- Connect BQ M10 to USB 2.0 port.
- Proceed.

### Expected behavior
The first screen of ubports-installer shall contain a hint that the user shall connect his device to a USB 3.0 port.

### Actual behavior
The first screen of ubports-installer does not contain any hints that the user shall connect his device to a USB 3.0 port.

**Comment by ShadowEO** [comment]
Why can't the use progress past fastboot if he/she does not use a USB 2.0 port? The installer is simply using ADB and fastboot to communicate with the phone at all stages, Neither require USB 3.0 ports to perform. So the installer shouldn't require one either.

I did notice however that a version back or so of the installer would simply hang after downloading files and rebooting to recovery, but that wasn't related to the USB port in use (I attempted with both USB2.0 and 3.0 and had the same behavior). Could this be related to that?

**Comment by hgvws** [comment]
The installer ran fastboot, the device repsponded by showing "Fastboot..", and the process got stuck.

After switching to another. newer machine, which runs the same versions of ubports-installer and Debian, but had USB 3.0 ports, everything went smooth.

For debugging purposes, I had been able to reproduce the behaviour of ubports-installer using adb and fastboot on the command line. So maybe it's an issue related to the Android toolchain!?

**Comment by Flohack74** [comment]
@hgvws it can be:
- a faulty cable
- Problems with the USB chipset on the phone
- Problems with the USB chipset on the PC
- Administrative rights to access USB
- And now NEW: USB3/USB2 - BUT: There is no such requirement to use only USB3. That must be a coincidence, I ues the installer a lot on USB2 machines.

So yes, we know, the installer is a bit of a problem but show me any other mobile OS which has such a friendly tool to install/upgrade. Android was not meant to be updated in such a way, and ADB is a DEBUG bridge for developers, not something that works for all users.

I can only ask for patience, as we tryx to make it better with each version. And change your USB cables often ;)

**Comment by hummlbach** [comment]
@hgvws
- also the installer has its own issue tracker at https://github.com/ubports/ubports-installer/issues
- would be cool if you could investigate on it further, develop ideas what else could be the problem and different, double check if your suspects holds and report it again in the installers tracker
- please add some logs then
- perhaps tell if you're using an m10 hd or fhd
