### ISSUE TITLE
Update android firmware

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubuntu-touch#805]
### Description of the feature
Device: Mako
update android firmware from 4 to lineage 15

**Comment by Flohack74** [comment]
You need to be more precise. Which device at least?

**Comment by ShadowEO** [comment]
@Flohack74 They appear to be asking for you to update the Android image on the mako to Lineage 15 (Android 8.0).

@fmulcar this is not possible at the moment due to how Halium works. Halium/UBports only support Android 5.1 and 7.1 at this point in time.

**Comment by UniversalSuperBox** [comment]
Upgrading the Android image used for a device is largely a useless measure unless the new firmware contains fixes for existing bugs. I'm not aware of any such fixes between AOSP 4.4.2 and LineageOS 15.1 for that device, so there is no reason to do this.
