### ISSUE TITLE
Unable to access "bacon"

### ISSUE THREAD

**Issue by shapley** [ubports/ubuntu-touch#810]
OnePlus One
Release Candidate
Build:22

I'm unable to access phone through 'adb'. When I connect the handset to my desktop Ubuntu 18.04 (bionic) it shows the 'bacon' icon but when i try to mount it I get the following error:

unable to access "bacon"
Unable to open MTP device "[usb:001,005]

I have ensured all MTP tools have been installed. Also tried UBports suggestion:
printf "0x9d17 \n" >> ~/.android/adb_usb.ini

**Comment by advocatux** [comment]
`adb` and `mtp` are very different tools. You don't need to mount your phone using `mtp`.

Please, see http://docs.ubports.com/en/latest/userguide/advanceduse/adb.html

You need to set on "developer mode", and accept the confirmation pop-up dialog in your phone (the first time you use `adb` with it).

**Comment by Flohack74** [comment]
Did you follow this guide? https://forums.ubports.com/topic/1015/howto-opo-fix-mtp-driver-permissions/22

**Comment by Flohack74** [comment]
Well actually it should not be necessary on 16.04 anymore. Can you confirm that you are on 16.04 devel or rc?

**Comment by Flohack74** [comment]
Plz confirm back whats the state here...

**Comment by shapley** [comment]
I reverted to a 'wipe' and then re-install of 16.04 rc which seemed to allow full access with 'adb' and an unrelated issue with bluetooth sound. All functioning OK since then.

**Comment by NeoTheThird** [comment]
Ok, thanks for reporting!
