### ISSUE TITLE
Some apps will not update to new version

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#813]
Apps will sometimes not update. The open store informs you that the package Is from an old source (which may or may not be true, see example below) and says it is now available from the open store. It shows an update button. When you tap it, you see the package being downloaded and (apparently) installed. But the installed version never changes and open store keeps nagging you that you should update.

This is on hammerhead (Nexus 5) but I suspect it affects all devices. However, it affects only few packages.  It is actually present since the first version of open store. The reason I report it now is it could become more prominent when (hopefully) a lot of maintainers recompile for Xenial and move their app to the open store. It's essential that they can be updated.

For example, my installed version of „Sturm Reader“ (ebook-reader) is 2.0.5. It is the old Vivid version. Open store says that the installed version is not from the open store, which I think is wrong (I seem to remember it has never been in the old store and I did not install it manually).
Version 2.0.6 is available (recompiled for Xenial). I tap the update button and it downloads and installs, but after that the version is still 2.0.5. I can repeat that as often as I like. Running the app confirmes it has *not* been updated (it is obviously still the old Vivid version that breaks).
I tried removing and reibstalling with no success: I always get 2.0.5, not 2.0.6.

Another example: „LibriFox“ app: Installed: 1.0.3, available: 1.0.3 (30.05.18). It will not update.

**Comment by ruedigerkupper** [comment]
Addendum: The problem often resolves itself when an even newer version gets available.

**Comment by Flohack74** [comment]
@bhdouglass any ideas about that?

**Comment by bhdouglass** [comment]
I have an idea, but could I get a log from the OpenStore app after you try to install one of these apps?

**Comment by ruedigerkupper** [comment]
Sure. Where would I find that?

**Comment by ruedigerkupper** [comment]
Found it with the logviewer app: http://paste.ubuntu.com/p/4c4YY8wTbK/
I tried to update "Sturm Reader".

In doing so, I noticed that while the author claims in the changelog the new version was 2.0.6, it really is "2.0.5 (30.7.18)". So the problem could well be caused by the fact that the version strings only differ in the date part. This is also the case with my install of LibriFox.

**Comment by ruedigerkupper** [comment]
From the log you see that the click file that is actually downloaded is "sturmreader.emanuelesorce_2.0.5_armhf.click".
In contrast, when I browse to https://open.uappexplorer.com/app/sturmreader.emanuelesorce and click the "Download (Xenial)" button, I get "sturmreader.emanuelesorce_2.0.6_armhf.click".

**Comment by ruedigerkupper** [comment]
Given from what I describe above, I suspect that the problem is caused by malformed comparison of version strings.

**Comment by bhdouglass** [comment]
Actually this ended up being a bug on the server side. The discover api was giving back some bad data for apps not in the "new & updated" section of the site. This has been fixed, just close the OpenStore app from the app switcher and you'll be good to go.

**Comment by ruedigerkupper** [comment]
Nice! Thank you!
