### ISSUE TITLE
Wont install on Nexus 5

### ISSUE THREAD

**Issue by dnomode** [ubports/ubuntu-touch#814]
- Device: nexus 5 D821
- Channel: 15.04/stable
- Build: not sure

### Actual behavior installer detects the Nexus 5, after I click on install and continue the phone reboots into bootloader screen and then software asks for my password. After I enter my password the software says please reboot to bootloader. So I hold the volume down and power until the phone reboots. The software never continues with the install. What am I doing wrong?
![image-1](https://user-images.githubusercontent.com/37214746/43745275-e4d5f4d0-99ab-11e8-9b9a-0c9cc23541b4.jpeg)

![screenshot 2018-08-06 19 05 30](https://user-images.githubusercontent.com/37214746/43745234-b6e887c2-99ab-11e8-9c10-d73627730bc5.png)

**Comment by mariehedwige** [comment]
Hi, I tried to install ubuntu touch on my Nexus 5x but finally found that is not possible so I'd like to know how can I restart my phone with Android ? It is now on the same mode as the picture on top of this website page !
