### ISSUE TITLE
Install from the Recovery possible (Oneplus One ) ? 

### ISSUE THREAD

**Issue by Matze-M** [ubports/ubuntu-touch#815]
I was not able to install the Os with the given tool but the **Ubuntu recovery is** already **installed** so **is it possible to install the Ubuntu touch OS from the recovery ?** When i want to boot normal only the Oneplus  "**powered by Android**" shows up. But from the recovery  under the option "**Ubuntu Actions**" i can choose " **Install Ubuntu Zip** " is a .Zip file to install available ?

**Comment by hummlbach** [comment]
@Matze-M Welcome! Please get in contact with our [welcome and install team on telegram](https://t.me/WelcomePlus) or open a thread in the [support category of the forum](https://forums.ubports.com/category/37/support) to ask such questions. If you want to contribute to the improvement of the install process, please open an issue in the [installer's issue tracker](https://github.com/ubports/ubports-installer/releases) (if theres nothing similar reported yet) and add some logs and some more information which versions on which OS you were using.
