### ISSUE TITLE
Design proposal for notification indicators

### ISSUE THREAD

**Issue by ChristianPauly** [ubports/ubuntu-touch#817]
### Description of the feature
Hi, I have a design proposal. The top-left corner of the system is unused in phone mode so we could use this to display the icons of the apps of the persistent notifications.

The new notification indicator seems to be always the first left indicator, so the relationship would be clear for the user.

In tablet mode, at this position is the title name of the focused app. Then the icons should be on the right side, left from the notification indicator.

What do you think? :-)

### Illustrations
![messageindicatorsproposal](https://user-images.githubusercontent.com/24619905/43949280-6294b6f2-9c8d-11e8-8584-7768587d13af.png)

**Comment by advocatux** [comment]
I like this idea but in some devices, like BQ E4.5, that free area is really minimal.

Also, in other devices, that area is pretty reduced when people have weather, flashlight, or any other extra icons showing in that bar.

**Comment by NeoTheThird** [comment]
Since that's where the [global menu will end up](https://github.com/ubports/unity8/issues/16), i don't think this is a very good idea.

**Comment by ChristianPauly** [comment]
I have thought about it and yes you are right. :) So I will close this.
