### ISSUE TITLE
Customised fields in Contacts app

### ISSUE THREAD

**Issue by adrmzz** [ubports/ubuntu-touch#825]
The Contacts app allows to assign different tags to the information for a contact:

![imatge](https://user-images.githubusercontent.com/6729251/44268294-4f293d00-a231-11e8-9618-4b11cf352aa8.png)

These tags might, however, fall short, and then it would be handy to allow users to set their own customised fields (like, —why not—, "House in the mountain" or "House on the beach").

**Comment by BlueKenny** [comment]
i like the idea but where would be this configuration?

**Comment by adrmzz** [comment]
I don't know if it is technically possible: maybe tapping "other" ["Un alt...", in the highlighted square of my screenshot above] could open a text field so that the user would write his/her own field?

**Comment by mardy** [comment]
@hummlbach I think it does, there's something here: https://github.com/ubports/address-book-service/blob/master/common/vcard-parser.cpp#L69

**Comment by hummlbach** [comment]
So I close this here and we'll reopen it or file a new issue if we see that something needs to be done in the backend.
