### ISSUE TITLE
Weather apps

### ISSUE THREAD

**Issue by jodumont** [ubports/ubuntu-touch#827]
Hi again;

so for the weathers apps

1. I'm unable to search a city because the keyboard don't appear
2. It's confuse me; I tough it have more than one city in the world starting with A, aka where and/or how to add cities ?

**Comment by stekalb** [comment]
Can you please clarify which channel on which device with which build you use. For me it works on opo (vivid stable) as well as on m10fhd (xenial dev)

**Comment by jodumont** [comment]
Channel: stable
Device: Hammerhead

but anyway I remove Ubuntu touch, it's a nice project to too early for me
