### ISSUE TITLE
Can't re-enable Notifications (Nexus 5, 16.04 rc) 

### ISSUE THREAD

**Issue by Gimped** [ubports/ubuntu-touch#831]
- Device: Nexus 5
- Channel: Ubuntu 16.04 LTS -armhf (20180814)
- Build: 2018-W33

### Steps to reproduce
Go to Notifications in Settings, uncheck them all in Notes, System, etc (for sound, vibration, etc), but you can't re-enable them after unchecking them. Only 2/4 (like Notes for example), you can re-enable, but if you uncheck those too, you can't re-enable.

### Expected behavior
Uncheck notfications you want turned off, turn them on again by checking the box (works in 15.04)

### Actual behavior
The whole checking/unchecking function freezes after you uncheck notifications in settings, but you can't re-enable them after unchecking it or rebooting the Nexus 5

**Comment by Marathon2422** [comment]
Pro 5
16.04 2018/08/21
Notifications only SD card settings effected.
You can turn off sound and other alerts, but you cannot turn them on again, 
Rebooted 
Tried another sdcard + reboot.

The others telegram,fluffychat,calendar,notes,system settings,
All work

**Comment by UniversalSuperBox** [comment]
Confirmed on FP2 and Nexus 5.

**Comment by arubislander** [comment]
Confirmed on M10 FHD

**Comment by padraic7a** [comment]
Tested on my Frieza this evening. Running 16.04, build 2018-10-01. 
Tested on my Hammerhead, running 16.04, build 2018-01-02.

This is still a problem. I will check tomorrow or the next day in case the fix hasn't landed in Devel yet.

**Comment by padraic7a** [comment]
Tested again this evening and this issue is now fixed.

**Comment by Eupalino** [comment]
Hello. Just switched to **RC** and downloaded and installed **2018-W40** on **anbox-boot-hammerhead.img** kernel to Nexus 5. Still, can't re-enable notifications (Settings/External Storage/Calendar/Notes.)
