### ISSUE TITLE
FEATURE-REQUEST: Screencapture current screen (Up Volume + Power Button)

### ISSUE THREAD

**Issue by Gimped** [ubports/ubuntu-touch#832]
### Description of the feature
Screen Capture current screen by an App or certain buttons

### Illustrations
![screencapture](https://user-images.githubusercontent.com/42617975/44483042-0221de00-a618-11e8-9a88-a1c5633d8921.jpg)

**Comment by UniversalSuperBox** [comment]
You can take a screenshot by pressing Volume Up and Volume Down at the same time

**Comment by Gimped** [comment]
Thank You!!! 
There's got to be like a cheat sheet in the UBPorts App or something, it's like an easter egg

**Comment by tcreek** [comment]
Not in the PinePhone.
