### ISSUE TITLE
Make 4 digits passphrase entry GUI rotateable

### ISSUE THREAD

**Issue by jumasheff** [ubports/ubuntu-touch#836]
### Illustrations

- Device: Google Nexus 4
- Channel: Stable
- Build: Ubuntu Touch 15/16 (tried in both of the OS versions)

### Steps to reproduce

Passphrase GUI is not rotating, even if screen rotation works ok
 - Enable 4 digits passphrase
 - Lock screen
 - Try to unlock the phone

### Expected behavior

 - When a phone is held horizontally, passphrase entry UI should have horizontal layout.

### Actual behavior

 - Even if you are holding your phone horizontally, "Enter passphrase" UI will be vertically oriented

**Comment by ruedigerkupper** [comment]
Duplicate of #275.
