### ISSUE TITLE
Xenial welcome app re-downloads each and every app

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ubuntu-touch#837]
- Device: hammerhead
- Channel: 16.04 RC
- Build: W34/2

Upon my last update on the RC channel, the welcome tool ran. After showing the change log, it searched for updates. It returned suggesting that *all* of my apps (literally) had an update available. Tapping "update all" it happily proceeded downloading all of the 160 updates.
After ten or so (150 to go) I got impatient and hit "back". Back to the change log. Tapping "next" again it searched for updates again — this time returning with "all apps up to date".

### Expected behavior
The welcome app only updates apps which really have an update available.

### Actual behavior
The app updated all apps, regardless if there was an update available.

This was the first time the app ever ran on my phone, so it might be a first-run issue.

**Comment by NeoTheThird** [comment]
This is the intended behavior. Some apps need to be re-installed for 16.04, and there's no reliable way of determining for what app it is necessary. So what the wizard does is re-install all of them, since this the only fool-proof way of avoiding having non-functional apps.

**Comment by Flohack74** [comment]
Maybe we got to mention that. Confused me as well...

**Comment by hummlbach** [comment]
Yes +1 confused me too.

**Comment by ruedigerkupper** [comment]
I see. Yes, would be mouch less confusing if the app said "reinstalling apps to make sure they work". Instead it says "looking for updates", which is just not true.

**Comment by ruedigerkupper** [comment]
Oh, and if that's the intended behavior, then what happened after I hit "back" is a bug: although it never reinstalled the remaining apps, the tool reported "all apps up to date" on the second try.
