### ISSUE TITLE
[Xenial] Open Store - No option available to write App Reviews

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#839]
- Device: vagetahd
- Channel: 16.04 Stable
- Build: OTA-4

### Steps to reproduce
- Go to Open Store
- Select an App to install
- No textbox to write app reviews

### Expected behavior
App reviews are necessary to be posted so that users can mention the issues which they are facing with the app.

### Actual behavior
No textbox to write app reviews

**Comment by Flohack74** [comment]
Please file this here: https://github.com/UbuntuOpenStore/openstore-meta/issues
