### ISSUE TITLE
Hammerhead - UBport splash screen loop

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#84]
Gent, 

After the last upgrade, the phone is stuck in loop on the UBport splash screen,

SystemImageInfo:
 current build number: 21
 device name: hammerhead
 channel: ubports-touch/legacy
 last update: 1970-02-04 18:26:15
 version version: 21
 version ubports: 20170531-13919
 version keyring: archive-master
 version device: 20170531-16579
Tags:  vivid

I gather some log : 
/var/log/apport.log loop of https://pastebin.ubuntu.com/24778638/
/home/phablet/.cache/upstart/unity8-dash.log loop of https://pastebin.ubuntu.com/24778647/
/var/log/auth.log loop of https://pastebin.ubuntu.com/24778653/

I've enclosed two files, in the zip below
https://hytte.duckdns.org/s/envV0NhAEYDXsUl
_usr_bin_media-hub-server.32011.crash
_usr_bin_maliit-server.32011.crash

I don't know if media hub crash is related to mallit but it has the same 32011

After a reboot, the phone boot normally, i took time to report this bug as i got it also on the previous upgrade.

**Comment by j2g2rp** [comment]
I had a few times issues like that (last time was about one year ago). In my case if I rember correctly not only the system was stucked, the device enter into a reboot loop once it arrives to splash of ubuntu.

I don't know why it happend, sometimes i had the image in RW mode, others not, so... no idea... I just could flash the device... I hope someone could help you to track a bug like that...

**Comment by ernesst** [comment]
The upgrade 29-30 didn't bring this problem... strange

**Comment by ernesst** [comment]
I'm closing it as i didn't got the issue anymore.
