### ISSUE TITLE
QQC2 apps are not being scaled properly

### ISSUE THREAD

**Issue by timsueberkrueb** [ubports/ubuntu-touch#841]
It appears like QtQuick Controls 2 applications are not scaled properly. They are relying on [Qt's high dpi support](https://doc.qt.io/archives/qt-5.10/qtquickcontrols2-highdpi.html) which has been introduced in Qt 5.6.

This is the workaround I'm temporarily using for my app: https://github.com/timsueberkrueb/switch-reloaded/commit/3c24835907baa6eebd9e5b6cd6c4f1e29229fef6.

As per discussion in the supergroup, this might be a problem with qtmir.

- Device: Nexus 5
- Channel: 16.04/stable
- Build: OTA-4

**Comment by UniversalSuperBox** [comment]
Oh dear, GitHub knows that I messed up my commit message three times.

Er, I mean, the fix for this is in https://github.com/ubports/qtubuntu/pull/5

**Comment by UniversalSuperBox** [comment]
With that merge, this issue can be closed. App developers who wish to use the Qt autoscaling should see the [QQC2 High DPI documentation](https://doc.qt.io/qt-5.9/qtquickcontrols2-highdpi.html) for how to enable it.

**Comment by timsueberkrueb** [comment]
Awesome, thanks so much @UniversalSuperBox!
