### ISSUE TITLE
Release Upgrade Wizard: Needs to ask for PIN code & startup network

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#842]
- Device: FP2
- Channel: 16.04/
- Build:

### Steps to reproduce
- Install OTA-4 for the first time

### Expected behavior
- Upgrade wizard can search for Apps to be upgraded after network and WiFi have been initialized

### Actual behavior
- Network is not initialized since the PIN code dialogue appears only after the wizard has finished.
- WiFi is initialized, but fails if either out of reach, or if in a public hotspot, it cannot open the captive portal page to log in.

**Comment by UniversalSuperBox** [comment]
The release upgrade wizard has been removed due to other issues (mainly with regression testing), so this issue is no longer valid.
