### ISSUE TITLE
Bug in Message app

### ISSUE THREAD

**Issue by neopar** [ubports/ubuntu-touch#844]
- Device: BQ E5
- Channel: 16.04 rc
- Build: OTA-4

### Steps to reproduce

1. Open app
2. Click on new message
3. Select contact

### Expected behavior

Contact added and you can start writing message.

### Actual behavior

White display with a red frame is shown-

### Logfiles and additional information

Screenshot here: [](url)https://imgur.com/a/hdYji3q

**Comment by NeoTheThird** [comment]
Hmm, this is interesting. It might be enough to upgrade to a newer version of ubuntu components and qtquick in the relevant qml file.

**Comment by Flohack74** [comment]
I think the App needs to be reviewd for 16.04 anyway, so maybe lets do this...

**Comment by jonnius** [comment]
People in german group say it affects OPO, too. Cant reproduce this issue on my FP2 though.

**Comment by jonnius** [comment]
I can reproduce it, but it depends on how you select the contact:

- Tab on the + to add a recipient and select one → Issue
- Search for a contact by typing directly into the recipient field → No Issue

**Comment by advocatux** [comment]
I had a Nexus 5 (hammerhead) running Ubuntu 16.04 devel (2018-09-02/2) and I had this issue https://github.com/ubports/messaging-app/issues/40 then I installed 16.04 rc (2018-W35) and I can confirm this _red frame_ issue.

**Comment by ellypsis** [comment]
I confirm this bug.
Device : OPO (bacon) on UT 16.04 Stable

**Comment by advocatux** [comment]
Confirmed in BQ E4.5 (krillin) too, running Ubuntu 16.04 (2018-09-09)

Log: https://paste.ubuntu.com/p/bvgMRF7YzY/

**Comment by MathhewJJ** [comment]
I confirm this bug also, logs uploaded:

Device: OPO (bacon) on 16.04 (OTA-5)

[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2582829/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2582830/UTlogcat.txt)

**Comment by UniversalSuperBox** [comment]
This issue sounds like https://github.com/ubports/messaging-app/issues/50. Has it been resolved?

**Comment by jonnius** [comment]
The issue is solved for me on edge (2018-12-02), which should be equal to devel.

**Comment by Thieb67k** [comment]
Hello, I have the same thing with LGE Nexus 4, OTA-5 (stable). That happens in 100% cases.
