### ISSUE TITLE
Welcome Wizard: Should automatically advance after hitting enter

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch#846]
When entering the "Preferred Name" into the welcome wizard, if the user hits the enter button it would be nice if it advanced to the next page automatically. Currently hitting the enter button just closes the keyboard. This also happens when inputting a password.

**Comment by UniversalSuperBox** [comment]
This issue should be fairly easy to fix if you have an Ubuntu Touch device. Even if you don't and have some QML know-how, you can get through this.

Check out [60-account.qml in Unity8](https://github.com/ubports/unity8/blob/xenial/qml/Wizard/Pages/60-account.qml). The `textField` where you enter your username has an `accepted` signal which is fired when the user presses Return on their keyboard. Hook that signal (`onAccepted:`) up to the `next()` signal on the `pageStack` to complete this task.

If you're taking this on, please add a comment here to say so.

**Comment by UniversalSuperBox** [comment]
Of course! Just let me know if you have any questions

**Comment by nikalon** [comment]
I don't know if I should link here but here's the PR: https://github.com/ubports/unity8/pull/79

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/79

Thanks @nikalon!

**Comment by UniversalSuperBox** [comment]
Note for QA:

You can re-run the Welcome Wizard once per session (reboot) by running `truncate -s 0 .config/ubuntu-system-settings/wizard-has-run` in the device terminal or via `adb shell`.

**Comment by UniversalSuperBox** [comment]
Sorry, I had the wrong command. `rm .config/ubuntu-system-settings/wizard-has-run` runs the wizard which is used in this case.

@3arn0wl, I'm not sure how to re-run the tutorial.

**Comment by 3arn0wl** [comment]
Thanks Dalton. :)

**Comment by cibersheep** [comment]
This is fixed in 2018-W48 on m10 HD
I get the menu until the welcome but tapping on introduction takes a long time and closes the wizard.

**Comment by hsbyter** [comment]
Fixed in 2018-w48 on m10 FHD
