### ISSUE TITLE
mp4 video playback has color issue

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#848]
### Illustrations

- Device: Hammerhead
- Channel: stable
- Build: OTA-4

### Steps to reproduce
Play back any .mp4 video

### Expected behavior
Video is displayed on the screen without any issue

### Actual behavior
The video is play back as expected, but the green colour channel seems to have a different scalling regarding screen size. This lead to a strange looking video

**Comment by NeoTheThird** [comment]
Duplicate of #7.
