### ISSUE TITLE
Bluetooth car connection shows empty battery

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#850]
### Illustrations

- Device: Hammerhead
- Channel: stable
- Build: OTA-4

### Steps to reproduce
Connect phone via Bluetooth to the multimedia system of the car

### Expected behavior
Current battery level is shown by the multimedia system of the car

### Actual behavior
The multimedia system of the car shows an empty battery

**Comment by NeoTheThird** [comment]
Thanks for reporting! Could you specify what model of a car and what version of an entertainment system you have?

**Comment by lgd821** [comment]
It's a simple Radio "Composition Colour" from Volkswagen offering these features used in various cars from Volkswagen

**Comment by mymike00** [comment]
I think this is a duplicate of #386

**Comment by Flohack74** [comment]
Indeed.
