### ISSUE TITLE
No phone call possible with Bluetooth car connection 

### ISSUE THREAD

**Issue by lgd821** [ubports/ubuntu-touch#851]
### Illustrations

- Device: Hammerhead
- Channel: stabel
- Build: OTA-4

### Steps to reproduce
Connect phone via Bluetooth to the multimedia system of the car. Try to do a phone call with somebody via the multimedia system (hands free phone call during driving)

### Expected behavior
The caller at the other end could be heard.

### Actual behavior
You can't hear anything. Maybe transmitted Bluetooth volume is set to 0, but there is no way to increase it.

**Comment by NeoTheThird** [comment]
Duplicate of #649.
