### ISSUE TITLE
Open Store not working on nexus 7 running UT v16.04

### ISSUE THREAD

**Issue by jxmproductions** [ubports/ubuntu-touch#852]
Earlier today i tapped on the open store icon but when it loaded i was greeted with was a white screen and a black bar.

taping on the black bar gave me 2 messages shown in the screenshots bellow

later i uninstalled the open store app and then manually installed the open store click package witch i downloaded from the open store site, only to have the same issue.

Also last night the open store was working and i was able to get some apps installed + i remember at one point being in the system settings app seeing there were some application updates available and installing them.

- Device: Nexus 7 2013 WiFi (flo)
- OS Version: 16.04 / ota-4
- Channel: Stable
Below are some screenshots i took showing the issue

![screenshot20180901_194718540](https://user-images.githubusercontent.com/27607461/44950832-919d6d00-ae20-11e8-8895-ccacd3e8c4e8.png)
![screenshot20180901_194722991](https://user-images.githubusercontent.com/27607461/44950833-96fab780-ae20-11e8-9182-458ce1bcc4c6.png)
![screenshot20180901_194727304](https://user-images.githubusercontent.com/27607461/44950834-9b26d500-ae20-11e8-949d-0c21ccbb6364.png)
![screenshot20180901_194731056](https://user-images.githubusercontent.com/27607461/44950836-9f52f280-ae20-11e8-93cb-a664063ce4c0.png)
![screenshot20180901_194734011](https://user-images.githubusercontent.com/27607461/44950839-a7ab2d80-ae20-11e8-98f0-6df3e9b6504a.png)
![screenshot20180901_194736528](https://user-images.githubusercontent.com/27607461/44950840-a974f100-ae20-11e8-9a00-1252c6fef187.png)

**Comment by jxmproductions** [comment]
just rebooted my nexus 7 and the open store is working

**Comment by Flohack74** [comment]
In the future when you face issues with Openstore, please file this with the Openstore team and not here: https://github.com/UbuntuOpenStore/openstore-meta
