### ISSUE TITLE
Unable to set dashbackground image the first time

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch#856]
- Device: Meizu MX4 & BQ M10
- Channel: 16.04/stable

### Steps to reproduce
- After a fresh install, enable the Dash Background switch
- DO NOT CHANGE THE BACKGROUND IMAGE

### Expected behavior
- The background image shows on the dash

### Actual behavior
- A black/blank image shows on the dash

### Logfiles and additional information
Settings:
![screenshot20180903_001156501](https://user-images.githubusercontent.com/935035/44967918-a35f3d00-af12-11e8-89f7-5d6ceb09608f.png)

Dash:
![screenshot20180903_001200215](https://user-images.githubusercontent.com/935035/44967920-a35f3d00-af12-11e8-8888-74ed61325479.png)

After setting an image it does show on the background of the dash, and you can switch back to the default background and it'll then show correctly on the dash. This bug only seems to appear the very first time.

**Comment by UniversalSuperBox** [comment]
Since the Dash has been removed, this bug no longer applies.
