### ISSUE TITLE
Contacts don't show up

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#857]
- Device: all
- Channel: 16.04/devel
- Build: 2018-09-03/2

### Steps to reproduce
Open address book.

### Expected behavior
If contacts are stored, they show up.

### Actual behavior
No contacts show up. This was likely introduced by #847.

**Comment by mardy** [comment]
I suspect that https://github.com/ubports/address-book-service/pull/5 didn't make it into the image yet. I created https://github.com/ubports/address-book-service/pull/6 to double check.

**Comment by mardy** [comment]
I tired today's image, and I see all my contacts. @NeoTheThird could you please confirm that the problem is fixed for you as well?

**Comment by UniversalSuperBox** [comment]
`address-book-service is already the newest version (0.1.4+ubports1+0~20180904223651.10~1.gbp21e792).`

Looks like my contacts are all showing up now.

**Comment by NeoTheThird** [comment]
Fixed, gj
