### ISSUE TITLE
Echo on the other side of the line during calls

### ISSUE THREAD

**Issue by Spraltik** [ubports/ubuntu-touch#861]
- Device: One Plus One - Bacon
- Channel: Development 
- Build: 16.04 - Version 471

### Steps to reproduce
Calling or receiving a call from another person using the phone app. 

### Expected behavior
No echo, and normal volume.

### Actual behavior
There is a echo for the person on the other end of the line, they hear themselves back with a slight delay. The echo is so annoying that every person I have called mentions it. Also the volume on my phone is at maximum and is still quite low and not affected by the volume buttons (this was not the case on Android). 

I have not included logs but will do so if it would help.

**Comment by Spraltik** [comment]
Thanks for your response FLohack74. Just to be sure we are on the same page: the echo is heard by the person on the other end of the phone call, not by you with the OPO right? I can find very few people who are experiencing the same issue as me it seems.

**Comment by delijati** [comment]
I have the same echo effect. But i never used the phone with android. So it could be also the hardware.

**Comment by thebosbird** [comment]
@delijati I don't have this on my OPO running 15.04

**Comment by Spraltik** [comment]
I found an old thread on the one plus one forums of someone experiencing the same issue on multiple roms: https://forums.oneplus.com/threads/phone-echo-issue.555264/. He also had no issue on Lineage OS up to a certain version. I suspect the same as him that it has something to do with the noise cancellation software not working properly.

**Comment by Flohack74** [comment]
Can you verify if your OPO shows up as bacon or A0001 in `getprop ro.product.device` ?

**Comment by delijati** [comment]
- getprop ro.product.device: bacon
- os: 16.04.05 LTS 20180921

**Comment by Flohack74** [comment]
Ok this is interesting, I got the later model A0001 :) - maybe its hw-specific and we would need some special bits for the other HW variant, could be...

**Comment by Spraltik** [comment]
same here:
- getprop ro.product.device: bacon
- os: Ubuntu 16.04 (2018-W35)

**Comment by Spraltik** [comment]
I did some more searching and found this thread on the oneplusone forums: [https://forums.oneplus.com/threads/problem-speakerphone-echo.376902/page-3](url)  they seem to have similar issues. It changes depending on what ROM they use so I still think it's fixable through software. I think post #47 might be on to something. I believe the issue is due to the noice cancelling microphone not working and therefore the microphone is picking up the sounds from the speaker. He writes the following suggestion: 

On cyanogenmod you need to edit /system/build.prop and add the following lines if they are not already there

persist.audio.fluence.mode=fluence

persist.audio.vr.enable=false

persist.audio.handset.mic=analog

persist.audio.voice.clarity=none

persist.audio.fluence.voicecall=true

persist.audio.fluence.voicerec=false

persist.audio.fluence.speaker=true

You can edit the file using root explorer. Please try this and let me know if it's working. It's supposed to turn on noise suppression

I can't seem to get write permissions from the terminal with: sudo nano build.prop it gives me the following error: "Unable to create directory /root/.nano: Read-only file system. I have been able to read the file do and the only line I could find back in it at the bottom was "persist.audio.fluence.voicecall=true". So perhaps adding the other lines might fix the issue? Can anyone explain to me how I can get root permissions to write into the build.prop file?

**Comment by Flohack74** [comment]
This is not so easy, near impossible, but we can inject this in our build services and then try to build it. Le me see if I can get this done.

**Comment by Flohack74** [comment]
The PR is still open, so you need to wait until https://github.com/ubports/android_device_oneplus_bacon-1/pull/11 is marked as Merged.

**Comment by UniversalSuperBox** [comment]
Please test whether this echo occurs today

**Comment by Sconioo** [comment]
I have a similar problem with my OPO,

When someone calls me, he can hear himself ( echo )


![photo_2018-10-22_21-49-59](https://user-images.githubusercontent.com/39526695/47315293-768ef280-d644-11e8-999d-a0c7f5309011.jpg)

This problem goes away immediately when using a wired headset.

The bug is in both 15.04 and 16.04

**Comment by wayneoutthere** [comment]
If it's helpful, this problem **used to exist** in the N5 and I think also the N4.  The description seems exactly the same.

**Comment by Spraltik** [comment]
Thanks Sconioo for that drawing!
The problem is still there and recently media started being played through the "earphone" instead of the speakers at the bottom of the phone. I'm still convinced "mic 2" acting as a normal microphone when it should be a noise cancelling one. I think it is picking up the sound of the earphone because it is so close to it.

**Comment by delijati** [comment]
Same here the problem still exists.

**Comment by delijati** [comment]
Awesome so far this works for me. No "Echo" on the other side. But now if i activate hand free mic, the other side is not hearing me.

**Comment by Flohack74** [comment]
Hmm I try currently to partially revert this stuff https://github.com/ubports/android_device_oneplus_bacon-1/pull/11 and then also to increase volume of the mics. Lets see...

**Comment by Flohack74** [comment]
Can you try to install today´s devel? Should be better now ;)

**Comment by Spraltik** [comment]
Flohack74, I want to sincerely thank you for fixing this issue! I have made calls the last couple of days and everybody said the echo issue was gone. Also the volume adjustment during calls now works and the volume is much better. Finally the phone is doing what it was meant for well :). I'll make a small donation today for your help.

**Comment by delijati** [comment]
@Flohack74 thanks so much for this :) Now also the "hand free" mic works but with the an echo. But that is fine for me. The biggest issue was the "normal" echo and this is resolved.

**Comment by Sconioo** [comment]
@Flohack74 Thank you sincerely for having solved the problem, now the echo to disappear, which (at the same time) makes the use of Linphone more pleasant
Nice work :)

**Comment by Flohack74** [comment]
@delijati What is "an echo"?

**Comment by Flohack74** [comment]
Thanks guys, was a pain for me as well. Next thing I try to take a look at is missing camera flash xD

**Comment by wayneoutthere** [comment]
nice work man

**Comment by delijati** [comment]
> @delijati What is "an echo"?

It's the same "echo" for the caller as it was with normal mic just in the "hand free" mode.

**Comment by tomoqv** [comment]
Is the code for this bugfix in any way affecting the Pro5 also? I have noticed a severe degradation of voice call quality recently, could be since updating to the latest RC. Sound is very choppy at both ends, almost like with a really bad GSM connection even though the connection looks fine and used to work without any choppiness in my house.

**Comment by tomoqv** [comment]
I could add that I today did a fresh install including wipe of my Pro 5. Have only tested one call so far, but problem seems to persist.

**Comment by Flohack74** [comment]
No, this was only applied to the hardware adaption repo of OPO.
