### ISSUE TITLE
Contact cannot be deleted

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#864]
Environment:
- Device: Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps:
1. Open contacts
2. Touch a contact until selected checkbox is shown
3. Select trashcan
4. Confirm with "Yes"

Expected:
- Contact is deleted

Actual:
- Contact is not deleted

**Comment by vlladdrakk** [comment]
I don't know if this is helpful, but I tested this on my nexus 4 on OTA-4 and could not replicate these results. Deleting any contacts worked fine. So I guess this bug may have been introduced after OTA-4.

**Comment by hummlbach** [comment]
@villaddrak which channel from which date have you tested with?
I can confirm this with makos dev channel from around 5th September. (Don't have the device at hand and don't know the exact date by heart.)
@mardy also side effect of the qtpim update?

**Comment by vlladdrakk** [comment]
@hummlbach I am running on the stable channel. 20180824-15370 is the build I am on.

**Comment by mardy** [comment]
I can reproduce it as well. I'm investigating :-)

**Comment by mardy** [comment]
This proposed fix works for me: https://github.com/ubports/address-book-service/pull/7

**Comment by padraic7a** [comment]
Checked on Hammerhead running 16.04 build 2018-10-02

This issue appears to be fixed.
