### ISSUE TITLE
Music app freezes and shutdown after selecting next title

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#865]
Environment:
- Device: Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps:
1. Open Music app
2. Select album
3. Select play all
4. Switch to and use another app
6. Swipe from right to left to show opened apps
7. Select music app
8. Select [>|]

Expected
- Next title is played
- played time counts up
- remaining time counts down
- Slider moves from left to right

Actual:
- Next title is played
- played time frozen at 0:00
- remaining time frozen
- Slider frozen
- Shutdown of music app before title completed

**Comment by Benni777** [comment]
Currently it is not possible to reproduce this issue systematically.

**Comment by ellypsis** [comment]
I also experiment this bug.
    Device: OPO (bacon), 16 GB
    OS: Ubuntu 16.04 (2018-08-24)
    Channel: stable
The bug also occurs when you don't switch to another app and come back.
I prevented the screen from locking, and kept the music app opened. After switching several tunes, the app crashed as described above, when using swap on folder cover or with button Next.

**Comment by ellypsis** [comment]
Maybe a admin could move this issue to [ubports/music-app](https://github.com/ubports/music-app)

**Comment by Flohack74** [comment]
This issue was moved to ubports/music-app#37
