### ISSUE TITLE
Albums are shown without cover in Music app

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#866]
Environment:
- Device: Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps:
- Open Music app

Expected
- Albums are displayed with specific cover

Actual:
- Album is displayed with default cover (sometimes)

**Comment by ernesst** [comment]
Most likely the mp3 file is not tag correctly. Not related to the app, can you confirm ?

**Comment by Benni777** [comment]
Hello, I tried below steps:

1. Open Music app
2. Albums are shown with cover
3. Select an album
4. Select play all
5. Swipe from right to left to shop opened apps
6. Swipe music app to the top to close it
7. Open music app

Expected:
- Albums shown with cover

Actual
- Albums shown with default cover

**Comment by ernesst** [comment]
I'm not understanding well the issue. The album cover are displayed correctly initially then after closing the app, the cover are not displayed correctly ?

Are you sure about the tag information of your mp3 ?

**Comment by Benni777** [comment]
Yes, the album covers ares displayed correctly initially then after closing the app, the cover are not displayed correctly. But only if I close the music app during a title is currently played. If I select [||] before, then the covers are displayed when open the music app again.

I found this bug because of issue #865.

**Comment by Benni777** [comment]
Yesterday I thought I could reproduce it. Today I tried again, but I could not reproduce it.

After work I would check tagging of my albums and also try again to find a way to reproduce it.

**Comment by Benni777** [comment]
Hello, I checked whether my MP3 files are are all tagged with a covers. I can confirm, that all files have the correct cover.

**Comment by ellypsis** [comment]
Maybe a admin could move this issue to [ubports/music-app](https://github.com/ubports/music-app)

**Comment by UniversalSuperBox** [comment]
Issue re-reported at ubports/music-app#40
