### ISSUE TITLE
Invalid state of message app after selecting a contact

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#867]
Environment:
- Device: Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps:
1. Open messages
2. Select [+] to write a new message
3. Select [+] to open contacts
4. Select a contact

Expected:
- Back in message app with contact selected

Actual:
- Back in message app with undefined state of GUI

**Comment by Benni777** [comment]
Same issue at:

Ubuntu 16.04 LTS - armhf (20180824)

**Comment by hummlbach** [comment]
@Benni777 I think I can reproduce that with todays (18/9/9) devel image on mako. Do you get this:

**Comment by Benni777** [comment]
Hello, yes this is the screen I get.

**Comment by hummlbach** [comment]
I just saw that its a duplicate of https://github.com/ubports/ubuntu-touch/issues/844.
