### ISSUE TITLE
Characters "ü", "ä" and "ö" are not imported correctly in contacts from vcard

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#868]
Environment:
- Device: Nexus 4 (mako), 16 GB
- OS: Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps:
1. Import vCard contacts into Contacts
2. Open contacts
3. Open contact

Actual:
- Character "ü" is imported as "=C3=BC"
- Example: "Baden-W=C3=BCrttemberg"

Expected
- Character "ü" is imported as "ü"
- Example: "Baden-Württemberg"

**Comment by Benni777** [comment]
Environment of  exporting therese vcard:
- Ubuntu Desktop
- Thunderbird

**Comment by Benni777** [comment]
Same issue at:

Ubuntu 16.04 UTS LTS - armhf (20180824)

**Comment by UniversalSuperBox** [comment]
@Benni777, do you have an example vcard (just one example, I recommend one that doesn't have anyone's actual contact information in it) that we can use to test?

**Comment by Danfro** [comment]
Hi, I am using a BQ E5 with 16.04 rc.
I did export and import contacts with dekko.
That works fine including äöüß.

I just tried to export an contact from thunderbird.
The Name "Dümmy GmbH" does look like this:
```
begin:vcard
fn;quoted-printable:D=C3=BCmmy GmbH
email;internet:duemmy@t-online.de
version:2.1
end:vcard
```
I can import this vcard back into thunderbird.
The =C3=BC gets imported fine as ü.

Importing it into contacts on my phone I do get "D=C3=BCmmy GmbH".
So ubuntu touch and thunderbird seem to speak different languages.
[Dümmy.zip](https://github.com/ubports/ubuntu-touch/files/2457266/Dummy.zip)

**Comment by balcy** [comment]
interestingly it does work with the long form of the encoding (as key-value pair)
```
begin:vcard
fn;encoding=quoted-printable:D=C3=BCmmy GmbH
email;internet:duemmy@t-online.de
version:2.1
end:vcard
```
The [vCard 2.1 spec](https://web.archive.org/web/20120501162958/http://www.imc.org/pdi/vcard-21.doc)  (linked in [wikipedia)](https://en.wikipedia.org/wiki/VCard) does allow the short and the long form (search for QUOTED-PRINTABLE in the .doc file).

*The property parameter expressions are specified as either a name=value or a value string. The value string can be specified alone in those cases where the value is unambiguous.* - very flexible isn't it ? : ) 

My guess is that in `QVersitReaderPrivate::unencode` (https://github.com/qt/qtpim/blob/dev/src/versit/qversitreader_p.cpp) the quoted-printable encoding is not detected, if the short form is used.

**Comment by lduboeuf** [comment]
moved to address book app:  https://gitlab.com/ubports/development/core/address-book-app/-/issues/227
