### ISSUE TITLE
Notes crashes at opening

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#880]
Environment
Nexus 4 (mako), 16 GB
Ubuntu 16.04 (2018-09-12)
Channel: dev

Steps
1. Open Notes (by Touch of the Icon)

Expected
- Notes opened

Actual
- Notes crashes
- Back at home screen

**Comment by vlladdrakk** [comment]
I can confirm, I have the same device on the same build and channel, and I am experiencing the same behavior.

**Comment by Arc676** [comment]
Can confirm on Nexus 5 (hammerhead) running 16.04 (2018-09-12).

**Comment by mardy** [comment]
This is due to the QtPim update:
```
NotesStore: Creating NotesStore instance.
reminders: relocation error: /usr/share/click/preinstalled/com.ubuntu.reminders/0.6.2/lib/arm-linux-gnueabihf/Evernote/libevernoteplugin.so: symbol _ZNK11QtOrganizer22QOrganizerCollectionId6isNullEv, version Qt_5 not defined in file libQt5Organizer.so.5 with link time reference
```
It's probably just a matter of rebuilding the application.

**Comment by mardy** [comment]
Duplicate of https://github.com/ubports/notes-app/issues/12
