### ISSUE TITLE
Double tap to (de)activate screen

### ISSUE THREAD

**Issue by fourloop2002** [ubports/ubuntu-touch#883]
FEATURE-REQUEST

### Description of the feature

I have a Nexus 5 running UT. I frequently read in the telegram groups the power button is a point of failure. To avoid this in future it would to very useful to have a double-tap facility to wake up the screen so the power button is not used as frequently. I have this feature on my daily driver (unfortunately not UT yet :-( )

How it works:
Double-tap anywhere on the blank screen to wake-up.  The screen displays the log-in screen.

Double tap notification area at top of screen to close/blank the screen.

- Device: Nexus 5
- Channel: n/a
- Build: n/a

**Comment by Arc676** [comment]
While I don't know how applicable this feature can be for the general user base, I can at least confirm that the power button on the N5 is indeed prone to debris and jamming.

A reasonable workaround is to avoid pushing down on the entire button and instead using your fingernail to gently click it. You can also jiggle the power button vertically to ensure it's not jammed, as the button is slightly free to move in the case.

**Comment by fourloop2002** [comment]
Thanks for the comment @Arc676.  The power button is just a side issue and only included in the Issue Description as background info.  I find the double-tap facility to be very useful on my OPO running CyanogenMod OS as it closes and opens the display easily and saves on battery usage, at least I like to think so ;-)

**Comment by sap-nocops** [comment]
there are already two issues opened about this:
[472](https://github.com/ubports/ubuntu-touch/issues/472)
[507](https://github.com/ubports/ubuntu-touch/issues/507)

if I understand it right

**Comment by fourloop2002** [comment]
Yes both #472 and #507 are what I was requesting.  The discussion on 507 is interesting.  I'll close this one and leave it to be followed in the earlier issues.  Hopefully we can see the feature implemented in OTA-5.

**Comment by fourloop2002** [comment]
See above
