### ISSUE TITLE
Message app keeps the onscreen keayboard expanded

### ISSUE THREAD

**Issue by ZikZakFR** [ubports/ubuntu-touch#889]
- Device: LGE Nexus 5
- Channel: Developpment
- Build: Ubuntu 16.04 (2018-09-21)

### Steps to reproduce
Open the "Messages" application
Open a message thread
On-screen keyaboard will be expanded without a way to collapse it, using more than half of the screen.

### Expected behavior
Keyboard must be collapsed by default when not selecting the text input field.

### Actual behavior
On-screen keyboard is expanded.

**Comment by ZikZakFR** [comment]
> 
> 
> You can drag down the OSK to hide. Doesn't that work? or I misunderstood your issue?

Unfortunately it doesn't.
Even displaying a simple picture from a message will keep the on-screen keyboard expanded.
It is simply always visible and can't be collapsed/hidden.

**Comment by kugiigi** [comment]
Actually, I can see this on my E5 with OTA-6 but it doesn't seem always happen.
It stays even you lock the screen or sometimes when going to the home screen/apps scope

**Comment by Flohack74** [comment]
I can see that the message input box is selected by default, and that triggers the keyboard. Shall we remove this focus event? Then probably the problem is diminished. We know that the keyboard likes to stay or hide itself sometimes without apparent reasons ;)

**Comment by kugiigi** [comment]
I'm thinking that it could also be a side effect of forcing focus on the compose field when flicking on the list view. I think focusing on the compose field is also important so it's not something we should remove.

**Comment by Flohack74** [comment]
Well for example in TELEports, when you click on any message the keyboard will hide as the input box looses focus. I do not think that it always needs to stay focused. People will rather honour that they have the full screen space for scrolling the message list.

**Comment by Lythimus** [comment]
I concur, I have to save MMS pictures into gallery and open in gallery in order to see the full image. A nuisance, but not a deal breaker. Conversely, if I switch to another app while in a message thread, and switch back, I can't get the keyboard to even appear when clicking the compose field.

**Comment by lduboeuf** [comment]
Don't seems to reproduce that now on devel ( at least since yesterday, i had the keyboard that overlapped the input text field only when unlocking the phone ( when the messaging-app was already open in message view ).

**Comment by lduboeuf** [comment]
@Lythimus for your picture view , this should be filled in another ticket
