### ISSUE TITLE
Setting up a Nextcloud user -> wrong username or password

### ISSUE THREAD

**Issue by YugiFanGX** [ubports/ubuntu-touch#893]
I have set up an user account for Nextcloud in my system settings.
As I already tried several scenarios, I know why my user credentials are wrong:

It is not allowed to use an "@" sign in the account name.
Please add support for this character.

(Let me recommend you to implement a sync for contacts as well)

**Comment by YugiFanGX** [comment]
I don't know how this code was implemented. On my desktop system I have set up such an account without problems. If UT uses some sort of API to Ubuntu - it might get fixed once you release 17.04 or 18.04

**Comment by trisimix** [comment]
Does anyone know where this code is?

**Comment by trisimix** [comment]
Thinking about attempting this as my first UT issue, it'll take me awhile though, probably.

**Comment by mardy** [comment]
Hi @trisimix, and thanks for your initiative! :-)
The repository is https://github.com/ubports/account-plugins, make sure you checkout the `xenial` branch, and not `master`.

**Comment by YugiFanGX** [comment]
Probably this is caused by the encoding?
https://github.com/ubports/account-plugins/blob/xenial/qml/nextcloud/NewAccount.qml#L210

**Comment by Flohack74** [comment]
It will take one night if it was merged properly into the repos ;)

**Comment by YugiFanGX** [comment]
I can't fix this. Currently `encodeURIcomponent()` is used, which is a huge security risk as the program ignores encoding of these characters:
 _ . ! ~ * ' ( ) -
(By using some brackets it is possible to execute code.)

Using only `encodeURI()` seems to be an alternative, as this function encodes special characters, except:
 , / ? : @ & = + $ #

But then it will probably misinterpret password and username..

**Comment by mardy** [comment]
Note that the password encoding was already fixed some time ago here: https://github.com/ubports/account-plugins/commit/87ed6896e462b1518ca4c6b56e749a77dd8b4517

@YugiFanGX I see that you initially removed the `encodeURIcomponent()` call completely; did it help in solving the issue? Have you been able find out what are the characters that should not be encoded?

**Comment by YugiFanGX** [comment]
@mardy I did not check these changes on my device, but I am pretty sure that this is the line, which makes some trouble. Even though I think that removing `encodeURIcomponent()` would fix the problem with my "@" character, it would allow the usage of other characters such as + ( and  ) .... I guess there is a meaning behind it, why the password encoding was added in the master branch again.

**Comment by mardy** [comment]
The password encoding was not added again: the `master` branch is older than the `xenial` branch, you should only look at the `xenial` one.

But indeed, I'm not sure what's the ideal solution here: according to the standards, both username and password should be URI-encoded. It looks like nextcloud might be at fault here; we need to find information on how exactly it expects username and password to be encoded.

**Comment by jonnius** [comment]
The master branch has never been changed, only the xenial branch. Tbh, I do not really understand the branch policy in the ubports repos and it does not seem to be consistent to me.

About the security concerns: Do you really think the nextcloud server would allow to execute code through misused username / password fields? I would expect the server to escape that. One could just try with his own nextcloud instance, I gues...

**Comment by YugiFanGX** [comment]
@jonnius No, not the server. I meant on the device itself. But now I am not quite sure..

**Comment by jonnius** [comment]
The html request is sent, not rendered on the phone. I don't see how this could be a danger.

**Comment by UniversalSuperBox** [comment]
I was able to add an account with the username `test@guy` and a password containing special characters to my device on the Nexus 7 (flo), Nexus 5, and Fairphone 2
