### ISSUE TITLE
Alarms can't be displayed nor edited

### ISSUE THREAD

**Issue by libra69de** [ubports/ubuntu-touch#894]
### Description of the bug
After upgrading to Ubtuntu touch version 15 (Ubuntu 16.04 (2018-W39) / 01.10.2018) the standard clock doesn't display alarms any more.
The alarms are still active, and I get a wake up alarm at 5:15 every morning, but I can't edit, activate or deactivate it any more.
If I open up the clock alarms, the display reads "Keine gespeicherten Wecker" (= "No stored alarms available").
Creating a new alarm seems to work regarding the wake up calls, but is also not displayed.

Please help !

### Illustrations

- Device: BQ 4.5
- Channel: Release Candidate
- Build: Version 15: Ubuntu 16.04 (2018-W39)

### Steps to reproduce
Open the clock and try to create an alarm, after saving it, it won't be displayed.

### Expected behavior
Editing existing alarms should be possible

### Actual behavior
No alarms are displayed, but in the background they are active

**Comment by dark-eye** [comment]
This is a QtPIM issue it was fixed on the 16.04/dev channel more detailed can be found in the following issues : https://github.com/ubports/clock-app/issues/102  and https://github.com/ubports/clock-app/issues/98 and #869.
I think you can edit it by using `syncevolution --print-items backend=evolution-tasks database=<time stamp>@ubuntu-phablet`.
You can find what databases you have by running `ls -l ~/.local/share/evolution/tasks`.

Hope this helps a little...

**Comment by libra69de** [comment]
Hi Eran dark-eye,
switching to the develop channel solved the issue.
Many many thanks for your help!
Best Regards
