### ISSUE TITLE
Echo heard during phone calls on hammerhead stable

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#9]
I have installed latest stable image (8/18/2016) to Nexus 5 phone. Software version is 15.04 (r10). Observation is that while making outgoing calls or receiving incoming calls, echo is heard on the other end by my callers.

This is happening since the time I've installed Ubuntu touch on Nexus 5 phone and each and every caller is complaining bad echo on their end, although voice is crystal clear at my end.

Let me know what information you need from my particular device. Thank you.

Reported by https://launchpad.net/~sagarpradhan-007

**Comment by HendriXXX** [comment]
My callers have been complaining that when I put N5 on speaker mode, then they hear their own voice as echo. It is quite bad what I've heard..
I'm on stable channel ota2.

**Comment by Flohack74** [comment]
I put this on needs confirmation, since the only confirmation is for loudspeaker mode. I used N5 now for some while myself, and never had echo problems...

**Comment by HendriXXX** [comment]
According my previous message, speaker mode echo problem has gone. My wife just said that voice was now super clear. I don't know which fixed problem, ota3 update or radio firmware update. :)

**Comment by advocatux** [comment]
I don't have this echo problem in my N5 (stable channel, ota-3)

Maybe we can close this bug.

**Comment by NeoTheThird** [comment]
Let's keep it open on needs confirmation for now, we'll need to keep an eye on this.

**Comment by UniversalSuperBox** [comment]
No new confirmations since original report.
