### ISSUE TITLE
Could not create online account in system settings

### ISSUE THREAD

**Issue by didderot** [ubports/ubuntu-touch#900]
- Device: Nexus 4
- Channel: 16.04 stable
- Build: OTA-4 20180824

### Steps to reproduce
Fresh install. Language "german" chosen.
I tried to create an account in the system settings page "accounts". When I clicked any of the account types, like "Owncloud" or so - nothing happend. 

### Expected behavior
The credentials form of the account type appears and I can create an account.

### Actual behavior
Nothing. Just the little blue circle appears for a fraction of a second.

### Logfiles and additional information
Later I discovered that when I switched the language setting of the phone from German to English it worked! The credentials form appeared when clicking on "Owncloud" and I could create the account. 
After this I switched back to German and tried it again, and now it also worked, but the credentials form was still in English. Maybe the form just crashed in the first try, because the translations where missing?

**Comment by Danfro** [comment]
Same here on my BQ E5.
Right after a clean install of 16.04 stable today I could not add an account [tried to add nextcloud].

I did install a few apps and a couple of reeboots as well - it is working now.
Unfortunately I can not remember if one reboot was sufficient to make it work.
The dialogs for setting up a nextcloud, CalDAV and owncloud accounts are not translated.
So maybe it is an language issue.
See attached screenshots. Done with German set for system language.

![screenshot20181007_220841589](https://user-images.githubusercontent.com/37637312/46586405-347b8380-ca7e-11e8-9580-cf76e5f00872.png)
![screenshot20181007_220926207](https://user-images.githubusercontent.com/37637312/46586410-39403780-ca7e-11e8-932c-9d8bd77a37df.png)
![screenshot20181007_220931546](https://user-images.githubusercontent.com/37637312/46586412-3d6c5500-ca7e-11e8-8b4f-a96330453ea9.png)

**Comment by kelmes** [comment]
I have the same problem as @Danfro in nextcloud, owncloud and caldav, the keyboard does not appear, and the only way to enter any text is to copy it from another application. This is entirely in English, however.

**Comment by laborim** [comment]
Software Version:
OnePlus 3
Channel: edge
Ubuntu 16.04 (2020-06-21)

What happened:
In the Accounts menu, in every, the keyboard doesn't appear to fill the credentials, even when the field is selected.
Tried both in portuguese and english.

What I expected to happen:
When the field is selected the keyboard shows up

Steps to reproduce:
Select Accounts menu and try to sign in any account.

**Comment by UniversalSuperBox** [comment]
I believe the original issue listed here, being unable to open the Accounts page to add a new account, has been resolved. The issue with the keyboard not showing up in Online Accounts on the OnePlus 3 or 3T is tracked as https://github.com/ubports/ubuntu-touch/issues/1678.
