### ISSUE TITLE
Include QtCharts in Qt

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#903]
### Description of the feature
Charts and graphs could be really helpful to many types of apps. Currently, a viable option is to use Chart.js but it isn't ideal and doesn't have many features. It would be nice to have official Qt charts integrated into apps.

**Comment by Flohack74** [comment]
Do you know the package name that is missing?

**Comment by tsimonq2** [comment]
QtCharts is `qtcharts-opensource-src` in Debian and Ubuntu.

**Comment by kugiigi** [comment]
I believe is now included in the image :)
