### ISSUE TITLE
[xenial]: Ensure the Desktop Apps scope is populated

### ISSUE THREAD

**Issue by TartanSpartan** [ubports/ubuntu-touch#906]
- Device: MX4, Pro 5, (very likely device-agnostic)
- Channel: Stable
- Build: OTA-4

### Steps to reproduce
Navigate to the Desktop Apps scope (if it is installed and a Libertine container has several programs installed)

### Expected behavior
The apps should be visually populated on the scope.You should be able to scroll through the apps and touch one to launch it. This was SOP on Vivid OTAs

### Actual behavior
This is not always the case, for some users/devices the scope becomes completely void on Xenial. But strangely it is not a problem for other users. I suspect the disrepancy is because some users (including me) built their container on Vivid, and it isn't populated after upgrading to Xenial, but possibly for other users who built their container on Xenial, it **is** populated

### Logfiles and additional information
A fix has been discovered on the forum. Again, this probably relates to an obsolete pair of files (or directories?) generated for users who built their container on VIvid, and these files are not deleted/replaced after the upgrade to Xenial. Therefore, the fix should be simple to implement into the OTA upgrade process: if a Libertine container exists (or specificially, exists and was built on Vivid) then delete these two files and after the OTA upgrade, the scope should become repopulated with zero break in user friendliness (novice users would feel intimidated by having to manually delete these on the terminal, or to install a newer build of the scope which Marius has distributed via Telegram, and that latter option is not persistent over reboots). The link to the fix is:

https://forums.ubports.com/topic/1741/desktop-apps-scope-is-always-void/11

The detail of the fix is to navigate in the terminal to /opt/click.ubuntu.com/libertine-scope.ubuntu/ and delete the two daughter files /current and /1.3.2.3.3, then to restart. Again, to have this be automated in the OTA process would be very nice.

**Comment by UniversalSuperBox** [comment]
It sounds like you have the old scope installed. You should be able to remove it from the newest version of the OpenStore. After refreshing the scope (or rebooting your device) you should have a working scope.
