### ISSUE TITLE
Qt Controls Demo installs, but displays Help About Buttonzilla device: hammerhead

### ISSUE THREAD

**Issue by omac777** [ubports/ubuntu-touch#912]
Nexus 5
ubuntu touch 16.04 2018-10-13

The Qt Controls Demo after launch displays what I perceive to be only the top right part of the qt window real estate within screen real-estate.  I desperately want to zoom out to see the entire qt window, but I can't.
The font text for the "help about" button item are HUGE and when I touch it the about dialog appears but I can't close it because the actual close button is located somewhere off the screen real-estate.

I can't zoom out to correct the scaling problem of the qt gui  in order to see the entire qt-window and the help about dialog and close the dialog.

For the past 10 touch updates, I have been installing qt controls demo and trying it and this bug still surfaces.  I uninstall it after that.

Ditto for kirigami demo.  It has similar bugs.  The Morph browser seems to suffer from this also.
Please bring back the Oxide browser as an available app in openstore until all the morph browser behaviour is correct and acceptable.  I would install both the Oxide and Morph Browser and run both in previous versions, but the latest few versions have blown away the old Oxide browser and I can't reinstall it.

Thank you.

**Comment by kugiigi** [comment]
There was an auto-scaling implemented in the later releases and caused the scaling issue with the qqc2 gallery app because it implements its own scaling logic.
I think you should file this bug in the gitlab page of qqc2 gallery app. Unless it is officially maintained by ubports?
https://gitlab.com/ubports/app-dev/qqc2-gallery

**Comment by UniversalSuperBox** [comment]
Should be fixed with later changes to correct auto-scaling and turn off manual scale factors for the affected apps. Please let me know if the behavior persists.
