### ISSUE TITLE
murph internet browser bugs

### ISSUE THREAD

**Issue by ivosvalek** [ubports/ubuntu-touch#913]
-------- BUG-REPORT ------------------------------------------------------------
-------- Something doesn't work the way you want it? That's a bug. -------------
1) The browser continuous playing of a sound (f.e. Youtube audio) even the panel with such multimedia has been closed. It is neccessary to close the browser comletely to stop the playing
2)the browser doesn't open previous web pages closed recently, even this setting is activated and the browser was closed with some pages opened. This means, that the browser always opens with homepage.

- Device: BQ M10 Aquaris FHD

### Expected behavior
I appreciate that murph keeps playing e.g. IPTV even I switch the browser to another tab opened, but the browser must stop playing audio when I close the tab with e.g. IPTV, Youtube etc...
When I close the murph with one or a few tabs opened, I expect that the browser will open the same tab or tabs again later...

### Actual behavior
1) The browser continuous playing of a sound (f.e. Youtube audio) even the panel with such multimedia has been closed. It is neccessary to close the browser comletely to stop the playing
2)the browser doesn't open previous web pages closed recently, even this setting is activated and the browser was closed with some pages opened. This means, that the browser always opens with homepage.

**Comment by UniversalSuperBox** [comment]
I've moved both of your bugs to https://github.com/ubports/morph-browser/issues/59 and https://github.com/ubports/morph-browser/issues/60. When reporting issues, please only report one issue per ticket
