### ISSUE TITLE
taking many photos causes keyboard (osk) to behave weird or disappear

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#915]
- Device: BQ E5 (vegetahd)
- Channel: rc
- Build: 2018-W41/2

### Steps to reproduce
- start camera app
- take many photos (20, 30 or 40), not sure, many ;-)
- start another app where you do need the osk (i.e terminal) or log off and try to log on again
### Expected behavior
keyboard responding normal

### Actual behavior
The keyboard (OSK) completely disappears or flickers when typing (see screenshots).
The keys are still there. So if you know where to press you can i.e. enter a password and log in.
After a reboot everything works fine again.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2475839/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2475840/UTlogcat.txt)
![screenshot20181012_170732924](https://user-images.githubusercontent.com/37637312/46909924-e4e3fe80-cf3a-11e8-847d-51d2d23ecb0f.png)
![screenshot20181012_170750162](https://user-images.githubusercontent.com/37637312/46909925-e4e3fe80-cf3a-11e8-8f4c-0ee605b3eabd.png)
![screenshot20181012_212121529](https://user-images.githubusercontent.com/37637312/46909926-e4e3fe80-cf3a-11e8-9b50-867748f1aa6f.png)

Could be also a memory issue and maybe related to #908.

**Comment by UniversalSuperBox** [comment]
Like #908, is this improved in 2018-W50?

**Comment by Danfro** [comment]
With rc 2018-W50 and zram providing more memory on the BQ E5 I can not reproduce this issue anymore. Please see #908 for further details.
Therefore I will mark it as solved.
