### ISSUE TITLE
pressing the search icon in address-book-app should open the keyboard

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#918]
- Device: BQ E5 (vegetahd)
- Channel: rc
- Build: 2018-W41/2

### Steps to reproduce
- open contact app
- tap on spyglass icon for search
- not the search field opens

### Expected behavior
- the keyboard should open as well, the search field should get the focus

### Actual behavior
- no keyboard appears
- swiping from the bottom brings up the "new contact" screen
- I have to tap the search bar to get the keyboard

I think this is since the W41 update, maybe even the upgrade to 16.04
On 15.04 it was working fine.

**Comment by UniversalSuperBox** [comment]
Keyboard focus can be automatically assigned like this: https://gitlab.com/ubports-linphone/linphone-simple/blob/master/qml/LinphoneAccount.qml#L20

**Comment by Danfro** [comment]
duplicate of [#56](https://github.com/ubports/address-book-app/issues/56)
