### ISSUE TITLE
No OTA-5 update

### ISSUE THREAD

**Issue by Dreamsorcerer** [ubports/ubuntu-touch#922]
The OTA-5 update was advertised as being available last week. I still have no system updates available when checking in the system settings.

Device: mako

**Comment by UniversalSuperBox** [comment]
The update is being phased in over a period of five days. Every device will be receiving the update at a random time. The phasing should be completed tomorrow (Wednesday, October 17th), so please let us know if you don't have the update by Thursday.

**Comment by Dreamsorcerer** [comment]
Ah, OK. Thought it was still a 24hr rollout.

**Comment by Dreamsorcerer** [comment]
Still no update found.

**Comment by kwah-gh** [comment]
Same here. No OTA-5 yet.
