### ISSUE TITLE
Mic on call problem

### ISSUE THREAD

**Issue by cryhos** [ubports/ubuntu-touch#925]
I can't make a call : my voice is not heard

I have the same problem when I'm using Android (LineageOS v15.1).
Some codes exist to correct this bug, but it works very randomly.

- Device: Bacon OnePlus One
- Channel: 16.04
- Build: OTA-5

### Steps to reproduce
Make a call

### Expected behavior
Microphone working on call

### Actual behavior
Microphone is not working : No sound is heard on the other side of the phone

**Comment by Flohack74** [comment]
Sorry to say but I have an OPO as daily and I never had this problem. I only had problems after a few minutes into a call that sometimes the other side would stop hearing me. But this could also be a network issue.

**Comment by sap-nocops** [comment]
I use the OPO as daily driver on OTA-5 stable and never ran into this issue. 
Probably it's an hardware problem since it does the same on LineageOS for you. 
What code are you referring to which fixes this problem?

**Comment by Flohack74** [comment]
@cryhos is this still an issue for you? If yes, please try out the latest devel build.

**Comment by cryhos** [comment]
Ok, I'll try the latest dev build. Thanks you.

Le 20 novembre 2018 14:19:55 GMT+01:00, Florian Leeber <notifications@github.com> a écrit :
>@cryhos is this still an issue for you? If yes, please try out the
>latest devel build.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubports/ubuntu-touch/issues/925#issuecomment-440270709

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cryhos** [comment]
Hello,

I tried the latest build with the development channel :

Version 2018-12-15
UBports Image Part 20181215-8621
16.04 LTS - armhf (20181215)
Device image part 20181214-15418
bacon-userdebug 5.1.1 LMY48W ac7c78eb2c test-keys

**I still have the problem.**
Under Android some bacon have this problem.

Some developers made patch :
https://forum.xda-developers.com/oneplus-one/development/fix-low-mic-call-t3055661
https://forum.xda-developers.com/oneplus-one/development/fix-low-metallic-voice-call-recordings-t3757335

I hope it will help you.

Thanks

**Comment by nicktelindert** [comment]
Same issue here and the speakerphone seems to be working fine just like @farsenfsd mentions. @Flohack74. I tried the development channel and stable channel.

**Comment by cryhos** [comment]
Ok, I'll try the builds.

Thanks

Le mercredi 23 décembre 2020 à 13:26 -0800, nicktelindert a écrit :

**Comment by Flohack74** [comment]
Can you try cleaning the small holes for the microphones? No joke, there are 3 tiny holes in the device, and if they are not working well then either voice recording or ambient sound suppression will not work well.

**Comment by cryhos** [comment]
I've already cleaned the microphone, but I'll do it again.

Thanks for the advice.

Le lundi 28 décembre 2020 à 15:39 -0800, Florian Leeber a écrit :

**Comment by nicktelindert** [comment]
@Flohack74 I tried to clean it but it makes no difference for me.

**Comment by cryhos** [comment]
Tried with 16/04 stable : no more mic...


Le samedi 02 janvier 2021 à 05:58 -0800, nicktelindert a écrit :

**Comment by nicktelindert** [comment]
I did some testing with the audiorecorder app and test every mic seperately while blocking the other microphones. All microphones record fine with the audiorecorder app. It obviously switches profiles when calling, is there something wrong the audio profile?

**Comment by nicktelindert** [comment]
While calling i get the following info from pulseaudio on the inputs:
2 sink input(s) available.
    index: 0
        driver: <protocol-native.c>
        flags: START_CORKED 
        state: CORKED
        sink: 0 <sink.primary>
        volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        muted: no
        current latency: 31,38 ms
        requested latency: 10,00 ms
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        resample method: speex-float-1
        module: 12
        client: 6 <QtPulseAudio:3642>
        properties:
                media.name = "QtPulseSample-3642-14730712"
                application.name = "QtPulseAudio:3642"
                native-protocol.peer = "UNIX socket client"
                native-protocol.version = "30"
                media.role = "feedbacksound"
                application.process.id = "3642"
                application.process.user = "phablet"
                application.process.host = "ubuntu-phablet"
                application.process.binary = "maliit-server"
                application.language = "nl_NL.UTF-8"
                application.process.machine_id = "ubuntu-phablet"
                application.process.session_id = "c2"
                module-stream-restore.id = "sink-input-by-media-role:feedbacksound"
    index: 71
        driver: <droid-sink.c>
        flags: START_CORKED NO_REMAP NO_REMIX 
        state: CORKED
        sink: 0 <sink.primary>
        volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        muted: no
        current latency: 0,00 ms
        requested latency: n/a
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        resample method: speex-float-1
        module: 5
        properties:
                media.name = "Virtual Stream for Voice Volume Control (Droid)"
                media.role = "phone"
                module-stream-restore.id = "sink-input-by-media-role:phone"

Is it normal to have state: Corked?

**Comment by Flohack74** [comment]
Idk all I can say is I used a Oneplus One for over 2 years and never had this problem.

**Comment by nicktelindert** [comment]
@Flohack74 Are there different version of the Oneplus One with different mic setup?

**Comment by Flohack74** [comment]
I dont think so. But there could be small variants that lead to different audio paths and we might not adapt correctly to them. However, please wait with further investigations until we finish the upgrade to 7.1 Android base for that device, it might fix such things.

**Comment by nicktelindert** [comment]
@Flohack74 No problem, i wait for the halium 7.1 upgrade. In the meantime i can switch to a spare nexus 5.

**Comment by cryhos** [comment]
OK, thanks for your job and I'll install the next version for testing.


Le vendredi 15 janvier 2021 à 01:08 -0800, Florian Leeber a écrit :

**Comment by nicktelindert** [comment]
I did some testing on lineage 17.1 and i can confirm it is an hardware issue and not an issue with ubports. It probably has something to do with noise cancelling not working properly

**Comment by Flohack74** [comment]
Ok then I close here for the time being :)
