### ISSUE TITLE
UT 16.04 update not received

### ISSUE THREAD

**Issue by luk-s** [ubports/ubuntu-touch#928]
I hope I'm not too early with creating this bug report. If you would like any additional information, log files etc. just ask. 

- Device: Fairphone 2
- OS: Ubuntu 15.04 (r3)
- Channel: stable

### Steps to reproduce

1. Open the system-settings app
2. Go to 'About'
3. Click on 'Check for updates'

### Expected behavior

OS update gets downloaded and installed.

### Actual behavior

Nothing appears except the message: "Software is up to date"

### Logfiles and additional information

[application-legacy-ubuntu-system-settings-.log](https://paste.ubuntu.com/p/8Fmdwk46tk/)
[dmesg](https://paste.ubuntu.com/p/j9DmGQYmbz/)
[/var/log/syslog](https://paste.ubuntu.com/p/fY54v2R7vG/)
[~/.cache/ubuntu-download-manager/log[date&time]](https://paste.ubuntu.com/p/njMMZY22Bs/)

**Comment by kugiigi** [comment]
Same issue on my BQ E5 on OTA-3 (vivid r3).
Same error: `Failed to parse availaleVersion`

**Comment by gurucubano** [comment]
same here with a BQ E4.5; but with some other picture in the log file:

```
$ cat .log20181019-092658.5847
Log file created at: 2018/10/19 09:26:58
Running on machine: ubuntu-phablet
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1019 09:26:58.089702  5847 base_daemon.cpp:204] Timeout is enabled: 1

[ at this point in time the app on the screen says 'uptodate', but the log continues ]


I1019 09:26:58.090562  5847 base_daemon.cpp:206] Daemon is stoppable: 0
I1019 09:26:58.095052  5847 downloads_db.cpp:151] Db file is  /home/phablet/.local/share/ubuntu-download-manager/ubuntu-download-manager/downloads.db
I1019 09:26:58.099221  5847 network_session.cpp:100] Instance is null
I1019 09:26:58.099289  5847 network_session.cpp:103] Create new instance
I1019 09:26:58.442880  5847 network_session.cpp:68] Connection type 802-11-wireless
I1019 09:26:58.443616  5847 manager.cpp:113] virtual void Ubuntu::DownloadManager::Daemon::DownloadManager::setAcceptedCertificates(const QList<QSslCertificate>&)
I1019 09:26:58.445240  5847 base_daemon.cpp:122] Service registered to com.canonical.applications.Downloader
I1019 09:26:58.450542  5847 manager.cpp:131] Owner is:  :1.120
I1019 09:26:58.454000  5847 manager.cpp:131] Owner is:  :1.120
I1019 09:26:58.454699  5847 manager.cpp:359] Returning uncollected downloads for app with id ubuntu-system-settings
I1019 09:27:28.472048  5847 base_daemon.cpp:152] Timeout reached, shutdown service.

```
all the logs show the same error `Timeout reached`; only the logs for updating the apps are different;

**Comment by jarsao** [comment]
Nexus 5. OTA-3  - Failed to parse availableVersion

**Comment by AlanGriffiths** [comment]
Nexus 4 - OTA-3
Nexus 10 - OTA-3

**Comment by kwah-gh** [comment]
Have FP2 that did not receive update as well.

**Comment by MenmuirMark** [comment]
OTA updates have always taken a long time to show on my BQ E4.5
I have a maximum 512kB/s download speed from our broadband which I had thought may contribute. However if I switch to RC channel it starts to download the update right away.

**Comment by gurucubano** [comment]
> OTA updates have always taken a long time to show on my BQ E4.5
> I have a maximum 512kB/s download speed from our broadband which I had thought may contribute. However if I switch to RC channel it starts to download the update right away.

I do not speak about **download** Timeout (I have switched auto-download to 'never'), but something else is timing out as far as the logs say. And the GUI of the app says "all uptodate" within 1-2 secs. There must be something broken, maybe in the database ` ubuntu-download-manager/ubuntu-download-manager/downloads.db `

**Comment by mdehollander** [comment]
Same here on Meizu MX4 running ota-3

**Comment by AlanGriffiths** [comment]
A workaround that worked on my N4:

1. Switch to RC
2. Update all apps 
3. Switch to stable

**Comment by luk-s** [comment]
@AlanGriffiths 
Thanks for the hint, this worked for me on my FP2!

**Comment by kwah-gh** [comment]
@AlanGriffiths 
Switched FP2 to rc channel. It said there is update to version 23 (or something like that). So, I've updated the phone. When I tried to switch it back to stable, it _hanged_ for a long time... And showed yet another update downloaded and ready for install. So, long hang upon channel switch is probably related to the fact that it was doing a lot of downloading, while not making any UI updates.

About screen now shows that phone has 16.04 (2018-W39), while updater offers to install version 17.

Then I switched it back to rc again. Updater still offers to install version 17 o_O.

Now I am confused and probably system updater on my FP2 as well. Any ideas?

**Comment by luk-s** [comment]
Hi @kwah-gh 
I too had to try a bit out. What in the end worked for me was:

1. Switch to rc channel
2. Download and install update (This is OTA 4)
3. Download and install the second update (This is now OTA 5 (but still rc))
4. Switch channel back to stable
5. The OTA 5 update stable will be downloaded and can be installed

I too tried to switch channels after the first update which didn't work. I also rebooted a few times. I also had these kind of strange version numbers. But in the end everything worked out nicely. I think a quick check to see on which version you are at the moment is to look at the name of your browser. In OTA 5 it should be called 'Morph Browser'. Otherwise you're still on OTA 4 or lower and have to continue updating.

**Comment by kwah-gh** [comment]
Hi @luk-s 
Thanks for the tips. I actually do continue updates as well. Just wish it was communicated upfront, which version should be reported by the system.

**Comment by kugiigi** [comment]
An update now shows on my bq E5. It is version 4 and I'm would think this is already OTA-5.
Not sure if someone fixed something or the phased update was just extended to more than 5 days.

**Comment by AlanGriffiths** [comment]
Yes, Version 4 is now showing on my N10.

**Comment by MenmuirMark** [comment]
I used the RC route last night and I'm now on 16:04, Ubuntu Touch version 17, OS build number 2018-W42 on my BQ E4.5. Other than having had to re-install Telegram to get it working everything seems fine. It seems like I could have been a little more patient and got the update through this morning :)

**Comment by mdehollander** [comment]
It looks like the queue has been given a push since I received the update yesterday on my mx4. In the update window is says 'version 3' but it contains OTA-6 with 16.04 LTS. So that seems fine.

**Comment by UniversalSuperBox** [comment]
Was everyone here able to receive the OTA-5 update?

**Comment by AlanGriffiths** [comment]
> Was everyone here able to receive the OTA-5 update?

[I did](https://github.com/ubports/ubuntu-touch/issues/928#issuecomment-431567533).

I don't know if it just became available later than advertised, or if somebody fixed something to make it available.

**Comment by luk-s** [comment]
Hi @Flohack74 I actually upgraded manually by switching to the rc channel, upgrading and then switching back to stable. I guess I just wasn't patient enough to wait any longer for the update. I'm sorry, I'm quite new to Github. Is it my job to mark the bug report as closed?

**Comment by Flohack74** [comment]
No I can do thx ;)

**Comment by AlanGriffiths** [comment]
@Flohack74 I don't know if anyone knows, but if they do it would be good for future releases to document whether:
1. a problem was identified and fixed;
2.  "five day" rollouts actually take seven days; or,
3. Something else.

**Comment by Flohack74** [comment]
The next OTA will send broadcast messages to wakeup the local agents, and everyone should get a notification when their update has been downloaded :)

**Comment by mdehollander** [comment]
I did not receive any updates for OTA-7 yet. Giving it a week after the release on dec 7, i think the new broadcast does not work completely. Anyone else who did not get this update?

**Comment by dobey** [comment]
You might need to check manually in _System Settings_ for the update. I think there may be a problem with the notification as relates to the staged update of releases in the stable channel.

**Comment by mdehollander** [comment]
Strange, i did that before. I had to go to update settings -> channels (and not changing anything, i was already on stable) to get the update.

**Comment by paulmueller** [comment]
@Flohack74 @mdehollander 
I just tried to update my M10 FHD to OTA-6 [sic]. It did not work when checking for updates manually. It did work after selecting the RC channel. I did not try to just do "update settings -> channels (and not changing anything)". This still looks like a bug to me...

**Comment by paulmueller** [comment]
In system settings, my OS build number is now "2018-W01" and UBports Image part is "20181231-2287". So I somehow managed to switch from OTA-5 to an RC image?

Is that bad (with incremental updates in mind)?

**Comment by UniversalSuperBox** [comment]
@paulmueller, No, it sounds like you are safely on the RC channel now. You may switch back to the stable channel at any time by repeating the steps you used to switch to RC.

For anyone who is experiencing a problem with not receiving an update, please go to "System Settings -> About -> Check For Updates," wait for it to finish, then grab the log file at `/var/log/system-image/client.log` on your device. Providing that log will be a huge help for us to track down this issue.

**Comment by kugiigi** [comment]
[client.log](https://github.com/ubports/ubuntu-touch/files/2753279/client.log)
This is the log from my bq E5 which had the same issue in OTA5.

**Comment by AlanGriffiths** [comment]
N5
[client.log](https://github.com/ubports/ubuntu-touch/files/2753339/client.log)

**Comment by UniversalSuperBox** [comment]
![image](https://user-images.githubusercontent.com/21966173/51089101-5e9faa00-172d-11e9-82ed-6fe0aa6ba4c9.png)

I think this is our problem. One of our release commands must not be doing what we expect it to do, the phase percentage is only at 50% when it should be at 100% today. This is the same across all devices. I'll investigate further.
