### ISSUE TITLE
Autocomplete in terminal not working

### ISSUE THREAD

**Issue by corrosab** [ubports/ubuntu-touch#930]
- Device: bq E5
- Channel: Stable
- Build: OTA5

### Steps to reproduce
Trying to launch media player application to play a video through the  terminal to avoid media-hub to copy the video into "imported" folder:
1- "tap" to autocomplete when indicating the file does not work
2- Media-player does not recognises the file thus does not open

Command: "ubuntu-app-launch mediaplayer-app file:///(path_to_video)"

### Expected behavior
Tap to autocomplete working and media-player recognizing the file (same as in OTA3)

### Actual behavior
Described above

### Logfiles and additional information
No log files

**Comment by balcy** [comment]
this is working again in RC and should be via OTA6:
https://github.com/ubports/ubuntu-touch/issues/769

**Comment by balcy** [comment]
oh maybe I've not fully read the issue, what I mentioned is only about autocomplete, the mediaplayer issue I've not tested.

**Comment by balcy** [comment]
for the autocompletion as workaround you could create `mediaplayer.sh` in the home folder:
`mediaFile=$(readlink -f "$1")`
`ubuntu-app-launch mediaplayer-app "file://$mediaFile"`
and use autocompletion with that.

**Comment by corrosab** [comment]
Dear Chris.

Thanks for your kidness.

Unless I' m wrong, I have to launch the script then I will be asked for the
file I want to play (with selfcompletion) then it will be sent as an
argument to the mediaplayer. Am I correct?


Thanks in advance!

Regards.
Marcos Alonso

**Comment by balcy** [comment]
Actually I thought, because general autocomplete works on RC / OTA6, you can call the script with the video as first parameter `mediaplayer.sh video.mp4` and then it calls mediaplayer with it

**Comment by corrosab** [comment]
Hi Chris.

Sorry for coming back so late. I m facing some crazy weeks.

I tested the script and works fine in terms of the autocompletion.

However, I have realized that no matter if through the script or directly
from the terminal, the media player does not recognises the argument (not
sure if that's the technical name. In other words, the file path) and asks
to select one file.

I guess something has changed on the media player application.

When I can get some time, I will fill a bug.

Again, thanks for your support and making UT so fantastic!

Regards.
Marcos Alonso

**Comment by UniversalSuperBox** [comment]
It is uncommon to launch Ubuntu Touch applications from the terminal, and then, even more so with `ubuntu-app-launch`. It's possible that you'd be able to use url-handler to directly launch the Music app, but I believe this would still be subject to change in the future.

I'll close this issue for now since it's more of a unexpected feature than a designed one... Maybe if you explained what you'd like to do in the support section of https://forums.ubports.com, someone might be able to offer an alternative that works better for you?
