### ISSUE TITLE
Unable to edit settings

### ISSUE THREAD

**Issue by JassMan23** [ubports/ubuntu-touch#937]
**- Device:** hammerhead
**- Channel:** Xenial Stable and dev 
**- Build:** 16.04.5 / all up to 667

**Steps to reproduce**
Open Dekko/Dekkan settings.  --> Accounts --> [any account] -->Details
Change the account nickname, return to Account Settings, return to Manage.

**Expected behavior**
expect to see new nickname in the list replacing the one you were editing

**Actual behavior**
Old details restored. 

**Logfiles and additional information**
unfortunately due to some other bug I am currently unable pastebin the log.
However, i think the relevant part is
[dekko.plugman.action] >>Action loaded for "Dekko::Settings::AccountAction"
[<time>[dekko.plugman.incubator] >> Incubator finished and ready to hatch.
[<time>[dekko.plugman.incubator] >> Finished incubating
[dekko.plugman.action] >>Action loaded for "Dekko::Settings::AccountAction"
[<time>Qobject::startTimer::startTimer: Timers cannot be started from another thread
other times it says as above except timer waring. Instead it says
[<time\>[qml]>>Destroying item:DekkoPage_QMLTYPE_201(0x1428250)

hope that is helpful

**Comment by hummlbach** [comment]
@JassMan23 thanks for creating the bug report, but unfortunately this is the wrong bug tracker... Please file it again in dekko ces bug tracker: https://gitlab.com/dekkan/dekko/issues
