### ISSUE TITLE
Morph Browser - Can't remove all text from Google Search box.

### ISSUE THREAD

**Issue by davidmattson1** [ubports/ubuntu-touch#941]
BUG-REPORT

- Device: Nexus 5
- Channel: Stable
- Build: OTA-5

### Steps to reproduce
1. Open Morph Browser
2. Go to Google.com
3. Search for 'Test' and search
4. Try to remove all the text from the search box to search again. (Backspace 4 times)
5. It shows Test in the search box again

### Expected behavior
Allow me to remove all the text and leave it blank

### Actual behavior
Deleting all the text makes it show Test again

### Logfiles and additional information
Not sure that I can.

**Comment by xqqy** [comment]
Same problem in bing China and Chinese input
It seems after switch input language will solve the problem

**Comment by davidmattson1** [comment]
I copied this to the Morph-Browser project instead.  I'm guessing this can be closed.
