### ISSUE TITLE
Unzip action need a progressbar

### ISSUE THREAD

**Issue by xqqy** [ubports/ubuntu-touch#943]
### **Description of the feature**
Now, when unzipping, it only shows a unknown length of progressbar. When unzipping take a lot of time, this feel really bad. Because of unknown time.
It is easy to set how many file are already unzipped and how many a the rest. And a progressbar for known time is great.

**Comment by dobey** [comment]
Can you be more specific about what this feature request is for? What unzip action?

**Comment by xqqy** [comment]
It is:
open a .zip file in folder manager then click it and choose unpack it here.

**Comment by Flohack74** [comment]
Is this about filemanager-app? then plz file here: https://translate.ubports.com/projects/ubports/filemanager-app/

**Comment by dobey** [comment]
Does file manager offer that? On UT? Or is this a bug about the `file-roller` application on normal Ubuntu on a PC?

**Comment by Flohack74** [comment]
Ha maybe he found the wrong place here :)
