### ISSUE TITLE
Orientation lock quick setting is mislabeled

### ISSUE THREAD

**Issue by vlladdrakk** [ubports/ubuntu-touch#947]
- Device: Nexus 4 (Mako)
- Channel: dev
- Build: 2018-11-01

### Steps to reproduce

1. Swipe down on the status bar to reveal the notifications pane.
2. scroll allong the quick settings until you see where orientation lock is.

### Expected behavior

The label is indicator-orientation-lock.

### Actual behavior

It used to say 'Orientation Lock. if I am not mistaken.

### Logfiles and additional information

my appologies if my terminology is incorrect.

**Comment by Danfro** [comment]
I am on 16.04 rc 2018-W45. 
Just one question: Do you have UTweak Tools installed?
The orientation lock used to be fine with the expected labelling.
Yesterday I did install UTweak Tool. That did mess up the labelling of the orientation lock to "indicator-orientation-lock" and there is no button to switch it on or off anymore.
Uninstalling UTweak Tool did bring back the correct labelling.

**Comment by vlladdrakk** [comment]
I didn't have UT Tweak Tool installed, but the issue has been resolved since. I see the proper label now.

**Comment by Danfro** [comment]
Same here. Reinstalled UT Tweak Tool and no problem. Everything is fine. Looks like there was another reason for it. But if this is sorted you may as well close this issue?

**Comment by kugiigi** [comment]
This issue happens whenever an indicator failed to start so this applies to all indicators.
I'm not sure the reason why some indicators sometimes fails to start but a reboot usually fixes them.
