### ISSUE TITLE
Ship PyOtherSide in the base image

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#95]
Many Click app developers use pyotherside to write Qt apps in python. In the past, they have had to ship their own copy of the library in their Click. It was decided at [our last developer meeting](https://forums.ubports.com/topic/273/june-1-2017-app-developer-os-developer-meeting/2) that this library should be shipped in the base image.

**Comment by dpniel** [comment]
It would also be good to grab the latest release from upstream instead of taking the one from the xenial archive as there has been 4 or 5 releases since then with some fixes that came up during UT development like https://github.com/thp/pyotherside/issues/86
