### ISSUE TITLE
Increace swap space

### ISSUE THREAD

**Issue by Talkless** [ubports/ubuntu-touch#965]
Hi,

After upgrading from OTA-3 to OTA-5, Unity has started crashing often. uNav, Reddit webapp, browser invokes crash for whole destkop - Untiy reboots, showing loading dots...

I've noticed that swap space is only 32MB. I believe in Canonical times it was around 500MB, but I might recall badly.

Anyway, I did experiment:

-   Rebooted so that OS memory would be as clear as possible.
-   ssh'ed into it and watched `free -m` output - it started with about (only!) 270MB available memory.
-   Launched uNav, and kept scrolling _as if_ I was driving. Available memory started to shrink.
-   After some time, available memory got down to tenths of megabytes, and whole Untiy crashed!

Then, I've increaced swap size:
```
cd /userdata/
sudo swapoff SWAP.img
sudo fallocate -l 1000000000 SWAP.img
sudo mkswap SWAP.img
sudo swapon SWAP.img
```

After this, uNav did not reproduce system crash. I see about ~180MB of swap used up constantly. System looks more stable, at least for now. 32MB default swap is really unrealistic on this device.

Please increase default swap size at least on small-memory devices such as BQ E5.

**Comment by dobey** [comment]
While the concern is understandable, increasing the swap space is not an appropriate solution, as it will greatly reduce the lifespan of the internal storage flash on these devices, due to the vastly increased number of writes that using it as swap would create.

This is I think caused by a bug in the browser, which if I understand correctly, has been improved in the current RC build. Can you test the RC channel to see if this behaves better for you?

**Comment by Talkless** [comment]
You mean it's more like a memory leak? Does uNav use the same browser component?

**Comment by UniversalSuperBox** [comment]
I tried to decrease Unity8's out-of-memory score, but unfortunately you're not allowed to do that in Upstart session jobs. Seems like no one but root is allowed to set the score adjustments.

**Comment by UniversalSuperBox** [comment]
The issue seems to be that zram, which compresses data in RAM, was not getting started on boot on devices where it is configured. ubports/lxc-android-config#20 should fix it.

**Comment by Talkless** [comment]
But that zram is only for android-container, i.e. on android subsystem, drivers..? Or it's more?

 Will it actually conserve enough to have significant more memory for apps?

**Comment by UniversalSuperBox** [comment]
The E5 and E4.5 allocate 512 MB of zram by default, which is mounted in the Ubuntu userspace. It will not provide you with 1GB more space. You will be able to run apps more like before the 16.04 transition.
