### ISSUE TITLE
Top/Indicator bar won't pull down/expand.

### ISSUE THREAD

**Issue by Thovthe** [ubports/ubuntu-touch#966]
- Device: Nexus 5 "hammerhead"
- Channel: Stable
- Build: OTA5

### Steps to reproduce
Not clear to me.  This issue is primarily to provide something for other people experiencing this bug to find.

Turned off phone for a few days then turned it back on and the issue has persisted through reboots since.

### Expected behavior

Swipe down from where the indicator bar is and have it expand.

### Actual behavior

Bar stays compacted/unexpanded.

### Logfiles and additional information

- Indicators still appear to update despite being otherwise unresponsive.
- Tried many UTTweak Tool settings.
- Tested if it was a hardware/digitizer issue using drawing application in both horizontal and vertical orientations.
- Can't pull down in any orientation.

**Can anyone suggest a potentially useful log?**

**Comment by Thovthe** [comment]
Changing update channels didn't fix the issue.

At the cost of all applications and settings `Settings -> System -> Reset -> Erase & Reset All` got rid of the issue.

**Comment by UniversalSuperBox** [comment]
Yes, this was a really strange issue. I'm glad you were able to get it resolved. I'll close this for now, but we can reopen it if someone else ever comes upon the same issue.
