### ISSUE TITLE
Contacts - Search Does Not Work

### ISSUE THREAD

**Issue by nikhilbhalwankar** [ubports/ubuntu-touch#967]
- Device: vagetahd
- Channel: 16.04 Stable
- Build: OTA-5

### Steps to reproduce
- Go to Contacts Application
- Search Contact by Name in textbox
- Nothing happens
- Only option available is to manually scroll to the contact. This is very time consuming.

### Expected behavior
Searching a contact by name should show the desired contact

### Actual behavior
Search does not work

**Note:- I have installed OTA5 with Full Wipe**

**Comment by hummlbach** [comment]
This is already tracked here: https://github.com/ubports/address-book-app/issues/56

**Comment by Mraanderson** [comment]
- Device: hammerhead
- Channel: 16.04 Stable
- Build: OTA-5

Search working. With any part of contact info e.g. using Y filters all containing a Y.
