### ISSUE TITLE
UBPORT installer keeps saying in a popup "Couldn't download device list" in ubuntu for my device OPO

### ISSUE THREAD

**Issue by uma-hs** [ubports/ubuntu-touch#969]
![screenshot from 2018-11-29 21-06-46](https://user-images.githubusercontent.com/11327160/49232842-c074b080-f41a-11e8-8de7-44bd614b84c7.png)

### Illustrations

- Device: OnePlusOne
- Channel:
- Build: LineageOS build 27 Nov 2018

### Steps to reproduce

 I installed ubports installer from debian package in my ubuntu os.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

So when i open ubport installer app and even though i connected to usb with debugging enabled, i keep getting the popup(screenshot attached).

**Comment by UniversalSuperBox** [comment]
This error should only occur if you are having trouble accessing https://api.ubports.com/ for some reason. Could you try browsing to this site, then using the installer again?

**Comment by uma-hs** [comment]
Perfect worked fine after changing ISP.
