### ISSUE TITLE
Change the style of the Switch Components

### ISSUE THREAD

**Issue by mymike00** [ubports/ubuntu-touch#97]
Is it possible to change the `Switch` style with the old one (Ubuntu.Components 1.2 and before)?
I liked it very much instead this too simple new one...

**Comment by NeoTheThird** [comment]
Could you post screen-shots to illustrate?

**Comment by mymike00** [comment]
Sure!

- This is the actual Switch Component (switched on and off)
  ![switch_1 3](https://user-images.githubusercontent.com/28359593/27013277-64cf574c-4ee1-11e7-8577-89b19f7fe282.png)
- And this was the old Switch Component
  ![switch_1 2](https://user-images.githubusercontent.com/28359593/27013287-8e896ae6-4ee1-11e7-9060-692599311c1a.png)

I like the second also because of transitions when I toggle the Switch (now I don't know how to record the screen to show the transitions etc... but if it's needed I can look for a solution. Or, if you want, just do a QML app with a `Switch` and `import Ubuntu.Components 1.2`)

**Comment by mymike00** [comment]
ok, this is the animation of the switch v1.2. see how the tick and the cross moves left/right when you switch it
![ubuntu components switch-1 2](https://user-images.githubusercontent.com/28359593/27711018-faef0b34-5d21-11e7-9f55-f400a3cea224.gif)
while the v1.3 of the same component is too simple IMO...
![ubuntu components switch-1 3](https://user-images.githubusercontent.com/28359593/27711019-faf882f4-5d21-11e7-866c-c9dac4f8f7bd.gif)

**Comment by NeoTheThird** [comment]
Ok, thanks for the clarification, that does indeed look neat. Let's investigate this :)

**Comment by mymike00** [comment]
![immagine](https://user-images.githubusercontent.com/28359593/36911462-e09ab010-1e43-11e8-9196-3eef38e9617a.png)
I tried to update the look of the old Switch using `aspect: UbuntuShape.Flat` or `UbuntuShape.DropShadow` in both the `UbuntuShape`s (the gray/green one that moves left-right and the big one, which contains the whole component)

**Comment by mymike00** [comment]
Sure for that, but I opened this ticket because I like more the look of the old one. if you all disagree we can just close the issue...

**Comment by cibersheep** [comment]
You're opinion is very valid of course.
Let's leave it open and come back to it in the future

**Comment by hummlbach** [comment]
I like the new switch much more, since the old one looks unnatural to me, but if you have problems distinguishing colors you have to know and keep in mind which is 'on'. So for accebility reasons the old one may be better. So maybe we could have it in some accessibility settings in the settings app.(?)

**Comment by mymike00** [comment]
no, my reason was only about the look of the switch. no accessibility problem. I also like very much the transition of the symbols (the tick and the cross) when triggering a switch...

**Comment by hummlbach** [comment]
I didn't think you needed it for accessibility reason. Just wanted to say that this may be an argument to bring the back as an option/setting. (but may be hard to make this configurable...(?))

**Comment by mymike00** [comment]
Well, idk if it make sense making it configurable...
anyway I saw how's the look in qqc2 suru style:

![switch-off-lighttheme](https://user-images.githubusercontent.com/28359593/49640360-b3a11f80-fa0d-11e8-931b-cea2c3ae89f2.png)![switch-on-lighttheme](https://user-images.githubusercontent.com/28359593/49640358-b13ec580-fa0d-11e8-941c-fa1b9cdeed99.png)
![switch-off-darktheme](https://user-images.githubusercontent.com/28359593/49640359-b3088900-fa0d-11e8-86e5-e63981996a4b.png)![switch-on-darktheme](https://user-images.githubusercontent.com/28359593/49640357-b0a62f00-fa0d-11e8-8c6b-18949caba88d.png)

**Comment by mymike00** [comment]
I don't think this issue make sense anymore since there will be better alternatives to uuitk
