### ISSUE TITLE
OTA-5 bluetooth regression: No audio upon phone call (Skoda)

### ISSUE THREAD

**Issue by kwah-gh** [ubports/ubuntu-touch#970]
- Device: krillin 
- Channel: stable (presumably)
- Build: OTA-5 (presumably)

### Steps to reproduce
Connect phone to the car kit
Receive the call

### Expected behavior
It is possible to make a phone call using connected car kit.

### Actual behavior
No audio on the car kit.

### Logfiles and additional information
Is there a specific set of logs relevant for bluetooth diagnostics?

**Comment by UniversalSuperBox** [comment]
Does the audio output work *once* after the device is initially paired, as in https://github.com/ubports/ubuntu-touch/issues/994?

**Comment by kwah-gh** [comment]
No. I cannot receive even one call.

What I tried:
* Unpair phone from the car kit
* Reboot the phone
* Pair phone to the car kit
* Call phone from the other phone

For the first call, ringtone of the incoming call is picked up by car audio. But no sound/mic for actual call is working.

From the second call onward - no audio at all. Phone just vibrates, car kit indicates incoming call without the ringtone sound. The second call upon picking up switches to the "private" mode, according to the car kit. No audio at all. No sound via car kit, no sound on the phone either.

**Comment by UniversalSuperBox** [comment]
One sound per pairing. Yes, that does sound like #994. I'll mark this as a duplicate.
