### ISSUE TITLE
OTA-5 (krillin): No channel selector in "System Settings -> Updates -> Update Settings"

### ISSUE THREAD

**Issue by kwah-gh** [ubports/ubuntu-touch#971]
- Device: krillin 
- Channel: 16.04 / stable (?)
- Build: ?

### Steps to reproduce
Go to System Settings -> Updates -> Update Settings

### Expected behavior
Channel selector should be available

### Actual behavior
No selector.

### Logfiles and additional information
While on OTA-3, I could not get OTA-5 update, so I switched from stable to rc channel. After that update was picked up. I updated the system, and switched back to stable. After a while (don't know when) channel selector disappeared.

**Comment by james-lyon** [comment]
I can't reproduce this issue, the channel selector is available on my device:

- Device: BQ E4.5 (krillin)
- Channel: Stable
- Ubuntu16.04 (OTA-5)

**Comment by kwah-gh** [comment]
Well, good for you.

Anyway, it might be an artifact of how I got to 16.04. Just reinstalled 16.04/stable using installer without wiping of the data. Got back channel selector.

Will close for now.
