### ISSUE TITLE
Add addressee through messaging app is not working

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#977]
I cannot add 2 or more addressees to my text (messaging app).

- Device: LGE Nexus 4
- Channel: stable
- Build: OTA-5

Steps to reproduce
I cannot add an addresse to any of my SMS.
I select the "plus" icon that would allow me to add someone but:
either a white screen with a red box appears. Nothing else. Just have to quit and send the text to one person only.
or if I manage to select a second addressee, the white screen with the red box appears.

Expected behavior
I expect to select a additional addressee and open a dialog box. 

Actual behavior
white screen with a red box appears. Instead of sendong one text to several people, I must send several time the same text to several people.

**Comment by UniversalSuperBox** [comment]
Hello @Thieb67k, can you provide more information with this issue? I have no idea what the issue is or how to reproduce it. Please follow [Contribute to Ubuntu Touch - Bug reporting](https://docs.ubports.com/en/latest/contribute/bugreporting.html) to provide the relevant information.

If no further information is provided, this report will be closed on December 10.

**Comment by Thieb67k** [comment]
For unknown reason my description did not appears.
Hope that can help people to solve the problem.
:)

**Comment by james-lyon** [comment]
I have the same problem on

- Device: BQ E4.5
- Channel: Stable
- Ubuntu16.04 (OTA-5)

**Comment by hummlbach** [comment]
Sounds like https://github.com/ubports/ubuntu-touch/issues/844

**Comment by hummlbach** [comment]
So then, don't open a new one. ;-) You can read in #844 that it was fixed recently. If you want you can  try it by switching to devel channel. If you actually find it not working there, please come back and reopen the issue.
