### ISSUE TITLE
Contact on SIM card

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#978]
Description of the feature
Hello, I would like to find out how to copy contacts on my Sim card? I did not find any way to kind of backup my contacts. For example, if I move my sim card to another phone, I cannot find my contacts which appear on Ubuntuphone.
Thank in advance.

- Device: LGE Nexus 4
- Channel: stable
- Build: OTA-5

**Comment by UniversalSuperBox** [comment]
Hello @Thieb67k, can you provide more information with this issue? I have no idea what the issue is or how to reproduce it. Please follow [Contribute to Ubuntu Touch - Bug reporting](https://docs.ubports.com/en/latest/contribute/bugreporting.html) to provide the relevant information.

If no further information is provided, this report will be closed on December 10.

**Comment by Thieb67k** [comment]
For unknown reason my description did not appears.
Hope that can help people to solve the problem.
:)

**Comment by UniversalSuperBox** [comment]
Currently there is only an option to import contacts from the SIM card.

From what I understand, SIM cards do not have much storage and will lose some of the attributes set on your contact. In my opinion, that is at least as bad as not being able to export to the SIM at all, if not worse.

It seems that this functionality is not available in LineageOS or iOS, maybe only in some Android ROMs and "feature phones" today. For that reason, I feel it is acceptable that Ubuntu Touch does not have this functionality.

**Comment by Thieb67k** [comment]
I got that feature on a old android OS (on Xperia J - 2013). That is a pity that is not possible, even if a part of data is not saved but at least name+phone...
In that case, how to backup contacts on ubuntu touch?

**Comment by UniversalSuperBox** [comment]
You can select the contacts by long-pressing on one then pressing the "Share" button in the upper right corner. This will allow you to send a `.vcf` file. It seems this doesn't work with my version of the file manager, but I could send the file through Telegram.
