### ISSUE TITLE
Choppy voice call sound on Pro 5

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#980]
### Illustrations

- Device: Turbo
- Channel: RC
- Build: W48

### Steps to reproduce
Make or receive a phone call in a place where you have good GSM signal

### Expected behavior
Good or at least decent sound quality of the call

### Actual behavior
Sound is very choppy and drops out, sometimes completely. The other party complains about not hearing me good and I get the same choppy behaviour at my end of the call. Same thing with mobile data on or off. 

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2640768/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2640769/UTlogcat.txt)

I tried my SIM card in my OPO with the latest xenial RC build and call quality was good. I reflashed my Pro 5 with the wipe option and popped the SIM card back in, and unfortunately the problem seems to persist. As there was a fix for [this issue](https://github.com/ubports/ubuntu-touch/issues/861) recently and this problem started recently (I think after the latest RC or the one before that) I have a suspicion the issues might be related.

**Comment by matv1** [comment]
I can confirm that I got complaints of bad quality voice-call on the other end of my phone conversation today. it was described as 'echo-y', not so much choppy. 
Meizu Pro 5 on RC 16.04
I shall try and test more.

**Comment by UniversalSuperBox** [comment]
@mariogrip, I think you have a Pro 5. Can you check on this?

**Comment by tomoqv** [comment]
I believe I had a lengthy phone call without the other party complaining just before upgrading to the latest RC, so it seems to be something in the latest build that causes this issue.

**Comment by hummlbach** [comment]
@tomoqv can you please check whether the quality is better with mobile data disabled?

**Comment by tomoqv** [comment]
Mobile data was disabled after the reflash and voice quality wasn't better. I will try once more to disable, but I doubt it will make any difference.

**Comment by tomoqv** [comment]
Ok, I have tried today again with mobile data switched off. Same problem (if not worse) in 3 different phone calls. The sound is reported as "extremely choppy" by the other party.

Here is also the log for the dialler app: http://paste.ubuntu.com/p/sC82GDh4cy/

**Comment by hummlbach** [comment]
I updated the radio firmware also right after updating to xenial. Not sure if that could help after all... but maybe you want to give it a try: https://forums.ubports.com/topic/929/update-meizu-pro-5-baseband

**Comment by tomoqv** [comment]
@hummlbach The thread you are referencing is a bit old and ends with the author saying "It has been a while with no update here on my side, i do not consider the Pro5 usable anymore..."

Have you tried this recently and are you not having any issues with voice call quality?

**Comment by hummlbach** [comment]
I updated the firmware recently. Mobile data connection is more stable for me with the update. Regarding voice calls I have the same issues as ever: I have to disable mobile data times to b

**Comment by tomoqv** [comment]
I haven't noticed any problems with mobile data, just voice calls, which stopped working with the latest RC. I am reluctant to upgrade firmware as this seems far from sure to make any difference with voice calls. Something broke in the last release. I am just hoping we will find what it is.

As soon as there is something to test, I will pop my SIM card back in the Pro 5 and try.

**Comment by hummlbach** [comment]
Yes you're right maybe unlikely. Just searched for differences, since I'm on RC with my pro 5 too and I didn't change its behavior ragearding voice quality at all... its just as good or as bad as it always have been since Canonicals times. So maybe we have different revisions but at the end I think simething else is causing this and not the latest RC update. What about going back to previous RC for making it really doesn't happen with that too in the meanwhile for some other reasons...

**Comment by tomoqv** [comment]
I just switched to the devel channel, so I will put my SIM back in and try now when the working day is over.

**Comment by hummlbach** [comment]
I would be interested in stable channel not devel... to be really really sure its caused by some changes made for ota6... so please test stable and that is really fine flash devel and check whether that is still bad. Make at least 20 calls ;-)

**Comment by tomoqv** [comment]
Ok ok, but first call on devel sounded OK according to the receiving end :).

**Comment by hummlbach** [comment]
Now ota6 is out and flashing stable will take you to RC basically ;-) going back to the state before RC just became slightly more complicated...

**Comment by tomoqv** [comment]
Yes, I figured, so I will stay on devel as long as the Pro 5 is usable as a phone.

**Comment by tomoqv** [comment]
This is, indeed, a tricky issue. I am on devel now and audio seems to work OK at times, but I still get what appears to be an extremely bad reception quite often and the person at the other end of the call says "It is really difficult to hear you". At those instances, audio gets cut out (choppy) and comes and goes for me too. I will try to determine if there is a difference depending on who initiates the call.

**Comment by tomoqv** [comment]
I should add that I upgraded the firmware as suggested by @hummlbach above, but I haven't been able to test it enough to see if it actually makes a difference.
