### ISSUE TITLE
Back button not working in OPO

### ISSUE THREAD

**Issue by uma-hs** [ubports/ubuntu-touch#981]
### Illustrations

- Device: OnePlusOne
- Channel:
- Build: Latest Build

### Steps to reproduce

Back Button and Home Button doesn't work.

**Comment by UniversalSuperBox** [comment]
The hardware buttons are not used on any device. This is by design with the device gestures. The buttons at the bottom of the screen could easily interfere with swipe-up gestures in most apps.

**Comment by uma-hs** [comment]
So how do i go back/home if i am in between some app?

**Comment by UniversalSuperBox** [comment]
After opening an app for the first time, the tutorial should appear. Perform a long swipe from the left of the screen to go home. Perform a long swipe from the right of the screen to open the app switcher. Perform a short swipe from the right of the screen to switch between the two most recently used apps.

**Comment by eMPee584** [comment]
> The hardware buttons are not used on any device. This is by design with the device gestures.

Can this please be changed for us folks who don't like gesture navigation too much? :sweat_smile:
