### ISSUE TITLE
Can't log in to websites protected with htpasswd

### ISSUE THREAD

**Issue by dominalien** [ubports/ubuntu-touch#989]
- Device: vegetahd
- Channel: rc
- Build: 2018-W48

### Steps to reproduce
1. Open Morph Browser
2. Go to a website protected with .htpasswd
3. In the box that appears, tap in the username field

### Expected behavior
The keyboard slides out, I type in the username, then tap on the password field and type that in

### Actual behavior
As the keyboard slides out from the bottom of the screen, the box slides upwards until only the very bottom appears on the screen. I can type in the user or password (depending on which field I tapped on), but I cannot tap on the other field to complete the log in.

**Comment by UniversalSuperBox** [comment]
This issue is tracked in ubports/morph-browser#52

**Comment by UniversalSuperBox** [comment]
As a workaround, the keyboard can be dismissed by swiping down on it. This will allow you to select the Password field.
