### ISSUE TITLE
Nexus 4 mako Linux kernel modules not working since 16.04 OTA-5 : crypto function based features stopped working

### ISSUE THREAD

**Issue by chriscroome** [ubports/ubuntu-touch#996]
The `mako` kernel has very few ciphers:

```bash
grep name.*aes /proc/crypto|cut -d : -f 2
 cbc(aes)
 aes
```

This means that LUKS encrypted disks can no longer be opened, see the [report I posted to the the UBports forum](https://forums.ubports.com/topic/1954/16-04-ota-5-kernel-missing-aes-xts-plain64-crypto-ciphers-on-mako).

**Comment by APokorny** [comment]
Many of the crypto lib features are modules and are available .. the mod tools just seem to look at the wrong location.

**Comment by APokorny** [comment]
There was an error in the kernel version configuration and the modules did not match anymore

**Comment by UniversalSuperBox** [comment]
Should be fixed in the newest devel image with @APokorny's upload of the device image: https://gitlab.com/ubports/community-ports/mako
