### ISSUE TITLE
Cannot share contact

### ISSUE THREAD

**Issue by kwah-gh** [ubports/ubuntu-touch#998]
- Device: krillin
- Channel: 16.04 / rc
- Build: 2018-w48

### Steps to reproduce
Go to Contacts
Select contact
Share... via Messaging
In "To:" field of messaging app press "+" to add recipient
Use search functionality to narrow down the list
Try to add actual recipient using "double tap" (as it works in the full contacts list, actually I discovered this by accident)

### Expected behavior
Recipient added in "To:" field of messaging app.

### Actual behavior
Contact details view is activated

**Comment by Thieb67k** [comment]
I have the same issue with LGE Nexus 4 on OTA-6.

**Comment by LlamasJM** [comment]
Same issue. Fairphone 2. OTA-6. Really horrible app: impossible share contacts, impossible search contacts, impossible add contacts to "personal". And I need it...

**Comment by aretzlaff** [comment]
I cannot reproduce this issue (Device: bacon; Channel: Dev; Build: 2018-12-16).

Following your steps, double tapping adds the first telephon number saved within the selected contact. Tapping the selected contact once opens the contact details (as described). I now can select which telephon number I want to use e.g. "Home" or "Mobile". In my opinion that makes sense.

**Comment by lduboeuf** [comment]
reproduced once on N5 last devel version (2018-12-17). Now a simple touch event on Contact Phone number leads me to a blocked screen "contact export". I will put the screenshot while back to wider screen ( can't upload file with mobile on Github)

**Comment by lduboeuf** [comment]
![screenshot20181217_232652231](https://user-images.githubusercontent.com/11663835/50120331-73377200-0255-11e9-945a-ad20216932c5.png)

**Comment by Danfro** [comment]
Cant't confirm on my E5 RC 16.04 2018-W51. I can select a contact and send SMS. 

Only the SMS did not get pushed trough.
Just checked it is not send as SMS but as MMS.
And from what I know there seems to be problems with MMS ([issue, MMS, open](https://github.com/ubports/ubuntu-touch/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mms)).
So sharing with messaging is not really an useful option. :-(

**Comment by lduboeuf** [comment]
To test:
Create a new message
In "To:" field of messaging app press "+" to add recipient
select a contact
-> it should now populate the recipients bar

Contact view is still possible by swipping left on the contact

**Comment by ivoxavier** [comment]
Tested the steps duboeuf said and it worked on the FP2.

Info:
channel: devel
version: 16.04 (2021-12-16)
